### ISSUE TITLE
Polish settings-sync UI

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#100426]
### UX
- [x] Sync: provide better progress information when sync is turning on #100411
- [x] Sync commands are undiscoverable #100425
- [x] :runner: UX: Improve first time sync user experience #100346
- [x] :runner:Synced data view is overwhelming #100347
- [x] Sync should allow you to replace synced data #100791
- [x] Use the same "sync" terminology across the product and docs #100315 
- [x] Skip sync configure dialog when re-enabling sync #100336 

### Bugs
- [x] Closing browser when Settings Sync starts leaves app in broken state #100314
- [x] Turning on sync from an old device fails #100348
- [ ] Extensions list doesn't auto-update when sync is installing extensions #100415
- [x] Synced data shows entries with no changes #100416
- [x] Restoring extensions data from synced view shows wrong data #100448

cc @RMacfarlane @Tyriar

**Comment by sandy081** [comment]
Moving this to next milestone as most of the requests will be handled then.
