### ISSUE TITLE
August Iteration Plan

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#10145]
## Endgame Schedule
- *August, 29th* Code freeze for the endgame
- *September, 2nd* Endgame done

##### Monday
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms **@kieferrm**
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT

##### Tuesday
- [x] Test build starts at 7am CET / 10pm PT on Monday
- [x] Test plan ready by 8am CET / 11pm PT on Monday
- [x] Testing

##### Wednesday
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the August milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)

##### Thursday
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] Add/update shrink-wrap files for built-in extensions if needed (see [instructions](https://github.com/Microsoft/vscode/issues/8570#issuecomment-229669456)) **@dbaeumer**
- [x] Update `OSSREADME.json` for built-in extensions based on differences to generated `npm-shrinkwrap.json` files if needed **@dbaeumer**
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **@dbaeumer**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **@dbaeumer**

##### Friday
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
- [x] Translation input - **@dbaeumer**
- [ ] Verification: since there are quite some old bugs to verify we decided to verify by age, youngest first. The queries we used are:
    - [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
    - [x] [August Bugs](https://github.com/Microsoft/vscode/issues?page=1&q=is%3Aissue+label%3Abug+-label%3Averified+is%3Aclosed+-label%3Aduplicate+-label%3Ainvalid+closed%3A%3E%3D2016-08-01&utf8=%E2%9C%93)
    - [ ] [July Bugs](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abug%20-label%3Averified%20is%3Aclosed%20-label%3Aduplicate%20-label%3Ainvalid%20closed%3A%222016-07-01%20..%202016-08-01%22%20)
    - [ ] [June Bugs](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abug%20-label%3Averified%20is%3Aclosed%20-label%3Aduplicate%20-label%3Ainvalid%20closed%3A%222016-06-01%20..%202016-07-01%22%20)
    - [ ] [May Bugs](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abug%20-label%3Averified%20is%3Aclosed%20-label%3Aduplicate%20-label%3Ainvalid%20closed%3A%222016-05-01%20..%202016-06-01%22%20)
    - [ ] [April and Before](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abug%20-label%3Averified%20is%3Aclosed%20-label%3Aduplicate%20-label%3Ainvalid%20closed%3A%22*%20..%202016-05-01%22%20)
- [ ] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - **@alexandrudima**
  - [x] OS X - **@isidorn**
  - [x] Linux - **@aeschli**
  - [x] Windows - **@roblourens**
  - [x] OS X - **@octref**
  - [x] Linux - **@rebornix**
- [ ] All release notes updated. Release notes are collected in a file named *`1_5.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
    - [x] @alexandrudima 
    - [x] @weinand 
    - [x] @bpasero 
    - [x] @chrmarti 
    - [x] @tyriar 
    - [x] @dbaeumer
    - [x] @egamma 
    - [x] @isidorn 
    - [x] @joaomoreno 
    - [x] @jrieken 
    - [x] @kieferrm 
    - [x] @aeschli 
    - [x] @rebornix 
    - [x] @octref 
    - [x] @ramya-rao-a 
    - [x] @roblourens 
    - [x] @sandy081
- [ ] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. **@all**
    - [x] @alexandrudima 
    - [x] @weinand 
    - [x] @bpasero 
    - [ ] @chrmarti 
    - [x] @tyriar 
    - [x] @dbaeumer
    - [x] @egamma 
    - [x] @isidorn 
    - [x] @joaomoreno 
    - [x] @jrieken 
    - [ ] @kieferrm 
    - [x] @aeschli 
    - [x] @rebornix 
    - [x] @octref 
    - [ ] @ramya-rao-a 
    - [x] @roblourens 
    - [x] @sandy081
- [ ] Mention notable fixes in the release notes:
    - [x] @alexandrudima 
    - [x] @weinand 
    - [x] @bpasero 
    - [ ] @chrmarti 
    - [x] @tyriar 
    - [x] @dbaeumer
    - [x] @egamma 
    - [x] @isidorn 
    - [x] @joaomoreno 
    - [x] @jrieken 
    - [x] @kieferrm 
    - [x] @aeschli 
    - [ ] @rebornix 
    - [x] @octref 
    - [ ] @ramya-rao-a 
    - [x] @roblourens 
    - [x] @sandy081

##### Friday/Monday
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually (Friday: @kieferrm, Moday: **@dbaeumer**)
- [x] Pause scheduled `insider` builds  (Friday: @kieferrm, Moday: **@dbaeumer**)
- [x] Branch code to `release/1.5 (Friday: @kieferrm, Moday: **@dbaeumer**)
- [x] Announce master is open for business (Friday: @kieferrm, Moday: **@dbaeumer**)
- [x] Polish release notes **@aweinand**

##### Monday/Tuesday
- [x] Publish `Insider` with hand-picked and reviewed candidate fixes **@dbaeumer**

##### Thursday/Friday
- [x] Build stable for all platforms **@dbaeumer**
- [x] [Smoke test](https://github.com/Microsoft/vscode/wiki/Smoke-Test) stable build (commit: 4fc690be31)
  - [x] Windows - **@dbaeumer**
  - [x] OS X - **@roblourens**
  - [x] Linux - **@weinand** (pls also see dep package item below)
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@dbaeumer**
    - [x] zip **@dbaeumerr**
  - [x] Linux
    - [x] deb package 64-bit **@weinand**
    - [x] deb package 32-bit **@tyriar**
    - [x] rpm package 64-bit **@tyriar**
    - [x] rpm package 32-bit **@tyriar**
    - [x] archives **@tyriar**
- [x] Publish website **@gregvanl**
- [x] Release [stable](https://vscode-builds.azurewebsites.net/stable) (commit: 4fc690be31) **@kieferrm**
- [x] Add a git tag to `HEAD` of `release/1.5` in format `1.5.z` **@kieferrm**
- [ ] Twitter announcement **@seanmcbreen**
- [ ] Enable scheduled `insider` builds **@dbaeumer**

##### 1.5.x
- [ ] Merge translations **@dbaeumer**
- [ ] Rebuild for all platforms **@dbaeumer**

## General

This plan captures what we work on during August. We will ship **early September**.
This is a **5 week** iteration compared to our usual 4 week iterations.
This release will be **fully translated** you will see that reflected in our endgame schedule. We will hold back making the stable release available until we have all trandslations.

## Vacation/Off time
Several of us who have not yet been on vacation are out on average 1-2 weeks. Thus, team members show up with different loads.

## Plan Items

| Mark  | Description |
| ------------- | ------------- |
| :runner:  | work in progress  |
| :hand:  | blocked task |
| :muscle:  | stretch goal for this iteration  |

### Feedback
- [x] Support Intellisense in the Debug Console #8114 @weinand @isidor
    - Test #10997
    - [x] Release notes
- [x] Emmet: Enable emmet for other file extensions #9500 @egamma
  - Test #11139
  - [x]  Release notes
- [x] Support file icons in explorer #10294 @aeschli @bpasero
- :runner: Continue on `Quick Open` performance #55 @chrmarti @bpasero
   - Test #11035
   - [x] Release notes 
- [x] Add a setting to control Angular-1 tag completion proposals when editing HTML #9797 @aeschli
  - [x] Release notes

### Extension Contributions
- :runner: **VIM**: Continue to increase command coverage (see [VIM extension roadmap](https://github.com/VSCodeVim/Vim/blob/master/ROADMAP.md)) @rebornix
    -Test #11147
- :runner: **Go**: Help managing issues @ramya-rao-a
- **ESLint**, **TSLint**, and **jsHint**: Regular maintenance @dbaeumer @egamma @kieferrm
  - [x] lint on save option
  - :runner: support to configure location of the linter module
    - Test #11100
- [x] **Language Server Protocol** and SDK: Regular maintenance @dbaeumer

### API Improvements for Extensions
- VIM: Continue to work on the API gaps backlog (see #8997) including
         - Test #11147
	- [x] Window/page scroll commands #9609 @sandy081
	- [x] More API to control folding, navigation with folding #9786 @aeschli @sandy081
	- [x] Expose Undo history #8096 @alexandrudima
	- [x] Add reason to selection change event #8093 @jrieken
- Language API
  - [x] Enable more efficient Workspace Symbol Provider by making the offset resolution lazy #890 @jrieken
      - Test #11113
  - [x] Support multiple edits for a completion item allowing languages such as Java and C# to automatically add imports #6874 @jrieken
     - Test #11111
- Terminal 
  - [x] Expose API to run a command in the terminal #9957 @Tyriar
      - Test #11133
- Extension doc 
  - [ ] Add the Language Extension Checklist to our docs @kieferrm

### Engineering
- [x] Debt: Refactor editor action/command enablement @alexandrudima 
- [x] Add coverage reports to the VS Code builds @alexandrudima 
- [x] API - Support programmatic cancellation of quick box @jrieken
    - Test #11110
- [x] Debt: Suggest support, handle incomplete result sets and cleanup.
- [x] Configuration settings - refactor the service to enable write access as an API #8937 @bpasero
    - Test #11023
- [x] Editor - extract more colors defined by the editor as custom settings in themes #11095 @sandy081
  - Test #11126
  - [x] Release notes
- [x] Electron investigate into adoption of latest version #10206 @bpasero
  - we will not switch to a new version of Electron in August
- Extensions:
  - [x] Adopt the installation performance improvements from the Market place #10180 @joaomoreno
  - [x] Extension details view: show more information about an installed extension  #10366 @joaomoreno
    - Test #11118
  - [x] Provide command to update all out of date extensions #8124  @joaomoreno
     - Test #11119
  - [x] Support other sorting orders in the extensions viewlet #8022 @joaomoreno
     - Test #11120
  - [x] Provide an option to automatically update outdated extensions @joaomoreno
     - Test #11119
- Debug:
  - [x] incorporate debug protocol additions [backlog](https://github.com/Microsoft/vscode-debugadapter-node/issues?q=is%3Aissue+is%3Aopen+label%3A%22protocol+extension%22+milestone%3A%22August+2016%22) @weinand
    - [x] support for intellisense https://github.com/Microsoft/vscode-debugadapter-node/issues/48
       - Test #10997
    - [x] support for launching debuggee in VS Code terminal https://github.com/Microsoft/vscode-debugadapter-node/issues/47
    - [x] Release notes
  - [x] Implement debug target launching in integrated terminal #10574 @isidorn @weinand
    - Test #11091
    - [x] Release notes
  - [x] Node debugging - continue investigate into supporting/switching to the Chrome Debugger Protocol that comes with node 7.0 https://github.com/Microsoft/vscode-node-cdp-debug/issues/1 @weinand
  - [x] Multi line debug repl input #8115
    - Test #10996
    - [x] Release notes
  - [x] Multi-level chunking of large arrays @isidorn
    - Test #10995
    - [x] Release notes
- Integrated Terminal - Continue to work on the Integrated Terminal backlog #9959 @Tyriar. This includes
	- [x] Add scroll bar to integrated terminal #6602
             - Test #11134

### Feedback Channels
- Error telemetry (managed in VSTS) @ramya-rao-a, @mjbvz
	- [x] Improve performance and fix timeout issue
	- [x] Filter out extension errors, but keep errors from built-in extensions
	- [x] Source map support
	- First steps on
		- [x] Define process for how to digest them
		- [x] web site improvements
- Telemetry @ramya-rao-a, @mjbvz
     - [x] Event completion tests
     - [x] Pipeline tests
- Power BI Dashboards
     - :runner: Explore BigQuery as a source instead of SQL @mjbvz
     - :runner: Improve data refresh times by improving SQL queries @ramya-rao-a

### UX 
- :runner: Design for horizontal editor layout support #1749 @stevencl @bgashler1  @bpasero
- :runner: How to preview complex refactorings (e.g. for Python) @stevencl

### Deferred
- Settings -  Add API to change a user setting.  #1396 @jrieken _additional requirements have emerged, e.g, to also support changing launch.json programmatically (see next item). We need more time to cover this requirement and come up with an API that we are confident with_
- :hand: Debug - API support to participate in launch.json generation #9061 @isidorn _see previous item_
- Investigate support for composite undo #9897 @jrieken @alexandrudima _we will start with a spec_
- :hand: Show release notes in product #10179 @joaomoreno _we have an implementation that fetches the release notes from github, which has the throtteling issue. Plan is to fetch the release notes from the web site. This requires changes to the website_
- :hand: VIM extension - improve support for the '.' command _need to clarify the requirements_
- HTML as extension #8938 @aeschli _not ready yet to replace the current implementation_
- :hand: Initial exploration of supporting nested languages. First step is CSS and JS in HTML files such as #8928.  @aeschli _depends on HTML as extension #8938, which didn't finish_
- :hand: Explore open/install an extension from the Market Place #10340 @joaomoreno _url handler is in place, needs to be exposed in the market place_
- :hand: TypeScript: incremental builder @dbaeumer _depends on adoption by the TS team, work is currently deferred_
- Debug - Debt add globbing support for the `outdir` attribute in the launch config. _work is done, change is risky, will be released to insiders early in the September milestone_
- :hand: TypeScript: Adopt TypeScript 2.0 #10136 @dbaeumer _TS 2.0 will not be available in August _
- :hand: Backspace, left and right in Windows integrated terminal cause prompt to go out of sync #7345 _Originally we had issues to reproduce the problem. We now found that this only happens in the `bash` on Windows which lowers its priority._

**Comment by leaxoy** [comment]
#10188   change **`command+<number>`** key behaviors.

**Comment by glen-84** [comment]
> Explore extended workbench support for UI themes that may include custom file explorer icons. #?????

* [Add file icons support in the explorer](https://github.com/Microsoft/vscode/issues/211) 
* [Add some API to support GUI customization](https://github.com/Microsoft/vscode/issues/1833)
* [Support to theme the entire workbench](https://github.com/Microsoft/vscode/issues/3112)

Related: #459, #1884.

**Comment by mouhong** [comment]
Is it possible to add antialias support for the editor and the file tree? This will improve editing experience a lot (Atom, Sublime and PHPStorm all supports it). And it's quite simple, just need to add following css in the main css file (I have to do it manually currently)
```
.monaco-editor {
    -webkit-font-smoothing: antialiased;
}
```

**Comment by glen-84** [comment]
@mouhong This issue is not the place for feature requests.

**Comment by egamma** [comment]
@niieani thanks for the kind comment. I'll make sure that it is shared with the entire team.

**Comment by egamma** [comment]
1.5 has been shipped - closing
