### ISSUE TITLE
Iteration Plan for July 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#102174]
This plan captures our work in **July**. We will ship in **early August**. This is a 5-week iteration and it includes the Microsoft-wide Hackathon on July 27-29. Also, this is the start of the vacation season (July-August) and although not a lot of traveling is happening, our team still takes time off.

## Endgame
- **August 3rd, 2020**: Endgame begins
- **August 7th, 2020**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/103792.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |
| :black_large_square:| a large work item, larger than one iteration      |

### Accessibility
- [ ] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22July+2020%22) **team**
- [ ] :runner: Revisit navigation model of the settings UI https://github.com/microsoft/vscode/issues/97567 @9at8
- [x] Community call (July 23rd) https://github.com/microsoft/vscode/issues/102832 @sana-ajani @isidorn

### Workbench
- [x] Manual Settings Sync UI https://github.com/microsoft/vscode/issues/100426 @misolori @sandy081
- [ ] :runner: Use encrypted keychain for account management https://github.com/microsoft/vscode/issues/95475 @rmacfarlane @sbatten
- [ ] Undo/redo of workspace edit file operations, support linked undo operations, https://github.com/microsoft/vscode/issues/101789 @alexdima @jrieken
- [x] First run experience: Support initial view state for Custom Views https://github.com/microsoft/vscode/issues/101283 and move the NPM Script Explorer to the `View` menu @alexr00
- [x] First run experience: Simplify Extensions `View` menu https://github.com/microsoft/vscode/issues/100756 @sandy081
- [x] Use shadow DOM for custom context menu to preserve editor focus https://github.com/microsoft/vscode/issues/98673 @sbatten

### Tasks
- [ ] :runner: :muscle: Expose variable resolvers for `CustomExecution` tasks https://github.com/microsoft/vscode/issues/81007 @alexr00

### Notebook Editor
- [x] Support for interrupting cell execution https://github.com/microsoft/vscode/issues/99203 @roblourens
- [x] Consolidate kernel support https://github.com/microsoft/vscode/issues/101963 @rebornix
- [ ] :red_circle: Collaborate with language teams on notebook support @jrieken
- [x] Explore notebook webview crash https://github.com/electron/electron/pull/24344 @rebornix @deepak1556
- [x] Provide automated fuzzy tests for finding notebook layout issues https://github.com/microsoft/vscode/issues/102541 @roblourens
- [x] Polish notebook behavior [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Anotebook+milestone%3A%22July+2020%22+label%3Apolish) @roblourens @rebornix
- [x] Support Jupyter-like cell folding https://github.com/microsoft/vscode/issues/100308 @roblourens @misolori
- [x] Support splitting/joining of all cell types https://github.com/microsoft/vscode/issues/102504 @rebornix
- [x] Provide editor inspired keybindings for cell operations out of the box https://github.com/microsoft/vscode/issues/101436 @rebornix
- [ ] :runner: Revise the renderer API surface (extension host and webview context) and `package.json` entry points https://github.com/microsoft/vscode/issues/102644 @connor4312
- [ ] Explore tabular variables debug view requirements https://github.com/microsoft/vscode/issues/100205 @weinand
- [x] Investigate into API gaps to support notebook diffing https://github.com/microsoft/vscode/issues/94810 @rebornix
- [x] Investigate into API gaps to support Liveshare for notebooks https://github.com/microsoft/vscode/issues/102503 @rebornix

#### LSP / LSIF
- [ ] :runner: Towards LSP version [3.16](https://github.com/microsoft/language-server-protocol/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.16) @dbaeumer
- [x] Stabilize the [LSIF TypeScript indexer](https://github.com/Microsoft/lsif-node/issues) @dbaeumer

#### TypeScript/JavaScript
- [ ] Get ready for adopting TS 4.0 https://github.com/microsoft/vscode/issues/102919 @mjbvz

### Debug
- [ ] :runner: Address self-hosting debugging pain-points https://github.com/microsoft/vscode/issues/100368 @connor4312
- [ ] :runner: Improve inline value https://github.com/microsoft/vscode/issues/101797 @weinand
- [x] Expose a `stopDebugging` API https://github.com/microsoft/vscode/issues/101883 @weinand
- [x] Investigate exposing DAP IDs of breakpoints in the vscode API https://github.com/microsoft/vscode/issues/99716 @weinand
- [ ] :muscle: Investigate issues introduced by the Web UI stopped indication https://github.com/microsoft/vscode/issues/100757 @weinand @isidorn

### SCM
- [x] Simplify the Git '...' menu and introduce submenus https://github.com/microsoft/vscode/issues/102109 (requires https://github.com/microsoft/vscode/issues/100172) @joaomoreno
- [x] Offer to create fork if user has no commit rights on GitHub repository https://github.com/microsoft/vscode/issues/102393 @joaomoreno
- [x] Make the GitHub repository picker available to other extensions https://github.com/microsoft/vscode/issues/102394 @joaomoreno

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2020%22+label%3A%22api-proposal%22)

### Extensions
- [ ] :muscle: Provide guidelines for extension authors how to consume the GitHub authentication provider https://github.com/microsoft/vscode/issues/100995 @rmacfarlane

### Extension Contributions
- [ ] :runner: Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/3347 **team**
- [x] Improvements to the GitHub PR and Issues extension, see [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+assignee%3Aalexr00+milestone%3A%22July+2020%22) @alexr00
- [ ] :runner: Improvements to the Hex editor extension https://github.com/microsoft/vscode-hexeditor/issues/76 @lramos15

### Install
- [ ] :runner: Explore `msix` installer for VS Code on Windows https://github.com/microsoft/vscode/issues/61793 @sbatten
- [ ] Improve existing Windows installer https://github.com/microsoft/vscode/issues/102594 @lszomoru @joaomoreno
- [x] Windows - add meta data for the uninstaller https://github.com/Microsoft/vscode/issues/73805 @joaomoreno

### Engineering
- [x] Improve experimentation service https://github.com/microsoft/vscode/issues/102620 @sbatten

### Bots
- [ ] :hand: Make issue triaging extension available in browser store(s) https://github.com/microsoft/vscode-github-triage-extension/issues/2 @jacksonkearl

### Electron
- [ ] :hand: Upgrade to electron 8/9 https://github.com/microsoft/vscode/issues/100731 @deepak1556

### Node.js-free, sandboxed renderer :black_large_square:
Backlog: https://github.com/microsoft/vscode/issues/92164
- [x] Support for encodings in sandboxed/web environments (`iconv-lite`, `jschardet`) https://github.com/microsoft/vscode/issues/79275 @bpasero
- [x] https://github.com/microsoft/vscode/issues/101850 add perf marks for web, enable perf view editor for web @jrieken
- [x] Remove dependency on node for startup path https://github.com/microsoft/vscode/issues/98682 @deepak1556 @alexdima
   - [ ] Adopt V8 cached data option for browser windows @deepak1556
   - [x] Move off file:// protocol for serving static assets @deepak1556
- [ ] Minimal sandboxed version of the workbench with stubbed services @bpasero @deepak1556
   - [x] Make our bootstrap and preload files ready to run in sandbox and isolated mode @bpasero
- [ ] :hand: Enable `sandbox: true` and `contextIsolation` for some of our windows https://github.com/microsoft/vscode/issues/101834 @deepak1556
   - [x] Issue reporter https://github.com/microsoft/vscode/issues/101833 @rmacfarlane
   - [x] Process explorer https://github.com/microsoft/vscode/issues/101832 @rmacfarlane

### Documentation
- None.

-----
### Deferred Items
- None.

**Comment by AdsonCicilioti** [comment]
Hi guys!

When will we have Settings / Preferences Sync the main release?

**Comment by Tyriar** [comment]
@AdsonCicilioti we're aiming to ship it in stable as part of this version.

**Comment by AdsonCicilioti** [comment]
> @AdsonCicilioti we're aiming to ship it in stable as part of this version.

Thanks @Tyriar!

**Comment by astrowonk** [comment]
Is there a plan to address any of the copious SCM single view feedback in #102118? A lot of us are sufficiently frustrated that we have stayed on 1.46.

**Comment by knynkwl** [comment]
This is the third most commented issue. Can we add this to the here or next patch? https://github.com/microsoft/vscode/issues/519

**Comment by FaiyazMujawar** [comment]
When will v1.48 be released? And, will it be released with the new notebooks UI(not preview, as I cannot use it in stable! ) ?

**Comment by racedaemon** [comment]
Not sure this is the place to report this, but this iteration is missing from Wiki > Project Management > Iteration Plans. Got me scared July was skipped but then I found out on Twitter about the launch party 🎉

**Comment by Tyriar** [comment]
@racedaemon fixed, thanks 🙂

**Comment by nicojmb** [comment]
Hi, "msix" installer will be available in this version?

**Comment by egamma** [comment]
1.48 has shipped - closing
