### ISSUE TITLE
Notebook UX Feedback

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#104772]
This issue is to track the feedback from the [new native notebook experience](https://devblogs.microsoft.com/python/notebooks-are-getting-revamped/). 

## Bugs
- [x] Make Markdown Cells Grabbable #104104
- [x] Add cells above first cell #96446
- [x] Clearing output is unclear/hard to find, add to context menu
- [x] Delete cell action should be at the end #104082
- [x] Improve execution count discoverability on hover/active cells #104680
- [x] Hover state for adding new cells is hard to find https://github.com/microsoft/vscode/issues/104854

## Feature requests
- [x] Make notebook status bar contributable #104958
- [x] User settings for cell toolbar position & status bar visibility
- [ ] Drag and drop for joining cells
- [ ] Multi-select on cells

**Comment by roblourens** [comment]
We have done all the work I plan to do this iteration, so I will close this

**Comment by misolori** [comment]
And here are the two new settings from above:
- `notebook.cellToolbarLocation`
- `notebook.showCellStatusbar`

![image](https://user-images.githubusercontent.com/35271042/91463607-72375000-e840-11ea-8af9-3313fa4c5216.png)
