### ISSUE TITLE
Iteration Plan for August 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#104735]
This plan captures our work in **August**. We will ship in **early September**. This is a 4-week iteration. This iteration falls into our summer vacation season and although not a lot of traveling is happening, our team still takes time off.

## Endgame
- **August 31st, 2020**: Endgame begins
- **September 4th, 2020**: Endgame done

The endgame details for this iteration are tracked in **https://github.com/microsoft/vscode/issues/105745**.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |
| :black_large_square:| a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22August+2020%22) **team**
- [ ] :runner: Revisit navigation model of the settings UI https://github.com/microsoft/vscode/issues/104318 @roblourens @sana-ajani

### Workbench
- [ ] :runner: Use encrypted keychain for account management https://github.com/microsoft/vscode/issues/95475 @rmacfarlane @sbatten
- [x] Explore static registration of authentication providers https://github.com/microsoft/vscode/issues/103507 @rmacfarlane
- [x] Polish rename on type https://github.com/microsoft/vscode/issues/104823 @aeschli
- [x] Support for custom views with WebView contents https://github.com/microsoft/vscode/issues/83911 @mjbvz
- [x] format modified https://github.com/microsoft/vscode/issues/44075 @jrieken

### Editor
- [x] Release a new version of the Monaco Editor @alexdima

### Tasks
- [x] Expose variable resolvers for `CustomExecution2` tasks https://github.com/microsoft/vscode/issues/81007 @alexr00

### Notebook Editor
- [x] Evaluate and respond to early adopter feedback for notebooks (execution counts, stop, clear outputs, ...) https://github.com/microsoft/vscode/issues/104772 @misolori @roblourens
- [x] Renderer API https://github.com/microsoft/vscode/issues/102644 https://github.com/microsoft/vscode/issues/103864 @connor4312
- [ ] :red_circle: :runner: Collaborate with language teams on notebook support @jrieken
- [ ] :runner: API to associate a notebook cell document with its notebook https://github.com/microsoft/vscode/issues/102091 @jrieken
- [x] API for metadata update and output clearing (https://github.com/microsoft/vscode/issues/103713 @roblourens @rebornix @jrieken
- [x] Rework API for cell execution https://github.com/microsoft/vscode/issues/103713 @roblourens @rebornix @jrieken
- [x] Explore UX for notebook diffing https://github.com/microsoft/vscode/issues/99877 @misolori @rebornix @roblourens
- [x] Identify and fill API gaps for Diffing https://github.com/microsoft/vscode/issues/94810 @rebornix
- [ ] :runner: Identify and fill API gaps for Live Share https://github.com/microsoft/vscode/issues/102503 @rebornix

#### LSP / LSIF
- [ ] :runner: Towards LSP version [3.16](https://github.com/microsoft/language-server-protocol/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.16) @dbaeumer
- [ ] :runner: Stabilize the [LSIF TypeScript indexer](https://github.com/Microsoft/lsif-node/issues) @dbaeumer

#### TypeScript/JavaScript
- [X] Adopt TS 4.0 https://github.com/microsoft/vscode/issues/102919 @mjbvz

### Debug
- [x] Support filter in the debug console https://github.com/microsoft/vscode/issues/20838 @isidorn
- [x] Support menu contributions in the Variables view https://github.com/microsoft/vscode/issues/70377 @weinand @isidorn
- [x] Revisit the node auto-attach behavior for js-debug https://github.com/microsoft/vscode-js-debug/issues/703 @connor4312
- [ ] :runner: Improve the inline value support https://github.com/microsoft/vscode/issues/105690 @weinand

#### DAP

Investigations for:
- [x] Support for indicating custom debug focus change https://github.com/microsoft/debug-adapter-protocol/issues/128  @weinand
- [ ] :runner: Support object IDs https://github.com/microsoft/debug-adapter-protocol/issues/134  @weinand

### SCM
- [x] Address pain points of new SCM View https://github.com/Microsoft/vscode/issues/104151 @joaomoreno

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2020%22+label%3A%22api-proposal%22)

### Extensions
- [x] Show Extension recommendation when the user switches the language mode https://github.com/microsoft/vscode/issues/102823 @sandy081

### Extension Contributions
- [x] Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/3523 **team**
- [x] Improvements to the GitHub PR and Issues extension, see [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22August+2020%22+) @alexr00 @rmacfarlane

### Engineering
- [ ] :runner: Make VSCode [Trusted Types](https://w3c.github.io/webappsec-trusted-types/dist/spec/) compliant https://github.com/Microsoft/vscode/issues/103699 @jrieken and **team**
- [x] Azure DevOps - test improvements https://github.com/Microsoft/vscode/issues/103814 @lszomoru

### Bots
- [x] Make issue triaging extension available in browser store(s) https://github.com/microsoft/vscode-github-triage-extension/issues/2 @jacksonkearl

### Electron
- [x] Upgrade to electron 9 https://github.com/microsoft/vscode/issues/100731 @deepak1556
- [ ] :muscle: Investigate exploration builds for Apple Silicon https://github.com/microsoft/vscode/issues/104780 @deepak1556

### Node.js-free, sandboxed renderer
- Backlog https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556
   - [ ] Remove dependency on node for startup path https://github.com/microsoft/vscode/issues/98682 @deepak1556 @alexdima
     - [ ] :hand: Electron 9: adopt V8 cached data option for browser windows @deepak1556
     - [x] move off file:// protocol for serving static assets @deepak1556
   - [x] Minimal sandboxed version of the workbench with stubbed services @bpasero @deepak1556

### Documentation
- None.

-----
### Deferred Items
- Undo/redo of workspace edit file operations, support linked undo operations https://github.com/microsoft/vscode/issues/101789 @alexdima @jrieken
- Include `Select Settings Sync Service...` action as part of `Settings Sync: Configure...` https://github.com/microsoft/vscode/issues/104496 @sandy081
- :muscle: Investigate issues introduced by the Web UI stopped indication https://github.com/microsoft/vscode/issues/100757 @weinand @isidorn
- :muscle: Support object favorites https://github.com/microsoft/debug-adapter-protocol/issues/132  @weinand
- :muscle: Improve existing Windows installer https://github.com/microsoft/vscode/issues/102594 @lszomoru @joaomoreno
- :muscle: Rework CLI to allow to use the macOS launch service https://github.com/microsoft/vscode/issues/102975 @deepak1556 @bpasero

**Comment by RayrayCf9** [comment]
Xxxwee7

**Comment by RayrayCf9** [comment]
-
