### ISSUE TITLE
Iteration Plan for September 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#106677]
This plan captures our work in **September**. We will ship in **early October**. This is a 4-week iteration. Heads-up: In October we'll have our annual house-keeping iteration.

## Endgame
- **September 28th, 2020**: Endgame begins
- **October 2nd, 2020**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/107567.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22September+2020%22) **team**
- [x] Revisit navigation model of the settings UI https://github.com/microsoft/vscode/issues/104318 @roblourens @sana-ajani

### Workbench
- [ ] :runner: Use encrypted keychain for account management https://github.com/microsoft/vscode/issues/95475 @rmacfarlane @sbatten
- [x] Undo/redo of workspace edit file operations, support linked undo operations https://github.com/microsoft/vscode/issues/101789 @alexdima
- [x] Pinned tabs polish: support to show more context for a pinned tab https://github.com/microsoft/vscode/issues/98161 @bpasero
- [x] Include `Select Settings Sync Service...` action as part of `Settings Sync: Configure...` https://github.com/microsoft/vscode/issues/104496 @sandy081
- [ ] :runner: :muscle: Explore the concept of Trusted Workspaces https://github.com/microsoft/vscode/issues/106488 @tyriar @lszomoru
- [ ] :runner: :muscle: Investigate predefined file filters search (https://github.com/microsoft/vscode/issues/106790) @jacksonkearl

### UX
- [ ] :runner: Explore possible integrations between extensions view and GH Sponsors https://github.com/microsoft/vscode/issues/107482 @misolori
- [ ] :runner: :muscle: Explore improvements to welcome pages https://github.com/microsoft/vscode/issues/106715 @misolori @jacksonkearl

### Notebook Editor

- [x] API to associate a notebook cell document with its notebook https://github.com/microsoft/vscode/issues/102091 @jrieken
- [ ] :runner: Identify and fill API gaps for Live Share https://github.com/microsoft/vscode/issues/102503 @rebornix
- [ ] :runner: Explore improved UX for kernel management https://github.com/microsoft/vscode/issues/106519 @misolori
- [ ] :runner: Explore API implications for allowing multiple notebook extensions to share the same file format https://github.com/microsoft/vscode/issues/106694 @rebornix @roblourens
- [ ] :runner: https://github.com/microsoft/vscode/issues/106744 Review of the current state of the proposed Notebook API @jrieken **team**

#### LSP / LSIF
- [x] LSP: Add support for [`Codeactions.disabled`](https://github.com/microsoft/language-server-protocol/issues/1093) @dbaeumer
- [x] LSP: Support to defer workspace edit computation for [code actions](https://github.com/microsoft/language-server-protocol/issues/787) (see also https://github.com/microsoft/vscode/issues/106410) @dbaeumer
- [x] Stabilize the [LSIF TypeScript indexer](https://github.com/Microsoft/lsif-node/issues) so that it can index the source of VS Code and its satellite repositories @dbaeumer

#### TypeScript/JavaScript
- [ ] Adopt insider versions of TS 4.1 https://github.com/microsoft/vscode/issues/106702 @mjbvz

### Debug
- [x] Consolidate auto-attach configuration flows https://github.com/microsoft/vscode/issues/105883 https://github.com/microsoft/vscode-js-debug/issues/732 https://github.com/microsoft/vscode/issues/105963 https://github.com/microsoft/vscode/issues/97087 @connor4312
- [x] Explore support for theme colors in the flame graph visualizer for js profiles https://github.com/microsoft/vscode-js-debug/issues/756 @connor4312 @misolori
- [x] :muscle: Explore performance view for js-debug @connor4312 https://github.com/microsoft/vscode-js-debug/issues/755
- [x] Implement the DAP "invalidate" event (refresh Variables view) https://github.com/microsoft/vscode/issues/106745 @isidorn @weinand
- [x] Console polish: show number of filtered console items https://github.com/microsoft/vscode/issues/105866, support to copy all https://github.com/Microsoft/vscode/issues/28094 @isidorn
- [x] Remember dynamic launch configurations https://github.com/microsoft/vscode/issues/96293 @isidorn
- [x] Address "path casing" issues for debug https://github.com/microsoft/vscode/issues/106382 @isidorn
- [x] Investigate how to show the editor hover while debugging https://github.com/microsoft/vscode/issues/84561 @isidorn @weinand

#### DAP
Investigations/reviews for:
- [ ] :runner: Support out-of-scope variables (aka "object IDs") https://github.com/microsoft/debug-adapter-protocol/issues/134 @weinand
- [x] Allow conditional exception breakpoints https://github.com/microsoft/debug-adapter-protocol/issues/137 @weinand

### Testing
- [ ] :runner: Explore how to improve testing support https://github.com/microsoft/vscode/issues/107467 @connor4312 @sandy081

### API
- [ ] :runner: Explore how to support organizing imports on Paste https://github.com/microsoft/vscode/issues/30066 @mjbvz
- [x] Support to resolve code actions https://github.com/microsoft/vscode/issues/106410 (see also https://github.com/microsoft/language-server-protocol/issues/787) @jrieken
- [x] Investigate support for contributing presentations like a Type Hierarchy to the `References View` https://github.com/microsoft/vscode/issues/106929 @jrieken
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2020%22+label%3A%22api-proposal%22)

### Extension Contributions
- [ ] :runner: Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/3669 **team**
- [x] Improvements to the GitHub PR and Issues extension https://github.com/microsoft/vscode-pull-request-github/issues/2134 @alexr00 @rmacfarlane @eamodio
- [x] Improve the eslint security warning dialog https://github.com/microsoft/vscode-eslint/issues/1012 @dbaeumer

### Engineering
- [x] Support ARM/Raspberry Pi Linux https://github.com/Microsoft/vscode/issues/6442 @joaomoreno
- [ ] :runner: Make VSCode [Trusted Types](https://w3c.github.io/webappsec-trusted-types/dist/spec/) compliant https://github.com/Microsoft/vscode/issues/103699 @jrieken and **team**

#### Bots
- [x] Add support for cc-ing contributors when issues are being labeled https://github.com/microsoft/vscode/issues/106682 @jacksonkearl

#### Electron
- [x] Electron 9 follow-up https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron-9-update @deepak1556

#### Node.js-free, sandboxed renderer
- [ ] :runner: Backlog https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556

### Monaco Editor
- [x] Ship a new version of the Monaco Editor - https://github.com/microsoft/monaco-editor/blob/master/CHANGELOG.md#0210-21092020 @alexdima

-----
### Deferred Items
- :red_circle: Improved UI guidelines for custom editors/views @misolori
- LSP: Add support for [rename on type](https://github.com/microsoft/language-server-protocol/issues/1092) @dbaeumer
- Support optional branch selection in the GitHub repository picker https://github.com/microsoft/vscode/issues/106664 @joaomoreno
- :muscle: Settings Sync: View doesn't move when view order is changed on another synced machine https://github.com/microsoft/vscode/issues/93909 @sandy081
- :muscle: Settings UI - support a color picker for color settings @lszomoru https://github.com/microsoft/vscode/issues/106041
- :muscle: Explore notebook keymap support https://github.com/microsoft/vscode/issues/106679 @rebornix @roblourens
- :muscle: Explore extensible markdown rendering for notebooks https://github.com/microsoft/vscode/issues/106701 @mjbvz
- :muscle: Improve the inline value support https://github.com/microsoft/vscode/issues/105690 @weinand
- :muscle: Support object favorites https://github.com/microsoft/debug-adapter-protocol/issues/132 @weinand
- :muscle: Investigate into installing the Remote-WSL extension out of the box on Windows https://github.com/microsoft/vscode/issues/106759 @joaomoreno @lszomoru
- :muscle: Rework CLI to allow to use the macOS launch service https://github.com/microsoft/vscode/issues/102975 @deepak1556 @bpasero
- :muscle: Stabilize Apple Silicon exploration builds https://github.com/microsoft/vscode/issues/106770 @deepak1556 **team**

**Comment by yubaoquan** [comment]
Since electron support background transparent setting, is there a plan of enabling use to set the background of vscode transparent?

**Comment by Milo123459** [comment]
When tauri becomes stable, do you think VSCode will move to it?
A few perks are that it is very memory efficient, so might be good for the program.
It's planned to become stable around the end of this year.

**Comment by idk-pixel** [comment]
@Milo123459 hey your friend | WhoAboutYT is here!

**Comment by cpoptic** [comment]
Is there a plan to add "execution time" for Jupyter notebook cells?  I've been seeing screenshots of VS Code  notebooks with execution time at the bottom of the cell, but didn't know if this is native in VS Code now or if an extension is required.

If an extension is needed to display notebook cell execution times, which extension is it?  Tthanks

**Comment by nathan130200** [comment]
Since 2016, and #13960 still not fixed... Really?

**Comment by m6502** [comment]
I second @nathan130200 comment. Please, Virtual Space is an important feature for many people. Many of us have been following this project for a long time but don't make a serious use of it because of #13960.

**Comment by nathan130200** [comment]
@m6502 Same. They need fix #13960 with high priority importance!

**Comment by biosmanager** [comment]
@nathan130200 @m6502 I also think virtual space is an essential feature of any text editor and should be implemented with utmost priority!

**Comment by hyiltiz** [comment]
Please support native libsecret or keyutils support on linux so other projects such as Live Share doesn't have to depend on gnome-keyring; many people use XFCE, KDE or something else.
