### ISSUE TITLE
Explore customizing the markdown renderer for notebooks

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#106701]
Explores letting extensions customize the markdown rendering used in notebooks

**Comment by mjbvz** [comment]
## Goals
- Let extensions customize the rendering of markdown cells. The main motivating use case is adding support for rendering LaTeX formulas, although [many other markdown extensions exist](https://www.npmjs.com/search?q=keywords:markdown-it-plugin)
- Allow multiple customizations to our markdown rendering to be enabled at the same time.
- Preferably let extensions reuse existing libraries for customizing markdown rendering (such as markdown it)

## Sketches
Here's my initial thought on how this could be implemented:

1. Add a new `notebookCellRenderer` contribution point:

```ts
"notebookCellRenderer": [
    {
        "id": "notebookMarkdownCellRenderer",
        "displayName": "Notebook Markdown Cell Renderer",
        "target": "markdown"
    }
]
```

This contribution point would let a extension fully replace VS Code's built-in markdown rendering. The API for a cell render would look like this:

```ts
render(markdown: string, /* notebook context */) -> Promise<string> // html output 
```

2. Create a new built-in VS Code extension that uses `notebookCellRenderer` to fully replace VS Code's built-in markdown rendering with a renderer that uses [markdown-it](http://markdown-it.github.io) for rendering

3. Allow this extension to be extended, similar to our existing [markdown extension points](https://code.visualstudio.com/api/extension-guides/markdown-extension).

This would let additional extensions to contribute custom markdown it plugins by building off the extension. This avoids having to load and execute markdown extensions in core


# Open questions

**Do we need to sandbox the rendered markdown?**
The markdown cell content is currently part of the main editor dom. Do we need to instead isolate it with an iframe or sanitize the rendered markdown that comes from an extension? Should we render any cells touched by extensions into the webview instead?

**Should the api be more like the markdownOutputRenderer**
This API is run inside the webview itself. As noted above, our markdown output currently isn't sandboxed at all but it may need to be

/cc @rebornix

**Comment by mjbvz** [comment]
Update on our current plans:

- [Branch with current work](https://github.com/microsoft/vscode/tree/dev/mjbvz/notebook-markdown-renderers)

You can test out the new extensible markdown support by setting `"notebook.experimental.useMarkdownRenderer": true`

### Fully replacing the markdown renderer

The new `notebookMarkdownRenderer` contribution point lets an extension contribute its own markdown render fore notebook cells. This contribution is very similar to an output renderer contribution. The contributed renderer code is run inside the backlayer webview and the rendered markdown is also shown in this webview instead of in the main editor dom like our built-in markdown support

For now, we will restrict this API to our internal extensions. We already have an extension that replaces the notebook's markdown renderer with [markdown-it](https://github.com/markdown-it/markdown-it), which we believe is extensible enough for most common notebook uses. In the future, we may open this API to let external extensions use their own markdown engine too.

### Extending the markdown renderer

Extensions can contribute extensions to the new markdown-it based markdown renderer. Example use cases include adding support for math and emoji in markdown. 

These markdown extensions also come in through the `notebookMarkdownRenderer` contribution point. They also contribute scripts that are run inside the webview. However rather than replacing the markdown renderer, they instead call the `extendMarkdownIt` global function and are given an instance of markdown-it which they can extend.

For now, we plan on including a simple markdown-it math extension in VS Code. In the future, math support may instead come from an external extension, such as Python or even a dedicated math extension. 


# TODO

**Short term**
- [ ] Improve markdown cell drag and drop
- [ ] Make sure links in markdown cells are handled properly
- [ ] Investigate accessibility for markdown cells
- [ ] Make sure new markdown cells don't cause other regressions
- [ ] Use markdown-it as the default renderer for notebooks
 
**Longer term**
- [ ] Move math support out of VS Code (either to python or another extension)
- [ ] Create markdown notebook extensions for other features, such as emoji
    - Should these be part of our existing markdown-preview extensions?
- [ ] Figure out how a notebook tells us which markdown features should/shouldn't be enabled
- [ ] Remove our in-editor rendering once it is no longer needed 

/cc @rebornix @kieferrm

**Comment by rchiodo** [comment]
Math support might be possible with just this?
https://www.npmjs.com/package/markdown-it-latex

**Comment by mjbvz** [comment]
Merged initial API point. Will continue working on this with #116393
