### ISSUE TITLE
Iteration Plan for October 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#108473]
This plan captures our work in **October**. This is a 4-week iteration. We will ship in **early November**. 

As you can see the plan is rather lean as this is our annual house-keeping iteration. You'll see a large number of GitHub issue notifications over the course of this iteration. If you want to track our progress, @lannonbr a while back created this nice website: https://vscode-github-stats.netlify.com/

If you are interested in why we have issue house keeping iterations and in our general philosophy around issue management, then we have this [write-up](https://github.com/microsoft/vscode/wiki/Issue-Grooming) for you.

House-keeping is not the only focus this iteration. We'll also work closely with our partners at GitHub to get GitHub Codespaces in great shape.

**Update**: The work on codespaces is more involved than we originally anticipated. Most of us didn't make the progress that you usually see in our house-keeping iterations.

## Endgame
- **October 26, 2020**: Endgame begins
- **October 30, 2020**: Endgame done

The endgame details for this iteration are tracked in **TBD**.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Housekeeping
- [ ] :runner: Issue/PR Grooming - review, categorization, assignment https://github.com/microsoft/vscode/issues/108472 **team**

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22October+2020%22) **team**

### Workbench
- [x] Use encrypted keychain for account management https://github.com/microsoft/vscode/issues/95475 @rmacfarlane @sbatten
- [ ] :runner: :muscle: Explore the concept of Trusted Workspaces https://github.com/microsoft/vscode/issues/106488 @tyriar @lszomoru

### UX
- [ ] :runner: Explore possible integrations between extensions view and GH Sponsors https://github.com/microsoft/vscode/issues/107482 @misolori
- [ ] :runner: :muscle: Explore improvements to welcome pages https://github.com/microsoft/vscode/issues/106715 @misolori @jacksonkearl
- [x] Make suggest widget resizable https://github.com/microsoft/vscode/issues/29126 @jrieken

### Notebook Editor
- [ ] :runner: Identify and fill API gaps for Live Share https://github.com/microsoft/vscode/issues/102503 @rebornix
- [x] Explore improved UX for kernel management https://github.com/microsoft/vscode/issues/106519 @misolori

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2020%22+label%3A%22api-finalization%22)

### Extension Contributions
- [ ] :runner: Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/3834 **team**

-----
### Deferred Items
- All work that was in-flight end of September. We'll resume that work in early November.

**Comment by wottery** [comment]
-_-
