### ISSUE TITLE
Web: Safari on macOS testing

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#108637]
This is a meta issue for our Safari (macOS) support:

* Major issues
  * [x] Worker extension not working in Safari #108285
  * [x] Editor worker is not included in content security policy #108833
  * [ ] User installed fonts not working https://github.com/microsoft/vscode/issues/83294
* Bug list https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asafari+label%3Abug+-label%3Aios
  * [x] Enter doesn't work after switching away from Settings Editor UI #108821
  * [x] Minimap shadow renders improperly #108822 
  * [x] (Dev) Multi root workspace does not load #108820

Blocked by browser
* Clipboard API not working #106997

**Comment by isidorn** [comment]
I see that most of the issues above have been fixed which is great.
We still have the two issues open, and those are tracked in them, thus I will for now close this issue since I do not think it is bringing any value.

Feel free to reopen if you disagree
