### ISSUE TITLE
Remove shell environment patching in the renderer

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#108804]
Details: https://github.com/microsoft/vscode/issues/106537#issuecomment-710084252

**Today:** The workbench depends on user env to be resolved. Resolving user env envolves spawning a shell and executing the user's init scripts. This can take long.

**Ideally:** The user env is only required for specific features: opening terminals, spawning tasks, spawning extension host. Until it's resolved, many other features should actually work, ie explorer, editor, etc.

Related:

- https://github.com/microsoft/vscode/issues/15452
- https://github.com/microsoft/vscode/issues/108571
- https://github.com/microsoft/vscode/pull/55194
- https://github.com/microsoft/vscode/issues/30847
### Adoption

I made a pass over usages of process environment by looking at:
* direct use of `process.env`
* usages of `IProcessEnvironment`
* clients of `vs/base/parts/ipc/node/ipc.cp` that spawn child processes

Assigning people based on areas and usages. Feel free to remove yourself and your items when this change needs no adoption in your area. 

* [x] **Terminal** @Tyriar @meganrogge 
  * [x] `vs/base/node/shell.ts` @TylerLeonhardt 

* [x] **Debug** @weinand 
  * [x] `vs/workbench/contrib/debug/browser/rawDebugSession.ts`
  * [x] `vs/workbench/contrib/debug/node/debugAdapter.ts` (only runs in EH -> nothing to do) 

* [x] **Tasks** @alexr00 
  * [x] `vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts`
  * [x] `vs/workbench/services/configurationResolver/electron-sandbox/configurationResolverService.ts`

* [x] **Proxy** @chrmarti 
* `vs/platform/request/node/proxy.ts`
* `vs/workbench/services/extensions/node/proxyResolver.ts`

#### Child Processes
* [x] [search](https://github.com/microsoft/vscode/blob/8c2d3b40e16b21ebb9e6bd396dfb02aa785731d6/src/vs/workbench/services/search/node/searchApp.ts#L13-L13) @roblourens 
* [x] [telemetry](https://github.com/microsoft/vscode/blob/ff9fbcb077b097d7ffb074f04f6301476578abc3/src/vs/workbench/contrib/debug/node/telemetryApp.ts#L16-L16) @sbatten

**Comment by bpasero** [comment]
After discussion with @joaomoreno we think this could work:
* we stop replacing `process.env` but keep it as is
* we introduce a new service `IProcessEnvService` that has a single method `env: Promise<typeof process.env>`

The implementation will talk to the `electron-main` side and ask for a merged flat view on the process environment to use:
* if the window was started from the CLI it will be that environment including custom user defined variables
  * we will preserve this environment even when the window changes folders to fix https://github.com/microsoft/vscode/issues/108571
* if the window was started from the UI it will be
  * the shell environment by spawning a shell and getting the variables if the main process was also started from the UI
  * the main process environment (including custom user defined variables from the first launch) if the main process was started from the CLI

**Comment by segevfiner** [comment]
If the first launch of VS Code started from CLI, under let's say some Python virtualenv, then any new window created not from CLI will have that virtualenv applied. That's unlike the case when the first launch of VS Code was from UI, where it would just have the shell environment.

What I'm trying to say is that anything that depends on whatever the first launch happened to be is confusing. It might make more sense for it to only depend on the way the current launch happened, independent of whatever the first launch happened to be. But that's just my two cents, there may be a reason for it that I'm not seeing.

Or maybe that first launch thing is really for when you launch a new VS Code window from another VS Code window, rather then the OS GUI. Maybe it would make more sense to inherit the environment of that window then, instead of the environment of the first launch.

Any work on improving the environment variables situation is more than welcome anyhow.

**Comment by bpasero** [comment]
@segevfiner that could be seen as breaking behaviour though, no? I wonder if we could have a setting that enforces that every window that opens after the first one uses the shell environment and does not inherit the first window environment if that was launched from the terminal.

Nevertheless, that still might need careful explanation as to what happens when you change the folder from within the window. Some users might expect the setting to apply there too and some maybe not.

**Comment by joaomoreno** [comment]
(Unrelated: @segevfiner can you send me a hello email to joao moreno at my company com?)

**Comment by segevfiner** [comment]
> @segevfiner that could be seen as breaking behaviour though, no? I wonder if we could have a setting that enforces that every window that opens after the first one uses the shell environment and does not inherit the first window environment if that was launched from the terminal.
>
> Nevertheless, that still might need careful explanation as to what happens when you change the folder from within the window. Some users might expect the setting to apply there too and some maybe not.

Could be, not sure who may or may not depend on this. I'm just basing this on how I expect it to behave, with each window just taking the environment from whatever way you launch. The first launch thing is really an implementation detail IMHO.

And yeah there is also the case of changing a folder in an existing window as opposed to a new one. You described just preserving the environment the window started with (Unrelated to the first launch), which makes sense.

**Comment by bpasero** [comment]
I just think it could be frustrating to setup a nice environment when you start VSCode from the terminal and then only getting it in the first window. Don't forget that we do potentially restore more than one window on startup, so in that case we cannot just apply the environment only to the first window and treat the others as new window. This would need a lot of careful tweaking to get right and I am not sure it is worth it.

**Comment by segevfiner** [comment]
(Unrelated: @joaomoreno Not sure I follow what that email address is, but you can find my gmail email address on my commits)

**Comment by segevfiner** [comment]
@bpasero There are cases for both behaviours I guess. On restoring a session you indeed want the environment appplied to all the restored windows.

But also imagine keeping VS Code running for a long time then opening a new window and getting some virtualenv from something that you worked on long ago that happened to be the first launch. I think in macOS it might even keep that process/VS Code open even when no windows are open (Not sure it does so currently).

**Comment by alexr00** [comment]
I think this will not be adoptable in the configuration resolver service (used for `${variable}` style variables in various places we have json, including some settings). Variable resolving must remain sync since some settings use it, so I don't see how we could wait for the promise to resolve.

**Comment by bpasero** [comment]
@alexr00 can you clarify what kind of `process.env` the configuration resolver service is using?

**Comment by joaomoreno** [comment]
@alexr00 Couldn't these settings assume the pre-resolved values at first and then emit configuration change events whenever the user shell env gets resolved?

**Comment by alexr00** [comment]
@bpasero one of the possible variables is `${env:<name of whatever environment variable you want>}`.

@joaomoreno it looks like might only be terminal setting that use this. I would need to defer to the settings owners to know if that would be ok.

**Comment by bpasero** [comment]
Since I am not sure we can adopt this in a timely manner, I have meanwhile pushed a couple of changes to `master` to address the biggest pain points. After these changes, the introduction of `IProcessEnvService` will only be a performance fix (in some cases), but not fix any other issues.

* the timeout for resolving the shell environment is back to `10s` (from `3s`) but a warning will be shown to the user when this timeout is hit pointing to some docs (we still have to write) to guide the user into fixing this (via https://github.com/microsoft/vscode/commit/6fdc79d81a90adf7b2d4552c36e2b9fc11462925)
* a new perf metric `ellapsedWaitForShellEnv` is added so that users who see slow startups from resolving shell env can be better identified (via https://github.com/microsoft/vscode/commit/fe65b26426b2ba16b803509a2a1a0fb6ceffd07a)
* the code to resolve and merge shell env has moved into `bootstrap-window.js` and thus will now run in all of our windows (workbench, shared process, issue reporter, process explorer) and the shell config will no longer overwrite the user config (https://github.com/microsoft/vscode/commit/6f3fcd2ce0002ffd876b7b43bff42a912edddaae)
* a second window that was started from a CLI will no longer trigger the shell environment resolution if the first window was started from the UI by taking the second window's environment into account (https://github.com/microsoft/vscode/commit/fb277edc0f2531ca2b9e2b0bb9261b79e5fca4fe)
* the user env of a window will now be preserved even when the window loads a different folder (https://github.com/microsoft/vscode/commit/ff1887be3e07b5d16760376106d6234cad5356a6)

**Comment by tddschn** [comment]
@bpasero Can I set the timeout for resolving the shell environment? 
I'm using a really long and complicated `.zshrc` for interactive login shell so sometimes I need more than 10s to initiate zsh and the env vars including $PATH, and I don't want to remove part of the `.zshrc`.

**Comment by bpasero** [comment]
The idea is that once this issue is resolved, we would not have a timeout at all anymore.

**Comment by bpasero** [comment]
An inventory of areas that would need to adopt this new service:
* Large Components
  * Debug
  * Tasks
  * Terminal
* Libraries
  *  `ipc.cp` (watcher, search, ext host)
  * configuration resolver / variable resolver (mainly used by components above)
  * some `base` libs (`shell.ts`, `processes.ts`)...

**Comment by bpasero** [comment]
### Synopsis

With https://github.com/microsoft/vscode/commit/dbbf2b16882b93f9598c999ca3850802aa1c2a8d there is a new service `IShellEnvironmentService` with a method `getShellEnv(): Promise<IProcessEnvironment>` that will give you exactly what `process.env` is today: a merged environment of the process environment and the shell environment. Going forward, `process.env` will no longer attempt to contain the shell environment of the user unless VSCode was launched from a terminal. As such, if you rely on the shell environment variables to be present, you have to use this new service to get it.

An example adoption is pushed for the extension host (@alexdima fyi) where we want to ensure that anything that happens inside the extension host is still receiving the shell environment even when VSCode was not started from a shell:

https://github.com/microsoft/vscode/blob/dbbf2b16882b93f9598c999ca3850802aa1c2a8d/src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts#L163-L163

Here is a set of rules to understand before jumping to the adoption
* only Linux and macOS need an adoption, Windows is always fine (if you access windows environment variables you don't have to adopt anything)
* processes or code only used in shared process is fine too because we already spawn it with the shell environment [here](https://github.com/microsoft/vscode/blob/01cfa2f8352f129fc922b2a9b3ec938f1bb93f84/src/vs/platform/sharedProcess/electron-main/sharedProcess.ts#L140-L140)
* anything inside extension host is also fine because extension host is spawned with the shell environment [here](https://github.com/microsoft/vscode/blob/dbbf2b16882b93f9598c999ca3850802aa1c2a8d/src/vs/workbench/services/extensions/electron-browser/localProcessExtensionHost.ts#L163-L163)

### Adoption

I made a pass over usages of process environment by looking at:
* direct use of `process.env`
* usages of `IProcessEnvironment`
* clients of `vs/base/parts/ipc/node/ipc.cp` that spawn child processes

Assigning people based on areas and usages

#### Terminal @Tyriar @meganrogge 
* `vs/platform/terminal/node/terminalEnvironment.ts`
* `vs/workbench/contrib/externalTerminal/node/externalTerminalService.ts`
* `vs/workbench/contrib/terminal/node/terminalEnvironment.ts`
* `vs/workbench/contrib/terminal/electron-sandbox/localTerminalService.ts`
* `vs/workbench/contrib/terminal/browser/terminalProcessManager.ts`
* `vs/workbench/contrib/terminal/common/environmentVariableCollection.ts`
* `vs/workbench/contrib/terminal/common/environmentVariable.ts`
* `vs/workbench/contrib/terminal/browser/terminalProcessManager.ts`
* `vs/workbench/contrib/terminal/common/terminalEnvironment.ts`
* `vs/platform/terminal/node/terminalEnvironment.ts`
* `vs/workbench/contrib/terminal/electron-sandbox/localTerminalService.ts`
* `vs/base/node/shell.ts` @TylerLeonhardt 

#### Debug @isidorn @weinand 
* `vs/workbench/contrib/debug/browser/rawDebugSession.ts`
* `vs/workbench/contrib/debug/node/debugAdapter.ts`

#### Tasks @alexr00 
* `vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts`
* `vs/workbench/services/configurationResolver/electron-sandbox/configurationResolverService.ts`

#### Proxy @chrmarti 
* `vs/platform/request/node/proxy.ts`
* `vs/workbench/services/extensions/node/proxyResolver.ts`

#### Child Processes
* [search](https://github.com/microsoft/vscode/blob/8c2d3b40e16b21ebb9e6bd396dfb02aa785731d6/src/vs/workbench/services/search/node/searchApp.ts#L13-L13) @roblourens 
* [telemetry](https://github.com/microsoft/vscode/blob/ff9fbcb077b097d7ffb074f04f6301476578abc3/src/vs/workbench/contrib/debug/node/telemetryApp.ts#L16-L16) @sbatten

**Comment by roblourens** [comment]
Checked off search, I don't think anything is needed, the spawned search process doesn't depend on the environment at all.

**Comment by bpasero** [comment]
Small clarification on top of https://github.com/microsoft/vscode/issues/108804#issuecomment-791217699: If you cannot depend on `IShellEnvironmentService` because you are in `node` layer or `electron-main`, you can directly depend on `resolveShellEnv` method provided from `src/vs/platform/environment/node/shellEnv.ts`. This method is caching a `Promise`, so even if it is called multiple times from the same process, it will only resolve once overall. 

Keep in mind though that if you are the first to call this method it may execute slow, up to 10s as we have seen. The `electron-main` process calls this method right in the beginning before opening windows to be ready when anyone needs it later.

**Comment by Tyriar** [comment]
> Going forward, process.env will no longer attempt to contain the shell environment of the user unless VSCode was launched from a terminal.

@bpasero is it possible to get access to the non-shell process environment? If so, is there a convenient way to access it from electron-sandbox? This would actually fix some issues where our terminal acts differently to other terminals https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed, we could potentially also remove the `terminal.integrated.inheritEnv` setting as ell.

**Comment by bpasero** [comment]
@Tyriar I do not think that is possible because when you launch VSCode from a terminal we just get `process.env` containing all the variables from the terminal already. We would probably have to change our startup scripts to have a clean environment even when launched from the terminal to get this.

But maybe I misunderstood the question.

**Comment by Tyriar** [comment]
@bpasero I think that's fine since if you start an external terminal from another terminal you would expect it to inherit the environment. What's not expected is when a terminal is launched from the dock, to run a login shell to establish an environment before launching the actual shell.

**Comment by bpasero** [comment]
@Tyriar after everyone has adopted this service you can simply use `process.env` and it will not include any shell environment unless VSCode was started from the shell. In other words, we will stop merging the shell environment into the current process environment at least in the renderer. If you need this also from shared process, I think we should be able to also stop doing this there. Just for the extension host we can probably not do this to not break extensions.

**Comment by weinand** [comment]
@bpasero the only reason why `process.env` was accessed in `vs/workbench/contrib/debug/browser/rawDebugSession.ts` was the "launch.json" feature to **delete** environment variables by using the value `null`. The code in `rawDebugSession.ts` merged and deleted the environment variables provided by the launch.json.

When reviewing the implementation, I noticed that the **delete** part no longer worked: it seems that another merge happening later undoes the delete.

I've removed the `process.env` code and we will have to find a better way to implement the deletion of environment variables.

**Comment by bpasero** [comment]
I have looked at the `telemetryApp` and think it should be fine because of the work that happened in `ICustomEndpointTelemetryService` where the app runs as a child from the shared process that gets the shell environment. 

The remaining work is in terminals and configuration resolvers 👍

**Comment by Tyriar** [comment]
Pretty sure terminal done now 🎉

**Comment by alexr00** [comment]
With some help from @Tyriar, I'm pretty sure that the configuration resolver is also done now.

**Comment by bpasero** [comment]
Thanks a lot ❤️

**Comment by bpasero** [comment]
We will take out the process environment patching early May to get a good milestone of coverage.

**Comment by agreeff** [comment]
Just out of curiosity, is there any way to just permanently ignore the "taking too long" warning message..?

I ask because I'm required to use a Mac at work (I really prefer Linux myself), but the machine I've been given to use is a late 2013 Intel i5 iMac 27". This thing is stupidly slow at the best of times, I've timed a cold boot at a little over 3 minutes, multiple times.

So I *know* it's slow, I don't need another notification telling me that every time I open a VSCode instance, which quite often involves multiple instances at the same time..

**Comment by bpasero** [comment]
> Just out of curiosity, is there any way to just permanently ignore the "taking too long" warning message..?

Yes, switch to insiders where this notification no longer appears: https://code.visualstudio.com/insiders/
