### ISSUE TITLE
Notebooks: Self-hosting experience

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#109549]
Over the last 2 weeks or so, I have been using GitHub issues notebooks intensively. Overall it's working very well. This is the collection of paper cut issues I ran into.  The first three in the list are indeed my top three.   

- [x] I miss the run button when I try to click on it around 50% of the time. When you move your mouse very slowly in and out of the run button you can see where it changes and how that is misleading.
![image](https://user-images.githubusercontent.com/4674940/97377924-5f5fec80-187e-11eb-91ae-47e478786c66.png)
- [x] When switching back and forth between different editors or windows I easily lose track of where the keyboard focus is inside a notebook. This is less of a problem when a cell editor has the focus but very much so when the cell has the focus. Try: Give a cell the focus, Cmd+Shift+F, Cmd+1. You see that the only indication is the change in upper and lower border.
![lsqWDiuxKq](https://user-images.githubusercontent.com/4674940/97377375-1ce9e000-187d-11eb-8abf-069b949692ae.gif)
- [x] I often click into the cell status bar when trying to give focus to an editor or I try to delete the "empty" line in a cell by using arrow-down to get there.
![n3xR8wR3OM](https://user-images.githubusercontent.com/4674940/97377512-76520f00-187d-11eb-9e8f-794c7b49e332.gif)
- [x] After I create a new cell with Cmd+Enter I try to change the cell language with "change language mode" in the command palette.
- [x] Undo of markdown edits replay in the rendered markdown. I'd expect that the cell goes into edit mode and then performs the undo.
![2MfGCeQchh](https://user-images.githubusercontent.com/4674940/97378085-bc5ba280-187e-11eb-9dc1-6fdf7a7f3e38.gif)
- [x] The first diff in a notebook is not revealed when opening the diff editor. Since we don't have the minimap or show diffs in the scrollbar it looks like there are no diff. We should follow the model of text editors here. 
![image](https://user-images.githubusercontent.com/4674940/97377888-46573b80-187e-11eb-9dc1-6a4eb4eee83d.png)
- [ ] I've seen rare situations in which I had screen cheese, see https://github.com/microsoft/vscode/issues/108764.
- [x] When I open a notebook diff editor with double-click and then open the notebook file that is being diffed using Cmd+P, the latter opens as json #110894.
- [x] 🏃 Open a GH issues notebook with problems. Open the Problems view and click on a problem. A second editor opens. 
- [ ] When trying to delete output, I was always first looking closer to the actual output rather than the cell toolbar #110959
- [ ] 💪 I repeatedly tried to use Find to look for information in the outputs... https://github.com/microsoft/vscode/issues/94239
- [x] I repeatedly tried to use ArrowDown to go from a cell editor to the output below.
  - We have enough context keys to allow such customization (see https://github.com/microsoft/vscode/issues/110962#issuecomment-730537959) and we will continue discuss about the default navigation flow in that.
- [x] 🏃  The GH issues notebook loses its keyboard focus when: 1) run a cell 2) Open an issue from output by clicking the link 3) Cmd-Tab to come back to the VS Code window -> no keyboard focus. You have to explicitly mouse click into the notebook to bring it back.

**Comment by misolori** [comment]
Updated the default styles to make the "focus" state much more clearer and also added placeholder text in the status bar for active cells to better use the space. This should be updated in tomorrow's Insiders, happy to hear any feedback:

![gif](https://user-images.githubusercontent.com/35271042/99299069-85363c80-27ff-11eb-9242-03206516845e.gif)

**Comment by claudiaregio** [comment]
I think this looks good too! At one point during the gif there was a cell output going past the bottom of the screen. My only feedback would be that for scenarios like this or very long cells, the blue line only on top of the cell could be too subtle for users to understand what that indicator is supposed to be. 

![image](https://user-images.githubusercontent.com/19276747/99343832-84bf9500-2843-11eb-93c2-c03b47870887.png)

For the same scenarios in the code editor, the blue border at least covers 3 sides of the cell and is a little more clear at indicating a selection/focus of some sort. The previous selection version also had a background the also spanned the 3 sides which helped. 

![image](https://user-images.githubusercontent.com/19276747/99343088-0d3d3600-2842-11eb-988c-d0b8a2aba1eb.png)

Thinking a bit forward, could this support navigating within multiselect somehow?

**Comment by rebornix** [comment]
Updates on some UX polishes:

* Clicking on status bar will adjust its `clientY` position and set the cursor correspondingly in the editor. if users click on a status bar item, then it will only run the command other than hijacking the clicking.

![mouse-click-adjustment](https://user-images.githubusercontent.com/876920/99459975-d28bda00-28e3-11eb-99ee-cde70fffdeea.gif)

* **Change Language Mode** will invoke "Change Cell Language" command under the hood when the command is executed inside a cell editor.

**Comment by rebornix** [comment]
>  Open a GH issues notebook with problems. Open the Problems view and click on a problem. A second editor opens.

The last time when @kieferrm ran into this issue, we found that 

* firstly it happens in remote ssh environment 
* the `Uri` of the problems differ from the resource uri of the document in the editor, the editor says `.vscode/notebooks/api.github-issues` but the problem says `/Users/penlv/code/vscode/.vscode/notebooks/api.github-issues`.

They should be pointing to the same resource but the resource Uris are not identical. I tried to reproduce this again with ssh into both macOS and Ubuntu but can't reproduce anymore. @kieferrm can you verify if you can still reproduce this in your setup?

> The GH issues notebook loses its keyboard focus when: 1) run a cell 2) Open an issue from output by clicking the link 3) Cmd-Tab to come back to the VS Code window -> no keyboard focus. You have to explicitly mouse click into the notebook to bring it back.

I'm not able to reproduce this issue now, @kieferrm can you confirm? 

![webview-focus](https://user-images.githubusercontent.com/876920/99599412-2b28a900-29b0-11eb-8b55-e06f82b6c0bb.gif)

**Comment by kieferrm** [comment]
@rebornix regarding https://github.com/microsoft/vscode/issues/109549#issuecomment-730014421: I cannot reproduce either issue in the latest insider.

**Comment by rebornix** [comment]
Thanks!

There are 3 items left which are tracked in separate issues and we will have discussions there. Closing this issue as others are all done.
