### ISSUE TITLE
Iteration Plan for November 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#110690]
This plan captures our work in **November**. This is a 5-week iteration. We will ship in **early December**.

We've spent the first two weeks of this iteration finishing our annual housekeeping. You can see the progress me made on https://vscode-github-stats.netlify.app/ that @lannonbr created for us a while back. If you are interested in why we have issue house keeping iterations and in our general philosophy around issue management, then we have this [write-up](https://github.com/microsoft/vscode/wiki/Issue-Grooming) for you.

Because of house keeping, the plan items below are mostly for the second half of the iteration. You might feel that you see more muscle items than usual. That is not an illusion. Since we don't ship a release in early January, we don't have a December place. The work in December is captured in our muscle items and will carry over into our January plan.

## Endgame
- **November 30, 2020**: Endgame begins
- **December 4, 2020**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/111406.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Housekeeping
- [x] Issue/PR Grooming - review, categorization, assignment https://github.com/microsoft/vscode/issues/108472 **team**

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22November+2020%22) **team**
- [ ] :runner: Assess notebook accessibility https://github.com/microsoft/vscode/issues/111255 @isidorn @rebornix @roblourens

### Workbench
- [ ] :runner: :muscle: Explore the concept of Trusted Workspaces https://github.com/microsoft/vscode/issues/106488 @lszomoru @sbatten
- [ ] :runner: :muscle: Investigate predefined file filters search (https://github.com/microsoft/vscode/issues/106790) @jacksonkearl
- [ ] :runner: :muscle: Explore support for adding/organizing imports on Paste https://github.com/microsoft/vscode/issues/30066 @mjbvz
- [ ] :runner: :muscle: Improve the welcome pages https://github.com/microsoft/vscode/issues/106715 @misolori @jacksonkearl
- [ ] :hand: Improve emmet support https://github.com/microsoft/vscode/issues/110697 @rzhao271
- [ ] :muscle: Explore showing file decorations in editor tabs https://github.com/microsoft/vscode/issues/49382 @jrieken
- [x] Improve initial appearance of Welcome Views in the explorer https://github.com/Microsoft/vscode/issues/106487 @joaomoreno
- [ ] :runner: Supporting to customize the product icons https://github.com/microsoft/vscode/issues/92791 @aeschli @misolori
- [x] Add sorting support for the Open Editors list https://github.com/microsoft/vscode/issues/12453 @isidorn
- [x] Support undo/redo of explorer operations https://github.com/microsoft/vscode/issues/107740 @isidorn
- [x] Improve our handling of process environment depending on context https://github.com/Microsoft/vscode/issues/108804 @bpasero @joaomoreno

### Notebook Editor
- [x] Scale to large simple outputs https://github.com/microsoft/vscode/issues/110581 @rebornix
- [x] Address notebook papercuts https://github.com/microsoft/vscode/issues/109549 @rebornix @roblourens @misolori
- [x] Introduce metadata to control rendering of outputs https://github.com/microsoft/vscode/issues/108946 @rebornix
- [x] Support to not render empty outputs https://github.com/microsoft/vscode/issues/109104 @rebornix
- [ ] :hand: Identify and fill API gaps for Live Share https://github.com/microsoft/vscode/issues/102503 @rebornix
- [ ] :runner: Explore notebook keymap support https://github.com/microsoft/vscode/issues/106679 @rebornix @roblourens
- [ ] :muscle: Explore extensible markdown rendering for notebooks https://github.com/microsoft/vscode/issues/106701 @mjbvz
- [ ] :muscle: Improve notebook diff editor scrolling performance https://github.com/microsoft/vscode/issues/109680 @rebornix
- [ ] :muscle: Explore output renderer support in notebook diff editors https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Anotebook+diff @rebornix
- [ ] :muscle: Explore options to support free-floating output renderer elements https://github.com/microsoft/vscode/issues/108947 @rebornix
- [ ] :muscle: Explore options to allow an output to go into full-screen mode https://github.com/microsoft/vscode/issues/110766 @rebornix

### Editor
- [x] Support word wrap in the diff editor https://github.com/microsoft/vscode/issues/11387 @alexdima

#### LSP /LSIF
- [x] [LSP - version 3.16](https://github.com/microsoft/language-server-protocol/milestones/3.16) including features like (`onTypeRename`, `onDid*`, `onWill*` events) @dbaeumer
- [x] LSIF - Same source for multiple projects support https://github.com/microsoft/lsif-node/issues/116 @dbaeumer
- [ ] :muscle: LSP - investigate supporting a pull model for diagnostics (diagnostics are currently delivered using a push model) https://github.com/microsoft/language-server-protocol/issues/737 @dbaeumer

#### JavaScript/TypeScript
- [x] Adopt TS 4.1 https://github.com/microsoft/vscode/issues/111000 @mjbvz
- [x] Improve TypeScript version selector https://github.com/microsoft/vscode/issues/111001 @mjbvz

### Debug
- [ ] :muscle: Update all node debug documentation/tutorials to use `debug-js` https://github.com/microsoft/vscode-docs/issues/4123 @connor4312
- [x] Collapse identical lines in the debug console https://github.com/microsoft/vscode/issues/104162 @isidorn
- [x] Improve the dynamic launch config UI https://github.com/microsoft/vscode-docs/issues/110009 @isidorn
- [ ] :runner: Improve stack traces for extension debugging https://github.com/microsoft/vscode/issues/104686 @connor4312 @isidorn
- [x] Show help text/tip at the bottom of debug hover to switch to the language hover https://github.com/microsoft/vscode/issues/107697 @isidorn
- [x] Add condition editing UI for exception breakpoints https://github.com/microsoft/vscode/issues/111227 @isidorn
- [ ] :runner: improve "inline values" https://github.com/microsoft/vscode-docs/issues/101797 @weinand
- [ ] :hand: Improve the "breakpoint hit" UI for Web UI https://github.com/microsoft/vscode/issues/100757 @weinand @isidorn

#### DAP
- [x] Support conditions for exception breakpoints https://github.com/microsoft/debug-adapter-protocol/issues/137 @weinand
- [x] Investigate: Is StackTraceResponse.totalFrames truly necessary? https://github.com/microsoft/vscode/issues/31851 @weinand
- [x] Review: Support object favorites https://github.com/microsoft/debug-adapter-protocol/issues/132 @weinand
- [ ] :runner: Continue discussion: Support object IDs https://github.com/microsoft/debug-adapter-protocol/issues/134 @weinand
- [ ] :runner: Investigate: control escaping/quoting arguments for the `runInTerminal` request https://github.com/microsoft/debug-adapter-protocol/issues/146 @weinand

### Testing
- [ ] :runner: Explore how to improve testing support https://github.com/microsoft/vscode/issues/107467 @connor4312 @sandy081

### Terminal
- [x] Explore ways to inform users about the specifics of terminal keyboard shortcuts https://github.com/microsoft/vscode/pull/110987 @meganrogge
- [ ] :runner: :muscle: Restore terminal UI state https://github.com/microsoft/vscode/issues/109244 @roblourens @meganrogge

### Source Control
- [x] Guide users if `user.name` or `user.email` are undefined in git config https://github.com/microsoft/vscode/issues/110880 @eamodio
- [ ] :runner: Warn when pushing to a rebased branch https://github.com/microsoft/vscode/issues/110881 @eamodio
- [x] Git: Support optional branch picking in the repository picker https://github.com/microsoft/vscode/issues/106664 @joaomoreno
- [ ] :muscle: Guide user to push to a remote after creating a commit https://github.com/microsoft/vscode/issues/110882 @eamodio

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2020%22+label%3A%22api-proposal%22)

### Extensions
- [x] Support to bisect extensions to narrow down a malfunctioning extension @jrieken
- [ ] :muscle: :red_circle: Explore bracket pair colorizing performance improvements @alexdima

### Extension Contributions
- [x] Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/4017 **team**
- [x] :muscle: Improvements to the GitHub PR extension https://github.com/microsoft/vscode-pull-request-github/issues/2293 @rmacfarlane @eamodio

### Install
- [ ] :muscle: :runner: Explore installing the Remote-WSL extension out of the box on Windows https://github.com/microsoft/vscode/issues/106759 @joaomoreno @aeschli

### Engineering
- [ ] :hand: Publish Linux ARM deb, rpm and snap to repositories https://github.com/Microsoft/vscode/issues/106473 @joaomoreno
- [ ] :runner: Make VSCode [Trusted Types](https://w3c.github.io/webappsec-trusted-types/dist/spec/) compliant https://github.com/Microsoft/vscode/issues/103699 @jrieken and **team**
- [ ] :runner: Stabilize Apple Silicon builds https://github.com/microsoft/vscode/issues/106770 @deepak1556
- [ ] :runner: electron 11 adoption https://github.com/microsoft/vscode/pull/110759 @deepak1556
- [ ] Adopt `vscode.open` and `vscode.diff` in SCM, Timeline, GHPRI extension
  - [x] SCM/git @joaomoreno
  - [ ] Timeline @eamodio
  - [ ] GHPRI extension @alexr00

#### Node.js-free, sandboxed renderer
- [ ] :runner: Backlog https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556

-----
### Deferred Items
- :runner: Explore possible integrations between extensions view and GH Sponsors https://github.com/microsoft/vscode/issues/107482 @misolori

**Comment by sandstrom** [comment]
Any chance you could add this feature to your November or December plan?

https://github.com/microsoft/vscode/issues/519

It's got 1600 up votes, 270 comments and it's five years old.

**Comment by MatthewS2077** [comment]
> Allow to change the font size and font of the workbench — #519

Yes please! 🙏 We shouldn't need to reset to "Monkey Patch" to change our font.

**Comment by ssbarnea** [comment]
Not sure how "Extension Bisect" was implemented but it seams to be missing from macos Version: 1.52.1 version of vscode. There is no option to be found anywhere about it.

**Comment by alexdima** [comment]
@ssbarnea You can find it by pressing `F1` and picking `Help: Start Extension Bisect`

**Comment by ssbarnea** [comment]
Now I feel stupid: I used the **Help** menu, which does not have such an option but it has a search, a search that finds nothing when typing bisect. 

Please take a look at https://code.visualstudio.com/updates/v1_52#_troubleshooting-extension-bisect and you will soon realize why the blog post is confusing.

![](https://sbarnea.com/ss/Screen-Shot-2020-12-21-15-34-56.22.png)

Do you see how "Help" is advertised... the other help. Probably it would have being less confusing to replace the text with "F1 > .." instead of "help".

**Comment by alexdima** [comment]
cc @gregvanl @jrieken re https://github.com/microsoft/vscode/issues/110690#issuecomment-749036419

**Comment by gregvanl** [comment]
Fixed release notes to use correct Command Palette name for Extension Bisect commands https://github.com/microsoft/vscode-docs/commit/ea9c64c28ac57a9c38010a617f4f52c353ff5dc6
