### ISSUE TITLE
Feedback from Jupyter notebook extension early adopters

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#113245]
We have received hundreds of good feedbacks from early adopters of the Jupyter extension using native notebook support. The clean UX, seamless integration with VS Code ecosystem and improved performance are mostly loved. However we are also seeing bugs and UX issues users are struggling with. Here I tried to compile the feedbacks into issues so we can track where we are with them.

## Bugs & UX improvements

**Core**

- [x] Problems with ctrl+z (cause the cell to run endlessly https://github.com/microsoft/vscode/issues/106362)
- [x] The control enter to run appears an increasing number of times https://github.com/microsoft/vscode/issues/113243
- [x] Vim https://github.com/VSCodeVim/Vim/issues/6104
  - [x] jk to move between cells
  - [x] the shortcut to clear the output is not working with vim bindings either
  - [x] compatibility with vim extension when pressing escape
- [ ] Cell/output collapse #104114, #104115, 
  - [ ] When dealing with cells containing very long output is quite clunky, you can right click on the cell and collapse output, but then it's fully collapsed and you don't see anything
  - [ ] Collapsing a very long cell when you're looking at its end, the document scroll position should probably jump to the code cell that produced the collapsed output
  - [ ] Show the first line when a cell is collapsed
- [x] Tooltip for every button

**Jupyter**

- [ ] 🐍 Kernel
  - [ ] 🐍kernel crashes (multiple reports of crashes) 
  - [ ] 🐍could get kernel to connect
  - [ ] 🐍two kernel selection options at the bottom microsoft/vscode-jupyter#3979
  - [ ] 🐍the constant failing to start up a kernel
  - [ ] 🐍severe performance issues. appears to degrade over time, requiring regular restarts of the kernel microsoft/vscode-jupyter#1622
- [ ] 🐍The old cell output stays when running empty cell
- [ ] 🐍Matplotlib plots (contour plots) very slow microsoft/vscode-jupyter#1622
- [ ] 🐍The linter often gets stuck
- [ ] 🐍Renderer
  - [ ] Plots with all content outside the axes (i.e., tick labels, etc.) shaded such that they are difficult to read. https://github.com/microsoft/vscode/issues/108947

## Feature Requests

**Core**
- Markdown
  - [x] :runner: Latex https://github.com/microsoft/vscode/issues/106701
  - Mapping of all Markdown capabilities into a menu
  - Markdown features (underline, bold, compared to Azure Data Studio)
- [x] Outline https://github.com/microsoft/vscode/issues/98173
  - [x] Heading navigation (like google colab)
- [ ] :runner: Live share support https://github.com/microsoft/vscode/issues/102503
- [x] :runner: Cell multi selection: selecting multiple cells to copy or cut would also be nice https://github.com/microsoft/vscode/issues/114156
- [ ] Cell metadata editing

**Jupyter**

- [x] 🐍Execution 
  - [x] 🐍Run all cells above or below a selected cell https://github.com/microsoft/vscode-jupyter/pull/4240
- [ ] 🐍 :runner: Full jupyter keyboard shortcut https://github.com/microsoft/vscode/issues/106679
- [ ] Variable explorer microsoft/vscode-jupyter#250
- [ ] 🐍Renderer (❓ how many of them are covered by nteract/jupyter-ext?)
  - Date viewer
  - built in save picture as
  - option to save the plot in svg format
  - image zoom
  - full widget support
  - support full interactive plotting suite from pyviz
  - bokeh
  - holoviews
  - Interactive matplotlib plots
- [x] 🐍Jupyter lab extensions (There's also jupyterlab extensions which would be great to include in vscode for plotly)
  - mathjax3-extension
  - geojson-extension
  - drawio
- [ ] 🐍Kernel
  - [ ] 🐍easily open a console connected to same kernel as notebook
- [ ] 🐍Language feaures microsoft/vscode-jupyter#1193
  - Go to definition and peek
  - Intellisense
- [ ] 🐍Resource monitoring tools for CPU/GPU/memory
- [ ] 🐍Set git not track outputs https://github.com/microsoft/vscode-jupyter/issues/4670
- [ ] 🐍Performance
  - optimizations for plotting
  - performance can be sluggish with large plots
- [ ] Customizable CSS to modify appearance of rendered markdown cells
- [ ] 🐍 ❓ Debug line by line microsoft/vscode-jupyter#1160 & microsoft/vscode-jupyter#1231
- MISC
  - More Julia support

**Comment by hugocool** [comment]
Im on Version: 1.53.0-insider
When using [plotly with vscode renderer](https://plotly.com/python/renderers/#builtin-renderers) (to which the renderer is set by default) I get an error: 
`No renderer could be found for MIME type: application/vnd.plotly.v1+json`

**Comment by DonJayamanne** [comment]
**Need more info for the following to understand the issue:**
* Kernel -> could get kernel to connect
* Kernel -> severe performance issues. appears to degrade over time, requiring regular restarts of the kernel
	* Could be related to https://github.com/microsoft/vscode-jupyter/issues/1622
* The linter often gets stuck
* Renderer
	* Plots with all content outside the axes (i.e., tick labels, etc.) shaded such that they are difficult to read.
	* Screen shot with sample code would help.


**Info related to some of the issues reported above:**
* Kernel
	* Crashes (we're looking into this in our repo)
	* Two kernel selection options at the bottom
		* Tracked here https://github.com/microsoft/vscode-jupyter/issues/3979
	* The constant failing to startup a kernel  (we're looking into this in our repo)
*  Matplotlib plots (contour plots) very slow
	* I believe we know the cause.
	* https://github.com/microsoft/vscode-jupyter/issues/1622
* Variable explorer
	* This is being tracked & worked on here https://github.com/microsoft/vscode-jupyter/issues/250
* Renderer
	* Datra viewer
	* full widget support - this was added in the last release (December release of Jupyter extension)
	* bokey, holoview, interactive plots, etc would fall under widget support - hence supported in Dec Release
* Language features
	* Tracked here https://github.com/microsoft/vscode-jupyter/issues/1193
* Debug line by line
	* Tracked here https://github.com/microsoft/vscode-jupyter/issues/1160 & https://github.com/microsoft/vscode-jupyter/issues/1231
* More julia support
	* The Jupyter extension supports execution against Julia kernel.
	* I'm assuming users are requesting additional support here (variables, data frame viewers, etc)

**Comment by claudiaregio** [comment]
@rebornix Additional feedback has come in since this issue was created and want to make sure we are also capturing the cell execution hanging and the interrupt cell execution also not working

**Comment by claudiaregio** [comment]
Created issue but realized it was mentioned here. 

> * [ ]  Cell/output collapse
>   
>   * [ ]  When dealing with cells containing very long output is quite clunky, you can right click on the cell and collapse output, but then it's fully collapsed and you don't see anything
>   * [ ]  **_Collapsing a very long cell when you're looking at its end, the document scroll position should probably jump to the code cell that produced the collapsed output_**: https://github.com/microsoft/vscode/issues/114866
>   * [ ]  Show the first line when a cell is collapsed

**Comment by phgmacedo** [comment]
@rebornix Can the vscode team please reconsider [menu contributions](https://github.com/microsoft/vscode-jupyter/issues/5387)? 

There are lots of issues with complaints about users being forced to have jupyter installed with the python extension, and mostly msft's python/jupyter extension team just [ignores feedback and users complaints](https://github.com/microsoft/vscode-python/issues/14857) unless [it's from a vscode team member](https://github.com/microsoft/vscode-python/issues/9284#issue-542105846).

**Comment by misolori** [comment]
@rebornix I think this issue is a bit outdated, leaving for you to decide if you want to keep it open.
