### ISSUE TITLE
Ports view polish

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#116058]
## Ports View
- [x] Use a tabular rendering of the Ports view, leveraging the planned table widget
- [x] Show an icon that indicates the 'state' of the port (running/not runnig/running elevated)
- [x] Move Ports view to Panel, a table doesn't work well in the place constrained sidebar.
- [x] Render the ports exposed by extension process in a custom way https://github.com/microsoft/vscode/issues/115213
- [x] Show an inline action to copy the target URL (remove closing the port action from the list of inline actions)
- [x] Improve the text message shown in the welcome view. Suggestion:  'No forwarded ports, forward a port to access your running services'

## Ports Notification
- [x] Always show a notification when a process is detected, even when the port is already forwarded https://github.com/microsoft/vscode-remote-release/issues/4309			
- [x] Show port forwarding notification not in all windows, only show it in the active window not all windows, see also https://github.com/microsoft/vscode/issues/114622

**Comment by alexr00** [comment]
The remaining polish items here are best tackled as part of the table view exploration. Once the table widget is available I'll continue! (https://github.com/microsoft/vscode/issues/99997)

**Comment by alexr00** [comment]
Here's where we're at:
![image](https://user-images.githubusercontent.com/38270282/108372628-4dc09d00-71ff-11eb-8b2a-9b6d7cac44de.png)

Forwarded ports have a filled circle **icon** if there's a running process or an outline circle if not.
Each cell can have it's own actions, so the "close" inline action is in the first column. The other actions are in the local address column since they are directly related to the local address. This includes the newly added **inline copy action**.

**Comment by alexr00** [comment]
View has been moved to the panel.
After feedback:
![image](https://user-images.githubusercontent.com/38270282/108494407-c713ca80-72a7-11eb-82d8-67f37ca1bd87.png)

I am sure there will be more tweaking of the UI in the next couple days, but all of the polish items here have now been completed.
