### ISSUE TITLE
Iteration Plan for February 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#116000]
This plan captures our work in **February**. This is a 4-week iteration. We will ship in **early March**.

## Endgame
- **February 22, 2021**: Endgame begins
- **February 26, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22February+2021%22).

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Improve navigability in tool bars https://github.com/microsoft/vscode/issues/106441 @isidorn
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22February+2021%22) @isidorn **team**
- [ ] :runner: Assess notebook accessibility https://github.com/microsoft/vscode/issues/111255 @isidorn @rebornix @roblourens

### Workbench
- [ ] :runner: Explore the concept of Trusted Workspaces https://github.com/microsoft/vscode/issues/106488 @lszomoru @sbatten
  - [x] Validate for the `eslint` extension @dbaeumer
  - [ ] Validate for the `remote-containers` extension @chrmarti
- [ ] :runner: Improve the welcome pages https://github.com/microsoft/vscode/issues/106715 @jacksonkearl @digitarald @misolori
  - [x] Improve accessibility of the new welcome page https://github.com/microsoft/vscode/issues/115896 @jacksonkearl
  - [x] Make the new welcome pages the default https://github.com/microsoft/vscode/issues/116412 @jacksonkearl
  - [x] Enable extensions to contribute tiles to the welcome page https://github.com/microsoft/vscode/issues/116414 @jacksonkearl
  - [ ] Explore integration of release notes and extension change logs @jacksonkearl
  - [x] User testing on new welcome pages @digitarald
- [x] Make it easier to switch between the classic and the compact menu appearance https://github.com/microsoft/vscode/issues/116142 @sbatten
- [x] Improve handling of new `untitled` text files for new users https://github.com/microsoft/vscode/issues/114307 @isidorn
- [x] Explore transition from viewing an image to editing an image https://github.com/microsoft/vscode/issues/116120 @tyriar
- [x] Enable multiple 'Run' contributions in the editor's toolbar https://github.com/Microsoft/vscode/issues/114123 @jrieken
- [x] Support to contribute to the icon registry https://github.com/Microsoft/vscode/issues/114942 @aeschli
- [ ] :muscle: Explore support for adding/organizing imports on Paste https://github.com/microsoft/vscode/issues/30066 @mjbvz
- [ ] :muscle: Explore consolidation of managing "Don't Show Again" in notifications https://github.com/microsoft/vscode/issues/24815 @meganrogge
- [x] Improve context keys handling (suggestions & doc), https://github.com/microsoft/vscode/issues/9303, https://github.com/microsoft/vscode/issues/114867 @jriekn

### UX
- [ ] :runner: Continue exploration of profiles https://github.com/microsoft/vscode/issues/116740 @misolori
- [x] Tree usability: revisit the twisty interaction https://github.com/microsoft/vscode/issues/115873  @joaomoreno @misolori
- [x] Tree usability: use a more prominent focus indicator https://github.com/microsoft/vscode/issues/95768 @joaomoreno @misolori

### Code Editor
- [ ] :red_circle: Refactor the hover widget @alexdima

### Notebook Editor
- [ ] :runner: Review Notebook API https://github.com/microsoft/vscode/issues/93265 @jrieken @rebornix @roblourens
- [x] Support implementation of LiveShare in notebooks https://github.com/microsoft/vscode/issues/102503 @rebornix
- [ ] :runner: Explore extensible markdown rendering for notebooks https://github.com/microsoft/vscode/issues/106701 @mjbvz
- [ ] :runner: Explore options to allow an output to go into full-screen mode https://github.com/microsoft/vscode/issues/110766 @rzhao271 @rebornix
- [ ] :runner: Reduce notebook papercut issues https://github.com/microsoft/vscode/issues/113245 @rebornix @jrieken @roblourens
  - [x] Improve focus handling in notebooks https://github.com/microsoft/vscode/issues/113246 @misolori
  - [x] Improve discoverability of cell folding https://github.com/microsoft/vscode/issues/113248 @misolori @rebornix
- [ ] :runner: Explore cell multi-select https://github.com/microsoft/vscode/issues/114156 @rebornix @misolori

### Languages
- [ ] :muscle: :black_circle: Explore inline type hints `InlineHintProvider` https://github.com/microsoft/vscode/issues/113276 @jrieken @alexdima @mjbvz

#### LSP /LSIF
- [x] LSP - explore supporting a pull model for diagnostics for the `eslint` extension https://github.com/microsoft/language-server-protocol/issues/737 @dbaeumer
- [ ] LSP - Explore "TypeHierarchy" support together with the Java extension team @dbaeumer  **todo add someone from the Java team**

#### JavaScript/TypeScript
- [x] Adopt TS 4.2 https://github.com/microsoft/vscode/issues/115568 @mjbvz

### Debug
- [ ] :runner: :hand: Ability to drag and drop breakpoints https://github.com/microsoft/vscode/issues/88227 @isidorn
- [x] Implement "Inline Values Provider" https://github.com/microsoft/vscode/issues/105690 @weinand
- [ ] :runner: Improve browser tab notifications for debugging in Web UI https://github.com/microsoft/vscode/issues/100757 @weinand @isidorn
- [ ] :muscle: Investigate debug UI for highly concurrent languages https://github.com/microsoft/vscode/issues/116109 @weinand @connor4312

#### DAP
- [x] Improve error handling/help support for breakpoint conditions https://github.com/microsoft/debug-adapter-protocol/issues/164 @weinand
- [x] Add per-stackframe `canRestart` https://github.com/microsoft/debug-adapter-protocol/issues/147 @weinand
- [x] New features for the `runInTerminal` request https://github.com/microsoft/debug-adapter-protocol/issues/165 @weinand

### Testing
- [ ] :runner: Explore how to improve testing support https://github.com/microsoft/vscode/issues/107467 @connor4312 @sandy081

### Terminal
- [x] Improve handling of variable collections https://github.com/microsoft/vscode/issues/115053 https://github.com/microsoft/vscode/issues/100193 @tyriar
- [x] Move terminal processes out of renderer process https://github.com/microsoft/vscode/issues/74620 @tyriar @meganrogge
- [x] Persistent local processes across reloads https://github.com/microsoft/vscode/issues/20013 @meganrogge @tyriar
- [ ] :muscle: Explore running `xterm.js` as a node process on the server https://github.com/microsoft/vscode/issues/116113 @tyriar @meganrogge

### Source Control
- [ ] :runner: :muscle: Explore UI additions to help guide users to push to a remote after committing https://github.com/microsoft/vscode/issues/110882 @eamodio
- [x] Allow compare between git timeline entries https://github.com/microsoft/vscode/issues/116361 @eamodio
- [ ] Investigate fine grained change events in git core for consumption in the GHPRI and GitLens extensions https://github.com/microsoft/vscode/issues/116360 @eamodio

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2021%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2021%22+label%3A%22api-proposal%22)

### Extension Contributions
- [x] Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/4430 **team**
- [ ] :runner: Improvements to the GitHub PR extension @rmacfarlane @eamodio
  - [x] Improve performance of entering review mode https://github.com/microsoft/vscode-pull-request-github/issues/2487 @eamodio
  - [ ] :runner: Improve refresh behavior of the PR views https://github.com/microsoft/vscode-pull-request-github/issues/2478 @rmacfarlane
  - [x] Split focus mode view from PR list view https://github.com/microsoft/vscode-pull-request-github/issues/2371 @rmacfarlane
  - [ ] :muscle: Investigate an option to close editors when exiting review mode https://github.com/microsoft/vscode-pull-request-github/issues/2479 @rmacfarlane
  - [ ] :muscle: Explore support marking files as viewed https://github.com/microsoft/vscode-pull-request-github/issues/520 @rmacfarlane
  - [ ] :muscle: Explore support for resolving comments https://github.com/microsoft/vscode-pull-request-github/issues/339 @rmacfarlane
- [x] Adopt auth API changes in GitLens to avoid notification on startup https://github.com/eamodio/vscode-gitlens/issues/1336 @eamodio
- [ ] Continue improving and adding functionality to REST Book https://github.com/tanhakabir/rest-book/issues/30 @tanhakabir

### Install
- [x] Provide macOS Apple Silicon for Stable https://github.com/microsoft/vscode/issues/116737 @deepak1556

### Engineering
- [ ] :runner: Consolidate `Open with` across custom editors and notebooks, see https://github.com/microsoft/vscode/issues/100281 @lramos15
- [ ] :runner: Investigation: Cache VS Code extension builds https://github.com/microsoft/vscode/issues/115023 @joaomoreno @TylerLeonhardt
- [x] electron 11 stabilization, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aelectron-11-update+is%3Aopen) @deepak1556 @rzhao271
- [x] Terminal lag on Big Sur https://github.com/microsoft/vscode/issues/105446 @deepak1556
- [ ] :runner: Scroll performance on Windows https://github.com/microsoft/vscode/issues/107016 @deepak1556
- [ ] :runner: Move away from `get*Actions` in Views and ViewContainers and use Menu instead https://github.com/microsoft/vscode/issues/92038 @sandy081 **team**
- [ ] :red_circle: Adopt `vscode.open` and `vscode.diff` in SCM, Timeline, GHPRI extension
  - [x] Timeline @eamodio
  - [ ] :runner: GHPRI extension @alexr00
- [x] Add a table widget https://github.com/microsoft/vscode/issues/99997 @joaomoreno
- [x] Winget - Publish system setup for stable and insiders https://github.com/microsoft/vscode/issues/105307 @lszomoru
- [ ] :muscle: Introduce an `IProcessEnvService` for resolving the merged process environment based on context https://github.com/microsoft/vscode/issues/108804 @bpasero
- [ ] :red_circle: :muscle: Investigate using component governance support for third party notices generation @lszomoru

#### Node.js-free, sand-boxed renderer
- [ ] :runner: Backlog https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556

**Comment by sanket-bhalerao** [comment]
@joaomoreno, as per [issue](https://github.com/microsoft/vscode/issues/116341) the branch is renamed to main, however, commit log in the 'February 2021 (version 1.54)' points to the old branch commit log and leads to 404.

![image](https://user-images.githubusercontent.com/9264813/108478958-23ccb080-72bb-11eb-80a6-be2e295ba90d.png)

**Comment by jrieken** [comment]
Closing. We have shipped 1.54
