### ISSUE TITLE
Polish notebook markdown extension point

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#116393]
Follow up on #106701, which added a new extension point that lets extensions contribute markdown extensions for notebooks. 

To enable the new render API, set:

```json
"notebook.experimental.useMarkdownRenderer": true,
```

## Todos

- [ ] Make a more thorough test of accessibility with these changes
     - [X] Improve focus tracking
     - [x] Test screen reader
- [x]  When pre-rendering the notebook cells on first load, look at cell position cache instead of just getting first five cells
- [X] Move the math contribution into a new extension
- [x] Make sure that only core extensions can fully replace the markdown renderer for now
- [ ] Figure out markdown extensions should be contributed. Right now they come in the same way replacement markdown renderers do
- [x] Improve drag + drop of cells. Currently there are noticeable delays

**Comment by mjbvz** [comment]
I've split the remaining issues out:

#121256 For API review
#118594 for accessibility
