### ISSUE TITLE
Notebook rendered markdown cell interaction issues

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#117423]
https://user-images.githubusercontent.com/35271042/108866964-91255d80-75a9-11eb-98d5-4926ad6d1221.mov

- [x] Hovering over the text turns the cursor into text selection (it should always be the grabber to move cells) #117488
- [ ] Hovering next to the next results in no cursor/move change (you should be able to select any area for selection) #117489
- [ ] Double-clicking into a cell for edit and then exiting causes extra padding to appear near the bottom of the cell
- [x] Double-clicking into a cell does not focus the cell editor #117487 (same root cause)
- [x] Pressing `esc` when a cell is selected in edit mode does not exist edit mode #117487
- [ ] Overall padding inside of cells seems larger than the previous version (see below: left is prev right is new) #117493
  ![image](https://user-images.githubusercontent.com/35271042/108867384-fd07c600-75a9-11eb-9a03-4c747e1ae97d.png)

**Comment by mjbvz** [comment]
For `esc`, the difference seems to be that we focus the cell instead of the editor instance

**Comment by mjbvz** [comment]
One other note on why there are now bottom borders on the `h1` elements: these borders were previously styled to white so they did not appear on light themes. I fixed the border color to match the text color.

**Comment by mjbvz** [comment]
I've split this out to separate issues so that we can better track fixes
