### ISSUE TITLE
Terminal tabs April plan

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#120241]
Plan item capturing terminal tabs work for April (https://github.com/microsoft/vscode/issues/10546)

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :large_blue_circle:  | more investigation required to remove uncertainty |

- [x] Icons @Tyriar
  - [x] APIs
    - [x] Proposed ext API #120538
    - [x] Profile schema
    - [x] Terminal types contribution (js debug)
    - [x] ITerminalService/ITerminalInstance API for tasks
      - [x] Adopt in tasks
  - [x] :muscle: Should also show icons in select default profile/new with profile
  - [ ] :muscle: ~~Color support: this could just be #rrggbb in the profile~~ Deferred: https://github.com/microsoft/vscode/issues/121738
  - [x] Assets: Generic terminal (`terminal`), generic WSL, Ubuntu, Debian, task (`tools`), cmd, pwsh, tmux https://github.com/microsoft/vscode-codicons/issues/51
- [x] Terminal status https://github.com/microsoft/vscode/issues/120583 @Tyriar 
  - [x] Internal status tracking: name, severity, information (they need to be able to show the same information/actions as the info widget)
  - [x] Terminal instance API to set statuses
    - [x] Issue to adopt in tasks
  - [x] Icon + status widget
  - [x] Assets: Running (`play`), failed (`error`), succeeded (`check`), `bell`, disconnected (`debug-disconnect`), `warning`, `info`
- [x] Visual bell @Tyriar
  - [x] Add event to xterm.js https://github.com/xtermjs/xterm.js/issues/3014
  - [x] Hook up to icon status
  - [ ] ~~Experiment with shake animation~~ Decorations have minimal icon support
- [x] Split pane @meganrogge 
  - [x] Widget to hold tabs (list/tree widget?)
    - [x] :large_blue_circle: UX: How do splits show? Tree widget?
    - [x] Actions on terminals (split, rename, kill)
    - [x] Setting to move to side
    - [x] ~~Double click in empty area to create new default terminal~~ Tracked in https://github.com/microsoft/vscode/issues/121933
    - [x] Scrollable overflow
    - [ ] :muscle: Drag and drop
    - [x] Context menu
  - [x] :large_blue_circle: UX: ~~Think through how this works when the panel is on the side~~ Tracked in https://github.com/microsoft/vscode/issues/121572
  - [x] Responsive: Resizing should be able to hide titles
- [x] New terminal with dropdown button
  - [x] Leverage the combined run button in editor?
- [x] Dropdown
  - [x] :large_blue_circle: UX: Include split icon? This wouldn't work in native mac menus
- [x] Default keybindings for navigating terminal tabs https://github.com/microsoft/vscode/issues/119653

**Comment by BerriJ** [comment]
Will this also enable us to draw a terminal into one "corner" of the editor area. Currently, it's only possible to choose between "left", "right" or "bottom" but every option covers 100% of the height/width of the editor area. It would be fantastic If one could draw the terminal into e.g., the bottom right corner, so you can have one editor opened with 100% height (left side) 1, editor open with 50% height (right-top), and the Terminal area with 50% height (right bottom).

Sorry if this feature request is misplaced here, or if it's already tracked elsewhere.

**Comment by Tyriar** [comment]
@BerriJ that's out of scope for this month's work, but we're planning on doing that later

**Comment by misolori** [comment]
Terminal icons have now been added to codicons via https://github.com/microsoft/vscode/commit/0e7d1610f3ffce066da209a57985e79abf0a0740:

![image](https://user-images.githubusercontent.com/35271042/113751848-34958200-96c1-11eb-8bc2-60b394e9995a.png)

![image](https://user-images.githubusercontent.com/35271042/113753228-b5a14900-96c2-11eb-94ef-1d24f02138c8.png)

**Comment by Tyriar** [comment]
![image](https://user-images.githubusercontent.com/2193314/113770636-31a58c00-96d7-11eb-94d8-281bda7ee56d.png)

**Comment by pixieaka** [comment]
@Tyriar  You can also add these split options also to the list down there?

![image](https://user-images.githubusercontent.com/17777237/115837046-73913a80-a418-11eb-9a09-89ca7f23ad8c.png)
![image](https://user-images.githubusercontent.com/17777237/115837071-7ab84880-a418-11eb-837b-96eb4e271608.png)

**Comment by Tyriar** [comment]
This list is a bit out of date, will probably close this issue soon in favor of individual issues.

**Comment by pixieaka** [comment]
@Tyriar  Some problems in 633562d

![Animation](https://user-images.githubusercontent.com/17777237/116054665-30370600-a67c-11eb-8066-54846ad5eb22.gif)
![Animation1](https://user-images.githubusercontent.com/17777237/116054770-5361b580-a67c-11eb-9457-b5f3b6f34779.gif)

**Comment by Tyriar** [comment]
@pixieaka I think the bottom one tracked in https://github.com/microsoft/vscode/issues/122161 already, created https://github.com/microsoft/vscode/issues/122187 for top. Thanks 🙂
