### ISSUE TITLE
Iteration Plan for May 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#123368]
This plan captures our work in **May**. This is a 5-week iteration. We will ship in **early June**.

## Endgame
- **May 31, 2021**: Endgame begins
- **June 4, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22May+2021%22).

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22May+2021%22) @isidorn **team**
- [ ] Assess notebook accessibility https://github.com/microsoft/vscode/issues/111255 @rebornix @isidorn @roblourens

### Workbench
- [x] Trusted Folders/Workspaces https://github.com/microsoft/vscode/issues/106488 @lszomoru @sbatten @alexdima @sandy081
   - [x] Introduce workbench banner to explain reduced functional support in untrusted folders @misolori @sbatten @lszomoru
   - [x] User documentation https://github.com/microsoft/vscode/issues/123522 @gregvanl @sbatten
   - [ ] :runner: Engagement with extension authors on adoption trusted folders https://github.com/microsoft/vscode/issues/120251 @TylerLeonhardt @lszomoru
   - [x] Engage with custom editor extensions to ensure editors can load in untrusted folders https://github.com/microsoft/vscode/issues/122992 @lramos15
   - [x] Treat all virtual file systems as untrusted by default https://github.com/microsoft/vscode/issues/123521 @sbatten
   - [x] When in untrusted mode the extension view defaults to extensions requiring a trusted folder https://github.com/microsoft/vscode/issues/123520 @sbatten
   - [x] Explore if we need untrusted domains in trusted folders https://github.com/microsoft/vscode/issues/124325 @jacksonkearl
- [ ] :runner: Improve the welcome pages https://github.com/microsoft/vscode/issues/106715 @jacksonkearl @misolori @digitarald
   - [ ] :runner: Review initial welcome contents and placement https://github.com/microsoft/vscode/issues/122702
   - [x] Explore handling of contributions of newly installed extensions https://github.com/microsoft/vscode/issues/119620#issuecomment-837088610 @JacksonKearl
   - [x] Improve UX for completing items https://github.com/microsoft/vscode/issues/119722 @misolori @digitarald @jacksonkearl
   - [x] Expand the set of `doneOn` clauses available to walkthrough steps https://github.com/microsoft/vscode/issues/122570 @jacksonkearl
   - [ ] :runner: Explore extension contributions to the "New File..." item https://github.com/microsoft/vscode/issues/124304 @misolori
   - [ ] :muscle: Explore integration of release notes and extension changelogs https://github.com/microsoft/vscode/issues/123906 @jacksonkearl
   - [ ] :muscle: Enable a walkthrough based on the files in the workspace https://github.com/microsoft/vscode/issues/121778 @jacksonkearl
   - [ ] :runner: Continue user testing on new welcome pages https://github.com/microsoft/vscode/issues/125117 @digitarald
   - [ ] :runner: Explore Extension content contributions https://github.com/microsoft/vscode/issues/118402 @digitarald
- [ ] :runner: Add support for drag&drop in custom trees https://github.com/microsoft/vscode/issues/32592 @alexr00
- [ ] :muscle: Improve rendering of Extensions Viewlet when the width is narrow https://github.com/microsoft/vscode/issues/118511 @sandy081
- [x] Polish flow of conflicting custom editors after extension install https://github.com/microsoft/vscode/issues/122433 @lramos15
- [ ] :runner: Add support for list of enums in settings editor https://github.com/microsoft/vscode/issues/77458 @rzhao271

#### Web
- [x] Improve iPad support (keyboard/trackpad/mouse and touch) [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aios+milestone%3A%22May+2021%22) @isidorn
   - [x] Editor context menu badly positioned https://github.com/microsoft/vscode/issues/122035
   - [x] Investigate Copy/Paste behavior in Safari https://github.com/microsoft/vscode/issues/109635 @isidorn
   - [x] Explore support for Zen mode https://github.com/microsoft/vscode/issues/106972 @isidorn

### UX
- [ ] :muscle: Continue exploration of profiles https://github.com/microsoft/vscode/issues/116740 @misolori

### Monaco Editor
- [x] Ship new release of the Monaco Editor @hediet @alexdima

### Notebook Editor
- [x] Finalize notebook API https://github.com/microsoft/vscode/issues/122922 @jrieken @rebornix @roblourens
- [x] Explore the notion of notebook profiles https://github.com/microsoft/vscode/issues/122481 @rebornix @roblourens @misolori
- [ ] :runner: Reduce notebook papercut issues https://github.com/microsoft/vscode/issues/113245 @rebornix @jrieken @roblourens
- [x] Adopt workspace trust for notebooks https://github.com/microsoft/vscode/issues/118584 @roblourens
- [ ] :muscle: Collect needs/requirements for marketplace to support notebook content provider and renderers suggestions https://github.com/microsoft/vscode/issues/123581 @rebornix
- [ ] :muscle: Overview ruler https://github.com/microsoft/vscode/issues/96442 @rebornix

#### LSP /LSIF
- [ ] :runner: LSP - Collaborate on "TypeHierarchy" support with the Java extension team @dbaeumer **Java team**
- [ ] :runner: LSP - Add support for a pull model for diagnostics https://github.com/microsoft/language-server-protocol/issues/737 @dbaeumer
#### JavaScript/TypeScript
- [x] Adopt TS v4.3 https://github.com/microsoft/vscode/issues/122884 @mjbvz
- [x] JS/TS initialization doesn't end in virtual workspace setup https://github.com/microsoft/vscode/issues/122979 @mjbvz
- [ ] :runner: Explore improving zero-knowledge onboarding into a well-tuned TS setup (tasks, tests, debugging, etc.) https://github.com/microsoft/vscode/issues/121345 @jacksonkearl @connor4312 @mjbvz @misolori

### Debug
- [x] Adopt Workspace/Folder Trust for debugging https://github.com/microsoft/vscode/issues/124034 @isidorn @connor4312 @weinand
- [x] Surface the new 'hitBreakpointIds' property of the DAP StoppedEvent in the UI https://github.com/microsoft/vscode/issues/118743 @weinand @isidorn
- [ ] :muscle: Investigate debug UI for highly concurrent languages https://github.com/microsoft/vscode/issues/116109 @weinand @connor4312
- [x] Consider surfacing mapped variables https://github.com/microsoft/vscode/issues/12066 @connor4312

#### DAP
- [x] Enable using the `Variable`'s `evaluateName` property instead of the `name` property in the `setVariable` request https://github.com/microsoft/debug-adapter-protocol/issues/188 @weinand

### Testing
- [ ] :runner: Provide consolidated testing support https://github.com/microsoft/vscode/issues/107467 @connor4312 @sandy081
- [ ] Finalize "write" side of testing APIs https://github.com/microsoft/vscode/issues/122208 @connor4312
- [ ] :runner: Review the "read" side of testing APIs to allow for LiveShare support https://github.com/microsoft/vscode/issues/117379 @connor4312
- [x] Investigate test coverage API https://github.com/microsoft/vscode/issues/123713 @connor4312

### Terminal
- [x] Investigate better support for text wrapping with `conpty` https://github.com/microsoft/vscode/issues/91898 @meganrogge
- [x] Node-pty hang/pty unresponsive on Windows https://github.com/microsoft/vscode/issues/71966 @deepak1556 @tyriar
- [x] Polish terminal tabs [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aterminal-tabs+milestone%3A%22May+2021%22) @meganrogge @tyriar
- [x] Polish terminal profiles [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aterminal-profiles+milestone%3A%22May+2021%22) @tyriar @meganrogge
- [x] Support drag and drop between tabs https://github.com/microsoft/vscode/issues/34103 @tyriar
- [x] Support renaming tabs inline like the file explorer https://github.com/microsoft/vscode/issues/122023 @meganrogge @tyriar
- [x] Allow set the tab color https://github.com/microsoft/vscode/issues/121738 @meganrogge @tyriar

### Source Control
- [ ] :muscle: Explore UI additions to help guide users to push to a remote after committing https://github.com/microsoft/vscode/issues/110882 @eamodio

### Tasks
- [x] Adopt terminal indicator for tasks  https://github.com/microsoft/vscode/issues/121659 @alexr00
- [x] Add option to automatically close task terminals when a task has finished https://github.com/microsoft/vscode/issues/112230 @alexr00

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2021%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2021%22+label%3A%22api-proposal%22)

### Extension Contributions
- [x] Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/5022 **team**
- [x] Improvements to the GitHub PR extension [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22May+2021%22) @alexr00 @rmacfarlane

### Engineering
- [x] Migrate to `IProcessEnvService` https://github.com/microsoft/vscode/issues/117873 @bpasero
- [x] Untitled support for custom editors and notebooks https://github.com/microsoft/vscode/issues/121974 @bpasero
- [x] Enable `FileSystemProvider` to stat a file as readonly https://github.com/Microsoft/vscode/issues/73122 @bpasero
- [ ] :runner: Explore support for transient/temporary workspaces https://github.com/microsoft/vscode/issues/119695 @bpasero
- [ ] :runner: Search editor: leverage text file model support and behave like normal text editors https://github.com/microsoft/vscode/issues/118947 @jacksonkearl
- [ ] :hand: Enable process reuse https://github.com/microsoft/vscode/issues/120431 @rzhao271
- [ ] :runner: Support searching in `iframe` https://github.com/microsoft/vscode/issues/96307 @rzhao271
- [x] Fix `document.hasFocus()` returning true for multiple windows https://github.com/microsoft/vscode/issues/122352 @rzhao271 @deepak1556
#### Builds
- [x] Consolidate publishing of build artifacts https://github.com/microsoft/vscode/issues/117891 @TylerLeonhardt @joaomoreno
- [x] Migrate to the new build process for language packs https://github.com/microsoft/vscode/issues/124035 @tylerleonhardt @dbaeumer
#### Electron
- [ ] :hand: Scroll performance on Windows https://github.com/microsoft/vscode/issues/107016 @deepak1556
- [x] Investigate crash reporter to monitor only specific child processes on mac https://github.com/microsoft/vscode/issues/118767 @deepak1556
- [x] Investigate slow startup time on windows https://github.com/microsoft/vscode/issues/121377 @deepak1556
- [x] Fix `cwd` option for `child_process` on mac https://github.com/microsoft/vscode/issues/118267 @deepak1556
#### Node.js-free, sand-boxed renderer
- [ ] :runner: Backlog https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556 @rzhao271

------
### Deferred
- None.

**Comment by githubnew-pro** [comment]
> این طرح کار ما در **ماه مه** را به تصویر می کشد . این یک تکرار 5 هفته ای است. ما در کشتی خواهد **اوایل ماه ژوئن** .
> 
> ## بازی آخر
> * **31 مه 2021** : پایان بازی آغاز می شود
> * **4 ژوئن 2021** : پایان بازی تمام شد
> 
> جزئیات بازی آخر این تکرار در [اینجا](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22May+2021%22) دنبال می [شود](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22May+2021%22) .
> 
> ## موارد را برنامه ریزی کنید
> در زیر خلاصه ای از موارد برنامه سطح بالا آورده شده است.
> 
> افسانه حاشیه نویسی:
> 
> علامت گذاری	شرح
> 🏃	کار در حال انجام
> ✋	کار مسدود شده
> 💪	هدف کششی برای این تکرار
> 🔴	مرجع شماره گمشده
> 🔵	تحقیقات بیشتر برای رفع عدم اطمینان لازم است
> ⚫	تحت بحث در تیم است
> ⬛	یک مورد بزرگ ، بزرگتر از یک تکرار
> ### دسترسی
> * [ ] مسائل دسترسی، و [جستجوهای ](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22May+2021%22) isidorn  **تیم**
> * [ ]  🏃ارزیابی نوت بوک دسترسی [# 111255 ](https://github.com/microsoft/vscode/issues/111255) rebornix  isidorn  roblourens
> 
> ### میز کار
> * [ ]  🏃پوشه مورد اعتماد / فضاهای کاری [# 106488 ](https://github.com/microsoft/vscode/issues/106488) lszomoru  sbatten  alexdima  @ sandy081
>   
>   * [ ]  🏃معرفی بنر میز کار برای توضیح حمایت کاربردی کاهش در پوشه های غیر قابل اطمینان misolori  sbatten  lszomoru
>   * [ ] مستندات کاربر [# 123522](https://github.com/microsoft/vscode/issues/123522)
>   * [ ]  🏃 Engagement with extension authors on adoption trusted folders #120251 @TylerLeonhardt @lszomoru
>   * [ ]  🏃 Engage with custom editor extensions to ensure editors can load in untrusted folders #122992 @lramos15
>   * [ ]  Treat all virtual file systems as untrusted by default #123521 @sbatten
>   * [x]  When in untrusted mode the extension view defaults to extensions requiring a trusted folder #123520 @sbatten
>   * [ ]  🔴 Explore if we need untrusted domains in trusted folders @JacksonKearl
> * [ ]  🏃 Improve the welcome pages #106715 @JacksonKearl @misolori @digitarald
>   
>   * [ ]  Review initial welcome contents and placement #122702
>   * [ ]  🔴 Explore handling of contributions of newly installed extensions
>   * [ ]  🏃 Improve UX for completing items #119722 @misolori @digitarald @JacksonKearl
>   * [ ]  Expand the set of `doneOn` clauses available to walkthrough steps #122570 @JacksonKearl
>   * [ ]  🔴 🏃 Explore extension contributions to the "New File..." item @misolori
>   * [ ]  🔴 💪 Explore integration of release notes and extension changelogs @JacksonKearl
>   * [ ]  💪 Enable a walkthrough based on the files in the workspace #121778 @JacksonKearl
>   * [ ]  🔴 🏃 Continue user testing on new welcome pages @digitarald
>   * [ ]  🏃 Explore Extension content contributions #118402 @digitarald
> * [ ]  🏃 Add support for drag&drop in custom trees #32592 @alexr00
> * [ ]  💪 Improve rendering of Extensions Viewlet when the width is narrow #118511 @sandy081
> * [ ]  💪 Polish flow of conflicting custom editors after extension install #122433 @lramos15
> 
> #### Web
> * [ ]  🏃 Improve iPad support (keyboard/trackpad/mouse and touch) [query](https://github.com/microsoft/vscode/labels/ios) @isidorn
>   
>   * [ ]  Editor context menu badly positioned #122035
>   * [ ]  Investigate Copy/Paste behavior in Safari #109635 @isidorn
>   * [ ]  Explore support for Zen mode #106972 @isidorn
> 
> ### UX
> * [ ]  💪 Continue exploration of profiles #116740 @misolori
> 
> ### Monaco Editor
> * [ ]  🔴 Ship new release of the Monaco Editor @hediet @alexdima
> 
> ### Notebook Editor
> * [ ]  🏃 Finalize notebook API #122922 @jrieken @rebornix @roblourens
> * [ ]  Explore the notion of notebook profiles #122481 @rebornix @roblourens @misolori
> * [ ]  🏃 Reduce notebook papercut issues #113245 @rebornix @jrieken @roblourens
> * [ ]  🏃 Adopt workspace trust for notebooks #118584 @roblourens
> * [ ]  💪 Collect needs/requirements for marketplace to support notebook content provider and renderers suggestions #123581 @rebornix
> * [ ]  💪 Overview ruler #96442 @rebornix
> 
> ### Languages
> #### LSP /LSIF
> * [ ]  🏃 LSP - Collaborate on "TypeHierarchy" support with the Java extension team @dbaeumer **Java team**
> * [ ]  🏃 LSP - Add support for a pull model for diagnostics [microsoft/language-server-protocol#737](https://github.com/microsoft/language-server-protocol/issues/737) @dbaeumer
> 
> #### JavaScript/TypeScript
> * [ ]  🏃 Adopt TS v4.3 #122884 @mjbvz
> * [x]  JS/TS initialization doesn't end in virtual workspace setup #122979 @mjbvz
> * [ ]  🏃 Explore improving zero-knowledge onboarding into a well-tuned TS setup (tasks, tests, debugging, etc.) #121345 @JacksonKearl @connor4312 @mjbvz @misolori
> 
> ### Debug
> * [ ]  🔴 Adopt Workspace/Folder Trust for debugging @isidorn @connor4312 @weinand
> * [ ]  Surface the new 'hitBreakpointIds' property of the DAP StoppedEvent in the UI #118743 @weinand @isidorn
> * [ ]  💪 Investigate debug UI for highly concurrent languages #116109 @weinand @connor4312
> * [ ]  💪 Consider surfacing mapped variables #12066 @connor4312
> 
> #### DAP
> * [ ]  Enable using the `Variable`'s `evaluateName` property instead of the `name` property in the `setVariable` request [microsoft/debug-adapter-protocol#188](https://github.com/microsoft/debug-adapter-protocol/issues/188) @weinand
> 
> ### Testing
> * [ ]  🏃 Provide consolidated testing support #107467 @connor4312 @sandy081
> * [ ]  🔴 Review the "read" side of testing APIs to allow for LiveShare support @connor4312
> * [ ]  🔴 💪 Investigate test coverage API @connor4312
> 
> ### Terminal
> * [ ]  Investigate better support for text wrapping with `conpty` #91898 @meganrogge
> * [ ]  🏃 Node-pty hang/pty unresponsive on Windows #71966 @deepak1556 @Tyriar
> * [ ]  🏃 Polish terminal tabs [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aintegrated-terminal-tabs+milestone%3A%22May+2021%22) @meganrogge @Tyriar
> * [ ]  🏃 💪 Support drag and drop between tabs #34103 @Tyriar
> * [ ]  💪 Support renaming tabs inline like the file explorer #122023 @Tyriar
> * [ ]  🏃 💪 Allow set the tab color #121738 @meganrogge @Tyriar
> 
> ### Source Control
> * [ ]  💪 Explore UI additions to help guide users to push to a remote after committing #110882 @eamodio
> 
> ### Tasks
> * [ ]  Adopt terminal indicator for tasks  #121659 @alexr00
> * [ ]  🏃 Add option to automatically close task terminals when a task has finished #112230 @alexr00
> 
> ### API
> * API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2021%22+label%3A%22api-finalization%22)
> * API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2021%22+label%3A%22api-proposal%22)
> 
> ### Extension Contributions
> * [ ]  Improvements to the Remote extensions [microsoft/vscode-remote-release#5022](https://github.com/microsoft/vscode-remote-release/issues/5022) **team**
> * [ ]  Improvements to the GitHub PR extension [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22May+2021%22) @alexr00 @RMacfarlane
> 
> ### Engineering
> * [x]  Migrate to IProcessEnvService #117873 @bpasero
> * [ ]  🏃 Untitled support for custom editors #121974 @bpasero
> * [x]  🏃 Enable `FileSystemProvider` to stat a file as readonly #73122 @bpasero
> * [ ]  Explore support for transient/temporary workspaces #119695 @bpasero
> * [ ]  🏃 Search editor: leverage text file model support and behave like normal text editors #118947 @JacksonKearl
> * [ ]  Enable process reuse #120431 @rzhao271
> * [ ]  Support searching in `iframe` #96307 @rzhao271
> * [ ]  Fix `document.hasFocus()` returning true for multiple windows #122352 @rzhao271
> 
> #### Builds
> * [ ]  🏃 Consolidate publishing of build artifacts #117891 @TylerLeonhardt @joaomoreno
> * [ ]  🔴 Migrate to the new build process for language packs @TylerLeonhardt @dbaeumer
> 
> #### Electron
> * [ ]  Scroll performance on Windows #107016 @deepak1556
> * [ ]  Fix crash reporter to monitor only specific child processes #118767 @deepak1556
> * [ ]  Investigate slow startup time on windows #121377 @deepak1556
> * [ ]  Fix `cwd` option for `child_process` on mac #118267 @deepak1556
> 
> #### Node.js-free, sand-boxed renderer
> * [ ]  🏃 Backlog #92164 @bpasero @deepak1556 @rzhao271
> 
> ### Deferred
> * None.

**Comment by githubnew-alt** [comment]
> این طرح کار ما در **ماه مه** را به تصویر می کشد . این یک تکرار 5 هفته ای است. ما در کشتی خواهد **اوایل ماه ژوئن** .
> 
> ## بازی آخر
> * **31 مه 2021** : پایان بازی آغاز می شود
> * **4 ژوئن 2021** : پایان بازی تمام شد
> 
> جزئیات بازی آخر این تکرار در [اینجا](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22May+2021%22) دنبال می [شود](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22May+2021%22) .
> 
> ## موارد را برنامه ریزی کنید
> در زیر خلاصه ای از موارد برنامه سطح بالا آورده شده است.
> 
> افسانه حاشیه نویسی:
> 
> علامت گذاری	شرح
> 🏃	کار در حال انجام
> ✋	کار مسدود شده
> 💪	هدف کششی برای این تکرار
> 🔴	مرجع شماره گمشده
> 🔵	more investigation required to remove uncertainty
> ⚫	under discussion within the team
> ⬛	a large work item, larger than one iteration
> ### Accessibility
> * [ ]  🏃 Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22May+2021%22) @isidorn **team**
> * [ ]  Assess notebook accessibility #111255 @rebornix @isidorn @roblourens
> 
> ### Workbench
> * [ ]  🏃 Trusted Folders/Workspaces #106488 @lszomoru @sbatten @alexdima @sandy081
>   
>   * [x]  🏃 Introduce workbench banner to explain reduced functional support in untrusted folders @misolori @sbatten @lszomoru
>   * [ ]  🏃 User documentation #123522 @gregvanl @sbatten
>   * [ ]  🏃 Engagement with extension authors on adoption trusted folders #120251 @TylerLeonhardt @lszomoru
>   * [x]  Engage with custom editor extensions to ensure editors can load in untrusted folders #122992 @lramos15
>   * [x]  Treat all virtual file systems as untrusted by default #123521 @sbatten
>   * [x]  When in untrusted mode the extension view defaults to extensions requiring a trusted folder #123520 @sbatten
>   * [x]  Explore if we need untrusted domains in trusted folders #124325 @JacksonKearl
> * [ ]  🏃 Improve the welcome pages #106715 @JacksonKearl @misolori @digitarald
>   
>   * [ ]  Review initial welcome contents and placement #122702
>   * [x]  Explore handling of contributions of newly installed extensions [#119620 (comment)](https://github.com/microsoft/vscode/issues/119620#issuecomment-837088610) @JacksonKearl
>   * [x]  Improve UX for completing items #119722 @misolori @digitarald @JacksonKearl
>   * [x]  🏃 Expand the set of `doneOn` clauses available to walkthrough steps #122570 @JacksonKearl
>   * [ ]  🏃 Explore extension contributions to the "New File..." item #124304 @misolori
>   * [ ]  💪 Explore integration of release notes and extension changelogs #123906 @JacksonKearl
>   * [ ]  💪 Enable a walkthrough based on the files in the workspace #121778 @JacksonKearl
>   * [ ]  🔴 🏃 Continue user testing on new welcome pages @digitarald
>   * [ ]  🏃 Explore Extension content contributions #118402 @digitarald
> * [ ]  🏃 Add support for drag&drop in custom trees #32592 @alexr00
> * [ ]  💪 Improve rendering of Extensions Viewlet when the width is narrow #118511 @sandy081
> * [x]  Polish flow of conflicting custom editors after extension install #122433 @lramos15
> * [ ]  🏃 Add support for list of enums in settings editor #77458 @rzhao271
> 
> #### Web
> * [ ]  🏃 Improve iPad support (keyboard/trackpad/mouse and touch) [query](https://github.com/microsoft/vscode/labels/ios) @isidorn
>   
>   * [ ]  Editor context menu badly positioned #122035
>   * [x]  Investigate Copy/Paste behavior in Safari #109635 @isidorn
>   * [x]  Explore support for Zen mode #106972 @isidorn
> 
> ### UX
> * [ ]  💪 Continue exploration of profiles #116740 @misolori
> 
> ### Monaco Editor
> * [x]  Ship new release of the Monaco Editor @hediet @alexdima
> 
> ### Notebook Editor
> * [ ]  🏃 Finalize notebook API #122922 @jrieken @rebornix @roblourens
> * [ ]  🏃 Explore the notion of notebook profiles #122481 @rebornix @roblourens @misolori
> * [ ]  🏃 Reduce notebook papercut issues #113245 @rebornix @jrieken @roblourens
> * [x]  Adopt workspace trust for notebooks #118584 @roblourens
> * [ ]  💪 Collect needs/requirements for marketplace to support notebook content provider and renderers suggestions #123581 @rebornix
> * [ ]  💪 Overview ruler #96442 @rebornix
> 
> ### Languages
> #### LSP /LSIF
> * [ ]  🏃 LSP - Collaborate on "TypeHierarchy" support with the Java extension team @dbaeumer **Java team**
> * [ ]  🏃 LSP - Add support for a pull model for diagnostics [microsoft/language-server-protocol#737](https://github.com/microsoft/language-server-protocol/issues/737) @dbaeumer
> 
> #### JavaScript/TypeScript
> * [ ]  🏃 Adopt TS v4.3 #122884 @mjbvz
> * [x]  JS/TS initialization doesn't end in virtual workspace setup #122979 @mjbvz
> * [ ]  🏃 Explore improving zero-knowledge onboarding into a well-tuned TS setup (tasks, tests, debugging, etc.) #121345 @JacksonKearl @connor4312 @mjbvz @misolori
> 
> ### Debug
> * [x]  Adopt Workspace/Folder Trust for debugging #124034 @isidorn @connor4312 @weinand
> * [x]  Surface the new 'hitBreakpointIds' property of the DAP StoppedEvent in the UI #118743 @weinand @isidorn
> * [ ]  💪 Investigate debug UI for highly concurrent languages #116109 @weinand @connor4312
> * [x]  💪 Consider surfacing mapped variables #12066 @connor4312
> 
> #### DAP
> * [x]  Enable using the `Variable`'s `evaluateName` property instead of the `name` property in the `setVariable` request [microsoft/debug-adapter-protocol#188](https://github.com/microsoft/debug-adapter-protocol/issues/188) @weinand
> 
> ### Testing
> * [x]  Provide consolidated testing support #107467 @connor4312 @sandy081
> * [x]  Finalize "write" side of testing APIs #122208 @connor4312
> * [ ]  🏃 Review the "read" side of testing APIs to allow for LiveShare support #117379 @connor4312
> * [x]  Investigate test coverage API #123713 @connor4312
> 
> ### Terminal
> * [x]  Investigate better support for text wrapping with `conpty` #91898 @meganrogge
> * [x]  Node-pty hang/pty unresponsive on Windows #71966 @deepak1556 @Tyriar
> * [x]  Polish terminal tabs [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aterminal-tabs+milestone%3A%22May+2021%22) @meganrogge @Tyriar
> * [x]  🏃 Polish terminal profiles [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aterminal-profiles+milestone%3A%22May+2021%22) @Tyriar @meganrogge
> * [x]  Support drag and drop between tabs #34103 @Tyriar
> * [x]  Support renaming tabs inline like the file explorer #122023 @meganrogge @Tyriar
> * [x]  Allow set the tab color #121738 @meganrogge @Tyriar
> 
> ### Source Control
> * [ ]  💪 Explore UI additions to help guide users to push to a remote after committing #110882 @eamodio
> 
> ### Tasks
> * [x]  Adopt terminal indicator for tasks  #121659 @alexr00
> * [x]  Add option to automatically close task terminals when a task has finished #112230 @alexr00
> 
> ### API
> * API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2021%22+label%3A%22api-finalization%22)
> * API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2021%22+label%3A%22api-proposal%22)
> 
> ### Extension Contributions
> * [ ]  🏃 Improvements to the Remote extensions [microsoft/vscode-remote-release#5022](https://github.com/microsoft/vscode-remote-release/issues/5022) **team**
> * [ ]  🏃 Improvements to the GitHub PR extension [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22May+2021%22) @alexr00 @RMacfarlane
> 
> ### Engineering
> * [x]  Migrate to `IProcessEnvService` #117873 @bpasero
> * [ ]  🏃 Untitled support for custom editors and notebooks #121974 @bpasero
> * [x]  Enable `FileSystemProvider` to stat a file as readonly #73122 @bpasero
> * [ ]  Explore support for transient/temporary workspaces #119695 @bpasero
> * [ ]  🏃 Search editor: leverage text file model support and behave like normal text editors #118947 @JacksonKearl
> * [ ]  ✋ Enable process reuse #120431 @rzhao271
> * [ ]  ✋ Support searching in `iframe` #96307 @rzhao271
> * [x]  Fix `document.hasFocus()` returning true for multiple windows #122352 @rzhao271 @deepak1556
> 
> #### Builds
> * [x]  Consolidate publishing of build artifacts #117891 @TylerLeonhardt @joaomoreno
> * [ ]  🏃 Migrate to the new build process for language packs #124035 @TylerLeonhardt @dbaeumer
> 
> #### Electron
> * [ ]  ✋ Scroll performance on Windows #107016 @deepak1556
> * [x]  Fix crash reporter to monitor only specific child processes #118767 @deepak1556
> * [x]  Investigate slow startup time on windows #121377 @deepak1556
> * [x]  Fix `cwd` option for `child_process` on mac #118267 @deepak1556
> 
> #### Node.js-free, sand-boxed renderer
> * [ ]  🏃 Backlog #92164 @bpasero @deepak1556 @rzhao271
> 
> ### Deferred
> * None.
