### ISSUE TITLE
VS Code Live Server - June Iteration Plans

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#124608]
This tracks the upcoming work on the Live Server, which is described in #124607. Some of these may be deferred to the July iteration. See backlog #125343

Bug Fixes:
- [x] External links on browser are broken. #125200 
- [x] Relative file links in sub-folders are not working. #125201
- [x] Make hosting port flexible + have error handling for if ports are occupied. #125152
- [x] Two refreshes when file change happens #125174
- [x] Filenames end in slash in index menu #125178
- [x] Handle situation if `index.html` does not exist (can show page with all of the files to pick).
- [x] Fix `Upgrade Required` when using localhost instead of 127.0.0.1
- [x] Support Emojis on html files

Features:
- [x] Basic Implementation of Default Page Index/Filesystem Navigation
- [x] Basic Implementation of "Page Not Found" 
- [x] Allow window reload to show last visible file in preview (currently always shows `index.html`)
- [x] Allow users to choose which file to display using active editor. #125775
- [x] Implement more visual way of showing server is on or off. #125854
- [x] Allow user settings to tweak experience #125855
- [x] Explore best UX experience for users. #125949 #126307
  - [x] Server run using tasks #126309
- [x] Page title support on embedded preview.
- [x] Non-workspace Support #126715
- [x] 💪SVG Preview Support #126093
- [x] Release Docs + Code Cleanup #126308
- [x] Link Preview #127019
- [x] Multi-root workspaces #126622 

Admin:
- [x] Transfer repo ownership to Microsoft
- [x] Look into extension bundling for smaller `*.vsix` size (bundling)
- [x] Upload to marketplace.
