### ISSUE TITLE
Terminal editors June plan

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#125514]
This is a plan for terminal tabs issue: https://github.com/microsoft/vscode/issues/10546, I read through all the comments on that issue while coming up with the below.

**If you have feedback on this feature, please put it in https://github.com/microsoft/vscode/issues/10546**

## Philosophy

The terminal view is convenient, it's nice to have all terminals in a single space where you can reliably go to in order to see all your terminals. Having said that, some people don't like the terminal panel and would prefer to work with editors. There are a few reasons for this:

- They want to use a true grid view with more than 1 dimension - this isn't implemented in the terminal view to keep things simple and lightweight.
- They want terminals that are persistent and will always be visible regardless of panel state.
- They want to save the panel's real estate for something else like the debug console or problems.
- They want to make better use of monitors.
- They want to temporarily use a terminal on the side to give it more real estate and use as a reference - this is something I use a text editors in a second editor group for.
- They want to have a single full screen editor group, being able to switch to the terminal without messing with its dimensions

The plan is to make terminal editors optional/opt-in. If the user doesn't want to use them, then they probably wouldn't even notice they exist. Terminal editors will complement the existing terminal tabs, both can be used if the user wants.

## Tasks

For an up to date list of tasks check [this query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22June+2021%22+label%3Aterminal-editors).

- [x] MVP - merge to main when done
  - https://github.com/microsoft/vscode/issues/126244 @meganrogge 
  - https://github.com/microsoft/vscode/issues/126243 @Tyriar
    - https://github.com/microsoft/vscode/issues/118276 @Tyriar
  - [x] Commands
    - https://github.com/microsoft/vscode/issues/126247 @Tyriar
    - https://github.com/microsoft/vscode/issues/126248 @Tyriar
- https://github.com/microsoft/vscode/issues/126243 @Tyriar 
- [x] Settings
  - https://github.com/microsoft/vscode/issues/126249 @meganrogge 
- https://github.com/microsoft/vscode/issues/126250 @meganrogge 
- https://github.com/microsoft/vscode/issues/126252 @meganrogge
- https://github.com/microsoft/vscode/issues/126471 @meganrogge
- [ ] Drag and drop
  - https://github.com/microsoft/vscode/issues/126251 @Tyriar
  - https://github.com/microsoft/vscode/issues/126633
  - 💪 https://github.com/microsoft/vscode/issues/126492
  - 💪 https://github.com/microsoft/vscode/issues/126387
- [x] Context menus
  - 💪 https://github.com/microsoft/vscode/issues/126254
  - https://github.com/microsoft/vscode/issues/126255
- 💪 https://github.com/microsoft/vscode/issues/126256
- 💪 https://github.com/microsoft/vscode/issues/127158
- https://github.com/microsoft/vscode/issues/126689 @Tyriar
- https://github.com/microsoft/vscode/issues/126525 @meganrogge 
- 💪 https://github.com/microsoft/vscode/issues/127193

## Verification

List of some things to make sure that they work during development and also to add to the test plan at the end of the iteration.

- [ ] Ensure API `Terminal.show` works for terminal editors
- [x] Ensure tab color, icon works for terminal editors
- [x] Status works for terminal editors, including the task running animation
- [x] Ensure status hover shows when hovering terminal editor tabs
- [x] Backgrounded terminal editors on reload should be restored correctly - the process should reconnect but the editor should not be created until focused
- [x] Ensure terminal editors are always pinned
- [x] Linux/Windows: Does ctrl+w close the tab as expected? (tracked in https://github.com/microsoft/vscode/issues/127189)
- [x] Does split editor (cmd/ctrl+\) work as expected within the terminal editor?
- [x] Does split terminal command work as expected within the terminal editor?
- [ ] Reconnected terminal editors don't resize terminal unless the window size has changed
- [ ] Work as expected in test resolver?
- [x] Work as expected in Web?
- [ ] Try live share

## Investigations

Some unknowns/explorations to consider after the main parts are done.

- [x] Consider setting to include editor terminals in next/previous terminal commands?
  - Will wait for feedback, editor nav commands will likely be enough
- [x] Investigate lock editor group/secondary editor concept - Deferred to https://github.com/microsoft/vscode/issues/124709
- [x] Keybindings? Create terminal is [option+T in Cloud9](https://www.shortcutfoo.com/app/dojos/cloud9-win/cheatsheet)
  - Let's leave keybindings out of the initial release, option+T seems like an odd choice, maybe better ideas will come in
- [x] How should ctrl+shift+t interact with closed terminal editors? Should the processes stick around for x seconds in case it was closed accidentally?
  - Always prompt for terminal editors?
  - confirmOnExit interaction? https://github.com/microsoft/vscode/issues/23808
  - Will wait for feedback
- [x] Is there anything else we should do wrt discoverability?
  - I think this is covered sufficiently with context menus, dragging and dropping and the registered commands
- [x] Support detaching terminals https://github.com/microsoft/vscode/issues/118276
- [x] Do a once over of all terminal commands, are there any others we need to handle specially?
  - Being tackled in #126471
- [x] Can/should the terminal editor code be loaded asynchronously since it's an optional feature?
  - Not possible due to how editors are registered, saving would also be very minimal and probably not worth it anyway
- [x] Breadcrumbs integration? Show cwd on macOS/Linux?
  - Will wait for feedback

## References

- Atom terminal-tab https://atom.io/packages/terminal-tab, https://github.com/microsoft/vscode/issues/10546#issuecomment-377086938
- VS Code Terminal Tab extension using webviews by @mmis1000 https://github.com/mmis1000/Vscode-terminal-tab

**Comment by Tyriar** [comment]
Locking as this is just for planning, please put any feedback on the main issue https://github.com/microsoft/vscode/issues/10546

**Comment by Tyriar** [comment]
Calling this done, there are a few items that didn't make the cut that will probably be done in next iteration
