### ISSUE TITLE
Iteration Plan for June 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#126181]
This plan captures our work in **June**. This is a 4-week iteration. We will ship in **early July**.

## Endgame
- **June 28, 2021**: Endgame
- **July 2, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22June+2021%22).

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22June+2021%22) @isidorn **team**
- [ ] :runner: Assess notebook accessibility [vscode#111255](https://github.com/microsoft/vscode/issues/111255) @rebornix @isidorn @roblourens

### Workbench
- [ ] :red_circle: Trusted Folders/Workspaces @lszomoru @sbatten
   - [ ] :runner: Investigate what it means to support the notion of trust for virtual workspaces [vscode#126913](https://github.com/microsoft/vscode/issues/126913) @sbatten @lszomoru
   - [ ] :runner: Engagement with extension authors on adoption trusted folders [vscode#120251](https://github.com/microsoft/vscode/issues/120251) @lszomoru @sbatten
- [ ] :runner: Improve the welcome pages [vscode#106715](https://github.com/microsoft/vscode/issues/106715) @jacksonkearl @misolori @digitarald
   - [x] Reclaim "Welcome" page for the current "Getting Started" page [vscode#126419](https://github.com/microsoft/vscode/issues/126419) @jacksonkearl
   - [x] Polish the graphics presented in the out-of-the-box walkthroughs [vscode#125877](https://github.com/microsoft/vscode/issues/125877) @daviddossett @digitarald
   - [x] Polish how the user can manage the tiles on the welcome page [vscode#126420](https://github.com/microsoft/vscode/issues/126420) @JacksonKearl @misolori
   - [x] Improve presentation of new tiles and presentation of a larger number of tiles [vscode#127196](https://github.com/microsoft/vscode/issues/127196) @JacksonKearl @misolori
   - [ ] :runner: Continue user testing on new welcome pages [vscode#125117](https://github.com/microsoft/vscode/issues/125117) @digitarald
   - [ ] :runner: Explore Extension content contributions [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald
   - [ ] :muscle: Enable a walkthrough based on the files in the workspace [vscode#121778](https://github.com/microsoft/vscode/issues/121778) @jacksonkearl
- [ ] :muscle: Explore consolidated presentation of release notes and change logs, see also [vscode#123906](https://github.com/microsoft/vscode/issues/123906) @jacksonkearl @misolori @digitarald
- [x] Explore universal, extensible "New..." to make it easier to create new files or notebooks, see also [vscode#124304](https://github.com/microsoft/vscode/issues/124304) @JacksonKearl @misolori
- [x] Add support for detail messages in notifications/dialogs [vscode#125750](https://github.com/microsoft/vscode/issues/125750) @jrieken
- [x] Add support for rich hovers in statusbar items [vscode#126258](https://github.com/microsoft/vscode/issues/126258) @aeschli
- [ ] :runner: Add support for drag&drop in custom trees [vscode#32592](https://github.com/microsoft/vscode/issues/32592) @alexr00
- [ ] :runner: Allow opening all new editors in a dedicated editor group [vscode#124709](https://github.com/microsoft/vscode/issues/124709) @bpasero @misolori
- [x] Improvements to the setting editor [vscode#77458](https://github.com/microsoft/vscode/issues/77458) [vscode#125958](https://github.com/microsoft/vscode/issues/125958) [vscode#79571](https://github.com/microsoft/vscode/issues/79571) [vscode#126089](https://github.com/microsoft/vscode/issues/126089) @rzhao271
- [x] Disable dependent extension if one of its dependency is disabled [vscode#122448](https://github.com/microsoft/vscode/issues/122448) @sandy081
- [ ] :muscle: Add support for rich hovers in the Extensions view [vscode#126479](https://github.com/microsoft/vscode/issues/126479) @sandy081
- [ ] :muscle: Improve rendering of Extensions Viewlet when the width is narrow [vscode#118511](https://github.com/microsoft/vscode/issues/118511) @sandy081
- [x] Settings sync: Provide easier access to the logs [vscode#125687](https://github.com/microsoft/vscode/issues/125687) @sandy081

#### Web
- [ ] :runner: Improve iPad support (keyboard/trackpad/mouse and touch) [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aios-ipados+milestone%3A%22June+2021%22) @isidorn

### UX
- [ ] :red_circle: :runner: Explore how to cycle through inline completion proposals @misolori @hediet
- [ ] :muscle: Continue exploration of profiles [vscode#116740](https://github.com/microsoft/vscode/issues/116740) @misolori
- [ ] :red_circle: :muscle: Explore improvements to the end-to-end experience of opening your first Jupyter notebook @misolori **team**

### Code Editor
- [x] Improve inline completion support [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Ahediet+milestone%3A%22June+2021%22) @hediet
- [x] Improve editor decoration support (move away from using CSS `::after`) root cause of [vscode#125123](https://github.com/microsoft/vscode/issues/125123) and other issues @hediet @alexdima
- [x] Publish a new Monaco editor release @hediet

#### Notebook Editor
- [ ] :red_circle: :runner: Improve discoverability of notebook layout and behavior customizability @misolori @rebornix @roblourens
- [ ] :runner: Improve rendering jitter in notebooks [vscode#126432](https://github.com/microsoft/vscode/issues/126432) @roblourens @mjbvz
- [ ] :runner: Fully support markup rendering in notebooks [vscode#126417](https://github.com/microsoft/vscode/issues/126417) @mjbvz
- [ ] :runner: Reduce notebook papercut issues [vscode#113245](https://github.com/microsoft/vscode/issues/113245) @rebornix @jrieken @roblourens
- [ ] :muscle: Collect needs/requirements for marketplace to support notebook content provider and renderers suggestions [vscode#123581](https://github.com/microsoft/vscode/issues/123581) @rebornix
- [ ] :muscle: Overview ruler [vscode#96442](https://github.com/microsoft/vscode/issues/96442) @rebornix
- [x] :runner: Update Notebook API Docs [vscode-docs#4604](https://github.com/microsoft/vscode-docs/issues/4604) @tanhakabir
#### Jupyter Notebooks
- [ ] :runner: Replace the webview-based interactive window with a built-in one [vscode#126415](https://github.com/microsoft/vscode/issues/126415) @rebornix @joyceerhl
- [ ] :runner: Explore debugging in Jupyter notebooks (line-by-line versus full debugging support) [vscode#126431](https://github.com/microsoft/vscode/issues/126431) @roblourens @weinand @DavidKutu

### Authentication
- [x] Improve GitHub auth provider [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aauthentication+milestone%3A%22June+2021%22) @tylerleonhardt

### Install
- [x] `winget`: support updates of the VS Code Insider release [vscode#126980](https://github.com/microsoft/vscode/issues/126980) @lszomoru

### Languages
- [x] Finalize support for richer completion item detail rendering [vscode#39441](https://github.com/microsoft/vscode/issues/39441) @jrieken
#### LSP /LSIF
- [x] LSP - Collaborate on "TypeHierarchy" support with the Java extension team @dbaeumer **Java team** https://github.com/microsoft/language-server-protocol/pull/1231
- [x] LSP - Add support for a pull model for diagnostics [language-server-protocol#737](https://github.com/microsoft/language-server-protocol/issues/737) @dbaeumer
#### JavaScript/TypeScript
- [ ] :runner: Explore improving zero-knowledge onboarding into a well-tuned TS setup (tasks, tests, debugging, etc.) [vscode#121345](https://github.com/microsoft/vscode/issues/121345) @jacksonkearl @connor4312 @mjbvz @misolori
#### Python
- [x] :red_circle: Explore support for untrusted folders @brettcannon
- [ ] :runner: Explore improvements to the debugging experience [vscode#126463](https://github.com/microsoft/vscode/issues/126463) @weinand @isidorn @luabud

### Debug
- [x] Improve editor run action by using the new split button [vscode#117722](https://github.com/microsoft/vscode/issues/117722) @weinand @isidorn
- [x] Investigate support for setting a value in the Watch view [vscode#115063](https://github.com/microsoft/vscode/issues/115063) @weinand @isidorn
- [ ] :muscle: :runner: Investigate in UI for debugging highly concurrent languages [vscode#116109](https://github.com/microsoft/vscode/issues/116109) @weinand
- [ ] :muscle: Explore integration of a memory inspector : [vscode-js-debug#1008](https://github.com/microsoft/vscode-js-debug/issues/1008) @connor4312
#### DAP
- [x] Support for a new `WriteMemoryRequest` if debuggee permits to [debug-adapter-protocol#163](https://github.com/microsoft/debug-adapter-protocol/issues/163) @weinand
- [ ] :runner: Add new Memory Event to refresh an address range [debug-adapter-protocol#194](https://github.com/microsoft/debug-adapter-protocol/issues/194) @weinand

### Testing
- [ ] :runner: Provide consolidated testing support [vscode#107467](https://github.com/microsoft/vscode/issues/107467) @connor4312 @sandy081
- [ ] :runner: Finalize testing APIs [vscode#122208](https://github.com/microsoft/vscode/issues/122208) [vscode#117379](https://github.com/microsoft/vscode/issues/117379) @connor4312 @jrieken @mjbvz
- [ ] :runner: Explore APIs for test coverage [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312

### Terminal
- [x] Support Terminals in editor tabs [vscode#10546](https://github.com/microsoft/vscode/issues/10546), [vscode#125514](https://github.com/microsoft/vscode/issues/125514) @tyriar @meganrogge @bpasero

### Source Control
- None.

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2021%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2021%22+label%3A%22api-proposal%22)
- [x] Collaborate with extension authors to adopt the new [statusbar id and name properties API](https://code.visualstudio.com/updates/v1_57#_status-bar-item-id-and-name-properties) @bpasero

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#5183](https://github.com/microsoft/vscode-remote-release/issues/5183) @alexr00 @roblourens @chrmarti
- [x] Improvements to the GitHub PR extension [vscode-pull-request-github#2775](https://github.com/microsoft/vscode-pull-request-github/issues/2775) @alexr00
- [x] Remote Repositories extension [vscode-remote-repositories-github#12](https://github.com/microsoft/vscode-remote-repositories-github/issues/12) @eamodio @JacksonKearl @alexr00

### Engineering
- [x] Support searching in `iframe` [vscode#96307](https://github.com/microsoft/vscode/issues/96307) @rzhao271
- [x] Switch to using untyped editor inputs externally for better lifecycle management [vscode#124351](https://github.com/microsoft/vscode/issues/124351) @lramos15
- [x] Add untitled resource support to override service [vscode#124352](https://github.com/microsoft/vscode/issues/124352) @lramos15

#### Builds
- [x] Finish language packs builds [vscode-loc-drop#51](https://github.com/microsoft/vscode-loc-drop/issues/51) [vscode-loc#286](https://github.com/microsoft/vscode-loc/issues/286) @tylerleonhardt
#### Electron
- None.
#### Node.js-free, sand-boxed renderer
- [ ] :runner: Backlog [vscode#92164](https://github.com/microsoft/vscode/issues/92164) @bpasero @deepak1556 @rzhao271

------
### Deferred
- [ ] Add more examples to samples repo for Notebooks/renderers [vscode-extension-samples#436](https://github.com/microsoft/vscode-extension-samples/issues/436) @tanhakabir
- [ ] Stabilize APIs for notebook change events [vscode#125758](https://github.com/microsoft/vscode/issues/125758) @jrieken
- [ ] Finalize renderer API [vscode#123601](https://github.com/microsoft/vscode/issues/123601) @connor4312
- [ ] Explore UI additions to help guide users to push to a remote after committing [vscode#110882](https://github.com/microsoft/vscode/issues/110882) @eamodio
- [ ] Search editor: leverage text file model support and behave like normal text editors [vscode#118947](https://github.com/microsoft/vscode/issues/118947) @jacksonkearl

**Comment by hxkuc** [comment]
https://github.com/microsoft/vscode/issues/52855

**Comment by g3offrey** [comment]
Hi @Tyriar, @meganrogge 

Thank you for the work on terminal editors, day after day the experience is more and more polished. ☺️

Today playing with the latest insiders I encountered a weird bug. 

Playing with splitted editors, one terminal on the left and one on the right and using the term listing panel to switch from one to another, the terminal is completely broken. 
I'm sorry that I am unable to do a screenshot at the moment (no laptop). 

Steps to reproduce :
1. Open latest insiders
2. Create new terminal editor
3. Split it using editor split button on top right.
4. Switch from one terminal to the other (several times) using CMD+P `term` listing.

I hope that my message is clear enough. If not don't hesitate to tell me, and I'll do a video for you on Monday.
