### ISSUE TITLE
Explore improvements to the Python debugging experience

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#126463]
Address pain points:
- [ ] Improve usability of "editor/title/run" button/menu: https://github.com/microsoft/vscode/issues/117722
- [x] While debugging cannot continue a process that is not in focus: https://github.com/microsoft/vscode/issues/125327
- [x] When thread is no longer stopped the focus is not automatically passed to another thread: https://github.com/microsoft/vscode/issues/125144
- [x] Remember chosen Debug Environment per workspace / file: https://github.com/microsoft/vscode/issues/124770

/cc @luabud @isidorn

**Comment by isidorn** [comment]
Since the remaining item is captured by https://github.com/microsoft/vscode/issues/117722 I will close this one.
@weinand feel free to reopen if you need this issue for bookkeeping.

**Comment by weinand** [comment]
@luabud we've addressed all pain points covered by this issue - are there more/new issues that we should tackle in July?

**Comment by luabud** [comment]
@weinand just realized I hadn't answered your question yet, sorry! We have no other issues on the VS Code side, I think now the problems are mostly all on the Python extension side.

**Comment by weinand** [comment]
@luabud thanks, great to hear!
