### ISSUE TITLE
Iteration Plan for July 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#128444]
This plan captures our work in **July**. This is a 4-week iteration. We will ship in **early August**.

## Endgame
- **July 26, 2021**: Endgame
- **July 30, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22July+2021%22).

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22July+2021%22) @isidorn **team**
- [x] Address web-site accessibility issues, see [query](https://github.com/microsoft/vscode-docs/issues?q=is%3Aissue+is%3Aopen+a11y) @rzhao271

### Workbench
- [ ] :runner: Engagement with extension authors on adoption trusted folders [vscode#120251](https://github.com/microsoft/vscode/issues/120251) @lszomoru @sbatten
- [x] Polish getting started (wording, padding, clickable images) [vscode#128574](https://github.com/microsoft/vscode/issues/128574) @jacksonkearl @digitarald @misolori
- [ ] :runner: Continue user testing on new welcome pages [vscode#125117](https://github.com/microsoft/vscode/issues/125117) @digitarald
- [ ] :runner: Explore extension content contributions to the welcome page [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald
- [ ] :runner: Add support for drag&drop in custom trees [vscode#32592](https://github.com/microsoft/vscode/issues/32592) @alexr00
- [x] Polish settings editor [vscode#79571](https://github.com/microsoft/vscode/issues/79571) [vscode#127424](https://github.com/microsoft/vscode/issues/127424) @rzhao271
- [x] Disable Open Changes icon for files without changes [vscode#26425](https://github.com/microsoft/vscode/issues/26425) @lramos15
- [x] Investigate automatic language detection in untitled files [vscode#129004](https://github.com/microsoft/vscode/issues/129004) @TylerLeonhardt
- [x] Option to specify separator for "Copy Relative Path" action [vscode#56279](https://github.com/microsoft/vscode/issues/56279) @bpasero
- [x] Support a new status item background color to indicate "warning" state [vscode#128205](https://github.com/microsoft/vscode/issues/128205) @misolori @aeschli

#### Extensions
- [x] Support installing and activating extensions from an extension pack together [vscode#128114](https://github.com/microsoft/vscode/issues/128114) @sandy081
- [x] Add support for rich hovers in the Extensions view [vscode#126479](https://github.com/microsoft/vscode/issues/126479) @sandy081
- [x] Improve rendering of extensions under extension pack tab [vscode#120702](https://github.com/microsoft/vscode/issues/120702) @sandy081
- [x] Improve rendering of Extensions view when the width is narrow [vscode#118511](https://github.com/microsoft/vscode/issues/118511) @sandy081

#### Web
- [x] Improve iPad support (keyboard/trackpad/mouse and touch) [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aios-ipados+milestone%3A%22July+2021%22) @isidorn

### UX
- [ ] :runner: Explore improvements to the end-to-end experience of opening your first Jupyter notebook [vscode#128592](https://github.com/microsoft/vscode/issues/128592) @misolori **team**

### Code Editor
- [x] :red_circle: Publish a new Monaco editor release @hediet
- [x] :red_circle: Complete support for injected text (click handling) @hediet
- [x] Adopt injected text support for ghosted text [vscode#129411](https://github.com/microsoft/vscode/issues/129411) @hediet
- [x] Use and validate injected text support for inlay type hints [vscode#129412](https://github.com/microsoft/vscode/issues/129412) @hediet

#### Notebook Editor
- [ ] :runner: Improve discoverability of notebook layout and behavior customizability [vscode#128549](https://github.com/microsoft/vscode/issues/128549) @misolori @rebornix @roblourens
- [x] Explore improvements of the toolbar behavior in narrow notebook editors [vscode#125551](https://github.com/microsoft/vscode/issues/125551) @misolori @rebornix @roblourens
- [x] Improve handling of long text outputs [vscode#128765](https://github.com/microsoft/vscode/issues/128765) @rebornix
- [ ] :runner:Improve visual presentation of folded inputs/outputs [vscode#119776](https://github.com/microsoft/vscode/issues/119776) @rebornix @roblourens
- [x] Progress on notebook renderer API [vscode#123601](https://github.com/microsoft/vscode/issues/123601) @connor4312
- [ ] :runner: Improve rendering jitter in notebooks [vscode#126432](https://github.com/microsoft/vscode/issues/126432) @roblourens @mjbvz
- [ ] :runner: Investigate scroll performance issues in notebooks [vscode#126880](https://github.com/microsoft/vscode/issues/126880) @rebornix
#### Jupyter Notebooks
- [x] Replace the webview-based interactive window with a built-in one [vscode#126415](https://github.com/microsoft/vscode/issues/126415) @rebornix @joyceerhl
- [x] Improve multi-line input box behavior in the built-in interactive window [vscode#128766](https://github.com/microsoft/vscode/issues/128766) @rebornix @joyceerhl
- [ ] :runner: Explore debugging in Jupyter notebooks (line-by-line versus full debugging support) [vscode#126431](https://github.com/microsoft/vscode/issues/126431) @DavidKutu @roblourens @weinand
- [x] Provide `.ipynb` file support out of the box [vscode#128495](https://github.com/microsoft/vscode/issues/128495) @roblourens @joyceerhl
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#6628](https://github.com/microsoft/vscode-jupyter/issues/6628) **team**
#### Samples
- [x] Add more examples to samples repo for Notebooks/renderers [vscode-extension-samples#436](https://github.com/microsoft/vscode-extension-samples/issues/436) @tanhakabir

### Languages
- [x] Explore a 'universal' token based language service [vscode#82024](https://github.com/microsoft/vscode/issues/82024) @jrieken
- [ ] :runner: Collaborate on [Type Hierarchy API](https://github.com/microsoft/vscode/issues/15533) with the Java extension team **Java team** @jrieken @dbaeumer
#### LSP /LSIF
- [x] LSP: Expose support for more structured completion items @dbaeumer
- [x] LSIF:[Support TS 4.4](https://github.com/microsoft/lsif-node/issues/131) in the TypeScript LSIF indexer @dbaeumer
#### JavaScript/TypeScript
- [x] Enable and polish inlay hints for TypeScript 4.4 [vscode#16221](https://github.com/microsoft/vscode/issues/16221) @mjbvz
- [x] Support reporting of syntax errors in the TS syntax server [vscode#127700](https://github.com/microsoft/vscode/issues/127700) @mjbvz
- [x] :red_circle: Explore variations of "New TS Project" to inform what APIs are needed @jacksonkearl
#### Python
- [x] Finalize Getting Started contribution [vscode-python#16678](https://github.com/microsoft/vscode-python/issues/16678) @brettcannon @luabud @kimadeline
- [ ] :runner: Adopt Testing API [vscode-python#15750](https://github.com/microsoft/vscode-python/issues/15750) @karthiknadig
- [ ] :muscle: Deprecate support for Python 2.7 in Jedi [vscode-python#11995](https://github.com/microsoft/vscode-python/issues/11995) @kimadeline

### Debug

- [x] Improve editor run action by using the new split button [vscode#117722](https://github.com/microsoft/vscode/issues/117722) @weinand
- [x] Explore support for a disassembly view with the C++ extension team [vscode#124163](https://github.com/microsoft/vscode/issues/124163) **C++ team** @weinand @isidorn
- [x] Add "Run To Line" command to the Breakpoint Context Menu [vscode#123872](https://github.com/microsoft/vscode/issues/123872) @hediet
- [ ] :muscle: Explore integration of a memory inspector: [vscode-js-debug#1008](https://github.com/microsoft/vscode-js-debug/issues/1008) @connor4312
#### DAP
- [x] Add new Memory Event to refresh an address range [debug-adapter-protocol#194](https://github.com/microsoft/debug-adapter-protocol/issues/194) @weinand
#### js-debug
- [ ] :runner: Improve dogfooding stability of js-debug in current electron version [vscode#127861](https://github.com/microsoft/vscode/issues/127861) @connor4312 @weinand
- [ ] :runner: Support inline value providers for TS/JS [TypeScript#43449](https://github.com/microsoft/TypeScript/issues/43449) @connor4312 @weinand

### Testing
- [x] Provide consolidated testing support [vscode#107467](https://github.com/microsoft/vscode/issues/107467) @connor4312
- [x] Finalize testing APIs [vscode#122208](https://github.com/microsoft/vscode/issues/122208) [vscode#117379](https://github.com/microsoft/vscode/issues/117379) @connor4312 @jrieken @mjbvz
- [x] Testing User Guide and API documentation [vscode-docs#4640](https://github.com/microsoft/vscode-docs/issues/4640) @connor4312 @gregvanl

### Terminal
- [x] Mark terminal editors as dirty when they have subprocesses, explore option for panel terminals [vscode#127193](https://github.com/microsoft/vscode/issues/127193) @tyriar
- [x] Only trigger `confirmOnExit` when terminals have subprocesses [vscode#23808](https://github.com/microsoft/vscode/issues/23808) @tyriar
- [x] Support drag and drop of terminals across windows [vscode#126387](https://github.com/microsoft/vscode/issues/126387) @meganrogge

### Source Control
- [ ] :runner: Explore UI additions to help guide users to push to a remote after committing [vscode#110882](https://github.com/microsoft/vscode/issues/110882) @eamodio

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2021%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2021%22+label%3A%22api-proposal%22)

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#5315](https://github.com/microsoft/vscode-remote-release/issues/5315) @alexr00 @roblourens @chrmarti
- [x] Improvements to the GitHub PRI [vscode-pull-request-github#2833](https://github.com/microsoft/vscode-pull-request-github/issues/2833) extension @alexr00
- [x] Improvements to the Remote Repositories extension [vscode-remote-repositories-github#39](https://github.com/microsoft/vscode-remote-repositories-github/issues/39) @eamodio @alexr00
- [x] Stabilization of the Live Preview extension [vscode-livepreview#71](https://github.com/microsoft/vscode-livepreview/issues/71) @andreamah
- [x] Investigate performance improvements of the [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) extension [vscode#128465](https://github.com/microsoft/vscode/issues/128465) @hediet

### Engineering
- [x] Support cut, copy, paste for iframe search [vscode#127456](https://github.com/microsoft/vscode/issues/127456) @rzhao271 @mjbvz
- [x] :red_circle: Investigate improving the release process of the Monaco editor by migrating to a mono repo @hediet
#### Builds
- [ ] :hand: Fix `vscode-encrypt` loading in snap builds [vscode#116690](https://github.com/microsoft/vscode/issues/116690) @deepak1556
- [ ] :runner: Fix rpm package support for RHEL7 [vscode#115784](https://github.com/microsoft/vscode/issues/115784) @deepak1556
- [ ] :muscle: Assume ownership of remaining translation build items [vscode#128995](https://github.com/microsoft/vscode/issues/128995) @tylerleonhardt
- [ ] Adopt latest playwright version to benefit from the new trace support [vscode#128479](https://github.com/microsoft/vscode/issues/128479) @bpasero @joaomoreno
- [x] Automate data migration smoketests [vscode#127799](https://github.com/microsoft/vscode/pull/127799) @bpasero @joaomoreno
- [x] Run smoke tests (including on Windows) as part of the CI builds [vscode#128224](https://github.com/microsoft/vscode/pull/128224) @joaomoreno
- [x] Enable certificate rotation for the code signing service @joaomoreno

#### Electron
- [x] Electron 13 update [vscode#124666](https://github.com/microsoft/vscode/pull/124666) @deepak1556
- [ ] :muscle: Investigate debug crash [vscode#122225](https://github.com/microsoft/vscode/issues/122225) @deepak1556
- [ ] :muscle: Investigate webview service worker issue on windows when workbench is run as admin [vscode#122951](https://github.com/microsoft/vscode/issues/122951) @deepak1556
- [x] Investigate fix to prevent eager preload script loading that breaks IPC [vscode#127421](https://github.com/microsoft/vscode/issues/127421) @deepak1556

#### Node.js-free, sand-boxed renderer
- [ ] :runner: Backlog [vscode#92164](https://github.com/microsoft/vscode/issues/92164) @bpasero @deepak1556 @rzhao271

------
### Deferred
- [ ] Exploration for moving new/recent column from Welcome to Explorer view [vscode#127681](https://github.com/microsoft/vscode/issues/127681) @digitarald
- [ ] Allow opening all new editors in a dedicated editor group [vscode#124709](https://github.com/microsoft/vscode/issues/124709) @bpasero @misolori
- [ ] :muscle: Explore improving zero-knowledge onboarding into a well-tuned TS setup (tasks, tests, debugging, etc.) [vscode#121345](https://github.com/microsoft/vscode/issues/121345) @jacksonkearl
- [ ] Explore APIs for test coverage [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312

**Comment by DonJayamanne** [comment]
@kieferrm I reverted the change I accidentally made to a task, I clicked an icon (which I thought was `go to issue`, instead it converted this task into an issue). Closed that issue & reverted the change.
