### ISSUE TITLE
Notebook performance

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#129972]
We have been seeing reports about the notebook performance for quite a while and recently since we rolled out them to all Jupyter users, we started to receive issues with reproduce steps to help us figure out what's going on. Notebook can be "slow" in multiple different ways and here is a summary of the issues we have good understanding of:

* File opening
  - [x] Stop activating all extensions onNotebook synchronously, only the serializer https://github.com/microsoft/vscode/issues/129932
  - [x] Serializer perf improvement https://github.com/microsoft/vscode/issues/129370
* Scrolling
  - [x] Mouse scrolling sensitivity https://github.com/microsoft/vscode/issues/117803
  - [x] Update layer tree https://github.com/microsoft/vscode/issues/126880
  - [x] Complex output https://github.com/microsoft/vscode-jupyter/issues/6913
  - [ ] Output stealing scrolling (e.g. map)
* Execution
  - [x] No await for output append https://github.com/microsoft/vscode/issues/127843, https://github.com/microsoft/vscode-jupyter/issues/5662
  - [ ] Use VSBuffer as data store, or use `string` as data store for `OutputItem.text()`
  - [ ] Do not generate svg for images always on execution (memory leak) https://github.com/microsoft/vscode-jupyter/issues/6913, https://github.com/microsoft/vscode-jupyter/issues/6901
  - [ ] Jedi language server interferes with execution : https://github.com/microsoft/vscode-jupyter/issues/1300
* File opened --> first execution
  - [ ] Avoid scanning all kernel specs when active interpreter is known https://github.com/microsoft/vscode-jupyter/issues/6672

**Comment by jswetzen** [comment]
I recently got problems with notebooks on WSL remote: when the file is large (like 40MB because of a plotly plot), it refuses to open it and looses connection. Would this be solved by one of these tasks or should I open a separate issue? Or is 40MB simply too large to expect to open?

**Comment by rebornix** [comment]
Most items in the issue have been tackled. let's track other perf issues separately.
