### ISSUE TITLE
Iteration Plan for August 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#130368]
This plan captures our work in **August**. This is a 4-week iteration. We will ship in **early September**.

## Endgame
- **August 23, 2021**: Endgame
- **August 27, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22August+2021%22).

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22August+2021%22) @isidorn **team**
- [ ] :muscle: Improve accessibility of the comments peek view @rebornix [vscode#110408](https://github.com/microsoft/vscode/issues/110408)

### Workbench
- [ ] :runner: Polish trusted folder management particularly for managing paths for remote repositories [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aworkspace-trust+label%3Aplan-item+milestone%3A%22August+2021%22) @sbatten
- [x] Enable a walkthrough based on the files in the workspace [vscode#121778](https://github.com/microsoft/vscode/issues/121778) @jacksonkearl
- [x] Restore active getting started walkthrough on window reload [vscode#123525](https://github.com/microsoft/vscode/issues/123525) @jacksonkearl
- [ ] :runner: Continue user testing on new welcome pages [vscode#125117](https://github.com/microsoft/vscode/issues/125117) @digitarald
- [ ] :runner: Explore extension content contributions to the welcome page [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald
- [ ] :runner: Add support for drag&drop in custom trees [vscode#32592](https://github.com/microsoft/vscode/issues/32592) @alexr00
- [x] Ensure automated language detection does not run in the UI thread [vscode#129607](https://github.com/microsoft/vscode/issues/129607) @tylerleonhardt
- [ ] Quick Pick improvements
   - [ ] :runner: Ensure UI stability when updating `QickPick.items` [vscode#109969](https://github.com/microsoft/vscode/issues/109969) @tylerleonhardt
   - [ ] :runner: Improve matching of numbers/subwords when filtering [vscode#130797](https://github.com/microsoft/vscode/issues/130797) @tylerleonhardt
   - [x] Proposed API for inline actions in `QuickPickItems` [vscode#88716](https://github.com/microsoft/vscode/issues/88716) @tylerleonhardt
- [x] Explore ways to not pollute editor groups with terminals with other editors [vscode#124709](https://github.com/microsoft/vscode/issues/124709) @bpasero @misolori

### Web
- [ ] :runner: Improve iPad support (keyboard/trackpad/mouse and touch) [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aios-ipados+milestone%3A%22August+2021%22) @isidorn **team**

### UX
- [ ] 🏃 Explore how to effectively signal limited language support to users, e.g. in untrusted folders [vscode#129037](https://github.com/microsoft/vscode/issues/129037) @misolori @daviddossett 
- [ ] :runner: Explore how to indicated read-only and deleted files open in editors more effectively [vscode#130526](https://github.com/microsoft/vscode/issues/130526) @misolori
- [ ] :runner: Align in-editor peek views (test, problems, references, etc.) UX [vscode#130516](https://github.com/microsoft/vscode/issues/130516) @misolori
- [ ] :muscle: Continue exploration of profiles [vscode#116740](https://github.com/microsoft/vscode/issues/116740) @misolori @lydiayschung

### Code Editor
- [x] Provide a high performant support for bracket pair colorization [vscode#129231](https://github.com/microsoft/vscode/issues/129231) @hediet
- [x] Inline Suggestions: Support Interactions with the suggest Widget [vscode#129495](https://github.com/microsoft/vscode/issues/129495) @hediet
- [x] Publish a new Monaco editor release [CHANGELOG](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0270-16082021) @hediet

### Notebooks
- [x] Enable to create new notebooks from the command line [vscode#125028](https://github.com/microsoft/vscode/issues/125028) @bpasero
- [ ] :runner: Explore improvements to the end-to-end experience of opening your first Jupyter (Python) notebook [vscode#128592](https://github.com/microsoft/vscode/issues/128592) @misolori **team**
- [ ] :runner: Improve discoverability of notebook layout and behavior customizability [vscode#128549](https://github.com/microsoft/vscode/issues/128549) @misolori @rebornix @roblourens
- [ ] :red_circle: :runner: :muscle: Improve discoverability of available/installable output renderers for given mime types @misolori
- [ ] :runner: :muscle: Explore ways to show execution progress while the execute cell is out of the viewport [vscode#130611](https://github.com/microsoft/vscode/issues/130611) @misolori
#### Notebook Editor
- [x] Improve visual presentation of folded outputs [vscode#119776](https://github.com/microsoft/vscode/issues/119776) @rebornix @roblourens
- [ ] :runner: Support notebook content provider, renderers, and controller extensions in the marketplace [vscode#123581](https://github.com/microsoft/vscode/issues/123581) @connor4312 @rebornix
- [x] Explore keymaps for notebooks @rebornix @joyceerhl [vscode#106679](https://github.com/microsoft/vscode/issues/106679)
- [x] Ensure Replace Text works in notebooks [vscode#129781](https://github.com/microsoft/vscode/issues/129781) @rebornix
- [ ] :runner: Allow extensions to persist controller meta information in `ipynb` files [vscode#130602](https://github.com/microsoft/vscode/issues/130602) @mjbvz
- [ ] :runner: Improve rendering jitter in notebooks [vscode#126432](https://github.com/microsoft/vscode/issues/126432) @roblourens
- [ ] :runner: Explore how to avoid unnecessary transformations to satisfy byte-based storage of `OutputItem` [vscode#130950](https://github.com/microsoft/vscode/issues/130950) @mjbvz
- [x] Review `onNotebook` activation usage and behavior [vscode#129932](https://github.com/microsoft/vscode/issues/129932) @rebornix @roblourens @DonJayamanne
- [x] Provide recommendations how output renderers can probe the activation state of their extension [vscode#130499](https://github.com/microsoft/vscode/issues/130499) @rebornix @DonJayamanne
#### Jupyter Notebooks
- [ ] :runner: Explore debugging in Jupyter notebooks (line-by-line versus full debugging support) [vscode#126431](https://github.com/microsoft/vscode/issues/126431) @roblourens @DavidKutu @weinand
- [x] Fix Vim keybinding conflicts in builtin Interactive Window and Notebook [vscode#130425](https://github.com/microsoft/vscode/issues/130425) @rebornix @joyceerhl
- [ ] :runner: Contributions to the vscode-jupyter extension [vscode-jupyter#7008](https://github.com/microsoft/vscode-jupyter/issues/7008) **team**

### Languages
- [ ] :runner: Add support for a language status indicator [vscode#129037](https://github.com/microsoft/vscode/issues/129037) @mjbvz @jrieken @misolori
- [ ] :runner: Collaborate on [Type Hierarchy API](https://github.com/microsoft/vscode/issues/15533) with the Java extension team **Java team** @jrieken @dbaeumer
#### LSP /LSIF
- None.
#### JavaScript/TypeScript
- [ ] :runner: Adopt and ship TS 4.4 [vscode#130601](https://github.com/microsoft/vscode/issues/130601) @mjbvz
#### Python
- [x] Adopt Testing API [vscode-python#15750](https://github.com/microsoft/vscode-python/issues/15750) @karthiknadig
- [x] Prompt to announce deprecation of support for Python 2.7 in Jedi [vscode-python#11995](https://github.com/microsoft/vscode-python/issues/11995) @kimadeline
- [ ] :runner: Improve python extension start-up time [vscode-python#16908](https://github.com/microsoft/vscode-python/issues/16908) @karthiknadig @karrtikr
- [ ] :runner: Improve support for untrusted folders (including web) [vscode-python#16126](https://github.com/microsoft/vscode-python/issues/16126) @brettcannon

### Debug
- [ ] :runner: Improve extension debugging (support clean-setup, address livecycle issues) [vscode#126737](https://github.com/microsoft/vscode/issues/126737) [vscode#124128](https://github.com/microsoft/vscode/issues/126911) @weinand @isidorn
- [ ] :runner: Finalize the disassembly view support with the C++ extension team [vscode#124163](https://github.com/microsoft/vscode/issues/124163) @isidorn @weinand **C++ team**
- [x] Improve debug focus management [vscode#128132](https://github.com/microsoft/vscode/issues/128132) [vscode#122775](https://github.com/microsoft/vscode/issues/122775) [vscode#128744](https://github.com/microsoft/vscode/issues/128744) [vscode#121898](https://github.com/microsoft/vscode/issues/121898) [vscode#113742](https://github.com/microsoft/vscode/issues/113742) @isidorn
- [x] Allow to set value of expressions in Watches view [vscode#115063](https://github.com/microsoft/vscode/issues/115063) @isidorn
- [x] Add "Run To Line" to the Breakpoint Context Menu [vscode#123872](https://github.com/microsoft/vscode/issues/123872) @hediet
- [ ] :muscle: Explore integration of a memory inspector [vscode-js-debug#1008](https://github.com/microsoft/vscode-js-debug/issues/1008) @connor4312

#### DAP
- [x] Finish the memory event [debug-adapter-protocol#194](https://github.com/microsoft/debug-adapter-protocol/issues/194) @weinand.
#### js-debug
- [ ] :runner: Improve dogfooding stability of js-debug in current electron version [vscode#127861](https://github.com/microsoft/vscode/issues/127861) @connor4312 @weinand
- [ ] :runner: Support inline value providers for TS/JS [TypeScript#43449](https://github.com/microsoft/TypeScript/issues/43449) @connor4312 @weinand

### Testing
- [ ] :runner: Provide support for tags [vscode#129456](https://github.com/microsoft/vscode/issues/129456) @connor4312
- [ ] :runner: Support non-error output for test runs [vscode#129201](https://github.com/microsoft/vscode/issues/129201) @connor4312

### Terminal
- [x] Explore `xtermjs` node target [vscode#116113](https://github.com/microsoft/vscode/issues/116113) @Tyriar @meganrogge
- [x] Support pixel perfect rendering for box drawing and block characters in `xtermjs` [vscode#130406](https://github.com/microsoft/vscode/issues/130406) @meganrogge
- [ ] :runner: :muscle: Explore support for fixed-width terminals [vscode#74501](https://github.com/microsoft/vscode/issues/74501) @tyriar @meganrogge

### Source Control
- [ ] :runner: Explore UI additions to help guide users to push to a remote after committing [vscode#110882](https://github.com/microsoft/vscode/issues/110882) @eamodio

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2021%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2021%22+label%3A%22api-proposal%22)

### Extensions
- [ ] :runner: Support platform specific extensions [vscode#23251](https://github.com/microsoft/vscode/issues/23251) @sandy081
- [ ] :runner: Update documentation to explain what it needs to run an extension in the web-worker extension host in the browser [vscode#130628](https://github.com/microsoft/vscode/issues/130628) @aeschli

### Extension Contributions
- [ ] :runner: Improvements to the Remote extensions [vscode-remote-release#5428](https://github.com/microsoft/vscode-remote-release/issues/5428) @alexr00 @roblourens @chrmarti
- [ ] :runner: Improvements to the GitHub PRI extension [vscode-pull-request-github#2890](https://github.com/microsoft/vscode-pull-request-github/issues/2890) @alexr00
- [ ] :runner: Improvements to the GitHub Repositories extension [vscode-remote-repositories-github#48](https://github.com/microsoft/vscode-remote-repositories-github/issues/48) @eamodio @alexr00
- [x] Investigate performance improvements of the [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) extension [vscode#128465](https://github.com/microsoft/vscode/issues/128465) @hediet

### Install
- [x] Expand the file types that VS Code is registered for on the OS and enable file associations by default [vscode#127075](https://github.com/microsoft/vscode/issues/127075) @digitarald @isidorn
- [ ] :runner: Explore a meta-installer suitable for the new Windows Store [vscode#130410](https://github.com/microsoft/vscode/issues/130410) @sbatten

### Engineering
- [ ] :muscle: Adopt the new file working copy support for core editors [vscode#130383](https://github.com/microsoft/vscode/issues/130383) @bpasero
- [ ] :runner: Adopt `vscode` namespace for npm packages [vscode#130301](https://github.com/microsoft/vscode/issues/130301) @connor4312 **team**
- [x] Improve performance of token validation in the GitHub auth provider [vscode#130795](https://github.com/microsoft/vscode/issues/130795) @tylerleonhardt
- [x] Remove old welcome code [vscode#130005](https://github.com/microsoft/vscode/issues/130005) @JacksonKearl
- [x] Assume ownership of the file explorer [vscode#130422](https://github.com/microsoft/vscode/issues/130422) @jacksonkearl @isidorn
- [x] Assume ownership of the debug UI [vscode#130424](https://github.com/microsoft/vscode/issues/130424) @roblourens @isidorn
- [ ] :runner: Explore impact on running search in the extension host [vscode#130532](https://github.com/microsoft/vscode/issues/130532) @roblourens

#### Builds
- [x] Fix rpm package support for RHEL7 [vscode#115784](https://github.com/microsoft/vscode/issues/115784) @deepak1556
- [ ] :muscle: Assume ownership of remaining translation build items [vscode#128995](https://github.com/microsoft/vscode/issues/128995) @tylerleonhardt
- [ ] :muscle: Explore to use `playwright` for our desktop smoke tests [vscode#128479](https://github.com/microsoft/vscode/issues/128479) @joaomoreno @bpasero

#### Electron
- [x] Open devtools scoped to a target frame [vscode#129437](https://github.com/microsoft/vscode/issues/129437) @rzhao271 @deepak1556
- [ ] :runner: Refactor startup code to use electron singleton instance api [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271 @deepak1556
- [ ] :runner: Launch app on macOS via open from the cli [vscode#102975](https://github.com/microsoft/vscode/issues/102975) @rzhao271 @deepak1556

#### Node.js-free, sand-boxed renderer
- [ ] :runner: Backlog [vscode#92164](https://github.com/microsoft/vscode/issues/92164) @bpasero @deepak1556 @rzhao271

------
### Deferred
- [ ] Smart run/debug command for loose TS files [vscode#124280](https://github.com/microsoft/vscode/issues/124280) @digitarald
- [ ] Investigate scroll performance issues in notebooks [vscode#126880](https://github.com/microsoft/vscode/issues/126880) @rebornix
- [ ] Exploration for moving new/recent column from Welcome to Explorer view [vscode#127681](https://github.com/microsoft/vscode/issues/127681) @digitarald
- [ ] :muscle: Explore improving zero-knowledge onboarding into a well-tuned TS setup (tasks, tests, debugging, etc.) [vscode#121345](https://github.com/microsoft/vscode/issues/121345) @jacksonkearl
- [ ] Explore APIs for test coverage [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312
- [ ] :hand: Fix `vscode-encrypt` loading in snap builds [vscode#116690](https://github.com/microsoft/vscode/issues/116690) @deepak1556
- [ ] :hand: Investigate debug crash [vscode#122225](https://github.com/microsoft/vscode/issues/122225) @deepak1556
- [ ] :muscle: Investigate webview service worker issue on windows when workbench is run as admin [vscode#122951](https://github.com/microsoft/vscode/issues/122951) @deepak1556

**Comment by noahehall** [comment]
`The endgame details for this iteration are tracked here.`

here === null

**Comment by Tyriar** [comment]
@noahehall the issue should be created on Monday.
