### ISSUE TITLE
Iteration Plan for September 2021

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#132467]
This plan captures our work in **September**. This is a 5-week iteration. We will ship in **early October**.

## Endgame

- **September 27, 2021**: Endgame
- **October 1, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22September+2021%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility

- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22September+2021%22) @isidorn **team**
- [ ] :muscle: Improve accessibility of the comments peek view [vscode#110408](https://github.com/microsoft/vscode/issues/110408) @rebornix

### Workbench

- [x] Allow extensions to register groups of settings for the settings editor [vscode#126089](https://github.com/microsoft/vscode/issues/126089) @rzhao271
- [x] Ensure UI stability when updating `QuickPick.items` [vscode#109969](https://github.com/microsoft/vscode/issues/109969) @tylerleonhardt
- [x] Provide individual user settings for error and usage telemetry [vscode#132552](https://github.com/microsoft/vscode/issues/132552) @lramos15 @sbatten
- [x] Explore second sidebar [vscode#132893](https://github.com/microsoft/vscode/issues/132893) @sbatten
- [x] Continue user testing on new welcome pages [vscode#125117](https://github.com/microsoft/vscode/issues/125117) @digitarald
- [ ] :runner: Explore extension content contributions to the welcome page [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald
- [ ] Improve markdown preview scrolling behavior [vscode#119370](https://github.com/microsoft/vscode/issues/119370) @mjbvz
- [x] Make Help menu entries more useful for exploration [vscode#132158](https://github.com/microsoft/vscode/issues/132158) @digitarald
- [x] Exploration for moving new/recent column from Welcome Editor to Explorer view [vscode#127681](https://github.com/microsoft/vscode/issues/127681) @digitarald
- [ ] :runner: Problems view - add support to sort by message contents [vscode#98819](https://github.com/microsoft/vscode/issues/98819) @lszomoru
- [x] Continue locked editor groups exploration [vscode#124709](https://github.com/microsoft/vscode/issues/124709) @bpasero
- [x] Allow to split an editor into two editors in a single group [vscode#36700](https://github.com/microsoft/vscode/issues/36700) @bpasero
- [x] Address confusion when a user wants to open a folder but runs 'Open Workspace...' [vscode#131793](https://github.com/microsoft/vscode/issues/131793) @bpasero

### Web

- [x] Improve drag&drop behavior [vscode#133116](https://github.com/microsoft/vscode/pull/133116) @sbatten @bpasero @isidorn

### UX

- [ ] :runner: :muscle: Explore how to effectively signal limited language support to users, e.g. in untrusted folders @daviddossett @misolori [vscode#133049](https://github.com/microsoft/vscode/issues/133049)
- [x] Explore how to indicate read-only and deleted files open in editors more effectively [vscode#130526](https://github.com/microsoft/vscode/issues/130526) @misolori @bpasero
- [x] Explore aligning in-editor peek views (test, problems, references, etc.) UX [vscode#130516](https://github.com/microsoft/vscode/issues/130516) @misolori @connor4312 @jrieken @sandy081
- [ ] :muscle: Continue exploration of profiles [vscode#116740](https://github.com/microsoft/vscode/issues/116740) @lydiayschung @sana-ajani @misolori
- [ ] :runner: :muscle: Explore improving the "Show Running Extensions" view @lydiayschung @misolori [vscode#133136](https://github.com/microsoft/vscode/issues/133136)

### Code Editor

- [x] Improve auto complete and ghosted text interaction [vscode#131940](https://github.com/microsoft/vscode/issues/131940) @hediet
- [x] Native bracket pair colorizer add support for rendering 'scope' lines [vscode#131001](https://github.com/microsoft/vscode/issues/131001) @hediet
- [ ] :runner: Adopt bracket AST infrastructure for all bracket related features [vscode#132536](https://github.com/microsoft/vscode/issues/132536) @hediet
- [x] Improve undo for the auto tag close by leveraging the new editor events [vscode#34484](https://github.com/microsoft/vscode/issues/34484) @aeschli
- [x] Publish a new Monaco editor release [changelog of 0.28.0](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0280-22092021) @hediet

### Notebooks

- [x] Explore improvements to the end-to-end experience of opening your first Jupyter (Python) notebook [vscode#128592](https://github.com/microsoft/vscode/issues/128592) @misolori **team**
- [x] Support notebook content provider, renderers, and controller extensions in the marketplace [vscode#123581](https://github.com/microsoft/vscode/issues/123581) @connor4312 @rebornix
- [ ] :runner: Improve discoverability of available/installable output renderers for given mime types [vscode#131031](https://github.com/microsoft/vscode/issues/131031) @misolori @rebornix
- [ ] :runner: :muscle: Explore ways to show execution progress while the executing cell is out of the viewport [vscode#130611](https://github.com/microsoft/vscode/issues/130611) @misolori @roblourens
- [x] Investigate an extension contribution point for a notebook type debugger [vscode#132014](https://github.com/microsoft/vscode/issues/132014) @roblourens @weinand

#### Notebook Editor

- [ ] :runner: Investigate scroll performance issues in notebooks [vscode#126880](https://github.com/microsoft/vscode/issues/126880) @rebornix
- [ ] :runner: Improve rendering jitter in notebooks [vscode#126432](https://github.com/microsoft/vscode/issues/126432) @roblourens
- [ ] :runner: Improve discoverability of cell folding @misolori @roblourens [vscode#132690](https://github.com/microsoft/vscode/issues/132690)
- [x] Improve usability of in-between cell toolbar [vscode#133205](https://github.com/microsoft/vscode/issues/133205) @roblourens
- [ ] :runner: Explore option for allowing to run all cells in a folded markdown region [vscode#133690](https://github.com/microsoft/vscode/issues/133690) @misolori

#### Jupyter Notebooks

- [x] Explore debugging in Jupyter notebooks (line-by-line versus full debugging support) [vscode#126431](https://github.com/microsoft/vscode/issues/126431) @roblourens @davidkutu @weinand
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#7428](https://github.com/microsoft/vscode-jupyter/issues/7428) @greazer **team**

#### Notebook Engineering

- [ ] :runner: Improve code structure and dependecies [vscode#131808](https://github.com/microsoft/vscode/issues/131808) @roblourens @rebornix
- [x] Improve overall quality (rendering failures, z-index issues, ...) [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Anotebook+label%3Aimportant+milestone%3A%22September+2021%22) @roblourens @rebornix

### Languages

- [ ] :runner: Add support for a language status indicator [vscode#129037](https://github.com/microsoft/vscode/issues/129037) @mjbvz @jrieken @daviddossett.
- Adopt the language status indicator:
  - [x] TypeScript @mjbvz
  - [x] :runner: ESLint @dbaeumer
  - [ ] Java **Java team**
  - [ ] C# @jrieken
- [x] Finish [Type Hierarchy API](https://github.com/microsoft/vscode/issues/15533) with the Java extension team **Java team** @jrieken
- [ ] :runner: Finish Type Inlay UI/API @jrieken @hediet

#### LSP /LSIF

- [x] Add "TypeHierarchy" support with the Java extension team @dbaeumer **Java team**
- [x] Support TS 4.4 final in the TypeScript LSIF indexer [lsif-node#131](https://github.com/microsoft/lsif-node/issues/131) @dbaeumer

#### Python

- [x] Contributions to the python extension [vscode-python#17468](https://github.com/microsoft/vscode-python/issues/17468) @brettcannon **team**

### Debug

- [ ] :runner: Continue investigation: extension debugging in a clean environment [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand
- [ ] :runner: Investigation: Exclude breakpoint from specific caller [vscode#127775 ](https://github.com/microsoft/vscode/issues/127775) @weinand @roblourens
- [ ] :runner: Finalize the disassembly view support with the C++ extension team [vscode#124163](https://github.com/microsoft/vscode/issues/124163) @roblourens @weinand **C++ team**
- [ ] :runner: Explore integration of a memory inspector [vscode-js-debug#1008](https://github.com/microsoft/vscode-js-debug/issues/1008) @connor4312
- [ ] :runner: Help top language extensions to support single file debugging experiences [vscode#132329](https://github.com/microsoft/vscode/issues/132329) @isidorn
  

#### js-debug

- [ ] :runner: Support inline value providers for TS/JS [TypeScript#43449](https://github.com/microsoft/TypeScript/issues/43449) @connor4312 @weinand

### Testing

- [x] Provide support for tags [vscode#129456](https://github.com/microsoft/vscode/issues/129456) @connor4312
- [x] Support non-error output for test runs [vscode#129201](https://github.com/microsoft/vscode/issues/129201) @connor4312
- [ ] :muscle: Explore APIs for test coverage [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312

### Terminal

- [x] Explore support for fixed-width terminals [vscode#74501](https://github.com/microsoft/vscode/issues/74501) @tyriar @meganrogge
- [x] Include cwd in terminal title [vscode#29816](https://github.com/microsoft/vscode/issues/29816) @meganrogge
- [ ] :runner: :muscle: Explore ways to make rendering edge cases more reliable [vscode#131580](https://github.com/microsoft/vscode/issues/131580) @tyriar
- [x] Save terminal buffer/cwd/icon/etc. on restart [vscode#131634](https://github.com/microsoft/vscode/issues/131634) @tyriar @meganrogge

### Source Control

- [x] :runner: Explore UI additions to help guide users to push to a remote after committing [vscode#110882](https://github.com/microsoft/vscode/issues/110882) @eamodio

### API

- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2021%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2021%22+label%3A%22api-proposal%22)
- [ ] :runner: Explore API access to open editors including focused notebooks or custom editors [vscode#15178](https://github.com/microsoft/vscode/issues/15178) @lramos15

### Extensions

- [x] Support platform specific extensions [vscode#23251](https://github.com/microsoft/vscode/issues/23251) @sandy081 @joaomoreno @isidorn
- [x] Explore support for an 'insider version' for an extension [vscode#15756](https://github.com/Microsoft/vscode/issues/15756) [vscode#111521](https://github.com/microsoft/vscode/issues/111521) @sandy081 @isidorn
- [ ] Explore simplifying enabling/disabling a group of extensions for a workspace [vscode#40239](https://github.com/microsoft/vscode/issues/40239) @lszomoru
- [ ] Explore how extensions could extend `Report Issue` to collect extension specific data [vscode#46726](https://github.com/microsoft/vscode/issues/46726) @tylerleonhardt

### Extension Contributions

- [x] Improvements to the Remote extensions @alexr00 @roblourens @chrmarti @aeschli [vscode-remote-release#5552](https://github.com/microsoft/vscode-remote-release/issues/5552)
- [x] Improvements to the GitHub PRI extension [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22September+2021%22) @alexr00
- [x] Improvements to the GitHub Repositories extension [vscode-remote-repositories-github#54](https://github.com/microsoft/vscode-remote-repositories-github/issues/54) @eamodio @alexr00
- [ ] :runner: Stabilize/maintain the Live Preview extension [query](https://github.com/microsoft/vscode-livepreview/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22September+2021%22) @lszomoru
- [ ] :runner: Work with popular extension on adopting and improving their welcome pages (e.g. docker) [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald

### Install
- [ ] :hand: Explore adding Insiders the new Windows Store [vscode#130410](https://github.com/microsoft/vscode/issues/130410) @sbatten

### Engineering

- [ ] :runner: Investigate consolidating the FileWatcher implementations by building on the multi-root file watcher [vscode#132483](https://github.com/microsoft/vscode/issues/132483) @bpasero
- [x] Explore how to support a more scoped access to proposed API [vscode#131165](https://github.com/microsoft/vscode/issues/131165) @jrieken @mjbvz
- [ ] :runner: Adopt `vscode` namespace for npm packages [vscode#130301](https://github.com/microsoft/vscode/issues/130301) @connor4312 **team**
- [ ] Improve reliability of the webview tests [vscode#132596](https://github.com/microsoft/vscode/issues/132596) @mjbvz

#### Builds

- [ ] :muscle: Explore to use `playwright` for our desktop smoke tests [vscode#128479](https://github.com/microsoft/vscode/issues/128479) @bpasero @joaomoreno

#### Electron

- [ ] :runner: Refactor startup code to use electron's `requestSingleInstanceLock` API [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271
- [x] Implement macOS CLI using `open` [vscode#102975](https://github.com/microsoft/vscode/issues/102975) @rzhao271
- [x] Windows occlusion tracker has incorrect behavior with vscode debugger [vscode#123257](https://github.com/microsoft/vscode/issues/123257) @deepak1556
- [ ] :runner: Investigate the impact of windows sandbox for vscode installs [vscode#122951](https://github.com/microsoft/vscode/issues/122951) @deepak1556
- [x] Fix v8 crash when debugging unit tests [vscode#122225](https://github.com/microsoft/vscode/issues/122225) @deepak1556
- [x] Explore feasability of webworker support in electron webviews [vscode#87282](https://github.com/microsoft/vscode/issues/87282) @deepak1556

#### Node.js-free, sand-boxed renderer

- [x] :runner: Remove node.js dependency from tunnel service [vscode#122723](https://github.com/microsoft/vscode/issues/122723) @alexdima
- [x] :runner: Move search app out of renderer into shared process or extension host [vscode#118200](https://github.com/microsoft/vscode/issues/118200) @roblourens
- [x] Explore launching the extension host from the shared process [vscode#123592](https://github.com/microsoft/vscode/issues/123592) @alexdima
- [ ] :runner: Investigate moving the file service out of the renderer [vscode#132282](https://github.com/microsoft/vscode/issues/132282) @bpasero

---

### Deferred
- [ ] Add data points in runtime code to understand a rare service worker registration failure on linux [vscode#125993](https://github.com/microsoft/vscode/issues/125993) @deepak1556
- [ ] TypeScript single file debugging [vscode#124280](https://github.com/microsoft/vscode/issues/124280) @isidorn @gcrev93
- [ ] :red_circle: Improve feedback on kernel startup @misolori @greazer @roblourens
- [ ] Adopt new injected text infrastructure for other features that inject text [vscode#132537](https://github.com/microsoft/vscode/issues/132537), e.g., inline values @hediet
- [ ] Improve iPad support (keyboard/trackpad/mouse and touch) [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aios-ipados+milestone%3A%22September+2021%22) @isidorn **team**
- [ ] :hand: Explore showing the verified publisher badge from the marketplace [vscode#127825](https://github.com/microsoft/vscode/issues/127825) @isidorn @misolori @sandy081
- [ ] :muscle: Explore improving zero-knowledge onboarding into a well-tuned TS setup (tasks, tests, debugging, etc.) [vscode#121345](https://github.com/microsoft/vscode/issues/121345) @jacksonkearl
- [ ] :hand: Fix `vscode-encrypt` loading in snap builds [vscode#116690](https://github.com/microsoft/vscode/issues/116690) @deepak1556
- [ ] Use sounds to notify screenreader users when inline suggestions or decorations are present, e.g. a breakpoint is on a current line [vscode#130565](https://github.com/microsoft/vscode/issues/130565) [see also](https://github.com/microsoft/vscode/issues/130565#issuecomment-900246306) @hediet @isidorn

**Comment by TJ-Dom** [comment]
How can ESLint be configured to save fixes automatically in the new version

**Comment by 1shaked** [comment]
what about support for native Ipados, not on the web

**Comment by Kenya-West** [comment]
> Explore adding Insiders the new **Windows** Store

Quick fix, **Microsoft** Store

**Comment by fisforfaheem** [comment]
Wish to see Dart/flutter improvements as well. Also much better and Visual windows 11 like settings/preferences UI.

**Comment by Diegorro98** [comment]
What about integrate vscode into the new contextual menu in Windows 11?
And an option to add vscode to the contextual menu once installed? (users who downloaded vscode through Microsoft Store can't get the contextual menu options in an easy way)

**Comment by fisforfaheem** [comment]
yes we need windows 11 UX i nvs code



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
10/10/21,
02:06:28 AM
