### ISSUE TITLE
Iteration Plan for October 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#134730]
This plan captures our work in **October**. This is a 4-week iteration. We will ship in **early November**.

As you can see the plan is rather lean as this is our annual house-keeping iteration. You'll see a large number of GitHub issue notifications over the course of this iteration. If you want to track our progress, @lannonbr created this nice website a couple of years ago https://vscode-github-stats.netlify.com/

If you are interested in why we have issue house keeping iterations and in our general philosophy around issue management, then we have this [write-up](https://github.com/microsoft/vscode/wiki/Issue-Grooming) for you.

House-keeping is not the only focus this iteration. We'll also work closely with our partners at GitHub to get GitHub Codespaces in great shape.

## Endgame

- **October 26, 2021**: Endgame
- **October 29, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22October+2021%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Housekeeping
- [ ] :runner: Issue/PR Grooming - review, categorization, assignment [vscode#134380](https://github.com/microsoft/vscode/issues/134380) **team**

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22October+2021%22) @isidorn **team**
- [ ] :runner: Debug Adapter Protocol website accessibility issues, see [query](https://github.com/microsoft/debug-adapter-protocol/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility) @sana-ajani @gregvanl

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#7874](https://github.com/microsoft/vscode-jupyter/issues/7874) @greazer **team**

#### Python
- [x] Contributions to the python extension [vscode-python#17683](https://github.com/microsoft/vscode-python/issues/17683) @brettcannon **team**

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2021%22+label%3A%22api-finalization%22)

-----
### Deferred Items
- All work that was in-flight end of September. We'll resume that work in early November.

**Comment by cyberfox1** [comment]
Please fix the multiple-window opening crap that has been raised in multiple issues but still keeps occurring.

**Comment by ElianCordoba** [comment]
@shujaatak What a disrespectful message to the people that are building something you are using for free. Instead of complaining why don't you provide some constructive feedback? Even better you can code it yourself.
Replacing that entitlement with humility and thankfulness will get you a long way, maybe even will get you a better looking and more usable code editor.

**Comment by GHOSTS15** [comment]
Add " Explore simplifying enabling/disabling a group of extensions for a workspace vscode#40239 @lszomoru"

**Comment by GHOSTS15** [comment]
> 
> 
> Add " Explore simplifying enabling/disabling a group of extensions for a workspace vscode#40239 @lszomoru"

P.s I hope the things you failed to implement in September you didn't discard, if you discarded them that's ridiculous and shameful and makes -100% logical sense.
