### ISSUE TITLE
Iteration Plan for November 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#136630]
This plan captures our work in **November**. This is a 5-week iteration. We will ship in **early December**. As usual, there will be no release in early January. The next release will come in early February 2022.

In addition to the plan items below, some of us who were tied up in releasing https://vscode.dev will continue house keeping in November.

## Endgame

- **November 30, 2021**: Endgame
- **December 03, 2021**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22November+2021%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Housekeeping
- [x] Issue/PR Grooming - review, categorization, assignment [vscode#134380](https://github.com/microsoft/vscode/issues/134380) **team**

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22November+2021%22) @isidorn **team**
- [x] Debug Adapter Protocol website accessibility issues, see [query](https://github.com/microsoft/debug-adapter-protocol/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility) @rzhao271 @sana-ajani

### Workbench
- [ ] :runner: Improve secondary side panel [vscode#132893](https://github.com/microsoft/vscode/issues/132893) @sbatten
- [ ] :runner: Explore improving discoverability of workbench layout options [vscode#137633](https://github.com/microsoft/vscode/issues/137633) @sbatten
- [x] Improvements to the settings editor, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Asettings-editor+milestone%3A%22November+2021%22+is%3Aopen) @rzhao271
- [x] Multiple languages specific editor settings [vscode#51935](https://github.com/microsoft/vscode/issues/51935) @sandy081
- [x] Explore incrementally updating the markdown preview editor [vscode#136703](https://github.com/microsoft/vscode/issues/136703) @mjbvz
- [x] Investigate support for incremental rollout of new defaults for settings [vscode#134684](https://github.com/microsoft/vscode/issues/134684) @sandy081
- [ ] :runner: Improve language detection model to better deal with small inputs [vscode#137104](https://github.com/microsoft/vscode/issues/137104) @jacksonkearl @tylerleonhardt

- [ ] :runner: Problems view - add support to sort by message contents [vscode#98819](https://github.com/microsoft/vscode/issues/98819) @lszomoru
- [ ] :runner: Add support for drag&drop in custom trees [vscode#32592](https://github.com/microsoft/vscode/issues/32592) @alexr00
- [x] Support to preview color, icon, product themes from the marketplace without having to install them [vscode#137289](https://github.com/microsoft/vscode/issues/137289) @aeschli

### Web
- [ ] :muscle: Explore translations in the web [vscode#136331](https://github.com/microsoft/vscode/issues/136331) @tylerleonhardt
- [x] Investigate startup performance measurements/improvements [vscode-dev#454](https://github.com/microsoft/vscode-dev/issues/454) @jrieken
- [x] :red_circle: :runner: Rapid render for the web @jrieken
- [x] vscode.dev: Make UI more stable when opening a PR URL [vscode#136660](https://github.com/microsoft/vscode/issues/136660) @alexr00

### Code Editor
- [x] Adopt injected text infrastructure for other features [vscode#132537](https://github.com/microsoft/vscode/issues/132537) @hediet
- [x] Highlight confusable Unicode characters [vscode#136437](https://github.com/microsoft/vscode/issues/136437) @hediet
- [x] Investigate simplifying Monaco Editor Release Process [vscode#136443](https://github.com/microsoft/vscode/issues/136443) @alexdima
- [x] Release the Monaco Editor [monaco-editor#2718](https://github.com/microsoft/monaco-editor/issues/2718) @alexdima
- [x] Publish Monaco Editor nightly builds @alexdima
- [x] Stream hovers from multiple providers [vscode#137714](https://github.com/microsoft/vscode/issues/137714) @alexdima
- [ ] :muscle: Investigate customizing mouse shortcuts [vscode#3130](https://github.com/microsoft/vscode/issues/3130) @hediet
- [ ] :muscle: Use sounds to notify screenreader users when inline suggestions or decorations are present, e.g. a breakpoint is on a current line [vscode#130565](https://github.com/microsoft/vscode/issues/130565) [see also](https://github.com/microsoft/vscode/issues/130565#issuecomment-900246306) @hediet @isidorn

### Notebook Editor
- [ ] :runner: Improve code structure and dependencies [vscode#131808](https://github.com/microsoft/vscode/issues/131808) @roblourens @rebornix
- [ ] :muscle: Improve perceived scroll performance in notebooks [vscode#117644](https://github.com/microsoft/vscode/issues/117644) @rebornix
- [ ] :runner: Improve rendering jitter in notebooks [vscode#126432](https://github.com/microsoft/vscode/issues/126432) @roblourens
- [x] Allow users to configure the font size for rendering markdown [vscode#126294](https://github.com/microsoft/vscode/issues/126294) @mjbvz
- [x] Explore syntax highlighting in markdown code blocks [vscode#136693](https://github.com/microsoft/vscode/issues/136693) @mjbvz
- [ ] :runner: Show execution progress while the executing cell is out of the viewport [vscode#130611](https://github.com/microsoft/vscode/issues/130611) @roblourens @rebornix @misolori
- [x] Support progressive behavior in the notebook toolbar [vscode#134248](https://github.com/microsoft/vscode/issues/134248) @rebornix
- [ ] :muscle: Explore indicating cell status for collapsed cells [vscode#131200](https://github.com/microsoft/vscode/issues/131200) @roblourens
- [ ] :muscle: Improve discoverability of cell folding [vscode#132690](https://github.com/microsoft/vscode/issues/132690) @roblourens

### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#8200](https://github.com/microsoft/vscode-jupyter/issues/8200) @greazer **team**

#### AnyCode
See [AnyCode](https://marketplace.visualstudio.com/items?itemName=ms-vscode.anycode).
- [ ] :runner: Improve the support in large workspaces [vscode-anycode#9](https://github.com/microsoft/vscode-anycode/issues/9) @jrieken
- [ ] :red_circle: Explore bundling the extension with VS Code desktop @jrieken

#### LSP /LSIF
- [x] Add support for TypeScript v4.5 [#135](https://github.com/microsoft/lsif-node/issues/135) @dbaeumer

#### Python
- [x] Contributions to the python extension [vscode-python#17956](https://github.com/microsoft/vscode-python/issues/17956) @brettcannon **team**

#### JavaScript/TypeScript
- [x] Adopt TypeScript v4.5 [vscode#136704](https://github.com/microsoft/vscode/issues/136704) @mjbvz

#### JSON
- [x] Add support for subschemes with IDs [vscode#92042](https://github.com/microsoft/vscode/issues/92042) @aeschli
- [x] Adapt language status indicator [vscode#137288](https://github.com/microsoft/vscode/issues/137288) @aeschli
- [x] Use http to cache JSON schemes [vscode#101050](https://github.com/microsoft/vscode/issues/101050) @aeschli

### Debug
- [x] Investigate lazy variable evaluation [vscode#135147](https://github.com/microsoft/vscode/issues/135147) [vscode#134450](https://github.com/microsoft/vscode/issues/134450) @weinand @roblourens
- [ ] :runner: Prototype extension debugging in a clean environment [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand
- [ ] :muscle: Propose UI for debugging highly concurrent languages [vscode#116109](https://github.com/microsoft/vscode/issues/116109) @weinand

#### DAP
- [x] New `OutputEvent` category for highly visible output messages [debug-adapter-protocol#218](https://github.com/microsoft/debug-adapter-protocol/issues/218) @weinand
- [x] Support continue for all threads [debug-adapter-protocol#214](https://github.com/microsoft/debug-adapter-protocol/issues/214) @weinand
- [x] Support global evaluation that requires a file for context [vscode#134452](https://github.com/microsoft/vscode/issues/134452) @weinand

### Terminal
- [x] Terminal refactors for improved testability [vscode#136065](https://github.com/microsoft/vscode/issues/136065) @meganrogge @tyriar
- [ ] :runner: Create terminal smoke test suite [vscode#136064](https://github.com/microsoft/vscode/issues/136064) @tyriar @meganrogge

### Source Control
- [ ] Explore how to improve the display defaults for the git repository provider [vscode#135992](https://github.com/microsoft/vscode/issues/135992) @lszomoru @misolori
- [ ] :muscle: Large change improvements [vscode#135865](https://github.com/microsoft/vscode/issues/135865) @lszomoru

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2021%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2021%22+label%3A%22api-proposal%22)
- [ ] :runner: Explore API access to open editors including focused notebooks or custom editors [vscode#15178](https://github.com/microsoft/vscode/issues/15178) @lramos15
- [x] Support separators/categories in QuickPicks [vscode#74967](https://github.com/microsoft/vscode/issues/74967) @tylerleonhardt

### Extensions
- [x] Add support for insider versions of extensions [vscode#15756](https://github.com/microsoft/vscode/issues/15756) @sandy081 @isidorn @misolori @lydiayschung
- [x] Enable extensions to contribute default values for settings [vscode#46851](https://github.com/microsoft/vscode/issues/46851) @sandy081
- [ ] :muscle: Explore simplifying enabling/disabling a group of extensions for a workspace [vscode#40239](https://github.com/microsoft/vscode/issues/40239) @sandy081

### Extension Contributions
- [ ] :runner: Improve handling of large files or memory sizes in the Hex Editor [vscode#126268](https://github.com/microsoft/vscode/issues/126268) @connor4312 @lramos15
- [x] Improvements to the Remote extensions [vscode-remote-release#5828](https://github.com/microsoft/vscode-remote-release/issues/5828) @alexr00 @roblourens @tanhakabir @chrmarti @aeschli
- [x] Improvements to the GitHub PRI extension [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22November+2021%22) @alexr00
- [x] Improvements to the GitHub Repositories extension (see [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/7)) @joyceerhl
- [x] Improvements to the Live Preview extension (see [query](https://github.com/microsoft/vscode-livepreview/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22November+2021%22)) @lszomoru
- [ ] :runner: Work with popular extension on adopting and improving their welcome pages (e.g. docker) [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald
- [x] Work with language extensions on adoption language status indication [vscode#129037](https://github.com/microsoft/vscode/issues/129037) @isidorn

### Engineering
- [ ] :runner: Adopt `vscode` namespace for npm packages [vscode#130301](https://github.com/microsoft/vscode/issues/130301) @connor4312 **team**
- [ ] :runner: Create "inbox tracker" bot: Round-robin assign low confidence issues [vscode#136688](https://github.com/microsoft/vscode/issues/136688) @jacksonkearl
- [ ] :red_circle: :muscle: Explore learned duplicate/needs-more-info triage @jacksonkearl
- [x] Proposed API process improvements [vscode#1311651](https://github.com/microsoft/vscode/issues/1311651) @jrieken @mjbvz
- [x] Investigate consolidating the FileWatcher implementations by building on the multi-root file watcher [vscode#132483](https://github.com/microsoft/vscode/issues/132483) @bpasero
- [ ] :runner: Update the 'how to contribute' documentation for Windows 11 [#137654](Document how to develop under Windows 11) @dbaeumer

#### Builds
- [ ] :hand: Explore to use `playwright` for our desktop smoke tests [vscode#128479](https://github.com/microsoft/vscode/issues/128479) @bpasero @joaomoreno

#### Electron
- [ ] :runner: Refactor startup code to use electron's `requestSingleInstanceLock` API [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271
- [ ] :runner: Update to Electron 16 [vscode#137241](https://github.com/microsoft/vscode/pull/137241) @deepak1556 @bpasero
- [x] Electron stability improvements, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Adeepak1556+milestone%3A%22November+2021%22+-label%3Adebt+-label%3Aupstream-issue-linked) @deepak1556

#### Node.js-free, sand-boxed renderer
Implement a node.js-free, sandboxed, context isolated renderer [vscode#92164](https://github.com/microsoft/vscode/issues/92164)
- [x] Move extension host out of the workbench [vscode#123592](https://github.com/microsoft/vscode/issues/123592) @alexdima @deepak1556 @bpasero
- [ ] :runner: Enable renderer process reuse [vscode#120431](https://github.com/microsoft/vscode/issues/120431) @rzhao271 @deepak1556 @bpasero
- [ ] :hand: Enable `contextIsolation` for all windows [vscode#128099](https://github.com/microsoft/vscode/issues/128099) @bpasero @rzhao271 @deepak1556

----
### Deferred
- [ ] Explore: Support virtual trees based on name patterns [vscode#6328](https://github.com/microsoft/vscode/issues/6328) @jacksonkearl
- [ ] :red_circle: Explore "Continue On" support in core @joyceerhl
- [ ] Investigate how to avoid double results from different language providers [vscode#136667](https://github.com/microsoft/vscode/issues/136667) @jrieken
- [ ] Investigate the impact of windows sandbox for vscode installs [vscode#122951](https://github.com/microsoft/vscode/issues/122951) @deepak1556

**Comment by tristan957** [comment]
CC @deepak1556 @bpasero: I think VSCode should not release with Electron >= 14 until https://github.com/electron/electron/pull/32049 is merged, otherwise Linux users may have a really bad time.

**Comment by deepak1556** [comment]
@tristan957 thanks for the heads up! the synchronous api is not used in the code base and also Electron 16 will not be merged for the November milestone pending some cleanups https://github.com/microsoft/vscode/pull/137241

**Comment by tristan957** [comment]
Cool. Well thanks for merging it anyways!
