### ISSUE TITLE
Iteration Plan for January 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#139607]
This plan captures our work in **January**. This is a 4-week iteration. We will ship in **early February**.

## Endgame

- **January 24, 2022**: Endgame begins
- **January 28, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22January+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22January+2022%22) @isidorn **team**

### UX
- [ ] :runner: Develop VS Code design system (classifying patterns for activity bar/sidebar/views/etc.) [vscode#140601](https://github.com/microsoft/vscode/issues/140601) @misolori
- [x] Explore possible integrations between extensions view and GH Sponsors [vscode#107482](https://github.com/microsoft/vscode/issues/107482) @lychung7 @isidorn

### Workbench
- [x] Improve secondary side panel [vscode#132893](https://github.com/microsoft/vscode/issues/132893) @sbatten
- [x] Explore support for virtual trees based on name patterns [vscode#6328](https://github.com/microsoft/vscode/issues/6328) @jacksonkearl
- [x] Improve keyboard interactions for undo/redo in explorer [vscode#117621](https://github.com/microsoft/vscode/issues/117621) @jacksonkearl
- [x] Allow to open a folder in a walkthrough while preserving the walkthrough state [vscode#137544](https://github.com/microsoft/vscode/issues/137544) @jacksonkearl
- [ ] :runner: Improve language detection model to better deal with small inputs [vscode#137104](https://github.com/microsoft/vscode/issues/137104) @jacksonkearl @tylerleonhardt
- [ ] :runner: Allow to resize the ToC in the settings editor [vscode#79581](https://github.com/microsoft/vscode/issues/79581) @rzhao271
- [x] Show extension contributed default values in the settings editor [vscode#137943](https://github.com/microsoft/vscode/issues/137943) @rzhao271
- [ ] :runner: Explore improving discoverability of workbench layout options [vscode#137633](https://github.com/microsoft/vscode/issues/137633) @sbatten @lychung7
- [x] Support synching of user tasks [vscode#91011](https://github.com/microsoft/vscode/issues/91011) @sandy081

### Web
- [ ] :muscle: Explore translations in the web [vscode#136331](https://github.com/microsoft/vscode/issues/136331) @tylerleonhardt
- [x] Improve how machine names are managed in the web for settings sync [vscode#122652](https://github.com/microsoft/vscode/issues/122652) @sandy081

### Code Editor
- [x] Use sounds to notify screenreader users when inline suggestions or decorations are present, e.g. a breakpoint is on a current line [vscode#130565](https://github.com/microsoft/vscode/issues/130565), see also [this comment](https://github.com/microsoft/vscode/issues/130565#issuecomment-900246306) @hediet @isidorn
- [x] Improve auto closing brackets support for inline suggestions [vscode#136452](https://github.com/microsoft/vscode/issues/136452) @hediet
- [x] Polish highlight support for confusable Unicode characters [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aunicode-highlight+milestone%3A%22January+2022%22) @hediet
- [ ] :runner: Help migrate users off bracket pairs coloring extensions [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22January+2022%22+label%3Abracket-pair-colorization) @hediet @isidorn
- [ ] :muscle: Investigate customizing mouse shortcuts [vscode#3130](https://github.com/microsoft/vscode/issues/3130) @hediet

### Commenting
- [ ] :red_circle: :runner: Assume ownership of the commenting support @alexr00
- [ ] :runner: Provide a way to add a timestamp or detail to a comment [vscode#139524](https://github.com/microsoft/vscode/issues/139524) @alexr00
- [x] Investigate improving resolved/unresolved comments [vscode#127473](https://github.com/microsoft/vscode/issues/127473) @alexr00 @isidorn

### Notebook Editor
- [x] Improve rendering jitter in notebooks [vscode#126432](https://github.com/microsoft/vscode/issues/126432) @roblourens
- [ ] :runner: Improve code structure and dependencies [vscode#131808](https://github.com/microsoft/vscode/issues/131808) @roblourens @rebornix
- [x] Show execution progress while the executing cell is out of the viewport [vscode#130611](https://github.com/microsoft/vscode/issues/130611) @roblourens @rebornix @misolori
- [x] Improve discoverability of cell folding [vscode#132690](https://github.com/microsoft/vscode/issues/132690) @roblourens
- [ ] :muscle: Explore indicating cell status for collapsed cells [vscode#131200](https://github.com/microsoft/vscode/issues/131200) @roblourens
- [x] Support searching across inputs and outputs [vscode#140098](https://github.com/microsoft/vscode/issues/140098) @rebornix
- [ ] :runner: Experiment with running notebook controllers extensions in dedicated extension host [vscode/140374](https://github.com/microsoft/vscode/issues/140374) @rebornix
- [ ] :muscle: Experiment with readonly view of monaco editor for faster scrolling [vscode#129972](https://github.com/microsoft/vscode/issues/129972) @rebornix

### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#8605](https://github.com/microsoft/vscode-jupyter/issues/8605) @greazer **team**

### Languages
- [x] Improve discoverability of the language status pin/unpin interaction [vscode#140241](https://github.com/microsoft/vscode/issues/140241) @daviddossett @jrieken
- [ ] :runner: Finalize inlay type hint support and API @jrieken @hediet
  - [x] Inlay type hints - support cmd-click for go to type definition [vscode#129528](https://github.com/microsoft/vscode/issues/129528) @jrieken, @hediet
  - [x] Inlay type hints - support hover [vscode#129528](https://github.com/microsoft/vscode/issues/129528)@jrieken, @hediet
#### AnyCode
See [AnyCode](https://marketplace.visualstudio.com/items?itemName=ms-vscode.anycode).
- [ ] :runner: Improve the support in large workspaces - guide users to download the tarball or download it automatically  [vscode-anycode#9](https://github.com/microsoft/vscode-anycode/issues/9) @jrieken @jacksonkearl
- [x] Explore how AnyCode index can improve the Python/TS experience for vscode.dev (e.g. workspace symbol search) @jrieken
- [ ] :red_circle: :muscle: Explore bundling the extension with VS Code desktop @jrieken

#### LSP
- [ ] :runner: [Add notebook support for LSP](https://github.com/microsoft/language-server-protocol/issues/1399) @dbaeumer

#### Python
- [x] Contributions to the python extension [vscode-python#18214](https://github.com/microsoft/vscode-python/issues/18214) @brettcannon **team**

#### JavaScript/TypeScript
- [ ] :runner: Explore automatic type acqusition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz
- [ ] :runner: Explore enabling TS Server plugins on web [vscode#140455](https://github.com/microsoft/vscode/issues/140455) @mjbvz

#### HTML
- [x] Auto insert quotes after typing `=` [vscode#18071](https://github.com/microsoft/vscode/issues/18071) @aeschli

### Debug
- [ ] :runner: Prototype extension debugging in a clean environment [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand
- [ ] :muscle: Propose UI for debugging highly concurrent languages [vscode#116109](https://github.com/microsoft/vscode/issues/116109) @weinand
- [x] Support viewing and editing of binary data [vscode#140393](https://github.com/microsoft/vscode/issues/140393) @connor4312
- [x] :muscle: Exclude breakpoint from specific caller [vscode#127775](https://github.com/microsoft/vscode/issues/127775) @connor4312 @weinand
#### DAP
- [x] Grow the number of DAP maintainers [microsoft/debug-adapter-protocol#240](https://github.com/microsoft/debug-adapter-protocol/issues/240) @weinand @connor4312 @roblourens
- [ ] :runner: Explore passing standard input to debuggee [microsoft/debug-adapter-protocol#216](https://github.com/microsoft/debug-adapter-protocol/issues/216) @weinand

### Terminal
- [x] Create terminal smoke test suite [vscode#136064](https://github.com/microsoft/vscode/issues/136064) @tyriar @meganrogge
- [ ] :runner: Shell integration [vscode#133084](https://github.com/microsoft/vscode/issues/133084) @meganrogge @tyriar
- [ ] :hand: :muscle: Ligatures in the terminal [vscode#34103](https://github.com/microsoft/vscode/issues/34103) @tyriar
- [x] Automatically reply to certain output [vscode#133524](https://github.com/microsoft/vscode/issues/133524) @tyriar
- [ ] :muscle: Explore cell-by-cell navigation for screen reader users [vscode#69795](https://github.com/microsoft/vscode/issues/69795) @tyriar
- [x] Explore navigating links in terminal with the keyboard [vscode#95570](https://github.com/microsoft/vscode/issues/95570) @meganrogge

### Source Control
- [x] Polish the Sync button @misolori @lszomoru
- [ ] :runner: Large change improvements [vscode#135865](https://github.com/microsoft/vscode/issues/135865) @lszomoru

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Explore API access to open editors including focused notebooks or custom editors [vscode#15178](https://github.com/microsoft/vscode/issues/15178) @lramos15

### Extensions
- [x] Support to use the file watcher for arbitrary folders [vscode#3025](https://github.com/microsoft/vscode/issues/3025) @bpasero
- [x] Support that an extension can specify custom file icons for the file types it supports. [vscode#14662](https://github.com/microsoft/vscode/issues/14662) @aeschli
- [x] Preview extension support - support to migrate extension storage [vscode#140088](https://github.com/microsoft/vscode/issues/140088) @sandy081
- [x] Preview extension support - reduce requests to the marketplace [vscode#1139015](https://github.com/microsoft/vscode/issues/139015) @sandy081
- [ ] :runner: :muscle: Provide Webview UI toolkit usage guidelines [vscode-webview-ui-toolkit#126](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/126) @daviddossett

### Extension Contributions
- [x] Improve handling of large files or memory sizes in the Hex Editor [vscode#126268](https://github.com/microsoft/vscode/issues/126268) @connor4312 @lramos15
- [x] Improvements to the GitHub Repositories extension (see [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/8)) @joyceerhl
- [x] Improvements to the Remote extensions [vscode-remote-release#6089](https://github.com/microsoft/vscode-remote-release/issues/6089) @alexr00 @roblourens @tanhakabir @chrmarti @aeschli
- [x] Improvements to the GitHub PRI extension [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22January+2022%22) @alexr00
- [ ] :runner: Work with popular extension on adopting and improving their welcome pages [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald @lychung7
- [x] eslint - adopt preview extension support @dbaeumer
- [ ] :runner: eslint - [Investigate into ESLint support for notebooks](https://github.com/microsoft/vscode-eslint/issues/1406)

### Engineering
- [x] CLI tool (`npx vscode-bisect`) to bisect released insider builds (web, desktop) @bpasero
- [ ] :runner: Adopt `vscode` namespace for npm packages [vscode#130301](https://github.com/microsoft/vscode/issues/130301) @connor4312 @aeschli @dbaeumer @roblourens @weinand @lramos15 @sbatten
- [ ] :runner: Make our smoke tests more reliable [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asmoke-test-failure) @bpasero @tyriar **team**
- [x] Settings sync - debounce requests when a request is in progress [vscode#91286](https://github.com/microsoft/vscode/issues/91286) @sandy081
- [ ] :runner: Investigate into adaptive debouncing of requests (outline, semantic tokens) to improve experience in higher latency setups [vscode#140557](https://github.com/microsoft/vscode/issues/140557) @jrieken @alexdima

#### Electron
- [ ] :hand: Refactor startup code to use electron's `requestSingleInstanceLock` API [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271
- [x] Update to Electron 16 [vscode#137241](https://github.com/microsoft/vscode/pull/137241) @deepak1556 @bpasero
- [x] Windows occlusion tracker has incorrect behavior with vscode debugger [vscode#123257](https://github.com/microsoft/vscode/issues/123257) @deepak1556
- [x] Explore MS-Edge de-elevate-on-launch flag for [vscode#122951](https://github.com/microsoft/vscode/issues/122951) @deepak1556
- [ ] :muscle: Explore how to support direct helper process to workbench communication [vscode#131798](https://github.com/microsoft/vscode/issues/131798) @deepak1556
- [ ] :runner: Explore locale mismatch between main process and extension host [vscode#85675](https://github.com/microsoft/vscode/issues/85675) @rzhao271
- [ ] :runner: Verifying linux dependencies and improving the process [vscode#17142](https://github.com/microsoft/vscode/issues/17142) @rzhao271

#### Node.js-free, sand-boxed renderer
Implement a node.js-free, sandboxed, context isolated renderer [vscode#92164](https://github.com/microsoft/vscode/issues/92164)
- [ ] :hand: Enable `contextIsolation` for all windows [vscode#128099](https://github.com/microsoft/vscode/issues/128099) @bpasero @rzhao271 @deepak1556
- [x] Move v8-inspect-profiler out of renderer [vscode#111211](https://github.com/microsoft/vscode/issues/111211) @jrieken

----
### Deferred
- [ ] Adopt ghost text for previewing emmet expansions [vscode#139247](https://github.com/microsoft/vscode/issues/139247) @rzhao271 @hediet
- [ ] Explore "Continue On" support in core [vscode#141293](https://github.com/microsoft/vscode/issues/141293) @joyceerhl
- [ ] Problems view - add support to sort by message contents [vscode#98819](https://github.com/microsoft/vscode/issues/98819) @lszomoru
- [ ] Explore how to improve the display defaults for the git repository provider [vscode#135992](https://github.com/microsoft/vscode/issues/135992) @lszomoru @misolori
- [ ] Make repository pickers available for other extensions [vscode#141295](https://github.com/microsoft/vscode/issues/141295) @joyceerhl
- [ ] Explore inside-out silent git installation (docker-like, using winget?) [vscode#136408](https://github.com/microsoft/vscode/issues/136408) @digitarald @lszomoru
- [ ] Explore how to support enabling/disabling a group of extensions for a workspace [vscode#40239](https://github.com/microsoft/vscode/issues/40239) @sandy081

**Comment by markadrake** [comment]
@kieferrm & @JacksonKearl If you are indeed looking at issue [vscode#6328](https://github.com/microsoft/vscode/issues/6328) I'd greatly appreciate if you [kept this in context](https://docs.microsoft.com/en-us/visualstudio/ide/file-nesting-solution-explorer?view=vs-2022) during the deliberations and planning as it's a robust, flexible solution that's already in place with Visual Studio and open source development using the .net framework. 

**Thank you for mentioning this issue**. As you may know we've eagerly awaited support for 5 years. Multiple people have contributed in various ways only to make no ground at all. Worst case scenario - would you please consider modularizing (?) the current file system explorer so that we can easily replace it or extend it with our own code? If we could register our own virtual file system provider to take over and make changes - I'm sure the community can fill in the gaps. Depends on how much your team wants to bite off! Thanks again!

**Comment by jasonwilliams** [comment]
@kieferrm has there been a December release? Or will that now roll into this January one?

**Comment by TylerLeonhardt** [comment]
No December release because of the holidays.
