### ISSUE TITLE
Iteration Plan for February 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#142359]
This plan captures our work in **February**. This is a 4-week iteration. We will ship in **early March**.

## Endgame

- **February 21, 2022**: Endgame begins
- **February 25, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22February+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22February+2022%22) @isidorn **team**
- [x] Develop a high-contrast light theme [#141652](https://github.com/microsoft/vscode/issues/141652) @daviddossett

### UX
- [ ] :runner: Develop a VS Code design system (classifying patterns for activity bar/sidebar/views/etc.) [vscode#140601](https://github.com/microsoft/vscode/issues/140601) @misolori
- [ ] :runner: Explore using the window titlebar to make the command palette more discoverable [vscode#142867](https://github.com/microsoft/vscode/issues/142867) @lychung7

### Workbench
- [x] Improve the 'Go Back' and 'Go Forward' support [vscode#142152](https://github.com/microsoft/vscode/issues/137633)@bpasero
- [ ] :runner: Explore improving discoverability of workbench layout options [vscode#137633](https://github.com/microsoft/vscode/issues/137633) @sbatten @lychung7
- [x] Icon themes - Support for folder/directory names in file associations [vscode#136656](https://github.com/microsoft/vscode/issues/136656) @aeschli
- [x] Allow to resize the ToC in the settings editor [vscode#79581](https://github.com/microsoft/vscode/issues/79581) @rzhao271
- [ ] :runner: Allow user to see which settings have language overrides [vscode#131707](https://github.com/microsoft/vscode/issues/131707) @rzhao271 @lychung7 @sandy081
- [x] Support DnD for problem markers and search matches [vscode#142508](https://github.com/microsoft/vscode/issues/142508) @sandy081
- [ ] :runner: Identify gaps to provide profile like functionality including user research [vscode#139409](https://github.com/microsoft/vscode/issues/139409) @sandy081 @sana-ajani
- [ ] Improve performance when auto-expanding virtually nested files [vscode#140883](https://github.com/microsoft/vscode/issues/140883) @jacksonkearl
- [ ] :runner: Improve language detection model to better deal with small inputs [vscode#137104](https://github.com/microsoft/vscode/issues/137104) @jacksonkearl @tylerleonhardt
- [ ] :muscle: Investigate rich hovers in the timeline view [vscode#114806](https://github.com/microsoft/vscode/issues/114806) @jacksonkearl
- [ ] Explore "Continue On" support in core [vscode#141293](https://github.com/microsoft/vscode/issues/141293) @joyceerhl

### Web
- [x] :runner: Investigte in restoring open files when using the local file system [vscode#140736](https://github.com/microsoft/vscode/issues/140736) @bpasero

### Code Editor
- [x] Improve contextual unicode highlighting [vscode#140960](https://github.com/microsoft/vscode/issues/140960) @hediet
- [x] Introduce audio cues in more places [vscode#141635](https://github.com/microsoft/vscode/issues/141635) [vscode#135908](https://github.com/microsoft/vscode/issues/135908) @hediet
- [ ] Folding - Avoid spontaneous "unfold all" [vscode#139779](https://github.com/microsoft/vscode/pull/139779) @aeschli

### Commenting
- [x] :runner: Explore improvements to Comments panel [vscod#142081](https://github.com/microsoft/vscode/issues/142081) @alexr00 @isidorn
- [x] :runner: Explore resolved/unresolved comments [vscode#127473](https://github.com/microsoft/vscode/issues/127473) @alexr00 @isidorn

### Notebook Editor
- [ ] :runner: Improve code structure and dependencies [vscode#131808](https://github.com/microsoft/vscode/issues/131808) @roblourens @rebornix
- [x] Convert all built-in renders to be regular output renders [vscode#142429](https://github.com/microsoft/vscode/issues/142429) @rebornix
- [x] :runner: Improve cell collapsing UX [vscode#142690](https://github.com/microsoft/vscode/issues/142690) @roblourens @misolori
- [x] :muscle: Explore indicating cell status for collapsed cells [vscode#131200](https://github.com/microsoft/vscode/issues/131200) @roblourens
- [x] :runner: Experiment with running notebook controllers extensions in dedicated extension host [vscode/140374](https://github.com/microsoft/vscode/issues/140374) @rebornix
- [ ] :runner: Investigate showing find results in the notebook scrollbar [vscode#142985](https://github.com/microsoft/vscode/issues/142985) @rebornix
- [ ] :muscle: Consolidate notebook setting names [vscode#142986](https://github.com/microsoft/vscode/issues/142986) @rebornix @roblourens

#### Jupyter Notebooks
- [ ] :runner: Contributions to the vscode-jupyter extension [vscode-jupyter#8939](https://github.com/microsoft/vscode-jupyter/issues/8939) @greazer **team**

#### [AnyCode](https://marketplace.visualstudio.com/items?itemName=ms-vscode.anycode)
- [x] Improve the support in large workspaces - guide users to download the tarball or download it automatically [vscode-anycode#9](https://github.com/microsoft/vscode-anycode/issues/9) @jrieken @jacksonkearl

#### LSP
- [x] :runner: Add notebook support for LSP [language-server-protocol#1399](https://github.com/microsoft/language-server-protocol/issues/1399) @dbaeumer
- [x] Avoid that the LSP client monopolizes the extension host, e.g., when there are many diagnostics [#894](https://github.com/microsoft/vscode-languageserver-node/issues/894)@dbaeumer

#### Python
- [ ] :runner: Contributions to the python extension [vscode-python#18456](https://github.com/microsoft/vscode-python/issues/18456) @brettcannon **team**

#### JavaScript/TypeScript
- [ ] :runner: Adopt TypeScript 4.6 [vscode#142460](https://github.com/microsoft/vscode/issues/142460) @mjbvz
- [ ] :runner: Explore automatic type acqusition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz

#### Markdown
- [ ] :muscle: Investigate create file and image links using DnD [vscode#142990](https://github.com/microsoft/vscode/issues/142990) @mjbvz

### Debug
- [x] :runner: Support 'important' category of `OutputEvents` [vscode#138091](https://github.com/microsoft/vscode/issues/138091) @roblourens @weinand
- [x] :runner: Support proposed lazy variable evaluation [vscode#134450](https://github.com/microsoft/vscode/issues/134450) @roblourens @weinand
- [ ] :runner: Prototype extension debugging in a clean environment [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand
- [ ] :muscle: Propose UI for debugging highly concurrent languages [vscode#116109](https://github.com/microsoft/vscode/issues/116109) @weinand

#### DAP
- [x] Explore passing standard input to debuggee [microsoft/debug-adapter-protocol#216](https://github.com/microsoft/debug-adapter-protocol/issues/216) @weinand @roblourens @connor4312
- [x] Allow to return addition information in `CompletionItem` [debug-adapter-protocol#235](https://github.com/microsoft/debug-adapter-protocol/issues/235) @connor4312

#### js-debug
- [ ] :runner: :muscle: Investigate supporting to attach to webviews running inside UWP applications @connor4312 [vscode-js-debug#1209](https://github.com/microsoft/vscode-js-debug/issues/1209)

### Terminal
- [x] Warn the user when pasting multi-line text into the terminal [vscode#122683](https://github.com/microsoft/vscode/issues/122683) @tyriar
- [ ] :muscle: :runner: Support smooth scrolling in the terminal [vscode#125950](https://github.com/microsoft/vscode/issues/125950) @tyriar
- [ ] :runner: Shell integration [vscode#133084](https://github.com/microsoft/vscode/issues/133084) @tyriar @meganrogge
- [x] :runner: Explore decorations in the terminal [vscode#140308](https://github.com/microsoft/vscode/issues/140308) @meganrogge
- [ ] :muscle: Highlight all matches when searching in the terminal [vscode#134790](https://github.com/microsoft/vscode/issues/134790) @meganrogge
- [ ] :muscle: :runner: Support "Copy as HTML" in the terminal [vscode#20813](https://github.com/microsoft/vscode/issues/20813) @meganrogge

### Source Control
- [ ] Make repository pickers available for other extensions [vscode#141295](https://github.com/microsoft/vscode/issues/141295) @joyceerhl
- [x] :runner: Automatically close unused git diff editors [vscode#141475](https://github.com/microsoft/vscode/issues/141475) @lszomoru

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Explore API access to open editors including focused notebooks or custom editors [vscode#15178](https://github.com/microsoft/vscode/issues/15178) @lramos15

### Extensions
- [x] Provide Webview UI toolkit usage guidelines [vscode-webview-ui-toolkit#126](https://github.com/microsoft/vscode-webview-ui-toolkit/issues/126) @daviddossett
- [x] Improve extension recommendation prompts,  [vscode#136301](https://github.com/microsoft/vscode/issues/136301) @sandy081 @isidorn
- [ ] Show GH Sponsor information for extension authors [vscode#107482](https://github.com/microsoft/vscode/issues/107482) @lychung7 @isidorn @sandy081

### Extension Contributions
- [ ] :runner: Improvements to the GitHub Repositories extension (see [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/9)) @joyceerhl
- [ ] :runner: Improvements to the Remote extensions [vscode-remote-release#6290](https://github.com/microsoft/vscode-remote-release/issues/6290) @alexr00 @roblourens @tanhakabir @chrmarti @aeschli
- [ ] :runner: Improvements to the GitHub PRI extension [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22February+2022%22) @alexr00
- [ ] :runner: Work with popular extension on adopting and improving their welcome pages [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald @lychung7
- [x] Investigate notebook support in ESLint [vscode-eslint#1406](https://github.com/microsoft/vscode-eslint/issues/1406) @dbaeumer

### Install
- [ ] Adopt the Windows 11 explorer context menu [vscode#127365](https://github.com/microsoft/vscode/issues/127365) @deepak1556

### Engineering
- [x] Define and organize the role of a [Build Champion](https://github.com/microsoft/vscode/wiki/Build-Champion) [vscode#142118](https://github.com/microsoft/vscode/issues/142118) @tyriar @bpasero
- [x] :runner: Ensure translation builds allow incrementation re-runs [vscode-loc#713](https://github.com/microsoft/vscode-loc/issues/713) @tylerleonhardt
- [ ] :runner: Improve restore of layout in webviews [vscode#106585](https://github.com/microsoft/vscode/issues/106585) @mjbvz
- [x] Adopt `vscode` namespace for npm packages [vscode#130301](https://github.com/microsoft/vscode/issues/130301) @connor4312 @aeschli @dbaeumer @roblourens @weinand @sbatten
- [x] Make LanguageFeatureRequestDelays easier to use and adopt in more places [vscode#140557](https://github.com/microsoft/vscode/issues/140557) @jrieken @aeschli

#### Electron
- [x] Update to Electron 16 [vscode#137241](https://github.com/microsoft/vscode/pull/137241) @deepak1556 @bpasero
- [ ] :muscle: Explore how to support direct helper process to workbench communication [vscode#131798](https://github.com/microsoft/vscode/issues/131798) @deepak1556
- [x] :runner: Improve windows control overlay feature in Electron to adjust with theme changes [vscode#142414](https://github.com/microsoft/vscode/issues/142414) @deepak1556
- [x] Upgrade-WG rotation Feb 7-15 @deepak1556
- [x] Explore locale mismatch between main process and extension host [vscode#85675](https://github.com/microsoft/vscode/issues/85675) @rzhao271
- [ ] :runner: Verifying linux dependencies and improving the process [vscode#17142](https://github.com/microsoft/vscode/issues/17142) @rzhao271
- [ ] :muscle: Fix cursor for draggable region elements on macOS [vscode#140724](https://github.com/microsoft/vscode/issues/140724) @rzhao271
- [ ] :hand: Refactor startup code to use electron's `requestSingleInstanceLock` API [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271

#### Node.js-free, sand-boxed renderer
Implement a node.js-free, sandboxed, context isolated renderer [vscode#92164](https://github.com/microsoft/vscode/issues/92164)
- [x] :runner: Investigate moving extension scanning out of the renderer process [vscode#142078](https://github.com/microsoft/vscode/issues/142078) @alexdima
- [ ] :hand: Enable `contextIsolation` for all windows [vscode#128099](https://github.com/microsoft/vscode/issues/128099) @bpasero @rzhao271 @deepak1556

----
### Deferred
- [ ] Adopt ghost text for previewing emmet expansions [vscode#139247](https://github.com/microsoft/vscode/issues/139247) @rzhao271 @hediet
- [ ] Explore translations in the web [vscode#136331](https://github.com/microsoft/vscode/issues/136331) @tylerleonhardt
- [ ] Explore inside-out silent git installation (docker-like, using winget?) [vscode#136408](https://github.com/microsoft/vscode/issues/136408) @digitarald @lszomoru
- [ ] Large change improvements [vscode#135865](https://github.com/microsoft/vscode/issues/135865) @lszomoru
- [ ] Explore cell-by-cell navigation for screen reader users [vscode#69795](https://github.com/microsoft/vscode/issues/69795) @tyriar

**Comment by brettcannon** [comment]
@jpallatin please see https://github.com/microsoft/vscode/pull/137241 where we are working towards adopting Electron 16.

**Comment by Acumane** [comment]
Please, *please* do consider addressing #141349 in this plan! This [new side panel](https://code.visualstudio.com/updates/v1_64#_new-side-panel) may indeed prove useful for some, but it's left many of us without a [valuable workflow](https://github.com/microsoft/vscode/issues/141349#issuecomment-1032707544) (one that's worked for years, I should add). This is *not* a feature request, but rather a plea to "iterate" on this regressive change introduced in `1.64.1`.

**Comment by samusxx** [comment]
You need to see my wrongfully closed issues. Neither was a question, nor outside the scope.

**Comment by Tyriar** [comment]
1.65 has been released
