### ISSUE TITLE
Improve Typescript and Javascript out of the box experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#144062]
I plan to investigate the JS+TS out of the box experience, and will update this issue with action items as I come across them:

- [ ] Improve JS/TS VS Code docs https://github.com/microsoft/vscode-docs/issues/5205
- [ ] TS no launch.json debug https://github.com/microsoft/vscode/issues/124280
- [ ] Better Typescript workspace setup - https://github.com/microsoft/TypeScript/issues/48597
- [ ] Better support for Javascript workspaces - https://github.com/microsoft/TypeScript/issues/48598
- [ ] Contribute to the welcome view https://github.com/microsoft/TypeScript/issues/48489

fyi @jrieken @mjbvz @DanielRosenwasser @digitarald for ideas

**Comment by isidorn** [comment]
I took an existing JS project and we have 0 ux on how to convert that project to typescript. I think we should invest in tools that generate a `jsconfig` or a `tsconfig.json`. I found a create a `jsconfig.file` under the language status, this command opens a new editor with the content pre-filled. Here are some ideas for improvements:
1. Create a `jsconfig.file` should also be present in the command palette. There should also be a "create a tsconfig.file" 
2. We should review the attributes that get generated in this config files, to make sure the most popular ones are there so the users can easily discover them. We can consider to add comments for clarificatino
3. The commands should be contributed to the Explorer Context Menu - if `jsconfig` or `tsconfig` can not be found in the workspace. 
4. We should make the problems welcome view contributable. Same how the Explorer and Debug do this already. So if there are no problems the welcome view is shown. This is a great opportunity for the Typescript extension to contribute a button like "For more precise error reporting generate `jsconfig.json` / `tsconfig.json`". fyi @lszomoru
5. Typescript needs to contribute to the welcome view. Same how python is doing. fyi @digitarald

**Comment by isidorn** [comment]
Feedback from Typescript team: 
* the ideas sound good
* offering to generate `tsconfig.json` is ok to be aggressive. For `jsconfig.json` we should be more subtle. We should think about generating `jsconfig.json` inside the `.vscode` folder.
* we sometimes can not figure out what is the right location to generate `tsconfig.json`. When it is unclear we should ask user
* if we want to market some attributes in `tsconfig.json` / `jsconfig.json` we should write them in those files even if they have a default value so users can discover them
* [Related discussion](https://github.com/microsoft/TypeScript/issues/45558) for inferring with jsconfig.json not present. Turns out it is complex.

Based on this great discussion I have updated the initial comment with action items.

fyi @chrisdias

**Comment by isidorn** [comment]
We have synced with the TS team and they will look into https://github.com/microsoft/TypeScript/issues/48597, https://github.com/microsoft/TypeScript/issues/48598 and https://github.com/microsoft/TypeScript/issues/48489

For TS docs Greg and me can look into it this and next week.
For js/ts getting started Connor will most likely look next milestone into this.

Thus moving this wrapper issue to backlog, and each linked issue will be tracked in different milestones / projects. Thanks
