### ISSUE TITLE
Iteration Plan for March 2022 [DRAFT]

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#144519]
This plan captures our work in **March**. This is a 4-week iteration. We will ship in **early April**.

## Endgame

- **March 22, 2022**: Endgame begins
- **March 25, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22March+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22March+2022%22) @isidorn **team**

### UX
- [ ] :runner: Develop a VS Code design system (classifying patterns for activity bar/sidebar/views/etc.) [vscode#140601](https://github.com/microsoft/vscode/issues/140601) @misolori
- [ ] :red_circle: Explore 3-way merge editor @daviddossett
- [ ] :red_circle: Explore notification improvements @daviddossett
- [ ] :red_circle: Explore variations for `File > New File` and `File > New File...` @lychung7 @digitarald @sbatten

### Workbench
- [ ] :runner: Improve discoverability of workbench layout options [vscode#137633](https://github.com/microsoft/vscode/issues/137633) @sbatten @lychung7
- [ ] :runner: Allow user to see which settings have language overrides [vscode#131707](https://github.com/microsoft/vscode/issues/131707) @rzhao271 @lychung7 @sandy081
- [ ] :runner: Identify gaps to provide profile like functionality including user research [vscode#139409](https://github.com/microsoft/vscode/issues/139409) @sandy081 @sana-ajani
- [ ] Explore providing a local file history [vscode#26339](https://github.com/microsoft/vscode/issues/26339) @bpasero
- [ ] :red_circle: Expose the confidence level of the history-based language detection model @jacksonkearl
- [ ] :red_circle: Consolidate and improve reduced motion mode @jacksonkearl
- [ ] :red_circle: :runner: Improve virtual file nesting for certain file icon themes @jacksonkearl
- [ ] :muscle: Explore `Continue On...` support in core [vscode#141293](https://github.com/microsoft/vscode/issues/141293) @joyceerhl
- [ ] :muscle: Adopt ghost text for previewing emmet expansions [vscode#139247](https://github.com/microsoft/vscode/issues/139247) @rzhao271 @hediet

### Web
- [x] :runner: Support DnD of local files when using a local file system [vscode#141935](https://github.com/microsoft/vscode/issues/141935) @bpasero
- [ ] :red_circle: Support workspace trust in the web @sbatten

### Code Editor
- [ ] :red_circle: Explore using injected text for quick suggestions @jrieken @hediet
- [ ] React to feedback on automatic brackets completions in inline completions [vscode#141550](https://github.com/microsoft/vscode/issues/141550) @hediet
- [ ] Adopt bracket AST infrastructure for all bracket related features [vscode#132536](https://github.com/microsoft/vscode/issues/132536) @hediet
- [ ] :red_circle: :muscle: Explore moving tokenization to a web worker @hediet
- [ ] :red_circle: :muscle: Align editor find widget with the notebook find widget @rebornix

### Commenting
- [ ] Improve the create comment UI [vscode-pull-request-github#2588](https://github.com/Microsoft/vscode-pull-request-github/issues/2588) @alexr00 @alexdima
- [ ] :runner: Explore resolved/unresolved comments [vscode#127473](https://github.com/microsoft/vscode/issues/127473) @alexr00 @isidorn
- [ ] :red_circle: Explore cell level commenting in notebooks @rebornix

### Notebook Editor
- [ ] :runner: Improve code structure and dependencies [vscode#131808](https://github.com/microsoft/vscode/issues/131808) @roblourens @rebornix
- [ ] :runner: Investigate showing find results in the notebook scrollbar [vscode#142985](https://github.com/microsoft/vscode/issues/142985) @rebornix
- [ ] :runner: Provide developer command to run notebook controllers extensions in dedicated extension host [vscode/140374](https://github.com/microsoft/vscode/issues/140374) @rebornix
- [ ] :red_circle: :muscle: Allow resizing for the find widget in notebooks @rebornix
- [ ] :muscle: Consolidate notebook setting names [vscode#142986](https://github.com/microsoft/vscode/issues/142986) @rebornix @roblourens

#### Jupyter Notebooks
- [ ] :red_circle: Contributions to the vscode-jupyter extension @greazer **team**

#### [AnyCode](https://marketplace.visualstudio.com/items?itemName=ms-vscode.anycode)
- [ ] :red_circle: Enable language contributions for AnyCode @jrieken @aeschli
- [ ] :red_circle: Investigate bundling the AnyCode extension for VS Code desktop @jrieken @aeschli

#### LSP
- [ ] :red_circle: Prepare LSP v3.17 with support for inlay hints, type hierarchy, inline code, pull diagnostics support @dbaeumer
- [ ] :red_circle: Adopt LSIF's mapped types annotations to LSP @dbaeumer @karthiknadig 

#### Python
- [ ] :red_circle: Contributions to the python extension @brettcannon **team**

#### JavaScript/TypeScript
- [ ] Improve Typescript and Javascript out of the box experience [vscode#144062](https://github.com/microsoft/vscode/issues/144062) @isidorn @gregvanl
- [ ] :muscle: Explore automatic type acqusition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz
- [ ] Support TS server plugins on web [vscode#140455](https://github.com/microsoft/vscode/issues/140455) @mjbvz

#### Markdown
- [ ] :muscle: Investigate create file and image links using DnD [vscode#142990](https://github.com/microsoft/vscode/issues/142990) @mjbvz

#### CSS
- [ ] :red_circle: Provide a CSS formatter out-of-the-box @aeschli

### Debug
- [ ] Explore: Allow debug extensions to show diagnostic information in the breakpoints view [vscode#142870](https://github.com/microsoft/vscode/issues/142870) @roblourens @weinand @connor4312
- [ ] :runner: Prototype extension debugging in a clean environment [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand

#### DAP
- [ ] Allow a debuggee to be disconnected gracefully [debug-adapter-protocol#196](https://github.com/microsoft/debug-adapter-protocol/issues/196) @weinand
- [ ] `Evaluate` request sent with unspecified `variables` context [debug-adapter-protocol#233](https://github.com/microsoft/debug-adapter-protocol/issues/233) @weinand

#### js-debug
- [ ] Adopt `completionItem.details` [vscode#142124](https://github.com/microsoft/vscode/issues/142124) @roblourens @connor4312
- [ ] :runner: :muscle: Investigate supporting to attach to webviews running inside UWP applications  [vscode-js-debug#1209](https://github.com/microsoft/vscode-js-debug/issues/1209) @connor4312
- [ ] :muscle: Investigate: Smart Step Into [vscode#123879](https://github.com/microsoft/vscode/issues/123879) @connor4312 @weinand

### Testing
- [ ] :muscle: Provide support for Go to Test/Go to Test Subject [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312

### Terminal
- [ ] :red_circle: :runner: Improve Shell integration @tyriar @meganrogge
- [ ] :runner: Support "Copy as HTML" in the terminal [vscode#20813](https://github.com/microsoft/vscode/issues/20813) @meganrogge
- [ ] :red_circle: Enable scrollbar annotations in the terminal @meganrogge
- [ ] Highlight all matches when searching in the terminal [vscode#134790](https://github.com/microsoft/vscode/issues/134790) @meganrogge

### Source Control
- [ ] :muscle: Make repository pickers available for other extensions [vscode#141295](https://github.com/microsoft/vscode/issues/141295) @joyceerhl
- [ ] Adopt new markdown rendering support in timeline hovers [vscode#144397](https://github.com/microsoft/vscode/issues/144397) @lszomoru @lychung7
- [ ] A full editor can be used as git commit message editor [vscode#95266](https://github.com/microsoft/vscode/pull/95266) @lszomoru @lychung7
- [ ] :red_circle: Provide sorting options for repositories in the SCM view @lszomoru 

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Explore API access to open editors including focused notebooks or custom editors [vscode#15178](https://github.com/microsoft/vscode/issues/15178) @lramos15
- [ ] :red_circle: Finalize the Notebook API that is used by the LSP Notebook support @jrieken @rebornix @dbaeumer
- [x] :runner: Add support for drag&drop in custom trees [vscode#32592](https://github.com/microsoft/vscode/issues/32592) @alexr00

### Extensions
- [ ] Show GH Sponsor information for extension authors [vscode#107482](https://github.com/microsoft/vscode/issues/107482) @sandy081 @lychung7 @isidorn
- [ ] :red_circle: :muscle: Investigate pre-release support for built-in extensions @sandy081

### Extension Contributions
- [ ] :runner: Improvements to the GitHub Repositories extension (see [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/10)) @joyceerhl
- [ ] :red_circle: Improvements to the Remote extensions @alexr00 @roblourens @tanhakabir @chrmarti @aeschli
- [ ] :runner: Improvements to the GitHub PRI extension (see [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22March+2022%22)) @alexr00
- [ ] :runner: Work with popular extension on adopting and improving their welcome pages [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald @lychung7
- [ ] :red_circle: :muscle: Investigate eslint notebook support in the web @dbaeumer

### Install
- [ ] Adopt the Windows 11 explorer context menu [vscode#127365](https://github.com/microsoft/vscode/issues/127365) @deepak1556

### Engineering
- [ ] :runner: Improve restore of layout of custom views [vscode#106585](https://github.com/microsoft/vscode/issues/106585) @mjbvz
- [ ] :red_circle: Review errors to identify which ones are actionable as error telemetry @lramos15 **team**

#### Electron
- [ ] Update to Electron 16 [vscode#137241](https://github.com/microsoft/vscode/pull/137241) @deepak1556 @bpasero
- [ ] Explore how to support direct helper process to workbench communication [vscode#131798](https://github.com/microsoft/vscode/issues/131798) @deepak1556
- [ ] :runner: Verifying linux dependencies and improving the process [vscode#17142](https://github.com/microsoft/vscode/issues/17142) @rzhao271
- [ ] :muscle: Fix cursor for draggable region elements on macOS [vscode#140724](https://github.com/microsoft/vscode/issues/140724) @rzhao271
- [ ] :hand: Refactor startup code to use electron's `requestSingleInstanceLock` API [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271

#### Node.js-free, sand-boxed renderer
Implement a node.js-free, sandboxed, context isolated renderer [vscode#92164](https://github.com/microsoft/vscode/issues/92164)
- [ ] :hand: Enable `contextIsolation` for all windows [vscode#128099](https://github.com/microsoft/vscode/issues/128099) @bpasero @rzhao271 @deepak1556

----
### Deferred
- [ ] :runner: Explore using the window titlebar to make the command palette more discoverable [vscode#142867](https://github.com/microsoft/vscode/issues/142867) @lychung7
- [ ] :muscle: :runner: Support smooth scrolling in the terminal [vscode#125950](https://github.com/microsoft/vscode/issues/125950) @tyriar
- [ ] Explore translations in the web [vscode#136331](https://github.com/microsoft/vscode/issues/136331) @tylerleonhardt
- [ ] Explore inside-out silent git installation (docker-like, using winget?) [vscode#136408](https://github.com/microsoft/vscode/issues/136408) @digitarald @lszomoru
- [ ] Explore cell-by-cell navigation for screen reader users [vscode#69795](https://github.com/microsoft/vscode/issues/69795) @tyriar
- [ ] :muscle: Propose UI for debugging highly concurrent languages [vscode#116109](https://github.com/microsoft/vscode/issues/116109) @weinand

**Comment by ericdrobinson** [comment]
This item:

> - [ ] Allow a debuggee to be disconnected gracefully [debug-adapter-protocol#196](https://github.com/microsoft/debug-adapter-protocol/issues/196) @weinand

is somewhat related to [this bug](https://github.com/microsoft/vscode/issues/143991) (which should have a ~1-line fix). It would be nice to have parity between these two features if graceful disconnection is added. By "parity" I mean that if a Launch Request Type debug session should be allowed to disconnect gracefully (I see no reason that it wouldn't if this feature is implemented), then Attach Request Type debug sessions should be allowed to terminate gracefully (currently they are not due to a vestigial request type check).

**Comment by Devon7925** [comment]
Why did this get unpinned?

**Comment by joshsleeper** [comment]
> - [x] Update to Electron 17 https://github.com/microsoft/vscode/pull/137241 @deepak1556 @bpasero

either the text is wrong and 16 is correct, or it's probably supposed to be linking to #143223 which I think is actually the 17 upgrade?
the date of the 16 PR merge feels too far back to be correct.
