### ISSUE TITLE
Iteration Plan for April 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#146672]
This plan captures our work in **April**. This is a 5-week iteration. We will ship in early **May**.

## Endgame
- **April 25, 2022**: Endgame begins
- **April 29, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22April+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22April+2022%22) @isidorn **team**
- [x] Improve light high contrast syntax highlighting [vscode#146687](https://github.com/microsoft/vscode/issues/146687) @daviddossett

### UX
- [x] Explore 3-way merge editor [vscode#146091](https://github.com/microsoft/vscode/issues/146091) @daviddossett @isidorn
- [ ] :runner: Explore variations for `File > New File` and `File > New File...` [vscode#145046](https://github.com/microsoft/vscode/issues/145046) @lychung7 @digitarald @sbatten
- [x] Make non-pinned language status items more prominent [vscode#145950](https://github.com/microsoft/vscode/issues/145950) @daviddossett @jrieken
- [x] Use language status for formatter conflicts [vscode#148053](https://github.com/microsoft/vscode/issues/148053) @jrieken
- [x] Update Figma toolkit with new components (Quick pick multi-select, Secondary side bar, etc.) [vscode#146365](https://github.com/microsoft/vscode/issues/146365) @lychung7
- [x] Explore how to better intergrate remote file system providers such as OneDrive or  Google Drive [vscode#146668](https://github.com/microsoft/vscode/issues/146688) @daviddossett
- [ ] :runner: Explore a `Share as...` menu for creating `vscode.dev` links [vscode#146309](https://github.com/microsoft/vscode/issues/146309) @lychung7
- [ ] :runner: Explore improving the discoverability of filtering in tree views [vscode#146806](https://github.com/microsoft/vscode/issues/146806) @misolori @joaomoreno
- [ ] :muscle: Explore using the window titlebar to make the command palette more discoverable [vscode#142867](https://github.com/microsoft/vscode/issues/142867) @lychung7
- [ ] :muscle: Explore quick start from snippet/templates in empty files [vscode#145929](https://github.com/microsoft/vscode/issues/145929) @digitarald

### Workbench
- [ ] :runner: Allow user to see which settings have language overrides [vscode#131707](https://github.com/microsoft/vscode/issues/131707) @rzhao271 @lychung7 @sandy081
- [x] Improve language filter discoverability [vscode#145710](https://github.com/microsoft/vscode/issues/145710) @rzhao271 @lychung7
- [x] 🏃 Local history - flush history before shutdown when connected to a remote [vscode#146554](https://github.com/microsoft/vscode/issues/146554) @bpasero
- [x] Initial profile support for settings, extensions, activity bar, views, view container, status bar [vscode#146729](https://github.com/microsoft/vscode/issues/146729) @sandy081
  - [x] Support to export a profile from the current workbench
  - [x] Support to import a profile from a file/URL
  - [x] Enable profile support in the storage service  @bpasero
- [ ] :runner: Explore profile managements [vscode#116740](https://github.com/microsoft/vscode/issues/116740) @lychung7  @sana-ajani @sandy081
- [ ] :runner: Problems view - support rendering as a table [vscode#98819](https://github.com/microsoft/vscode/issues/98819) @lszomoru
- [ ] :runner: :muscle: Explore `Continue On...` support in core [vscode#141293](https://github.com/microsoft/vscode/issues/141293) @joyceerhl
- [ ] :runner: :muscle: Adopt inline suggestions for previewing emmet expansions [vscode#139247](https://github.com/microsoft/vscode/issues/139247) @hediet @rzhao271
- [ ] :muscle: Explore a view header menu contribution point in the Explorer [vscode#108271](https://github.com/microsoft/vscode/issues/108271) @JacksonKearl
- [ ] :runner: :muscle: Adopt Window Control Overlay API in electron 18 [vscode#140694](https://github.com/microsoft/vscode/issues/140694) @sbatten

### Web
- [ ] :runner: Support workspace trust in the web [vscode#145564](https://github.com/microsoft/vscode/issues/145564) @sbatten
- [ ] :runner: Explore how a web extension can leverage the [WebUSB API](https://wicg.github.io/webusb) [vscode#116761](https://github.com/microsoft/vscode/issues/116761) @mjbvz @alexdima

### Code Editor
- [x] Adopt bracket AST infrastructure for all bracket related features [vscode#132536](https://github.com/microsoft/vscode/issues/132536) @hediet
- [ ] Context menu on the minimap to hide/show it [vscode#148131](https://github.com/microsoft/vscode/issues/148131)@alexdima
- [x] Add support for defining scopes without brackets in vscode-textmate [vscode#144736](https://github.com/microsoft/vscode/issues/144736) @hediet
- [ ] :runner: Explore the implementation of a merge editor [vscode#146091](https://github.com/microsoft/vscode/issues/146091) @hediet @jrieken @alexdima
- [ ] :runner: :muscle: Explore moving tokenization to a web worker [vscode#147066](https://github.com/microsoft/vscode/issues/147066) @hediet
- [ ] :muscle: Align editor find widget with the notebook find widget [vscode#144851](https://github.com/microsoft/vscode/issues/144851) @rebornix
- [ ] :muscle: Explore variable line heights in the editor [vscode#147067](https://github.com/microsoft/vscode/issues/147067) @hediet
- [ ] :runner: Improve presentation of inline suggestions with inprecise prefix matches [vscode#147068](https://github.com/microsoft/vscode/issues/147068) @hediet @misolori

### Commenting
- [ ] Improve cell level commenting in notebooks [vscode#144850](https://github.com/microsoft/vscode/issues/144850) @rebornix
- [x] Comments panel improvements [vscode#127473](https://github.com/microsoft/vscode/issues/127473) @alexr00
- [x] Support to comment on ranges of lines [vscode#146510](https://github.com/microsoft/vscode/issues/146510) @alexr00

### Notebook Editor
- [ ] :runner: Explore support for proxy controllers [vscode#146942](https://github.com/microsoft/vscode/issues/146942) @rebornix @misolori
- [ ] :runner: Tune autoselection of controllers [vscode#146339](https://github.com/microsoft/vscode/issues/146339) @rebornix
- [x] Provide a  url for cell locations like `https://github.com/owner/repo/blob/master/notebook.ipynb#C2:L6-10` [vscode#147183](https://github.com/microsoft/vscode/issues/147183) @rebornix
- [x] Introduce settings to change line height and font size of the built-in text output renders [vscode#123149](https://github.com/microsoft/vscode/issues/123149) @amunger
- [ ] :runner: Improve code structure and dependencies [vscode#131808](https://github.com/microsoft/vscode/issues/131808) @roblourens @rebornix
- [ ] :runner: Explore allowing extensions to manage cell context keys [vscode#146686](https://github.com/microsoft/vscode/issues/146686) @roblourens
- [ ] :runner: Explore improving files search results for notebooks [vscode#95275](https://github.com/microsoft/vscode/issues/95275) @roblourens
- [ ] :runner: Improve automatic language detection in ployglot notebooks [vscode#147184](https://github.com/microsoft/vscode/issues/147184) @jacksonkearl @rebornix
- [ ] :muscle: Allow resizing for the find widget in notebooks [vscode#141516](https://github.com/microsoft/vscode/issues/141516) @rebornix
- [ ] :muscle: Consolidate notebook setting names [vscode#142986](https://github.com/microsoft/vscode/issues/142986) @rebornix @roblourens

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#9566](https://github.com/microsoft/vscode-jupyter/issues/9566) @greazer **team**

#### [AnyCode](https://marketplace.visualstudio.com/items?itemName=ms-vscode.anycode)
- [ ] :red_circle: :runner: Investigate bundling the AnyCode extension for VS Code desktop @jrieken @aeschli @alexdima
- [ ] Explore CSS language support focussing on cross-file results [vscode-anycode#35](https://github.com/microsoft/vscode-anycode/issues/35) @aeschli

#### LSP
- [x] Introduce a new capability to allow clients and servers to agree on using UTF8 position encoding [LSP #376](https://github.com/microsoft/language-server-protocol/issues/376) @dbaeumer
- [x] Prepare LSP v3.17 with support for inlay hints, type hierarchy, inline code, pull diagnostics support [LSP query](https://github.com/microsoft/language-server-protocol/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.17) [languageserver-node query](https://github.com/microsoft/vscode-languageserver-node/issues?q=is%3Aopen+is%3Aissue+milestone%3A3.17) @dbaeumer
- [x] (partly deferred) Add support to suspend a language server on idle [LSP Node #97](https://github.com/microsoft/vscode-languageserver-node/issues/97) @dbaeumer

#### Python
- [x] Contributions to the python extension [vscode-python#18850](https://github.com/microsoft/vscode-python/issues/18850) @brettcannon **team**

#### JavaScript/TypeScript
- [ ] Improve Typescript and Javascript out of the box experience [vscode#144062](https://github.com/microsoft/vscode/issues/144062) @isidorn @gregvanl
- [ ] :runner: Support TS server plugins on web [vscode#140455](https://github.com/microsoft/vscode/issues/140455) @mjbvz
- [ ] :hand: Explore automatic type acqusition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz

#### Markdown
- [ ] :runner: Investigate create file and image links using DnD [vscode#142990](https://github.com/microsoft/vscode/issues/142990) @mjbvz

### Debug
- [ ] :runner: Support showing diagnostic information in the breakpoints view [vscode#142870](https://github.com/microsoft/vscode/issues/142870) @roblourens @weinand @connor4312
- [x] Support suspendDebuggee option on Disconnect UI [vscode#134412](https://github.com/microsoft/vscode/issues/134412) @roblourens @weinand
- [x] Add option to automatically expand lazy getters [vscode#144861](https://github.com/microsoft/vscode/issues/144861) @roblourens
- [ ] :runner: Remove special treatment of extension debugging in VS Code (Prototype extension debugging in a clean environment) [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand

#### DAP
- [x] Investigate support for executing commands [debug-adapter-protocol#231](https://github.com/microsoft/debug-adapter-protocol/issues/231) @weinand @connor4312

#### js-debug
- [ ] :muscle: Investigate: Smart Step Into [vscode#123879](https://github.com/microsoft/vscode/issues/123879) @connor4312 @weinand
- [ ] :hand: Investigate supporting to attach to webviews running inside UWP applications  [vscode-js-debug#1209](https://github.com/microsoft/vscode-js-debug/issues/1209) @connor4312

### Testing
- [ ] :muscle: Provide support for Go to Test/Go to Test Subject [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312

### Terminal
- [x] Polish shell integration [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+assignee%3Ameganrogge+milestone%3A%22April+2022%22+-label%3Averification-found+-label%3A*duplicate+is%3Aclosed+label%3Aterminal-shell-integration+) @meganrogge
- [x] Highlight all matches when searching in the terminal [vscode#134790](https://github.com/microsoft/vscode/issues/134790) @meganrogge

### Source Control
- [x] Make repository pickers available for other extensions [vscode#141295](https://github.com/microsoft/vscode/issues/141295) @joyceerhl
- [ ] A full editor can be used as git commit message editor [vscode#30562](https://github.com/microsoft/vscode/pull/30562) @lszomoru @lychung7
- [x] Provide sorting options for repositories in the SCM view [vscode#146359](https://github.com/microsoft/vscode/pull/146359) @lszomoru

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] Finalize API access to open editors including focused notebooks or custom editors [vscode#15178](https://github.com/microsoft/vscode/issues/15178) @lramos15
- [ ] :red_circle: Begin finalization of remaining proposed notebook API @mjbvz @rebornix @roblourens

### Extensions
- [x] Add support to drag a file from the OS into a custom tree view [vscode#146734](https://github.com/microsoft/vscode/issues/146734) @alexr00
- [x] Explore deprecated extensions [vscode#4772](https://github.com/microsoft/vscode/issues/4772) @lychung7 @isidorn @sandy081
- [x] Unable to enable extension that depends on another disabled extension [vscode#144294](https://github.com/microsoft/vscode/issues/144294) @sandy081
- [x] Align Extension's UI with its runtime status [vscode#144444](https://github.com/microsoft/vscode/issues/144444) @sandy081

### Extension Contributions
- [x] Improvements to the GitHub Repositories extension (see [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/11)) @joyceerhl
- [x] Improvements to the Remote extensions [vscode-remote-release#6554](https://github.com/microsoft/vscode-remote-release/issues/6554) @alexr00 @tanhakabir @chrmarti @aeschli
- [x] Improvements to the GitHub PRI extension (see [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22April+2022%22)) @alexr00
- [ ] Work with popular extension on adopting and improving their welcome pages [vscode#118402](https://github.com/microsoft/vscode/issues/118402) @digitarald @lychung7
- [x] Make the eslint extension more approachable for new contributors [ESLint #1447](https://github.com/microsoft/vscode-eslint/issues/1447) @dbaeumer
- [ ] :muscle: Investigate eslint notebook support in the web [vscode-eslint#1366](https://github.com/microsoft/vscode-eslint/issues/1366) @dbaeumer

### Install
- [ ] :muscle: Explore adopting to the Windows 11 explorer context menu [vscode#127365](https://github.com/microsoft/vscode/issues/127365) @deepak1556

### Engineering
- [ ] Review errors to identify which ones are actionable as error telemetry [vscode#145043](https://github.com/microsoft/vscode/issues/145043) @lramos15 **team**
- [x] Decide on a subset of shared issue labels to simplify moving issues between repositories [issue](https://github.com/microsoft/vscode-internalbacklog/issues/2799) @brettcannon
- [x] Use `playwright` for our desktop smoke tests [vscode#128479](https://github.com/microsoft/vscode/issues/128479) @bpasero @joaomoreno
- [ ] Issue reporter template - include versions of built-in extensions that have been updated [vscode#145529](https://github.com/microsoft/vscode/issues/145529) @sandy081
- [ ] :red_circle: Provide a translation build for our extensions; onboard the Python extension @tylerleonhardt @paulacamargo25

#### Electron
- [x] Explore how to support direct helper process to workbench communication [vscode#131798](https://github.com/microsoft/vscode/issues/131798) @deepak1556
- [ ] :runner: Improve dependency generation for Debian [vscode#13089](https://github.com/microsoft/vscode/issues/13089) @rzhao271
- [ ] :runner: :muscle: Refactor startup code to use electron's `requestSingleInstanceLock` API [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271
- [ ] :muscle: Fix cursor for draggable region elements on macOS [vscode#140724](https://github.com/microsoft/vscode/issues/140724) @rzhao271

#### Node.js-free, sand-boxed renderer
Implement a node.js-free, sandboxed, context isolated renderer [vscode#92164](https://github.com/microsoft/vscode/issues/92164)
- [ ] :muscle: Enable `contextIsolation` for all windows [vscode#128099](https://github.com/microsoft/vscode/issues/128099) @bpasero @rzhao271 @deepak1556

### Documentations
- [x] Improve visibility of extension guidelines [vscode-docs#5207](https://github.com/microsoft/vscode-docs/issues/5207) @daviddossett
- [ ] :runner: Draft Git Beginner's Docs [vscode-docs#5033](https://github.com/microsoft/vscode-docs/issues/5033) @digitarald @burkeholland
- [x] New Rust language topic [vscode-docs#4531](https://github.com/microsoft/vscode-docs/issues/4531) @gregvanl

----
### Deferred
- [ ] Explore translations in the web [vscode#136331](https://github.com/microsoft/vscode/issues/136331) @tylerleonhardt
- [ ] Support smooth scrolling in the terminal [vscode#125950](https://github.com/microsoft/vscode/issues/125950) @tyriar
- [ ] Explore inside-out silent git installation (docker-like, using winget?) [vscode#136408](https://github.com/microsoft/vscode/issues/136408) @digitarald @lszomoru
- [ ] Explore cell-by-cell navigation for screen reader users [vscode#69795](https://github.com/microsoft/vscode/issues/69795) @tyriar
- [ ] Propose UI for debugging highly concurrent languages [vscode#116109](https://github.com/microsoft/vscode/issues/116109) @weinand
- [ ] Keyboard shortcut PDF accessibility [vscode-docs#4265](https://github.com/microsoft/vscode-docs/issues/4265) @gregvanl

**Comment by rustyx** [comment]
Any way we can finally look into [Copy left/right in the diff view (25887)](https://togithub.com/microsoft/vscode/issues/25887)?

**Comment by andig** [comment]
I'd like to highlight https://github.com/microsoft/vscode/issues/81589 which has 213 positive votes just one day after asking everyone to vote on the issue.

**Comment by sanket-bhalerao** [comment]
is there any way to get html tags lit up with bracket pair colorized kind of way?
