### ISSUE TITLE
UX Backlog

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#146840]
## Summary

This backlog is a collection of design issues related to the user experience of the product. Design will use this list as a discussion point for iteration planning as well as discussions with the team during our weekly ux sync. You can reference our [previous backlog](https://github.com/Microsoft/vscode/issues/66299).

## General

- [x] New file/editor creation [#145046](https://github.com/microsoft/vscode/issues/145046)
- [x] Standardize social/YouTube Thumbnails
- [ ] :runner: Website/Docs Re-Design
- [ ] Explore touch-only mode [#70764](https://github.com/microsoft/vscode/issues/70764)
- [x] Notification management [#144324](https://github.com/microsoft/vscode/issues/144324)
- [ ] JSON ⇒ UI Experiences (tasks, launch, extensions) [#84309](https://github.com/microsoft/vscode/issues/84309)
- [ ] Default run configurations (universal run)
- [ ] Integrating [vscode.dev](http://vscode.dev) with docs
- [ ] Improve settings navigation
- [ ] Improve peek/comment views in large screens [#150824](https://github.com/microsoft/vscode/issues/150824)

## Guidelines

- [x] Improved extension guidelines
  - [x] Increase visibility in docs t.o.c. [vscode-docs#5207](https://github.com/microsoft/vscode-docs/issues/5207)
  - [x] Update overview page and add missing pages (e.g. Walkthroughs, Panel, etc.) [vscode-docs#5389](https://github.com/microsoft/vscode-docs/pull/5389)
  - [x] Include link in `yo code` generator [vscode-generator-code#358](https://github.com/microsoft/vscode-generator-code/pull/358)
- [ ] Core design guidelines
  - [x] Design systems patterns [#140601](https://github.com/microsoft/vscode/issues/140601)
  - [ ] Illustration guidelines
  - [ ] UX Best practices
  - [ ] Component guidelines
- [ ] Create design tokens (colors, spacing, type)

## API

- [ ] Expose Table widget for extensions

## Editor

- [x] 3-way Merge [#37350](https://github.com/microsoft/vscode/issues/37350)
- [ ] Improve gutter support
  - [ ] Support codicons in gutter decorations [#143774](https://github.com/microsoft/vscode/issues/143774)
  - [ ] GlyphWidgets for overlapping decorators [#114776](https://github.com/microsoft/vscode/issues/114776)
  - [ ] Show error & warnings in the gutter [#3915](https://github.com/microsoft/vscode/issues/3915)
- [x] Improve commenting ranges [#115808](https://github.com/microsoft/vscode/issues/115808)

## Extensions

- [ ] :runner: Extension view re-design [#151599](https://github.com/microsoft/vscode/issues/151599)
- [ ] What’s New/Extension Updates [#102139](https://github.com/microsoft/vscode/issues/102139)
- [ ] Extension recommendation E2E experience [#139321](https://github.com/microsoft/vscode/issues/139321)
- [x] Extension Management [#68527](<https://github.com/microsoft/vscode/issues/68527>)
- [ ] GitHub/Extensions Sponsors integration [#107482](https://github.com/microsoft/vscode/issues/107482)
- [ ] Improve 1st party extension icons

## Getting Started

- [x] User Profiles [#116740](https://github.com/microsoft/vscode/issues/116740)
- [ ] User onboarding configuration
- [ ] Playground/UI Overview
- [ ] User Coach Marks/help bubbles [#120147](https://github.com/microsoft/vscode/issues/120147)
- [ ] Web Playgrounds (Icon Theme, Extensions, Settings)

## Source Control

- [x] Improve default git experience [#135992](https://github.com/microsoft/vscode/issues/135992)
- [ ] Improve diff/merge conflicts UX

## Themes

- [x] High Contrast theme types [#144193](https://github.com/microsoft/vscode/issues/144193)
- [ ] Theme token inspector
- [x] Default theme updates

## UI

- [x] :runner: Title bar modernization [#142867](https://github.com/microsoft/vscode/issues/142867>)
- [x] :runner: Command Center [#149445](https://github.com/microsoft/vscode/issues/149445) [#155458](https://github.com/microsoft/vscode/issues/155458)
- [ ] Omnisearch
- [ ] :runner: Layout density [#168671](https://github.com/microsoft/vscode/issues/168671)
- [ ] Explore Fluent UI Design
- [ ] Typography Tune up [#9152](https://github.com/microsoft/vscode/issues/9152)
- [ ] Presentation mode (mobile) [#70764](https://github.com/microsoft/vscode/issues/70764)
- [ ] GUI customization [#1833](https://github.com/microsoft/vscode/issues/1833)
- [ ] Allow app icon to be configured [#120604](https://github.com/microsoft/vscode/issues/120604)

**Comment by jo-oikawa** [comment]
Closing as all linked issues are either closed or tracked on Design team board
