### ISSUE TITLE
Debug protocol additions for November

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14845]
Planned for November:
- [x] Allow multiline eval results in debug console Microsoft/vscode-debugadapter-node/pull/83
- [x] Allow debug adapters to customize the behavior of the 'restart' button #14189
- [x] Add reverse continue for TimeTravel Debugging feature #13705
- [x] Support a variablesReference in OutputEvent Microsoft/vscode-debugadapter-node/issues/79
- [x] Support more flexible handling of exceptions Microsoft/vscode-debugadapter-node/issues/64
- [x] formatting hints Microsoft/vscode-debugadapter-node/issues/84

Planned for December:
- [ ] Allow passing back a `path` AND a `sourceReference` Microsoft/vscode-debugadapter-node/issues/60

Rejected:
- [x] Add ability to change the value of expressions Microsoft/vscode-debugadapter-node/issues/85

Backlog:
- [ ] Protocol support for "blackbox script"/"Just my code" #14728

/cc @gregg-miskelly @jacdavis @kieferrm @egamma @roblourens @richardstanton
