### ISSUE TITLE
Iteration Plan for May 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#149008]
This plan captures our work in **May**. This is a 5-week iteration. We have several holidays across countries coming up which gives us a bit less than 5 weeks of work time. We will ship in early **June**.

## Endgame
- **May 30, 2022**: Endgame begins
- **June 3, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22May+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22May+2022%22) @isidorn **team**

### UX
- [ ] :runner: Explore improving the discoverability of filtering in tree views [vscode#146806](https://github.com/microsoft/vscode/issues/146806) @misolori @joaomoreno
- [ ] :runner: Improve extension UX guidelines [vscode-docs#5327](https://github.com/microsoft/vscode-docs/issues/5327) @daviddossett
- [x] Explore improvements to custom menu styles [vscode#148587](https://github.com/microsoft/vscode/issues/148587) @daviddossett
- [x] Explore more visible section headers in quick pick lists [vscode#149057](https://github.com/microsoft/vscode/issues/149057) @daviddossett
- [ ] :muscle: Indicate focused tab when using multiple editor groups in HC themes [vscode#145563](https://github.com/microsoft/vscode/issues/145563) @daviddossett

### Workbench
- [ ] :runner: Explore profile management [vscode#116740](https://github.com/microsoft/vscode/issues/116740) @sana-ajani @sandy081 @daviddossett
- [ ] :runner: Explore `Continue On...` support in core [vscode#141293](https://github.com/microsoft/vscode/issues/141293#issuecomment-1117468466) @joyceerhl
- [ ] :runner: Explore a `Share as...` menu for creating `vscode.dev` links [vscode#146309](https://github.com/microsoft/vscode/issues/146309) @alexr00
- [ ] :runner: Problems view - support rendering as a table [vscode#98819](https://github.com/microsoft/vscode/issues/98819) @lszomoru
- [ ] :runner: :muscle: Adopt inline suggestions for previewing emmet expansions [vscode#139247](https://github.com/microsoft/vscode/issues/139247) @rzhao271 @hediet
- [x] Investigate use of `.gitignore` to filter content in the Explorer [vscode#38878](https://github.com/microsoft/vscode/issues/38878) @lramos15 @JacksonKearl
- [ ] :runner: Adopt Window Control Overlay API in electron 18 [vscode#147947](https://github.com/microsoft/vscode/pull/147947) @sbatten
- [ ] :runner: Explore Command Palette launcher in titlebar [vscode#149445](https://github.com/microsoft/vscode/issues/149445) @jrieken
- [ ] Investigate grouping of events in timeline view [vscode#145294](https://github.com/microsoft/vscode/issues/145294) @JacksonKearl @lramos15
- [x] Investigate global policy support [vscode#147756](https://github.com/microsoft/vscode/issues/147756) @joaomoreno
  - [x] Generate Windows Group Policy definition files from static analysis [vscode#148941](https://github.com/microsoft/vscode/issues/148941) @joaomoreno
  - [x] Create a `PolicyService` and use it in the `ConfigurationService` [vscode#148943](https://github.com/microsoft/vscode/issues/148943) @joaomoreno @sandy081
  - [x] Surface policy values in settings editor  [vscode#148944](https://github.com/microsoft/vscode/issues/148944) @rzhao271
- [ ] :runner: Settings Editor: Indicate if setting has a language-specific value [vscode#145731](https://github.com/microsoft/vscode/issues/145731)  @rzhao271 @sandy081
- [ ] :muscle: Explore reuseable inline edit widget for tree views [vscode#149641](https://github.com/microsoft/vscode/issues/149641) @lramos15

### Web
- [ ] :runner: Explore translations in the web [vscode#82595](https://github.com/microsoft/vscode/issues/82595) @tylerleonhardt
- [x] Support workspace trust in the web [vscode#145564](https://github.com/microsoft/vscode/issues/145564) @sbatten
- [ ] :runner: Explore how a web extension can leverage the [WebUSB API](https://wicg.github.io/webusb) [vscode#116761](https://github.com/microsoft/vscode/issues/116761) @mjbvz @alexdima
- [x] :runner: Explore a partial WASI implementation using the VS Code API [vscode#149092](https://github.com/microsoft/vscode/issues/149092) @dbaeumer

### Code Editor
- [ ] Context menu on the minimap to hide/show it [vscode#148131](https://github.com/microsoft/vscode/issues/148131) @alexdima
- [x] Explore the implementation of a merge editor [vscode#146091](https://github.com/microsoft/vscode/issues/146091) @hediet @jrieken
- [ ] :muscle: Explore moving tokenization to a web worker [vscode#147066](https://github.com/microsoft/vscode/issues/147066) @hediet
- [ ] :muscle: Align editor find widget with the notebook find widget [vscode#144851](https://github.com/microsoft/vscode/issues/144851) @rebornix
- [ ] Investigate providing a default snippet for a language [vscode#145929](https://github.com/microsoft/vscode/issues/145929) @jrieken @digitarald

### Notebook Editor
- [x] Tune autoselection of controllers [vscode#146339](https://github.com/microsoft/vscode/issues/146339) @rebornix
- [x] Provide support for proxy controllers [vscode#146942](https://github.com/microsoft/vscode/issues/146942) @rebornix @misolori
- [ ] :runner: Improve notebook “scrolling up” rendering performance [vscode#148164](https://github.com/microsoft/vscode/issues/148164) @roblourens
- [x] Improve cell positioning when using the Outline view [vscode#123828](https://github.com/microsoft/vscode/issues/123828) @roblourens
- [x] Improve cell positioning when using arrow keys across cell boundaries [vscode#147527](https://github.com/microsoft/vscode/issues/147527) @roblourens
- [x] Explore allowing extensions to manage cell context keys [vscode#146686](https://github.com/microsoft/vscode/issues/146686) @roblourens
- [ ] :runner: Explore improving files search results for notebooks [vscode#95275](https://github.com/microsoft/vscode/issues/95275) @roblourens
- [x] Improve notebook language detection CPU performance [vscode#148762](https://github.com/microsoft/vscode/issues/148762) @JacksonKearl
- [ ] :muscle: Allow resizing for the find widget in notebooks [vscode#141516](https://github.com/microsoft/vscode/issues/141516) @rebornix
- [ ] :muscle: Support copying simple output to the clipboard [vscode#129880](https://github.com/microsoft/vscode/issues/129880) @amunger @rebornix
- [ ] :muscle: Show changes in the overview ruler of the notebook diff editor [vscode#146224](https://github.com/microsoft/vscode/issues/146224) @amunger @rebornix

#### Jupyter Notebooks
- [ ] :red_circle: Explore improve first-run experience for running a Jupyter notebook @misolori
- [ ] :runner: Contributions to the vscode-jupyter extension [vscode-jupyter#9937](https://github.com/microsoft/vscode-jupyter/issues/9937) @greazer **team**

#### [AnyCode](https://marketplace.visualstudio.com/items?itemName=ms-vscode.anycode)
- [ ] :runner: Limit AnyCode providers when rich language extension is present [anycode#38](https://github.com/microsoft/vscode-anycode/pull/38) @jrieken
- [ ] :runner: Build index for a language only when there is strong evidence that an index is necessary [anycode#39](https://github.com/microsoft/vscode-anycode/pull/39) @jrieken

#### LSP
- None.

#### Python
- [ ] :runner: Contributions to the python extension [vscode-python#19088](https://github.com/microsoft/vscode-python/issues/19088) @brettcannon **team**

#### JavaScript/TypeScript
- [ ] :runner: Support TS server plugins on web [vscode#140455](https://github.com/microsoft/vscode/issues/140455) @mjbvz
- [ ] Support TS project-wide intellisense on web [typescript#47600](https://github.com/microsoft/TypeScript/issues/47600) @mjbvz
- [ ] :hand: Explore automatic type acqusition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz

#### Markdown
- [ ] :runner: Investigate create file and image links using DnD [vscode#142990](https://github.com/microsoft/vscode/issues/142990) @mjbvz
- [ ] :runner: Explore pasting images into markdown (file url, data url) [vscode#119961](https://github.com/microsoft/vscode/issues/119961) @mjbvz

#### CSS
- [x] Adopt LSP pull diagnostics in CSS [vscode#149643](https://github.com/microsoft/vscode/issues/149643) @aeschli

#### JSON
- [x] Support unevaluatedProperties for JSON schemas [vscode-json-languageservice#132](https://github.com/microsoft/vscode-json-languageservice/issues/132) @aeschli
- [x] Adopt LSP pull diagnostics in JSON [vscode#149643](https://github.com/microsoft/vscode/issues/149643) @aeschli
- [ ] :muscle: Explore test suite from JSON schema spec [vscode-json-languageservice#120](https://github.com/microsoft/vscode-json-languageservice/issues/102) @aeschli

### Debug
- [x] Support showing diagnostic information in the breakpoints view [vscode#142870](https://github.com/microsoft/vscode/issues/142870) @roblourens @weinand @connor4312
- [x] Explore avoiding the "Select environment" prompt when launching a debugger without `launch.json` [vscode#146338](https://github.com/microsoft/vscode/issues/146338) @roblourens @weinand
- [ ] :runner: Remove special treatment of extension debugging in VS Code (Prototype extension debugging in a clean environment) [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand

#### DAP
- None.

#### js-debug
- [ ] :runner: :muscle: Investigate: Smart Step Into [vscode#123879](https://github.com/microsoft/vscode/issues/123879) @connor4312 @weinand
- [x] Investigate supporting to attach to webviews running inside UWP applications  [vscode-js-debug#1209](https://github.com/microsoft/vscode-js-debug/issues/1209) @connor4312

### Testing
- [ ] :runner: :muscle: Provide support for Go to Test/Go to Test Subject [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312

### Terminal
- [x] Render find matches on the background layer [vscode#147013](https://github.com/microsoft/vscode/issues/147013) @tyriar @meganrogge
- [x] Optimize decorations performance in the terminal [vscode#145751](https://github.com/microsoft/vscode/issues/145751) @tyriar @meganrogge
- [x] Improve prompt response time when shell integration is enabled  [vscode#145576](https://github.com/microsoft/vscode/issues/145576) @meganrogge @tyriar
- [x] Improve shell integration user experience [vscode#148856](https://github.com/microsoft/vscode/pull/148856) @meganrogge

### Tasks
- [x] :runner: Change feature area ownership of tasks [vscode#149060](https://github.com/microsoft/vscode/issues/149060) @meganrogge @tyriar @alexr00

### Source Control
- [x] Git logging improvements [vscode#148656](https://github.com/microsoft/vscode/pull/148656) @lszomoru
- [x] Add support for random branch name generation [vscode#148781](https://github.com/microsoft/vscode/issues/148781) @lszomoru
- [x] Support to configure branches which should be protected from direct commits [vscode#148783](https://github.com/microsoft/vscode/issues/148783) @lszomoru
- [ ] A full editor can be used as git commit message editor [vscode#30562](https://github.com/microsoft/vscode/pull/30562) @lszomoru

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Continue finalization of remaining proposed notebook API [vscode#149861)](https://github.com/microsoft/vscode/issues/149861) @mjbvz @rebornix @roblourens

### Extensions
- [x] Support an activation event for timeline view [vscode#94151](https://github.com/microsoft/vscode/issues/94151) @lramos15 @jacksonkearl
- [x] Deprecated extensions support [vscode#4772](https://github.com/microsoft/vscode/issues/4772) @sandy081
- [x] Show Sponsor information for extension authors [vscode#107482](https://github.com/microsoft/vscode/issues/107482) @sandy081

### Extension Contributions
- [ ] :runner: GitHub Repositories: [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/12) @joyceerhl
- [ ] :runner: Improvements to the Remote extensions [vscode-remote-release#6699](https://github.com/microsoft/vscode-remote-release/issues/6699) @tanhakabir @chrmarti @aeschli
- [ ] :runner: GHPR: Improvements papercuts, selfhosting issues, [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22May+2022%22) @alexr00
- [ ] Make the eslint extension more approachable for new contributors [vscode-eslint#1447](https://github.com/microsoft/vscode-eslint/issues/1447) @dbaeumer
- [ ] :muscle: Investigate eslint notebook support in the web [vscode-eslint#1366](https://github.com/microsoft/vscode-eslint/issues/1366) @dbaeumer

### Install
- [ ] :runner: Integrate with the Windows 11 explorer context menu [vscode#127365](https://github.com/microsoft/vscode/issues/127365) @deepak1556

### Engineering
- [x] Explore new Electron process utility for spawning the extension host [vscode#131798](https://github.com/microsoft/vscode/issues/131798)  [vscode#135268](https://github.com/microsoft/vscode/issues/135268) @alexdima @deepak1556
- [ ] Review errors to identify which ones are actionable as error telemetry [vscode#145043](https://github.com/microsoft/vscode/issues/145043) @lramos15 **team**
- [ ] :runner: Provide a translation build for our extensions; onboard the Python extension and other extensions [vscode#150202](https://github.com/microsoft/vscode/issues/150202) @tylerleonhardt @paulacamargo25

#### Electron
- [ ] :runner: Improve dependency generation for Debian [vscode#13089](https://github.com/microsoft/vscode/issues/13089) @rzhao271
- [ ] :runner: Update `requestSingleInstanceLock` API to use `MessageWindow` for acknowledgement [electron/electron#34235](https://github.com/electron/electron/issues/34235) @rzhao271
- [x] Explore Electron 18 update [vscode#145527](https://github.com/microsoft/vscode/pull/145527) @deepak1556

### Documentation
- [ ] Draft Git Beginner's Docs [vscode-docs#5033](https://github.com/microsoft/vscode-docs/issues/5033) @digitarald @burkeholland
- [ ] :runner: Improve TS docs [vscode-docs#5205](https://github.com/microsoft/vscode-docs/issues/5205) @gregvanl @isidorn

----
### Deferred
- [ ] Implement a node.js-free, sandboxed, context isolated renderer [vscode#92164](https://github.com/microsoft/vscode/issues/92164)
- [ ] Enable `contextIsolation` for all windows [vscode#128099](https://github.com/microsoft/vscode/issues/128099) @bpasero @rzhao271 @deepak1556
- [ ] Fix cursor for draggable region elements on macOS [vscode#140724](https://github.com/microsoft/vscode/issues/140724) @rzhao271
- [ ] Refactor startup code to use electron's `requestSingleInstanceLock` API [vscode#97626](https://github.com/microsoft/vscode/issues/97626) @rzhao271
- [ ] Explore variable line heights in the editor [vscode#147067](https://github.com/microsoft/vscode/issues/147067) @hediet
- [ ] Improve presentation of inline suggestions with imprecise prefix matches [vscode#147068](https://github.com/microsoft/vscode/issues/147068) @hediet @misolori
- [ ] Explore a view header menu contribution point in the Explorer [vscode#108271](https://github.com/microsoft/vscode/issues/108271) @JacksonKearl
- [ ] Issue reporter template - include versions of built-in extensions that have been updated [vscode#145529](https://github.com/microsoft/vscode/issues/145529) @sandy081
- [ ] Consolidate notebook setting names [vscode#142986](https://github.com/microsoft/vscode/issues/142986) @rebornix @roblourens
- [ ] Improve cell level commenting in notebooks [vscode#144850](https://github.com/microsoft/vscode/issues/144850) @rebornix
- [ ] Review and update Integrated Terminal [vscode-docs#4809](https://github.com/microsoft/vscode-docs/issues/4809) @gregvanl @Tyriar

**Comment by fisforfaheem** [comment]
Updating to latest ELECTRON version will also fix so many performance issues found in electron

**Comment by lorand-horvath** [comment]
> Updating to latest ELECTRON version will also fix so many performance issues found in electron

Do you mean from 17.4.1 to 17.4.3 (I've opened issue https://github.com/microsoft/vscode/issues/149223) or the newer 18.x branch? https://github.com/electron/electron/releases/tag/v18.2.2

I should mention the slowness and lag reported in https://github.com/microsoft/vscode/issues/146737 which nobody seems to care about (ticket closed, merged with other issues, etc) - the problems have been obviously introduced with Electron 17...

**Comment by praveer-k** [comment]
Any plan to include a toggle button to show/hide code section. Make it look like a report instead of showing code?

**Comment by vhscom** [comment]
> Do you mean from 17.4.1 to 17.4.3 (I've opened issue https://github.com/microsoft/vscode/issues/149223) or the newer 18.x branch?

Anything you can do to improve performance at this point would trump any more features. I used to sing praises for VSCode telling people it didn't feel like Electron. Today, however, I would tell them it feels like an Electron app unless you're using bleeding edge hardware. I would expect reasonable performance without much heat on a 2019 MBP and I'm just not seeing it.

**Comment by vhscom** [comment]
@lorand-horvath you can comment instead of responding with emojis

**Comment by lorand-horvath** [comment]
@vhscom Sure... I'm just kind of tired of repeating the same performance issue reports without actually solving anything... You may check this one https://github.com/microsoft/vscode/issues/146737 and see that I got nowhere with it. So I'm not sure how to proceed in order to make the relevant developers bring back at least some of the performance we had in VSCode before upgrading to Electron 17.
IIRC in VSCode 1.65 we had Electron 13, which was fast and it was a pleasure to work with. Since VSCode 1.66 based on Electron 17 all kinds of problems appeared and it's slow as a snail...

**Comment by vhscom** [comment]
Have you looked at moving to Tauri?

**Comment by lorand-horvath** [comment]
@vhscom  Well, I'd be really interested to see a proper explanation as to why Electron 17 was chosen for VSCode since April and not staying on 13.5.2 (which was quite good IMHO) or 15 or 16 or even the latest stable 18 for that matter?
Electron 17 clearly has terrible performance issues.

I've just checked out Tauri - it looks very interesting!

**Comment by isidorn** [comment]
Thanks for providing feedback, but let's continue the discussion in https://github.com/microsoft/vscode/issues/146737
The iteration plan is not intended for scoped discussions, I would hate to have to lock this issue.

**Comment by fisforfaheem** [comment]
Yeah, let's goto  #146737
<https://github.com/microsoft/vscode/issues/146737> . I think the latest
version is much faster and has latest chrome improvements

**Comment by mkurz** [comment]
If it's possible, it would be nice if you could bump electron to version 19. Like mentioned in https://github.com/microsoft/vscode/pull/145527#issuecomment-1140317717 it contains a bug fix to make it work on Linux running on Apple Silicon. Thank you!

**Comment by lorand-horvath** [comment]
Looks like VSCode 1.68 (May 2022) will still use Electron 17, which is a real mess... many serious issues, bugs, including performance regressions; no wonder several other projects have moved on.
Hopefully we will get Electron 18 in VSCide 1.69 (June 2022).

**Comment by fisforfaheem** [comment]
maybe the insider version might get Electron 18 with latest chrome or at
least version 100... VS code is so far behind the latest stable release



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/06/22,
12:21:26 PM

**Comment by lorand-horvath** [comment]
@fisforfaheem VSCode is far behind with the Electron version because they're following an 8 weeks iteration plan, see @deepak1556 https://github.com/microsoft/vscode/pull/145527#issuecomment-1140742594

Holding on to that 8 week plan, no matter what, is pointless when it's obvious there are serious issues with the current Electron version. Anyway, there's nothing we can do, I guess. We'll just have to wait until the snail arrives to the finish line. Hopefully insiders will allow a sneak peek of what's to come... fingers crossed.

**Comment by fisforfaheem** [comment]
Agree, they should go for 4 week release

**Comment by lorand-horvath** [comment]
@mjbvz Since you unliked my comments, I have deleted them. I would have preferred a constructive comment.

**Comment by fisforfaheem** [comment]
[image: image.png]
