### ISSUE TITLE
Migrate to new notebook workspace edit api

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#149181]
We've working on cleaning up how extensions can apply edits to notebooks. As part of this, we will be removing the `notebookEditorEdit` API proposal and replacing it with a new `notebookWorkspaceEdit` api proposal. Main changes:

- Edits are now expressed using a `NotebookEdit` object
- We've removed the `NotebookEditor.edit` edit builder function entirely

The functionality of this new api should be the same as the old API. You can find the current api [here](https://github.com/microsoft/vscode/blob/18cf3d01ed22f7b35895a9b3c531048c835d4489/src/vscode-dts/vscode.proposed.notebookWorkspaceEdit.d.ts#L13)

Here's a list of current consumers:

- [x] Jupyter  @rchiodo https://github.com/microsoft/vscode-jupyter/pull/10117
- [x] Jupyter powertoys @rchiodo https://github.com/microsoft/vscode-jupyter-powertoys/issues/33
- [x] LiveShare  @alyssajotice @fubaduba https://github.com/MicrosoftDocs/live-share/issues/4682
- [x] Dot net interactive  @brettfo, @colombod https://github.com/dotnet/interactive/issues/2036

**Comment by mjbvz** [comment]
Merged in new proposal with #149128

**Comment by mjbvz** [comment]
Hey @rchiodo, can you please take a look at the [new API proposal ](https://github.com/microsoft/vscode/blob/18cf3d01ed22f7b35895a9b3c531048c835d4489/src/vscode-dts/vscode.proposed.notebookWorkspaceEdit.d.ts#L13) and me know if you have any feedback on it? We want to make sure it looks ok for Jupyter before asking other extensions migrate over too

**Comment by rchiodo** [comment]
Just glancing at it looks fine. We'd have to port to it I think before we could comment on what might or might not work.

**Comment by mjbvz** [comment]
All users have now been migrated over. Just need to remove the api itself now
