### ISSUE TITLE
Finalizing the notebook apis

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#149861]
Issue for tracking finalization (or deprecation) of the various notebook API proposals  

### Key
 ⬆️  —  Waiting for extensions (upstream)

## Tasks

- [ ] ⬆️  https://github.com/microsoft/vscode/issues/146831
- [x]  https://github.com/microsoft/vscode/issues/147248
- [x] https://github.com/microsoft/vscode/issues/149181
- [x] https://github.com/microsoft/vscode/issues/147264
- [x] #155245
- [x] https://github.com/microsoft/vscode/issues/146838
- [X] https://github.com/microsoft/vscode/issues/149271
- [X] https://github.com/microsoft/vscode/issues/147414
- [X] https://github.com/microsoft/vscode/issues/146781

**Comment by mjbvz** [comment]
At this point, we've finalized or removed the core notebook APIs. This work has included finalizing proposals for editing and notebook editors, as well as removing all the main proposals that saddled us with significant technical debt

The remaining api proposals are as follows:

- `notebookCellExecutionState` — This is an advanced API but it also needs more thought as the current proposal has known gaps. With the limited number of use cases we know of, we are not sure finalizing it is worth it. 

- `notebookControllerAffinityHidden` — New API. @IanMatthewHuff Can you please determine if this should be finalized?

- `notebookControllerKind` — https://github.com/microsoft/vscode/issues/168535 Small. Unclear if others beside Jupyter need this. Will follow up in linked issue

- `notebookDeprecated` — https://github.com/microsoft/vscode/issues/146831. Minor seeming but kind of annoying to get right. We are tracking this in the linked issue

- `notebookKernelSource` — New api. @rebornix can you please determine if this API should be finalized

- `notebookLiveShare` — This will likely be a proposal forever. LiveShare's use case is pretty unique and we don't think other extensions should use this API. It would be nice if we could move LiveShare off of this proposal but we don't know how to do this. The proposal is also not adding much debt to our code

- `notebookMessaging` — The proposal name is not accurate since most parts of notebook messaging have already been finalized. For the remaining parts, `NotebookRendererScript` may be replaced by #163511. It's not clear if notebook controller messaging is needed at all

- `notebookMime` — https://github.com/microsoft/vscode/issues/126280. Will follow up in linked issue

As I believe the original goal of this issue has largely been achieved, I'm going to close this issue. I will following up on the linked issues
