### ISSUE TITLE
Onboard more extensions to localization

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#150202]
This extension tracks our progress to onboard our extensions to vscode-nls & our [new localization pipeline](https://github.com/microsoft/vscode-engineering/wiki/Extensions-Localization):

* [ ] [ms-python.gather](https://marketplace.visualstudio.com/items?itemName=ms-python.gather) (uses custom solution) - https://github.com/microsoft/vscode-gather/issues/109
* [ ] [ms-toolsai.jupyter-renderers](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers) (not localized)
* [ ] [ms-vscode.anycode](https://marketplace.visualstudio.com/items?itemName=ms-vscode.anycode) (not localized) - https://github.com/microsoft/vscode-anycode/issues/77
* [ ] [ms-vscode.hexeditor](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor) (not localized) https://github.com/microsoft/vscode-hexeditor/issues/468
* [ ] [dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) (not localized) https://github.com/microsoft/vscode-eslint/issues/1753
* [x] [ms-vscode.vscode-selfhost-test-provider](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-selfhost-test-provider) (not localized) (low pri: dev extension)
* [x] [ms-vscode.vscode-markdown-notebook](https://marketplace.visualstudio.com/items?itemName=) (not localized) (low pri: dev extension)
* [x] [ms-vscode.mock-debug](https://marketplace.visualstudio.com/items?itemName=ms-vscode.mock-debug) (not localized) (low pri: dev extension)
* [x] [ms-vscode.azurecli](https://marketplace.visualstudio.com/items?itemName=ms-vscode.azurecli)
* [x] [ms-vscode.sublime-keybindings](https://marketplace.visualstudio.com/items?itemName=ms-vscode.sublime-keybindings)
* [x] [ms-vscode.live-server](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server)
* [x] [ms-vscode-remote.remote-containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers)
* [x] [ms-vscode-remote.remote-ssh](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh)
* [x] [ms-vscode-remote.remote-ssh-edit](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-ssh-edit)
* [x] [ms-vscode-remote.remote-wsl](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl)
* [x] [ms-toolsai.jupyter](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter)
* [x] [ms-python.python](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
* [x] [ms-python.black-formatter](https://marketplace.visualstudio.com/items?itemName=ms-python.black-formatter)
* [x] [ms-python.flake8](https://marketplace.visualstudio.com/items?itemName=ms-python.flake8)
* [x] [ms-python.pylint](https://marketplace.visualstudio.com/items?itemName=ms-python.pylint)
* [x] [ms-python.isort](https://marketplace.visualstudio.com/items?itemName=ms-python.isort)
* [x] [ms-python.autopep8](https://marketplace.visualstudio.com/items?itemName=ms-python.autopep8)
* [x] Azure Repos
* [x] GitHub Repositories
* [x] Remote Repositories
* [x] [GitHub.vscode-pull-request-github](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github)
* [x] [ms-vscode.vscode-github-issue-notebooks](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks)
* [x] [ms-vscode.atom-keybindings](https://marketplace.visualstudio.com/items?itemName=ms-vscode.atom-keybindings) (no strings to localize)
* [x] [ms-vscode.brackets-keybindings](https://marketplace.visualstudio.com/items?itemName=ms-vscode.brackets-keybindings) (no strings to localize)
* [x] [ms-vscode.notepadplusplus-keybindings](https://marketplace.visualstudio.com/items?itemName=ms-vscode.notepadplusplus-keybindings) (no strings to localize)
* [x] [ms-vscode.vs-keybindings](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings) (no strings to localize)
* [x] [ms-toolsai.jupyter-keymap](https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-keymap) (no strings to localize)
* [x] [ms-vscode.vscode-typescript-next](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) (no strings to localize)

**Comment by TylerLeonhardt** [comment]
Closing this since issues have been created in their respective repos... the exception is Notebook Renderers which can't be localized at the moment.
