### ISSUE TITLE
November/December Iteration Plan

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#15099]
This plan captures what we work on during November and early December. This iteration will be 6 weeks long. This is unusually long for us. We are an internationally distributed team and everybody in the team wants to enjoy the forthcoming holiday season while we still continue working as a closely knit team. Thus, it's 6 weeks this time. We will ship **mid December**.

Not unusual and still noteworthy: We will do several explorations that might or might not result in concrete deliverables in this or later releases.

## Endgame Schedule
- *December, 5th* Code freeze for the endgame
- *December, 9th* Endgame done

##### Monday - 5th December
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT

##### Tuesday - 6th December
- [x] Test build starts at 7am CET / 10pm PT on Monday
- [x] Test plan ready by 8am CET / 11pm PT on Monday
- [x] Testing

##### Wednesday - 7th December
- [x] Testing
- [x] Remind team members to assign issues that they intend to fix to the November milestone
- [x] Fixing (self-assigned, milestone assigned)
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification) Since there are quite some old bugs to verify we verify by age, youngest first. The queries are:
  - [x] [Verification needed](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+-label%3Averified+is%3Aclosed+label%3Averification-needed)
  - [x] [November Bugs](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Abug%20-label%3Averified%20is%3Aclosed%20-label%3Aduplicate%20-label%3Ainvalid%20closed%3A%3E%3D2016-11-01%20-label%3Aas-designed)
About 80 issues were verified on 12/7

##### Thursday - 8th December
- [x] Remind team members to start add Release Notes
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting, labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Add/update shrink-wrap files for built-in extensions if needed (see [instructions](https://github.com/Microsoft/vscode/issues/8570#issuecomment-229669456)) **@ramya-rao-a**
- [x] Update `OSSREADME.json` for built-in extensions based on differences to generated `npm-shrinkwrap.json` files if needed **@ramya-rao-a**
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **@ramya-rao-a**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **@ramya-rao-a**

##### Friday - 9th December
- [x] Pause scheduled `insider` builds **@zurich**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
- [x] Translation input - **@dbaeumer**
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - **@dbaeumer**
  - [x] OS X - **@weinand**
  - [x] Linux - **@sandy081**
- [x] All release notes updated. Release notes are collected in a file named *`Major_Minor.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero 
  - [x] @egamma
  - [x] @isidorn 
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm 
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps 
- [x] Acknowledge pull requests in release notes. We acknowledge PRs from outside the team. Use the [thankyou](https://github.com/Microsoft/vscode-tools/tree/master/thankyou) utility to generate the initial contents of the section. 
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero 
  - [x] @egamma
  - [x] @isidorn 
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm 
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps 
- [x] Mention notable fixes in the release notes **@all**
  - [x] @alexandrudima
  - [x] @weinand
  - [x] @chrmarti
  - [x] @tyriar
  - [x] @dbaeumer
  - [x] @bpasero 
  - [x] @egamma
  - [x] @isidorn 
  - [x] @joaomoreno
  - [x] @jrieken
  - [x] @kieferrm 
  - [x] @aeschli
  - [x] @rebornix
  - [x] @ramya-rao-a
  - [x] @roblourens
  - [x] @sandy081
  - [x] @mjbvz
  - [x] @mousetraps 
- When done fixing/verifying and there are changes since last build at the end of day PT
  - [x] Trigger new insider build and publish it manually **@ramya-rao-a**

##### Friday- 9th December
- [x] Branch code to `release/<x.y> **@zurich**
- [x] Announce master is open for business **@zurich**

##### Monday - 12th December
- [x] Publish `Insider` with hand-picked and reviewed candidate fixes **@ramya-rao-a**
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - @roblourens
  - [x] OS X - @mbjvz
  - [x] Linux - @rebornix
- [x] Polish release notes **@gregvanl**
- [x] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)

##### Tuesday - 13th December
- [x] Merge translations **@dbaeumer**
- [x] Build stable for all platforms **@ramya-rao-a**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@mousetraps**
    - [x] zip **@mousetraps**
  - [x] OS X - **@ramya-rao-a**
  - [x] Linux
    - [x] deb package 32-bit **@tyriar**
    - [x] deb package 64-bit **@tyriar**
    - [x] rpm package 64-bit **@rebornix**
    - [x] rpm package 32-bit **@rebornix**
    - [x] archives **@chrmarti**

##### Wednesday - 14th December
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@kieferrm**
- [x] Add a git tag to `HEAD` of `release/<x.y>` in format `x.y.z` **@ramya-rao-a**
- [x] Enable scheduled `insider` builds **@kieferrm**
- [x] Twitter announcement **@seanmcbreen**

## Plan Items

Our team uses a [GitHub Project](https://github.com/orgs/Microsoft/projects/2) to track its work. GitHub does not support public Projects right now. Below is a summary of the top level plan items.

Legend for annotations:

| Mark  | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

## Themes
- performance
- discoverability
- UI scalability
- API improvements
- accessibility testing

### Feedback

Issues to address community feedback:

- [x] Workbench - Finish 'Hot Exit' #101 @tyriar @bpasero
- [x] Workbench - Polish and evolve API and implementation of contributable explorers #14048 @jrieken @octref @__owner__
- [x] Workbench - Address UI scalability in the face of contributable explorers #15155 @stevencl @bgashler1 @bpasero
- [ ] Workbench - Improve discoverability of available functionality
   - [ ] Review command, panel, and widget names #15158 @seanmcbreen @chrmarti
   - [x] Add a 'Selection' menu #15156 @chrmarti
   - [x] Add entries to keymaps to Preferences menu #15159 @chrmarti
- [x] Editor - Improve accessibility of diff editor (do not only use color) #15371 @rebornix @alexandrudima
- [x] Editor - Sublime compatibility (see #3776)
   - [x] Prioritize missing Sublime keybindings @waderyan
   - [x] Implement top 3 of the missing keybindings @rebornix
- [x] Git - Add 'Clone from GitHub' to the command palette @joaomoreno
- [x] Debug - Improve UX for multi-target debugging #14450 @isidorn
- [x] Debug - Support more flexible handling of exceptions Microsoft/vscode-debugadapter-node#64 @weinand
- [x] Debug - Allow debug adapters to customize the behavior of the 'restart' button #14189 @weinand @isidorn
- [x] Debug - Add reverse continue for TimeTravel Debugging #13705 @weinand @isidorn
- [x] Debug - Support objects in debug console output #15796 @weinand @isidorn
- [x] Debug - Improve 'smart step' to support black-listing of modules/libraries #3215 @roblourens @weinand 
- [x] Debug - Allow to use external files to specify the environment of a launch config #14523 @weinand
- [x] Debug - Productize composite launch configs #14842 @weinand @isidorn
- [ ] Documentation - Describe our UX process for the team and the community @chrisdias
- [x] :muscle: Workbench - Use custom title on macOS #15098 @bpasero

### API Improvements for Extensions

- [x] API - Configuration service provides access to configuration scopes #10583 @jrieken
- [x] API - Add support for dynamic changes of capabilities to the language server protocol [LSP#125](https://github.com/Microsoft/language-server-protocol/issues/125) @dbaeumer
- [x] API - Allow language servers to provide command implementations [LSP#126](https://github.com/Microsoft/language-server-protocol/issues/126) @dbaeumer
- [ ] :muscle: API - Explore exposing the language server protocol as JSON schema rather than a `d.ts` file [LSP#25](https://github.com/Microsoft/language-server-protocol/issues/25) @dbaeumer
- [x] API - Allow code completion providers to return dynamically computed snippets using a subset of the TextMate snippet syntax #3210 @jrieken
- [x] API - Support variables in snippets #4956 @jrieken
- [x] API - Explore the use of status codes in rejected promises to communicate information back to the client #15454 @jrieken
   - [x] Code completion providers
   - [x] Find all references
   - [x] Go to definition
- [x] API - Use non-nullable types in `vscode.d.ts` #6907 @jrieken 
- [ ] :muscle: API - Use `readonly` modifier in `vscode.d.ts` #12732 @jrieken 
- [x] :muscle: Debug - Support snippets in 'launch.json' #13886 #15974 @isidorn @weinand

### Language support
- [x] JavaScript
   - [x] Clarify need of `jsconfig.json` for projects without commonjs modules [TS#11554](https://github.com/Microsoft/TypeScript/issues/11554) @dbaeumer
   - [x] Remove `jsconfig.json` light bulb #15205 @mjbvz
   - [x] Improve large project warning - dependency on TS server sending a notification #15208 @mjbvz
   - [ ] :muscle: UX improvements for automated typings acquistion (adopt new status code API) #15209 @mjbvz @dbaeumer
   - [x] Explore the need for pre-seeding typings files #15536 @dbaeumer
- [x] TypeScript
   - [x] Explore with the TS team on Compile on Save support [TS#11526](https://github.com/Microsoft/TypeScript/issues/11526) @dbaeumer
   - [x] Explore exposing code actions provided by the TS Server #15535 @dbaeumer & @mjbvz

### Debt Items

Issues to reduce our engineering debt:

- [x] Let `vscode-textmate` compute simplified tokens. This will improve rendering performance as well as fix issues we see with several textmate themes. #15379 @alexandrudima
- [x] Review themes in response to `vscode-textmate` changes #15376 @aeschli
- [ ] :muscle: Change emmet ownership @ramya-rao-a
   - [ ] Use #11679 as warm-up @ramya-rao-a
- [ ] :muscle: Improve Integrated Terminal on Windows by moving up to a newer version of winpty (part of ##13625) @tyriar
- [ ] :muscle: Use @types in our code rather than the old style typings files #14043 @dbaeumer
- [x] Port language server implementation to TS 2.0 #15201 @mjbvz
- [x] Debug - VS Code starts to use that information to fix the hover experience by only showing a hover when inside the scope boundaries. #15172 @isidorn

### Extension Contributions

Support/contribute to extensions:

- [x] All - Ensure all extensions we contribute to are using the extension change log @kieferrm
- [ ] :running: PHP - Continue exploration of improved PHP parser with symbol and location information #15818  @mousetraps
   - [ ] Discuss parser exploration with community
- [x] Go - Explore Go language server seeded by SourceGraph @ramya-rao-a
- [x] Azure - Explore Azure extension pack for the market place @chrisdias

### Engineering

This section lists several engineering/development items that the team identified:

- [x] Improve support for Javascript in HTMl #15377 @aeschli
   - [x] Ensure html language server is self-contained
   - [x] Explore possibility of providing an html language server library for easy adaptation to other scenarios
- [x] Improve workbench start-up performance #15455 @bpasero @jrieken
   - [x] Collect more detailed startup performance data and send it using the existing start-up time event
   - [x] Investigate need for log service
- [x] Workbench - Investigate return to open on mouse-down #15819 @bpasero
- [ ] Quick Open - Invesigate the costs of persisting our file cache #15382 @chrmarti
- [x] File Search - Improve performance of file search #15384 @chrmarti @roblourens
   - [ ] Ensure we understand usage patters of file search
- [x] Understand extension host reliability #15456 @jrieken
- [x] Adopt extension marketplace's CDN changes #15557 @joaomoreno
- [ ] :muscle: Investigate automating our smoke test @aeschli

### Feedback Channels

- [ ] Crash data (see also https://github.com/electron/electron/issues/7474) @ramya-rao-a
   - [x] #15375 Investigate possible sceanrios that can get crashes reported without metadata
   - [ ] #15754 Add crash details to the crash web site
- [x] Improve error telemetry @ramya-rao-a
   - [x] #12694 Fix broken stack traces in macOS and Linux
   - [x] #15483 Update error telemetry website to add links to source code from deminified call stack
   - [x] #13864 Error telemetry: sort by machines by default
   - [x] #15603 Update error telemetry site to add callstacks as comments to existing issues
   - [x] #15374 Fix errors coming from processes spawned by extensions that may have PII
   - [x] #15752 Always start to de-minify stack traces
- [ ] Data pipeline maintenance @ramya-rao-a
   - [ ] 🏃 Rename KPIs, add Weekly Avg KPI and backfill
   - [ ] Improve support for retention and churn data

### Explorations

We are continuously exploring options and ideas. Some might make it into future releases.

- [ ] :running: API - Explore potential support for SCM providers #15246 @joaomoreno
- [ ] Workbench - Explore improvements to settings #15162 @sandy081
   - [x] Improve adjustment of common settings
   - [x] Make it easier to find the settings that need adjustment and to adjust them
- [ ] Workbench - Improve experience for first time users #15383 @chrmarti @sandy081
   - [x] What adjustments are typically made on first run
   - [x] Familiarizing a first time user with VS Code
   - [x] How do we know we improved?
- [ ] :running: Tasks - Explore future direction of task support #15179 @dbaeumer
- [x] Debug - Explore how extension should participate in launching the debug adapers #8645 @weinand
- [x] Debug - Explore how extensions can contribute and implement custom actions #15656 #15657 @isidorn @weinand
- [ ] :running: Explore what it takes to ship VS Code as a UWP application #15820 @bpasero 
- [ ] :muscle: Explore code commenting support in diff editor for allowing a 'Review Github PR' extension #15380 @alexandrudima

**Comment by rozzzly** [comment]
## I think everybody can agree
![obligatory election-day-eve-day gif](https://i.giphy.com/l3vR6qrnp8LgMKjqo.gif)
### This is a pretty exciting agenda.

Can wait to see how it unfolds!

@rebornix @alexandrudima If you're revisiting the diff viewer, could you look into a cool merge-mode feature like JetBrains has? Here's a [video](https://www.youtube.com/watch?v=RDV2LJzd1wU) 

 The one thing I am sad to see missing is custom inline widgety-things ala #3220. I understand your initial investigation into the concept wasn't promising, **but don't give up!!**

OP mentions: 
> Describe our UX process for the team and the community

and a few other vague references to "contributable explorers.. but might it be wiser to address UI extensibility as a whole rather than a case by case basis? ___This extensibility is the one thing that I believe `vscode` is lacking.___ If this is November / December track... can January be overhaul of UI extensibility?? Custom sidebars, popovers, custom workspace css, etc. It's no small order, but that would bump up extensibility up a few orders of magnitude. 

# Anyway, that's my 2¢.

**Comment by eamodio** [comment]
Sounds great!

Since the diff viewer is going to be looked at -- a feature I would love to have (and others on my team have echoed) would be small buttons (or something) to be able to quickly move change blocks from on side to the other. Of course these would only be available if one side of the diff was editable.

This is how Beyond Compare does it.
![image](https://cloud.githubusercontent.com/assets/641685/20067498/62bb76f0-a4e3-11e6-91bc-07bd049d550a.png)

**Comment by zhcm** [comment]
it would be great to get it over the Windows Store!Especially in China!

**Comment by darcome** [comment]
I agree with PHP support! A very promising extension is https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

You could help me with his work!

**Comment by egamma** [comment]
Closing - November has been shipped
