### ISSUE TITLE
Switch to the finalized notebookEditor API  

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#151661]
The `notebookEditor` has been finalized with VS Code 1.68 🎉   (#149271). If your extension was using the proposal, you should now switch to the finalized version of this API.

In the majority of cases, this switch is as simple as:
1. Switch your extension to target VS Code `1.68`
2. pulling in the new `vscode.d.ts`
3. Remove `notebookEditor` from your list of enabled  API proposal.

However there are few small bumps to be aware of:

- `NotebookEditor.document` has been renamed `NotebookEditor.notebook`. Please make sure to switch over to the new property name as part of this migration

- We did not finalize the version of `showNotebookDocument` that takes a uri. Instead you can use `openNotebookDocument(uri).then(document => showNotebookDocument(document, options))`

---

Here's a list of all current consumers of the old API proposal:

- [x] ms-vsliveshare.vsliveshare — @alyssajotice @fubaduba
- [X] ms-toolsai.vscode-ai-remote  — @sevillal  https://github.com/microsoft/vscode-azureml/issues/245
- [x] Dot net interactive —  @brettfo, @colombod https://github.com/dotnet/interactive/issues/2149
- [x] GitHub.codespaces — @jkeech @KartikM123 @osortega
- [x] ms-python.vscode-pylance — https://github.com/microsoft/pylance-release/issues/3054

If you own one of these extensions, please migrate to the finalized notebook editor API. Let me know once the new version of your extension is published and I will remove your extension from the list of api consumers

**Comment by dbaeumer** [comment]
I am actually fine in ESLint. The dependency was because of notebook support in LSP and LSP already converted to the final version for the 8.x release of the LSP libs.

**Comment by mjbvz** [comment]
Thank you everyone who's checked off their extension so far! If you have, I plan to remove your extension from the list of `notebookEditor`API consumers in July. This will only start effecting the insiders builds of VS Code at first, but please let me know if you notice any issues

**Comment by jkeech** [comment]
I'm working on the change for Codespaces and expect it to be in our next extension release (1.10.0) in a few days. I'll reply back once it's on the marketplace.

**Comment by jkeech** [comment]
We just published GitHub Codespaces 1.10.0 with this change, so you should be able to remove our extension from the list of `notebookEditor` proposed API consumers.
