### ISSUE TITLE
Iteration Plan for July 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#154652]
This plan captures our work in **July**. This is a 4-week iteration. We will ship in early **August**.

## Endgame
- **July 25, 2022**: Endgame begins
- **July 29, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22July+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22July+2022%22) @isidorn **team**

### UX
- [x] Improve the discoverability of filtering in tree views [vscode#146806](https://github.com/microsoft/vscode/issues/146806) @misolori @joaomoreno
- [ ] :runner: Explore improvements to Extensions view [#151599](https://github.com/microsoft/vscode/issues/151599) @misolori
- [x] Improve editor group focus states in high contrast themes [vscode#145563](https://github.com/microsoft/vscode/issues/145563) @daviddossett
- [ ] :runner: Explore improvements to Command Center interactions [vscode#155458](https://github.com/microsoft/vscode/issues/155458) @daviddossett

### Workbench
- [Profiles](https://github.com/microsoft/vscode/issues/116740)
   - [x] Improve UX for managing application and profile settings in the Settings Editor [vscode#152888](https://github.com/microsoft/vscode/issues/152888) @rzhao271 @sandy081
   - [x] Support Settings Profiles in Web [vscode#154242](https://github.com/microsoft/vscode/issues/154242) @sandy081
   - [ ] :runner: Support Syncing Settings Profiles [vscode#154243](https://github.com/microsoft/vscode/issues/154243) @tyriar @sandy081
   - [ ] :muscle: CLI: Launch VSCode with a specific profile [vscode#151301](https://github.com/microsoft/vscode/issues/151301) @sandy081
- [ ] :runner: :muscle: Support hiding/showing toolbar items using right-click [vscode#150916](https://github.com/microsoft/vscode/issues/150916) @jrieken
- [x] Support hiding/showing title bar elements using right-click [vscode#155345](https://github.com/microsoft/vscode/issues/155345) @sbatten
- [x] Improve menu bar experience when command center is visible [vscode#152906](https://github.com/microsoft/vscode/issues/152906) @sbatten
- [ ] :runner: Explore `Continue On...` support in core [vscode#141293](https://github.com/microsoft/vscode/issues/141293#issuecomment-1117468466) @joyceerhl
- [ ] :hand: Adopt Window Control Overlay API in electron 18 [vscode#147947](https://github.com/microsoft/vscode/pull/147947) @sbatten
- [ ] :runner: Investigate providing a default snippet for a language [vscode#145929](https://github.com/microsoft/vscode/issues/145929) @jrieken @digitarald
- [x] Support multiselect in the search result tree [vscode#47166](https://github.com/microsoft/vscode/issues/47166) @andreamah
- [x] Explore showing file decorations in the search result tree [vscode#115741](https://github.com/microsoft/vscode/issues/115741) @andreamah
- Merge Editor Improvements
   - [x] Allow the merge editor to veto on close without being dirty [vscode#152841](https://github.com/microsoft/vscode/issues/152841) @bpasero
   - [x] Support using vscode as git mergetool [vscode#5770](https://github.com/microsoft/vscode/issues/5770) @bpasero @hediet
   - [ ] :muscle: Support contributing a diff provider [vscode#84981](https://github.com/microsoft/vscode/issues/84981) @hediet
   - [x] Have a good way to redirect open request into the merge editor [vscode#153110](https://github.com/microsoft/vscode/issues/153110) @jrieken @bpasero

### Web
- [ ] :runner: Continue translations in the web [vscode#82595](https://github.com/microsoft/vscode/issues/82595) @Tylerleonhardt
- [ ] :muscle: Reload extension host on server side when connected from web and locale is changed [vscode#151000](https://github.com/microsoft/vscode/issues/151000) @TylerLeonhardt
- [x] Explore setting COOP and COEP headers on vscode.dev [vscode#137884](https://github.com/microsoft/vscode/issues/137884) @jrieken @joaomoreno
- [ ] :muscle: Improve VS Code WASI implementation [vscode#154797](https://github.com/microsoft/vscode/issues/154797) @dbaeumer
- [ ] :runner: Provide a web-shell with pluggable parser and multi-line editing capabilities [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @tyriar

### Code Editor
- [ ] :runner: Introduce the custom widget for code actions [vscode#152913](https://github.com/microsoft/vscode/issues/152913) @justschen
- [ ] :runner: Support sticky scroll [vscode#26757](https://github.com/microsoft/vscode/issues/26757) @aiday-mar @jrieken
- [x] Select symbol closest to the cursor in quick outline [vscode#154246](https://github.com/microsoft/vscode/issues/154246) @jrieken
- [x] Support folding a selection and keeping folded ranges stable [vscode#139779](https://github.com/microsoft/vscode/pull/139779) [vscode#155302](https://github.com/microsoft/vscode/pull/155302) @aeschli
- [ ] :muscle: Explore accepting parts of an inline completion proposal [vscode#155473](https://github.com/microsoft/vscode/issues/155473) @hediet
- [ ] :runner: Publish a new version of the Monaco editor [monaco-editor](https://github.com/microsoft/monaco-editor/) @hediet
- [ ] :runner: Support snippets in workspace edits [vscode#145374](https://github.com/microsoft/vscode/issues/145374) @jrieken
- [x] Code action for surround-with snippets [vscode#150678](https://github.com/microsoft/vscode/issues/150678) @jrieken
- [ ] :runner: Support opening a merge editor through an extension [vscode#153213](https://github.com/microsoft/vscode/issues/153213) @lramos15

### Comments
- [ ] :runner: :muscle: Comments view should have ability to filter by resolved/unresolved [vscode#150958](https://github.com/microsoft/vscode/issues/150958) @alexr00

### Notebook Editor
- [x] Investigate support for hot exit in interactive window [vscode#151444](https://github.com/microsoft/vscode/issues/151444) @rebornix @lramos15
- [x] Improve UI stability for programmatic, short-lived executions [vscode#150924](https://github.com/microsoft/vscode/issues/150924) @roblourens
- [ ] :muscle: Explore improving files search results for notebooks [vscode#95275](https://github.com/microsoft/vscode/issues/148068) @roblourens
- [x] Allow resizing for the find widget in notebooks [vscode#141516](https://github.com/microsoft/vscode/issues/141516) @andreamah
- [x] Support "Go to Last Failed Cell" [vscode#142898](https://github.com/microsoft/vscode/issues/142898) @andreamah

#### Jupyter Notebooks
- [x] Explore improve first-run experience for running a Jupyter notebook; [board](https://github.com/orgs/microsoft/projects/359/views/1); @brettcannon @lramos15 @IanMatthewHuff @karrtikr @minsa110
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#10749](https://github.com/microsoft/vscode-jupyter/issues/10749) @greazer **team**

#### Python
- [x] Contributions to the python extension [vscode-python#19438](https://github.com/microsoft/vscode-python/issues/19438) @brettcannon **team**

#### JavaScript/TypeScript
- [ ] :hand: Support TS project-wide intellisense on web [typescript#47600](https://github.com/microsoft/TypeScript/issues/47600) @mjbvz
- [ ] :hand: Explore automatic type acqusition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz
- [ ] :runner: :muscle: Tooling for generating/hierachies of `tsconfig.json` files [vscode-languageserver-node#1026](https://github.com/microsoft/vscode-languageserver-node/issues/1026) @dbaeumer

#### Markdown
- [x] Finalize `DropIntoEditor` API for creating file and image links [vscode#142990](https://github.com/microsoft/vscode/issues/142990) @mjbvz
- [ ] :runner: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz

#### JSON
- [x] Option for JSON formatter to keep new-lines [vscode#23260](https://github.com/microsoft/vscode/issues/23260) @aiday-mar @aeschli
- [ ] :runner: Sort JSON properties alphabetically [vscode#155312](https://github.com/microsoft/vscode/issues/155312) @aiday-mar @aeschli
- [x] Explore test suite from JSON schema spec [vscode-json-languageservice#120](https://github.com/microsoft/vscode-json-languageservice/issues/102) @aeschli

### Debug
- [x] Support to pass unescaped arguments in `launch.json` [vscode#149910](https://github.com/microsoft/vscode/issues/149910) @roblourens @weinand
- [x] Command to show debug sessions picker [vscode#153347](https://github.com/microsoft/vscode/issues/153347) @andreamah
- [ ] :muscle: Remove special treatment of extension debugging in VS Code (Prototype extension debugging in a clean environment) [vscode#126737](https://github.com/microsoft/vscode/issues/126737) @weinand

#### DAP
- [x] Spec clarifications [issues](https://github.com/microsoft/debug-adapter-protocol/issues?q=is%3Aissue+is%3Aopen+label%3Aclarification+author%3Arillig+milestone%3A%22July+2022%22) @weinand @connor4312
- [x] Control escaping of arguments in `runInTerminal` [debug-adapter-protocol#146](https://github.com/microsoft/debug-adapter-protocol/issues/146) @roblourens @weinand

#### js-debug
- [x] Improve breakpoint predictor caching for large projects [vscode-js-debug#1149](https://github.com/microsoft/vscode-js-debug/issues/1149) @connor4312
- [ ] :muscle: Automatically create debug config with a "dry run" [vscode-js-debug#1214](https://github.com/microsoft/vscode-js-debug/issues/1214) @connor4312

### Terminal
- [x] Support equivalent to reverse-i-search using shell integration [vscode#154016](https://github.com/microsoft/vscode/issues/154016) @tyriar @meganrogge
- [x] Simplify manual installation of shell integration [vscode#153921](https://github.com/microsoft/vscode/issues/153921) @tyriar @meganrogge
- [x] Support missing keybindings in PowerShell [vscode#45705](https://github.com/microsoft/vscode/issues/45705) @tyriar @meganrogge
- [ ] :muscle: Support auto-complete of Powershell commands [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar

### Tasks
- [x] Add command for filtering task quick open entries [vscode#153145](https://github.com/microsoft/vscode/issues/153145) @meganrogge
- [x] Use an object for `runTask` args [vscode#154201](https://github.com/microsoft/vscode/issues/154201) @meganrogge
- [ ] :runner: :muscle: Reconnect tasks on window reload [vscode#117408](https://github.com/microsoft/vscode/issues/117408) @meganrogge

### Source Control
- [ ] :runner: Polish SCM commit button [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22July+2022%22+assignee%3Alszomoru+label%3Apolish) @lszomoru
- [x] Polish and fix git rebase --continue experience [vscode#114461](https://github.com/microsoft/vscode/issues/114461) @lszomoru
- [ ] :runner: :muscle: Investigate: Support input box spell checking [vscode#35571](https://github.com/microsoft/vscode/issues/35571) @lszomoru

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Continue finalization of remaining proposed notebook API [vscode#149861](https://github.com/microsoft/vscode/issues/149861) @mjbvz @rebornix @roblourens

### Extensions
- [x] Web: Language extensions should not be installable [vscode#154461](https://github.com/microsoft/vscode/issues/154461) @sandy081

### Custom Views
- [x] Customize custom view height [vscode#122283](https://github.com/microsoft/vscode/issues/122283) @alexr00

### Extension Contributions
- [x] GitHub Repositories: [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/16) @joyceerhl
- [x] Improvements to the Remote extensions [vscode-remote-release#6919](https://github.com/microsoft/vscode-remote-release/issues/6919) @tanhakabir @chrmarti @aeschli
- [x] GHPR: Improvements papercuts, selfhosting issues, [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22July+2022%22) @alexr00
- [x] Close the loop between committing and creating a PR [vscode#151589](https://github.com/microsoft/vscode/issues/151589) @alexr00 @lszomoru
- [x] GHPR: Owner dropdown should list me first [vscode-pull-request-github#3627](https://github.com/microsoft/vscode-pull-request-github/issues/3627) @benibenj
- [x] GHPR: Allow me to create a new Milestone from the Milestone picker [vscode-pull-request-github#3630](https://github.com/microsoft/vscode-pull-request-github/issues/3630) @benibenj
- [ ] :runner: GHPR: Show changes since last review [vscode-pull-request-github#363](https://github.com/microsoft/vscode-pull-request-github/issues/363) @benibenj
- [x] Contributions to the Azure Machine Learning extensions [vscode-azureml#239](https://github.com/microsoft/vscode-azureml/issues/239) @tbombach **team**

### Install / Update
- [x] Windows: Unable to update [vscode#147408](https://github.com/microsoft/vscode/issues/147408) @joaomoreno
- [x] Windows: Prevent update service from activating if running as Admin in User install [vscode#148428](https://github.com/microsoft/vscode/issues/148428) @joaomoreno
- [ ] :runner: Integrate with the Windows 11 explorer context menu [vscode#127365](https://github.com/microsoft/vscode/issues/127365) @deepak1556

### Engineering
- [x] Review errors to identify which ones are actionable as error telemetry [vscode#145043](https://github.com/microsoft/vscode/issues/145043) @lramos15 **team**
- [ ] :runner: Explore using `swc` for transpilation [vscode#150025](https://github.com/microsoft/vscode/issues/150025) @jrieken
- [x] Allow to enable `sandbox` behind a setting and validate it works [vscode#154006](https://github.com/microsoft/vscode/issues/154006) @bpasero @deepak1556
- [ ] :muscle: Fix auto-generation of `ILocalizedString` for strings from extension package.json [vscode#153538](https://github.com/microsoft/vscode/issues/153538#issuecomment-1172769878) @TylerLeonhardt @alexdima

#### Electron
- [x] Improve dependency generation for Debian [vscode#13089](https://github.com/microsoft/vscode/issues/13089) @rzhao271
- [ ] :runner: Windows layout styling issue on launch [vscode#146683](https://github.com/microsoft/vscode/issues/146683) @rzhao271 @deepak1556
- [x] The pseudoterminal extension API latency seems much higher than it was before [vscode#153182](https://github.com/microsoft/vscode/issues/153182) @deepak1556
- [ ] :runner: WCO on Windows don't respond to touch events [electron#34364](https://github.com/electron/electron/issues/34364) @deepak1556
- [x] Cannot persist / load GitHub Authentication SignIn Token to macOS Ventura Beta 2 Keychain [vscode#152964](https://github.com/microsoft/vscode/issues/152964) @deepak1556
- [ ] :runner: Contribute the utility process and APIs to Electron [vscode#154007](https://github.com/microsoft/vscode/issues/154007) @deepak1556

### Documentation
- [ ] :runner: Review and update Integrated Terminal section [vscode-docs#4809](https://github.com/microsoft/vscode-docs/issues/4809) @gregvanl @Tyriar

----
### Deferred
- [ ] Support HTML headers in the notebook outline [vscode#134853](https://github.com/microsoft/vscode/issues/134853) @roblourens
- [ ] Allow to open the merge editor in files with conflict markers [vscode#153800](https://github.com/microsoft/vscode/issues/155472) @hediet @jrieken
- [ ] :red_circle: Adopt transpilation in dev-flow for watch tasks @jrieken
- [ ] WCO on Windows occludes dev tools [electron#34129](https://github.com/electron/electron/issues/34129) @deepak1556
