### ISSUE TITLE
Track usage of internal snippet syntax

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15573]
With #3210 we are adding API to inserts snippets via completions. These snippets use the same syntax external, static snippets use which again is a subset of the TextMate snippet syntax. Eventually, we will not support the internal snippet syntax anymore.

This issue lists extensions that are known to be using the internal syntax and tracks their adoption of the new API. 

* [x] vscode.typescript - 0abf2747489e3afd263479a55c53b323742dc8ed
* [x] lukehoban.Go -> @ramya-rao-a 
* [x] vscode.javascript
* [x] rlovelett.vscode-swift-language -> https://github.com/RLovelett/vscode-swift/issues/24
* [x] vscode.css -> @aeschli 
* [x] ~~HookyQR.JSDocTagComplete -> https://github.com/HookyQR/VSCodeJSDocTagComplete/issues/2~~
* [x] vscode.json -> @aeschli 
* [x] flowtype.flow-for-vscode -> https://github.com/flowtype/flow-for-vscode/issues/51
* [x] ~~zeppelin.asp -> GONE, deleted?~~
* [x] redhat.java -> https://github.com/redhat-developer/vscode-java/issues/99
* [x] DanTup.dart-code -> https://github.com/Dart-Code/Dart-Code/issues/216
* [x] vscode.html -> @aeschli 
* [x] twxs.cmake -> https://github.com/twxs/vs.language.cmake/issues/21
* [x] AureliaEffect.aurelia -> https://github.com/aurelia/vscode-extension/issues/25
* [ ] msazurermtools.azurerm-vscode-tools -> not on GH
* [ ] mrmlnc.vscode-vash -> https://github.com/mrmlnc/vscode-vash/issues/6

**Comment by jrieken** [comment]
Some extensions depend on the LSP to have support for this as well - #15577

**Comment by aeschli** [comment]
@jrieken Is there a spec for the new syntax?

**Comment by jrieken** [comment]
Yeah - this should be a more or less precise descriptions: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md#L27

**Comment by aeschli** [comment]
@jrieken Can you spec the escaping rule in case a text contains $1 or ${... ?

**Comment by aeschli** [comment]
I created #16056 for issues around escaping.

**Comment by DanTup** [comment]
FYI - Dart Code now uses the new API :-)

Our use of the old API seemed to break in 1.8 - underscores were being inserted during completion. Updating seemed like a faster option than waiting for a fix, but it does mean people upgrading to 1.8 need to then upgrade Dart Code (they can't do it before, since the new version had to have `engine: 1.8`) for things to work properly.

**Comment by ramya-rao-a** [comment]
This is done for the Go extension as well.

https://github.com/Microsoft/vscode-go/pull/709

**Comment by jrieken** [comment]
Removal is happening in May
