### ISSUE TITLE
Support moving the tasks framework to use the integrated terminal

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15584]
It makes sense to reuse the work of the integrated terminal in the tasks framework to leverage things like:

- Handling of ANSI control characters (colors, cursor movement)
- Multiple tasks
- Allowing input

Here are the blockers to allow this to happen:

- [x] #15583 Expose a terminal API option to pause when the shell is exited
- [x] #18376 Terminal should throw an event when a terminal has completed (and is waiting to close)
- [x] #18377 Allow terminals to be reused

No longer needed:

- #13267 ~~Allow extensions to access all terminals via API~~ (deferred as it's not a mandatory requirement and poses security/performance obstacles)
- #13337 ~~Allowing richer integration with integrated terminal (co-processes)~~ (internal API exposed for now https://github.com/Microsoft/vscode/commit/7900f252ec15ffd18d1b873c35b37d7bfc9cdcfd)~~

After this is done tasks could also be moved to an extension.

**Comment by Tyriar** [comment]
For the problem watcher I'm thinking that something similar to an [iterm2 trigger](https://www.iterm2.com/documentation/2.1/documentation-triggers.html) with a callback and then some way of grabbing stdout would be sufficient.
