### ISSUE TITLE
Iteration Plan for September 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#160046]
This plan captures our work in **September**. This is a 5-week iteration. We will ship in early **October**.

## Endgame
- **September 26, 2022**: Endgame begins
- **September 30, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22September+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22September+2022%22) @isidorn **team**
- [ ] :runner: Workbench: Improve accessibility of Setting indicators [vscode#159088](https://github.com/microsoft/vscode/issues/159088) @rzhao271

### Workbench
- [ ] [Setting Profiles](https://github.com/microsoft/vscode/issues/116740)
   - [ ] :runner: Improvements to the settings profile experience [vscode#155067](https://github.com/microsoft/vscode/issues/155067) @sandy081 @daviddossett @isidorn
   - [ ] :runner: Support Syncing Settings Profiles [vscode#154243](https://github.com/microsoft/vscode/issues/154243) @tyriar @sandy081 @lszomoru
   - [ ] Finalize profiles import/export feature [vscode#159891](https://github.com/microsoft/vscode/issues/159891) @sandy081 @bpasero
- [x] Support hiding/showing toolbar items using right-click [vscode#150916](https://github.com/microsoft/vscode/issues/150916) @jrieken
- [x] Provide `Continue On...` support in core [vscode#160047](https://github.com/microsoft/vscode/issues/160047) @joyceerhl
- [ ] :runner: Define default snippets for languages (empty file getting started) [vscode#145929](https://github.com/microsoft/vscode/issues/145929) @digitarald
- [x] Add configurations for search view decorations [vscode#157462](https://github.com/microsoft/vscode/issues/157462) @andreamah
- [x] Explore showing search results as a tree view [vscode#20224](https://github.com/microsoft/vscode/issues/20224) @andreamah @roblourens
- [ ] :runner: Align trust and policy UX in settings editor with other indicators [vscode#157564](https://github.com/microsoft/vscode/issues/157564) @rzhao271 @sandy081
- [ ] :runner: Support actions on quick pick categories [vscode#149057](https://github.com/microsoft/vscode/issues/149057) @TylerLeonhardt @daviddossett
- [x] Unify toggle UX in input fields throughout the workbench [vscode#156179](https://github.com/microsoft/vscode/issues/156179) @Tyriar
- [x] Allow disabling incremental naming on paste for the explorer [vscode#84857](https://github.com/microsoft/vscode/issues/84857) @lramos15
- [x] Explore syncing open recent and recent on getting started [vscode#60821](https://github.com/microsoft/vscode/issues/60821) @lramos15
- [x] Share and Copy As consolidation [vscode#157722](https://github.com/microsoft/vscode/issues/157722) @alexr00

### Web
- [ ] :runner: Continue translations in the web [vscode#82595](https://github.com/microsoft/vscode/issues/82595) @Tylerleonhardt

#### WebAssembly Runtime Support
- [x] Productize `@vscode/sync-*` npm packages [vscode-wasm#3](https://github.com/microsoft/vscode-wasm/issues/3) @dbaeumer
- [x] Implement cancellation strategy for sync npm packages [vscode#148967](https://github.com/microsoft/vscode/issues/148967) @dbaeumer
- [ ] Explore testing strategies for `@vscode/wasm-wasi` [vscode-wasm#4](https://github.com/microsoft/vscode-wasm/issues/4) @dbaeumer
- [ ] Provide a web-shell with pluggable parser and multi-line editing capabilities [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @tyriar

### Code Editor
- [x] Support sticky scroll for languages without outline support [vscode#157165](https://github.com/microsoft/vscode/issues/157165) @aiday-mar @jrieken
- [ ] :runner: Explore using TreeSitter for generating TM scopes for TypeScript [vscode#161256](https://github.com/microsoft/vscode/issues/161256) @aiday-mar @jrieken @aeschli
- [ ] Explore accepting parts of an inline completion proposal [vscode#155473](https://github.com/microsoft/vscode/issues/155473) @hediet
- [ ] Publish a new version of the Monaco editor [monaco-editor](https://github.com/microsoft/monaco-editor/) @hediet
- [ ] :muscle: Modernize the Monaco editor playground [monaco-editor#3247](https://github.com/microsoft/monaco-editor/issues/3247) @hediet
- [x] Support snippets in workspace edits [vscode#145374](https://github.com/microsoft/vscode/issues/145374) @jrieken

### Merge Editor
- [ ] :runner: Explore switching the merge editor to the new diff algorithm [vscode#160801](https://github.com/microsoft/vscode/issues/160801) @hediet
- [x] Add possibility to see and diff against base [vscode#155277](https://github.com/microsoft/vscode/issues/155277) @hediet
- [ ] :muscle: Reduce conflict in case both sides have common lines in their diffs [vscode#157496](https://github.com/microsoft/vscode/issues/157496) @hediet
- [x] Explore a toggle to hide non conflicting areas (streamline merge editor for git conflict resolution) @hediet
- [x] 3-way merge editor customer development [vscode#159561](https://github.com/microsoft/vscode/issues/159561) @isidorn @stevencl

### Notebook Editor
- [ ] :runner: Help users diagnose notebook rendering perf issues [vscode#154873](https://github.com/microsoft/vscode/issues/154873) @mjbvz
- [x] Support HTML headers in the notebook outline [vscode#134853](https://github.com/microsoft/vscode/issues/134853) @rebornix
- [x] Show changes in the overview ruler of the notebook diff editor [vscode#146224](https://github.com/microsoft/vscode/issues/146224) @rebornix
- [ ] :muscle: Explore improving files search results for notebooks [vscode#95275](https://github.com/microsoft/vscode/issues/148068) @andreamah

#### Jupyter Notebooks
- [x] Unify Stop/Interrupt button across core and Jupyter [vscode#128245](https://github.com/microsoft/vscode/issues/128245) [vscode-jupyter#7661](https://github.com/microsoft/vscode-jupyter/issues/7661) @rebornix
- [ ] :runner: Contributions to the vscode-jupyter extension [vscode-jupyter#11286](https://github.com/microsoft/vscode-jupyter/issues/11286) **team**

### Custom Views
- [x] Allow tree items to have optional checkboxes [vscode#116141](https://github.com/microsoft/vscode/issues/116141) @benibenj

#### Python
- [ ] :runner: Contributions to the python extension [vscode-python#19779](https://github.com/microsoft/vscode-python/issues/19779) @brettcannon **team**

##### Python WebAssembly Runtime Support
- [x] Improve performance of python environments hosted on GitHub [vscode-wasm#5](https://github.com/microsoft/vscode-wasm/issues/5)@dbaeumer @joyceerhl
- [x] Investigate installing python packages with native code into a Python environment hosted on GitHub @dbaeumer @aeschli
- [x] Make GitHub hosted python environments available in `vscode.dev` [vscode-wasm#6](https://github.com/microsoft/vscode-wasm/issues/6) @dbaeumer @aeschli

#### JavaScript/TypeScript
- [ ] Explore automatic type acquisition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz
- [ ] :hand: Support TS project-wide intellisense on web [typescript#47600](https://github.com/microsoft/TypeScript/issues/47600) @mjbvz

#### Markdown
- [ ] :muscle: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz

#### JSON
- [ ] :runner: Sort JSON properties alphabetically [vscode#155312](https://github.com/microsoft/vscode/issues/155312) @aiday-mar @aeschli

#### CSS
- [x] Add support for new CSS syntax (@layer, @property) [vscode#147354](https://github.com/microsoft/vscode/issues/147354) [vscode#157267](https://github.com/microsoft/vscode/issues/157267) @aeschli

### Debug
- [x] Extension debugging in a clean environment [vscode#126737](https://github.com/microsoft/vscode/issues/159572) @weinand

#### DAP
- [x] Starting new debug session from within a debug adapter [debug-adapter-protocol#79](https://github.com/microsoft/debug-adapter-protocol/issues/79) @weinand @roblourens @connor4312

### Terminal
- [x] Support hyperlink ansi escapes in the integrated terminal [vscode#39278](https://github.com/microsoft/vscode/issues/39278) @Tyriar
- [x] Support custom terminal markers [vscode#157026](https://github.com/microsoft/vscode/issues/157026) @meganrogge @tyriar
- [x] Investigate flaky terminal/tasks smoke tests [vscode#159510](https://github.com/microsoft/vscode/issues/159510) @meganrogge
- [x] :muscle: Investigate contextual commands [vscode#151937](https://github.com/microsoft/vscode/issues/151937) @meganrogge

### Source Control
- [x] Support git with private key password [vscode#13680](https://github.com/microsoft/vscode/issues/13680) @lszomoru
- [x] Git: Support nested git repositories [vscode#37947](https://github.com/microsoft/vscode/issues/37947) @lszomoru
- [ ] :runner: Git - add action to pull branch before switching [vscode#159165](https://github.com/microsoft/vscode/issues/159165) @lszomoru

### Extensions
- [x] Explore using `SharedArrayBuffer` in the web worker extension host on desktop [vscode#116715](https://github.com/microsoft/vscode/issues/116715) @jrieken
- [x] Sort extensions by extension update date [vscode#53405](https://github.com/microsoft/vscode/issues/53405) @benibenj @sandy081
- [ ] :runner: Explore Extensions Management notification center [vscode#159889](https://github.com/microsoft/vscode/issues/159889) @benibenj @sandy081

### API
- [ ] API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [ ] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Continue finalization of remaining proposed notebook API [vscode#149861](https://github.com/microsoft/vscode/issues/149861) @mjbvz @rebornix @roblourens
- [ ] :runner: Work with LiveShare on content provider migration [vscode#147248](https://github.com/microsoft/vscode/issues/147248) @mjbvz
- [X] Support context menu actions in webviews [vscode#54285](https://github.com/microsoft/vscode/issues/54285) @mjbvz
- [X] `vscode.open` on document link doesn't accept additional arguments [vscode#154993](https://github.com/microsoft/vscode/issues/154993) @mjbvz
- [ ] :runner: Improve Extensions logging [vscode#159892](https://github.com/microsoft/vscode/issues/159892) @sandy081

### Extension Contributions
- [ ] :runner: Improvements to the Remote extensions [vscode-remote-release#7160](https://github.com/microsoft/vscode-remote-release/issues/7160) @eleanorjboyd @chrmarti @aeschli
- [ ] :runner: GitHub Repositories: [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/18) @joyceerhl
- [ ] :runner: Improvements to the Live Preview extension: [query](https://github.com/microsoft/vscode-livepreview/milestone/19) @andreamah @roblourens
- [ ] :hand: Fix preview of forwarded ports in Codespaces for Simple Browser and Live Preview [vscode-livepreview#111](https://github.com/microsoft/vscode-livepreview/issues/111) @andreamah @mjbvz
- [x] Try to link PRs to issues mentioned in the PR title [vscode-pull-request-github#3739](https://github.com/microsoft/vscode-pull-request-github/issues/3739) @alexr00
- [ ] :runner: GHPR: Adopt localization pipeline [vscode-pull-request-github#3913](https://github.com/microsoft/vscode-pull-request-github/issues/3913) @alexr00

### Install / Update
- [x] Integrate with the Windows 11 explorer context menu [vscode#127365](https://github.com/microsoft/vscode/issues/127365) @deepak1556

### Engineering
- [x] Explore using `swc` for transpilation [vscode#150025](https://github.com/microsoft/vscode/issues/150025) @jrieken
- [ ] :muscle: Explore migrating from AMD to ESM [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken
- [x] Sandboxing: Utility process does not support stdout and stderr [vscode#155987](https://github.com/microsoft/vscode/issues/155987) @bpasero @deepak1556
- [ ] Sandboxing: Explore adopting utility process for shared process [vscode#154050](https://github.com/microsoft/vscode/issues/154050) @bpasero @deepak1556
- [ ] :runner: Investigate startup performance regression and improvements [vscode@156864](https://github.com/microsoft/vscode/issues/156864) @jrieken @bpasero @alexr00 @sandy081 <@team>
- [ ] :muscle: Parcel: Support simple glob patterns for ignore rules [watcher#64](https://github.com/parcel-bundler/watcher/issues/64) @bpasero
- [ ] Investigate using `chardet` instead of `jschardet` [vscode#159896](https://github.com/microsoft/vscode/issues/159896) @bpasero
- [ ] :hand: Linux: authentication fails on Ubuntu 22.04 [vscode#159124](https://github.com/microsoft/vscode/issues/159124) @TylerLeonhardt @deepak1556

#### Electron
- [ ] :runner: White flashing when opening a new window [vscode#132339](https://github.com/microsoft/vscode/issues/132339) @rzhao271 @deepak1556
- [x] Improve screen reader detection on macOS [vscode#158008](https://github.com/microsoft/vscode/issues/158008) @deepak1556
- [x] Contribute the utility process and APIs to Electron [vscode#154007](https://github.com/microsoft/vscode/issues/154007) @deepak1556
- [x] Seg fault in Linux integration tests (electron) [vscode#153181](https://github.com/microsoft/vscode/issues/153181) @deepak1556
- [ ] :muscle: Main Request service is throwing errors for valid requests [vscode#155204](https://github.com/microsoft/vscode/issues/155204) @deepak1556
- [x] WCO restore icon is off-center of the button when window is maximized [electron#35038](https://github.com/electron/electron/issues/35038) @rzhao271
- [x] WCO separator colour incorrect in v20 [electron#35312](https://github.com/electron/electron/issues/35312) @rzhao271
- [x] WCO incorrect behavior in tablet mode [vscode#159851](https://github.com/microsoft/vscode/issues/159851) @rzhao271 @deepak1556
- [ ] :runner: WCO misaligned when OS is configured to RTL [vscode#159813](https://github.com/microsoft/vscode/issues/159813) @rzhao271 @deepak1556
- [ ] WCO black border under buttons [vscode#150778](https://github.com/microsoft/vscode/issues/150778) @rzhao271

### Documentation
- [ ] :runner: Review and update Configure C++ Debugging topic [vscode-docs#5518](https://github.com/microsoft/vscode-docs/issues/5518) @gregvanl
- [ ] :runner: Investigate pulling out advanced, reference, and troubleshooting content from Terminal Basics [vscode-docs#4809](https://github.com/microsoft/vscode-docs/issues/4809) @gregvanl @tyriar
- [ ] :runner: Update Azure Content, ToC [vscode-docs#5614](https://github.com/microsoft/vscode-docs/issues/5614) @gregvanl @isidorn
- [ ] Explain how to use the merge editor [vscode-docs#5618](https://github.com/microsoft/vscode-docs/issues/5618) @hediet @gregvanl

----
### Deferred
- [ ] Explore possibility of unifying explorer selection in focus behind a setting @lramos15
- [ ] :hand: Explore creating a debug config for a terminal command [vscode#150460](https://github.com/microsoft/vscode/issues/150460) @connor4312
- [ ] :hand: Reload extension host on server side when connected from web and locale is changed [vscode#151000](https://github.com/microsoft/vscode/issues/151000) @TylerLeonhardt
- [ ] Align editor find widget with the notebook find widget [vscode#144851](https://github.com/microsoft/vscode/issues/144851) @rebornix
- [ ] Support shipping and automatic activation of bash and zsh completions on macOS when shell integration is enabled [vscode#155733](https://github.com/microsoft/vscode/issues/155733) @tyriar @meganrogge
- [ ] Automatically create debug config with a "dry run" [vscode-js-debug#1214](https://github.com/microsoft/vscode-js-debug/issues/1214) @connor4312
- [ ] Explore improvements to Extensions view [#151599](https://github.com/microsoft/vscode/issues/151599) @misolori

**Comment by kingofDaniel** [comment]
hi

**Comment by JorensM** [comment]
Please add "exclude comments" option for search. It's been requested for many years now (#11688)

**Comment by sghaugen** [comment]
Curious, why was the iteration plan created as an issue?

**Comment by Curious-r** [comment]
> Curious, why was the iteration plan created as an issue?

ummmm, I almost thought I was asked...😂

**Comment by mjbvz** [comment]
Closing as 1.72 has shipped: https://code.visualstudio.com/updates/v1_72
