### ISSUE TITLE
Iteration Plan for October 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#163069]
This plan captures our work in **October**. This is a 4-week iteration. We will ship in early **November**.

## Endgame
- **October 24, 2022**: Endgame begins
- **October 28, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22October+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22October+2022%22) @isidorn @meganrogge **team**
- [x] Accessibility explorations [vscode#162867](https://github.com/microsoft/vscode/issues/162867) @meganrogge
- [ ] :runner: Improve accessibility of Setting indicators [vscode#159088](https://github.com/microsoft/vscode/issues/159088) @rzhao271

### UX
- [ ] :runner: Provide guidance for usage of Quick Pick titles [vscode#158895](https://github.com/microsoft/vscode/issues/158895) @daviddossett
- [x] Explore presenting deleted lines in the minimap [vscode#161386](https://github.com/microsoft/vscode/issues/161386) @daviddossett
- [x] Explore UI improvements for the GitHub PR extension [vscode-pull-request-github#4029](https://github.com/microsoft/vscode-pull-request-github/issues/4029) @daviddossett @alexr00

### Workbench
- [ ] [Setting Profiles](https://github.com/microsoft/vscode/issues/116740)
   - [x] Show Synced Profiles in Settings Sync Data views [vscode#162942](https://github.com/microsoft/vscode/issues/162942) @sandy081
- [x] Align trust and policy UX in settings editor with other indicators [vscode#157564](https://github.com/microsoft/vscode/issues/157564) @rzhao271 @sandy081
- [ ] :runner: Adopt `diffIdentityProvider` in search for improved performance [vscode#127621](https://github.com/microsoft/vscode/issues/127621) @andreamah
- [ ] :muscle: Explore ways to improve interacting with root files and folders in a crowded explorer view @lramos15 [vscode#151630](https://github.com/microsoft/vscode/issues/151630)
- [x] Introduce basic "home view" entry point for the Command Center [vscode#158638](https://github.com/microsoft/vscode/issues/158638) @TylerLeonhardt
- [ ] :runner: Improve "Continue On..." (performance, usability, completeness) [vscode#163077](https://github.com/microsoft/vscode/issues/163077) @joyceerhl
- [x] Improve View menu structure for editor actions [vscode#158458](https://github.com/microsoft/vscode/issues/158458) @sbatten @daviddossett

### Web
- [x] Continue translations in the web [vscode#82595](https://github.com/microsoft/vscode/issues/82595) @Tylerleonhardt

### Code Editor
- [x] Remove too many folding regions notification [vscode#163428](https://github.com/microsoft/vscode/issues/163428) @aeschli
- [x] Make it more clear that long lines are truncated [vscode#162320](https://github.com/microsoft/vscode/issues/162320) @alexdima

### Merge Editor
- [x] Add "Mark as Handled: action in the Result view [vscode#162656](https://github.com/microsoft/vscode/issues/162656) @hediet
- [x] Render diff information in Base [vscode#160292](https://github.com/microsoft/vscode/issues/160292) @hediet
- [x] Accept both sides under each other when character-level merging is not possible [vscode#157632](https://github.com/microsoft/vscode/issues/157632) @hediet
- [x] Continue Merge editor customer development [vscode#162815](https://github.com/microsoft/vscode/issues/162815) @isidorn @stevencl

### Notebook Editor
- [x] :red_circle: Ensure markdown renderers are always loaded successfully @mjbvz @rebornix
- [ ] :runner: Help users diagnose notebook rendering perf issues [vscode#154873](https://github.com/microsoft/vscode/issues/154873) @mjbvz
- [ ] :muscle: Enable scrollable notebook outputs [vscode-jupyter#7096](https://github.com/microsoft/vscode-jupyter/issues/7096) @amunger
- [ ] :muscle: :runner: Explore improving files search results for notebooks [vscode#95275](https://github.com/microsoft/vscode/issues/148068) @andreamah

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#11581](https://github.com/microsoft/vscode-jupyter/issues/11581) **team**

#### Python
- [x] Contributions to the python extension [vscode-python#19972](https://github.com/microsoft/vscode-python/issues/19972) @brettcannon **team**

#### Markdown
- [ ] :muscle: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz
- [x] Finalize support for markdown link refactoring updates [vscode#148146](https://github.com/microsoft/vscode/issues/148146) @mjbvz

### Debug
- [ ] :runner: Implement `StartDebugging` DAP request [vscode#160169](https://github.com/microsoft/vscode/issues/160169) @roblourens

### Terminal
- [ ] :runner: Allow extensions to contribute terminal quick fixes [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @meganrogge
- [ ] :runner: Adopt editor quick fix widget for terminal quick fixes [vscode#162067](https://github.com/microsoft/vscode/issues/162067) @meganrogge
- [x] Improve UX of port quick fix [vscode#162217](https://github.com/microsoft/vscode/issues/162217) @meganrogge

### Source Control
- [ ] :runner: Explore implementing certain git status operations without spawning git [vscode#64234](https://github.com/microsoft/vscode/issues/64234) @lszomoru
- [ ] :runner: Responsive UI updates handling of slow status updates in large mono repos [vscode#162417](https://github.com/microsoft/vscode/issues/162417) @lszomoru
- [x] Git - Adopt extension log API [vscode#162185](https://github.com/microsoft/vscode/issues/162185) @lszomoru

### Extensions
- [x] Verify signed extension [vscode#162284](https://github.com/microsoft/vscode/issues/162284) @sandy081

### API
- [x] API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [x] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Continue finalization of remaining proposed notebook API [vscode#149861](https://github.com/microsoft/vscode/issues/149861) @mjbvz @rebornix @roblourens
- [ ] :runner: Work with LiveShare on content provider migration [vscode#147248](https://github.com/microsoft/vscode/issues/147248) @mjbvz
- [ ] :runner: Improve Extensions logging [vscode#159892](https://github.com/microsoft/vscode/issues/159892) @sandy081

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#7315](https://github.com/microsoft/vscode-remote-release/issues/7315) @eleanorjboyd @chrmarti @aeschli
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/19) @joyceerhl
- [x] Improvements to the Live Preview extension [query](https://github.com/microsoft/vscode-livepreview/milestone/20) @andreamah @roblourens
- [ ] :hand: Fix preview of forwarded ports in Codespaces for Simple Browser and Live Preview [vscode-livepreview#111](https://github.com/microsoft/vscode-livepreview/issues/111) @andreamah @mjbvz
- [x] GHPRI: Adopt localization pipeline [vscode-pull-request-github#3913](https://github.com/microsoft/vscode-pull-request-github/issues/3913) @alexr00

### Install / Update
- [x] Enable Windows 11 explorer context menu feature with Insiders [vscode#127365](https://github.com/microsoft/vscode/issues/127365) @deepak1556

### Engineering
- [x] Enrich extension host unresponsive telemetry events to include slow stacks [vscode#163819](https://github.com/microsoft/vscode/issues/163819) @jrieken
- [x] Investigate slow stacks reported from the renderer process [vscode#163819](https://github.com/microsoft/vscode/issu  es/163819) @jrieken
- [ ] :runner: Explore lazy code loading @jrieken @tyriar [vscode#164068](https://github.com/microsoft/vscode/issues/164068)
- [ ] :runner: Explore reducing typing latency [vscode#161622](https://github.com/microsoft/vscode/issues/161622) @tyriar

#### Electron
- [x] Contribute the utility process and APIs to Electron [vscode#154007](https://github.com/microsoft/vscode/issues/154007) @deepak1556
- [ ] :muscle: Enable `AutoDisableAccessibility` Chromium runtime flag [vscode#162331](https://github.com/microsoft/vscode/issues/162331) @deepak1556
- [x] WCO black border under buttons [vscode#150778](https://github.com/microsoft/vscode/issues/150778) @rzhao271
- [ ] :runner: Adopt display language as locale for electron to properly display WCO [vscode#159958](https://github.com/microsoft/vscode/pull/159958) @rzhao271

### Documentation
- [ ] :runner: Update Azure Content, ToC [vscode-docs#5614](https://github.com/microsoft/vscode-docs/issues/5614) @gregvanl @isidorn
- [x] Update Dev Container documentation [vscode-docs#5696](https://github.com/microsoft/vscode-docs/issues/5696) @gregvanl @bamurtaugh

----
### Deferred
- [ ] Exploration: Sharing profiles [vscode#159891](https://github.com/microsoft/vscode/issues/159891) @sandy081 @isidorn
- [ ] Improve how title bar visibility interacts with its interactive components [vscode#161948](https://github.com/microsoft/vscode/issues/161948) @sbatten @jrieken
- [ ] Explore automatic type acquisition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz
- [ ] Add task dropdown menu to terminals, hidden by default [vscode#162469](https://github.com/microsoft/vscode/issues/162469) @meganrogge
- [ ] SCM: Notification API [vscode#161200](https://github.com/microsoft/vscode/issues/161200) @lszomoru
- [ ] Git: Improve unsafe repository warning [vscode#157159](https://github.com/microsoft/vscode/issues/157159) @lszomoru
- [ ] GHPRI: Show PR review status [vscode-pull-request-github#681](https://github.com/microsoft/vscode-pull-request-github/issues/681) @alexr00
- [ ] :red_circle: Explore splitting main bundle in multiple files @jrieken
- [ ] Update source control documentation to include the merge editor [vscode-docs#5618](https://github.com/microsoft/vscode-docs/issues/5618) @hediet @gregvanl
- [ ] Add an Git introductory page [vscode-docs#5677](https://github.com/microsoft/vscode-docs/pull/5677) @digitarald
- [ ] Explore how to better express view display styles (tree versus list) [vscode#162595](https://github.com/microsoft/vscode/issues/162595) @daviddossett
- [ ] Explore migrating from AMD to ESM [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken
- [ ] Support actions on quick pick categories [vscode#149057](https://github.com/microsoft/vscode/issues/149057) @TylerLeonhardt @daviddossett
- [ ] Explore possibility of unifying explorer selection in focus behind a setting @lramos15
- [ ] Align editor find widget with the notebook find widget [vscode#144851](https://github.com/microsoft/vscode/issues/144851) @rebornix
- [ ] Explore accepting parts of an inline completion proposal [vscode#155473](https://github.com/microsoft/vscode/issues/155473) @hediet
- [ ] Sandboxing: Explore adopting utility process for shared process [vscode#154050](https://github.com/microsoft/vscode/issues/154050) @bpasero @deepak1556
- [ ] :runner: White flashing when opening a new window [vscode#132339](https://github.com/microsoft/vscode/issues/132339) @rzhao271 @deepak1556
- [ ] Review and update Configure C++ Debugging topic [vscode-docs#5518](https://github.com/microsoft/vscode-docs/issues/5518) @gregvanl

**Comment by lorand-horvath** [comment]
An update to latest Electron 19.1.x would also be welcome:
https://github.com/electron/electron/releases/tag/v19.1.0
https://github.com/electron/electron/releases/tag/v19.1.1
https://github.com/electron/electron/releases/tag/v19.1.2
https://github.com/electron/electron/releases/tag/v19.1.3
