### ISSUE TITLE
Iteration Plan for November 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#165643]
This plan captures our work in **November**. This is a 5-week iteration. We will ship in early **December**. Heads-up, we'll use the month of December for our annual house keeping iterations. So, this is the plan for the last stable release of the year.

## Endgame
- **November 28, 2022**: Endgame begins
- **December 2, 2022**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22November+2022%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22November+2022%22) @meganrogge @isidorn **team**
- [x] Improve accessibility of Setting indicators [vscode#159088](https://github.com/microsoft/vscode/issues/159088) @rzhao271
- [x] Fix accessibility issues in the welcome page [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+label%3Agetting-started+-label%3Aunder-discussion+assignee%3Abhavyaus) @bhavyaus

### UX
- [x] Identify Getting Started walkthrough improvements [vscode#165846](https://github.com/microsoft/vscode/issues/165846) @daviddossett @bhavyaus
- [ ] :runner: Explore surfacing the remote experiences on the welcome page [vscode-internalbacklog#3276](https://github.com/microsoft/vscode-internalbacklog/issues/3276) @bhavyaus
- [x] Provide guidance for usage of Quick Pick titles [vscode#158895](https://github.com/microsoft/vscode/issues/158895) @daviddossett
- [x] Identify improvements to workbench usability and aesthetic [vscode#115641](https://github.com/microsoft/vscode/issues/115641) @daviddossett
- [ ] :runner: Explore updated built-in themes [vscode#164924](https://github.com/microsoft/vscode/issues/164924) @daviddossett

### Workbench
- [x] Exploration: Sharing profiles [vscode#159891](https://github.com/microsoft/vscode/issues/159891) @sandy081 @isidorn
- [x] Allow hiding of badges for view containers [vscode#158781](https://github.com/microsoft/vscode/pull/158781) @lramos15
- [x] Support exclusions for the explorer's `autoReveal` behavior [vscode#136905](https://github.com/microsoft/vscode/pull/136905) @lramos15
- [x] Investigate issue with users getting stuck in restricted mode [vscode#161362](https://github.com/microsoft/vscode/issues/161362)  @sbatten
- [x] Swap Continue On item picker and asking for auth order [vscode#165409](https://github.com/microsoft/vscode/issues/165409) @joyceerhl
- [x] Remove mention of edit sessions from: [vscode#165408](https://github.com/microsoft/vscode/issues/165408) @joyceerhl
- [ ] :runner: Surface Continue On in more places [vscode#165406](https://github.com/microsoft/vscode/issues/165406) @joyceerhl

#### WebAssembly Runtime Support
- [x] Provide pluggable device drivers in WASM-WASI [vscode-wasm#28](https://github.com/microsoft/vscode-wasm/issues/28)@dbaeumer
- [ ] :runner: :muscle: Explore provide a web-shell [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @dbaeumer @tyriar

### Code Editor
- [x] Explore accepting parts of an inline completion proposal [vscode#140708](https://github.com/microsoft/vscode/issues/140708) @hediet
- [x] Explore moving tokenization to a web worker [vscode#147066](https://github.com/microsoft/vscode/issues/147066) @hediet
- [x] Have a setting to not focus suggestions [vscode#151336](https://github.com/microsoft/vscode/issues/151336) @jrieken

### Merge Editor
- [x] Participate in undo stack [vscode#158864](https://github.com/microsoft/vscode/issues/158864) @hediet
- [x] Replace "Mark as Handled" with "Ignore" actions [vscode#165696](https://github.com/microsoft/vscode/issues/165696) @hediet

### Notebook Editor
- [ ] :runner: Explore a built-in variables viewer [vscode#165445](https://github.com/microsoft/vscode/issues/165445) @roblourens
- [ ] :runner: Enable scrollable notebook outputs [vscode-jupyter#7096](https://github.com/microsoft/vscode-jupyter/issues/7096) @amunger
- [ ] :muscle: Drop `NotebookContentProvider` usage in the Interactive Window [vscode#165252](https://github.com/microsoft/vscode/issues/165252) @amunger
- [x] Use consistent origin in backlayer webview for notebooks to improve caching [vscode#145567](https://github.com/microsoft/vscode/issues/145567) @mjbvz
- [x] Help users diagnose notebook rendering perf issues [vscode#154873](https://github.com/microsoft/vscode/issues/154873) @mjbvz
- [x] Improvements to notebook opening performance [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aperf+milestone%3A%22November+2022%22+assignee%3Amjbvz) @mjbvz
- [ ] :runner: Allow searching dirty changes in open notebook editors in global search [vscode#95275](https://github.com/microsoft/vscode/issues/148068) @andreamah
- [ ] :runner: Allow searching rich content in notebooks in global search [vscode#164926](https://github.com/microsoft/vscode/issues/164926) @andreamah

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#11922](https://github.com/microsoft/vscode-jupyter/issues/11922) **team**

#### Language Server Protocol
- [x] Publish new LSP release [Fixed issue](https://github.com/microsoft/vscode-languageserver-node/issues?q=is%3Aissue+milestone%3A8.1.0+is%3Aclosed) @dbaeumer

#### Python
- [x] Contributions to the python extension [vscode-python#20161](https://github.com/microsoft/vscode-python/issues/20161) @brettcannon **team**

##### Python WebAssembly Runtime Support
- [x] Implement a debug device driver for Python [Branch](https://github.com/microsoft/vscode-python-web-wasm/tree/dbaeumer/debugAdapter) @dbaeumer
- [x] Help getting pdb work in the web [PR](https://github.com/microsoft/vscode-python-web-wasm/pull/16) @dbaeumer

#### JavaScript/TypeScript
- [ ] :runner: Explore automatic type acquisition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz

### Debug
- [x] Implement `StartDebugging` DAP request [vscode#160169](https://github.com/microsoft/vscode/issues/160169) @roblourens
- [x] Provide support for `console.profile` [vscode-js-debug#1443](https://github.com/microsoft/vscode-js-debug/issues/1443) @connor4312

#### Debug Adapter Protocol
- [x] EOF behavior [debug-adapter-protocol#239](https://github.com/microsoft/debug-adapter-protocol/issues/239) @connor4312 @roblourens @weinand
- [ ] :runner: Memory reuse [debug-adapter-protocol#238](https://github.com/microsoft/debug-adapter-protocol/issues/238) @connor4312 @roblourens @weinand

### Testing
- [ ] :muscle: Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [ ] :muscle: Auto run tests [vscode#134941](https://github.com/microsoft/vscode/issues/134941) @connor4312

### Comments
- [x] Additional actions in the Comment Thread [vscode#163281](https://github.com/microsoft/vscode/issues/163281) @alexr00

### Terminal
- [x] Allow extensions to contribute terminal quick fixes [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @meganrogge
- [x] Adopt editor quick fix widget for terminal quick fixes [vscode#162067](https://github.com/microsoft/vscode/issues/162067) @meganrogge

### Tasks
- [x] Add run task action to terminal dropdown [vscode#162469](https://github.com/microsoft/vscode/issues/162469) @meganrogge
- [x] Investigate duplicate build tasks [vscode#159640](https://github.com/microsoft/vscode/issues/159640) @meganrogge

### Source Control
- [x] Explore implementing certain git status operations without spawning git [vscode#64234](https://github.com/microsoft/vscode/issues/64234) @lszomoru
- [x] Responsive UI updates handling of slow status updates in large mono repos [vscode#162417](https://github.com/microsoft/vscode/issues/162417) @lszomoru
- [x] SCM: Notification API [vscode#161200](https://github.com/microsoft/vscode/issues/161200) @lszomoru
- [x] Git: Improve unsafe repository warning [vscode#157159](https://github.com/microsoft/vscode/issues/157159) @lszomoru

### API
- [x] API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [x] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Continue finalization of remaining proposed notebook API [vscode#149861](https://github.com/microsoft/vscode/issues/149861) @mjbvz @rebornix @roblourens
- [x] Improve Extensions logging [vscode#159892](https://github.com/microsoft/vscode/issues/159892) @sandy081

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#7479](https://github.com/microsoft/vscode-remote-release/issues/7479) @eleanorjboyd @chrmarti @aeschli
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/22) @joyceerhl @bhavyaus
- [ ] Live Preview: Add option to specify which external browser [vscode-livepreview#69](https://github.com/microsoft/vscode-livepreview/issues/69) @andreamah
- [ ] Live Preview: Add option to specify the root path of the server [vscode-livepreview#155](https://github.com/microsoft/vscode-livepreview/issues/155) @andreamah
- [ ] :runner: Fix preview of forwarded ports in Codespaces for Simple Browser and Live Preview [vscode-livepreview#111](https://github.com/microsoft/vscode-livepreview/issues/111) @andreamah @mjbvz
- [x] GHPRI: Show PR review status [vscode-pull-request-github#681](https://github.com/microsoft/vscode-pull-request-github/issues/681) @alexr00
- [x] GHPRI: Improve activation performance [vscode-pull-request-github#4053](https://github.com/microsoft/vscode-pull-request-github/issues/4053) @alexr00
- [ ] :runner: :muscle: GHPRI: Support GitHub's suggested changes [vscode-pull-request-github#603](https://github.com/microsoft/vscode-pull-request-github/issues/603) @alexr00

### Performance
- [x] Introduce an Input Latency telemetry event [vscode#163184](https://github.com/microsoft/vscode/pull/163184) @tyriar
- [ ] :runner: Explore migrating from AMD to ESM [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken @alexdima
    - [ ] Explore using esbuild for transpilation / bundling @alexdima
    - [ ] Explore AMD lazy code loading [vscode#164068](https://github.com/microsoft/vscode/issues/164068) @jrieken @alexdima @tyriar
    - [ ] :red_circle: Explore splitting main AMD bundle in multiple files @jrieken @alexdima
- [ ] :runner: Investigate moving away from the styler pattern [vscode#165478](https://github.com/microsoft/vscode/issues/165478) @aeschli
- [x] Explore mangling of private & protected properties in the codebase [vscode#166126](https://github.com/microsoft/vscode/pull/166126) [vscode#165429](https://github.com/microsoft/vscode/issues/165429) @jrieken
- [x] Investigate reducing the size of the authentication extensions [vscode#165728](https://github.com/microsoft/vscode/issues/165728) @TylerLeonhardt
- [x] Explore improving the loading performance of the Jupyter extension (packing, splitting) [vscode-jupyter#11996](https://github.com/microsoft/vscode-jupyter/issues/11996) @tyriar
- [x] Why is the npm extension using `workspaceContains:package.json`? [vscode#163480](https://github.com/microsoft/vscode/issues/163480) @joyceerhl
- [x] Generate implicit activation events from extension package.json contributions [vscode#164701](https://github.com/microsoft/vscode/issues/164701) @joyceerhl @alexdima @sandy081 @jrieken
- [x] Add a new `onNotebookSerializer:*` [vscode#134127](https://github.com/microsoft/vscode/issues/134127) @joyceerhl
- [ ] Explore `setTimeout` for `onStartupFinished` extensions [vscode#164593](https://github.com/microsoft/vscode/issues/164593) @joyceerhl
- [ ] :runner: Explore running Remote Repositories in a dedicated extension host in vscode.dev [vscode-internalbacklog#3204](https://github.com/microsoft/vscode-internalbacklog/issues/3204) @joyceerhl
- [x] Load language wasm files on demand [vscode-anycode#53](https://github.com/microsoft/vscode-anycode/issues/53) @jrieken
- [x] Eliminate first request to update server on vscode.dev @jrieken
- [x] Generate `<script>` and `<link>` tags server-side on vscode.dev [vscode-dev#454](https://github.com/microsoft/vscode-dev/issues/454) @jrieken
- [x] Web: Cache gallery extension resources [vscode#165817](https://github.com/microsoft/vscode/issues/165817) @sandy081

### Engineering
- [x] Convert LSP and WASM to the new npm publish pipeline [#3191](https://github.com/microsoft/vscode-internalbacklog/issues/3191) @dbaeumer

#### Electron
- [x] Enable `AutoDisableAccessibility` Chromium runtime flag [vscode#162331](https://github.com/microsoft/vscode/issues/162331) @deepak1556
- [x] Main Request service is throwing errors for valid requests [vscode#155204](https://github.com/microsoft/vscode/issues/155204) @deepak1556
- [ ] :runner: Investigate Electron 22 upgrade [vscode#166265](https://github.com/microsoft/vscode/issues/166265) @deepak1556
- [x] Backport `getPreferredSystemLanguages` API in Electron [electron#36035](https://github.com/electron/electron/pull/36035) @rzhao271 @deepak1556
- [x] Adopt display language as locale for electron to properly display WCO [vscode#159958](https://github.com/microsoft/vscode/pull/159958) @rzhao271

### Documentation
- [ ] :runner: Update Azure Content, ToC [vscode-docs#5614](https://github.com/microsoft/vscode-docs/issues/5614) @gregvanl @isidorn
- [x] Update repo locations in Dev Container docs [vscode-docs#5736](https://github.com/microsoft/vscode-docs/issues/5736) @bamurtaugh @gregvanl

----
### Deferred
- [ ] Support profiles in remote workspaces [vscode#165247](https://github.com/microsoft/vscode/issues/165247) @sandy081
- [ ] Settings Editor performance improvements [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Asettings-editor+label%3Aperf) @rzhao271
- [ ] Investigate ways to reduce the performance cost of max results in search [vscode#127621](https://github.com/microsoft/vscode/issues/127621) @andreamah
- [ ] Adopt webpack for emmet-helper [microsoft/vscode-emmet-helper#27](https://github.com/microsoft/vscode-emmet-helper/issues/27) @rzhao271 
- [ ] Update source control documentation to include the merge editor [vscode-docs#5618](https://github.com/microsoft/vscode-docs/issues/5618) @hediet @gregvanl
- [ ] Add an Git introductory page [vscode-docs#5677](https://github.com/microsoft/vscode-docs/pull/5677) @digitarald
- [ ] Restructure and refresh dev containers docs within new Dev Containers node [vscode-docs#5737](https://github.com/microsoft/vscode-docs/issues/5737) @bamurtaugh @gregvanl
- [ ] Convert LSIF to the new npm publish pipeline [#3191](https://github.com/microsoft/vscode-internalbacklog/issues/3191) @dbaeumer
- [ ] Explore how to better express view display styles (tree versus list) [vscode#162595](https://github.com/microsoft/vscode/issues/162595) @daviddossett
- [ ] Explore possibility of unifying explorer selection in focus behind a setting @lramos15
- [ ] Sandboxing: Explore adopting utility process for shared process [vscode#154050](https://github.com/microsoft/vscode/issues/154050) @bpasero @deepak1556
- [ ] :runner: White flashing when opening a new window [vscode#132339](https://github.com/microsoft/vscode/issues/132339) @rzhao271 @deepak1556
- [ ] Review and update Configure C++ Debugging topic [vscode-docs#5518](https://github.com/microsoft/vscode-docs/issues/5518) @gregvanl
- [ ] :muscle: Explore ways to improve interacting with root files and folders in a crowded explorer view @lramos15 [vscode#151630](https://github.com/microsoft/vscode/issues/151630)\
- [ ] :muscle: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz

**Comment by Hgseof** [comment]
> This plan captures our work in **November**. This is a 5-week iteration. We will ship in early **December**. Heads-up, we'll use the month of December for our annual house keeping iterations. So, this is the plan for the last stable release of the year.
> 
> ## Endgame
> * **November 28, 2022**: Endgame begins
> * **December 2, 2022**: Endgame done
> 
> The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22November+2022%22).
> 
> ## Plan Items
> Below is a summary of the top level plan items.
> 
> Legend of annotations:
> 
> Mark	Description
> 🏃	work in progress
> ✋	blocked task
> 💪	stretch goal for this iteration
> 🔴	missing issue reference
> 🔵	more investigation required to remove uncertainty
> ⚫	under discussion within the team
> ⬛	a large work item, larger than one iteration
> ### Accessibility
> * [ ]  🏃 Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22November+2022%22) @meganrogge @isidorn **team**
> * [ ]  🏃 Improve accessibility of Setting indicators [vscode#159088](https://github.com/microsoft/vscode/issues/159088) @rzhao271
> * [x]  Fix accessibility issues in the welcome page [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+label%3Agetting-started+-label%3Aunder-discussion+assignee%3Abhavyaus) @bhavyaus
> 
> ### UX
> * [ ]  🔴 Identify Getting Started walkthrough improvements @daviddossett @bhavyaus
> * [ ]  🔴 Explore surfacing the remote experiences on the welcome page @bhavyaus
> * [ ]  🏃 Provide guidance for usage of Quick Pick titles [vscode#158895](https://github.com/microsoft/vscode/issues/158895) @daviddossett
> * [ ]  Identify improvements to workbench usability and aesthetic [vscode#115641](https://github.com/microsoft/vscode/issues/115641) @daviddossett
> * [ ]  💪 Explore updated built-in themes [vscode#164924](https://github.com/microsoft/vscode/issues/164924) @daviddossett
> 
> ### Workbench
> * [ ]  Exploration: Sharing profiles [vscode#159891](https://github.com/microsoft/vscode/issues/159891) @sandy081 @isidorn
> * [ ]  Support profiles in remote workspaces [vscode#165247](https://github.com/microsoft/vscode/issues/165247) @sandy081
> * [ ]  🏃 Allow hiding of badges for view containers [vscode#158781](https://github.com/microsoft/vscode/pull/158781) @lramos15
> * [ ]  Support exclusions for the explorer's `autoReveal` behavior [vscode#136905](https://github.com/microsoft/vscode/pull/136905) @lramos15
> * [ ]  Settings Editor performance improvements [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Asettings-editor+label%3Aperf) @rzhao271
> * [ ]  Investigate issue with users getting stuck in restricted mode [vscode#161362](https://github.com/microsoft/vscode/issues/161362)  @sbatten
> * [ ]  Swap Continue On item picker and asking for auth order [vscode#165409](https://github.com/microsoft/vscode/issues/165409) @joyceerhl
> * [ ]  Remove mention of edit sessions from: [vscode#165408](https://github.com/microsoft/vscode/issues/165408) @joyceerhl
> * [ ]  Surface Continue On in more places [vscode#165406](https://github.com/microsoft/vscode/issues/165406) @joyceerhl
> 
> ### Search
> * [ ]  Investigate ways to reduce the performance cost of max results in search [vscode#127621](https://github.com/microsoft/vscode/issues/127621) @andreamah
> 
> ### Web
> #### WebAssembly Runtime Support
> * [ ]  Provide pluggable device drivers in WASM-WASI [vscode-wasm#28](https://github.com/microsoft/vscode-wasm/issues/28)@dbaeumer
> * [ ]  💪 Explore provide a web-shell [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @dbaeumer @Tyriar
> 
> ### Code Editor
> * [ ]  Explore accepting parts of an inline completion proposal [vscode#140708](https://github.com/microsoft/vscode/issues/140708) @hediet
> * [ ]  Explore moving tokenization to a web worker [vscode#147066](https://github.com/microsoft/vscode/issues/147066) @hediet
> 
> ### Merge Editor
> * [ ]  Participate in undo stack [vscode#158864](https://github.com/microsoft/vscode/issues/158864) @hediet
> * [x]  Replace "Mark as Handled" with "Ignore" actions [vscode#165696](https://github.com/microsoft/vscode/issues/165696) @hediet
> 
> ### Notebook Editor
> * [ ]  Explore a built-in variables viewer [vscode#165445](https://github.com/microsoft/vscode/issues/165445) @roblourens
> * [ ]  Enable scrollable notebook outputs [vscode-jupyter#7096](https://github.com/microsoft/vscode-jupyter/issues/7096) @amunger
> * [ ]  💪 Drop `NotebookContentProvider` usage in the Interactive Window [vscode#165252](https://github.com/microsoft/vscode/issues/165252) @amunger
> * [x]  Use consistent origin in backlayer webview for notebooks to improve caching [vscode#145567](https://github.com/microsoft/vscode/issues/145567) @mjbvz
> * [ ]  🏃 Help users diagnose notebook rendering perf issues [vscode#154873](https://github.com/microsoft/vscode/issues/154873) @mjbvz
> * [ ]  Improvements to notebook opening performance [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+label%3Aperf+milestone%3A%22November+2022%22+assignee%3Amjbvz) @mjbvz
> * [ ]  Allow searching dirty changes in open notebook editors in global search [vscode#95275](https://github.com/microsoft/vscode/issues/148068) @andreamah
> * [ ]  Allow searching rich content in notebooks in global search [vscode#164926](https://github.com/microsoft/vscode/issues/164926) @andreamah
> 
> #### Jupyter Notebooks
> * [ ]  🏃 Contributions to the vscode-jupyter extension [vscode-jupyter#11922](https://github.com/microsoft/vscode-jupyter/issues/11922) **team**
> 
> ### Languages
> #### Language Server Protocol
> * [ ]  Publish new LSP release [Fixed issue](https://github.com/microsoft/vscode-languageserver-node/issues?q=is%3Aissue+milestone%3A8.1.0+is%3Aclosed) @dbaeumer
> 
> #### Python
> * [ ]  🏃 Contributions to the python extension [vscode-python#20161](https://github.com/microsoft/vscode-python/issues/20161) @brettcannon **team**
> 
> ##### Python WebAssembly Runtime Support
> * [ ]  Implement a debug device driver for Python [Branch](https://github.com/microsoft/vscode-python-web-wasm/tree/dbaeumer/debugAdapter) @dbaeumer
> * [ ]  Help getting pdb work in the web [PR](https://github.com/microsoft/vscode-python-web-wasm/pull/16) @dbaeumer
> 
> #### JavaScript/TypeScript
> * [ ]  Explore automatic type acquisition on web [typescript#45314](https://github.com/microsoft/TypeScript/issues/45314) @mjbvz
> 
> ### Debug
> * [ ]  🏃 Implement `StartDebugging` DAP request [vscode#160169](https://github.com/microsoft/vscode/issues/160169) @roblourens
> * [ ]  🔴 Provide support for `console.profile` @connor4312
> 
> #### Debug Adapter Protocol
> * [ ]  EOF behavior [debug-adapter-protocol#239](https://github.com/microsoft/debug-adapter-protocol/issues/239) @connor4312 @roblourens @weinand
> * [ ]  Memory reuse [debug-adapter-protocol#238](https://github.com/microsoft/debug-adapter-protocol/issues/238) @connor4312 @roblourens @weinand
> 
> ### Testing
> * [ ]  💪 Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
> * [ ]  💪 Auto run tests [vscode#134941](https://github.com/microsoft/vscode/issues/134941) @connor4312
> 
> ### Comments
> * [ ]  Additional actions in the Comment Thread [vscode#163281](https://github.com/microsoft/vscode/issues/163281) @alexr00
> 
> ### Terminal
> * [ ]  🏃 Allow extensions to contribute terminal quick fixes [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @meganrogge
> * [ ]  🏃 Adopt editor quick fix widget for terminal quick fixes [vscode#162067](https://github.com/microsoft/vscode/issues/162067) @meganrogge
> 
> ### Tasks
> * [x]  Add run task action to terminal dropdown [vscode#162469](https://github.com/microsoft/vscode/issues/162469) @meganrogge
> * [x]  Investigate duplicate build tasks [vscode#159640](https://github.com/microsoft/vscode/issues/159640) @meganrogge
> 
> ### Source Control
> * [ ]  🏃 Explore implementing certain git status operations without spawning git [vscode#64234](https://github.com/microsoft/vscode/issues/64234) @lszomoru
> * [ ]  🏃 Responsive UI updates handling of slow status updates in large mono repos [vscode#162417](https://github.com/microsoft/vscode/issues/162417) @lszomoru
> * [ ]  SCM: Notification API [vscode#161200](https://github.com/microsoft/vscode/issues/161200) @lszomoru
> * [ ]  Git: Improve unsafe repository warning [vscode#157159](https://github.com/microsoft/vscode/issues/157159) @lszomoru
> 
> ### Extensions
> * None.
> 
> ### API
> * [ ]  API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2022%22+label%3A%22api-finalization%22) @jrieken @mjbvz
> * [ ]  API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2022%22+label%3A%22api-proposal%22) @jrieken @mjbvz
> * [ ]  🏃 Continue finalization of remaining proposed notebook API [vscode#149861](https://github.com/microsoft/vscode/issues/149861) @mjbvz @rebornix @roblourens
> * [ ]  🏃 Improve Extensions logging [vscode#159892](https://github.com/microsoft/vscode/issues/159892) @sandy081
> 
> ### Extension Contributions
> * [ ]  Improvements to the Remote extensions [vscode-remote-release#7479](https://github.com/microsoft/vscode-remote-release/issues/7479) @eleanorjboyd @chrmarti @aeschli
> * [ ]  Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/22) @joyceerhl
> * [ ]  Live Preview: Add option to specify which external browser [vscode-livepreview#69](https://github.com/microsoft/vscode-livepreview/issues/69) @andreamah
> * [ ]  Live Preview: Add option to specify the root path of the server [vscode-livepreview#155](https://github.com/microsoft/vscode-livepreview/issues/155) @andreamah
> * [ ]  Fix preview of forwarded ports in Codespaces for Simple Browser and Live Preview [vscode-livepreview#111](https://github.com/microsoft/vscode-livepreview/issues/111) @andreamah @mjbvz
> * [ ]  GHPRI: Show PR review status [vscode-pull-request-github#681](https://github.com/microsoft/vscode-pull-request-github/issues/681) @alexr00
> * [ ]  🏃 GHPRI: Improve activation performance [vscode-pull-request-github#4053](https://github.com/microsoft/vscode-pull-request-github/issues/4053) @alexr00
> * [ ]  💪 GHPRI: Support GitHub's suggested changes [vscode-pull-request-github#603](https://github.com/microsoft/vscode-pull-request-github/issues/603) @alexr00
> 
> ### Install / Update
> * None.
> 
> ### Performance
> * [ ]  Introduce an Input Latency telemetry event [vscode#163184](https://github.com/microsoft/vscode/pull/163184) @Tyriar
> * [ ]  Explore migrating from AMD to ESM [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken @alexdima
>   
>   * [ ]  🏃 Explore using esbuild for transpilation / bundling @alexdima
>   * [ ]  🏃 Explore AMD lazy code loading [vscode#164068](https://github.com/microsoft/vscode/issues/164068) @jrieken @alexdima @Tyriar
>   * [ ]  🔴 Explore splitting main AMD bundle in multiple files @jrieken @alexdima
> * [ ]  Investigate moving away from the styler pattern [vscode#165478](https://github.com/microsoft/vscode/issues/165478) @aeschli
> * [ ]  Explore mangling of private properties in the codebase [vscode#165429](https://github.com/microsoft/vscode/issues/165429)
> * [ ]  🔴 Adopt webpack for emmet extension @rzhao271
> * [ ]  🏃 Investigate reducing the size of the authentication extensions [vscode#165728](https://github.com/microsoft/vscode/issues/165728) @TylerLeonhardt
> * [ ]  🔴 Explore improving the loading performance of the Jupyter extension (packing, splitting) @Tyriar
> * [ ]  Why is the npm extension using `workspaceContains:package.json`? [vscode#163480](https://github.com/microsoft/vscode/issues/163480) @joyceerhl
> * [ ]  Add a new `onNotebookSerializer:*` [vscode#134127](https://github.com/microsoft/vscode/issues/134127)  @joyceerhl
> * [ ]  Explore `setTimeout` for `onStartupFinished` extensions [vscode#164593](https://github.com/microsoft/vscode/issues/164593) @joyceerhl
> * [ ]  Explore running Remote Repositories in a dedicated extension host in vscode.dev [vscode-internalbacklog#3204](https://github.com/microsoft/vscode-internalbacklog/issues/3204) @joyceerhl
> * [x]  Load language wasm files on demand [vscode-anycode#53](https://github.com/microsoft/vscode-anycode/issues/53) @jrieken
> * [ ]  🔴 🏃 Eliminate first request to update server on vscode.dev @jrieken
> * [ ]  🔴 Generate `<script>` and `<link>` tags server-side on vscode.dev @jrieken
> * [ ]  Web: Cache gallery extension resources [vscode#165817](https://github.com/microsoft/vscode/issues/165817) @sandy081
> 
> ### Engineering
> * [ ]  Convert LSP, LSIF and WASM to the new npm publish pipeline [#3191](https://github.com/microsoft/vscode-internalbacklog/issues/3191) @dbaeumer
> 
> #### Electron
> * [ ]  Enable `AutoDisableAccessibility` Chromium runtime flag [vscode#162331](https://github.com/microsoft/vscode/issues/162331) @deepak1556
> * [ ]  Main Request service is throwing errors for valid requests [vscode#155204](https://github.com/microsoft/vscode/issues/155204) @deepak1556
> * [ ]  🔴 Investigate Electron 22 upgrade @deepak1556
> * [ ]  🏃 Backport `getPreferredSystemLanguages` API in Electron [electron#36035](https://github.com/electron/electron/pull/36035) @rzhao271
> * [ ]  🏃 Adopt display language as locale for electron to properly display WCO [vscode#159958](https://github.com/microsoft/vscode/pull/159958) @rzhao271
> 
> ### Documentation
> * [ ]  🏃 Update Azure Content, ToC [vscode-docs#5614](https://github.com/microsoft/vscode-docs/issues/5614) @gregvanl @isidorn
> * [ ]  Update source control documentation to include the merge editor [vscode-docs#5618](https://github.com/microsoft/vscode-docs/issues/5618) @hediet @gregvanl
> * [ ]  Add an Git introductory page [vscode-docs#5677](https://github.com/microsoft/vscode-docs/pull/5677) @digitarald
> * [ ]  Update repo locations in Dev Container docs [vscode-docs#5736](https://github.com/microsoft/vscode-docs/issues/5736) @bamurtaugh @gregvanl
> * [ ]  Restructure and refresh dev containers docs within new Dev Containers node [vscode-docs#5737](https://github.com/microsoft/vscode-docs/issues/5737) @bamurtaugh @gregvanl
> 
> ### Deferred
> * [ ]  Explore how to better express view display styles (tree versus list) [vscode#162595](https://github.com/microsoft/vscode/issues/162595) @daviddossett
> * [ ]  Explore possibility of unifying explorer selection in focus behind a setting @lramos15
> * [ ]  Sandboxing: Explore adopting utility process for shared process [vscode#154050](https://github.com/microsoft/vscode/issues/154050) @bpasero @deepak1556
> * [ ]  🏃 White flashing when opening a new window [vscode#132339](https://github.com/microsoft/vscode/issues/132339) @rzhao271 @deepak1556
> * [ ]  Review and update Configure C++ Debugging topic [vscode-docs#5518](https://github.com/microsoft/vscode-docs/issues/5518) @gregvanl
> * [ ]  💪 Explore ways to improve interacting with root files and folders in a crowded explorer view @lramos15 [vscode#151630](https://github.com/microsoft/vscode/issues/151630)\
> * [ ]  💪 Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz

**Comment by DetachHead** [comment]
sorry if this is the wrong place to ask, but i'm having trouble finding some more info regarding the "Support for nested sourcemaps" [mentioned in the release notes](https://code.visualstudio.com/updates/v1_74#_javascript-debugging). is there an issue/PR with more info since i don't see anything about it here.

i'm trying to find out if it's related to https://github.com/nodejs/node/issues/45196, but it seems to still be broken

**Comment by connor4312** [comment]
@DetachHead we have a docs section on what you need to tweak 🙂 https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-resolution
