### ISSUE TITLE
Move built-in libraries off `vscode-nls` and on to the `l10n` API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#166305]
Similar to https://github.com/microsoft/vscode/issues/164438 but for libraries...

Here are the docs for `@vscode/l10n`:
https://github.com/microsoft/vscode-l10n/tree/main/l10n

* [x] [vscode-emmet-helper](https://github.com/microsoft/vscode-emmet-helper) ([PR](https://github.com/microsoft/vscode-emmet-helper/pull/71), ✋ https://github.com/microsoft/vscode-l10n/issues/51) @rzhao271 
* [x] [vscode-markdown-languageservice](https://github.com/microsoft/vscode-markdown-languageservice) ([PR](https://github.com/microsoft/vscode-markdown-languageservice/pull/95), Needs `@vscode/l10n` version bump) @mjbvz 
* [x] [vscode-css-languageservice](https://github.com/microsoft/vscode-css-languageservice) @aeschli https://github.com/microsoft/vscode/issues/165729
* [x] [vscode-html-languageservice](https://github.com/microsoft/vscode-html-languageservice) @aeschli https://github.com/microsoft/vscode/issues/165729
* [x] [vscode-json-languageservice](https://github.com/microsoft/vscode-json-languageservice) @aeschli https://github.com/microsoft/vscode/issues/165729

**Comment by aeschli** [comment]
The HTML/CSS/JSON services are now all using @vscode/l10n.

https://github.com/microsoft/vscode/pull/168111 adds the code to configure the servers with location of the localization bundle
