### ISSUE TITLE
Scroll top improvement based on context

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#169038]
Currently the scroll top position update is not context-aware, meaning when we have cell height changes, we don't know if it's because output height change, or users re-run a cell and outputs are updated/replaced, or users shift+enter to run cell and navigate to next cell. Users might have different expectations for each scenario but currently our heuristics for updating the scroll top didn't take the context into account.

Let's use this issue to finalize the desired behavior of scroll top update. The polished/new design should cover

* [ ] Update element height API respects context (execution, execute+create, output update)
* [ ] Reveal API should handle out of sync view/content height

---

## Execute focused cell

* Click the run button or press Ctrl+Enter to run focused cell
* If there is no enough room/space after the cell (e.g., the focused cell is the last cell)
  * Users have `editor.scrollBeyondLastLine` disabled
    * [ ] There is no output before execution, the view should scroll up to reveal the output fully
      * [ ] Some users might want the bottom of the output to be fully revealed, when the output is larger than the viewport https://github.com/microsoft/vscode-jupyter/issues/5186
    * [ ] There is output before execution, the cell position should be persistent 
  * Users have `editor.scrollBeyondLastLine` enabled
    * [ ] Reveal cell output
* If there is enough room after the cell
   * [ ] Reveal cell output
* [ ] If the cell input is larger than the viewport, execute cell should reveal the output properly https://github.com/microsoft/vscode/issues/129440

## Operations on focused cell

* [ ] Collapse focused cell output should always keep the cell in viewport https://github.com/microsoft/vscode/issues/114866
* [ ] Type/Pasting content into focused cell should keep the cell in viewport 
  * [x] https://github.com/microsoft/vscode/issues/165415
  * [ ] Notebook cell list reveal api might reveal a position on a cell whose view height is not synced with real editor height yet.

## Operations on non-focused cell

* [ ] ❓ Execute non-focused cell, should it keep the focused cell position persistent or keep the top of the target cell persistent? https://github.com/microsoft/vscode/issues/121723
* [ ] Non focused cell output height change should not change scroll top on scroll https://github.com/microsoft/vscode/issues/142439
* [ ] Shift+enter executes and moves focus to next cell, then new focused cell should always be in viewport https://github.com/microsoft/vscode/issues/134607

## Split view 
* [x] Scroll top position of inactive notebook editor should not change if the first partially visible cell's height change https://github.com/microsoft/vscode/issues/145340

**Comment by roblourens** [comment]
I noticed an issue recently, is this related?

- Paste a large amount of text into a code cell
- The notebook scrolls down so far that the focused code cell is out of the viewport

I can open a separate issue if you wnt

**Comment by rebornix** [comment]
@roblourens I guess what you were seeing is https://github.com/microsoft/vscode/issues/165415 , I'll update the description to include this.

**Comment by Yoyokrazy** [comment]
Couple cases discovered in the latest notebook sync. both of these are likely tied to outputLineLimit being large @ 100

- when the shift-enter behavior is set to "firstline" the events are as follows:
  - first line of next cell is focused and shown at the bottom of the viewport
  - output is cleared and the focused cell is pulled upwards against the currently executing cell
  - output streams and pushes the focused cell out of the viewport.
  - my ideal thoughts:
    - anchor the focused cell (with setting), maintaining the first line visible. output will stream in, pushing the executing cell upwards out of the viewport

https://github.com/microsoft/vscode/assets/12552271/f2800ad7-d264-43b7-8d4e-dfc20e67c544

- shift-enter set to "fullCell" and next cell has a large output
  - focus shifts to next cell, and the viewport exposes the bottom of the output for that cell. there is no cell editor in the viewport
  - my thoughts:
    - "fullCell" behavior should show the top of the next cell editor at the top of the viewport

https://github.com/microsoft/vscode/assets/12552271/e182f393-4d86-4e2d-890c-2febc0a32547
