### ISSUE TITLE
Fix locale and language-dependent code in the product

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#169114]
The language pack recommender, especially on Windows, relies on the `app.getPreferredSystemLanguages()` API in order to properly recommend language packs.

The usage of that API has been temporarily reverted to fix the regression https://github.com/microsoft/vscode/issues/166936. The revert should also incidentally fix https://github.com/microsoft/vscode/issues/168583 and https://github.com/microsoft/vscode/issues/167871.

This issue looks into using that API again and the processing needed on the output to ensure that the results do not break any areas outside of the language recommender.

## TODO
- [x] Determine which users of `platform.locale` actually require the system locale, and which ones merely require the `language` variable.
- [x] Determine how the `language` variable is actually set. `platform.locale` is set either through `app.getLocale()` or `app.getPreferredSystemLanguages()[0]`.
- [ ] Modify the code as needed

**Comment by TylerLeonhardt** [comment]
> Determine how the language variable is actually set. platform.locale is set either through app.getLocale() or app.getPreferredSystemLanguages()[0].

`language` is set when you install a language pack or it's set to `en` by default.
