### ISSUE TITLE
Iteration Plan for January 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#170413]
This plan captures our work in **January**. This is a 4-week iteration. We will ship in early **February**. The release will also contain minor improvements and bug fixes that happened during our [December Housekeeping Iteration](https://github.com/microsoft/vscode/issues/168000).

## Endgame
- **January 23, 2023**: Endgame begins
- **January 27, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22January+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22January+2023%22) @meganrogge @isidorn **team**
- [x] Support arrow key navigation in Setting indicators [vscode#167470](https://github.com/microsoft/vscode/issues/167470) @rzhao271

### UX
- [x] Explore how to better express view display styles (tree versus list) [vscode#162595](https://github.com/microsoft/vscode/issues/162595) @daviddossett
- [ ] :runner: Explore updated built-in themes [vscode#164924](https://github.com/microsoft/vscode/issues/164924) @daviddossett
- [ ] :runner: Explore UI density modes  [vscode#115641](https://github.com/microsoft/vscode/issues/115641) @daviddossett
- [ ] :runner: Explore an integrated way to introduce unique vscode.dev behaviors  [vscode#166895](https://github.com/microsoft/vscode/issues/166895) @daviddossett @joyceerhl
- [ ] :runner: Introduce an experimental modal walkthrough for web experiences [vscode#171190](https://github.com/microsoft/vscode/issues/171190) @bhavyaus @joyceerhl
- [ ] :runner: Explore lightweight toast UI [vscode#166891](https://github.com/microsoft/vscode/issues/166891) @daviddossett @bpasero

### Workbench
- [x] Ship profiles [vscode#116740](https://github.com/microsoft/vscode/issues/116740) @sandy081
- [x] Improve performance of the Settings Editor [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+label%3Asettings-editor+label%3Aperf) @rzhao271
- [x] Allow glob patterns for native file watcher excludes [vscode#137872](https://github.com/microsoft/vscode/issues/137872) @bpasero
- [x] Add a confirmation to open large files behind a setting [vscode#170090](https://github.com/microsoft/vscode/issues/170090) @bpasero
- [x] Improve first time experience for command palette [vscode#169091](https://github.com/microsoft/vscode/issues/169091) @TylerLeonhardt @digitarald
- [x] Improve custom titlebar layout performance [vscode#169866](https://github.com/microsoft/vscode/pull/169866) @sbatten
- [x] Support keyboard-based trusting of a workspace [vscode#170310](https://github.com/microsoft/vscode/issues/170310) @sbatten
- [x] Improvements to Keyboard Shortcuts Editor [vscode#151599](https://github.com/microsoft/vscode/issues/151599) @sandy081
   - [x] Specify which extension provides a specific keyboard shortcut  [vscode#121673](https://github.com/microsoft/vscode/issues/121673) @sandy081
   - [x] Enhance filtering Keyboard Shortcuts with chords [vscode#80181](https://github.com/microsoft/vscode/issues/80181) @sandy081
   - [x] Keybinding UI editor should support context key suggestions [vscode#116855](https://github.com/microsoft/vscode/issues/116855) @sandy081

#### Continue-On
- [ ] :runner: Surface Continue-On in more places [vscode#165406](https://github.com/microsoft/vscode/issues/165406) @joyceerhl
- [x] Surface transitions in Remote Indicator [vscode#162259](https://github.com/microsoft/vscode/issues/162259) @joyceerhl
- [x] Add additional Continue-On transitions [vscode#162118](https://github.com/microsoft/vscode/issues/162118) @joyceerhl
- [x] Auto-publish unpublished branch state when invoking Continue Working On on desktop [vscode#160237](https://github.com/microsoft/vscode/issues/160237) @joyceerhl
- [x] Add a way to discover extensions which contribute Continue On options [vscode#165105](https://github.com/microsoft/vscode/issues/165105) @joyceerhl

#### WebAssembly Runtime Support
- [ ] :runner: :muscle: Explore provide a web-shell [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @dbaeumer @tyriar

### Code Editor
- [x] Suggest Mode for auto complete [#vscode/139825](https://github.com/microsoft/vscode/issues/139825) @jrieken
- [x] Partial suggestion acceptance - discoverability/keybinding [vscode#140708](https://github.com/microsoft/vscode/issues/140708) @hediet

### Notebook Editor
- [x] Drop `NotebookContentProvider` usage in the Interactive Window [vscode#165252](https://github.com/microsoft/vscode/issues/163377) @amunger @rebornix
- [x] Remove kernel preloads globals API [vscode#163513](https://github.com/microsoft/vscode/issues/163513) @mjbvz @DonJayamanne
- [ ] :runner: Enable scrollable notebook outputs [vscode-jupyter#7096](https://github.com/microsoft/vscode-jupyter/issues/7096) @amunger
- [x] Improve updating outputs when re-running a cell [vscode#132143](https://github.com/microsoft/vscode/issues/132143) @rebornix @roblourens
- [ ] :runner: Explore notebook specific list view and layout improvements [vscode#170881](https://github.com/microsoft/vscode/issues/170881) @rebornix @roblourens
- [ ] :runner: Explore a built-in variables viewer [vscode#165445](https://github.com/microsoft/vscode/issues/165445) @roblourens
- [ ] :runner: Allow searching dirty changes in open notebook editors in global search [vscode#95275](https://github.com/microsoft/vscode/issues/148068) @andreamah
- [ ] :runner: Allow searching rich content in notebooks in global search [vscode#164926](https://github.com/microsoft/vscode/issues/164926) @andreamah
- [ ] :runner: Explore how to stop hanging network request from preventing the opening of notebooks [vscode#166860](https://github.com/microsoft/vscode/issues/166860) @mjbvz
- [ ] :runner: Explore localization support for notebook renderers [vscode#170919](https://github.com/microsoft/vscode/issues/170919) @TylerLeonhardt @mjbvz
- [ ] :runner: Explore UX to surface common notebook renderer performance issues [vscode#170309](https://github.com/microsoft/vscode/issues/170309) @sbatten @rebornix

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#12474](https://github.com/microsoft/vscode-jupyter/issues/12474) **team**

#### Python
- [x] Contributions to the python extension [vscode-python#20450](https://github.com/microsoft/vscode-python/issues/20450) @brettcannon **team**

##### Python WebAssembly Runtime Support
- [ ] :muscle: [Explore support for statically linking and loading native modules](https://github.com/microsoft/vscode-wasm/issues/35) @dbaeumer @brettcannon
- [x] Strategy for testing packages against CPython WASI - work across CPython and VS Code; [python doc issue](https://github.com/python/cpython/issues/100956), [pytest issue](https://github.com/pytest-dev/pytest/issues/10670) [wasm-wasi issue](https://github.com/microsoft/vscode-wasm/issues/4); @brettcannon @dbaeumer
- [ ] :runner: How do users find packages that work in CPython WASI? [issue](https://github.com/microsoft/vscode-python-web-wasm/issues/42); @brettcannon
- [ ] :muscle: [Explore support for notebooks](https://github.com/microsoft/vscode-wasm/issues/36) @dbaeumer

#### JavaScript/TypeScript
- [ ] :runner: Project-wide IntelliSense on the web [vscode#170920](https://github.com/microsoft/vscode/issues/170920) @mjbvz

### Debug Adapter Protocol
- [ ] :runner: Memory reuse [debug-adapter-protocol#238](https://github.com/microsoft/debug-adapter-protocol/issues/238) @connor4312 @roblourens
- [x] Clarify combination of log point and conditional breakpoint [debug-adapter-protocol#363](https://github.com/microsoft/debug-adapter-protocol/issues/363) @roblourens

### Testing
- [x] Auto run tests [vscode#134941](https://github.com/microsoft/vscode/issues/134941) @connor4312

### Terminal
- [ ] :runner: Support external terminals as a default for WSL sessions [vscode#167865](https://github.com/microsoft/vscode/issues/167865) @tyriar
- [x] Provide Quick Fixes for new `pwsh` feedback provider apis [vscode#170484](https://github.com/microsoft/vscode/issues/170484) @tyriar
- [x] Fix env var collection on macOS [vscode#99878](https://github.com/microsoft/vscode/issues/99878) @tyriar
- [ ] :runner: Continue `pwsh` autocomplete [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar
- [x] Explore UX and API for a proper Co-pilot integration [vscode#170485](https://github.com/microsoft/vscode/issues/170485) @tyriar

### Tasks
- [x] Address paper cuts [vscode#167061](https://github.com/microsoft/vscode/issues/167061) @meganrogge

### Source Control
- [ ] :runner: Git: Performance work [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Alszomoru+label%3Agit+label%3Aperf) @lszomoru
- [ ] :runner: Git: Prompt before opening repos outside workspace [vscode#169256](https://github.com/microsoft/vscode/issues/169256) @lszomoru

### API
- [ ] :muscle: Allow `FileSystemProviders` to set the read-only file message [vscode#166971](https://github.com/microsoft/vscode/issues/166971) @jrieken
- [ ] :runner: Support `QuickDiffProvider` without SourceControl registration [vscode#169012](https://github.com/microsoft/vscode/issues/169012) @alexr00
- [x] Finalize Telemetry API for extension authors [vscode#160090](https://github.com/microsoft/vscode/issues/160090) @lramos15 @jrieken
- [x] API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [x] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz

### Extensions
- [x] Launch Extension Repository Signing to Stable [vscode#169550](https://github.com/microsoft/vscode/issues/169550) @isidorn @dtivel @sandy081
- [x] Lint redundant explicitly listed activation events in `package.json` [vscode#170984](https://github.com/microsoft/vscode/issues/170984) @joyceerhl
- [x] Support pinning extension version when installed from CLI [vscode#63903](https://github.com/microsoft/vscode/issues/63903) @sandy081
- [x] Supporting syncing specific extension installed version [vscode#157079](https://github.com/microsoft/vscode/issues/157079) @sandy081
- [x] Allow translations for language servers [vscode#168594](https://github.com/microsoft/vscode/issues/168594) @TylerLeonhardt

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#7783](https://github.com/microsoft/vscode-remote-release/issues/7783) @eleanorjboyd @chrmarti @aeschli
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/24) @joyceerhl @bhavyaus
- [x] Live Preview: Add option to specify which external browser [vscode-livepreview#69](https://github.com/microsoft/vscode-livepreview/issues/69) @andreamah
- [x] Live Preview: Add option to specify the root path of the server [vscode-livepreview#155](https://github.com/microsoft/vscode-livepreview/issues/155) @andreamah
- [ ] :runner: Fix preview of forwarded ports in Codespaces for Simple Browser and Live Preview [vscode-livepreview#111](https://github.com/microsoft/vscode-livepreview/issues/111) @andreamah @mjbvz
- [x] Support GitHub's suggested changes [vscode-pull-request-github#603](https://github.com/microsoft/vscode-pull-request-github/issues/603) @alexr00
- [x] Support setting labels on PRs at creation time [vscode-pull-request-github#2436](https://github.com/microsoft/vscode-pull-request-github/issues/2436) @alexr00
- [ ] :runner: Support permalink rendering [vscode-pull-request-github#4229](https://github.com/microsoft/vscode-pull-request-github/issues/4229) @alexr00
- [x] Move `js-debug` to l10n API [vscode#164438](https://github.com/microsoft/vscode/issues/164438) @connor4312 @tylerleonhardt

### Performance
- [x] Investigate moving away from the styler pattern [vscode#165478](https://github.com/microsoft/vscode/issues/165478) @aeschli
- [x] Why is the npm extension using `workspaceContains:package.json`? [vscode#163480](https://github.com/microsoft/vscode/issues/163480) @joyceerhl
- [ ] :runner: Explore `setTimeout` for `onStartupFinished` extensions [vscode#164593](https://github.com/microsoft/vscode/issues/164593) @joyceerhl
- [ ] :runner: :muscle: Explore delaying doing * activation extensions until initial activation events are finished [vscode#171135](https://github.com/microsoft/vscode/issues/171135) @joyceerhl
- [x] Investigate slow stacks reported to telemetry & ramp up the experiment [vscode#170954](https://github.com/microsoft/vscode/issues/170954)  @jrieken
- [x] Add detailed telemetry for RPC payloads with large serialization/deserialization times [vscode#170955](https://github.com/microsoft/vscode/issues/170955) @jrieken @alexdima
- [ ] :runner: VSCode Perf Tool - Tool to measure performance of VSCode [vscode-perf#1](https://github.com/microsoft/vscode-perf/issues/1) @bpasero @sandy081
- [ ] :black_large_square: PGO for VSCode Desktop [vscode#170931](https://github.com/microsoft/vscode/issues/170931) @deepak1556

### Engineering
- [ ] :runner: Explore migrating from AMD to ESM [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken @alexdima
- [ ] :runner: Sandboxing: Investigate increased extension host crash rate in stable @bpasero @deepak1556 @digitarald
- [x] Investigate insiders startup regression [vscode#168639](https://github.com/microsoft/vscode/issues/168639) @jrieken @bpasero @sandy081
- [x] Sandbox: enable utility process by default in stable @bpasero

#### Electron
- [x] Investigate Electron 22 upgrade [vscode#166265](https://github.com/microsoft/vscode/issues/166265) @deepak1556
- [x] Drop support for macOS 10.11 [vscode#123374](https://github.com/microsoft/vscode/issues/123374) @deepak1556
- [x] Screen reader not detected on macOS [vscode#167627](https://github.com/microsoft/vscode/issues/167627) @deepak1556
- [x] Native crash in macOS smoke tests [vscode#168415](https://github.com/microsoft/vscode/issues/168415) @deepak1556
- [x] Crash when closing active macOS native tab [vscode#167936](https://github.com/microsoft/vscode/issues/167936) @deepak1556
- [x] Fix locale and language-dependent code in the product [vscode#169114](https://github.com/microsoft/vscode/issues/169114) @rzhao271 @TylerLeonhardt

### Documentation
- [ ] :runner: Update Azure Content, ToC [vscode-docs#5614](https://github.com/microsoft/vscode-docs/issues/5614) @gregvanl @isidorn
- [x] Restructure and refresh dev containers docs within new Dev Containers node [vscode-docs#5737](https://github.com/microsoft/vscode-docs/issues/5737) @bamurtaugh @gregvanl

----
### Deferred
- [ ] Support an RTL layout of the titlebar based on WCO [vscode#164397](https://github.com/microsoft/vscode/issues/164397) @sbatten
- [ ] Explore improvements to the extensions list [vscode#151599](https://github.com/microsoft/vscode/issues/151599) @esonnino @sandy081
- [ ] Update source control documentation to include the merge editor [vscode-docs#5618](https://github.com/microsoft/vscode-docs/issues/5618) @hediet @gregvanl
- [ ] Add an Git introductory page [vscode-docs#5677](https://github.com/microsoft/vscode-docs/pull/5677) @digitarald
- [ ] Investigate large screen update under remote desktop [vscode#164503](https://github.com/microsoft/vscode/issues/164503) @deepak1556
- [ ] Improving the developer experience for the CLI within the vscode repo [vscode#171515](https://github.com/microsoft/vscode/issues/171515) @connor4312 @aeschli
- [ ] Sandboxing: Adopt utility process for shared process, file watchers and terminal host [vscode#154050](https://github.com/microsoft/vscode/issues/154050) @bpasero @deepak1556 @Tyriar
- [ ] Git: Support untracked folders [vscode#169253](https://github.com/microsoft/vscode/issues/169253) @lszomoru
- [ ] Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [ ] Move background tokenization to a web worker [vscode#147066](https://github.com/microsoft/vscode/issues/147066) @hediet
- [ ] Support coloring a subset of the matched brackets [vscode#170497](https://github.com/microsoft/vscode/issues/170497) @hediet
- [ ] Publish new Monaco Editor website with improved playground [monaco-editor#3483](https://github.com/microsoft/monaco-editor/issues/3483) @hediet
- [ ] Publish new Monaco Editor version [CHANGELOG.md](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md) @hediet
- [ ] Evaluate iPad support [vscode#170498](https://github.com/microsoft/vscode/issues/170498) @hediet
- [ ] Provide built-in Profiles [vscode#166359](https://github.com/microsoft/vscode/issues/166359) @isidorn @sandy081
- [ ] :red_circle: :runner: Explore surfacing the remote experiences on the welcome page @bhavyaus
- [ ] Improve introduction to Command Palette in get started walkthrough [vscode#166735](https://github.com/microsoft/vscode/issues/166735) @esonnino @bhavyaus
- [ ] Improvements to Getting Started experience [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Abhavyaus+milestone%3A%22January+2023%22+label%3Abug) @bhavyaus
- [ ] Convert LSIF to the new npm publish pipeline [#3191](https://github.com/microsoft/vscode-internalbacklog/issues/3191) @dbaeumer
- [ ] Explore possibility of unifying explorer selection in focus behind a setting @lramos15
- [ ] :runner: White flashing when opening a new window [vscode#132339](https://github.com/microsoft/vscode/issues/132339) @rzhao271 @deepak1556
- [ ] :muscle: Explore ways to improve interacting with root files and folders in a crowded explorer view @lramos15 [vscode#151630](https://github.com/microsoft/vscode/issues/151630)\
- [ ] :muscle: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz
- [ ] SCM: Notification API [vscode#161200](https://github.com/microsoft/vscode/issues/161200) @lszomoru
- [ ] Support profiles in remote workspaces [vscode#165247](https://github.com/microsoft/vscode/issues/165247) @sandy081
- [ ] Finalize or remove the `notebookControllerKind` API Proposal [vscode#168535](https://github.com/microsoft/vscode/issues/168535) @mjbvz @rebornix
