### ISSUE TITLE
Enhance Copy/Update action in Settings editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#17292]
Current copy/update action has following issues

- [x] [Display the edit icon in settings with a small delay](https://github.com/Microsoft/vscode/issues/16802)
- [x] [dropdown decorator only works for first setting with multiple settings on a single line](https://github.com/Microsoft/vscode/issues/16458)
- [x] [action decoration in settings file makes it hard to put cursor at end of line](https://github.com/Microsoft/vscode/issues/16457)
- [x] [Settings: Edit icon off by a few pixels](https://github.com/Microsoft/vscode/issues/16698)
- [x] [Clicking edit icon in editable settings.json scrolls horizontally](https://github.com/Microsoft/vscode/issues/16714)
- [x] [New settings "copy to settings" drop down is clunky](https://github.com/Microsoft/vscode/issues/16711)
- [x] ["Copy to Settings" overwrites existing value](https://github.com/Microsoft/vscode/issues/16728)

**Comment by sandy081** [comment]
@bgashler1 Listed in the description are the issues with Edit icon in Settings editor. Most of them are usability issues. Hence, I have done following changes to the edit icon

- Moved and placed edit icon to the Glyph margin just like Light bulb. This will make action to be consistent. 
- Icon is visible when the cursor is in setting or when mouse is hovered on setting (includes description, value)
- Used line highlights when 
a. Hovering on icon
b. On copying the setting 
- When there are more than one setting in a line, used sub context menu. 

Looks like there is no UX call today hence showing the video here

![jan-04-2017 13-48-41](https://cloud.githubusercontent.com/assets/10746682/21642736/a669a9c0-d284-11e6-94fd-0baf7d4ef037.gif)

Feedback is welcome.

Thanks

**Comment by bgashler1** [comment]
@sandy081 this is great 👍 nice work!  I love the consistency parallel you introduced.  I can't wait to try it out.

One other thing that would be cool to have is that if you scroll down the search box could become fixed at the top (but first letting you scroll passed the header/description above it).
![screen shot 2017-01-04 at 3 50 31 pm](https://cloud.githubusercontent.com/assets/11839736/21663522/95f18bec-d295-11e6-9473-37820ffb7e4d.png).
What do you think?
