### ISSUE TITLE
Iteration Plan for February 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#173445]
This plan captures our work in **February**. This is a 4-week iteration. We will ship in early **March**.

## Endgame
- **February 20, 2023**: Endgame begins
- **February 24, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22February\+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22February+2023%22) @meganrogge @isidorn **team**

### UX
- [ ] :runner: Refine updated built-in themes [vscode#164924](https://github.com/microsoft/vscode/issues/164924) @daviddossett
- [x] Explore UI density modes [vscode#115641](https://github.com/microsoft/vscode/issues/115641) @daviddossett
- [ ] :runner: Introduce an experimental modal welcome for web experiences [vscode#171190](https://github.com/microsoft/vscode/issues/171190) @bhavyaus @joyceerhl @daviddossett
- [ ] :runner: Explore improvements to the extensions list [vscode#151599](https://github.com/microsoft/vscode/issues/151599) @esonnino @sandy081

### Workbench
- [ ] :runner: Explore built-in Profiles [vscode#166359](https://github.com/microsoft/vscode/issues/166359) @isidorn @sandy081
- [x] Support profiles in remote workspaces [vscode#165247](https://github.com/microsoft/vscode/issues/165247) @sandy081
- [ ] :runner: Explore surfacing the remote experiences on the welcome page [vscode#173396](https://github.com/microsoft/vscode/issues/173396) @bhavyaus
- [x] Explore UI for new file snippets [vscode#173729](https://github.com/microsoft/vscode/issues/173729) @ulugbekna @jrieken
- [x] Support making the explorer moveable to other parts [vscode#173388](https://github.com/microsoft/vscode/issues/173388) @lramos15
- [x] Support an RTL layout of the titlebar based on WCO [vscode#164397](https://github.com/microsoft/vscode/issues/164397) @sbatten
- [ ] :runner: Support parenthesis in context keys [vscode#91473](https://github.com/microsoft/vscode/issues/91473) @ulugbekna @jrieken
- [ ] :runner: Triage & address sticky scroll issues [vscode#174259](https://github.com/microsoft/vscode/issues/174259) @aiday-mar @aeschli
- [x] Allow `showOpenDialog` to open local files on web [vscode#131138](https://github.com/microsoft/vscode/issues/131138) @alexr00
- [x] Support changing the default log level for core & extensions [vscode#173120](https://github.com/microsoft/vscode/issues/173120) @sandy081
- [x] Persist badge visibility across reloads and view movement [vscode#168939](https://github.com/microsoft/vscode/issues/168939) @lramos15
- [x] Add support for links in quick pick input validation messages [vscode#82112](https://github.com/microsoft/vscode/issues/82112) @TylerLeonhardt
- [x] Add support for hover messages on quick pick items [vscode#174473](https://github.com/microsoft/vscode/issues/174473) @TylerLeonhardt

#### WebAssembly Runtime Support
- [x] Continue to increase test coverage for the VS Code WASI implementation [vscode-wasm#4](https://github.com/microsoft/vscode-wasm/issues/4) @dbaeumer
- [ ] :muscle: Explore provide a web-shell [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @dbaeumer @tyriar

### Code Editor
- [x] Monaco editor housekeeping [monaco-editor inbox query](https://github.com/microsoft/monaco-editor/issues?q=is%3Aissue+is%3Aopen+-label%3Afeature-request+-label%3Aquestion+-label%3Aupstream+-label%3A%22help+wanted%22+-label%3A%22info-needed%22+-label%3A%22as-designed%22+-label%3Abug+-label%3A*question+) @hediet
- [x] Publish new Monaco Editor version [CHANGELOG.md](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md) @hediet
- [x] iPad: Trackpad scroll doens't work in vscode.dev [vscode#164220](https://github.com/microsoft/vscode/issues/164220) @hediet
- [x] Move background tokenization to a web worker [vscode#147066](https://github.com/microsoft/vscode/issues/147066) @hediet
- [x] Support union brackets (build the tree out of both colorized brackets and matched brackets) [vscode#170497](https://github.com/microsoft/vscode/issues/170497) @hediet
- [x] Publish new Monaco Editor website with improved playground [monaco-editor#3483](https://github.com/microsoft/monaco-editor/issues/3483) @hediet

### Notebook Editor
- [x] Explore UX to surface common notebook renderer performance issues [vscode#170309](https://github.com/microsoft/vscode/issues/170309) @sbatten @rebornix
- [ ] :runner: Polish and enable scrollable notebook outputs [vscode-jupyter#4406](https://github.com/microsoft/vscode-jupyter/issues/4406) @amunger
- [x] Wrong horizontal scrollbar calculation on initial load [vscode#167806](https://github.com/microsoft/vscode/issues/167806) @rebornix @alexdima
- [ ] :runner: Explore how to stop hanging network request from preventing the opening of notebooks [vscode#166860](https://github.com/microsoft/vscode/issues/166860) @mjbvz
- [ ] :runner: Introduce global search options for open notebooks [vscode#164926](https://github.com/microsoft/vscode/issues/164926) @andreamah
- [ ] :runner: Explore smart global search for notebooks in the workspace [vscode#173726](https://github.com/microsoft/vscode/issues/173726) @andreamah
- [ ] :muscle: Align closing behavior of the Interactive Window with Untitled Files [vscode#172974](https://github.com/microsoft/vscode/issues/172974) @amunger

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#12734](https://github.com/microsoft/vscode-jupyter/issues/12734) **team**

#### Python
- [x] Contributions to the python extension [vscode-python#20648](https://github.com/microsoft/vscode-python/issues/20648) @brettcannon **team**

##### Python WebAssembly Runtime Support
- [ ] :runner: [Explore support for statically linking and loading native modules](https://github.com/microsoft/vscode-wasm/issues/35) @dbaeumer @brettcannon
- [ ] :runner: :black_large_square: How do users find packages that work in CPython WASI? [issue](https://github.com/microsoft/vscode-python-web-wasm/issues/42); @brettcannon
- [x] [Explore support for notebooks](https://github.com/microsoft/vscode-wasm/issues/36) @dbaeumer

#### JavaScript/TypeScript
- [ ] :runner: Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Project-wide IntelliSense on the web [vscode#170920](https://github.com/microsoft/vscode/issues/170920) @mjbvz
- [x] Explore LSIF support for TS v5 @dbaeumer [Branch dbaeumer/ts5.0](https://github.com/microsoft/lsif-node/tree/dbaeumer/ts5.0)

#### JSON
- [x] Sort JSON properties alphabetically [vscode#155312](https://github.com/microsoft/vscode/issues/155312) @aiday-mar @aeschli

### Localization
- [x] Display language change not taking effect for extensions running in remote extension host [vscode#166836](https://github.com/microsoft/vscode/issues/166836) @TylerLeonhardt

#### Debug Adapter Protocol
- None.

### Testing
- None.

### Terminal
- [ ] :runner: Support external terminals as a default for WSL sessions [vscode#167865](https://github.com/microsoft/vscode/issues/167865) @tyriar
- [ ] :runner: Continue `pwsh` autocomplete [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar

### Tasks
- None.

### Source Control
- None.

### API
- [x] API finalization: [query](https:/github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February\+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [x] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February\+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] Support `QuickDiffProvider` without SourceControl registration [vscode#169012](https://github.com/microsoft/vscode/issues/169012) @alexr00
- [x] Expose folding regions through executeFoldingRangeProvider [vscode#36638](https://github.com/microsoft/vscode/issues/36638) @aeschli
- [x] Support comma-separated globs in `findTextInFiles` API [vscode#169422](https://github.com/microsoft/vscode/issues/169422) @andreamah
- [ ] :hand: Finalize or remove the `notebookControllerKind` API Proposal [vscode#168535](https://github.com/microsoft/vscode/issues/168535) @mjbvz @rebornix

### Extensions
- None.

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#7972](https://github.com/microsoft/vscode-remote-release/issues/7972) @eleanorjboyd @chrmarti @aeschli @joyceerhl
- [x] Support permalink rendering [vscode-pull-request-github#4229](https://github.com/microsoft/vscode-pull-request-github/issues/4229) @alexr00
- [x] Ability to re-request a review from the PR description page [vscode-pull-request-github#4092](https://github.com/microsoft/vscode-pull-request-github/issues/4092) @alexr00
- [ ] :runner: Exploration: Re-think PR creation flow [vscode-pull-request-github#4403](https://github.com/microsoft/vscode-pull-request-github/issues/4403) @alexr00 @daviddossett
- [x] Adopt new log level API [vscode-pull-request-github#4490](https://github.com/microsoft/vscode-pull-request-github/issues/4490) @alexr00

### Performance
- [ ] :runner: Defer `onStartupFinished` activation [vscode#164593](https://github.com/microsoft/vscode/issues/164593) @joyceerhl
- [x] VSCode Perf Tool - Tool to measure performance of VSCode [vscode-perf#1](https://github.com/microsoft/vscode-perf/issues/1) @bpasero @sandy081
- [ ] :black_large_square: :hand: PGO for VSCode Desktop [vscode#170931](https://github.com/microsoft/vscode/issues/170931) @deepak1556
- [ ] :red_circle: :muscle: Investigate slow stacks reported to telemetry, ramp up the experiment @jrieken
- [ ] :runner: Log sizes of extension host telemetry messages [vscode#170955](https://github.com/microsoft/vscode/issues/170955) @jrieken

### Install
- [ ] :runner: Update snap package to use `base:` [vscode#119436](https://github.com/microsoft/vscode/issues/119436) @deepak1556
- [ ] :muscle: Linux: Ship RPM packages for EL8/EL9 alongside EL7 [vscode#144969](https://github.com/microsoft/vscode/issues/144969) @deepak1556

### Engineering
- [x] Adopt generating implicit activation events [vscode#172869](https://github.com/microsoft/vscode/issues/172869) @bhavyaus @meganrogge @tyriar @rebornix @team
- [ ] :runner: Explore migrating from AMD to ESM [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken @alexdima
- [ ] :runner: :black_large_square: Sandboxing: Adopt utility process for shared process, file watchers and terminal host [vscode#154050](https://github.com/microsoft/vscode/issues/154050) @bpasero @deepak1556 @Tyriar
- [ ] :red_circle: :runner: Sandboxing: Investigate increased extension host crash rate in stable @bpasero @deepak1556 @digitarald

#### Electron
- [ ] :runner: Update to Electron 22 [vscode#166265](https://github.com/microsoft/vscode/issues/166265) @deepak1556 @bpasero @rzhao271
- [ ] Orca can't be stopped in native dialogs [vscode#121811](https://github.com/microsoft/vscode/issues/121811) @deepak1556
- [ ] Right Click acting abnormal [vscode#113175](https://github.com/microsoft/vscode/issues/113175) @deepak1556

### Documentation
- [ ] :runner: Profiles topic/section [vscode-docs#6020](https://github.com/microsoft/vscode-docs/issues/6020) @gregvanl @sandy081
- [ ] :runner: Add an Git introductory page [vscode-docs#5677](https://github.com/microsoft/vscode-docs/pull/5677) @digitarald

----
### Deferred
- [ ] Revisit TOC selection behavior in the settings editor when searching [vscode#170462](https://github.com/microsoft/vscode/issues/170462) @rzhao271
- [ ] Fix scroll jumping issue in settings editor [vscode#170462](https://github.com/microsoft/vscode/issues/170462) @rzhao271
- [ ] Defer eager activation events till initial events have settled [vscode#171135](https://github.com/microsoft/vscode/issues/171135) @joyceerhl
- [ ] Update source control documentation to include the merge editor [vscode-docs#5618](https://github.com/microsoft/vscode-docs/issues/5618) @gregvanl @hediet
- [ ] Explore notebook specific list view and layout improvements [vscode#170881](https://github.com/microsoft/vscode/issues/170881) @rebornix @roblourens
- [ ] Clarify requirement for unique variable names [debug-adapter-protocol#141](https://github.com/microsoft/debug-adapter-protocol/issues/141) @roblourens
- [ ] Add ‘singleThread’ argument to pause requests [debug-adapter-protocol#355](https://github.com/microsoft/debug-adapter-protocol/issues/355) @roblourens
- [ ] Continue request shouldn’t fall back on continuing all threads [debug-adapter-protocol#221](https://github.com/microsoft/debug-adapter-protocol/issues/221) @roblourens
- [ ] :runner: Explore a built-in variables viewer [vscode#165445](https://github.com/microsoft/vscode/issues/165445) @roblourens
- [ ] :runner: Surface Continue-On in more places [vscode#165406](https://github.com/microsoft/vscode/issues/165406) @joyceerhl
- [ ] :runner: Memory reuse [debug-adapter-protocol#238](https://github.com/microsoft/debug-adapter-protocol/issues/238) @connor4312 @roblourens
- [ ] Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [ ] Improving the developer experience for the CLI within the vscode repo [vscode#171515](https://github.com/microsoft/vscode/issues/171515) @aeschli @connor4312
- [ ] Improvements to Getting Started experience [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Abhavyaus+milestone%3A%22February\+2023%22+label%3Abug) @bhavyaus
- [ ] :muscle: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz
- [ ] Git: Support untracked folders [vscode#169253](https://github.com/microsoft/vscode/issues/169253) @lszomoru
- [ ] :hand: :runner: Fix preview of forwarded ports in Codespaces for Simple Browser and Live Preview [vscode-livepreview#111](https://github.com/microsoft/vscode-livepreview/issues/111) @andreamah @mjbvz
- [ ] :runner: Explore localization support for notebook renderers [vscode#170919](https://github.com/microsoft/vscode/issues/170919) @TylerLeonhardt @mjbvz
- [ ] :runner: Update Azure Content, ToC [vscode-docs#5614](https://github.com/microsoft/vscode-docs/issues/5614) @gregvanl @isidorn
- [ ] Investigate large screen update under remote desktop [vscode#164503](https://github.com/microsoft/vscode/issues/164503) @deepak1556

**Comment by sanket-bhalerao** [comment]
could you please have a look at https://github.com/microsoft/vscode/issues/173258?
vscode is unusable due to this
I have already tried to disable all extensions,
reinstalled the vscode

**Comment by Ssiswent** [comment]
`Explore UI density modes`
This has been finished?
