### ISSUE TITLE
January Iteration Plan

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#17608]
This plan captures what we work on during second halve of December and January. We will ship **early February**.

The endgame for this iteration is tracked in #19031

## Plan Items

Below is a summary of the top level plan items.

Legend for annotations:

| Mark  | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Themes
- performance
- discoverability
- UI scalability
- Expand API

### Workbench
- [x] Improve discoverability of panels and explore the use of tabs for switching among panels #18078 @bpasero 
- [x] File type/language specific settings #1587 @sandy081 
- [x] Initial investigation into `multi root workspaces`  @waderyan 
- [x] Investigate int Welcome experience  #18091 @chrmarti 
- [x] Support to run tasks in the integrated terminal #15584, #18312 @dbaeumer @Tyriar 
- [x] Polish settings experience (searching, sorting, actions, layout, switching between user/workspace settings) #18094 @sandy081 @bgashler1 
- [x] Terminal: Improve Windows support #13625 @Tyriar
- [x] Terminal: Improve performance #17875 @Tyriar
- [x] Explore Hot Exit strategies when switching between folders and how to configure them #15467 @Tyriar 
- [x] Improve keyboard navigability for Search results #17324 @roblourens 

### Editor
- [x] Adopt new TextMate Scope representation #18317 @alexandrudima
- [x] Tooling for grammar authors (see also the scope extension) #18068 @alexandrudima
- [x] Ship updated monaco editor (depends on TextMate Scope adoption) @alexandrudima
- [x] Investigate in mini map support @alexandrudima
- Auto indent support #17868 
  - [x] Improve auto indent on enter for languages like Ruby @rebornix
  - [x] :runner: Add 'Reindent all Lines' command #18958 @rebornix
- [x] Format on Paste (setting) #13945 @rebornix @jrieken
- [x] Monaco editor: remove IE9 and IE10 support  #18057 @rebornix @alexandrudima

### Languages
- Language protocol
  - [x] Version 3 of the language server protocol [#140](https://github.com/Microsoft/vscode-languageserver-node/issues/140)@dbaeumer
- Markdown
  - [x] Synchronized scrolling in markdown preview #5047 @mjbvz  
- Emmet
  - [x] Add support for loading emmet preferences, profiles and snippets from external files #11679 @ramya-rao-a 
- SCSS 
  - [x] Add support for the map syntax #1758 @aeschli
- TypeScript/JavaScript
  - [x] ATA UI improvements #15209 @mjbvz @jrieken 
  - [x] TS 2.1.5 adoption #18052 @mjbvz 
  - [x] Reference code lens :hand: on some TS issues #18054 @mjbvz 

### Extensions

- [x] Disable an extension pack #16666 @sandy081
- [x] Add extension packs category #18056 @waderyan  
- [x] Add a yeoman generator for an extension pack @egamma
- [x] Dynamic extension recommendation improvement (add language ID and extension ID) #18147 @joaomoreno @waderyan

### Debugging

- Just my code UI
  - [x] Support node core modules (introduce magic path) #16918 @weinand @isidorn 
  - [x] Introduce 'deemphasize' style of Source objects in CALL STACK view #18396 @isidorn @weinand 
  - [x] extension based implementation #14728 @roblourens @isidorn
- [x] Support 'restart' option for 'launch' requests #17381 @weinand 
- [x] Improvements and adoptions of printing objects in the debug console https://github.com/Microsoft/vscode-chrome-debug-core/issues/145 @roblourens  @isidorn 
- [x] Enable source maps by default to simplify configuration https://github.com/Microsoft/vscode-chrome-debug-core/issues/134 @roblourens @weinand  
- [x] Show inline values in source when stepping #13424 @isidorn  
- [x] Review and assess user testing feedback, explore improvements to simplify setup #18098 @weinand @isidorn @roblourens 
   - [x] Explore support to launch/debug single files when there is no project folder and no launch.json #285 @isidorn @weinand
   - [x] Revisit the 'add configuration' button UI to add a configuration snippet #18359 @isidorn 
- [x] Add launch config snippets for common node scenarios #18776 @weinand

### Extension Authoring
- Source Control provider API #15894 @joaomoreno
  - [x] Provide preview of Git support running from an extension #18615
- [x] Debug - support to launch an adapter through an extension #8645 @weinand @isidorn
- [x] Leverage TS support for readonly properties in API (replace readonly doc annotation) #12732 @jrieken
- [x] Progress API #18066 @jrieken

### Contributions to Extensions
- [x] php parser adoption and completion #15818 @mousetraps 
- [x] TSLint support to selectively enable JS validation https://github.com/Microsoft/vscode-tslint/issues/149 @egamma
- [x] Go - add telemetry https://github.com/Microsoft/vscode-go/issues/646 @ramya-rao-a
- [x] Go - Explore Go language server seeded by SourceGraph https://github.com/Microsoft/vscode-go/issues/706 @ramya-rao-a 
- [x] Go - Implement Step Out feature in debugging @ramya-rao-a

### Engineering
- Performance
  - [x] Continue work on startup performance #15455 @jrieken @bpasero
  - [x] Invest into tools for measuring the startup performance #18087 @jrieken
  - [x] Enable that a user can easily report a startup perf problem. #18080 @bpasero
- [x] Proxy support - provide setup so that community can help us with proxy testing #18103 @joao
- [x] Explore what it takes to ship VS Code as a UWP application #15820 @bpasero 
- Telemetry
  - [x] Add metrics like last 7/28 day active and last active day for events like File read/write by mime type, extension activation, core feature usage and type of workspace @ramya-rao-a

### Documentation
- [x] Docathon Microsoft/vscode-docs#702

### Deferred
23/01

- Improve exception experience #16860 @weinand @isidorn
- Column break points #14784 @isidorn @weinand 
- Auto indent: auto indent lines when moving them up/down @rebornix
---
17/01

- Keyboard layout improvements #17521 @alexandrudima
- :hand: Support large extension, adopt new marketplace support #18146 @joaomoreno
- Additional  theming options in the workbench  #3112 @bpasero @aeschli
- :hand: Linux auto update/auto signing #229 #2973 @Tyriar 
- Investigate in applying the Settings UI improvements to keybinding customization #18095 @sandy081 @bgashler1 
- ESLint support multi-round auto fixes [#154](https://github.com/Microsoft/vscode-eslint/issues/154)@dbaeumer
- Adopt new Status Codes APIs for Intellisense #15454 @jrieken
- Adopt cancellation token support #18053 @mjbvz

**Comment by shanalikhan** [comment]
Please add https://github.com/Microsoft/vscode/issues/14444 and https://github.com/Microsoft/vscode/issues/12178 also. My [code settings sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) is waiting for these features to give full results 😄 

Thanks

**Comment by joh** [comment]
Suspect I was mentioned here by mistake (I have no affiliation with this project).

**Comment by LiPengfei19820619** [comment]
Would you please add "provide setting file text encoding API to extensions" to the plan?
Thanks.

**Comment by egamma** [comment]
@joh fixed... sorry, but we always welcome contributions 😄

**Comment by egamma** [comment]
@LiPengfei19820619 thanks for your comment, but remember that commenting on the iteration plan is not the best way to make a feature request. Please see our [guidelines](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions)

**Comment by buzzzzer** [comment]
@egamma @LiPengfei19820619`s comment its not FR, its heart-cry )))
When the source code in different encodings different from utf*, development on vs turns into hell,but we still love it.

p.s. sorry for flood

**Comment by egamma** [comment]
@buzzzzer @LiPengfei19820619 I understand and I'm glad you still like VS Code. This sounds like #5388 and you can vote on this issue over there.

**Comment by felixfbecker** [comment]
I appreciate your investments in a new parser, but you could help the PHP folks a lot more for the time being if you just added the simple ability to disable the built-in PHP completion (https://github.com/Microsoft/vscode/issues/9003) so I can finally release completion support in my extension, which I have been holding off for over a month now because it has no benefit if VS Code spams the completion list with hundreds of suggestions that don't make sense in the context. Please consider adding this to the Jan release. @mousetraps

**Comment by equinusocio** [comment]
Any detailed informations about this?

>**Themes**
>
>- performance
>- discoverability
>- UI scalability
>- Expand API

**Comment by egamma** [comment]
Closing the January update is shipped

@equinusocio pls see the release notes for more detail.

**Comment by Kutsan** [comment]
And that's not what we want #3112.

**Comment by equinusocio** [comment]
I agree with @Kutsan. We want a customizable workbench (css and colors). As a theme developers we need more extensibility... The UX here can be widely improved.

**Comment by teesloane** [comment]
Hey folks - 

Just wanted to say excellent work on shipping this release. I know these issues are meant for tracking change, feedback and so on—but I couldn't help but say that I appreciate all your hard work and effort! You folks are doing great work and I look forward to what comes next!

**Comment by skbolton** [comment]
I like that @equinusocio is talking about this because I love his original Material theme (the greenish background) and I suspect he hasn't implemented it in vscode because of the color clash that would occur with vscode's outer ui. I love my text editor to look great and as silly as it is this is why I don't use vscode for more than a couple of minutes. The themes are locked into black or white background or clash with vscode ui

**Comment by bpasero** [comment]
That is covered in #3112
