### ISSUE TITLE
Iteration Plan for March 2023 [DRAFT]

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#176147]
This plan captures our work in **March**. This is a 4-week iteration. We will ship in early **April**.

## Endgame
- **March 20, 2023**: Endgame begins
- **March 24, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22March\+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] Dynamically update the terminal accessible buffer [vscode#172582](https://github.com/microsoft/vscode/issues/172582) @meganrogge
- [ ] Add symbol provider for terminal accessible buffer [vscode#174079](https://github.com/microsoft/vscode/issues/174079) @meganrogge
- [ ] :red_circle: Explore improvindg accessibility for inline completions @hediet @meganrogge
- [x] Command palette placeholder text accessibility [vscode#166920](https://github.com/microsoft/vscode/issues/166920) @tylerleonhardt
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22March+2023%22) @meganrogge @isidorn **team**

### UX
- [ ] :runner: Refine updated built-in themes [vscode#164924](https://github.com/microsoft/vscode/issues/164924) @daviddossett
- [ ] :runner: Explore improvements to the extensions list [vscode#151599](https://github.com/microsoft/vscode/issues/151599) @esonnino
- [ ] :red_circle: Explore improvements on how to manage accounts @esonnino
- [ ] :red_circle: Publish ProtoPie interactive components file for VS Code extensions @esonnino

### Workbench
- [ ] :runner: Explore built-in Profiles [vscode#166359](https://github.com/microsoft/vscode/issues/166359) @isidorn @sandy081 @esonnino
- [ ] :runner: Explore surfacing the remote experiences on the welcome page [vscode#173396](https://github.com/microsoft/vscode/issues/173396) @bhavyaus
- [ ] :runner: Introduce an experimental modal welcome for web experiences [vscode#171190](https://github.com/microsoft/vscode/issues/171190) @bhavyaus @joyceerhl @daviddossett
- [ ] :runner: Improvements to Getting Started experience [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Abhavyaus+milestone%3A%22March+2023%22+label%3Abug+) @bhavyaus
- [ ] Make it easier to get sharing links [vscode#175676](https://github.com/microsoft/vscode/issues/175676) @joyceerhl
- [ ] Add support for running macros [vscode#871](https://github.com/microsoft/vscode/issues/871 ) @ulugbekna
- [ ] :muscle: Add support for recording macros [vscode#4490](https://github.com/microsoft/vscode/issues/4490 ) @ulugbekna
- [ ] :runner: Support parenthesis in context keys [vscode#91473](https://github.com/microsoft/vscode/issues/91473) @ulugbekna @jrieken
- [ ] Improve rendering of command palette when it is scrollable [vscode#173851](https://github.com/microsoft/vscode/issues/173851) @tylerleonhardt
- [ ] Fix delay when opening the accounts menu [vscode#111398](https://github.com/microsoft/vscode/issues/111398) @tylerleonhardt
- [ ] Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt

### Code Editor
- [x] :runner: Polish the interplay between intellisense and inline suggestions [vscode#131940](https://github.com/microsoft/vscode/issues/131940) @hediet @isidorn
- [ ] :runner: Add keyboard navigation to Sticky Scroll [vscode#169107](https://github.com/microsoft/vscode/issues/169107) @aiday-mar
- [ ] :red_circle: Allow configuring Sticky Scroll data provider @aiday-mar
- [ ] :red_circle: :runner: Polish and enable async tokenization @hediet
- [ ] Add elided text (editor core subset of [vscode#170447](https://github.com/microsoft/vscode/pull/170447)) @hediet @alexdima
- [ ] :runner: Show markers at the top of editor hovers [vscode#73120](https://github.com/microsoft/vscode/pull/73120) @aiday-mar
- [ ] Scroll editor hovers using arrow keys [vscode#69836](https://github.com/microsoft/vscode/pull/69836) @aiday-mar
- [ ] :muscle: Make editor hovers resizeable [vscode#14165](https://github.com/microsoft/vscode/pull/14165) @aiday-mar
- [ ] :muscle: Explore workaround for missing `wheel` event on iPad [vscode#164220](https://github.com/microsoft/vscode/issues/164220) @hediet
- [ ] :runner: Monaco Editor issue grooming @hediet
- [ ] Monaco Editor Release @hediet

### Notebook Editor
- [ ] :runner: Polish and enable scrollable notebook outputs [vscode-jupyter#4406](https://github.com/microsoft/vscode-jupyter/issues/4406) @amunger
- [ ] :muscle: Align closing behavior of the Interactive Window with Untitled Files [vscode#172974](https://github.com/microsoft/vscode/issues/172974) @amunger
- [ ] Enable find in output by default [vscode-jupyter#12886](https://github.com/microsoft/vscode-jupyter/issues/12886) @rebornix
- [ ] :runner: Explore how to stop hanging network request from preventing the opening of notebooks [vscode#166860](https://github.com/microsoft/vscode/issues/166860) @mjbvz
- [ ] :runner: Introduce global search options for open notebooks [vscode#164926](https://github.com/microsoft/vscode/issues/164926) @andreamah
- [ ] :runner: Explore smart global search for notebooks in the workspace [vscode#173726](https://github.com/microsoft/vscode/issues/173726) @andreamah
- [ ] Introduce `onWillSaveNotebookDocument` event to support run or format on save [vscode#157844](https://github.com/microsoft/vscode/issues/157844), [vscode#130799](https://github.com/microsoft/vscode/issues/130799) @rebornix

#### Jupyter Notebooks
- [ ] :red_circle: :runner: Contributions to the vscode-jupyter extension **team**

### WebAssembly Runtime Support
- [ ] :red_circle: Prepare WASI implementation for WASM threads @dbaeumer
- [ ] :red_circle: Translate core utils to WASM/WASI @connor4312
- [ ] :muscle: Explore provide a web-shell [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @dbaeumer @tyriar

#### Python
- [ ] :red_circle: :runner: Contributions to the python extension @brettcannon **team**

##### Python WebAssembly Runtime Support
- [ ] :runner: [Explore support for statically linking and loading native modules](https://github.com/microsoft/vscode-wasm/issues/35) @dbaeumer @brettcannon
- [ ] :runner: :black_large_square: How do users find packages that work in CPython WASI? [issue](https://github.com/microsoft/vscode-python-web-wasm/issues/42); @brettcannon

#### JavaScript/TypeScript
- [ ] :runner: Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Project-wide IntelliSense on the web [vscode#170920](https://github.com/microsoft/vscode/issues/170920) @mjbvz
- [ ] :red_circle: TypeScript 5.1 support @mjbvz

#### JSON
- None.

### Localization
- None.

### Debug
- None.

#### Debug Adapter Protocol
- None.

### Testing
- None.

### Terminal
- [ ] :runner: Support external terminals as a default for WSL sessions [vscode#167865](https://github.com/microsoft/vscode/issues/167865) @tyriar
- [ ] :runner: Continue `pwsh` autocomplete [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar
- [ ] Improvements to the environment collection API [vscode#171173](https://github.com/microsoft/vscode/issues/171173) [vscode#171108](https://github.com/microsoft/vscode/issues/171108) @tyriar
- [ ] Provide API to set the terminal title and description [vscode#171175](https://github.com/microsoft/vscode/issues/171175) @tyriar

### Tasks
- None.

### Source Control
- None.

### API
- [ ] :runner: API finalization: [query](https:/github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March\+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [ ] :runner: API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March\+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] Remove the `notebookControllerKind` API Proposal [vscode#168535](https://github.com/microsoft/vscode/issues/168535) @mjbvz @rebornix
- [ ] Finalize static preloads notebook contribution [vscode#163511](https://github.com/microsoft/vscode/issues/163511) @mjbvz
- [ ] :red_circle: Explore support for extensions to provide additional data to the issue reporter @TylerLeonhardt

### Extensions
- None.

### Extension Contributions
- [ ] :red_circle: :runner: Improvements to the Remote extensions @eleanorjboyd @chrmarti @aeschli @joyceerhl
- [ ] :runner: Exploration: Re-think PR creation flow [vscode-pull-request-github#4403](https://github.com/microsoft/vscode-pull-request-github/issues/4403) @alexr00 @daviddossett

### Performance
- [ ] Defer eager activation events till initial events have settled [vscode#171135](https://github.com/microsoft/vscode/issues/171135) @joyceerhl
- [ ] :hand: :black_large_square: PGO for VSCode Desktop [vscode#170931](https://github.com/microsoft/vscode/issues/170931) @deepak1556

### Install
- [ ] :runner: Update snap package to use `base:` [vscode#119436](https://github.com/microsoft/vscode/issues/119436) @deepak1556
- [ ] :muscle: Linux: Ship RPM packages for EL8/EL9 alongside EL7 [vscode#144969](https://github.com/microsoft/vscode/issues/144969) @deepak1556

### Engineering
- [ ] :muscle: Explore migrating from AMD to ESM [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken @alexdima
- [ ] :runner: :black_large_square: Sandboxing: Adopt utility process for shared process and file watchers [vscode#154050](https://github.com/microsoft/vscode/issues/154050) @bpasero @deepak1556
- [ ] Adopt utility process in terminal/pty host [vscode#175335](https://github.com/microsoft/vscode/issues/175335) @tyriar
- [ ] :red_circle: :runner: Sandboxing: Investigate increased extension host crash rate in stable @bpasero @deepak1556 @digitarald

#### Electron
- [ ] :runner: Update to Electron 22 [vscode#166265](https://github.com/microsoft/vscode/issues/166265) @deepak1556 @bpasero @rzhao271
- [ ] Orca can't be stopped in native dialogs [vscode#121811](https://github.com/microsoft/vscode/issues/121811) @deepak1556
- [ ] Right Click acting abnormal [vscode#113175](https://github.com/microsoft/vscode/issues/113175) @deepak1556

### Documentation
- [ ] Update source control documentation to include the merge editor [vscode-docs#5618](https://github.com/microsoft/vscode-docs/issues/5618) @gregvanl @hediet
- [ ] Review and update Terminal Basics (git bash setup from verbatims) [vscode-docs#6108](https://github.com/microsoft/vscode-docs/issues/6108) @gregvanl

----
### Deferred
- [ ] :runner: Defer `onStartupFinished` activation [vscode#164593](https://github.com/microsoft/vscode/issues/164593) @joyceerhl
- [ ] :red_circle: :muscle: Investigate slow stacks reported to telemetry, ramp up the experiment @jrieken
- [ ] Explore notebook specific list view and layout improvements [vscode#170881](https://github.com/microsoft/vscode/issues/170881) @rebornix @roblourens
- [ ] Clarify requirement for unique variable names [debug-adapter-protocol#141](https://github.com/microsoft/debug-adapter-protocol/issues/141) @roblourens
- [ ] Add ‘singleThread’ argument to pause requests [debug-adapter-protocol#355](https://github.com/microsoft/debug-adapter-protocol/issues/355) @roblourens
- [ ] Continue request shouldn’t fall back on continuing all threads [debug-adapter-protocol#221](https://github.com/microsoft/debug-adapter-protocol/issues/221) @roblourens
- [ ] :runner: Explore a built-in variables viewer [vscode#165445](https://github.com/microsoft/vscode/issues/165445) @roblourens
- [ ] :runner: Surface Continue-On in more places [vscode#165406](https://github.com/microsoft/vscode/issues/165406) @joyceerhl
- [ ] :runner: Memory reuse [debug-adapter-protocol#238](https://github.com/microsoft/debug-adapter-protocol/issues/238) @connor4312 @roblourens
- [ ] Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [ ] :hand: Improving the developer experience for the CLI within the vscode repo [vscode#171515](https://github.com/microsoft/vscode/issues/171515) @aeschli @connor4312
- [ ] :muscle: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz
- [ ] Git: Support untracked folders [vscode#169253](https://github.com/microsoft/vscode/issues/169253) @lszomoru
- [ ] :hand: :runner: Fix preview of forwarded ports in Codespaces for Simple Browser and Live Preview [vscode-livepreview#111](https://github.com/microsoft/vscode-livepreview/issues/111) @andreamah @mjbvz
- [ ] :runner: Explore localization support for notebook renderers [vscode#170919](https://github.com/microsoft/vscode/issues/170919) @TylerLeonhardt @mjbvz
- [ ] :runner: Update Azure Content, ToC [vscode-docs#5614](https://github.com/microsoft/vscode-docs/issues/5614) @gregvanl @isidorn
- [ ] Investigate large screen update under remote desktop [vscode#164503](https://github.com/microsoft/vscode/issues/164503) @deepak1556
- [ ] Revisit TOC selection behavior in the settings editor when searching [vscode#170462](https://github.com/microsoft/vscode/issues/170462) @rzhao271

**Comment by zm-cttae** [comment]
#174286 - would it help this PR go On Deck if I wrote full testing plan? Would be quite similar to #143636 to be honest
