### ISSUE TITLE
Enhance Search in Default Settings editor

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#17646]
Enhance Search in Default Settings editor

- [x] [Preferences: cannot find "cssempty" or "css empty"](https://github.com/Microsoft/vscode/issues/17536)
- [x] [Search in Settings editor - not standard search](https://github.com/Microsoft/vscode/issues/17436)
- [x] [Preferences: decorations on whitespace](https://github.com/Microsoft/vscode/issues/17161)
- [x] [Too much fuzzy matching in settings](https://github.com/Microsoft/vscode/issues/16700)
