### ISSUE TITLE
Improve xterm.js performance

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#17875]
There are a few improvements needed in xterm.js to improve terminal performance

- [x] Use circular list to manage buffer **PR: https://github.com/sourcelair/xterm.js/pull/422**
  - Also fixes scrollback issue https://github.com/sourcelair/xterm.js/issues/361
- [x] ~~Proposal: revamp the refresh method for better rendering performance~~ https://github.com/sourcelair/xterm.js/issues/150 (no longer needed with other changes)
- [x] ~~Performance of refresh is still subpar https://github.com/sourcelair/xterm.js/issues/134~~ (no longer an issue)
- [x] Viewport.refresh seems to be triggered on every line of input https://github.com/sourcelair/xterm.js/issues/290 (**PR: https://github.com/sourcelair/xterm.js/pull/438**)
- [x] Refresh limit system makes performance bad on Windows https://github.com/sourcelair/xterm.js/issues/280 (**PR: https://github.com/sourcelair/xterm.js/pull/438**)
- [x] Commands that fill a non-full buffer lock up the terminal for a couple of seconds https://github.com/sourcelair/xterm.js/issues/444 (**PR: https://github.com/sourcelair/xterm.js/pull/445**)
- [x] Reconsider XON/XOFF PR to keep slave in sync with terminal https://github.com/sourcelair/xterm.js/issues/425 (**PR: https://github.com/sourcelair/xterm.js/pull/447**)
- [x] Too much time is spent in getBoundingClientRect (no issue) (**PR: https://github.com/sourcelair/xterm.js/pull/440**)
- [x] ~~Investigate reuse of DOM nodes to reduce browser garbage collection https://github.com/sourcelair/xterm.js/issues/449 (**PR: https://github.com/sourcelair/xterm.js/pull/450**)~~ Deferred until results are proven or the model is needed for something else
- [x] :muscle: Optimize parser https://github.com/sourcelair/xterm.js/issues/459 (**PR: https://github.com/sourcelair/xterm.js/pull/462**)

**Comment by nirmaljpatel** [comment]
I am using VSCode as IDE for Appcelerator App development. I compile and run the project using a Grunt build task which in turn uses grunt-shell to invoke a  CLI command: `appc run`.
The output is directed to console. If I turn on high level of logs output, the terminal process stops with following error msg:
```
Warning: stderr maxBuffer exceeded Use --force to continue.
Aborted due to warnings.
Execution Time (2017-01-27 16:00:19 UTC-6)
loading tasks       902ms  ▇ 2%
shell:appc-run-sim  43.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
```
The expectation would be the console should keep running showing the messages directed at it.
I tried specifying maxBuffer to the shell command (via grunt). This did increase the amount of logs before this error appeared. When set to 20MB, the entire Code IDE froze.

**Comment by Tyriar** [comment]
@nirmaljpatel what version are you on?

**Comment by nirmaljpatel** [comment]
Code Version 1.8.1 (1.8.1) 
MacOS Sierra (10.12.2)

**Comment by Tyriar** [comment]
@nirmaljpatel next version January/1.9.0 fixes the performance issues. You can try it out now with https://code.visualstudio.com/insiders

**Comment by nirmaljpatel** [comment]
On this newer version, I still faced the same issue.
```
Warning: stderr maxBuffer exceeded Use --force to continue.
Aborted due to warnings.
Execution Time (2017-01-27 16:08:30 UTC-6)
loading tasks       565ms  ▇ 2%
shell:appc-run-sim  29.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 98%
Total 30.5s
```

However, after specifying the maxBuffer for grunt-shell, the output is running fine so far.
```
execOptions: {
	maxBuffer: 1000 * 1000 * 10
}
```

**Comment by Tyriar** [comment]
Sounds like an issue with `grunt-shell`?
