### ISSUE TITLE
Improvements to Remote Explorer

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#178854]
- [x]     Deprecate `Provide Feedback` in favor of `Report Issue` [vscode#178246](https://github.com/microsoft/vscode/issues/178246)
- [x]     Get Started actions should open extension-contributed walkthroughs instead of opening an external link [vscode-remote-release#8349](https://github.com/microsoft/vscode-remote-release/issues/8349)
- [x]      Rename `Remote` category [vscode-remote-release#8006](https://github.com/microsoft/vscode-remote-release/issues/8006)
- [x]      WSL extension's refresh button in view title menu should be right-aligned, not left-aligned
- [ ]      Standardize remote view contents
- [ ]  Standardize windowing behavior across remotes

**Comment by joyceerhl** [comment]
Tracking the remaining improvements here in https://github.com/microsoft/vscode-remote-release/issues/8397, thus closing this item out.
