### ISSUE TITLE
Iteration Plan for April 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#178951]
This plan captures our work in **April**. This is a 5-week iteration. We will ship in **early May**.

## Endgame
- **April 24, 2023**: Endgame begins
- **April 28, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22April+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Improve command palette input box screen reader experience [vscode#176081](https://github.com/microsoft/vscode/issues/176081) @TylerLeonhardt
- [x] Inline suggestions are read twice by screen reader [vscode#177696](https://github.com/microsoft/vscode/issues/177696) @hediet
- [x] `Set Selection Anchor` and `Select from Anchor to Cursor` does not work in a11y terminal buffer [vscode#177029](https://github.com/microsoft/vscode/issues/177029) @meganrogge
- [ ] :runner: Notebook output accessibility [vscode#178630](https://github.com/microsoft/vscode/issues/178630) @amunger
- [x] `allowNavigateToSurroundingCells` should be false when screen reader is detected [vscode#176286](https://github.com/microsoft/vscode/issues/176286) @meganrogge
- [x] Notebook cell complete audio cue didn't play if kernel was selected in same execution action [vscode#176284](https://github.com/microsoft/vscode/issues/176284) @meganrogge
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22April+2023%22) @meganrogge @isidorn **team**
- [ ] :runner: Custom dialog does not properly return focus to webView [vscode#170442](https://github.com/microsoft/vscode/issues/170442) @sbatten @mjbvz

### Workbench
- [x] Built-in Profiles [vscode#166359](https://github.com/microsoft/vscode/issues/166359) @isidorn @sandy081
- [ ] :runner: Support Dev Containers and WSL in new Connect to... experience on Welcome Page [vscode-remote-release#8251](https://github.com/microsoft/vscode-remote-release/issues/8251) @bhavyaus @aeschli @chrmarti
- [ ] :runner: Improve the keybinding recording widget [vscode#178042](https://github.com/microsoft/vscode/issues/178042) [vscode#179015](https://github.com/microsoft/vscode/issues/179015) [vscode#179018](https://github.com/microsoft/vscode/issues/179018) @ulugbekna
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [x] Address performance regression in insiders [vscode#177257](https://github.com/microsoft/vscode/issues/177257) @bpasero
- [x] Explore flatten "Continue On" options in Terminal welcome view [vscode#179013](https://github.com/microsoft/vscode/issues/179013) @joyceerhl
- [x] Improve "Continue On" sign-in flow [vscode#179012](https://github.com/microsoft/vscode/issues/179012) @joyceerhl
- [ ] :runner: Support roaming open editors and notebook kernel state in "Continue On" [vscode#179898](https://github.com/microsoft/vscode/issues/179898) @joyceerhl @rebornix
- [ ] :runner: Change default light and dark themes to the v2 themes [vscode#179688](https://github.com/microsoft/vscode/issues/179688) @aeschli @daviddossett

### Code Editor
- [x] Roll out async tokenization and add correctness assertions behind setting [vscode#179133](https://github.com/microsoft/vscode/issues/179133) @hediet
- [x] Deprecate smart diffing algorithm in favor of experimental diffing algorithm [vscode#164583](https://github.com/microsoft/vscode/issues/164583) @hediet
- [ ] :muscle: Collapse unchanged regions in diff [vscode#3562](https://github.com/microsoft/vscode/issues/3562) @hediet
- [x] Accept inline completion words across lines [vscode#172162](https://github.com/microsoft/vscode/issues/172162) @hediet
- [x] Allow inline providers to opt in to showing inline completions at the same time as completions [vscode#179134](https://github.com/microsoft/vscode/issues/179134) @hediet
- [ ] :runner: Make editor hovers resizable [vscode#14165](https://github.com/microsoft/vscode/issues/14165) @aiday-mar
- [ ] :runner: Allow using the color picker without a color region [vscode#52364](https://github.com/microsoft/vscode/issues/52364) @aiday-mar
- [x] Monaco Editor Release [0.37.0](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0370) @hediet

### Notebook Editor
- [x] Allow toggling scrollable outputs per cell [vscode#174951](https://github.com/microsoft/vscode/issues/174951) @amunger
- [x] Polish global search options for open notebooks [vscode#164926](https://github.com/microsoft/vscode/issues/164926) @andreamah
- [ ] :runner: Static resources fail to load in Notebook renderer with 401 error [vscode#175033](https://github.com/microsoft/vscode/issues/175033) @mjbvz
- [ ] :muscle: Align closing behavior of the Interactive Window with Untitled Files [vscode#172974](https://github.com/microsoft/vscode/issues/172974) @amunger
- [x] Support dynamic profile switching [vscode#179224](https://github.com/microsoft/vscode/issues/179224) @rebornix @bpasero
- [x] Explore supporting replace while markdown cells are in preview mode [vscode#179320](https://github.com/microsoft/vscode/issues/179320) @rebornix

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#13250](https://github.com/microsoft/vscode-jupyter/issues/13250) **team**

### WebAssembly Runtime Support
- [x] Finish up multi thread support for WASM-WASI threads [vscode-wasm#45](https://github.com/microsoft/vscode-wasm/issues/45) @dbaeumer
- [ ] :runner: Convert Python WASM-WASI extension to the new library extension [vscode-python-web-wasm#47](https://github.com/microsoft/vscode-python-web-wasm/issues/47) @dbaeumer
- [ ] :runner: Explore provide a web-shell [shell-engine-js#1](https://github.com/microsoft/shell-engine-js/issues/1) @dbaeumer @tyriar

#### Python
- [x] Contributions to the python extension [vscode-python#20971](https://github.com/microsoft/vscode-python/issues/20971) @brettcannon **team**

##### Python WebAssembly Runtime Support
- [x] How do users find packages that work in CPython WASI? [issue](https://github.com/microsoft/vscode-python-web-wasm/issues/42); @brettcannon

#### JavaScript/TypeScript
- [ ] :runner: Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Project-wide IntelliSense on the web [vscode#170920](https://github.com/microsoft/vscode/issues/170920) @mjbvz
- [x] TypeScript 5.1 move to existing file support [typescript#29988](https://github.com/microsoft/TypeScript/issues/29988) @mjbvz
- [x] TypeScript 5.1 jsx mirror cursor support [typescript#51832](https://github.com/microsoft/TypeScript/issues/51832) @mjbvz

#### Language Server Protocol
- [ ] :runner: Investigate to extract a base protocol definition out of the LS protocol [1707](https://github.com/microsoft/language-server-protocol/issues/1707) @dbaeumer
- [ ] :runner: Support that servers can read from remote file systems [1264](https://github.com/microsoft/language-server-protocol/issues/1264) @rchiodo / @dbaeumer

### Source Control
- [x] Git Status Updates Are Blocking [vscode#168453](https://github.com/microsoft/vscode/issues/168453) @lszomoru
- [x] SCM - Add document property to expose the text document [vscode#171504](https://github.com/microsoft/vscode/pull/171504) @lszomoru
- [x] Handle push errors more gracefully [vscode#178990](https://github.com/microsoft/vscode/issues/178990) @lszomoru
- [ ] :black_large_square: [vscode#179000](https://github.com/microsoft/vscode/issues/179000) Exploration: Changes editor @lszomoru
- [ ] :muscle: Surface Dependabot alerts in workbench [vscode#178991](https://github.com/microsoft/vscode/issues/178991) @lszomoru

### Terminal
- [x] Allow specifying workspace-specific environment variables via EnvironmentVariableCollection [vscode#171173](https://github.com/microsoft/vscode/issues/171173) @karrtikr @tyriar
- [x] Allow to provide description to environment collection API [vscode#171108](https://github.com/microsoft/vscode/issues/171108) @karrtikr
- [ ] :runner: Finalize proposed APIs for environment workspace collection [vscode#171108](https://github.com/microsoft/vscode/issues/171108) @karrtikr
- [ ] :runner: Allow EnvironmentVariableCollection API to apply changes via shell integration [vscode#179476](https://github.com/microsoft/vscode/issues/179476) @tyriar @karrtikr

### Testing
- [x] Expose selection and profile of the test explorer [vscode#179065](https://github.com/microsoft/vscode/issues/179065) @connor4312
- [x] Allow to watch subsets of tests [vscode#178973](https://github.com/microsoft/vscode/issues/178973) @connor4312
- [x] Better indicators for what tests are running continuously [vscode#178973](https://github.com/microsoft/vscode/issues/178973) @connor4312
- [ ] :muscle: Support for ANSI colors in test output [vscode#151964](https://github.com/microsoft/vscode/issues/151964) @connor4312
- [ ] :muscle: Start drafting a retired test item API [vscode#134970](https://github.com/microsoft/vscode/issues/134970) @connor4312

### vscode.dev
- [ ] :muscle: Opening vscode.dev should not require a browser reload to update web extensions [vscode#174682](https://github.com/microsoft/vscode/issues/174682) @sandy081

### API
- [x] API finalization: [query](https:/github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [x] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: Explore support for extensions to provide additional data to the issue reporter [vscode#46726](https://github.com/microsoft/vscode/issues/46726) @TylerLeonhardt

### Extensions
- [x] Show the publisher in notifications whenever we recommend extensions [179004](https://github.com/microsoft/vscode/issues/179004) @sandy081

### Extension Contributions
- [x] Improvements to the Remote extensions @eleanorjboyd @chrmarti [vscode-remote-release#8314](https://github.com/microsoft/vscode-remote-release/issues/8314) @aeschli @joyceerhl @connor4312
- [ ] :runner: Exploration: Re-think PR creation flow [vscode-pull-request-github#4403](https://github.com/microsoft/vscode-pull-request-github/issues/4403) @alexr00 @hbons
- [x] Add Team Reviewers to Pull Request [vscode-pull-request-github#1126](https://github.com/microsoft/vscode-pull-request-github/issues/1126) @alexr00
- [x] :muscle: Respect git's pullBeforeCheckout setting for githubPullRequests.postCreate [vscode-pull-request-github#4450](https://github.com/microsoft/vscode-pull-request-github/issues/4450) @alexr00
- [x] GHPR: Make it very obvious when the rate limit has been hit [vscode-pull-request-github#4546](https://github.com/microsoft/vscode-pull-request-github/issues/4546) @alexr00

### Engineering
- [ ] :runner: :muscle: Adopt utility process in terminal/pty host [vscode#175335](https://github.com/microsoft/vscode/issues/175335) @tyriar @bpasero
- [x] Sandboxing: Investigate increased extension host crash rate in stable [vscode-internalbacklog#3456](https://github.com/microsoft/vscode-internalbacklog/issues/3456) @bpasero @deepak1556 @digitarald

#### Electron
- [x] :black_large_square: Update to Electron 22 [vscode#166265](https://github.com/microsoft/vscode/issues/166265) @deepak1556 @bpasero @rzhao271

----
### Deferred
- [ ] Explore alternative wording for "Continue On" explanations [vscode#180106](https://github.com/microsoft/vscode/issues/180106) @hbons
- [ ] Exploration: Cross-profile settings and extensions [vscode#176813](https://github.com/microsoft/vscode/issues/176813) [vscode#157492](https://github.com/microsoft/vscode/issues/157492)@sandy081
- [ ] Show existing tunnels on Welcome page in vscode.dev [vscode#179687](https://github.com/microsoft/vscode/issues/179687) @bhavyaus @aeschli @connor4312
- [ ] Support experimental contextual non-modal dialogs to educate users on web experiences [vscode#179401](https://github.com/microsoft/vscode/issues/179401) @bhavyaus @joyceerhl @daviddossett
- [ ] Walkthrough images load slowly [vscode#166890](https://github.com/microsoft/vscode/issues/166890) @bhavyaus
- [ ] UX to alert users of a slow remote connection [vscode#178553](https://github.com/microsoft/vscode/issues/178553) @bpasero
- [ ] Support scrollable outputs for streaming text [vscode#177721](https://github.com/microsoft/vscode/issues/177721) @amunger @mjbvz
- [ ] Explore smart global search for notebooks in the workspace [vscode#173726](https://github.com/microsoft/vscode/issues/173726) @andreamah
- [ ] Explore prompting to enable Cloud Changes on save in web [vscode#179014](https://github.com/microsoft/vscode/issues/179014) @joyceerhl
- [ ] Investigation: Azure DevOps multi-tenant support [vscode-remote-repositories-github#241](https://github.com/microsoft/vscode-remote-repositories-github/issues/241) @lszomoru
- [ ] Improving the developer experience for the CLI within the vscode repo [vscode#171515](https://github.com/microsoft/vscode/issues/171515) @aeschli @connor4312
- [ ] Orca can't be stopped in native dialogs [vscode#121811](https://github.com/microsoft/vscode/issues/121811) @deepak1556
- [ ] Explore improvements to the extensions list [vscode#151599](https://github.com/microsoft/vscode/issues/151599)
- [ ] Support external terminals as a default for WSL sessions [vscode#167865](https://github.com/microsoft/vscode/issues/167865) @tyriar
- [ ] Continue `pwsh` autocomplete [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar
- [ ] :hand: Add elided text (editor core subset of [vscode#170447](https://github.com/microsoft/vscode/pull/170447)) @hediet @alexdima
- [ ] :hand: :black_large_square: PGO for VSCode Desktop [vscode#170931](https://github.com/microsoft/vscode/issues/170931) @deepak1556
- [ ] :muscle: Right Click acting abnormal [vscode#113175](https://github.com/microsoft/vscode/issues/113175) @deepak1556
- [ ] Add support for running macros [vscode#871](https://github.com/microsoft/vscode/issues/871) @ulugbekna
- [ ] Add support for recording macros [vscode#4490](https://github.com/microsoft/vscode/issues/4490) @ulugbekna

**Comment by Chaos-070799** [comment]
I really hope we got this one right...  The last time I had so much
interference in making educated decisions in continuing my business in
merchandising do to problems with collecting accurate data I'm hoping with
this one I can receive an email attach the calendar and store list doc with
the ability to add to calendar the gps from store list doc...  And stop the
ability to fudge the map information  For expenses etc

**Comment by dzienisz** [comment]
This plans always looks the same and not reflect real development and changes :(

**Comment by virtruvio** [comment]
Is there time to get either:

a ping to the Canonical snap "core" team to upgrade GLIBCXX-3.4 to version 29 (GLIBCXX_3.4.29) in Core20

OR

(likely formidable) convert "code" to use Core22 (which contains GLIBCXX_3.4.29 already).  

The missing version 29 in GLIBCXX_3.4 in libstdc++.so.6 embedded in Core20 throws errors when using anything from libproxy.so

This theme is recurring when there's a GLIBXX_ update and we start to get modules using the upgrades and core hasn't caught up.

**Comment by agirault** [comment]
> - [ ] 💪 Collapse unchanged regions in diff https://github.com/microsoft/vscode/issues/3562 @hediet

Are you able to provide an ETA on this? Thank you!

**Comment by Chaos-070799** [comment]
I'm working on this issue now...  I am sitting by whom I think is hacking my data wether he realizes it or not, so I'm having to start and stop a lot!  He builds RC cars on side and orders from a Temu sight!
