### ISSUE TITLE
Improve Git extension

### ISSUE THREAD

**Issue by GIT-MDW** [microsoft/vscode#179053]
Type: <b>Feature Request</b>

While working with git graphs, I utilize both vscode and webstorm to determine which one is best, and I believe webstorm is effective right now.

It has a free git tool that we can use, but we must install an extension for vscode to use it. The best extension is git graph, but it costs money and isn't very versatile. Can it be made better to have one built in?

vscode git graph https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph

![image](https://user-images.githubusercontent.com/94377644/229609918-0553f055-28be-40cf-8c62-775493a146ab.png)

VS Code version: Code 1.77.0 (7f329fe6c66b0f86ae1574c2911b681ad5a45d63, 2023-03-29T10:02:16.981Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by Keavon** [comment]
[Git Graph](https://marketplace.visualstudio.com/items?itemName=mhutchie.git-graph) is the single best thing ever to happen to making Git accessible. It single-handedly taught me Git from it being a complete mystery to making perfect sense. It's also such an efficient and useful tool that I consider it my "home page" in the VS Code editor.

However, it is no longer maintained at all (the creator is MIA).

But it is so well designed, so popular, so useful, and still manages to be a minimal and unopinionated approach to displaying a repo's Git status, that I strongly believe it absolutely deserves to become the blueprint for VS Code's built-in Git history viewer. This would make Git profoundly less confusing for millions of people. And it would act as a perfect complement to the existing Source Control panel that's already built into VS Code.

VS Code team, please consider reimplementing the core design of Git Graph straight into the default VS Code experience! Literally millions of people are counting on it (Git Graph has over 7 million installs and a 5.0/5.0 rating because it is so adored).

**Comment by otdavies** [comment]
I want to second @Keavon's point here. It is the best git graph around. It is great for code review and properly represents the flow of your git history without any biases. Please please make this a core part of VSCode.

**Comment by isaacsando** [comment]
I use this daily to review my git branches. I would love to see this as a core part of VS Code!

**Comment by piradata** [comment]
hello, i also would love this feature, there is no way to review git commits without the git blame and git graph extensions

**Comment by MuTsunTsai** [comment]
Absolutely second @Keavon 's proposal. We all need that.

**Comment by Guddi11** [comment]
Same here. It’s too bad git graph is not further maintained at the moment. To implement its core functionality would put the use of git in vscode through the roof.

**Comment by romansh** [comment]
+1, I'd like to see it as a core functionality for VS Code.

**Comment by AlexMarlow25** [comment]
It would be nice to see this feature as the main functionality in VS Code! This is one of the key features that still forces me to use WebStorm with VS Code.

**Comment by Patta** [comment]
+1

**Comment by imagryesweid** [comment]
Invaluable for large scale repos

**Comment by pdicerbo** [comment]
Essential to my everyday work!

**Comment by Jibbajabbafic** [comment]
This is an absolute must have extension and I always recommend it to new starters in my team, so having it directly integrated and maintained would be a huge benefit to the community.

**Comment by apitofme** [comment]
Not sure what to do about this but I found that there is a (presumably "illegally" forked / cloned / reverse-engineered) version of the O.G. Git Graph that has been published to the (OpenVSX) marketplace, going by then name [Git Graph Plus](https://open-vsx.org/extension/cweijan/git-graph-pro).

1. This version [links to a fully permissive MIT license](https://openvsxorg.blob.core.windows.net/resources/cweijan/git-graph-pro/1.1.1/LICENSE.txt) with notably different copyright details.
2. It doesn't even try to hide it's fraud, given that it still links back to [mhutchie's repo](https://github.com/mhutchie/vscode-git-graph) where (or course) the original restrictive license still exists.

Whilst first-party functionality is highly desirable and I am hopeful of this campaign's success, in the meantime may I also note that there is a new extension available in the marketplace which aims to provide a fully and permissively _free_, maintained and fork-able alternative to Git Graph called "[git-log--graph](https://marketplace.visualstudio.com/items?itemName=phil294.git-log--graph)" by phil294 (which _is_ in both the Microsoft and OpenVSX marketplaces).

So for those interested / inclined you can support this new project [here](https://github.com/phil294/git-log--graph)?

---
_(Note: I have no affiliation to any projects mentioned!)_

_Additionally, since it is unrelated to the MS Marketplace (where it does not appear to be listed) I have reported the fraudulent extension to the maintainers of the OpenVSX marketplace (i.e. Eclipse Foundation)_

**Comment by GIT-MDW** [comment]
For example, there is good program that can be considered as well 
![image](https://github.com/microsoft/vscode/assets/94377644/635b7ccd-784c-4bb8-baa0-83917750b864)

**Comment by GIT-MDW** [comment]
For example there is good program that can be considered as well as alternative, but 100% you need to implement in vs code
![image](https://github.com/microsoft/vscode/assets/94377644/635b7ccd-784c-4bb8-baa0-83917750b864)

**Comment by CDboyOne** [comment]
+1

**Comment by txf-** [comment]
This would be great

**Comment by mjkodkks** [comment]
+1

**Comment by laterz** [comment]
其实，Virtual Studio有这样看起来很好用的Git可视化功能，希望在VSCode中也开放下！

https://learn.microsoft.com/zh-cn/visualstudio/version-control/git-browse-repository?view=vs-2022

**Comment by stunited-thien** [comment]
+1

**Comment by dearpowa** [comment]
Same, this feature is a must have +1

**Comment by telemaxxx** [comment]
+1

**Comment by jakub-gawlik** [comment]
+1

**Comment by barak-flare** [comment]
+1

**Comment by gamesun** [comment]
+1

**Comment by Cube707** [comment]
+1

**Comment by SuperDino484** [comment]
+1

**Comment by piradata** [comment]
guys, stop with the +1 on comments, just a 👍is enough

**Comment by taozuhong** [comment]
It's better if add the arrow on the line.

**Comment by bvandevliet** [comment]
I think this is related: #219953 
Seems to me they're trying to implement a git graph in the source control panel, but it's experimental at the time of writing and doesn't work well yet. But it might be something to check out and keep an eye on.

**Comment by Fydon** [comment]
The new functionality shows [ingoing and outgoing changes](https://code.visualstudio.com/updates/v1_91#_incomingoutgoing-changes-graph-preview) and is an experimental feature in version 1.19. [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) would provide more what I think is being asked for, although the Commit Graph is a Pro feature (free for public repositories but requires a license for private).

**Comment by Keavon** [comment]
> [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)'s Commit Graph would provide more what I think is being asked for

GitLens is hideously bloated to the point of total uselessness. Git Graph is very minimal and is the main point of interest amongst most people voting for this issue.

**Comment by bvandevliet** [comment]
> The new functionality shows changes in the current branch and possibly the base branch ([read here to see more](https://code.visualstudio.com/updates/v1_91#_incomingoutgoing-changes-graph-preview)) and is an experimental feature in version 1.19. [GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)'s Commit Graph would provide more what I think is being asked for, although not built into vscode. However the Commit Graph is a Pro feature (free for public repositories but requires a license for private).

You're right it shows changes only. However the fact vscode now has a sort of git graph implemented (though very limited) gives me hope that they might extend on that in the future making it a full featured git graph. I mean part of the work is already done right. :)

**Comment by Keavon** [comment]
Some seemingly good news [mentioned](https://code.visualstudio.com/updates/v1_93#_source-control-graph-view) in the 1.93 release notes (specifically the last sentence, which I've bolded):

> ### Source Control Graph view
> Based on user feedback, we have moved the history graph that was enabled last milestone from the Source Control view into a new view called Source Control Graph. This reduces the information overload from the main view and enables you to hide/collapse/move the new view as you see fit. **This also lays the foundation for a full-featured history graph.**

@lszomoru Would it make sense to update the triaging of this issue in any way to reflect that intention? I'd also like to volunteer to be involved in any kind of design, use case determination, feedback, etc. if this moves forward and that's something your team would find useful. (My background is in product design and UX, and I have lots of thoughts regarding Git visualizations that I'd be most happy to share.) Thanks for building towards this, by the looks of it.

**Comment by lszomoru** [comment]
Thank you all for your interest in this feature request and for your patience. While in VS Code 1.93 we did ship the new "Source Control Graph" view I did not want to update this issue just yet as the first iteration was very limited in functionality. 

Since we shipped VS Code 1.93 we have been heads down polishing both the user experience as well as adding new functionality to the Source Control Graph view. Please download VS Code Insiders (1.94), give it a try and let us know what you think. 

As far as feature parity with extensions I would like to set clear expectations that we will focus on basic functionality and not provide all feature that are available in extensions as we want extension authors to continue to innovate in this space and continue to foster a vibrant extension ecosystem.

@Keavon, thank you very much for your offer. The best way to engage is to download the latest VS Code Insiders release, try out the graph, and share any feedback that you have around the UX in this issue. We are still polishing the UX so any feedback that you have will be appreciated. Thank you!

**Comment by bvandevliet** [comment]
@lszomoru If functionality will remain basic and extended functionalities are intended to be added through extensions, I'd suggest that the source control graph view should at least have a rich API to extend on it, e.g. context menu's, etc ;)

**Comment by lszomoru** [comment]
> I'd suggest that the source control graph view should at least have a rich API to extend on it, e.g. context menu's, etc ;)

That's the plan.

**Comment by Cube707** [comment]
@lszomoru I just tested the insider build and really like the work.

I thing I noticed: there seems to be a problem when showing `all`, where commits are not added to the view according to their date but in some other order. for example:

this image taken from the GitGraph extention shows the feature-branch in between the two tags, where it last updated:
![grafik](https://github.com/user-attachments/assets/e717c22c-51da-4821-8a4d-4e311962b6b1)

In the new view the branch is missing in between the Tags:
![grafik](https://github.com/user-attachments/assets/c7ee80ef-003c-46aa-8c59-a9a2175bc62d)

Instead it shows up much further down:
![grafik](https://github.com/user-attachments/assets/c4fde701-5bcb-485e-b2d9-e122b9ceebda)

**Comment by lszomoru** [comment]
Thank you very much for the feedback. The "Source Control Graph" view is currently using [topological order](https://git-scm.com/docs/git-log#Documentation/git-log.txt---topo-order) of commits (`--topo-order`). This order was created specifically for rendering commits in a graph as it makes the graph easier to read as it avoid interleaving commits. In the future we will surface this as a setting so that users can choose the order that is being used.

**Comment by Cube707** [comment]
> In the future we will surface this as a setting so that users can choose the order that is being used

Making this configurable seems like the best solution :+1:

**Comment by bvandevliet** [comment]
I've been testing v1.94.0 a bit and I really like the direction this is going to, great work!! 👍

There's just one last thing that is holding me from completely switching from the good ol' git-graph extension to this new built-in source control graph. That is that clicking a commit in the source control graph shows all diffs expanded at once, while in the good ol' git graph extension the graph expands showing the files that have changed, then by clicking one of those files it would show just that diff. See my paint skills below how this could look like if implemented into the source control graph.. ;)

Might this be something that others also like to have, or is it just me ;p? Though, I'd already be satisfied if there's a setting that allows the diffs to always appear collapsed by default (instead of expanded and having to click the "Collapse all diffs" button each time).. :)

![Image](https://github.com/user-attachments/assets/46261ebf-1f17-4bc9-847e-ffe42ca3c6f9)

**Comment by Cube707** [comment]
I also second @bvandevliet.

I especially find it strange that clicking a file with open changes and wanting to see tha changes made by a commit results in two different types of views (one showing multiple files and one only showing a single file). While they are only slightly different I believe that showing identical views would and having a file-tree in the new source-graph would feel more consistent.

**Comment by probitcarwyn** [comment]
Being able to revert a commit from the graph view would be really handy. Typical workflow:

- Make a commit.
- Realise it's on the wrong branch (usually main).
- Use the graph to create a branch from the parent.
- Cherry pick the commit onto the right branch.
- Can't do the "undo" of the commit on the wrong branch from the graph view.
 
Obviously you can do this in other ways, but given the other actions are possible from the graph view, it would be nice to be able to do the last step there too.

**Comment by Cube707** [comment]
The same is true for rebasing onto a branch.

- checkout a feature-brnach
- right-click in the graph-view -> "rebase current branch here"

this would be very handy

**Comment by bvandevliet** [comment]
May I summarize this as reference and add some more? :)

- [ ] Make browsing diffs more usable / user friendly ([2407072695](https://github.com/microsoft/vscode/issues/179053#issuecomment-2407072695), [2434701422](https://github.com/microsoft/vscode/issues/179053#issuecomment-2434701422), [2435036201](https://github.com/microsoft/vscode/issues/179053#issuecomment-2435036201)).
- [ ] Add option to sort the commits in the graph based on their datetime ([2363205011](https://github.com/microsoft/vscode/issues/179053#issuecomment-2363205011), [2366732569](https://github.com/microsoft/vscode/issues/179053#issuecomment-2366732569)).
- [ ] Also show stashes.
- [ ] Extend context menu on right-click on a commit, tag, branch or stash, (depending on the context of what was clicked):
  - [ ] Checkout branch ([2435036201](https://github.com/microsoft/vscode/issues/179053#issuecomment-2435036201))
  - [ ] Rename branch...
  - [ ] Delete (remote) branch...
  - [ ] Push branch...
  - [ ] Pull into current branch...
  - [ ] Merge into current branch...
  - [ ] Rebase current branch on branch... ([2435036201](https://github.com/microsoft/vscode/issues/179053#issuecomment-2435036201))
  - [ ] Rebase current branch on this commit... ([2435036201](https://github.com/microsoft/vscode/issues/179053#issuecomment-2435036201))
  - [ ] Reset current branch to this commit... ("undo" in [2434940874](https://github.com/microsoft/vscode/issues/179053#issuecomment-2434940874)?)
  - [ ] Revert this commit
  - [ ] Delete (remote) tag...
  - [ ] Push tag
  - [ ] Apply stash
  - [ ] Pop stash
  - [ ] Drop stash

**Comment by Cube707** [comment]
It would alternatively be helpfull to get feedback on what won't make it into the official version, so that work on extensions for these features could begin

**Comment by ADTC** [comment]
Is there any existing issue for this problem? I can't find any, but maybe I'm not using the right keywords in my search...

When viewing the diff of a commit from the graph, or when viewing the full diff of changes or staged changes, "moved or renamed" files are not shown as such, but they are shown as separate delete and add operations.

Note: I know that a Git commit has no notion of "renames" but most diff tools (including `git diff`) use a similarity index to convert any "delete+add" pairs into "rename/move" if they have high similarity. Seems like VS Code diff is completely refusing to do this.

Am I missing a config, or should I open a new issue?

Another issue: the combined diff view doesn't indicated whether the file was added, changed, deleted, moved etc. All files look the same especially when collapsed. It doesn't show the change ratio or `+/-` character count either. I hope we can bring in the basic features of GitHub diff into VS Code diff as a reference.

**Comment by lszomoru** [comment]
@ADTC, could you please file separate issues for this so that I can look into it? Thanks!

**Comment by laterz** [comment]
> 其实，Virtual Studio有这样看起来很好用的Git可视化功能，希望在VSCode中也开放下！
> 
> https://learn.microsoft.com/zh-cn/visualstudio/version-control/git-browse-repository?view=vs-2022

In fact, visual studio  has such a very useful+beautiful GitGraph function. I hope it can be implemented  in VS Code!

https://learn.microsoft.com/zh-cn/visualstudio/version-control/media/vs-2022/git-repository-multigraph-branch-view.png?view=vs-2022

**Comment by aurexav** [comment]
> In fact, visual studio has such a very useful+beautiful GitGraph function. I hope it can be implemented in VS Code!

Please don't post such screenshot here. There were already a lot of people mentioned such extensions. It will just make thread long and hard to read.

**Comment by bvandevliet** [comment]
> I've been testing v1.94.0 a bit and I really like the direction this is going to, great work!! 👍
> 
> There's just one last thing that is holding me from completely switching from the good ol' git-graph extension to this new built-in source control graph. That is that clicking a commit in the source control graph shows all diffs expanded at once, while in the good ol' git graph extension the graph expands showing the files that have changed, then by clicking one of those files it would show just that diff. See my paint skills below how this could look like if implemented into the source control graph.. ;)
> 
> Might this be something that others also like to have, or is it just me ;p? Though, I'd already be satisfied if there's a setting that allows the diffs to always appear collapsed by default (instead of expanded and having to click the "Collapse all diffs" button each time).. :)
> 
> ![Image](https://github.com/user-attachments/assets/46261ebf-1f17-4bc9-847e-ffe42ca3c6f9)

To this day, this still keeps me from switching from the good old abandoned Git Graph extension.... Still using Git Graph on a daily basis (hasn't been updated for like 4 years or so XD).

**Comment by ADTC** [comment]
> clicking a commit in the source control graph shows all diffs expanded at once

I typically want to see all of the diff in the whole commit, so I don't mind it. I do sometimes instinctively reach for the Collapse All button though. It would have been nice if there's a setting to make collapsed state the default state.

Also I often prefer the flat list view more than the folder structure view, though the option to toggle will be nice.

**Comment by Delapouite** [comment]
For people in this thread not up to date with the latest couple of versions, VSCode 1.101 (released 2025-06-12) improved the Git graph view. You can now expand a commit by clicking on it and reveal the list of changed files as requested many time in this thread.

More details and videos in the official changelog : https://code.visualstudio.com/updates/v1_101#_source-control-history-item-details

**Comment by txf-** [comment]
It has improved. However, honestly it still does not hold a candle to the clarity and usability of Git Graph (the extension).

**Comment by dvdrtrgn** [comment]
The VsCode team should clone Git Graph (mhutchie/vscode-git-graph) and keep it maintained. 

It is nearly perfect.

**Comment by amithegde** [comment]
can this be prioritized please? the implementation on the vs code under Source Control called Graph is rudimentary and doesn't even display a tree view for files modified. There are so many features missing and it is hard to use it as a daily driver.

**Comment by roberto-gigli** [comment]
@amithegde are you sure you are on the latest version? Because, on the latest version there is|

<img width="549" height="314" alt="Image" src="https://github.com/user-attachments/assets/709947ea-e19b-493d-84cd-3f30e6f4b11e" />

<img width="555" height="455" alt="Image" src="https://github.com/user-attachments/assets/e98a22e8-276a-4f99-85bf-d35ee0cdfd83" />

**Comment by amithegde** [comment]
I see, there is this

<img width="151" height="100" alt="Image" src="https://github.com/user-attachments/assets/5c6cf7c8-e42a-4f8d-a6f2-a2cfdb5d9c0f" />

But still the git graph is way better and vs code should just implment this feature instead of trying to hack together something in the side panel

**Comment by germanfrelo** [comment]
The biggest issue for me is that with the Git Graph extension, all the information is visible in one tab. With this native feature, however, that is not the case. The native graph is in the sidebar and the branch names are truncated. I'd also prefer that the branch badges be on the left instead of the right.

Edit: The main issue for me at the moment is that branch names are always truncated. It's as if they all have a maximum width.

**Comment by cameronfrye-eaton** [comment]
I definitely agree, after the latest vscode update I have been having issues with the old Git Graph extension and have been looking for something new to use. Something like this would be amazing. I agree that instead of a little panel in the source control menu a larger window is much more suitable for working with git.

**Comment by DiM-RiC** [comment]
@cameronfrye-eaton 
> I have been having issues with the old Git Graph extension and have been looking for something new to use. 

If you are talking about the git-graph icon disappearing, I solved my issues selecting "Select Single Repository" in the Repository options of the source control. In this way you select one repository at a time to visualize in the "CHANGES", and there you will find again the git-graph icon available.

I fully agree that vscode should simply integrate git-graph, and maintain it.

**Comment by ahernsean** [comment]
Though the feature overlap with other tools is certainly not complete, this issue is technically resolved with the implementation of the Graph within VSCode's Source Control panel. I wonder if the additional specific asks (changing location of branch names, moving the graph into the editor area, date display, suppress remote branches, etc.) should be carved into separate issues here on the board. That would allow detailed discussion of the pros, cons, and desired UX of each.

**Comment by nselvara** [comment]
I second the idea. It's incredible that this versatile tool wasn't implemented by the makers by themselves. As an addendum, I'd really love to see similar to the visual depiction of how bitbucket does.

**Comment by zmbc** [comment]
@lszomoru as @Cube707 said above, it would be helpful if the VS Code team could share a roadmap of what will be considered "basic functionality" to be included in core and what will need to be in extensions. This is a huge area for potential UX improvement, and I think there is a lot of energy here that could be harnessed to help, but right now it isn't clear which of these features would be accepted as PRs to core.

**Comment by germanfrelo** [comment]
The main issue for me right now is that branch names are always truncated to a fixed maximum width. It would be great if you could at least add a setting that allows the full name of each branch to be displayed.

<img width="270" height="768" alt="Screenshot of the VS Code Source Control commit graph. Next to the commit author names, several branch labels are shown, but most of them—such as 'vscode/repo-se…', 'zsh/formatting-…', and 'origin/dependa…'—are truncated with an ellipsis." src="https://github.com/user-attachments/assets/32ae5c28-2223-4d47-b06f-0fd4e002a0dd" />
