### ISSUE TITLE
January Iteration Plan

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1826]
We are back from the holidays and are rolling again. We are starting to target our next important milestone for Code, the [Build 2016 conference](http://build.microsoft.com/), which takes place at end of March in San Francisco. The [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) outlines our high level plans for getting there and this is our detailed plan for the January 2016 iteration. 

We plan to declare General Availability ("GA") with the March 2016 release. GA comes with several quality obligations in areas such as accessibility and localization. We know that we have significant gaps here and we want to start to tackle them right away. On the drive to Connect(); we accumulated engineering debt that we must to address sooner rather than later. And, as we always do, we will continue to ship monthly and address key development pain points and adoption blockers.  

Based on these imperatives we arrived at the following themes for January:
* Ramp up the work to get to GA (accessibility, localization, ...).
* Reduce the engineering debt.
* Respond to feedback and try to address as many issues as possible.

The [January Test Plan](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+label%3Atestplan-item+milestone%3A%22Jan+2016%22) is in progress.

### Schedule
The goal is to make the January update available by the following dates.

End game dates (we end an iteration with an [endgame](https://github.com/Microsoft/vscode/wiki/Development-Process#end-game))
* Monday Jan 25th evening (GMT+1): freeze
* Tuesday: test day
* Wednesday: fix day
* Thursday: fix day
* Friday: Done: documentation, release notes update, bugs verified

:warning: update we will switch to `dev channels` and deprecate the `insider channel`. We will make the new dev channels available as soon as possible during the end game and will hold back updating the stable channel until we have received early feedback.

### Plan Items

:runner: = work in progress
:hand: = task is blocked
:muscle: = stretch goal for this iteration

**Feedback**
Issues to address feedback from the community:
- [x] UI: Improve auto save behaviour, support to customize auto save delay, support to save on focus lost @bpasero 
 - Issues #353, #1055, #1211 
  - Test #1854 
  - [x] Release notes
- [x] UI: Support to hide the menu bar @bpasero 
 - Issues #945, #1563 
  - Test #2226 
  - [x] Release notes
- [x] UI: Intellisense - no way to show full documentation for a completion proposal @joaomoreno 
  - Test #2230 
  - [x] Release notes
- [x] Editor: Support ligatures #192 @alexandrudima
  - [x] Release notes @jrieken
- [x] UI: More colorful default `Dark` and `Lite` themes @aeschli
  - Issue #1470, #1849
  - Test #2256
  - [x] Release notes
- [x] UI: Find widget improvements #1999 #2033 #2010 #1869
  - Test #1869
  - [x] Release notes
- [x] UI: new welcome page experience #2166 @sofianHn
  - Test #2251  
- Debug: Generalize debug adapter protocol to support other debuggers like XDebug @weinand 
  - [x] Microsoft/vscode-debugadapter-node#4
  - [x] Microsoft/vscode-debugadapter-node#9
  - [x]  Microsoft/vscode-debugadapter-node#5
  - Test #2183 
  - [x] Release notes
- [x] Debug; Indicate changed values in Variables pane
  - Issue #866 
  - Test #2171 
  - [x] Release notes
- [x] Debug; Support conditional break points @isidorn, @weinand
  - Issue #1582, Microsoft/vscode-debugadapter-node#6
  - Test #1830
  - [x] Release notes
- Debug: support to remote debug node running inside a docker container
  - [x] improve source path matching (#1591) @weinand
  - [x] support "address" attribute on "attach" launch config (Microsoft/vscode-node-debug#32) @weinand
  - Test #2188
  - [x] Release notes
- [x] API: Support to create a TextDocument virtually @jrieken 
  - Issue #272
  - Test #2007
  - [x] Release notes
- [x] API: Richer quick pick support @jrieken
  - Issue: #1795
  - Test #2008
  - [x] Release notes
- [x] API: command to preview html document (#1308) @jrieken
  - Test #2099 
  - [x] Release notes
- [x] API: Allow to map a filename to a language based on a prefix (#1851) @jrieken 
  - Test #2238
  - [x] Release notes
- [x] API: Provide API to current editor column #1835 
  - Test #2152
  - [x] Release notes
- [x] API: Support Markdown in the API (MarkedString)
  - Test #2222 
  - [x] Release notes
- [x] *IntelliSense filtering has become slow again in huge lists* #1923 @joaomoreno
  - Test #2254
  - [x] Release notes

**Debt Items**
This section lists items to reduce our engineering debt:
- Start to migrate 'built-in' language services into extensions 
  - [x] Migrate JSON into an extension @aeschli 
  - Test #2257 
  - [x] Release notes
  - *Deferred* - Provide JSON language service in standalone monaco editor @aeschli @alexandrudima
- *Deferred* -  Intellisense for asp.net 5 package dependencies in the `project.json` is currently hard coded into JSON language, Enable that this can be contributed by the C# extension.  
- [x] Debug: Provide a test suite for debugger adapters @weinand
  - [x] Release notes
- [x] Extensions: Separate the vscode related tools from the vscode API into the existing vscode module #970 @bpasero 
  - Currently the vscode node module combines the tools and the vscode API into one unit, we want to decouple the API from the used modules.
  - Test #1881
  - [x] Release notes

**Adoptions**
We continuously have to adopt components which we require:
- [x] Adopt electron 0.35.6  @bpasero 
  - Issues: #1485 
  - [x] Release notes
- *Deferred - TS 1.8 isn't available yet* Adopt [TypeScript 1.8](https://github.com/Microsoft/TypeScript/wiki/Roadmap)
  - 1.8Beta is planned for Jan 25th #836  @dbaeumer
  - Update the vscode-extension yo generator to depend on 1.8 @bpasero 
- *not for January release* Adopt the a newer version of OmniSharp @jrieken

**Engineering Items**
This section lists several engineering/development items that the team identified:
- [x] JS: [Salsa](Microsoft/TypeScript#4789) support for JS and provide feedback @jrieken @egamma @dbaeumer
  - Test #2218 
  - [x] Release Notes
- [x] UI: Support that the debug output and task output is shown in a horizontal bar #1875 @isidorn
  - Tests #2176, #2173
  - [x] Release Notes
- [x] Debug: Improve the value hover for rich objects by using the tree widget @isidorn
  - Test #1832
  - [x] Release Notes
- [x] Debug: support source maps with inlined source
  - Issues: #1793, Microsoft/vscode-node-debug#27
  - Test #2183
  - [x] Release Notes
- :hand: Build: Automated Mac build signing @joaomoreno 
- [x] Install: Support side-by-side installs of VS Code from different channels (insider, stable) @joaomoreno, @bpasero
  - Test done by selfhost
- [x] Enable tslint for vscode #2102 @egamma
  - Test - covered by dog fooding

**Initial Investigations**
- :runner: Keyboard accessibility  #2108 @bpasero 
  - Test #2145
  - [x] Release Notes
- :runner: Screen reading support in the editors @alexandrudima 
  - Test #2258
  - [x] Release Notes
- :runner: Localization: investigate into localizing Code  #2041 @dbaeumer
  - Test #2228
  - [x] Release Notes

## Bugs
This section includes bug queries for the vscode related repositories:
- [vscode](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Abug+-label%3Aupstream+milestone%3A%22Jan+2016%22)

For more information about our development process please refer to the development process [page](https://github.com/Microsoft/vscode/wiki/Development-Process).
