### ISSUE TITLE
Improve Extension UI

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#18354]
Current Extension UI causes quiet number of dialogs during an extension managing lifecycle. It would be better to reduce them with nicer UI. 

Also improve representation of an extension.

- [x] [When I presss "reload", an unnecessary confirm dialog appears](https://github.com/Microsoft/vscode/issues/18039)
- [x] [Extra confirmation message seems weird](https://github.com/Microsoft/vscode/issues/14412)
- [x] ["Reload this window to activate the extension X" - wording](https://github.com/Microsoft/vscode/issues/17432)
- [x] ["UX: Extension should have visual indication of globally/locally enabled](https://github.com/Microsoft/vscode/issues/14472)
- [ ] ["Bad layout for extensions with empty description](https://github.com/Microsoft/vscode/issues/14475)

**Comment by bpasero** [comment]
I would just not confirm after clicking reload, especially since hot exit is now enabled by default and all dirty changes will be restored.

**Comment by borekb** [comment]
The first item (When I presss "reload", an unnecessary confirm dialog appears) seems to be delivered in 1.18.

**Comment by sandy081** [comment]
Yes

**Comment by sandy081** [comment]
Closing this a most of the concerns are addressed
