### ISSUE TITLE
Update to Electron 25

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#184021]
```[tasklist]
### Todo
- [x] Update patches
- [x] Nightly Exploration builds
- [x] Update native modules
- [x] Update/Check LICENSE file in CG for new node.js version
- [x] Update LICENSE for new ffmpeg version
- [x] Node 18 bumps minimum GLIBC >= 2.28, refs https://nodejs.org/en/blog/announcements/v18-release-announce#toolchain-and-compiler-upgrades
- [x] Create meta issue for tackling DNS result order changes from Node v18, refs https://github.com/nodejs/node/issues/40702
```

**Comment by fisforfaheem** [comment]
Please consider Electron 25 it has much better performance and stability

**Comment by lorand-horvath** [comment]
> Please consider Electron 25 it has much better performance and stability

And of course, no backward compatibility. As for stability, how can one say the first couple releases of a major version are stable? Electron 25.0.0 is barely 2 weeks old!
I said it many times before... stop asking for bleeding edge software, there are and always will be many bugs in them. Do you like your VSCode having all kinds of weird issues? I don't.

**Comment by fisforfaheem** [comment]
but using an ond chromium engine feels not safe... Also Vscode needs to
focus on improving performance.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/10/23,
02:39:59 AM

**Comment by zm-cttae** [comment]
Native node fetch! Very keen on this upgrade. It'll make a lot of my WASM-related code mutch quicker.

**Comment by tjx666** [comment]
@lorand-horvath there are two months to test and fix

**Comment by fisforfaheem** [comment]
Hope we see latest chromium soon! VSCODE insiders atleast should have
latest version, given it's name



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/13/23,
11:18:34 AM

**Comment by tjx666** [comment]
@deepak1556 will be released in July interation?

**Comment by fisforfaheem** [comment]
I agree that using blazing edge electron may get issues. But at least
VSCode Insiders should have Electron version 23 or 24 to benefit. I'm not
talking about the stable version of VSCode, but the Insider version.

**Comment by lorand-horvath** [comment]
> I agree that using blazing edge electron may get issues. But at least VSCode Insiders should have Electron version 23 or 24 to benefit. I'm not talking about the stable version of VSCode, but the Insider version.

@fisforfaheem That's not how it works; this is the 3rd time you are asking to have Electron 24 only in Insiders.
Insiders is max 1 month ahead of official VSCode, you can verify that yourself. It's basically the beta testing phase.
There's also VSCode Exploration, which is the alpha development phase.

**Comment by lorand-horvath** [comment]
@fisforfaheem You can find VSCode Exploration version 1.75 here. Install it (it has the orange logo, you'll see), then inside it Check for Updates which will get you the latest version 1.81-exploration (alpha).

**Comment by fisforfaheem** [comment]
LINK?

**Comment by deepak1556** [comment]
@tjx666 not likely, this iteration will be focused on resolving the two Node.js blockers 

1) Get server executables based on Node v18 to be GLIBC >= 2.17 compatible
2) Adopt DNS result order changes

**Comment by AaronDewes** [comment]
Please consider Electron 25, because Chromium is only compatible with KDE 6 since v114, which is what Electron 25 includes.

**Comment by zm-cttae** [comment]
I thought we agreed that targeting non-LTS software like KDE 6 and Electron 25 was not ideal.

**Comment by AaronDewes** [comment]
> I thought we agreed that targeting non-LTS software like KDE 6 and Electron 25 was not ideal.

KDE 6 will be maintained for many years, and Electron has no LTS releases AFAIK... So I'm not sure what you're trying to ask for here?

**Comment by zm-cttae** [comment]
LTS concept in Node as in stable channel release that has been in production for a while and is battle tested

**Comment by shannon** [comment]
I just wanted to add a use case for updating to Electron 25. I'm building an extension that leverages WebGPU. While this should work in vscode.dev it won't work on the desktop version until electron is updated to at least Chrome 113. As it stands the desktop version is on a much older version of chrome and having such a large difference between vscode.dev and the desktop means it's getting more difficult to code extensions that work in both places. New Web APIs and new ES language additions will be months or longer behind vscode.dev.

The biggest problem I have right now is I have now way to test my development for the extension because you typically do it the other way around. Meaning you test the web version using desktop:

https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension-in-vs-code-running-on-desktop

So right now I am falling back to WebGL2 but I can't test WebGPU functionality fully. 

I just wanted to add that I understand that keeping electron updated is not trivial but as the Chrome versions slide further apart it's doing a disservice to web extension authoring. Please don't take this as a criticism, I mean this only as friendly feedback as I don't see this particular issue being discussed here.

As far as LTS (Long Term Support) goes, electron does not have LTS releases. They do have Stable releases and electron 24 is EOL in October of this year. v25 is December, so it's only a couple of months difference but we are getting closer to October fast.

https://www.electronjs.org/docs/latest/tutorial/electron-timelines

Anyways, thank you for all the hard work and I hope this feedback can be helpful in some way.

**Comment by zm-cttae** [comment]
I read your comment Shannon and I do appreciate the detail there. What I *would* say is that it's fine for the team to upgrade to electron 25 later (as an outsider) but my hunch is that the team would not be upgrading to 25 within this year then. The engineering work and refactoring involved is quite great 👀

**Comment by deepak1556** [comment]
Thanks for your feedback @shannon , I understand the pain with having to work with different runtime versions between web and desktop. Ideally I would like to keep them as close as possible but the past few updates had breaking changes which required us to have a longer adoption cycle to avoid disrupting our user base. I am preparing Electron 25 builds as part of this issue and if it does not bring any additional issues then we will adopt Electron 25 instead of Electron 24. But either way, as mentioned before https://github.com/microsoft/vscode/issues/184021#issuecomment-1630070515 needs to be resolved first.

**Comment by markg85** [comment]
While i don't have specific compelling reasons like @shannon, i do have my own "ahh, vscode again" issues.
I happen to run a linux environment with Slack (uses electron25) and vscode (electron22). Both get compiled from source and both take absolute ages to finally be done.

From that point of view, I happily only have 1.

From an update point of view - we're all developers here, right? - there should be a natural tendency to stay on the most recent version and update often. Meaning that it would be great if vscode jumps on a new version relatively quick. In my book that means within a month. Electron 25 is from 55 days ago (https://releases.electronjs.org/history/2023-05-29 may 29th 2023). That does feel like it's certainly about time now.

I'm well aware that this multiple runtime stuff is just a never ending story and you're never going to satisfy everyone.

**Comment by zm-cttae** [comment]
> I happen to run a linux environment with Slack (uses electron25) and vscode (electron22). Both get compiled from source and both take absolute ages to finally be done.

We desperately need electron/electron#673 , but getting them to move on this is impossible. I can't wait for the day the browser version gets all the app permissions and advanced APIs (FS access, indexed DB etc) it needs to kick Electron out.

**Comment by NCLnclNCL** [comment]
> https://az764295.vo.msecnd.net/exploration/a7703202794cf4894003d6502eb196192e8e0333/VSCode-win32-ia32-1.81.0-exploration.zip

thanks

**Comment by zhouxinghong** [comment]
It works very well! Thank you very much!

**Comment by zhouxinghong** [comment]
https://github.com/electron/electron/releases/tag/v25.4.0

**Comment by zhouxinghong** [comment]
https://github.com/electron/electron/releases/tag/v25.5.0

**Comment by zhouxinghong** [comment]
https://github.com/electron/electron/releases/tag/v26.0.0

**Comment by tjx666** [comment]
@deepak1556 any performance improved after upgrade electron v25? I think node18 maybe improve some

**Comment by fisforfaheem** [comment]
yes feeling a slight performance improvement

**Comment by zhouxinghong** [comment]
https://github.com/electron/electron/releases/tag/v26.1.0
https://github.com/electron/electron/releases/tag/v25.8.0
Fixes a lot of bugs included Electron 25 version

**Comment by deepak1556** [comment]
@tjx666 yes we have seen nice improvements to process launch times across all platforms, most noticeable on windows with ~80ms drop, there are also some minor script execution time improvements ~20-30ms. However on macOS we lost some time from start till `app.isReady` which requires investigation. But overall the score is better than Electron 22.

**Comment by shannon** [comment]
Just FYI, the following bug is present in Electron 25 and therefore present in the latest release of VS Code: https://github.com/electron/electron/issues/38790

**Comment by lorand-horvath** [comment]
I will now venture and say that the update to Electron 25 was rushed in VSCode 1.82, as I've correctly predicted would happen https://github.com/microsoft/vscode/issues/184021#issuecomment-1584236830 - that strange bugs were going to creep in.
Here's just a couple of them, but I'm sure there are many others (lack of time to track everything going on):
https://github.com/microsoft/vscode/issues/190437
https://github.com/electron/electron/issues/38790

I'd really like to have an Electron 22 branch somehow still available and maintained, it was much more stable, no serious issues as far as I can see. And it was also working on Windows 7 without problems. But that's too much to ask, I guess.

**Comment by donotsdubba** [comment]
@lorand-horvath I genuinely laughed seeing all the "geniuses" that originally thumbed down your wise, well-grounded first comment. The vast majority of people really accept just about anything up their orifices, don't they? Even software developers, who are supposed to be the ones doing more thinking than anyone else, generally do not think at all.

So thank you for speaking reason amongst them, despite how they "rewarded" you, and for taking them to school. I say this on behalf of _many_ lurkers.

**Comment by shannon** [comment]
My comment about the bug from Electron 25 being in VS Code was not to disparage the work to do the upgrade or suggest that it should not have been done. I merely wanted to point it out in case anyone else ran into it. It is a very strange bug but not show stopping. Having said that, I think this just reiterates that the work to keep VS Code inline with Electron upgrades (including any bug fixes) is important and should be as streamlined as possible. 

Other than this bug, being able to now run and test my WebGPU based code directly inside VS Code has been invaluable.
