### ISSUE TITLE
www.google.com

### ISSUE THREAD

**Issue by Anointe12345min** [microsoft/vscode#184456]
[ADD](url) ISSUE DESCRIPTION HERE

Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Embedder: codespaces

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/170534
- [ ] https://github.com/microsoft/vscode/issues/179956
- [ ] https://github.com/microsoft/vscode/issues/179598
- [ ] https://github.com/microsoft/vscode/issues/175836
- [ ] https://github.com/microsoft/vscode/issues/174159
- [ ] https://github.com/microsoft/vscode/issues/179451
- [ ] https://github.com/microsoft/vscode/issues/174157
- [ ] https://github.com/microsoft/vscode/issues/180565
```
