### ISSUE TITLE
Iteration Plan for June 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#184844]
This plan captures our work in **June**. This is a 4-week iteration. We will ship in **early July**.

## Endgame
- **June 26, 2023**: Endgame begins
- **June 30, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22June+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Provide generic accessibility help menus [vscode#183363](https://github.com/microsoft/vscode/issues/183363) @meganrogge
- [x] Provide generic accessibility views [vscode#183364](https://github.com/microsoft/vscode/issues/183364) @meganrogge
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22June+2023%22) @meganrogge **team**

### UX
- None.

### Workbench
- [x] Integrate Share in VS Code [vscode#176316](https://github.com/microsoft/vscode/issues/176316) @joyceerhl
- [x] Support clickable gutter decorations [vscode#179725](https://github.com/microsoft/vscode/issues/179725) @joyceerhl @alexdima
- [x] Unify remote menu and Connect To... start entry [vscode#184845](https://github.com/microsoft/vscode/issues/184845) @joyceerhl @bhavyaus
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [ ] :runner: Allow Default profile to be a fallback for settings, extensions and keyboard shortcuts [vscode#156144](https://github.com/microsoft/vscode/issues/156144) @sandy081
- [x] Drop support for windows 8 and 8.1 [vscode#177676](https://github.com/microsoft/vscode/issues/177676) @deepak1556
- [ ] :runner: Investigate Settings editor startup perf issue [vscode#179486](https://github.com/microsoft/vscode/issues/179486) @rzhao271
- [x] Allow `FileSystemProviders` to set the read-only file message [vscode#166971](https://github.com/microsoft/vscode/issues/166971) @alexr00
- [ ] :runner: Add proxy support to `http2` requests in the extension host [vscode#185098](https://github.com/microsoft/vscode/issues/185098) @chrmarti

### vscode.dev
- [x] Explore prompting to enable Cloud Changes on save in web [vscode#179014](https://github.com/microsoft/vscode/issues/179014) @joyceerhl
- [x] Support experimental contextual non-modal dialogs to educate users on web experiences [vscode#179401](https://github.com/microsoft/vscode/issues/179401) @bhavyaus @joyceerhl @daviddossett

### Code Editor
- [x] Make editor hovers resizable [vscode#14165](https://github.com/microsoft/vscode/issues/14165) @aiday-mar
- [x] Roll out web worker tokenization [vscode#184899](https://github.com/microsoft/vscode/issues/184899) @hediet
- [x] Roll out new diff algorithm [vscode#184900](https://github.com/microsoft/vscode/issues/184900) @hediet
- [x] Collapse unchanged regions in diff [vscode#3562](https://github.com/microsoft/vscode/issues/3562) @hediet
- [x] Detect and represent moves in the diff editor [vscode#181902](https://github.com/microsoft/vscode/issues/181902) @hediet
- [ ] :muscle: Explore reducing conflicts by diffing both inputs against each-other [vscode#157496](https://github.com/microsoft/vscode/issues/157496) @hediet
- [x] Monaco Editor Release [0.39.0](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0390) @hediet

### Notebook Editor
- [x] Align closing behavior of the Interactive Window with Untitled Files [vscode#172974](https://github.com/microsoft/vscode/issues/172974) @amunger
- [x] Support hiding menu items on notebook toolbar [vscode#161119](https://github.com/microsoft/vscode/issues/161119) @Yoyokrazy
- [x] Notebook toolbar execution section improvements [vscode#184194](https://github.com/microsoft/vscode/issues/184194) @Yoyokrazy
- [ ] :muscle: Explore Sticky Scroll showing markdown headers in notebooks [vscode#182444](https://github.com/microsoft/vscode/issues/182444) @Yoyokrazy
- [x] Fix API `NotebookEdit.updateCellMetadata` [vscode#184606](https://github.com/microsoft/vscode/issues/184606) @rebornix
- [ ] :runner: Optimize IPC traffic on notebook saving [vscode#172345](https://github.com/microsoft/vscode/issues/172345) @rebornix @bpasero
- [ ] :runner: Explore smart global search for notebooks in the workspace [vscode#173726](https://github.com/microsoft/vscode/issues/173726) @andreamah

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#13682](https://github.com/microsoft/vscode-jupyter/issues/13682) **team**

### WebAssembly Support
- [x] Explore WASI preview2 support [vscode-wasm#52](https://github.com/microsoft/vscode-wasm/issues/52) @dbaeumer
- [x] Convert Python wasm extension to new WASM core extension [vscode-python-web-wasm#47](https://github.com/microsoft/vscode-python-web-wasm/issues/47) @dbaeumer

#### Python
- [x] Contributions to the python extension [vscode-python#21403](https://github.com/microsoft/vscode-python/issues/21403) @brettcannon **team**

#### JavaScript/TypeScript
- [ ] Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
    - [ ] :runner: Merge in initial prototype from TS [vscode#182801](https://github.com/microsoft/vscode/pull/182801)

#### Language Server Protocol
- [ ] :runner: ‍Add .NET support to [lsprotocol](https://github.com/microsoft/lsprotocol) [lsprotocol#205](https://github.com/microsoft/lsprotocol/issues/205) @karthiknadig

#### Markdown
- [x] Create Markdown links when pasting urls [vscode#179628](https://github.com/microsoft/vscode/issues/179628) @MeghanKulkarni

### Source Control
- [x] Handle GitHub's Secret Scanning Push Protection [vscode#169355](https://github.com/microsoft/vscode/issues/169355) @lszomoru
- [ ] :hand: Surface Dependabot alerts in workbench [vscode#178991](https://github.com/microsoft/vscode/issues/178991) @lszomoru
- [ ] :hand: GitHub: Automatic branch protection from repository rules [vscode#182488](https://github.com/microsoft/vscode/issues/182488) @lszomoru

### Terminal
- [x] Support rendering images [vscode#182443](https://github.com/microsoft/vscode/issues/182443) @tyriar
- [x] Revisit reattached to wrong terminal bug [vscode#133542](https://github.com/microsoft/vscode/issues/133542) @tyriar
- [x] Make fixes to environment workspace collection and finalize proposed APIs [vscode#182069](https://github.com/microsoft/vscode/issues/182069) [vscode#181755](https://github.com/microsoft/vscode/issues/181755) @karrtikr

### Testing
- [x] Support for ANSI colors in test output [vscode#151964](https://github.com/microsoft/vscode/issues/151964) @connor4312

### API
- [ ] :runner: Explore `ShareableDataProvider` API [vscode#176316](https://github.com/microsoft/vscode/issues/176316) @joyceerhl
- [ ] :runner: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz
- [x] Finalize tree checkboxes API [vscode#116141](https://github.com/microsoft/vscode/issues/116141) @alexr00
- [ ] :runner: Finalize port attributes API [vscode#115616](https://github.com/microsoft/vscode/issues/115616) @alexr00
- [x] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- None.

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#8593](https://github.com/microsoft/vscode-remote-release/issues/8593) @roblourens @chrmarti @aeschli @joyceerhl @connor4312
- [ ] :runner: Exploration: Re-think PR creation flow [vscode-pull-request-github#4403](https://github.com/microsoft/vscode-pull-request-github/issues/4403) @alexr00 @hbons

### Engineering
- [x] Enable private member mangling [vscode#180461](https://github.com/microsoft/vscode/issues/180461) @mjbvz
- [x] Make CLI build faster [vscode#178692](https://github.com/microsoft/vscode/issues/178692) @connor4312
- [x] Investigate performance improvements to event emitters [vscode#185789](https://github.com/microsoft/vscode/issues/185789) @connor4312
- [ ] :muscle: Clean up CLI build [vscode#178691](https://github.com/microsoft/vscode/issues/178691) @connor4312
- [ ] :muscle: Use Terrapin instead of crates.io. Artifacts support for Cargo is now available in DevOps @connor4312
- [ ] :runner: Adopt `StorageScope.WORKSPACE` and `StorageTarget.USER` in workbench [vscode#183449](https://github.com/microsoft/vscode/issues/183449) @joyceerhl **team**
- [ ] :muscle: Explore providing prebuilt node-pty binaries [node-pty#46](https://github.com/microsoft/node-pty/issues/46) @tyriar
- [ ] :runner: Revoke GitHub token on sign out [vscode#152055](https://github.com/microsoft/vscode/issues/152055) @tylerleonhardt
- [x] :muscle: Move off `keytar` [vscode#185677](https://github.com/microsoft/vscode/issues/185677) @tylerleonhardt
- [x] Add SHA checksum verification when downloading Electron, Node and built-in extensions [vscode#184885](https://github.com/microsoft/vscode/issues/184885) @bpasero @deepak1556
- [x] Add a Linux perf bot @bpasero

#### Electron
- [x] Investigation: Electron 24 [vscode#184021](https://github.com/microsoft/vscode/issues/184021) @deepak1556

----
### Deferred
- [ ] Improve default theme diff colors for users with colorblindness [vscode#182173](https://github.com/microsoft/vscode/issues/182173) @hbons
- [ ] Explore improvements to notifications for users using screenreaders [vscode#183567](https://github.com/microsoft/vscode/issues/183567) @hbons
- [ ] :red_circle: Update color token architecture and themes in Figma toolkit @hbons
- [ ] Explore simplifying the account menu for built-in online services [vscode-internalbacklog#3271](https://github.com/microsoft/vscode-internalbacklog/issues/3271) @tylerLeonhardt @sandy081 @aeschli
- [ ] :red_circle: Investigate editor working sets @bpasero
- [ ] Improve rendering performance for streaming output update [vscode#182636](https://github.com/microsoft/vscode/issues/182636) @amunger @mjbvz
- [ ] :red_circle: ​Move Live Preview extension off of vscode-nls @andreamah
- [ ] :hand: Add elided text (editor core subset of [vscode#170447](https://github.com/microsoft/vscode/pull/170447)) @hediet @alexdima
- [ ] :hand: PGO for VSCode Desktop [vscode#170931](https://github.com/microsoft/vscode/issues/170931) @deepak1556
- [ ] Explore a Changes editor [vscode#179000](https://github.com/microsoft/vscode/issues/179000) @lszomoru
- [ ] :runner: Improve the keybinding recording widget [vscode#178042](https://github.com/microsoft/vscode/issues/178042) [vscode#179015](https://github.com/microsoft/vscode/issues/179015) [vscode#179018](https://github.com/microsoft/vscode/issues/179018) @ulugbekna

**Comment by gjsjohnmurray** [comment]
The API finalization query link is broken. Please fix it, and maybe check the template that presumably gets used when creating new iteration plans.

**Comment by Tyriar** [comment]
@gjsjohnmurray thanks, fixed. I think future plans are based on the previous month's plan so it should be good now.

**Comment by cinderblock** [comment]
What is the status of including #127365 in the Stable release? Is there any way/place to track the progress of that (and other, seemingly finished/stable) feature?

_I'd comment on that issue specifically but it is locked and I'm not sure where else to ask..._

**Comment by deepak1556** [comment]
@cinderblock it is discussed in https://github.com/microsoft/vscode/issues/183297, you can follow it for updates.
