### ISSUE TITLE
Move off of Keytar

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#185677]
With [node-keytar](https://github.com/atom/node-keytar) now archived and unmaintained, we need a path forward for securely storing secrets and additionally, reflect the fact that we do not need to follow the shape of keytar anymore.

On Desktop, we will take advantage of Electron's [safeStorage](https://www.electronjs.org/docs/latest/api/safe-storage) API. We will also get rid of `vscode-encrypt` because it would be providing no benefit in this new world.

Additionally, we will remove the KeytarShim that has been in the product. This was the solution to secrets before the [SecretStorage API](https://code.visualstudio.com/api/references/vscode-api#SecretStorage).

Outlined are the steps to get this done:
```[tasklist]
### Tasks
- [x] Implement new `EncryptionService` & `SecretStorageService` services with a migration story. Use new services for extension SecretStorage API
- [ ] https://github.com/microsoft/vscode/issues/186241
- [x] Write new docs for troubleshooting keyring issues & update remote docs
- [x] Notify top X extensions of KeytarShim that we will remove it
- [x] Make discussion post: https://github.com/microsoft/vscode-discussions/discussions/662
- [ ] https://github.com/microsoft/vscode/issues/115215
```

**Comment by TylerLeonhardt** [comment]
Closing since everything is done or captured in a follow up issue

**Comment by tomduncalf-figma** [comment]
Hey @TylerLeonhardt, I just wanted to flag that the behaviour of the secret store `onDidChange` listener appears to have changed in a surprising way since it was migrated away from keytar: https://github.com/microsoft/vscode/issues/187247
