### ISSUE TITLE
Clean up any other direct usecases of old Credentials API and replace them with the new API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#186241]
At this point it's just a couple of calls that are only used in the web.
```[tasklist]
### Tasks
- [x] https://github.com/microsoft/vscode/blob/376cf9168f4305bfcba7a03839270ddb04e7ed59/src/vs/code/browser/workbench/workbench.ts#L31
- [x] https://github.com/microsoft/vscode/blob/376cf9168f4305bfcba7a03839270ddb04e7ed59/src/vs/workbench/services/authentication/browser/authenticationService.ts#L80C1-L80C1
- [x] https://github.com/microsoft/vscode/blob/376cf9168f4305bfcba7a03839270ddb04e7ed59/src/vs/code/electron-main/auth.ts#L70-L71
```

**Comment by chdalski** [comment]
Hi @TylerLeonhardt,
the move to electrons safeStorage had some (most likely unwanted) consequences on Linux:
https://github.com/VSCodium/vscodium/issues/1561

**Comment by TylerLeonhardt** [comment]
@chdalski from what I'm seeing in that issue, it's a dupe of https://github.com/microsoft/vscode/issues/187338

and how to 
https://code.visualstudio.com/docs/editor/settings-sync#_troubleshooting-keychain-issues

**Comment by TylerLeonhardt** [comment]
All of this code is cleaned up. The last usecase of the CredentialsService is in the KeytarShim tracked by: https://github.com/microsoft/vscode/issues/115215
