### ISSUE TITLE
Iteration Plan for July 2023 [DRAFT]

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#187398]
This plan captures our work in **July**. This is a 4-week iteration. We will ship in **early August**.

## Endgame
- **July 24, 2023**: Endgame begins
- **July 28, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22July+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22July+2023%22) @meganrogge **team**

### UX
- [ ] Improve default theme diff colors for users with colorblindness [vscode#182173](https://github.com/microsoft/vscode/issues/182173) @hbons
- [ ] :muscle: Explore improvements to notifications for users using screenreaders [vscode#183567](https://github.com/microsoft/vscode/issues/183567) @hbons
- [ ] :red_circle: Update color token architecture and themes in Figma toolkit @hbons
- [ ] Explore notification management UX for specific extensions [vscode#41767](https://github.com/microsoft/vscode/issues/41767) @daviddossett

### Workbench
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [ ] :runner: Allow Default profile to be a fallback for settings, extensions and keyboard shortcuts [vscode#156144](https://github.com/microsoft/vscode/issues/156144) @sandy081
- [ ] :runner: Investigate Settings editor startup perf issue [vscode#179486](https://github.com/microsoft/vscode/issues/179486) @rzhao271
- [ ] :runner: Add proxy support to `http2` requests in the extension host [vscode#185098](https://github.com/microsoft/vscode/issues/185098) @chrmarti
- [ ] :red_circle: Support Kerberos proxies in the extension host @chrmarti

### vscode.dev
- None.

### Code Editor
- [ ] Roll out async tokenization [vscode#184899](https://github.com/microsoft/vscode/issues/184899) @hediet
- [ ] Accessibility improvements in diff editor [vscode#187061](https://github.com/microsoft/vscode/issues/187061) @hediet
- [ ] :red_circle: Polish moved source code detection and rendering @hediet
- [ ] :muscle: Explore reducing merge conflicts by diffing both inputs against each-other [vscode#157496](https://github.com/microsoft/vscode/issues/157496) @hediet
- [x] :runner: Monaco Editor Release [0.40.0](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0400) @hediet

### Notebook Editor
- [ ] Improve rendering performance for streaming output update [vscode#182636](https://github.com/microsoft/vscode/issues/182636) @amunger
- [ ] Support Copy Output through command/contextmenu [vscode#187152](https://github.com/microsoft/vscode/issues/187152)  @amunger
- [ ] Explore Sticky Scroll showing markdown headers in notebooks [vscode#182444](https://github.com/microsoft/vscode/issues/182444) @Yoyokrazy
- [ ] Support word highlight across notebook cell [vscode#184259](https://github.com/microsoft/vscode/issues/184259) @Yoyokrazy
- [ ] :muscle: Support trim trailing whitespace/empty lines in notebook cells [vscode#181905](https://github.com/microsoft/vscode/issues/181905) @Yoyokrazy
- [x] :runner: Optimize IPC traffic on notebook saving [vscode#172345](https://github.com/microsoft/vscode/issues/172345) @rebornix @bpasero
- [ ] :red_circle: :muscle: Handle missing language support in notebook cell @rebornix
- [ ] :runner: Explore smart global search for notebooks in the workspace [vscode#173726](https://github.com/microsoft/vscode/issues/173726) @andreamah

#### Jupyter Notebooks
- [ ] :red_circle: :runner: Contributions to the vscode-jupyter extension **team**

### WebAssembly Support
- [ ] :red_circle: Implement the [Canonical API](https://github.com/WebAssembly/component-model/blob/main/design/mvp/CanonicalABI.md) for preview2 in TypeScript @dbaeumer
- [ ] :red_circle: Continue work on the Wit Parser / AST @dbaeumer

#### Python
- [ ] :red_circle: :runner: Contributions to the python extension @brettcannon **team**

#### JavaScript/TypeScript
- [ ] Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
    - [ ] :runner: Merge in initial prototype from TS [vscode#182801](https://github.com/microsoft/vscode/pull/182801)

#### Language Server Protocol
- [ ] :runner: ‍Add .NET support to [lsprotocol](https://github.com/microsoft/lsprotocol) [lsprotocol#205](https://github.com/microsoft/lsprotocol/issues/205) @karthiknadig

#### Markdown
- None.

### Source Control
- [ ] :runner: GitHub: Automatic branch protection from repository rules [vscode#182488](https://github.com/microsoft/vscode/issues/182488) @lszomoru
- [ ] :runner: Git: Support opening repositories on symlinked paths [vscode#5970](https://github.com/microsoft/vscode/issues/5970) @lszomoru

### Terminal
- None.

### Testing
- None.

### API
- [ ] :runner: Explore `ShareableDataProvider` API [vscode#176316](https://github.com/microsoft/vscode/issues/176316) @joyceerhl
- [ ] :runner: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz
- [ ] :runner: Finalize port attributes API [vscode#115616](https://github.com/microsoft/vscode/issues/115616) @alexr00
- [ ] :runner: API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- None.

### Extension Contributions
- [ ] :red_circle: :runner: Improvements to the Remote extensions @roblourens @chrmarti @aeschli @joyceerhl @connor4312
- [ ] :runner: Exploration: Re-think PR creation flow [vscode-pull-request-github#4403](https://github.com/microsoft/vscode-pull-request-github/issues/4403) @alexr00 @hbons

### Engineering
- [x] :runner: Avoid launching pty host process when terminals aren't used [vscode#182637](https://github.com/microsoft/vscode/issues/182637) @tyriar
- [ ] Clean up CLI build [vscode#178691](https://github.com/microsoft/vscode/issues/178691) @connor4312
- [ ] Use Terrapin instead of crates.io. Artifacts support for Cargo is now available in DevOps @connor4312
- [ ] :red_circle: Ship separate third party notice with CLI download @connor4312
- [ ] :runner: Adopt `StorageScope.WORKSPACE` and `StorageTarget.USER` in workbench [vscode#183449](https://github.com/microsoft/vscode/issues/183449) @joyceerhl **team**
- [ ] :runner: Revoke GitHub token on sign out [vscode#152055](https://github.com/microsoft/vscode/issues/152055) @tylerleonhardt

#### Electron
- [ ] Investigation: Electron 24/25 [vscode#184021](https://github.com/microsoft/vscode/issues/184021) @deepak1556
- [ ] Crash when closing macOS tab [vscode#167936](https://github.com/microsoft/vscode/issues/167936) @deepak1556

----
### Deferred
- [ ] :hand: PGO for VSCode Desktop [vscode#170931](https://github.com/microsoft/vscode/issues/170931) @deepak1556
- [ ] Explore a Changes editor [vscode#179000](https://github.com/microsoft/vscode/issues/179000) @lszomoru
- [ ] :runner: Improve the keybinding recording widget [vscode#178042](https://github.com/microsoft/vscode/issues/178042) [vscode#179015](https://github.com/microsoft/vscode/issues/179015) [vscode#179018](https://github.com/microsoft/vscode/issues/179018) @ulugbekna
- [ ] Explore simplifying the account menu for built-in online services [vscode-internalbacklog#3271](https://github.com/microsoft/vscode-internalbacklog/issues/3271) @tylerLeonhardt @sandy081 @aeschli
- [ ] :red_circle: ​Move Live Preview extension off of vscode-nls @andreamah
