### ISSUE TITLE
https://youtu.be/ZdSrOnuIxkU

### ISSUE THREAD

**Issue by SIMJO774478989THXXX** [microsoft/vscode#187886]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. https://youtu.be/ZdSrOnuIxkU
2. https://youtu.be/ZdSrOnuIxkU

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/187885
- [ ] connor4312/cli-service-windows-fixhttps://youtu.be/ZdSrOnuIxkU
- [ ] https://github.com/microsoft/vscode/issues/187875
- [ ] sev
- [ ] https://github.com/microsoft/vscode/pull/187884
- [ ] https://github.com/microsoft/vscode/issues/180419
- [ ] https://github.com/microsoft/vscode/pull/187749
- [ ] https://github.com/microsoft/vscode/issues/187747
- [ ] https://github.com/microsoft/vscode/pull/187787
- [ ] https://github.com/microsoft/vscode/issues/187016
- [ ] https://github.com/microsoft/vscode/pull/187883
- [ ] https://github.com/microsoft/vscode/pull/187743
- [ ] https://github.com/microsoft/vscode/issues/175262
- [ ] https://github.com/microsoft/vscode/issues/183081
- [ ] https://github.com/microsoft/vscode/issues/183686
- [ ] https://github.com/microsoft/vscode/issues/178403
- [ ] https://github.com/microsoft/vscode/issues/183703
- [ ] https://github.com/microsoft/vscode/issues/178567
- [ ] https://github.com/microsoft/vscode/issues/182742
- [ ] https://github.com/microsoft/vscode/issues/183737
- [ ] https://github.com/microsoft/vscode/issues/183729
```

**Comment by SIMJO774478989THXXX** [comment]
https://youtu.be/ZdSrOnuIxkU

**Comment by SIMJO774478989THXXX** [comment]
connor4312/cli-service-windows-fixhttps://github.com/nodejs/help.wiki.gitCODE_OF_CONDUCT.md

**Comment by SIMJO774478989THXXX** [comment]
Simjo77
https://youtu.be/ZdSrOnuIxkU

**Comment by SIMJO774478989THXXX** [comment]
https://youtu.be/ZdSrOnuIxkU

CODE_OF_CONDUCT.md

**Comment by SIMJO774478989THXXX** [comment]
[https://youtu.be/ZdSrOnuIxkU](https://youtu.be/ZdSrOnuIxkU)

**Comment by SIMJO774478989THXXX** [comment]
Onesinus983@gmail.com
