### ISSUE TITLE
bug-

### ISSUE THREAD

**Issue by zvailanu98** [microsoft/vscode#188047]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/187312
- [ ] https://github.com/microsoft/vscode/issues/188046
- [ ] https://github.com/microsoft/vscode/issues/188045
- [ ] https://github.com/microsoft/vscode/pull/187931
- [ ] https://github.com/microsoft/vscode/issues/187970
- [ ] https://github.com/microsoft/vscode/issues/188033
- [ ] https://github.com/microsoft/vscode/pull/186926
- [ ] https://github.com/microsoft/vscode/issues/187998
- [ ] https://github.com/microsoft/vscode/issues/188014
- [ ] https://github.com/microsoft/vscode/issues/188042
- [ ] https://github.com/microsoft/vscode/issues/187920
- [ ] https://github.com/microsoft/vscode/issues/187993
- [ ] https://github.com/microsoft/vscode/pull/188043
- [ ] https://github.com/microsoft/vscode/issues/188044
- [ ] https://github.com/microsoft/vscode/pull/186729
- [ ] https://github.com/microsoft/vscode/issues/187544
- [ ] https://github.com/microsoft/vscode/pull/187586
- [ ] https://github.com/microsoft/vscode/issues/169142
```
