### ISSUE TITLE
super a.i

### ISSUE THREAD

**Issue by beto811** [microsoft/vscode#189320]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/189248
- [ ] https://github.com/microsoft/vscode/issues/189283
- [ ] https://github.com/microsoft/vscode/pull/189302
- [ ] https://github.com/microsoft/vscode/pull/189317
- [ ] https://github.com/microsoft/vscode/issues/189303
- [ ] https://github.com/microsoft/vscode/issues/189316
- [ ] https://github.com/microsoft/vscode/issues/188547
- [ ] https://github.com/microsoft/vscode/issues/189254
- [ ] https://github.com/microsoft/vscode/issues/189319
- [ ] https://github.com/microsoft/vscode/issues/186279
- [ ] https://github.com/microsoft/vscode/issues/181798
- [ ] https://github.com/microsoft/vscode/issues/188781
- [ ] https://github.com/microsoft/vscode/issues/189251
- [ ] https://github.com/microsoft/vscode/issues/176074
- [ ] https://github.com/microsoft/vscode/pull/189293
- [ ] https://github.com/microsoft/vscode/issues/189315
- [ ] https://github.com/microsoft/vscode/issues/187199
- [ ] https://github.com/microsoft/vscode/issues/188413
- [ ] https://github.com/microsoft/vscode/issues/189233
- [ ] https://github.com/microsoft/vscode/pull/189321
- [ ] https://github.com/microsoft/vscode/issues/189318
- [ ] https://github.com/microsoft/vscode/issues/189266
- [ ] https://github.com/microsoft/vscode/issues/189314
- [ ] https://github.com/microsoft/vscode/issues/189285
- [ ] https://github.com/microsoft/vscode/issues/184271
- [ ] https://github.com/microsoft/vscode/issues/189268
- [ ] https://github.com/microsoft/vscode/issues/171870
- [ ] https://github.com/microsoft/vscode/issues/189215
- [ ] https://github.com/microsoft/vscode/issues/189207
- [ ] https://github.com/microsoft/vscode/issues/189167
- [ ] https://github.com/microsoft/vscode/issues/189288
- [ ] https://github.com/microsoft/vscode/issues/189235
- [ ] https://github.com/microsoft/vscode/issues/100533
- [ ] https://github.com/microsoft/vscode/issues/189218
- [ ] https://github.com/microsoft/vscode/issues/189206
- [ ] https://github.com/microsoft/vscode/pull/189311
- [ ] https://github.com/microsoft/vscode/pull/189289
- [ ] https://github.com/microsoft/vscode/issues/189234
- [ ] https://github.com/microsoft/vscode/issues/189284
- [ ] https://github.com/microsoft/vscode/issues/188760
- [ ] https://github.com/microsoft/vscode/issues/183993
- [ ] https://github.com/microsoft/vscode/pull/189259
- [ ] https://github.com/microsoft/vscode/issues/186088
- [ ] https://github.com/microsoft/vscode/pull/189177
- [ ] https://github.com/microsoft/vscode/pull/188268
- [ ] https://github.com/microsoft/vscode/issues/181709
- [ ] https://github.com/microsoft/vscode/issues/188922
- [ ] https://github.com/microsoft/vscode/issues/189313
- [ ] https://github.com/microsoft/vscode/issues/188893
- [ ] https://github.com/microsoft/vscode/issues/189312
- [ ] https://github.com/microsoft/vscode/pull/189308
- [ ] https://github.com/microsoft/vscode/issues/188871
- [ ] https://github.com/microsoft/vscode/pull/189292
- [ ] https://github.com/microsoft/vscode/pull/189310
- [ ] https://github.com/microsoft/vscode/issues/187853
- [ ] https://github.com/microsoft/vscode/issues/185155
- [ ] https://github.com/microsoft/vscode/issues/189274
- [ ] https://github.com/microsoft/vscode/pull/189304
- [ ] https://github.com/microsoft/vscode/issues/189256
- [ ] https://github.com/microsoft/vscode/issues/123111
- [ ] https://github.com/microsoft/vscode/issues/182686
- [ ] https://github.com/microsoft/vscode/issues/171082
- [ ] https://github.com/microsoft/vscode/issues/188872
- [ ] https://github.com/microsoft/vscode/issues/188108
- [ ] https://github.com/microsoft/vscode/pull/189230
- [ ] https://github.com/microsoft/vscode/issues/32840
- [ ] https://github.com/microsoft/vscode/pull/102401
- [ ] https://github.com/microsoft/vscode/pull/189322
- [ ] https://github.com/microsoft/vscode/issues/187450
- [ ] https://github.com/microsoft/vscode/issues/189106
- [ ] https://github.com/microsoft/vscode/issues/189103
- [ ] https://github.com/microsoft/vscode/issues/188566
- [ ] https://github.com/microsoft/vscode/issues/188958
- [ ] https://github.com/microsoft/vscode/issues/188874
- [ ] https://github.com/microsoft/vscode/issues/189309
- [ ] https://github.com/microsoft/vscode/issues/188873
- [ ] https://github.com/microsoft/vscode/issues/189307
- [ ] https://github.com/microsoft/vscode/issues/189030
- [ ] https://github.com/microsoft/vscode/issues/188867
- [ ] https://github.com/microsoft/vscode/issues/184777
- [ ] https://github.com/microsoft/vscode/issues/187327
- [ ] https://github.com/microsoft/vscode/issues/181801
- [ ] https://github.com/microsoft/vscode/issues/182034
- [ ] https://github.com/microsoft/vscode/issues/189305
- [ ] https://github.com/microsoft/vscode/issues/178040
- [ ] https://github.com/microsoft/vscode/issues/188449
- [ ] https://github.com/microsoft/vscode/issues/188539
- [ ] https://github.com/microsoft/vscode/issues/188349
- [ ] https://github.com/microsoft/vscode/issues/188580
- [ ] https://github.com/microsoft/vscode/pull/189323
- [ ] https://github.com/microsoft/vscode/issues/189306
- [ ] https://github.com/microsoft/vscode/issues/182848
- [ ] https://github.com/microsoft/vscode/issues/52855
- [ ] https://github.com/microsoft/vscode/issues/188587
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/189323
- [ ] https://github.com/microsoft/vscode/issues/189106
- [ ] https://github.com/microsoft/vscode/issues/188349
```
