### ISSUE TITLE
Iteration Plan for August 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#189778]
This plan captures our work in **August**. This is a 5-week iteration. We will ship in **early September**.

## Endgame
- **August 28, 2023**: Endgame begins
- **September 1, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22August+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Support go-to-symbol in the accessible view [vscode#188702](https://github.com/microsoft/vscode/issues/188702) @meganrogge
- [x] Support actions in the accessible view [vscode#189486](https://github.com/microsoft/vscode/issues/189486) @meganrogge
- [x] Allow to include the name of the focused view in the window title [vscode#97790](https://github.com/microsoft/vscode/issues/97790) @meganrogge
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22August+2023%22) @meganrogge **team**

### UX
- [x] Provide options for custom icons/colors for profiles [vscode#188972](https://github.com/microsoft/vscode/issues/188972) @hbons
- [x] Explore anchored Quick Pick component [vscode#189030](https://github.com/microsoft/vscode/issues/189030) @hbons
- [x] Improve editor toolbar toggle states [vscode#186403](https://github.com/microsoft/vscode/issues/186403) @hbons

### Workbench
- [x] Implement unfocused view dimming [vscode#30522](https://github.com/microsoft/vscode/issues/30522) @tyriar
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [ ] :runner: Add proxy support to `http2` requests in the extension host [vscode#185098](https://github.com/microsoft/vscode/issues/185098) @chrmarti
- [x] Submenu entries hover state should not be sticky [vscode#187195](https://github.com/microsoft/vscode/issues/187195) @sbatten
- [ ] Explore using watchman as backend for file watching [vscode#156964](https://github.com/microsoft/vscode/issues/156964) @bpasero
- [x] Avoid inspecting all settings during settings editor load [vscode#179486](https://github.com/microsoft/vscode/issues/179486) @rzhao271
- [x] Explore showing workspace search results in the command center [vscode#189964](https://github.com/microsoft/vscode/issues/189964) @andreamah

### vscode.dev
- None.

### Code Editor
- [x] Polish moved source code detection and rendering [vscode#187432](https://github.com/microsoft/vscode/issues/187432) @hediet
- [ ] Reduce merge conflicts by diffing both inputs against each-other [vscode#157496](https://github.com/microsoft/vscode/issues/157496) @hediet
- [ ] :runner: Explore multiple diff editors in a single scrolling editor for PR diff reviewing [vscode#179000](https://github.com/microsoft/vscode/issues/179000) @hediet @lszomoru @bpasero

### Notebook Editor
- [ ] :runner: Polish notebook sticky scroll rendering [vscode#188703](https://github.com/microsoft/vscode/issues/188703) @Yoyokrazy
- [ ] Support word highlight across notebook cell [vscode#184259](https://github.com/microsoft/vscode/issues/184259) @Yoyokrazy
- [ ] :muscle: Support trim trailing whitespace/empty lines in notebook cells [vscode#181905](https://github.com/microsoft/vscode/issues/181905) @Yoyokrazy
- [x] Support Copy Output through command/contextmenu [vscode#187152](https://github.com/microsoft/vscode/issues/187152)  @amunger
- [x] Handle missing language support in notebook cell [vscode#187516](https://github.com/microsoft/vscode/issues/187516) @amunger
- [ ] :runner: Explore support code cell symbols in Go to Symbols (sort using `:`) [vscode-jupyter#13930](https://github.com/microsoft/vscode-jupyter/issues/13930) @amunger
- [ ] :muscle: Explore scroll position improvement on execution [vscode#169038](https://github.com/microsoft/vscode/issues/169038) @amunger
- [x] Support searching output cells notebooks in the workspace [vscode#189564](https://github.com/microsoft/vscode/issues/189564) @andreamah

#### Jupyter Notebooks
- [x] Contributions to the vscode-jupyter extension [vscode-jupyter#14069](https://github.com/microsoft/vscode-jupyter/issues/14069)@rebornix **team**

### WebAssembly Support
- [x] Continue work on the Wit Parser / AST [vscode-wasm#52](https://github.com/microsoft/vscode-wasm/issues/52) @dbaeumer
- [x] Investigate executing C# in the browser using WASM/WASI [vscode-wasm#112](https://github.com/microsoft/vscode-wasm/issues/112)@dbaeumer

#### Python
- [x] Contributions to the python extension [vscode-python#21771](https://github.com/microsoft/vscode-python/issues/21771) @brettcannon **team**

#### JavaScript/TypeScript
- [ ] Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [x] Merge in initial prototype from TS [vscode#182801](https://github.com/microsoft/vscode/pull/182801) @mjbvz

#### Language Server Protocol
- None.

#### Markdown
- [ ] :runner: Add smart pasting of markdown URLs [vscode#186289](https://github.com/microsoft/vscode/issues/186289) @MeghanKulkarni
- [ ] :runner: Add drop/paste for css [vscode#189875](https://github.com/microsoft/vscode/issues/189875) @MeghanKulkarni

### Source Control
- None.

### Terminal
- [x] Add API to set terminal prompt prefix via Environment variable collection [vscode#188969](https://github.com/microsoft/vscode/issues/188969) @karrtikr
- [x] Finalize API for scoped environment variable collection [vscode#171173](https://github.com/microsoft/vscode/issues/171173) @karrtikr
- [x] Add option to disable terminal restoration [vscode#39137](https://github.com/microsoft/vscode/issues/39137) @tyriar
- [x] Faster DOM renderer [vscode#189405](https://github.com/microsoft/vscode/issues/189405) @tyriar
- [x] Toggle to disable bracketed paste mode permanently [vscode#187480](https://github.com/microsoft/vscode/issues/187480) @tyriar

### Testing
- [ ] :runner: Explore improvements to Mocha testing [vscode#189680](https://github.com/microsoft/vscode/issues/189680) @connor4312

### Debug
- [ ] :runner: Support debugging WASM files in JavaScript [vscode-js-debug#1789](https://github.com/microsoft/vscode-js-debug/issues/1789)

### API
- [ ] :runner: Explore `ShareableDataProvider` API [vscode#176316](https://github.com/microsoft/vscode/issues/176316) @joyceerhl
- [ ] :runner: Finalize port attributes API [vscode#115616](https://github.com/microsoft/vscode/issues/115616) @alexr00
- [x] API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [x] Extension packs should not open multiple welcome pages [vscode#188104](https://github.com/microsoft/vscode/issues/188104) @bhavyaus
- [x] Add tunnel activation event [vscode#188730](https://github.com/microsoft/vscode/issues/188730) @alexr00
- [ ] :muscle: Explore support for extensions to provide additional data to the issue reporter [vscode#46726](https://github.com/microsoft/vscode/issues/46726) @TylerLeonhardt

### Extension Contributions
- [x] Improvements to the Remote extensions [vscode-remote-release#8807](https://github.com/microsoft/vscode-remote-release/issues/8807) @roblourens @chrmarti @connor4312 @joyceerhl

### Documentation
- [ ] Review and update Command Line Interface (CLI) topic [vscode-docs#6435](https://github.com/microsoft/vscode-docs/issues/6435) @gregvanl
- [ ] Review and update Configure C++ Debugging topic [vscode-docs#5518](https://github.com/microsoft/vscode-docs/issues/5518) @gregvanl
- [ ] :runner: Scaffold "Custom Layout" document [vscode-docs#6393](https://github.com/microsoft/vscode-docs/issues/6393) @gregvanl

### Engineering
- [x] Clean up CLI build [vscode#178691](https://github.com/microsoft/vscode/issues/178691) @connor4312
- [ ] :hand: Use Terrapin instead of crates.io. Artifacts support for Cargo is now available in DevOps [#4353](https://github.com/microsoft/vscode-internalbacklog/issues/4353) @connor4312
- [x] Ship separate third party notice with CLI download [vscode#178691](https://github.com/microsoft/vscode/issues/178691) @connor4312
- [ ] :runner: Adopt `StorageScope.WORKSPACE` and `StorageTarget.USER` in workbench [vscode#183449](https://github.com/microsoft/vscode/issues/183449) @joyceerhl **team**

#### Electron
- [x] Update to Electron 25 [vscode#184021](https://github.com/microsoft/vscode/issues/184021) @deepak1556
- [x] Crash when closing macOS tab [vscode#167936](https://github.com/microsoft/vscode/issues/167936) @deepak1556

----
### Deferred
- [ ] Improve default theme diff colors for users with colorblindness [vscode#182173](https://github.com/microsoft/vscode/issues/182173) @hbons
- [ ] Explore improvements to notifications for users using screenreaders [vscode#183567](https://github.com/microsoft/vscode/issues/183567) @hbons
- [ ] Update color token architecture and themes in Figma toolkit [vscode-figma-toolkit#9](https://github.com/microsoft/vscode-figma-toolkit/issues/9) @hbons
- [ ] Explore notification management UX for specific extensions [vscode#41767](https://github.com/microsoft/vscode/issues/41767) @daviddossett
- [ ] :hand: PGO for VSCode Desktop [vscode#170931](https://github.com/microsoft/vscode/issues/170931) @deepak1556
- [ ] :runner: Improve the keybinding recording widget [vscode#178042](https://github.com/microsoft/vscode/issues/178042) [vscode#179015](https://github.com/microsoft/vscode/issues/179015) [vscode#179018](https://github.com/microsoft/vscode/issues/179018) @ulugbekna
- [ ] Explore simplifying the account menu for built-in online services [vscode-internalbacklog#3271](https://github.com/microsoft/vscode-internalbacklog/issues/3271) @tylerLeonhardt @sandy081 @aeschli
- [ ] :runner: Stabilize `DocumentPasteEditProvider` API to support pasting images [vscode#30066](https://github.com/microsoft/vscode/issues/30066) @mjbvz

**Comment by zhouxinghong** [comment]
https://github.com/electron/electron/releases/tag/v26.0.0
Fixes a lot of bugs included Electron 25 version

**Comment by burtek** [comment]
@kieferrm quick note, the iteration plan is duplicated (copy-pasted twice?) in your message
