### ISSUE TITLE
Review all proposed terminal APIs

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#189832]
They're stacking up, let's try push some forward as some new ones are coming in for August.

---

Checked ones are reviewed/have next steps.

- `EnvironmentVariableCollection`
  - [x] :runner: vscode.proposed.envCollectionOptions.d.ts https://github.com/microsoft/vscode/issues/179476
    - **Ready for finalization** after decision on `applyAtProcessCreation`
    - We will treat undefined as false for all members and finalize
  - [x] :arrow_right: vscode.proposed.envCollectionWorkspace.d.ts https://github.com/microsoft/vscode/issues/171173
    - @karrtikr owns, planned for this iteration
  - [x] :runner: `promptPrefix` https://github.com/microsoft/vscode/issues/188969
    - Brought to API sync 8/8, bring to 15/8
  - [x] :runner: promptPrefix https://github.com/microsoft/vscode/issues/188969
    - Still unclear what we want to do here, bring to UX sync?
- `env`
  - [x] :runner: vscode.proposed.envShellEvent.d.ts https://github.com/microsoft/vscode/issues/160694
    - The Python extension wants to use this one
    - **Ready for finalization** after decision on whether to resolve profiles before exthost launch
    - Brought to API sync 8/8, bring to 15/8
- Terminal
  - [x] :hand: vscode.proposed.terminalDataWriteEvent.d.ts https://github.com/microsoft/vscode/issues/78502
    - Frozen in proposed, updated comments
  - [x] :hand: vscode.proposed.terminalDimensions.d.ts https://github.com/microsoft/vscode/issues/55718
    - Was for Live Share but has problems (https://github.com/microsoft/vscode/issues/79246), not enough time to look into this considering its priority
  - [x] :runner: vscode.proposed.terminalQuickFixProvider.d.ts https://github.com/microsoft/vscode/issues/162950
    - Not ready for finalization, updated proposal to have a vscode command callback
  
New APIs for Copilot

- Terminal
  - [x] :runner: vscode.proposed.terminalSelection.d.ts https://github.com/microsoft/vscode/issues/188173
    - Updated proposal
    - Brought to API sync 8/8, bring to 15/8
  - [x] :runner: Terminal context menu https://github.com/microsoft/vscode/issues/79034
    - Contribution only
    - Updated proposal, approved in API sync before but additions were made
    - New additions look good, going ahead with it
  - [x] :runner: Expose shell integration command knowledge to extensions https://github.com/microsoft/vscode/issues/145234
    - Updated proposal, discuss before implementing as it's complex
    - Have some early feedback, iterate before bringing to API sync again

**Comment by Tyriar** [comment]
Above is a summary of the current state, all APIs are now tracked in the milestone/project
