### ISSUE TITLE
Tupiswif

### ISSUE THREAD

**Issue by diegohj66** [microsoft/vscode#190723]
[Swift](https://github.com/apple/swift-argument-parser.git) 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/190678
- [ ] https://github.com/microsoft/vscode/issues/189156
- [ ] https://github.com/microsoft/vscode/issues/189802
- [ ] https://github.com/microsoft/vscode/issues/189179
- [ ] https://github.com/microsoft/vscode/issues/190722
- [ ] https://github.com/microsoft/vscode/issues/190679
- [ ] https://github.com/microsoft/vscode/issues/189221
```

```[tasklist]
### Tasks
```
