### ISSUE TITLE
Diff Editor v2: options for unchanged regions

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode#190837]
I find the colored background for unchaged regions very useful, but sometimes I just prefer all regions expanded by default.
* There could be an option to **expand all regions by default**.
    * Then you could fold on demand. Hopefully with some hotkeys https://github.com/microsoft/vscode/issues/186425
    * I guess a command to expand all could do for now https://github.com/microsoft/vscode/issues/188416 but seems nicer to have a default setting too

I would also like to edit the **number of lines around the unchaged regions that are not folded**. Now its 3 lines, too few IMO.

* These lines are marked as "changed", no background coloring and no folding. I guess this is part of the change detection algorithm. Would like a setting to edit the amount.

![image](https://github.com/microsoft/vscode/assets/26868611/2134cc28-b5ce-4d66-8fba-9c113022f627)

* Or keep the same 3 lines, but add a setting to specify additional expanded lines by default. Like if I had dragged to show `N` more lines. I prefer the previous one because here the lines would fold with the "Fold Unchanged Region" button I guess.

![image](https://github.com/microsoft/vscode/assets/26868611/2088e5e7-2bcd-471a-adce-dde2402d30ee)

Clicking on the show more line expands 20 lines, let this amount be an option instead of a fixed value. I find the 20 lines ok tho.

A final idea I had was to keep the "Fold Unchanged Region" button at the left when the region is partially expanded. Atm you have to either expand all + fold or drag to hide them.

![image](https://github.com/microsoft/vscode/assets/26868611/51080990-5609-4e70-a806-7d326222b1e6)

Thanks for the updates and the great work! I can break this into multiple issues if you want.
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193979
- [ ] https://github.com/microsoft/vscode/issues/190886
- [ ] https://github.com/microsoft/vscode/issues/186425
- [ ] https://github.com/microsoft/vscode/issues/188416
- [ ] https://github.com/microsoft/vscode/issues/190887
- [ ] Diff Editor v2: UI keep both fold/expand buttons when a region is partially expanded
```

**Comment by hediet** [comment]
> Thanks for the updates and the great work! I can break this into multiple issues if you want.

Yes, this would be nice!

**Comment by dimateos** [comment]
Hey! Created the list, sorted by personal preference (kind of).

I guess full keyboard shortcuts will be the toughest to get perfect. The untouched lines around changed regions might be tricky dependng on the implementation?

I think `Diff Editor v2: setting for number of untouched lines around unchanged regions` removes the need for the following feature, hence I did not add a task for it: 
> Or keep the same 3 lines, but add a setting to specify additional expanded lines by default. Like if I had dragged to show N more lines. I prefer the previous one because here the lines would fold with the "Fold Unchanged Region" button I guess.

Feel free to discuss, edit anything, tell me to convert tasks to issues, etc...
Thanks!

**Comment by hediet** [comment]
Closing, because there are now individual issues to track this one.
