### ISSUE TITLE
Issues:code.visualstudio

### ISSUE THREAD

**Issue by Oiuyen1986** [microsoft/vscode#191098]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/191097
- [ ] https://github.com/microsoft/vscode/pull/191096
- [ ] https://github.com/microsoft/vscode/issues/190910
- [ ] https://github.com/microsoft/vscode/issues/190913
- [ ] https://github.com/microsoft/vscode/issues/191076
- [ ] https://github.com/microsoft/vscode/issues/189776
- [ ] https://github.com/microsoft/vscode/pull/191002
```
