### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Jho0nny29** [microsoft/vscode#191400]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/191403
- [ ] https://github.com/microsoft/vscode/issues/187186
- [ ] https://github.com/microsoft/vscode/pull/191348
- [ ] https://github.com/microsoft/vscode/issues/187178
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/187178
- [ ] https://github.com/microsoft/vscode/issues/187186
```

**Comment by VSCodeTriageBot** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!

**Comment by sbmelvin** [comment]
Spam
