### ISSUE TITLE
Allow hiding an existing debug toolbar item

### ISSUE THREAD

**Issue by alestiago** [microsoft/vscode#192185]
## Description

As a VS Code extension developer I would like to have the ability to:
- **Remove or hide an icon of an exiting registered command in the debug toolbar**. Sometimes, when building upon an existing debugType some of those icons might be redundant or not relevant anymore. Furthermore, sometimes an extension would like to customise certain icons; hiding and adding a new one would have the desired effect.

I do not know if the above is already possible (attaching to when clause?). 

As part of this issue, I would also like to request documentation about the debug toolbar and this feature. I think the only available information in the documentation website is a brief sentence on [Contribution Points](https://code.visualstudio.com/api/references/contribution-points). 

In addition, I also think we're missing a sample that edits the debug toolbar in [VS Code extensions samples](https://github.com/microsoft/vscode-extension-samples), it would be great to have a sample there. Let me know if I should open an issue there about this.

## Tasks

- [ ] Allow hiding an existing debug toolbar item 
- [ ] Include samples to [VS Code extensions samples](https://github.com/microsoft/vscode-extension-samples) for customising the debug toolbar.
- [ ] Include documentation about the debug toolbar, such as the groups and order shown [here](https://github.com/microsoft/vscode/blob/05f926991c9c52dff838d542c0014acd756833e2/src/vs/workbench/contrib/debug/electron-browser/debug.contribution.ts#L262).

## References
- [Allow customisation of debug toolbar (eg. additional buttons) ](https://github.com/microsoft/vscode/issues/45116)
- [Actions in the debug toolbar should be properly contributed #69153](https://github.com/microsoft/vscode/issues/69153)

(cc: @isidorn)

**Comment by alestiago** [comment]
> Are you talking about custom buttons from another extension or builtin debug commands (like step-in)

Yes I am indeed. Would it be something the team is willing to work on?

**Comment by roblourens** [comment]
No, we can't let one extension disable features from another extension
