### ISSUE TITLE
0xF18eCd99F8bb2f420303BaA3Ecb91b6B45241948

### ISSUE THREAD

**Issue by Falehfaleh** [microsoft/vscode#192779]
0xF18eCd99F8bb2f420303BaA3Ecb91b6B45241948
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/192309
- [ ] https://github.com/microsoft/vscode/pull/192781
- [ ] https://github.com/microsoft/vscode/pull/192732
- [ ] https://github.com/microsoft/vscode/issues/192729
- [ ] https://github.com/microsoft/vscode/pull/156796
- [ ] https://github.com/microsoft/vscode/issues/192780
- [ ] https://github.com/microsoft/vscode/issues/192685
- [ ] https://github.com/microsoft/vscode/issues/100335
- [ ] https://github.com/microsoft/vscode/issues/192778
- [ ] https://github.com/microsoft/vscode/issues/192754
- [ ] https://github.com/microsoft/vscode/issues/192748
- [ ] https://github.com/microsoft/vscode/issues/192770
- [ ] https://github.com/microsoft/vscode/issues/192739
- [ ] https://github.com/microsoft/vscode/issues/185298
- [x] 0xF18eCd99F8bb2f420303BaA3Ecb91b6B45241948
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/192309
- [ ] https://github.com/microsoft/vscode/pull/192781
- [ ] https://github.com/microsoft/vscode/issues/192739
- [ ] https://github.com/microsoft/vscode/pull/192732
- [ ] https://github.com/microsoft/vscode/issues/192729
- [ ] https://github.com/microsoft/vscode/pull/156796
- [ ] https://github.com/microsoft/vscode/issues/192780
- [ ] https://github.com/microsoft/vscode/issues/192685
```

**Comment by Falehfaleh** [comment]
0xF18eCd99F8bb2f420303BaA3Ecb91b6B45241948

**Comment by Falehfaleh** [comment]
0xF18eCd99F8bb2f420303BaA3Ecb91b6B45241948
