### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ReyBan82** [microsoft/vscode#192888]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/192887
- [ ] https://github.com/microsoft/vscode/issues/192884
- [ ] https://github.com/microsoft/vscode/issues/192716
- [ ] https://github.com/microsoft/vscode/issues/192792
- [ ] https://github.com/microsoft/vscode/issues/192471
```
