### ISSUE TITLE
Iteration Plan for September 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#192822]
This plan captures our work in **September**. This is a 4-week iteration. We will ship in **early October**.

## Endgame
- **September 25, 2023**: Endgame begins
- **September 29, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22September+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22September+2023%22) @meganrogge **team**
- [x] Improve Comments accessibility [vscode#192377](https://github.com/microsoft/vscode/issues/192377) @alexr00
- [x] Improve reviewing accessibility [vscode-pull-request-github#5225](https://github.com/microsoft/vscode-pull-request-github/issues/5225) @alexr00

### UX
- [ ] :runner: Update Figma toolkit to use color variables [vscode-figma-toolkit#10](https://github.com/microsoft/vscode-figma-toolkit/issues/10) @daviddossett

### Workbench
- [ ] :runner: Add CA support to `http2` requests in the extension host [vscode#185098](https://github.com/microsoft/vscode/issues/185098) @chrmarti
- [x] Explore and scope support for floating windows via `window.open` [vscode#10121](https://github.com/microsoft/vscode/issues/10121) @bpasero @tyriar
- [ ] :muscle: Polish unfocused dimming feature [vscode#191775](https://github.com/microsoft/vscode/issues/191775) @tyriar
- [ ] :muscle: Support keyboard navigation between groups in quick picks [vscode#149046](https://github.com/microsoft/vscode/issues/149046) @tylerleonhardt
- [ ] :runner: Investigate UI state syncing issues [vscode#192267](https://github.com/microsoft/vscode/issues/192267) @sandy081 @sbatten
- [x] Allow for smaller or larger tab height size [vscode#42253](https://github.com/microsoft/vscode/issues/42253) @benibenj @bpasero
- [x] Pinned tabs: show them in a secondary tab row above others [vscode#98160](https://github.com/microsoft/vscode/issues/98160) @benibenj @bpasero
- [x] :muscle: Make comment editor expandable [vscode#110403](https://github.com/microsoft/vscode/issues/110403) @alexr00
- [x] Support icons for Profiles [vscode#192386](https://github.com/microsoft/vscode/issues/192386) @sandy081
- [ ] :runner: Explore Profiles Management UX [vscode#192387](https://github.com/microsoft/vscode/issues/192387) @hbons @sandy081

### Code Editor
- [x] Explore using `ArrayBuffer` as backend for editor text contents [vscode#167719](https://github.com/microsoft/vscode/issues/167719) @rebornix
- [x] Support triggering quick fixes with `CtrlCmd+.` with the cursor positioned anywhere [vscode#191854](https://github.com/microsoft/vscode/issues/191854) @justschen

### Notebook Editor
- [x] Support trim trailing whitespace/empty lines in notebook cells [vscode#181905](https://github.com/microsoft/vscode/issues/181905) @Yoyokrazy
- [ ] :runner: Support word highlight across notebook cell [vscode#184259](https://github.com/microsoft/vscode/issues/184259) @Yoyokrazy
- [x] Explore support code cell symbols in Go to Symbols (sort using `:`) [vscode-jupyter#13930](https://github.com/microsoft/vscode-jupyter/issues/13930) @amunger
- [x] Explore scroll position improvement on execution [vscode#169038](https://github.com/microsoft/vscode/issues/169038) @amunger

#### Jupyter Notebooks
- [x] Finalize API `JupyterServerProvider` [vscode-jupyter#13894](https://github.com/microsoft/vscode-jupyter/issues/13894) and onboard AML @DonJayamanne
- [x] Explore extension recommendation for pandas dataframes viewers [vscode-jupyter#14315](https://github.com/microsoft/vscode-jupyter/issues/14315) @rebornix
- [ ] :runner: Explore supporting **Run Dependent Cells** [vscode-jupyter#14316](https://github.com/microsoft/vscode-jupyter/issues/14316) @rebornix
- [x] Support latest jupyter `notebook` 7.x API [vscode-jupyter#14215](https://github.com/microsoft/vscode-jupyter/issues/14215) @DonJayamanne
- [x] Moving Jupyter Hub support to a separate extension and support latest Jupyter Hub [vscode-jupyter#13973](https://github.com/microsoft/vscode-jupyter/issues/13973) @DonJayamanne
- [ ] :muscle: Fix custom ZMQ build for Linux ARM32/ARM64 [vscode-jupyter#14070](https://github.com/microsoft/vscode-jupyter/issues/14070) @DonJayamanne

### WebAssembly Support
- [x] Understand the implications of the proposed Resource model for VS Code's host implementation [wasm#117](https://github.com/microsoft/vscode-wasm/issues/117) @dbaeumer

### Languages
- [x] Adopt a new Perl6/Raku grammar [vscode#168319](https://github.com/microsoft/vscode/issues/168319) @alexr00

#### Python
- [x] Contributions to the python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22September+2023%22) @brettcannon **team**

#### Language Server Protocol
- [x] Ship new version of LSP [lsp#1314](https://github.com/microsoft/vscode-languageserver-node/issues/1314) @dbaeumer

#### Markdown
- [ ] :runner: Add smart pasting of markdown URLs [vscode#186289](https://github.com/microsoft/vscode/issues/186289) @mjbvz
- [ ] :runner: Add drop/paste for css [vscode#189875](https://github.com/microsoft/vscode/issues/189875) @mjbvz

### Source Control
- [ ] :runner: Ahead/behind view in SCM view container [vscode#192290](https://github.com/microsoft/vscode/issues/192290) @lszomoru

### Tasks
- [x] Tasks issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Atasks+milestone%3A%22September+2023%22) @meganrogge

### Testing
- [ ] :runner: Explore improvements to Mocha testing [vscode#189680](https://github.com/microsoft/vscode/issues/189680) @connor4312

### Debug
- [x] Support debugging WASM files in JavaScript [vscode-js-debug#1789](https://github.com/microsoft/vscode-js-debug/issues/1789) @connor4312
- [x] Support `toString` in for call-stacks [vscode-js-debug#1770](https://github.com/microsoft/vscode-js-debug/issues/1770) @connor4312

### API
- [ ] :runner: Explore `ShareableDataProvider` API [vscode#176316](https://github.com/microsoft/vscode/issues/176316) @joyceerhl
- [ ] :runner: API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [ ] :runner: Explore support for extensions to provide additional data to the issue reporter [vscode#46726](https://github.com/microsoft/vscode/issues/46726) @justschen @TylerLeonhardt

### Extension Contributions
- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22September+2023%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [x] Automatically collapse comments once they are resolved [vscode-pull-request-github#5031](https://github.com/microsoft/vscode-pull-request-github/issues/5031) @alexr00

### Documentation
- [ ] :runner: Scaffold "Custom Layout" document [vscode-docs#6393](https://github.com/microsoft/vscode-docs/issues/6393) @gregvanl

### Engineering
- [ ] :hand: Use Terrapin instead of crates.io. Artifacts support for Cargo is now available in DevOps [#4353](https://github.com/microsoft/vscode-internalbacklog/issues/4353) @connor4312
- [x] Adopt `StorageScope.WORKSPACE` and `StorageTarget.USER` in workbench [vscode#183449](https://github.com/microsoft/vscode/issues/183449) @joyceerhl **team**
- [x] Move chat view and container registration to a workbench contribution [vscode#185179](https://github.com/microsoft/vscode/issues/185179) @sbatten @roblourens
- [ ] :runner: Track memory leaks in unit tests [vscode#190503](https://github.com/microsoft/vscode/issues/190503) **team**

#### Electron
- [ ] :runner: Explore wiring `Electron.net` API into the utility process [vscode#192899](https://github.com/microsoft/vscode/issues/192899) @devm33 @deepak1556
- [x] Deprecate macOS 10.13, 10.14 [vscode#192897](https://github.com/microsoft/vscode/issues/192897) @deepak1556

----
### Deferred
- [ ] Update Figma templates to use Dark/Light Modern themes [vscode-figma-toolkit#9](https://github.com/microsoft/vscode-figma-toolkit/issues/9) @daviddossett
- [ ] Maximize current file/tab/editor [vscode#16927](https://github.com/microsoft/vscode/issues/16927)  @benibenj @bpasero
- [ ] Explore multiple diff editors in a single scrolling editor for PR diff reviewing [vscode#179000](https://github.com/microsoft/vscode/issues/179000) @hediet @lszomoru
- [ ] Allow having shorter text when pinning in language status API [vscode#192880](https://github.com/microsoft/vscode/issues/192880) @jrieken
- [ ] Adopt canonical URI Provider API for workspace trust [vscode#180582](https://github.com/microsoft/vscode/issues/180582) @sbatten
- [ ] Explore publishing the CLI to `winget` [vscode#192885](https://github.com/microsoft/vscode/issues/192885) @connor4312
- [ ] Reduce merge conflicts by diffing both inputs against each-other [vscode#157496](https://github.com/microsoft/vscode/issues/157496) @hediet
- [ ] Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [ ] :runner: Finalize port attributes API [vscode#115616](https://github.com/microsoft/vscode/issues/115616) @alexr00
- [ ] Review and update Command Line Interface (CLI) topic [vscode-docs#6435](https://github.com/microsoft/vscode-docs/issues/6435) @gregvanl
- [ ] Review and update Configure C++ Debugging topic [vscode-docs#5518](https://github.com/microsoft/vscode-docs/issues/5518) @gregvanl

**Comment by skmcgowan** [comment]
> It seems `Explore and scope support for floating windows via window.open` has been marked as finished.
> 
> When It be shiped into public?

Best news ever!  Can't wait :-)
