### ISSUE TITLE
Master 

### ISSUE THREAD

**Issue by Aein29** [microsoft/vscode#193318]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193317
- [ ] https://github.com/microsoft/vscode/issues/193316
- [ ] https://github.com/microsoft/vscode/issues/193315
- [ ] https://github.com/microsoft/vscode/issues/193305
- [ ] https://github.com/microsoft/vscode/pull/193314
- [ ] https://github.com/microsoft/vscode/issues/184021
- [ ] https://github.com/microsoft/vscode/issues/193313
- [ ] https://github.com/microsoft/vscode/issues/135127
- [ ] https://github.com/microsoft/vscode/issues/191932
- [ ] https://github.com/microsoft/vscode/pull/193310
- [ ] https://github.com/microsoft/vscode/issues/193312
- [ ] https://github.com/microsoft/vscode/issues/193295
- [ ] https://github.com/microsoft/vscode/issues/187360
- [ ] https://github.com/microsoft/vscode/issues/167719
- [ ] https://github.com/microsoft/vscode/pull/193309
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193316
- [ ] https://github.com/microsoft/vscode/issues/193313
- [ ] https://github.com/microsoft/vscode/issues/193317
- [ ] https://github.com/microsoft/vscode/issues/184021
- [ ] https://github.com/microsoft/vscode/issues/193315
- [ ] https://github.com/microsoft/vscode/issues/193305
- [ ] https://github.com/microsoft/vscode/issues/135127
- [ ] https://github.com/microsoft/vscode/pull/193314
- [ ] https://github.com/microsoft/vscode/issues/193238
- [ ] https://github.com/microsoft/vscode/issues/183456
- [ ] https://github.com/microsoft/vscode/issues/193312
- [ ] https://github.com/microsoft/vscode/issues/193295
- [ ] https://github.com/microsoft/vscode/issues/187360
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193317
- [ ] https://github.com/microsoft/vscode/issues/193316
- [ ] https://github.com/microsoft/vscode/issues/193238
- [ ] https://github.com/microsoft/vscode/issues/184021
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193315
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193317
- [ ] https://github.com/microsoft/vscode/issues/193316
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193313
- [ ] https://github.com/microsoft/vscode/issues/193305
- [ ] https://github.com/microsoft/vscode/issues/193238
- [ ] https://github.com/microsoft/vscode/issues/184021
```
