### ISSUE TITLE
.github/workflows/basic.yml

### ISSUE THREAD

**Issue by Genericreqd** [microsoft/vscode#194252]
<!
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```set
List
...
.
..
  @@//
-- 🔧 Launch with `code --disable-extensions` to check. -->


 @1. -- 🔧 Launch with `code --disable-extensions` to check. -->
2. #193923 @mojodna 
3. Help
4. Run
5. 

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by Genericreqd** [comment]
```[tasklist]
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task
```
