### ISSUE TITLE
Microsoft/vScode 

### ISSUE THREAD

**Issue by AIDAIDAOXING** [microsoft/vscode#194525]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/193974
- [ ] https://github.com/microsoft/vscode/pull/193848
- [ ] https://github.com/microsoft/vscode/issues/194212
- [ ] https://github.com/microsoft/vscode/issues/194524
- [ ] https://github.com/microsoft/vscode/issues/194523
- [ ] https://github.com/microsoft/vscode/issues/194522
- [ ] https://github.com/microsoft/vscode/issues/194392
- [ ] https://github.com/microsoft/vscode/pull/193425
- [ ] https://github.com/microsoft/vscode/issues/190116
- [ ] https://github.com/microsoft/vscode/issues/166864
- [ ] https://github.com/microsoft/vscode/issues/194521
- [ ] https://github.com/microsoft/vscode/issues/194413
- [ ] https://github.com/microsoft/vscode/pull/190462
- [ ] https://github.com/microsoft/vscode/issues/194519
- [ ] https://github.com/microsoft/vscode/issues/194507
- [ ] https://github.com/microsoft/vscode/issues/189598
- [ ] https://github.com/microsoft/vscode/issues/192086
- [ ] https://github.com/microsoft/vscode/issues/183500
- [ ] https://github.com/microsoft/vscode/issues/194482
- [ ] https://github.com/microsoft/vscode/issues/190480
- [ ] https://github.com/microsoft/vscode/issues/185055
```
