### ISSUE TITLE
Iteration Plan for October 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#195109]
This plan captures our work in **October**. This is a 4-week iteration. We will ship in **early November**.

## Endgame
- **October 23, 2023**: Endgame begins
- **October 27, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22October+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22October+2023%22) @meganrogge **team**

### UX
- [x] Update Figma toolkit to use color variables [vscode-figma-toolkit#10](https://github.com/microsoft/vscode-figma-toolkit/issues/10) @daviddossett
- [x] Update Figma templates to use Dark/Light Modern themes [vscode-figma-toolkit#9](https://github.com/microsoft/vscode-figma-toolkit/issues/9) @daviddossett

### Workbench
- [ ] :muscle: Polish unfocused dimming feature [vscode#191775](https://github.com/microsoft/vscode/issues/191775) @tyriar
- [ ] :muscle: Support keyboard navigation between groups in quick picks [vscode#149046](https://github.com/microsoft/vscode/issues/149046) @tylerleonhardt
- [x] Maximize current file/tab/editor [vscode#16927](https://github.com/microsoft/vscode/issues/16927)  @benibenj @bpasero
- [x] Allow to hide editor title section entirely (tabs, breadcrumbs) [vscode#33607](https://github.com/microsoft/vscode/issues/33607) @benibenj
- [ ] :runner: Improve Profiles Management UX [vscode#192387](https://github.com/microsoft/vscode/issues/192387) @sandy081 @hbons
- [x] Support showing the activity bar in alternate layouts [vscode#118692](https://github.com/microsoft/vscode/issues/118692) @sandy081
- [ ] :runner: Allow for floating windows [vscode#10121](https://github.com/microsoft/vscode/issues/10121) @bpasero @Tyriar
- [x] Deprecate Windows 32-bit builds [vscode-internalbacklog#4460](https://github.com/microsoft/vscode-internalbacklog/issues/4460) @joaomoreno

### Code Editor
- [x] Explore multiple diff editors in a single scrolling editor for PR diff reviewing [vscode#179000](https://github.com/microsoft/vscode/issues/179000) @hediet @lszomoru

### Comments
- None.

### Notebook Editor
- [x] Improve notebook scrolling on execution [vscode#194516](https://github.com/microsoft/vscode/issues/194516) @amunger
- [x] Improve stack trace handling and rendering [vscode#195579](https://github.com/microsoft/vscode/issues/195579) @amunger
- [x] Support word highlight across notebook cell [vscode#184259](https://github.com/microsoft/vscode/issues/184259) @Yoyokrazy

#### Jupyter Notebooks
- [x] Explore supporting **Run Dependent Cells** [vscode-jupyter#14316](https://github.com/microsoft/vscode-jupyter/issues/14316) @rebornix
- [x] Extension recommendation on datatype/mimetype [vscode-jupyter#14315](https://github.com/microsoft/vscode-jupyter/issues/14315) @rebornix
- [x] Explore moving Tensorboard support from Python extension to its own [vscode-jupyter#14472](https://github.com/microsoft/vscode-jupyter/issues/14472) @DonJayamanne
- [x] Explore requirements for Kernel API [vscode-jupyter#14487](https://github.com/microsoft/vscode-jupyter/issues/14487) @DonJayamanne @rebornix
- [ ] :muscle: Fix custom ZMQ build for Linux ARM32/ARM64 [vscode-jupyter#14070](https://github.com/microsoft/vscode-jupyter/issues/14070) @DonJayamanne

### WebAssembly Support
- [ ] :runner: Investigate compile C# code in the browser to IL using dotnet.wasm [vscode-wasm#112](https://github.com/microsoft/vscode-wasm/issues/112) @dbaeumer
- [x] Explore resource model in WIT [vscode-wasm#123](https://github.com/microsoft/vscode-wasm/issues/123) @dbaeumer

#### Python
- [x] Contributions to the python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22October+2023%22) @brettcannon **team**

#### Language Server Protocol
- [x] Explore support WASM as a first class target for LSP servers in the LSP client [vscode-languageserver-node#1337](https://github.com/microsoft/vscode-languageserver-node/issues/1337) @dbaeumer
- [ ] :runner: LSP support to 3rd-parties [vscode-python#21964](https://github.com/microsoft/vscode-python/issues/21964) @karthiknadig

### Source Control
- [ ] :runner: Ahead/behind view in SCM view container [vscode#192290](https://github.com/microsoft/vscode/issues/192290) @lszomoru

### Tasks
- None.

### Testing
- [x] Improve testing experience in self-hosting with extension test runner [vscode#189680](https://github.com/microsoft/vscode/issues/189680) @connor4312
- [ ] :muscle: Design test coverage API [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312

### Debug
- [ ] :runner: Explore rust-implemented memory profiler [vscode-js-debug#1855](https://github.com/microsoft/vscode-js-debug/issues/1855) @connor4312

### API
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [x] Explore support for extensions to provide additional data to the issue reporter [vscode#46726](https://github.com/microsoft/vscode/issues/46726) @justschen @TylerLeonhardt

### Extension Contributions
- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22October+2023%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [x] Support setting project when viewing a PR [vscode-pull-request-github#4926](https://github.com/microsoft/vscode-pull-request-github/issues/4926) @alexr00

### Documentation
- [x] Scaffold "Custom Layout" document [vscode-docs#6393](https://github.com/microsoft/vscode-docs/issues/6393) @gregvanl

### Engineering
- [x] Use Terrapin instead of `crates.io` for building the CLI [vscode#195031](https://github.com/microsoft/vscode/issues/195031) @connor4312
- [x] Explore publishing the CLI to `winget` [vscode#192885](https://github.com/microsoft/vscode/issues/192885) @connor4312
- [x] Track memory leaks in unit tests [vscode#190503](https://github.com/microsoft/vscode/issues/190503) **team**

#### Electron
- None.

----
### Deferred
- [ ] Support PR comments in notebooks [vscode-pull-request-github#3462](https://github.com/microsoft/vscode-pull-request-github/issues/3462) @alexr00
- [ ] Provide diff view inside comment card to preview suggested edits [vscode#192129](https://github.com/microsoft/vscode/issues/192129) @alexr00
- [ ] Support picking tab vs spaces in notebook cell editor [vscode#108675](https://github.com/microsoft/vscode/issues/108675) @Yoyokrazy
- [ ] Adopt canonical URI Provider API for workspace trust [vscode#180582](https://github.com/microsoft/vscode/issues/180582) @sbatten
- [ ] Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [ ] :runner: Finalize port attributes API [vscode#115616](https://github.com/microsoft/vscode/issues/115616) @alexr00
- [ ] Review and update Command Line Interface (CLI) topic [vscode-docs#6435](https://github.com/microsoft/vscode-docs/issues/6435) @gregvanl
- [ ] Review and update Configure C++ Debugging topic [vscode-docs#5518](https://github.com/microsoft/vscode-docs/issues/5518) @gregvanl
- [ ] :runner: Explore wiring `Electron.net` API into the utility process [vscode#192899](https://github.com/microsoft/vscode/issues/192899) @devm33 @deepak1556
- [ ] :runner: Add smart pasting of markdown URLs [vscode#186289](https://github.com/microsoft/vscode/issues/186289) @mjbvz
- [ ] :runner: Add drop/paste for css [vscode#189875](https://github.com/microsoft/vscode/issues/189875) @mjbvz
- [ ] :runner: Add CA support to `http2` requests in the extension host [vscode#185098](https://github.com/microsoft/vscode/issues/185098) @chrmarti
- [ ] Allow having shorter text when pinning in language status API [vscode#192880](https://github.com/microsoft/vscode/issues/192880) @jrieken

**Comment by idmadj** [comment]
Is there any plan to promote #127365 to stable?

**Comment by RichCaloggero** [comment]
Instead of using visual descriptions of icons, then requiring a screen reader user to look up and remember the meaning of the icon (i.e. "personRunning" means "work in progress"), just use "work in progress" as the icon label.
