### ISSUE TITLE
James

### ISSUE THREAD

**Issue by jamiegreen7** [microsoft/vscode#195306]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/195202
- [ ] https://github.com/microsoft/vscode/pull/195202
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/195304
```

**Comment by jamiegreen7** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> * VS Code Version:
> * OS Version:
> 
> Steps to Reproduce:
> 
> 
> ### Tasks
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
> We're having trouble rendering your tasklist, it's most likely has one of the following formatting errors:
> 
> * indented tasks (i.e. nested tasklist; support for this is coming!)
> * an empty task (i.e. `- [ ]` on a line by itself)
> * any empty new lines (before/after the tasklist or in between tasks)
> * duplicate issue/pr links
> * a draft task exceeds 512 characters
> 
> Please check the [ tasklists documentation ](https://docs.github.com/issues/managing-your-tasks-with-tasklists/creating-a-tasklist#creating-tasklists-with-markdown) for more information. [ 🔗 Feedback Discussion ](https://github.com/orgs/community/discussions/39106?sort=new) 
> 
> Thank you for participating in the Private Beta ❤️
> No tasks being tracked yet.
> 1. [ ] 
>                    
>                  
>    
>                  
>                    
>                      
>    
>                    
>                      
>                  
>                
>                
>                  
>      
>        
>          
>        
>    
>      Options
>    
>    
>    
>      
>        
>          
>            
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
> 2. 
> 
> ### Tasks
> 
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
>  
> 1. [
>            Add steps to SDL pipeline
>    
>          #195304
>    
>        ](https://github.com/microsoft/vscode/pull/195304)
>      
>    
>          
>            
>              
>        
>    
>    
>            
>          
>    
>        
>          
>          
>        
>    
>        
>          
>    
>            
>    
>                +0
>          
>            
>            
>      
>        
>                    
>    
>                  
>    
>    
>          
>    
>          
>            
>      
>          <img alt="rzhao271" width="20" height="20" src="https://avatars.githubusercontent.com/u/7199958?v=4">
