### ISSUE TITLE
Devil

### ISSUE THREAD

**Issue by Devil7-coder** [microsoft/vscode#196032]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/176215
- [ ] https://github.com/microsoft/vscode/issues/195579
- [ ] https://github.com/microsoft/vscode/issues/195946
- [ ] https://github.com/microsoft/vscode/pull/196030
- [ ] https://github.com/microsoft/vscode/pull/196024
```
