### ISSUE TITLE
Voice: allow to respond chat contents with voice for a true conversation

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#196261]
Now I want to hear Copilot respond. It is a nice pair, I talk and I hear the response back. Ideally there is some easy toggle to mute Copilot.
```[tasklist]
### Tasks
- [ ] Explore UI of others (Bing, OpenAI)
- [ ] Auto synthesise when voice was used by changing mic icon to speaker icon
- [ ] Have action per chat block to synthesize
- [ ] Explore SML: can it be used to control playback speed or skip over code?
```

**Comment by isidorn** [comment]
Yup - I like that flow 😍

**Comment by SPiercer** [comment]
upvoting since the new "Hey Code" feature is out it would be amazing

**Comment by ssalbdivad** [comment]
I've been looking for this feature since Chat was announced.

Would be a great way to rubber duck and make chat much more helpful in complex projects where it doesn't do as well providing code directly.

**Comment by bpasero** [comment]
Pointer: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-speech-synthesis?tabs=browserjs%2Cterminal&pivots=programming-language-cpp

**Comment by bpasero** [comment]
A first version is in insiders:
- chat responses have a 🔈 icon to start text-to-speech
- text-to-speech starts automatically for when voice is used as input to chats
- there is a new setting `accessibility.voice.autoSynthesize` that controls that behaviour
- we support all voice languages that we support in `accessibility.voice.speechLanguage`
