### ISSUE TITLE
Update to Electron 27

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#196941]
```[tasklist]
### Todo
- [x] Update patches
- [x] Update native modules
- [ ] Nightly Exploration builds
- [ ] Update/Check LICENSE file in CG for new node.js version
- [ ] Update LICENSE for new ffmpeg version
```

**Comment by lppedd** [comment]
Looking forward to Electron 28 with Chromium 120.  
This will enable shipping WASM binaries with GC enabled without messing with flags.
