### ISSUE TITLE
Iteration Plan for November 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#197438]
This plan captures our work in **November**. This is a 5-week iteration. We will ship in **early December**.

## Endgame

- **November 27, 2023**: Endgame begins
- **December 1, 2023**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22November+2023%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility

- [ ] :runner: Show icon only button tooltips [vscode#132344](https://github.com/microsoft/vscode/issues/132344) @meganrogge
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22November+2023%22) @meganrogge **team**

### UX

- [x] Improve built-in walkthroughs [vscode#197503](https://github.com/microsoft/vscode/issues/197503) @daviddossett

### Workbench

- [x] Allow for floating windows [vscode#10121](https://github.com/microsoft/vscode/issues/10121) @bpasero @Tyriar
- [ ] :runner: Explore the ability to hide problem markers throughout the workbench [vscode#166797](https://github.com/microsoft/vscode/issues/166797) @justschen
- [x] Tree: Support sticky scroll [vscode#161207](https://github.com/microsoft/vscode/issues/161207) @benibenj

### Code Editor

- [x] Fix hanging UI when code action widget has many entries [vscode#196857](https://github.com/microsoft/vscode/issues/196857) @justschen
- [x] Address poor code actions sort order with multiple fixes on same line [vscode#197162](https://github.com/microsoft/vscode/issues/197162) @justschen
- [x] Migrate users from from `boolean`-based code actions on save to `enum` [vscode#197161](https://github.com/microsoft/vscode/issues/197161) @justschen
- [x] Multi File Diff Editor [vscode#179000](https://github.com/microsoft/vscode/issues/179000) @hediet
- [ ] Support dynamic line heights using decorations [vscode#194609](https://github.com/microsoft/vscode/pull/194609) @hediet @alexdima

### Comments

- None.

### Notebook Editor

- [ ] :runner: Explore built-in "variable explorer" notebook functionality [vscode#165445](https://github.com/microsoft/vscode/issues/165445) @amunger
- [ ] :runner: Multi-document highlighter API proposal and enhancements [vscode#184259](https://github.com/microsoft/vscode/issues/184259) @Yoyokrazy
- [ ] Support picking tab vs spaces in notebook cell editor [vscode#108675](https://github.com/microsoft/vscode/issues/108675) @Yoyokrazy

#### Jupyter Notebooks

- [ ] Kernel API finalization @DonJayamanne
  - [x] API proposal and adoption plans for 3rd party extensions [vscode-jupyter#14669](https://github.com/microsoft/vscode-jupyter/issues/14669)
  - [x] Explore UX for code execution permissions for third-party extensions [vscode-jupyter#14669](https://github.com/microsoft/vscode-jupyter/issues/14685)
- [x] Explore enabling Non-Python kernel auto complete [vscode-jupyter#14672](https://github.com/microsoft/vscode-jupyter/issues/14672) @DonJayamanne
- [ ] :muscle: Explore Kernel Picker experience in Dev Containers [vscode-jupyter#14673](https://github.com/microsoft/vscode-jupyter/issues/14673) @DonJayamanne @rebornix
- [ ] Support module import/usage analysis in **Run Dependent Cells** [vscode-jupyter#14674](https://github.com/microsoft/vscode-jupyter/issues/14674) @rebornix w/ Pylance team

### WebAssembly Support

- [ ] :runner: Investigate compile C# code in the browser to IL using dotnet.wasm [vscode-wasm#112](https://github.com/microsoft/vscode-wasm/issues/112) @dbaeumer
- [x] Test the threading support in Python WASM [vscode-wasm#148](https://github.com/microsoft/vscode-wasm/issues/148) @dbaeumer
- [ ] :runner: Support WASI preview2 [vscode-wasm#52](https://github.com/microsoft/vscode-wasm/issues/52) @dbaeumer

#### Python

- [x] Contributions to the python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22November+2023%22) @brettcannon **team**

#### Language Server Protocol

- [ ] :runner: LSP support to 3rd-parties [vscode-python#21964](https://github.com/microsoft/vscode-python/issues/21964) @karthiknadig

### Source Control

- [x] Ahead/behind view in SCM view container [vscode#192290](https://github.com/microsoft/vscode/issues/192290) @lszomoru

### Tasks

- None.

### Terminal

- [x] Sticky scroll in the terminal [vscode#172742](https://github.com/microsoft/vscode/issues/172742) @tyriar
- [ ] :muscle: Explore quick fixes attached to rows in sticky scroll [vscode#198116](https://github.com/microsoft/vscode/issues/198116)@tyriar
- [x] Highlight terminal commands subtly when mousing over them [vscode#196634](https://github.com/microsoft/vscode/issues/196634) @tyriar

### Testing

- [ ] :runner: Design test coverage API [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312
- [x] API for selected run profiles (playwright ask) [vscode#193160](https://github.com/microsoft/vscode/issues/193160) @connor4312
- [x] Support find in the test output panel [vscode#193589](https://github.com/microsoft/vscode/issues/193589) @connor4312

### Debug

- [x] Rust-based heap snapshot tooling [vscode-js-debug#1855](https://github.com/microsoft/vscode-js-debug/issues/1855) @connor4312
- [x] Investigate extension point for data visualization [vscode#197287](https://github.com/microsoft/vscode/issues/197287) @connor4312

### API

- [ ] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2023%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2023%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions

- [x] Support finer-grained control over extension auto-updates [vscode#194188](https://github.com/microsoft/vscode/issues/194188) @sandy081

### Extension Contributions

- [x] GHPRI: Support merge queues [vscode-pull-request-github#5402](https://github.com/microsoft/vscode-pull-request-github/issues/5402) @alexr00
- [ ] :muscle: Allow users to resolve merge conflicts from PR view [vscode-pull-request-github#1562](https://github.com/microsoft/vscode-pull-request-github/issues/1562) @alexr00
- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22November+2023%22) @roblourens @chrmarti @connor4312 @joyceerhl

### Documentation

- None.

### Engineering

- [x] Gather heap metrics from CI [vscode#191920](https://github.com/microsoft/vscode/issues/191920) @connor4312
- [ ] :hand: Deprecate macOS 10.13, 10.14 [vscode#192897](https://github.com/microsoft/vscode/issues/192897) @deepak1556
- [x] Update build agent distros [vscode-linux-build-agent#41](https://github.com/microsoft/vscode-linux-build-agent/issues/41) @deepak1556

#### Electron

- [x] Update to Electron 27 [vscode#196941](https://github.com/microsoft/vscode/issues/196941) @deepak1556
- [ ] :runner: Wire `Electron.net` API into the utility process [vscode#192899](https://github.com/microsoft/vscode/issues/192899) @deepak1556
- [ ] :runner: WCO on Windows leaves no room for resizing horizontally/diagonally [vscode#185249](https://github.com/microsoft/vscode/issues/185249) @rzhao271

---

### Deferred

- [ ] Polish unfocused dimming feature [vscode#191775](https://github.com/microsoft/vscode/issues/191775) @tyriar
- [ ] Fix custom ZMQ build for Linux ARM32/ARM64 [vscode-jupyter#14070](https://github.com/microsoft/vscode-jupyter/issues/14070) @DonJayamanne
- [ ] Adopt canonical URI Provider API for workspace trust [vscode#180582](https://github.com/microsoft/vscode/issues/180582) @sbatten
- [ ] Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [ ] :runner: Add smart pasting of markdown URLs [vscode#186289](https://github.com/microsoft/vscode/issues/186289) @mjbvz
- [ ] :runner: Add drop/paste for css [vscode#189875](https://github.com/microsoft/vscode/issues/189875) @mjbvz
- [ ] Support keyboard navigation between groups in quick picks [vscode#149046](https://github.com/microsoft/vscode/issues/149046) @tylerleonhardt
- [ ] :runner: Improve Profiles Management UX [vscode#192387](https://github.com/microsoft/vscode/issues/192387) @sandy081 @hbons

**Comment by DawallAZllon91** [comment]
Revision
