### ISSUE TITLE
33

### ISSUE THREAD

**Issue by BTCRob1993** [microsoft/vscode#197452]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/197451
- [ ] https://github.com/microsoft/vscode/issues/197423
- [ ] https://github.com/microsoft/vscode/issues/197450
- [ ] https://github.com/microsoft/vscode/issues/28795
- [ ] https://github.com/microsoft/vscode/issues/197420
- [ ] https://github.com/microsoft/vscode/pull/196204
- [ ] https://github.com/microsoft/vscode/issues/185064
```

**Comment by starball5** [comment]
1. ... what is this?
2. https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
