### ISSUE TITLE
https://github.com/lunapaint/vscode-luna-paint.wiki.git

### ISSUE THREAD

**Issue by mohib4445** [microsoft/vscode#197983]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/197979
- [ ] https://github.com/microsoft/vscode/issues/197981
- [ ] https://github.com/microsoft/vscode/issues/197982
- [ ] https://github.com/microsoft/vscode/pull/197961
- [ ] https://github.com/microsoft/vscode/issues/197214
- [ ] https://github.com/microsoft/vscode/issues/197978
- [ ] https://github.com/microsoft/vscode/issues/197865
- [ ] https://github.com/microsoft/vscode/issues/194871
- [ ] https://github.com/microsoft/vscode/issues/197980
- [ ] https://github.com/microsoft/vscode/issues/197144
- [ ] https://github.com/microsoft/vscode/issues/192031
- [ ] https://github.com/microsoft/vscode/issues/192744
- [ ] https://github.com/microsoft/vscode/issues/197977
```
