### ISSUE TITLE
febeling/edit-distance

### ISSUE THREAD

**Issue by infoalbertkin55** [microsoft/vscode#198967]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/198962
- [ ] https://github.com/microsoft/vscode/pull/198966
- [ ] https://github.com/microsoft/vscode/pull/198964
- [ ] https://github.com/microsoft/vscode/pull/198963
- [ ] https://github.com/microsoft/vscode/issues/66750
- [ ] https://github.com/microsoft/vscode/pull/198960
- [ ] https://github.com/microsoft/vscode/issues/197334
- [ ] https://github.com/microsoft/vscode/pull/198965
- [ ] https://github.com/microsoft/vscode/issues/198920
- [ ] https://github.com/microsoft/vscode/issues/198788
- [ ] https://github.com/microsoft/vscode/pull/198961
- [ ] https://github.com/microsoft/vscode/issues/198947
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/198962
```

**Comment by infoalbertkin55** [comment]
> 
> 
> 
> 
> 
> 
> 
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> 
> 
> - VS Code Version: 
> - OS Version: 
> 
> Steps to Reproduce:
> 
> 1. 
> 2. 
>
