### ISSUE TITLE
See

### ISSUE THREAD

**Issue by whitemossyoak64** [microsoft/vscode#199688]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/199687
- [ ] https://github.com/microsoft/vscode/issues/162712
- [ ] https://github.com/microsoft/vscode/issues/199684
- [ ] https://github.com/microsoft/vscode/pull/198594
- [ ] https://github.com/microsoft/vscode/issues/199577
- [ ] https://github.com/microsoft/vscode/pull/199685
- [ ] https://github.com/microsoft/vscode/issues/199441
- [ ] https://github.com/microsoft/vscode/issues/199681
- [ ] https://github.com/microsoft/vscode/pull/199680
- [ ] https://github.com/microsoft/vscode/issues/196730
- [ ] https://github.com/microsoft/vscode/issues/199671
- [ ] https://github.com/microsoft/vscode/issues/162286
```

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```
