### ISSUE TITLE
February Iteration Plan

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#20021]
This plan captures what we work on during February. We will ship **early March**.

Not unusual and still noteworthy: We will do several explorations that might or might not result in concrete deliverables in this or later releases.

The endgame for this iteration is tracked in #20981.

## Plan Items

Below is a summary of the top level plan items.

Legend for annotations:

| Mark  | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Workbench
- [x] Evolve welcome experience and react to feedback @chrmarti 
- [x] Keybindings for explorer to enable VIM style navigation @bpasero
- [x] Render chording short cuts in the menus @bpasero
- Tasks
  - [x] Provide additional terminal APIs and functionality #15179 #12000 #18454 @Tyriar
  - [x] Define v2 of `task.json`, v2 shows the task output in the terminal  @dbaeumer
  - [x] Support to assign keybindings to tasks @dbaeumer 
- [x] Search: Explore search implementation based on [Silver Searcher](https://github.com/ggreer/the_silver_searcher) #19983 @roblourens
- [x] Move the preferences for theme, icon theme from local storage to settings #7358 @aeschli @sandy081
- [x] Linux auto update/auto signing #229 #2973 @Tyriar 

### Editor
- [x] Initial version of Minimap support #4865 @alexandrudima
- [x] Add ability to copy formatted code to clipboard #3518 @rebornix
- [x] Support to drag and drop selected text #1046 @rebornix 

### Languages
- C#
  - [x] Bundle the C# TextMate grammar https://github.com/Microsoft/vscode/issues/19469 @aeschli
- TypeScript/JavaScript
  - [x] TS 2.2 adoption #20162 @mjbvz
  - [x] More `tsconfig.json` validation  (see also Microsoft/TypeScript#12336) #20163
  - [x] Explore improved language support for JSDoc comments #20161 @mjbvz
  - [x] Transfer tmGrammar ownership #20160 @mjbvz @aeschli
- HTML
  - [x] Analyze Live preview options @waderyan

### Debugging
- [x] Evolve `node2` and `node` into a single node debugging experience #19650 @weinand @roblourens 
- [x] Column break points #14784 @isidorn @weinand 
- [x] Improve the UI when an exception is thrown #16860 @isidorn @michelkaporin 
- [x] DAP: Support for getting information about a thrown exception Microsoft/vscode-debugadapter-node#97 @weinand
- [x] Ability to select a launch configuration and start a debug target using keyboard #16613 @isidorn @michelkaporin 
- [x] Exploration: Live Edit #6930 @weinand @roblourens
- [x] Exploration: Async Stackframes #5552 @roblourens @weinand 

### Extension Authoring
- [x] Initial version of Source Control Provider API (API will still be in proposed state end of February) #15894 @joaomoreno
- [x] API to show a modal confirmation (required for SCM API) @joaomoreno 
- [x] Support that an extension can contribute and define its default language settings #19733 @sandy081

### Contributions to Extensions
- [ ] :running_man: php parser completion and investigate contribution @mousetraps
- [x] Go - support single file debugging without a launch config and add configuration snippets @ramya-rao-a
- [x] Docker – update [dockerfile_lint](https://github.com/projectatomic/dockerfile_lint) version @chrisdias
- [x] Docker – support running windows containers @chrisdias @lostintangent 
- [x] Docker – support running Azure CLI in a container @chrisdias

### Engineering Items
- [x] Investigate into next Electron update @bpasero
- [x] Performance test infrastructure for start-up performance @jrieken
- [x] Adopt @ types in our bundled extensions #20164 @mjbvz 
- [x] Start website for tools that help us managing issues and releases @sandy081 
- [ ] :running_man: Consolidate telemetry infrastructure @ramya-rao-a

### Deferred
- Investigate into implementing 'multi root workspaces', 'multi folder' workspaces @bpasero
- Additional theming options in the workbench (colors, fonts) #3112 @aeschli @bpasero
- Investigate more types for CompletionItemKind enum #2628 @jrieken
- Startup performance: provide a dashboard @jrieken, @seanmcbreen
- Exploration: configuration UI for exception hierarchies #18093 @weinand
- :hand: Support large extension, adopt new marketplace support #18146 @joaomoreno
- :hand: Adopt cancellation token support #18053 @mjbvz 
----
- Keyboard layout improvements #17521 @alexandrudima
- Support to contribute to task creation (template) and to contribute problem matchers @dbaeumer 
- Go - debug Intellisense support in the Debug Console @ramya-rao-a
- Move lines up/down with auto indent @rebornix
- Go - Support to run without a debugger attached @ramya-rao-a

**Comment by alexdresko** [comment]
If "Explore: Move the preferences for theme, icon theme from local storage to settings @aeschli @sandy081" means per-workspace theme settings, then YES PLEASE!

**Comment by LiPengfei19820619** [comment]
I expect this feature to appear in the iteration plan, thanks.
#5388

**Comment by soulchainer** [comment]
Hoping that the «HTML: Analyze Live preview options» , will solve, eventually, the problems with some of the HTML preview extensions available :D.
Basically: «not working» or «only working when the HTML tab is focused and the changes are done directly in the tab» (rendering it useless if you use any kind of template engine that generates HTML).

**Comment by waderyan** [comment]
@soulchainer what HTML preview extensions have you tried? Can you send me an email wade.anderson@microsoft.com?

**Comment by egamma** [comment]
Closing 1.10 has shipped.
