### ISSUE TITLE
GitHub Copilot recommends professional legal advice is necessary to decide if it's OK to use GitHub Copilot to develop AI

### ISSUE THREAD

**Issue by bionicles** [microsoft/vscode#200271]
Does this issue occur when all extensions are disabled?: Not if Copilot is off, which I turned off after I realized this issue, and canceled my sub. 

- VS Code Version: 1.85.0
- OS Version: Win 11 Fall 2023

Steps to Reproduce:

0. Ask Github Copilot if it can help develop AI. Wait for the affirmative response.
1. Quote this Microsoft AI Term of Use https://archive.ph/N5iVq#selection-1895.0-1897.140 to GitHub Copilot. 

> AI Services.
> ”AI services” are services that are labeled or described by Microsoft as including, using, powered by, or being an Artificial Intelligence (“AI”) system.
> ...
> - Limits on use of data from the AI Services. You may not use the AI services, or data from the AI services, to create, train, or improve (directly or indirectly) any other AI service. 

3. Wait for the weak, fair and balanced initial wishy washy response.
4. Request a stronger response based on factual matters of [United States antitrust law](https://en.wikipedia.org/wiki/United_States_antitrust_law) such as the [Sherman Antitrust Act of 1890](https://en.wikipedia.org/wiki/Sherman_Antitrust_Act), [Addyston Pipe & Steel Co. v. United States](https://en.wikipedia.org/wiki/Addyston_Pipe_%26_Steel_Co._v._United_States), or, ironically, [United States v. Microsoft Corp](https://law.justia.com/cases/federal/district-courts/FSupp2/87/30/2307082/) ... and basic logic
5. Observe:

![Screenshot 2023-12-06 141137](https://github.com/microsoft/vscode/assets/24532336/132fcf9d-28b3-4570-bde2-31849fc274d6)

?

Is this a _bug_ because GitHub Copilot is a Microsoft AI Service willing to help create, train, or improve (directly or indirectly) any other AI service?

Or is this a _feature_ intended to just work, and Microsoft's Legal Team is clearly in flagrant violation of basic [business ethics](https://en.wikipedia.org/wiki/Business_ethics) and the [History of United States Antitrust Law](https://en.wikipedia.org/wiki/History_of_United_States_antitrust_law) ?

BTW, If you guys blow this off, I'm going to contact the Department of Justice about criminal activity, and I'm not joking.

```[tasklist]
### Tasks
- [x] Clarify Legal Status of GitHub Copilot for AI Development
- [ ] Modify Microsoft AI Terms of Use to Stop Breaking United States Antitrust Law
- [x] Contact the Department of Justice about criminal activity, because I wasn't joking
```

**Comment by bionicles** [comment]
@digitarald see task list, issue persists, guess ill "Clarify Legal Status of GitHub Copilot for AI Development" since I already completed "Contact the Department of Justice about criminal activity, because I wasn't joking" (and notified the Washington State Attorney General) 

![Screenshot 2023-12-19 145415](https://github.com/microsoft/vscode/assets/24532336/2c6e745b-3f83-4f18-be72-2deaea852f57)
![federal_antitrust_criminal_law_enforcement_primer_highlighted](https://github.com/microsoft/vscode/assets/24532336/eb3d9c1c-498b-4ee3-acef-eed177377c86)

### Explicit WA Law Noncompetitive Covenant for Federal Monopolization Offense on record today 2023-12-19 https://archive.ph/wip/1GPy7

Please note: the state of Washington https://app.leg.wa.gov/rcw/default.aspx?cite=49.62&full=true
![Screenshot 2023-12-19 153204](https://github.com/microsoft/vscode/assets/24532336/e96d19af-1970-453e-99bf-5dd05c64e475)
![Screenshot 2023-12-19 153207](https://github.com/microsoft/vscode/assets/24532336/0a7cf213-4f14-4683-bf43-33bb46f4a8da)
![image](https://github.com/microsoft/vscode/assets/24532336/6d342fa5-5a7c-4929-bbc5-4fb9a6c39f30)
![Screenshot 2023-12-19 153113](https://github.com/microsoft/vscode/assets/24532336/059b2b6b-4854-49d7-b185-dca7a0fe0d91)

# In the spirit of Chapter 49.62 RCW, NONCOMPETITION COVENANTS, 

[RCW (Revised Code of Washington) 49.62.030](https://app.leg.wa.gov/rcw/default.aspx?cite=49.62&full=true)

**Can lack of employment of harmed parties be justified as an excuse to apply non-compete clauses even more broadly to customers and other people who do not even work at the company who defines the relevant agreement limiting competition?**

## Opinion of Bion Howard (Claimant and Harmed Party)

1. Given employee noncompete is void in Washington, and the spirit of the relevant law is to broadly prevent such restraint of trade by noncompetition covenants (agreements limiting competition) which were already found to be unreasonable by Washington State Legislature.
2. Then, customer noncompete, an even more general form of noncompetition covenant, without even the already rejected attempted justification of employment, cannot be considered lawful under these provisions, 
3. Because customer noncompete would be an even worse, more unfair, and more unreasonable application of the underlying rejected concept of **agreements limiting competition** exemplified by employee noncompete clauses as voided by Washington.
4. Furthermore, predicting Microsoft will argue (c) a covenant prohibiting use or disclosure of trade secrets or inventions; is relevant, we point to the fact that Microsoft GitHub Copilot output is not secret (they send it directly to the user) and invention, according to the USPTO (United States Patent and Trademark Office), requires both:
   - 4.1. Natural Personhood (i.e. being a human being -- notwithstanding the clear capability of AI to generate inventive content, which I do not dispute) [See 43 F.4th 1207 (Fed. Cir. 2022).](https://cafc.uscourts.gov/opinions-orders/21-2347.OPINION.8-5-2022_1988142.pdf) found at [Artificial Intelligence Inventions Are Patentable Under U.S. Patent Law, Even If Artificial Intelligence Can’t Be An Inventor](https://www.crowell.com/en/insights/client-alerts/artificial-intelligence-inventions-are-patentable-under-us-patent-law-even-if-artificial-intelligence-cant-be-an-inventor#:~:text=Vidal%2C%20the%20Federal%20Circuit%20affirmed,Cir.)
   - 4.2. Approval of a Patent Application by the USPTO.

Or, more simply, AI can invent, but a natural person needs to submit papers and be approved. It's not a trade secret, it's not an invention unless Microsoft wants to wait around for patent approval on every Microsoft GitHub Copilot "Output."

Therefore, the ["Microsoft Services Agreement - 14. Service-Specific Terms - q. AI Services - iii. Limits on use of data from the AI Services. You may not use the AI services, or data from the AI services, to create, train, or improve (directly or indirectly) any other AI service." Noncompetition Covenant](https://archive.ph/1GPy7#selection-3467.0-3471.139) 

according to  ["You and we irrevocably consent to the exclusive jurisdiction and venue of the state or federal courts in King County, Washington, for all disputes arising out of or relating to these Terms or the Services that are not heard in arbitration or small claims court."](https://archive.ph/1GPy7#selection-2283.353-2283.614) 

is **almost surely void right now** according to the [Aforementioned Noncompetition Covenant Revised Code of Washington](https://app.leg.wa.gov/rcw/default.aspx?cite=49.62&full=true), 

and is almost surely a **federal court felony monopolization offense** according to the [U.S. Department of Justice Antitrust Division FEDERAL ANTITRUST CRIME PRIMER FOR LAW ENFORCEMENT](https://www.justice.gov/media/967286/dl?inline) also pictured above.

Dang, man, nice corporate legal team you there. Wouldn't it a shame if somebody reported [this](https://en.wikipedia.org/wiki/Illegal_agreement) to the State and Federal authorities, @digitarald? 

10/10 response time!!!

**Comment by digitarald** [comment]
Regarding the initial _Steps to Reproduce_, given that AI can be inaccurate I can't recommend to ask it for legal advice.

To your other points:

Copilot's product specific terms are available here: https://docs.github.com/en/site-policy/github-terms/github-terms-for-additional-products-and-features#github-copilot

They in turn reference the acceptable use policies: https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies

General trust questions are also outlined in https://resources.github.com/copilot-trust-center/ , which also has a _contact us_ link in case you need more details.
