### ISSUE TITLE
JloiiiJlgow_save

### ISSUE THREAD

**Issue by ksh5a** [microsoft/vscode#200459]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/200458
- [ ] https://github.com/microsoft/vscode/issues/12588
- [ ] https://github.com/microsoft/vscode/issues/158669
- [ ] https://github.com/microsoft/vscode/issues/200383
- [ ] https://github.com/microsoft/vscode/issues/195381
- [ ] https://github.com/microsoft/vscode/issues/195863
- [ ] https://github.com/microsoft/vscode/issues/196332
- [ ] https://github.com/microsoft/vscode/issues/195031
- [ ] https://github.com/microsoft/vscode/issues/196047
- [ ] https://github.com/microsoft/vscode/issues/198586
- [ ] https://github.com/microsoft/vscode/issues/195333
- [ ] https://github.com/microsoft/vscode/issues/196200
```
