### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by bonzzo2014** [microsoft/vscode#200518]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/200495
- [ ] https://github.com/microsoft/vscode/issues/192290
- [ ] https://github.com/microsoft/vscode/issues/200517
- [ ] https://github.com/microsoft/vscode/pull/200468
- [ ] https://github.com/microsoft/vscode/issues/200512
```

**Comment by VSCodeTriageBot** [comment]
Thanks for creating this issue! We figured it's missing some basic information or in some other way doesn't follow our [issue reporting guidelines](https://aka.ms/vscodeissuereporting). Please take the time to review these and update the issue.

Happy Coding!

**Comment by bonzzo2014** [comment]
https://opensource.microsoft.com/codeofconduct/faq
