### ISSUE TITLE
Iteration Plan for January 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#201255]
This plan captures our work in **January**. This is a 4-week iteration. We will ship in **early February**.

## Endgame
- **January 23, 2024**: Endgame begins
- **January 26, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22December+%2F+January+2024%22).

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Consider alert instead of audio cue for components [vscode#195282](https://github.com/microsoft/vscode/issues/195282) @meganrogge
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22December+%2F+January+2024%22) @meganrogge **team**
- [x] GHPRI Accessibility issues, see [query](https://github.com/microsoft/vscode-pull-request-github/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22December+%2F+December+%2F+January+2024%22) @alexr00

### Workbench
- [x] Explore the ability to hide problem markers throughout the workbench [vscode#166797](https://github.com/microsoft/vscode/issues/166797) @justschen
- [x] Aux window: Support to restore aux windows and editors [vscode#195887](https://github.com/microsoft/vscode/issues/195887) @bpasero
- [x] Tree Sticky Scroll Support Focus & Navigation [vscode#199373](https://github.com/microsoft/vscode/issues/199373) @benibenj
- [x] Tree Sticky Scroll: Support node compression [vscode#199539](https://github.com/microsoft/vscode/issues/199539) @benibenj
- [x] Support title bar within native title bar [vscode#172464](https://github.com/microsoft/vscode/issues/172464) @benibenj
- [x] Support drag and drop between items in the list [vscode#200745](https://github.com/microsoft/vscode/issues/200745) @benibenj
- [ ] :runner: Localize inno-updater [vscode#168894](https://github.com/microsoft/vscode/issues/168894) @benibenj
- [x] Polish Multi-File Diff Editor [vscode#201718](https://github.com/microsoft/vscode/issues/201718) @hediet
- [x] Windows: Investigate changes to API behavior for Wi-Fi access and location [vscode#196746](https://github.com/microsoft/vscode/issues/196746) @deepak1556

### Code Editor
- [ ] :runner: Support dynamic line heights using decorations [vscode#194609](https://github.com/microsoft/vscode/pull/194609) @hediet @alexdima
- [x] Release Monaco Editor https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0450 @hediet
- [x] Slowly roll out editor sticky scroll on by default [vscode#202655](https://github.com/microsoft/vscode/issues/202655) @aiday-mar
- [x] Allow to customize the font family for inline completions [vscode#201307](https://github.com/microsoft/vscode/issues/201307) @aiday-mar @hediet
- [ ] :runner: Add support for multicursor for inline completions [vscode#201308](https://github.com/microsoft/vscode/issues/201308) @aiday-mar @hediet
- [ ] :runner: Allow code actions to highlight their related code ranges [vscode#199608](https://github.com/microsoft/vscode/issues/199608) @justschen

### Search
- [x] Improve the ergonomics between Quick Search and the Search view [vscode#201735](https://github.com/microsoft/vscode/issues/201735) @andreamah
- [x] Show matches in a preview editor when navigating quick search results [vscode#191259](https://github.com/microsoft/vscode/issues/191259) @andreamah

### Notebook Editor
- [x] Notebook sticky scroll refinement (font-family/icon/folding) [vscode#188974](https://github.com/microsoft/vscode/issues/188974) @Yoyokrazy
- [ ] :runner: Built-in variable view UI [vscode#165445](https://github.com/microsoft/vscode/issues/165445) @amunger
- [x] Support notebook editor in floating window [vscode#195715](https://github.com/microsoft/vscode/issues/195715) @rebornix
#### Jupyter Notebooks

- [x] Finalize/publish Jupyter Kernel API (merge into `api.d.ts` and update npm package) [vscode-jupyter#14669](https://github.com/microsoft/vscode-jupyter/issues/14669) @DonJayamanne
- [x] Polish for auto complete from kernel [vscode-jupyter#13596](https://github.com/microsoft/vscode-jupyter/issues/13596) @DonJayamanne
   - [x] Fix duplicated suggestions for Python and avoid launching another language server [vscode-jupyter#13596](https://github.com/microsoft/vscode-jupyter/issues/13596)
   - [x] Consolidate settings for completion trigger characters (`jupyter.kernelCompletions.*`) [vscode-jupyter#13596](https://github.com/microsoft/vscode-jupyter/issues/14774)
- [x] Explore Kernel Picker experience in Dev Containers [vscode-jupyter#14673](https://github.com/microsoft/vscode-jupyter/issues/14673) @DonJayamanne @rebornix
- [ ] :muscle: Explore file explorer/file syncing for Remote Jupyter Server [vscode-jupyter#1366](https://github.com/microsoft/vscode-jupyter/issues/1366) @DonJayamanne @rebornix
- [ ] :runner: Implement jupyter variable provider [vscode-jupyter#14821](https://github.com/microsoft/vscode-jupyter/issues/14821) @amunger

### WebAssembly Support
- [x] Research options for shared memory and object management between WASI threads that are mapped to workers [vscode-wasm#153](https://github.com/microsoft/vscode-wasm/issues/153) @dbaeumer

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22December+%2F+January+2024%22) @brettcannon **team**
#### Language Server Protocol
- [x] LSP support to 3rd-parties [vscode-python#21964](https://github.com/microsoft/vscode-python/issues/21964) @karthiknadig
#### TypeScript
- [ ] :runner: Change the TS language server to not always offer "Move to file..." code actions [vscode#201310](https://github.com/microsoft/vscode/issues/201310) @aiday-mar
- [ ] :runner: Fix code actions not being available when error is introduced [vscode#117812](https://github.com/microsoft/vscode/issues/117812) @justschen
- [ ] :runner: Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :hand: Support bringing along imports with copy paste [typescript#50187](https://github.com/microsoft/TypeScript/issues/50187) @mjbvz

### Source Control
- [ ] :runner: Support contextual actions in SCM Incoming/Outgoing nodes [vscode#199318](https://github.com/microsoft/vscode/issues/199318) @lszomoru

### Testing
- [x] Design test coverage UX/API [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312

### Debug
- [x] Explore debug visualization extension point [vscode#197287](https://github.com/microsoft/vscode/issues/197287) @connor4312
- [x] Add support for breakpoint dependencies [vscode#152428](https://github.com/microsoft/vscode/issues/152428) @connor4312

#### Debug Adapter Protocol
- [ ] :runner: Support additional data fields for breakpoint [debug-adapter-protocol#445](https://github.com/microsoft/debug-adapter-protocol/issues/445) @connor4312

### API
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22December+%2F+January+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22December+%2F+January+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [ ] :runner: Explore improvements to the proposed IssueReporter API [vscode#196863](https://github.com/microsoft/vscode/issues/196863) @justschen

### Extensions
- [x] Investigate high extension install error rate [vscode#190233](https://github.com/microsoft/vscode/issues/190233) @sandy081

### Extension Contributions
- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22December+%2F+January+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [x] GHPRI: Allow users to resolve merge conflicts from PR view [vscode-pull-request-github#1562](https://github.com/microsoft/vscode-pull-request-github/issues/1562) @alexr00
- [x] GHPRI: Provide group by setting for queries [vscode-pull-request-github#1881](https://github.com/microsoft/vscode-pull-request-github/issues/1881) @alexr00
- [x] Ship new ESLint release version @dbaeumer

### Engineering
- [x] Configure c++ toolchain in extension build steps on Linux pipeline [vscode-engineering#456](https://github.com/microsoft/vscode-engineering/issues/456) @deepak1556
- [x] Integrate vscode-zeromq with pipeline templates from vscode-engineering [zeromq-prebuilt#26](https://github.com/microsoft/zeromq-prebuilt/issues/26) @deepak1556 @DonJayamanne
#### Electron
- [x] Wire `Electron.net` API into the utility process [vscode#192899](https://github.com/microsoft/vscode/issues/192899) @deepak1556
- [ ] :runner: WCO on Windows leaves no room for resizing horizontally/diagonally [vscode#185249](https://github.com/microsoft/vscode/issues/185249) @rzhao271

---
### Deferred
- [ ] Support picking tab vs spaces in notebook cell editor [vscode#108675](https://github.com/microsoft/vscode/issues/108675) @Yoyokrazy
- [ ] Support module import/usage analysis in **Run Dependent Cells** [vscode-jupyter#14674](https://github.com/microsoft/vscode-jupyter/issues/14674) @rebornix w/ Pylance team
- [ ] :muscle: Explore quick fixes attached to rows in sticky scroll [vscode#198116](https://github.com/microsoft/vscode/issues/198116)@tyriar
- [ ] :runner: Investigate compile C# code in the browser to IL using dotnet.wasm [vscode-wasm#112](https://github.com/microsoft/vscode-wasm/issues/112) @dbaeumer
- [ ] :runner: Support WASI preview2 [vscode-wasm#52](https://github.com/microsoft/vscode-wasm/issues/52) @dbaeumer
- [ ] Polish unfocused dimming feature [vscode#191775](https://github.com/microsoft/vscode/issues/191775) @tyriar
- [ ] Fix custom ZMQ build for Linux ARM32/ARM64 [vscode-jupyter#14070](https://github.com/microsoft/vscode-jupyter/issues/14070) @DonJayamanne
- [ ] Adopt canonical URI Provider API for workspace trust [vscode#180582](https://github.com/microsoft/vscode/issues/180582) @sbatten
- [ ] :runner: Explore support for multiple GitHub accounts [vscode#127967](https://github.com/microsoft/vscode/issues/127967) @tylerleonhardt
- [ ] :runner: Add smart pasting of markdown URLs [vscode#186289](https://github.com/microsoft/vscode/issues/186289) @mjbvz
- [ ] :runner: Add drop/paste for css [vscode#189875](https://github.com/microsoft/vscode/issues/189875) @mjbvz
- [ ] Support keyboard navigation between groups in quick picks [vscode#149046](https://github.com/microsoft/vscode/issues/149046) @tylerleonhardt
- [ ] :runner: Improve Profiles Management UX [vscode#192387](https://github.com/microsoft/vscode/issues/192387) @sandy081 @hbons

**Comment by Cpt-Falcon** [comment]
Any word on whether copy paste is going to be fixed? You can't copy a variable during debugging without visual studio truncating saying "...". Quite a nuisance. Only way to get the contents of a larger variable is to write it out to a json file. Visual studio 2022 doesn't have this problem and limitation. I would understand if it truncated past 1000, but truncating it at like 20 is ridiculous. Maybe put a setting in the code that does not restrict on copying large variable values

**Comment by jstm88** [comment]
How about addressing the fact that extensions are constantly able to spam the "Output" panel and there is *no way to prevent it*?

I opened https://github.com/microsoft/vscode/issues/203478 in an attempt to get the discussion in https://github.com/microsoft/vscode/issues/105270 restarted, but all mentions of this problem keep getting **incorrectly** closed as "duplicates" because the original report from over 6 years ago was closed without fully understanding the issue.

Not sure what users are supposed to do when a rogue mod starts closing valid issues and then not even looking at the discussion where users are calling for it to be reopened...
