### ISSUE TITLE
Polish Multi-File Diff Editor

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#201718]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/199291
- [x] Better Support For Renames
- [x] Better Support For Deleted Files
- [x] Better Support For New Files
- [ ] https://github.com/microsoft/vscode/issues/199295
- [ ] https://github.com/microsoft/vscode/issues/199615
- [ ] https://github.com/microsoft/vscode/issues/200336
- [ ] https://github.com/microsoft/vscode/issues/202064
```

**Comment by hediet** [comment]
Closing, as most issues are addressed.
