### ISSUE TITLE
Update to Electron 28

### ISSUE THREAD

**Issue by verhovsky** [microsoft/vscode#201935]
Electron 28 was released on December 5th, 2023. It finally supports ECMAScript Modules (ESM) https://www.electronjs.org/docs/latest/tutorial/esm which I would like to use in my VS Code extension.

@deepak1556 could you update Electron again please?

**Comment by deepak1556** [comment]
```[tasklist]
### Todo
- [x] Update patches
- [ ] Update native modules
- [ ] Nightly Exploration builds
- [ ] Update/Check LICENSE file in CG for new node.js version
- [ ] Update LICENSE for new ffmpeg version
```

**Comment by C0rn3j** [comment]
I would like to note that Electron 28 seemingly fixes some crashing issues on Wayland https://github.com/electron/electron/issues/37531#issuecomment-1861632826

I have a hope it might, at least partially, resolve https://github.com/microsoft/vscode/issues/184124 / https://github.com/electron/electron/issues/39449.

**Comment by fisforfaheem** [comment]
Kindly make sure to release this version with electron 28

**Comment by Manish3323** [comment]
🤩

**Comment by svipas** [comment]
@deepak1556 As I can see Electron 28 isn't released with 1.87.0, is it going to be included in 1.88.0?

**Comment by C0rn3j** [comment]
@svipas Feature targeted for March won't be present in a February build.

**Comment by deepak1556** [comment]
@svipas yes the update will be available in `1.88` release.

**Comment by AlexCannonball** [comment]
I've tested `1.88` on Windows with an extension using ESM `import`-s and it doesn't work. I get the following error upon the extension activation:

> Activating extension 'xxxxxx' failed: require() of ES Module d:\xxxxxx\out\extension.js from d:\Programs\VS_code\resources\app\out\vs\loader.js not supported. Instead change the require of extension.js in d:\Programs\VS_code\resources\app\out\vs\loader.js to a dynamic import() which is available in all CommonJS modules..
