### ISSUE TITLE
الحسا 

### ISSUE THREAD

**Issue by h58v** [microsoft/vscode#202305]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/202304
- [ ] https://github.com/microsoft/vscode/pull/202303
- [x] https://t.snapchat.com/oOa8DhBZ
- [ ] https://github.com/microsoft/vscode/issues/198519
```
