### ISSUE TITLE
TRASH

### ISSUE THREAD

**Issue by CHINOBKLING** [microsoft/vscode#203279]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/171016
- [ ] https://github.com/microsoft/vscode/issues/193703
- [ ] https://github.com/microsoft/vscode/issues/202851
- [ ] https://github.com/microsoft/vscode/issues/175760
- [ ] https://github.com/microsoft/vscode/issues/203124
- [ ] https://github.com/microsoft/vscode/issues/181818
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/203150
- [ ] https://github.com/microsoft/vscode/issues/193703
```
