### ISSUE TITLE
Localize Code

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#2041]
Today we have the Monaco editor localized. This plan item captures how we get to a localized VS Code. 

We need to localize both the `core` and the `extensions` we bundle.
## Core + Helper Apps

The core includes the main process, renderer, and extension host. All these components use AMD and we will use the same localization approach as is used in the Monaco editor (`nls.localize`).

The core includes some built-in languages like PHP, CSS, JSON. Each of these languages comes with strings that are used as documentation for Intellisense or validation (PHP built-in functions, CSS attribute descriptions, JSON schema descriptions from http://schemastore.org/json/). We will not externalize and translate these strings initially.

Tasks:
- [x] Provide a tslint rule to check for non-externalized strings.  @dbaeumer 
- [x] Externalize the remaining strings. Major areas of the workbench are already localized, but there are gaps. @Microsoft/vscode
- [x] Review the places where we expose exception messages directly to the user (e.g. editor, explorer, git, search) and ensure that a higher-level translatable error message is shown in the UI, which incluldes the raw error as detail in parenthesis. @bpasero 
- [x] Localize the Search App. @dbaeumer 
- [x] Localize the Git App @dbaeumer 
- [x] Plugin Host @dbaeumer 
- [x] Main @dbaeumer 
- [x] Renderer @dbaeumer 
## Extensions

Extensions are implemented using the CommonJS modules and the AMD based externalization used in the Code cannot be use. The goal is to use the same file format for the language bundles used for the Core and extensions.

An extensions has contributes strings in the package.json and from the code.  We need a localization support for both.

Tasks:
- [x] Localization support for the package.json.
- [x] Provide a node localization module that uses the same file format as for the core and that can be used by extensions..
- [x] Provide nls-checking tool to check for non-localized strings for the bundled extensions
- Externalize bundled extensions (with user visible strings)
  - [x] TypeScript
  - [x] JSON
  - :question: others
## Debug Adapters
- [x] Support that messages from the debug adapter can be localized @weinand 
## Development Tasks
- [x] Support pseudo localization for testing.
- [x] Document the localization support so that the community can contribute translations.
- [x] Tools to enable contributions of translations.
- [x] Support install/update localized Code versions.
## Roadmap
- January
  - Core + Apps is localized
  - Demo Code in German (minus extensions)
- February
  - Bundled extensions are localized
  - Bundled debug adapter are localized
  - Demo Code in German with a localized extension

**Comment by eliashdezr** [comment]
Is there a way to turn off localization? I want the editor to be always on English.

**Comment by bgashler1** [comment]
@eliashdezr: yes, there will be a setting or command that you can run that will let you turn off localization.

**Comment by akamud** [comment]
I see the localization is now released in insiders channel, how can we contribute to other languages?

**Comment by dbaeumer** [comment]
@akamud we are working on the details to allow to contribute additional languages. We aren't there yet.

**Comment by akamud** [comment]
![http://static1.squarespace.com/static/53951756e4b00bb4cdae2705/t/565bab83e4b05079e4bcc313/1448848265740/?format=original](http://static1.squarespace.com/static/53951756e4b00bb4cdae2705/t/565bab83e4b05079e4bcc313/1448848265740/?format=original)

**Comment by dbaeumer** [comment]
@akamud unfortunately not.

**Comment by sean-mcmanus** [comment]
How can we add localized strings to our C/C++ extension? I can't find any documentation.

**Comment by dbaeumer** [comment]
@sean-mcmanus: there are two npm module that we use to localize the extension we ship in VS Code in the box. The are: vscode-nls and vscode-nls-dev. The typescript extension in the vscode source tree (https://github.com/Microsoft/vscode/tree/master/extensions/typescript) is a good example to copy from to see how to use the two npm modules.

**Comment by akamud** [comment]
Any progress on this? I see in 1.5.3 there is now support for 9 languages in VS Code. How can we help expand this?

**Comment by rafaelcpalmeida** [comment]
@egamma Any updates on how we can contribute with translations?

**Comment by egamma** [comment]
@rafaelcpalmeida @akamud we will do another investigation on this topic during our March iteration.

**Comment by dbaeumer** [comment]
We opened VS Code translations up for contributions. See our VS Code project on Transifex.
