### ISSUE TITLE
Iteration Plan for February 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#204292]
This plan captures our work in **February**. This is a 4-week iteration. We will ship in **early March**.

## Endgame

- **February 20, 2024**: Endgame begins
- **February 23, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22February+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility

- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22February+2024%22) @meganrogge **team**
- [ ] :muscle: Explore Lay-of-the-Land command [vscode#201898](https://github.com/microsoft/vscode/issues/201898) @meganrogge

### Workbench

- [ ] ⚫ 🏃 Tree: Support showing entire cell on hover [vscode#163580](https://github.com/microsoft/vscode/issues/163580) @benibenj
- [x] Localize inno-updater [vscode#168894](https://github.com/microsoft/vscode/issues/168894) @benibenj
- [x] Align reorder UX across lists, tabs and views [vscode#203441](https://github.com/microsoft/vscode/issues/203441) @benibenj
- [ ] :muscle: Support keyboard navigation between groups in quick picks [vscode#149046](https://github.com/microsoft/vscode/issues/149046) @tylerleonhardt
- [x] Support toggling settings from release notes [vscode#204338](https://github.com/microsoft/vscode/issues/204338) @alexr00
- [ ] :hand: Enable Window 11 context menu in Stable [vscode#204696](https://github.com/microsoft/vscode/issues/204696) @deepak1556
- [ ] :runner: Investigate dictation support into the editor [vscode#205263](https://github.com/microsoft/vscode/issues/205263) @bpasero
- [ ] :runner: Adopt the multi-file diff editor for rendering refactor previews [vscode#204370](https://github.com/microsoft/vscode/issues/204370) @aiday-mar @hediet @jrieken

### Code Editor

- [x] Support dynamic line heights using decorations [vscode#194609](https://github.com/microsoft/vscode/pull/194609) @hediet @alexdima
- [ ] Explore using the new EditContext API [vscode#204371](https://github.com/microsoft/vscode/issues/204371) @hediet
- [x] Add support for multicursor for inline completions [vscode#201308](https://github.com/microsoft/vscode/issues/201308) @aiday-mar @hediet
- [x] Release the Monaco Editor [CHANGELOG](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0460) @hediet
- [x] Explore showing off-cursor inline edits [vscode#204158](https://github.com/microsoft/vscode/pull/204158) @hediet @aiday-mar
- [ ] :muscle: Explore hover enriching [vscode#195394](https://github.com/microsoft/vscode/issues/195394) @aiday-mar @hediet

### Search

- [ ] :runner: Polish the quick search preview editor experience [vscode#204853](https://github.com/microsoft/vscode/issues/204853) @andreamah

### Notebook Editor

- [ ] :runner: Polish variables view [vscode#203480](https://github.com/microsoft/vscode/issues/203480) @amunger
- [x] Data viewer extension point for variables view: [vscode#203054](https://github.com/microsoft/vscode/issues/203054) @amunger
- [x] Support picking tab vs spaces in notebook cell editor [vscode#108675](https://github.com/microsoft/vscode/issues/108675) @Yoyokrazy
- [ ] :runner: Explore run in section in sticky scroll / outline / Go to Symbols [vscode#199992](https://github.com/microsoft/vscode/issues/199992) @Yoyokrazy
- [ ] :runner: Notebook keyboard shortcut flakiness [vscode#204950](https://github.com/microsoft/vscode/issues/204950) @donjayamanne

#### Jupyter Notebooks

- [ ] Update Codespace with latest Kernel Provider api [vscode-jupyter#15125](https://github.com/microsoft/vscode-jupyter/issues/15125) @DonJayamanne
- [x] Explore supporting requests from kernel on code execution [vscode-jupyter#15124](https://github.com/microsoft/vscode-jupyter/issues/15124) @DonJayamanne
- [ ] Support module import/usage analysis in Run Dependent Cells [vscode-jupyter#14674](https://github.com/microsoft/vscode-jupyter/issues/14674) @rebornix w/ Pylance team

### WebAssembly Support

- [ ] :runner: Implemented WASI preview 2 `pollables` and `streams` on top of the shared-memory model [wasm-wasi#155](https://github.com/microsoft/vscode-wasm/issues/155) @dbaeumer

### Issue Reporter

- [ ] :red_circle: :muscle: Explore supporting the issue reporter in the web @justschen

#### Python

- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22) @brettcannon **team**

#### Language Server Protocol

- [x] Support Snippets in workspace edits [lsp#1414](https://github.com/microsoft/vscode-languageserver-node/issues/1414) @dbaeumer
- [x] Design notebook formatting provider API [lsp#1336](https://github.com/microsoft/vscode-languageserver-node/issues/1336) @karthiknadig @rebornix

#### TypeScript

- [x] Change the TS language server to not always offer "Move to file..." code actions [vscode#201310](https://github.com/microsoft/vscode/issues/201310) @aiday-mar
- [ ] :hand: Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :hand: Support bringing along imports with copy paste [typescript#50187](https://github.com/microsoft/TypeScript/issues/50187) @mjbvz
- [ ] Adopt `CodeAction` `ranges` API in TS refactorings [vscode#204040](https://github.com/microsoft/vscode/issues/204040) @justschen

### Source Control

- [x] Support contextual actions in SCM Incoming/Outgoing nodes [vscode#199318](https://github.com/microsoft/vscode/issues/199318) @lszomoru
- [x] Support displaying git branch info in title bar [vscode#197498](https://github.com/microsoft/vscode/issues/197498) @lszomoru
- [x] Use diagnostics to show input validation warnings/errors [vscode#201156](https://github.com/microsoft/vscode/issues/201156) @lszomoru
- [ ] :runner: Quick diff decorators for incoming changes [vscode#204982](https://github.com/microsoft/vscode/issues/204982) @lszomoru

### Testing

- [x] Make `vscode-test` `launch.json`-runnable [vscode#199211](https://github.com/microsoft/vscode/issues/199211) @connor4312
- [x] Support test coverage in `vscode-test` [vscode#203563](https://github.com/microsoft/vscode/issues/203563) @connor4312
- [ ] :runner: Finalize test coverage API @connor4312 [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312

### Debug

- [ ] Continue debug visualization exploration [vscode#197287](https://github.com/microsoft/vscode/issues/197287) @connor4312

#### Debug Adapter Protocol

- [ ] :runner: Support additional data fields for breakpoint [debug-adapter-protocol#454](https://github.com/microsoft/debug-adapter-protocol/issues/454) [debug-adapter-protocol#455](https://github.com/microsoft/debug-adapter-protocol/issues/455) @connor4312

### API

- [ ] :runner: Explore improvements to the proposed IssueReporter API [vscode#196863](https://github.com/microsoft/vscode/issues/196863) @justschen
- [x] Explore an improved findFiles API [vscode#48674](https://github.com/microsoft/vscode/issues/48674) @andreamah
- [ ] :muscle: Remove "sortByLabel" default behavior and stale proposed API [vscode#73904](https://github.com/microsoft/vscode/issues/73904) @tylerleonhardt
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions

- [ ] Investigate high extension install error rate [vscode#190233](https://github.com/microsoft/vscode/issues/190233) @sandy081

### Extension Contributions

- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [ ] :runner: GHPRI: Allow "Files Changed" in new PR to diff against file on disk [vscode-pull-request-github#5163](https://github.com/microsoft/vscode-pull-request-github/issues/5163) @alexr00
- [x] GHPRI: Support user-level PR templates [vscode-pull-request-github#3414](https://github.com/microsoft/vscode-pull-request-github/issues/3414) @alexr00
- [x] GHPRI: Support setting Project when creating PR [vscode-pull-request-github#3062](https://github.com/microsoft/vscode-pull-request-github/issues/3062) @alexr00
- [x] Investigate solutions to improve support for ESLint rules that have inter-file dependencies [vscode-eslint#1774](https://github.com/microsoft/vscode-eslint/issues/1774) @dbaeumer
- [x] Explore adoption of the ESLint flat config support [vscode-eslint#1644](https://github.com/microsoft/vscode-eslint/issues/1644) @dbaeumer

### Engineering

- None.

#### Electron

- [x] Update to Electron 28 [vscode#201935](https://github.com/microsoft/vscode/issues/201935) @deepak1556
- [ ] :runner: V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556

---

### Deferred

- [ ] :muscle: Explore quick fixes attached to rows in sticky scroll [vscode#198116](https://github.com/microsoft/vscode/issues/198116)@tyriar
- [ ] :runner: Investigate compile C# code in the browser to IL using dotnet.wasm [vscode-wasm#112](https://github.com/microsoft/vscode-wasm/issues/112) @dbaeumer
- [ ] Fix custom ZMQ build for Linux ARM32/ARM64 [vscode-jupyter#14070](https://github.com/microsoft/vscode-jupyter/issues/14070) @DonJayamanne
- [ ] Adopt canonical URI Provider API for workspace trust [vscode#180582](https://github.com/microsoft/vscode/issues/180582) @sbatten

**Comment by WilmarE** [comment]
> This plan captures our work in **February**. This is a 4-week iteration. We will ship in **early March**.
> 
> ## Endgame
> * **February 20, 2024**: Endgame begins
> * **February 23, 2024**: Endgame done
> 
> The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22February+2024%22).
> 
> ## Plan Items
> Below is a summary of the top level plan items.
> 
> Legend of annotations:
> 
> Mark	Description
> 🏃	work in progress
> ✋	blocked task
> 💪	stretch goal for this iteration
> 🔴	missing issue reference
> 🔵	more investigation required to remove uncertainty
> ⚫	under discussion within the team
> ⬛	a large work item, larger than one iteration
> ### Accessibility
> * [ ]  🏃 Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22February+2024%22) @meganrogge **team**
> * [ ]  💪 Explore Lay-of-the-Land command [vscode#201898](https://github.com/microsoft/vscode/issues/201898) @meganrogge
> 
> ### Workbench
> * [ ]  Tree: Support showing entire cell on hover [vscode#163580](https://github.com/microsoft/vscode/issues/163580) @benibenj
> * [ ]  🏃 Localize inno-updater [vscode#168894](https://github.com/microsoft/vscode/issues/168894) @benibenj
> * [x]  🏃 Align reorder UX across lists, tabs and views [vscode#203441](https://github.com/microsoft/vscode/issues/203441) @benibenj
> * [ ]  💪 Support keyboard navigation between groups in quick picks [vscode#149046](https://github.com/microsoft/vscode/issues/149046) @TylerLeonhardt
> * [ ]  Support toggling settings from release notes [vscode#204338](https://github.com/microsoft/vscode/issues/204338) @alexr00
> * [ ]  🔴 Enable Window 11 context menu in Stable @deepak1556
> * [ ]  Investigate dictation support [vscode#40976](https://github.com/microsoft/vscode/issues/40976) @bpasero
> * [ ]  Adopt the multi-file diff editor for rendering refactor previews [vscode#204370](https://github.com/microsoft/vscode/issues/204370) @aiday-mar @hediet @jrieken
> 
> ### Code Editor
> * [ ]  🏃 Support dynamic line heights using decorations [vscode#194609](https://github.com/microsoft/vscode/pull/194609) @hediet @alexdima
> * [ ]  Explore using the new EditContext API [vscode#204371](https://github.com/microsoft/vscode/issues/204371) @hediet
> * [ ]  🏃 Add support for multicursor for inline completions [vscode#201308](https://github.com/microsoft/vscode/issues/201308) @aiday-mar @hediet
> * [ ]  🔴 Release the Monaco Editor @hediet
> * [ ]  💪 Explore showing off-cursor inline suggestions [vscode#204158](https://github.com/microsoft/vscode/pull/204158) @aiday-mar @hediet
> * [ ]  💪 Explore hover enriching [vscode#195394](https://github.com/microsoft/vscode/issues/195394) @aiday-mar @hediet
> 
> ### Search
> * [ ]  🔴 Polish the quick search preview editor experience @andreamah
> 
> ### Notebook Editor
> * [ ]  Polish variables view [vscode#203480](https://github.com/microsoft/vscode/issues/203480) @amunger
> * [ ]  Data viewer extension point for variables view: [vscode#203054](https://github.com/microsoft/vscode/issues/203054) @amunger
> * [ ]  Support picking tab vs spaces in notebook cell editor [vscode#108675](https://github.com/microsoft/vscode/issues/108675) @Yoyokrazy
> * [ ]  🔴 Explore run in section in sticky scroll / outline / Go to Symbols @Yoyokrazy
> * [ ]  🔴 Notebook keyboard shortcut flakiness @rebornix
> 
> #### Jupyter Notebooks
> * [ ]  🔴 Update Codespace with latest Kernel Provider api [vscode-jupyter#15125](https://github.com/microsoft/vscode-jupyter/issues/15125) @DonJayamanne
> * [ ]  🏃 Explore supporting Comms messaging on code execution [vscode-jupyter#15124](https://github.com/microsoft/vscode-jupyter/issues/15124) @DonJayamanne
> * [ ]  Support module import/usage analysis in Run Dependent Cells [vscode-jupyter#14674](https://github.com/microsoft/vscode-jupyter/issues/14674) @rebornix w/ Pylance team
> 
> ### WebAssembly Support
> * [ ]  Implemented WASI preview 2 `pollables` and `streams` on top of the shared-memory model [wasm-wasi#155](https://github.com/microsoft/vscode-wasm/issues/155) @dbaeumer
> 
> ### Issue Reporter
> * [ ]  🔴 💪 Explore supporting the issue reporter in the web @justschen
> 
> ### Languages
> #### Python
> * [ ]  🏃 Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22) @brettcannon **team**
> 
> #### Language Server Protocol
> * [ ]  Support Snippets in workspace edits [lsp#1414](https://github.com/microsoft/vscode-languageserver-node/issues/1414) @dbaeumer
> * [ ]  Design notebook formatting provider API [lsp#1336](https://github.com/microsoft/vscode-languageserver-node/issues/1336) @karthiknadig @rebornix
> 
> #### TypeScript
> * [ ]  🏃 Change the TS language server to not always offer "Move to file..." code actions [vscode#201310](https://github.com/microsoft/vscode/issues/201310) @aiday-mar
> * [ ]  ✋ Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
> * [ ]  ✋ Support bringing along imports with copy paste [typescript#50187](https://github.com/microsoft/TypeScript/issues/50187) @mjbvz
> * [ ]  Adopt `CodeAction` `ranges` API in TS refactorings [vscode#204040](https://github.com/microsoft/vscode/issues/204040) @justschen
> 
> ### Source Control
> * [ ]  🏃 Support contextual actions in SCM Incoming/Outgoing nodes [vscode#199318](https://github.com/microsoft/vscode/issues/199318) @lszomoru
> * [ ]  Support displaying git branch info in title bar [vscode#197498](https://github.com/microsoft/vscode/issues/197498) @lszomoru
> * [ ]  Use diagnostics to show input validation warnings/errors [vscode#201156](https://github.com/microsoft/vscode/issues/201156) @lszomoru
> * [ ]  🔴 Quick diff decorators for incoming changes @lszomoru
> 
> ### Testing
> * [ ]  Make `vscode-test` `launch.json`-runnable [vscode#199211](https://github.com/microsoft/vscode/issues/199211) @connor4312
> * [ ]  Support test coverage in `vscode-test` [vscode#203563](https://github.com/microsoft/vscode/issues/203563) @connor4312
> * [ ]  🔴 Finalize test coverage API @connor4312
> 
> ### Debug
> * [ ]  Continue debug visualization exploration [vscode#197287](https://github.com/microsoft/vscode/issues/197287) @connor4312
> 
> #### Debug Adapter Protocol
> * [ ]  Support additional data fields for breakpoint [debug-adapter-protocol#454](https://github.com/microsoft/debug-adapter-protocol/issues/454) [debug-adapter-protocol#455](https://github.com/microsoft/debug-adapter-protocol/issues/455) @connor4312
> 
> ### API
> * [ ]  🏃 Explore improvements to the proposed IssueReporter API [vscode#196863](https://github.com/microsoft/vscode/issues/196863) @justschen
> * [ ]  Explore an improved findFiles API [vscode#48674](https://github.com/microsoft/vscode/issues/48674) @andreamah
> * [ ]  💪 Remove "sortByLabel" default behavior and stale proposed API [vscode#73904](https://github.com/microsoft/vscode/issues/73904) @TylerLeonhardt
> * [ ]  🏃 API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
> * [ ]  🏃 API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz
> 
> ### Extensions
> * [ ]  Investigate high extension install error rate [vscode#190233](https://github.com/microsoft/vscode/issues/190233) @sandy081
> 
> ### Extension Contributions
> * [ ]  🏃 Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
> * [ ]  GHPRI: Allow "Files Changed" in new PR to diff against file on disk [vscode-pull-request-github#5163](https://github.com/microsoft/vscode-pull-request-github/issues/5163) @alexr00
> * [ ]  GHPRI: Support user-level PR templates [vscode-pull-request-github#3414](https://github.com/microsoft/vscode-pull-request-github/issues/3414) @alexr00
> * [ ]  GHPRI: Support setting Project when creating PR [vscode-pull-request-github#3062](https://github.com/microsoft/vscode-pull-request-github/issues/3062) @alexr00
> * [ ]  Investigate solutions to improve support for ESLint rules that have inter-file dependencies [vscode-eslint#1774](https://github.com/microsoft/vscode-eslint/issues/1774) @dbaeumer
> * [ ]  Explore adoption of the ESLint flat config support [vscode-eslint#1644](https://github.com/microsoft/vscode-eslint/issues/1644) @dbaeumer
> 
> ### Engineering
> * None.
> 
> #### Electron
> * [ ]  🏃 Update to Electron 28 [vscode#201935](https://github.com/microsoft/vscode/issues/201935) @deepak1556
> * [ ]  V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556
> 
> ### Deferred
> * [ ]  💪 Explore quick fixes attached to rows in sticky scroll [vscode#198116](https://github.com/microsoft/vscode/issues/198116)@Tyriar
> * [ ]  🏃 Investigate compile C# code in the browser to IL using dotnet.wasm [vscode-wasm#112](https://github.com/microsoft/vscode-wasm/issues/112) @dbaeumer
> * [ ]  Fix custom ZMQ build for Linux ARM32/ARM64 [vscode-jupyter#14070](https://github.com/microsoft/vscode-jupyter/issues/14070) @DonJayamanne
> * [ ]  Adopt canonical URI Provider API for workspace trust [vscode#180582](https://github.com/microsoft/vscode/issues/180582) @sbatten

**Comment by nnmrts** [comment]
> 🏃 Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22+sort%3Aupdated-desc)

The link on "plan" there shows me Page not found error, is it a private repo?

**Comment by sanket-bhalerao** [comment]
The SCM view loads as a blank pane most of the time, and then starts showing the tree after a while.
started getting this since a couple of weeks.

**Comment by alefragnani** [comment]
Hi @sanket-bhalerao , 

Is there an open issue related to that? I'm asking because I didn´t find any open or recently closed issue. If there isn't, I suggest you to open a new one (https://github.com/microsoft/vscode/issues/new?assignees=&labels=&projects=&template=bug_report.md), so the team will be aware and can investigate it.

Hope this helps

**Comment by MetricMike** [comment]
> > 🏃 Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22+sort%3Aupdated-desc)
> 
> The link on "plan" there shows me a Page not found error, is it a private repo?

Typo in the link (singular vscode-remote-release instead of plural) [plan](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22+sort%3Aupdated-desc)
