### ISSUE TITLE
Notebook keyboard shortcut flakiness

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#204950]
```[tasklist]
### Tasks
- [ ] Ctrl+A doesn’t work reliably. The expected behavior is that it selects the current cell or cell output and nothing, or, hitting escape and to take the focus out of any cell or output would allow for selecting the entire notebook including cells and cell output. A bonus would be a "select all cells" or "select all cell output" option.
- [ ] Scrolling/paging with copy selecting should stop at cell boundary. Oftentimes I want to select part of a cell or cell output. If a make a selection and then do a Ctrl+Page Up or Down, the selection proceeds outside of that boundary and I end up picking up more than I want.
- [ ] Navigation (e.g. escape, ctrl+shift+home) doesn’t work reliably. Again, I should be able to hit escape to move out to the notebook, and Ctrl+Shift+Home should take me to the top of the selected cell/cell output or Notebook if none is selected.
- [ ] Ctrl+Z should undo cell deletion. Sometimes I inadvertently hit a keystroke that deletes a cell and then can't get it back with undo (and the timeline doesn't make it easy to restore it either)
- [ ] https://github.com/microsoft/vscode/issues/205634
```

**Comment by DonJayamanne** [comment]
This should now be fixed.

**Comment by alexr00** [comment]
`ctrl+A` doesn't seem to work quite right. I only see that everything in an output cell is shown after focusing out of the output:

![Recording 2024-03-27 at 15 31 01](https://github.com/microsoft/vscode/assets/38270282/90aa3df8-691d-4969-9a70-5bfbafdc4b09)

**Comment by DonJayamanne** [comment]
Looks like a focus issue.
@alexr00 can you click on the text that contains the Issue number along with the date and author.
Press it a few times untill the output contains the blue border indicating the fact that the output has been selected.
And then press Ctrl+A, it should then work.

I would like to verify that you too are seeing the same issue at your end.

**Comment by DonJayamanne** [comment]
Closing and marking as verifeid as this has been tested in other issues/TPI items,
We have an edge case for HTML and this has to do with focus in outputs -> creating a separate issue for this
