### ISSUE TITLE
Sa50511

### ISSUE THREAD

**Issue by sa50511** [microsoft/vscode#205554]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/205320
- [ ] https://github.com/microsoft/vscode/pull/205553
- [ ] https://github.com/microsoft/vscode/pull/205552
- [ ] https://github.com/microsoft/vscode/issues/204923
- [ ] https://github.com/microsoft/vscode/issues/205512
- [ ] https://github.com/microsoft/vscode/pull/205549
- [ ] https://github.com/microsoft/vscode/issues/205547
- [ ] https://github.com/microsoft/vscode/issues/192129
- [ ] https://github.com/microsoft/vscode/pull/205550
- [ ] https://github.com/microsoft/vscode/pull/205551
- [ ] https://github.com/microsoft/vscode/issues/205534
- [ ] https://github.com/microsoft/vscode/issues/195394
- [ ] https://github.com/microsoft/vscode/issues/200671
- [ ] https://github.com/microsoft/vscode/pull/205225
- [ ] https://github.com/microsoft/vscode/issues/204005
- [ ] https://github.com/microsoft/vscode/issues/197828
- [ ] https://github.com/microsoft/vscode/issues/205402
- [ ] https://github.com/microsoft/vscode/issues/205548
- [ ] https://github.com/microsoft/vscode/issues/205451
- [ ] https://github.com/microsoft/vscode/issues/204731
- [ ] https://github.com/microsoft/vscode/issues/205234
- [ ] https://github.com/microsoft/vscode/pull/204725
- [ ] https://github.com/microsoft/vscode/issues/205544
- [ ] https://github.com/microsoft/vscode/pull/205536
- [ ] https://github.com/microsoft/vscode/issues/205543
- [ ] https://github.com/microsoft/vscode/issues/205545
- [ ] https://github.com/microsoft/vscode/issues/163580
- [ ] https://github.com/microsoft/vscode/issues/168894
- [ ] https://github.com/microsoft/vscode/pull/205279
- [ ] https://github.com/microsoft/vscode/issues/205446
- [ ] https://github.com/microsoft/vscode/pull/205546
- [ ] https://github.com/microsoft/vscode/issues/205533
- [ ] https://github.com/microsoft/vscode/issues/205461
- [ ] https://github.com/microsoft/vscode/issues/204946
- [ ] https://github.com/microsoft/vscode/issues/205206
- [ ] https://github.com/microsoft/vscode/pull/205542
- [ ] https://github.com/microsoft/vscode/issues/205294
- [ ] https://github.com/microsoft/vscode/issues/205013
- [ ] https://github.com/microsoft/vscode/issues/82524
- [ ] https://github.com/microsoft/vscode/issues/174978
- [ ] https://github.com/microsoft/vscode/pull/205556
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/205557
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/205547
- [ ] https://github.com/microsoft/vscode/issues/205548
- [ ] https://github.com/microsoft/vscode/pull/205320
- [ ] https://github.com/microsoft/vscode/pull/205552
- [ ] https://github.com/microsoft/vscode/issues/204923
- [ ] https://github.com/microsoft/vscode/issues/205555
- [ ] https://github.com/microsoft/vscode/issues/205559
- [ ] https://github.com/microsoft/vscode/issues/201156
- [ ] https://github.com/microsoft/vscode/pull/205558
- [ ] https://github.com/microsoft/vscode/issues/205557
- [ ] https://github.com/microsoft/vscode/issues/192129
- [ ] https://github.com/microsoft/vscode/pull/205550
- [ ] https://github.com/microsoft/vscode/pull/205551
- [ ] https://github.com/microsoft/vscode/issues/205534
- [ ] https://github.com/microsoft/vscode/pull/205556
- [ ] https://github.com/microsoft/vscode/issues/200671
```
