### ISSUE TITLE
Remove `custom` entry from Jupyter Notebook & Cell Metadata

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#205637]
This is an unnecessary layer
Everywhere in code we need to look at `custom`, when there's no such thing in Jupyter (specification) metdata.
This is a carry over from the old VS Code notebook Notebook format.
All metadata had to be stored under `custom` and this was never migrated when `custom` in core was removed.

This shows up in SCM view as well
I.e. when using the diff view, the `custom` node is displayed, and this is wrong, as there's no such thing in the spec.

**Removing this will:**
* Improve SCM
* Make it easier for extensions to access the metadata
* Ensure the API lines up with the Jupyter specification
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-jupyter/issues/15378
- [ ] https://github.com/microsoft/vscode/issues/207968#issuecomment-2002992138
- [ ] https://github.com/microsoft/vscode-jupyter/issues/15380
- [ ] https://github.com/julia-vscode/julia-vscode/issues/3568
- [ ] https://github.com/microsoft/vscode-jupyter/issues/15402
```

**Comment by DonJayamanne** [comment]
@rebornix /cc
We will need to coordinate this with partner teams that read/write ipynb notebooks

**Comment by DonJayamanne** [comment]
@davidanthoff 
From what I can tell, the only place where the Notebook or Cell metadata is accessed, is in the `notebookFeature.ts` file.
My plan is to submit a PR that would make a change to support both the old `custom` and the new format.
This way, it would be backwards compatible if and when we move away from the `custom` property.

Should be easy enough to create a single function that returns the metadata and use that everywhere.

How does that sound?

**Comment by DonJayamanne** [comment]
@colombod 

Looking at the code in Polyglot Notebooks (Interactive)
I can see it is used in a large number of places `notebookControllers.ts`, `metadataUtilities.ts`, `notebookSerializers.ts`, etc.
I think the best and safest way to make such a change in your repo would be to have an `if` condition that conditionally uses `custom` based on the version of VS Code being used.
From what I can tell, tehre are a number of files that would be effected, hence the change would not be as simple/straightforward, happy to discuss offline.

**Comment by davidanthoff** [comment]
@DonJayamanne that definitely works!
