### ISSUE TITLE
Iteration Plan for March 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#206739]
This plan captures our work in **March**. This is a 5-week iteration. We will ship in **early April**.

## Endgame

- **March 25, 2024**: Endgame begins
- **March 28, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22March+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Add context actions to Comments view [vscode#5741](https://github.com/microsoft/vscode-pull-request-github/issues/5741) @alexr00
- [x] Inform users of running cells and inline suggestions in notebooks [vscode#176288](https://github.com/microsoft/vscode/issues/176288) @amunger
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22March+2024%22) @meganrogge **team**

### Workbench
- [x] Improve quick pick experiences, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22March+2024%22+assignee%3ATylerLeonhardt+label%3Aquick-pick) @tylerleonhardt
- [x] Adopt the multi-file diff editor for rendering refactor previews [vscode#204370](https://github.com/microsoft/vscode/issues/204370) @aiday-mar @hediet @jrieken
- [x] Support moving webviews to aux window [vscode#195715](https://github.com/microsoft/vscode/issues/195715) @bpasero @rebornix @mjbvz
- [x] Move activity bar to bottom [vscode#118692](https://github.com/microsoft/vscode/issues/118692) @benibenj
- [x] Allow custom editor labels [vscode#41909](https://github.com/microsoft/vscode/issues/41909) @benibenj @bpasero
- [x] Synchronized Scrolling in Split Editor [vscode#33110](https://github.com/microsoft/vscode/issues/33110) @benibenj
- [x] Allow to easily stage code from the diff editor [vscode#206808](https://github.com/microsoft/vscode/issues/206808) @hediet

### Code Editor
- [x] Explore using the new EditContext API [vscode#204371](https://github.com/microsoft/vscode/issues/204371) @hediet
- [ ] :runner: Explore hover enriching [vscode#195394](https://github.com/microsoft/vscode/issues/195394) @aiday-mar @hediet
- [x] Merge rendering logic of PR "[Support dynamic line heights using decorations #194609](https://github.com/microsoft/vscode/pull/194609)" @hediet
- [x] Explore tree-sitter parser ecosystem @alexr00 [vscode#207416](https://github.com/microsoft/vscode/issues/207416)
- [x] Missing quick fixes immediately after introducing an error [vscode#117812](https://github.com/microsoft/vscode/issues/117812) @justschen
- [ ] :runner: Multi-file diff editor has no `TabInput` [vscode#206411](https://github.com/microsoft/vscode/issues/206411) @lramos15 @hediet
- [x] Release the Monaco Editor [CHANGELOG](https://github.com/microsoft/monaco-editor/blob/main/CHANGELOG.md#0470) @hediet

### Search
- [x] Polish the quick search preview editor experience [vscode#204853](https://github.com/microsoft/vscode/issues/204853) @andreamah

### Authentication
- [x] Prevent logging in with multiple GitHub accounts while its not supported [vscode#203850](https://github.com/microsoft/vscode/issues/203850) @TylerLeonhardt

### Notebook Editor
- [ ] :runner: Polish variables view [vscode#203480](https://github.com/microsoft/vscode/issues/203480) @amunger
- [x] Explore run in section in sticky scroll / outline / Go to Symbols [vscode#199992](https://github.com/microsoft/vscode/issues/199992) @Yoyokrazy
- [x] Polish outline view entries for notebook [vscode#206308](https://github.com/microsoft/vscode/issues/206308) @Yoyokrazy
- [ ] :runner: Explore notebook level formatting support [vscode#207334](https://github.com/microsoft/vscode/issues/207334) @Yoyokrazy @rebornix
- [x] Notebook edit history polish (timeline, undo/redo of notebook operations) [vscode#205634](https://github.com/microsoft/vscode/issues/205634) @DonJayamanne
- [x] Support browser keybindings (arrow, pageup/down, shift+pageup/down, ctrl+a) [vscode#206747](https://github.com/microsoft/vscode/issues/206747) @DonJayamanne
- [x] Remove `custom` entry from Jupyter notebook metadata (coordinate with .NET and Julia) [vscode#205637](https://github.com/microsoft/vscode/issues/205637) @DonJayamanne

#### Jupyter Notebooks
- [x] Update Codespace with latest Kernel Provider api [vscode-jupyter#15125](https://github.com/microsoft/vscode-jupyter/issues/15125) @DonJayamanne
- [x] Support module import/usage analysis in Run Dependent Cells [vscode-jupyter#14674](https://github.com/microsoft/vscode-jupyter/issues/14674) @rebornix w/ Pylance team

### WebAssembly Support
- [ ] :runner: Document how to use VS Code's component model tooling to use WASM services inside a VS Code extensions [vscode-wasm#157](https://github.com/microsoft/vscode-wasm/issues/157) @dbaeumer

### Issue Reporter
- [ ] :runner: Explore supporting the issue reporter in the web @justschen

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22March+2024%22) @karthiknadig **team**

#### TypeScript
- [ ] :hand: Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Support bringing along imports with copy paste [typescript#50187](https://github.com/microsoft/TypeScript/issues/50187) @mjbvz
- [x] Adopt `CodeAction` `ranges` for refactorings @mjbvz
- [x] Ship TypeScript 5.4 @mjbvz
- [ ] :runner: Use vscode watches for tsserver [vscode#193848](https://github.com/microsoft/vscode/pull/193848) @bpasero
- [x] Explore adoption of new issue reporter command contribution in TS extension @justschen

### Terminal
- [x] Release xterm.js 5.4 [xterm.js@5.4.0](https://github.com/xtermjs/xterm.js/releases/tag/5.4.0) @tyriar
- [x] Explore automatic glyph scaling opt-out [vscode#206342](https://github.com/microsoft/vscode/issues/206342) @tyriar
- [ ] :runner: Explore exposing shell integration command knowledge to extensions [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @tyriar

### Source Control
- [x] Quick diff decorators for incoming changes [vscode#204982](https://github.com/microsoft/vscode/issues/204982) @lszomoru

### Testing
- [ ] :runner: Finalize test coverage API [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312

### Debug
- [ ] :runner: Expose current thread/stack frame id [vscode#63943](https://github.com/microsoft/vscode/issues/63943) @connor4312

#### Debug Adapter Protocol
- [x] Support additional data fields for breakpoint [debug-adapter-protocol#455](https://github.com/microsoft/debug-adapter-protocol/issues/455) @connor4312

### API
- [x] Explore improvements to the proposed IssueReporter API [vscode#196863](https://github.com/microsoft/vscode/issues/196863) @justschen
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [ ] :runner: Investigate high extension install error rate [vscode#190233](https://github.com/microsoft/vscode/issues/190233) @sandy081
- [x] Update extensions whenever VS Code is about to update [vscode#125417](https://github.com/microsoft/vscode/issues/125417) @sandy081
- [x] Support extensions from the workspace [vscode#206783](https://github.com/microsoft/vscode/issues/206783) @sandy081

### Extension Contributions
- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22March+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [ ] :runner: Allow resolving merge conflicts without checking out PRs [vscode-pull-request-github#5802](https://github.com/microsoft/vscode-pull-request-github/issues/5802) @alexr00
- [x] Improve outdated comments experience [vscode-pull-request-github#5760](https://github.com/microsoft/vscode-pull-request-github/issues/5760) @alexr00
- [x] Improve support for ESLint rules that have inter-file dependencies [vscode-eslint#1774](https://github.com/microsoft/vscode-eslint/issues/1774) @dbaeumer
- [ ] :runner: Adapt the new ESLint flat config support [vscode-eslint#1644](https://github.com/microsoft/vscode-eslint/issues/1644) @dbaeumer

#### Electron
- [ ] :runner: V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556

---
### Deferred
- [ ] Investigate text-to-speech in panel/inline chat interfaces [vscode#196261](https://github.com/microsoft/vscode/issues/196261) @bpasero
- [ ] Improve auto indentation in the editor [vscode#206891](https://github.com/microsoft/vscode/issues/206891) @aiday-mar @hediet
- [ ] Explore better handling of merge conflicts for `.ipynb` files [vscode#160941](https://github.com/microsoft/vscode/issues/160941) @DonJayamanne
- [ ] Continue debug visualization exploration [vscode#197287](https://github.com/microsoft/vscode/issues/197287) @connor4312
- [ ] :muscle: Explore Lay-of-the-Land command [vscode#201898](https://github.com/microsoft/vscode/issues/201898) @meganrogge
- [ ] :runner: Implemented WASI preview 2 `pollables` and `streams` on top of the shared-memory model [wasm-wasi#155](https://github.com/microsoft/vscode-wasm/issues/155) @dbaeumer
- [ ] :muscle: Remove "sortByLabel" default behavior and stale proposed API [vscode#73904](https://github.com/microsoft/vscode/issues/73904) @tylerleonhardt
- [ ] :runner:  Allow "Files Changed" in new PR to diff against file on disk [vscode-pull-request-github#5163](https://github.com/microsoft/vscode-pull-request-github/issues/5163) @alexr00

**Comment by gjsjohnmurray** [comment]
Disappointment again that neither #59921 nor #73524 are listed, and that @andreamah's only item (#204853) involves polishing a recently-added feature (Quick Search, specifically its Previewing capability) that is still not available (polished or unpolished) to our userbase (pinging @isc-bsaviano) because those two proposed APIs have remained unfinalized for more than 5 years now.

**Comment by Locwyn42** [comment]
#203850
Please, let us select specific GitHub accounts for each extension, many of us dream of having our paid Github Copilot from our personal Github account and the repository management for the work account.

**Comment by oenu** [comment]
Heads up the 
```md
🏃 Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-releases/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22March+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
```
has been a broken link for a while

**Comment by sbatten** [comment]
Hi @gjsjohnmurray, I appreciate your feedback and also your many contributions to the project over the years. I can understand the frustration of waiting an indeterminate amount of time for a long-standing feature request for which you have personal interest. As you may know, our team members have responsibilities beyond the iteration plan items here and that this comes into play when creating the right balance for each team member's plan. That being said, I am aware of your requests as @joaomoreno has brought them up to me and it is something that @andreamah and I have on our radar and discussed. I ask for your understanding and please remain patient as we look for ways to make progress on those items.

**Comment by starball5** [comment]
> Disappointment again that neither #59921 nor #73524 are listed, and that @andreamah's only item (#204853) involves polishing a recently-added feature (Quick Search, specifically its Previewing capability) that is still not available (polished or unpolished) to our userbase (pinging @isc-bsaviano) because those two proposed APIs have remained unfinalized for more than 5 years now.

You might be happy to see https://github.com/microsoft/vscode/issues/209775
