### ISSUE TITLE
Iteration Plan for April 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#209775]
This plan captures our work in **April**. This is a 4-week iteration. We will ship in **early May**.

## Endgame

- **April 22, 2024**: Endgame begins
- **April 26, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22April+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22April+2024%22) @meganrogge **team**
- [x] Accessibility signal for cell execution progress status [vscode#196396](https://github.com/microsoft/vscode/issues/196396) @meganrogge @amunger
- [x] Refine when accessibility signals play in code editor [vscode#204257](https://github.com/microsoft/vscode/issues/204257), [vscode#205320](https://github.com/microsoft/vscode/pull/205320) @hediet @meganrogge
- [x] Improve handling of inline completion / suggest widget accessibility signals for SR users [vscode#208449](https://github.com/microsoft/vscode/issues/208449) @hediet @meganrogge

### Workbench
- [ ] :runner: Exploration: Make tree find controls more discoverable [vscode#173742](https://github.com/microsoft/vscode/issues/173742) @benibenj
- [x] Improve automatic theme switching behavior [vscode#158314](https://github.com/microsoft/vscode/issues/158314) @aeschli

### Code Editor
- [x] Explore hover enriching [vscode#195394](https://github.com/microsoft/vscode/issues/195394) @aiday-mar @hediet
- [ ] :runner: Improve auto indentation in the editor [vscode#206891](https://github.com/microsoft/vscode/issues/206891) @aiday-mar @hediet
    - [ ] Skip lines that are part of a multi-line string (or comment) [vscode#209859](https://github.com/microsoft/vscode/issues/209859) @aiday-mar @hediet
    - [ ] Strip comments from code before evaluating regexes [vscode#209861](https://github.com/microsoft/vscode/issues/209861) @aiday-mar @hediet
    - [ ] Explore removing brackets from strings before evaluating regexes [vscode#209862](https://github.com/microsoft/vscode/issues/209862) @aiday-mar @hediet
- [x] Multi-file diff editor has no `TabInput` [vscode#206411](https://github.com/microsoft/vscode/issues/206411) @lramos15 @hediet
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00
- [ ] :muscle: Placeholder support [vscode#208976](https://github.com/microsoft/vscode/issues/208976) @hediet
- [ ] Release the Monaco Editor @hediet

### Search
- [x] Polish quick search [vscode#209979](https://github.com/microsoft/vscode/issues/209979) @andreamah

### Notebook Editor
- [ ] :runner: Filter/grouping support in variables view [vscode#208865](https://github.com/microsoft/vscode/issues/208865) @amunger
- [x] Investigate notebook document backup blocking renderer process [vscode-jupyter#14459](https://github.com/microsoft/vscode-jupyter/issues/14459) @amunger
- [ ] :runner: Improving Error Renderer (Default call stack collapse, display '/fix' and '/explain' actions) [vscode#200253](https://github.com/microsoft/vscode/issues/200253) @amunger
- [ ] :runner: Explore API to support notebook document formatting with Ruff and Black [vscode#207334](https://github.com/microsoft/vscode/issues/207334) @Yoyokrazy @rebornix
- [ ] :runner: Investigate freeze/slowness on notebook cell execution [vscode#209787](https://github.com/microsoft/vscode/issues/209787) @DonJayamanne

#### Jupyter Notebooks
- [x] Roll out experiments for dropping "custom" namespace in cell metadata and api migration in codespace extension [vscode#205637](https://github.com/microsoft/vscode/issues/205637) @DonJayamanne
- [x] Deprecation notice for the Data Viewer in Jupyter [vscode-jupyter](https://github.com/microsoft/vscode-jupyter/issues/15486) @rebornix @amunger

### WebAssembly Support
- [ ] :runner: Document how to use VS Code's component model tooling to use WASM services inside a VS Code extensions [vscode-wasm#157](https://github.com/microsoft/vscode-wasm/issues/157) @dbaeumer

### Issue Reporter
- [ ] :runner: Explore supporting the issue reporter in the web [vscode#203247](https://github.com/microsoft/vscode/issues/203247) @justschen

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22April+2024%22) @karthiknadig **team**

#### TypeScript
- [ ] :hand: Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [ ] :runner: Support bringing along imports with copy paste [typescript#50187](https://github.com/microsoft/TypeScript/issues/50187) @mjbvz
- [x] Use vscode watches for tsserver [vscode#193848](https://github.com/microsoft/vscode/pull/193848) @bpasero

### Terminal
- [ ] :runner: Expose shell integration command knowledge to extensions [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @tyriar
- [ ] :muscle: Explore Terminal Buffer access for extensions [vscode#207504](https://github.com/microsoft/vscode/issues/207504) @tyriar
- [x] Terminal middle click paste option [vscode#187365](https://github.com/microsoft/vscode/issues/187365) @tyriar

### Source Control
- [ ] :runner: Working sets for git branches [vscode#35307](https://github.com/microsoft/vscode/issues/35307) @lszomoru @bpasero

### Testing
- [x] Finalize test coverage API [vscode#123713](https://github.com/microsoft/vscode/issues/123713) @connor4312
- [x] Support `preserveFocus` on test runs [vscode#209491](https://github.com/microsoft/vscode/issues/209491) @connor4312

### Debug
- [ ] :runner: Expose current thread/stack frame id [vscode#63943](https://github.com/microsoft/vscode/issues/63943) @connor4312

### API
- [ ] :runner: Explore finalizing `FileSearchProvider` API [vscode#73524](https://github.com/microsoft/vscode/issues/73524) @andreamah
- [ ] :runner: Explore finalizing `TextSearchProvider` API [vscode#59921](https://github.com/microsoft/vscode/issues/59921) @andreamah
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [ ] :runner: Investigate high extension install error rate [vscode#190233](https://github.com/microsoft/vscode/issues/190233) @sandy081
- [x] Create GitHub releases whenever releasing `vsce` [vscode-vsce#862](https://github.com/microsoft/vscode-vsce/issues/862) @benibenj
- [x] Support the files property in `package.json` [vscode-vsce#867](https://github.com/microsoft/vscode-vsce/issues/867) @benibenj
- [x] Finalize support local workspace extensions [vscode#206783](https://github.com/microsoft/vscode/issues/206783) @sandy081

### Extension Contributions
- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22April+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [x] Allow resolving merge conflicts without checking out PRs [vscode-pull-request-github#5802](https://github.com/microsoft/vscode-pull-request-github/issues/5802) @alexr00
- [ ] :runner: Adapt the new ESLint flat config support [vscode-eslint#1644](https://github.com/microsoft/vscode-eslint/issues/1644) @dbaeumer

### Electron
- [x] Exploration: Electron 29 [vscode#210467](https://github.com/microsoft/vscode/issues/210467) @deepak1556
- [ ] :runner: V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556

---
### Deferred
- [ ] Support Find in editor selection, selected cells, or sections in Notebook Find Widget [vscode#209839](https://github.com/microsoft/vscode/issues/209839) @Yoyokrazy
- [ ] Explore better handling of merge conflicts for `.ipynb` files [vscode#160941](https://github.com/microsoft/vscode/issues/160941) @DonJayamanne
- [ ] :muscle: :red_circle: Explore updating extension template to use esbuild @aeschli
- [ ] Investigate text-to-speech in panel/inline chat interfaces [vscode#196261](https://github.com/microsoft/vscode/issues/196261) @bpasero

**Comment by umpox** [comment]
Hi!

I'd love to see some progress on some proposed features that have been around for a while, I know there's a lot of extensions that would make great use of these features:

- https://github.com/microsoft/vscode/issues/195474
  - This was available previously but was disabled, a number of extensions were making use of this (inc GitLens). It'd be great to support this again!
- https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.codeActionAI.d.ts (I didn't see any issue for this, shall I make one?)
  - This is a small boolean addition that has been proposed for 7 months. Lots of other extensions would make great use of this category for AI fixes.

Please let me know if I can help in any way. Thank you!

**Comment by DaveGuenther** [comment]
Hi Folks, hopefully this is the correct platform to ask this question, if not please re-direct me to a more appropriate forum.  I use the open source code-server and just learned that the Data Viewer would be deprecated out of the Jupyter extension.  I can see as such above in the plan.  **I rely on the Data Viewer to inspect pandas data frames in memory when debugging .py files such as pipeline scripts or Shiny apps (not .ipynb)**, and am not aware of any other mechanism to do this in code-server.  There is a Data Wrangler extension for but isn't doesn't appear to be available for code-server (only VS Code Server?).  Can someone please let me know if there are other extensions that are able to do this in code-server after Data Viewer is deprecated?
Thanks!
