### ISSUE TITLE
Perf: visualise memory efficiency

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#211837]
Similar to our startup perf tracking, can we report daily on how memory efficient startup is? Memory efficiency is, how much wasted objects where garbage collected.

We could utilise `playwright` for this and run it against web on one platform, similar to our web startup tests.

//cc @joaomoreno 
```[tasklist]
### Tasks
- [x] Show total heap used and garbage at the end
- [x] Figure out how many GCs (small, full) ran as part of startup
- [x] Figure out how much total garbage was collected during startup
```
