### ISSUE TITLE
Iteration Plan for May 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#212065]
This plan captures our work in **May**. This is a 5-week iteration. We will ship in **early June**.

## Endgame

- **May 27, 2024**: Endgame begins
- **May 31, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22May+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22May+2024%22) @meganrogge **team**
- [ ] :runner: :muscle: Investigate VS Code speech commands [vscode#209906](https://github.com/microsoft/vscode/issues/209906) @meganrogge @bpasero

### Workbench
- [x] Investigate text-to-speech in panel/inline chat interfaces [vscode#196261](https://github.com/microsoft/vscode/issues/196261) @bpasero
- [x] Tabs multi select [vscode#119327](https://github.com/microsoft/vscode/issues/119327) @benibenj
- [x] Editor action: option to always show [vscode#209962](https://github.com/microsoft/vscode/issues/209962) @benibenj
- [ ] :runner: Profile polish [Issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue%20state%3Aopen%20assignee%3Asandy081%20label%3Auser-profiles%20milestone%3A%22May%202024%22%20-label%3Abug) @sandy081
- [ ] :muscle: Deep folder settings [vscode#32693](https://github.com/microsoft/vscode/issues/32693) @sandy081

### Code Editor
- [x] Improve auto indentation in the editor [vscode#206891](https://github.com/microsoft/vscode/issues/206891) @aiday-mar @hediet
    - [x] Skip lines that are part of a multi-line string (or comment) [vscode#209859](https://github.com/microsoft/vscode/issues/209859) @aiday-mar @hediet
    - [x] Strip comments from code before evaluating regexes [vscode#209861](https://github.com/microsoft/vscode/issues/209861) @aiday-mar @hediet
    - [x] Explore removing brackets from strings before evaluating regexes [vscode#209862](https://github.com/microsoft/vscode/issues/209862) @aiday-mar @hediet
- [x] Make expandable hover content accessible for SR users [vscode#207592](https://github.com/microsoft/vscode/issues/207592) @aiday-mar @hediet
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00
- [x] Release the Monaco Editor @hediet

### Notebook Editor
- [ ] :runner: Migrate Interactive window editor to notebook only [vscode#154983](https://github.com/microsoft/vscode/issues/154983) @amunger
- [ ] :runner: Experiment saving notebooks on extension host by default [vscode#211730](https://github.com/microsoft/vscode/issues/211730) @amunger
- [x] Introduce `notebook.format` code actions to support notebook document formatting with Ruff and Black [vscode#212381](https://github.com/microsoft/vscode/issues/212381) @Yoyokrazy @rebornix
- [x] Support Find in editor selection, selected cells, or sections in Notebook Find Widget [vscode#209839](https://github.com/microsoft/vscode/issues/209839) @Yoyokrazy
- [ ] :runner: Introduce `NotebookDocumentChangeEvent#reason` API for notebook document event filtering [vscode#212063](https://github.com/microsoft/vscode/issues/212063) @DonJayamanne
- [x] Explore better handling of merge conflicts for `.ipynb` files [vscode#160941](https://github.com/microsoft/vscode/issues/160941) @DonJayamanne

### Search
- [ ] :runner: Explore finalizing `FileSearchProvider` API [vscode#73524](https://github.com/microsoft/vscode/issues/73524) @andreamah
- [ ] :runner: Explore finalizing `TextSearchProvider` API [vscode#59921](https://github.com/microsoft/vscode/issues/59921) @andreamah

### WebAssembly Support
- [x] Document how to use VS Code's component model tooling to use WASM services inside a VS Code extensions [vscode-wasm#157](https://github.com/microsoft/vscode-wasm/issues/157) @dbaeumer

### Issue Reporter
- [x] Support the issue reporter in the web [vscode#203247](https://github.com/microsoft/vscode/issues/203247) @justschen
- [x] Improve behaviour when multiple calls to the issue reporter are made [vscode#208718](https://github.com/microsoft/vscode/issues/208718) @justschen

#### Language Server Protocol
- [x] Improve LSP implementation in regards to [event handling](https://github.com/microsoft/vscode/issues/211142) @dbaeumer
- [x] Add support for [pull diagnostics in notebooks](https://github.com/microsoft/vscode-languageserver-node/pull/1465) @dbaeumer
- [x] Release new version of LSP @dbaeumer

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22May+2024%22) @karthiknadig **team**

#### TypeScript
- [x] Automatic type acquisition on the web [vscode#172887](https://github.com/microsoft/vscode/issues/172887) @mjbvz
- [x] Support bringing along imports with copy paste [typescript#50187](https://github.com/microsoft/TypeScript/issues/50187) @mjbvz
- [x] Reduce how often `move` code actions trigger the light bulb [typescript#58387](https://github.com/microsoft/TypeScript/issues/58387) @justschen

### Testing
- [x] Track which test generates which coverage information [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [x] Finalize the preserveFocus API [vscode#209491](https://github.com/microsoft/vscode/issues/209491) @connor4312

### Debug
- [x] Expose current thread/stack frame id [vscode#63943](https://github.com/microsoft/vscode/issues/63943) @connor4312

### API
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Engineering
- [x] Create startup memory efficiency performance test [vscode#211837](https://github.com/microsoft/vscode/issues/211837) @bpasero

### Extensions
- [ ] :runner: Investigate high extension install error rate [vscode#190233](https://github.com/microsoft/vscode/issues/190233) @sandy081
- [x] Explore updating extension template to use esbuild [vscode-generator-code#461](https://github.com/microsoft/vscode-generator-code/pull/461) @aeschli
- [ ] :runner: Allow extension to contribute custom labels [vscode#211632](https://github.com/microsoft/vscode/issues/211632) @benibenj

### Extension Contributions
- [x] Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22May+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [ ] :runner: Adapt the new ESLint flat config support [vscode-eslint#1644](https://github.com/microsoft/vscode-eslint/issues/1644) @dbaeumer

### Electron
- [x] Electron 29 [vscode#210467](https://github.com/microsoft/vscode/issues/210467) @deepak1556
- [ ] :runner: V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556

### Documentation
- [ ] :runner: Add Testing user guide [vscode-docs#7208](https://github.com/microsoft/vscode-docs/issues/7208) @ntrogh

---
### Deferred
- [ ] SCM accessibility improvements [vscode#203577](https://github.com/microsoft/vscode/issues/203577) @lszomoru @meganrogge
- [ ] Tree: Support contributable find providers [vscode#212077](https://github.com/microsoft/vscode/issues/212077) @benibenj
- [ ] Add url handling for settings [vscode#212079](https://github.com/microsoft/vscode/issues/212079) @alexr00
- [ ] Decouple NLS from loader [vscode#212542](https://github.com/microsoft/vscode/issues/212542) @bpasero
- [ ] Expose shell integration command knowledge to extensions [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @tyriar
- [ ] Explore Terminal Buffer access for extensions [vscode#207504](https://github.com/microsoft/vscode/issues/207504) @tyriar
