### ISSUE TITLE
"npm.scriptExplorerAction": "open",

### ISSUE THREAD

**Issue by RIZKYARDIANSYAH25** [microsoft/vscode#212907]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/212171
- [x] "npm.scriptExplorerAction": "open",
- [ ] https://github.com/microsoft/vscode/pull/212906
```

```[tasklist]
### "npm.scriptExplorerAction": "open",
- [x] "npm.scriptExplorerAction": "open",
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/212908
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/212171
- [ ] https://github.com/microsoft/vscode/pull/212908
- [ ] https://github.com/microsoft/vscode/issues/109293
- [ ] https://github.com/microsoft/vscode/pull/212906
- [ ] https://github.com/microsoft/vscode/issues/212828
- [ ] https://github.com/microsoft/vscode/issues/212368
- [ ] https://github.com/microsoft/vscode/pull/212900
- [ ] https://github.com/microsoft/vscode/pull/211712
- [ ] https://github.com/microsoft/vscode/issues/212905
- [ ] https://github.com/microsoft/vscode/issues/212835
- [ ] https://github.com/microsoft/vscode/issues/212893
- [ ] https://github.com/microsoft/vscode/pull/212902
- [ ] https://github.com/microsoft/vscode/issues/210837
- [ ] https://github.com/microsoft/vscode/pull/212895
- [ ] https://github.com/microsoft/vscode/pull/212783
- [ ] https://github.com/microsoft/vscode/pull/212859
- [ ] https://github.com/microsoft/vscode/issues/212896
- [ ] https://github.com/microsoft/vscode/issues/168202
- [ ] https://github.com/microsoft/vscode/issues/212857
- [ ] https://github.com/microsoft/vscode/pull/212899
- [ ] https://github.com/microsoft/vscode/issues/212898
- [ ] https://github.com/microsoft/vscode/pull/212873
- [ ] https://github.com/microsoft/vscode/pull/212901
- [ ] https://github.com/microsoft/vscode/pull/212880
- [ ] https://github.com/microsoft/vscode/issues/212903
- [ ] https://github.com/microsoft/vscode/pull/212878
- [ ] https://github.com/microsoft/vscode/pull/212856
- [ ] https://github.com/microsoft/vscode/issues/205618
- [ ] https://github.com/microsoft/vscode/issues/212883
- [ ] https://github.com/microsoft/vscode/pull/212445
- [ ] https://github.com/microsoft/vscode/issues/212805
- [ ] https://github.com/microsoft/vscode/issues/119327
- [ ] https://github.com/microsoft/vscode/issues/212846
- [ ] https://github.com/microsoft/vscode/issues/144850
- [ ] https://github.com/microsoft/vscode/pull/212862
- [ ] https://github.com/microsoft/vscode/pull/212909
- [ ] https://github.com/microsoft/vscode/pull/212865
- [ ] https://github.com/microsoft/vscode/issues/211866
- [ ] https://github.com/microsoft/vscode/issues/205061
- [ ] https://github.com/microsoft/vscode/issues/212904
- [ ] https://github.com/microsoft/vscode/pull/212897
- [ ] https://github.com/microsoft/vscode/pull/212886
- [ ] https://github.com/microsoft/vscode/issues/212105
- [x] "npm.scriptHover": true,
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/212727
- [ ] https://github.com/microsoft/vscode/issues/212828
- [ ] https://github.com/microsoft/vscode/issues/212368
- [ ] https://github.com/microsoft/vscode/pull/212908
- [ ] https://github.com/microsoft/vscode/issues/212835
- [ ] https://github.com/microsoft/vscode/pull/212906
- [x] // Display hover with 'Run' and 'Debug' commands for scripts.
- [ ] https://github.com/microsoft/vscode/pull/212909
- [ ] https://github.com/microsoft/vscode/issues/212171
- [x] // Run npm commands with the `--silent` option
- [x] "npm.runSilent": false
- [x] // The default click action used in the NPM Scripts Explorer: `open` or `run`, the default is `open`.
- [ ] https://github.com/microsoft/vscode/issues/164557
- [ ] https://github.com/microsoft/vscode/pull/212900
- [ ] https://github.com/microsoft/vscode/pull/212902
- [ ] https://github.com/microsoft/vscode/pull/212895
- [ ] https://github.com/microsoft/vscode/issues/212893
- [ ] https://github.com/microsoft/vscode/pull/212783
- [ ] https://github.com/microsoft/vscode/pull/212859
- [x] // Display hover with 'Run' and 'Debug' commands for scripts.
- [ ] https://github.com/microsoft/vscode/issues/109293
- [ ] https://github.com/microsoft/vscode/issues/210837
- [x] // Controls whether 'Peek References' or 'Find References' is invoked when selecting CodeLens references.
- [ ] https://github.com/microsoft/vscode/issues/212857
- [ ] https://github.com/microsoft/vscode/issues/168202
- [ ] https://github.com/microsoft/vscode/issues/212896
- [ ] https://github.com/microsoft/vscode/issues/212898
- [ ] https://github.com/microsoft/vscode/pull/212899
- [ ] https://github.com/microsoft/vscode/pull/212878
- [ ] https://github.com/microsoft/vscode/issues/212904
- [ ] https://github.com/microsoft/vscode/pull/212880
- [ ] https://github.com/microsoft/vscode/issues/212903
- [ ] https://github.com/microsoft/vscode/pull/212856
- [ ] https://github.com/microsoft/vscode/issues/119327
- [ ] https://github.com/microsoft/vscode/issues/212905
- [ ] https://github.com/microsoft/vscode/pull/212445
- [ ] https://github.com/microsoft/vscode/issues/205618
- [ ] https://github.com/microsoft/vscode/issues/212883
- [ ] https://github.com/microsoft/vscode/pull/212897
- [ ] https://github.com/microsoft/vscode/issues/144850
- [ ] https://github.com/microsoft/vscode/issues/212805
- [ ] https://github.com/microsoft/vscode/issues/212846
- [ ] https://github.com/microsoft/vscode/issues/212430
- [ ] https://github.com/microsoft/vscode/pull/212862
- [ ] https://github.com/microsoft/vscode/issues/212910
- [ ] https://github.com/microsoft/vscode/issues/205061
- [ ] https://github.com/microsoft/vscode/issues/211866
- [ ] https://github.com/microsoft/vscode/pull/212865
- [ ] https://github.com/microsoft/vscode/pull/212886
- [ ] https://github.com/microsoft/vscode/pull/212868
- [ ] https://github.com/microsoft/vscode/pull/211712
- [ ] https://github.com/microsoft/vscode/issues/212885
- [ ] https://github.com/microsoft/vscode/issues/212404
- [ ] https://github.com/microsoft/vscode/issues/205212
- [ ] https://github.com/microsoft/vscode/pull/212871
- [ ] https://github.com/microsoft/vscode/issues/212740
- [ ] https://github.com/microsoft/vscode/pull/212890
- [ ] https://github.com/microsoft/vscode/issues/212105
- [ ] https://github.com/microsoft/vscode/issues/212637
- [x] //  - view: Show references in separate view.
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/212906
- [ ] https://github.com/microsoft/vscode/pull/212909
- [ ] https://github.com/microsoft/vscode/pull/212727
- [ ] https://github.com/microsoft/vscode/issues/212835
- [ ] https://github.com/microsoft/vscode/pull/212908
- [ ] https://github.com/microsoft/vscode/issues/212171
- [ ] https://github.com/microsoft/vscode/issues/212828
- [ ] https://github.com/microsoft/vscode/issues/212368
- [ ] https://github.com/microsoft/vscode/issues/212910
- [ ] https://github.com/microsoft/vscode/pull/212783
```
