### ISSUE TITLE
https://maps.app.goo.gl/QbnoJvSqdd4bvdbPA

### ISSUE THREAD

**Issue by Alnahrclean** [microsoft/vscode#213487]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/213439
- [ ] https://github.com/microsoft/vscode/issues/213051
- [ ] https://github.com/microsoft/vscode/issues/213484
```
