### ISSUE TITLE
Iteration Plan for June 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#215394]
This plan captures our work in **June**. This is a 4-week iteration. We will ship in **early July**.

## Endgame

- **June 24, 2024**: Endgame begins
- **June 28, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22June+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22June+2024%22) @meganrogge **team**

### UX
- [x] Explore a setting for underlined links [vscode-website#203989](https://github.com/microsoft/vscode/issues/203989) @daviddossett

### Workbench
- [ ] :runner: Profiles Editor [vscode#192387](https://github.com/microsoft/vscode/issues/192387) @sandy081

### Code Editor
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00
- [x] Text Buffer API for fetching text in nearest chunk [vscode#214648](https://github.com/microsoft/vscode/pull/214648) @rebornix
- [x] Improve Sticky Scroll rendering to reduce confusion [vscode#215440](https://github.com/microsoft/vscode/issues/215440) @aiday-mar @hediet
- [x] Ensure the editor hover widget uses the right accessibility role and is accessible [vscode#215445](https://github.com/microsoft/vscode/issues/215445) @aiday-mar @hediet @meganrogge
- [x] Improve auto-indentation support for TS users using [Allman indentation](https://en.wikipedia.org/wiki/Indentation_style#Notable_styles) [vscode#209802](https://github.com/microsoft/vscode/issues/209802) @aiday-mar
- [ ] :muscle: Adopt EditContext [vscode@207700](https://github.com/microsoft/vscode/issues/207700) @aiday-mar @hediet
- [x] Release the Monaco Editor @hediet @aiday-mar

### Notebook Editor
- [ ] :runner: Migrate Interactive window editor to notebook only [vscode#154983](https://github.com/microsoft/vscode/issues/154983) @amunger
- [x] Notebook Find Widget: support find in text selection and UI polishes [vscode#121218](https://github.com/microsoft/vscode/issues/121218) @Yoyokrazy
- [ ] :muscle: Address papercuts in Notebook Editor for experimenting with large language models [vscode#215397](https://github.com/microsoft/vscode/issues/215397) @rebornix

### Search
- [ ] :runner: Explore finalizing `FileSearchProvider` API [vscode#73524](https://github.com/microsoft/vscode/issues/73524) @andreamah
- [ ] :runner: Explore finalizing `TextSearchProvider` API [vscode#59921](https://github.com/microsoft/vscode/issues/59921) @andreamah

### WebAssembly Support
- [x] Code clean-up in `@vscode/wasm-component-model` [vscode-wasm#166](https://github.com/microsoft/vscode-wasm/issues/166) @dbaeumer

### Issue Reporter
- [ ] :runner: Migrate desktop issue report to auxiliary service approach [vscode#213332](https://github.com/microsoft/vscode/issues/213332) @justschen
- [x] Enable issue reporter in the web [vscode#$203247](https://github.com/microsoft/vscode/issues/203247) @justschen

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22June+2024%22) @karthiknadig **team**

#### TypeScript
- [ ] :runner: Support bringing along imports with copy paste [typescript#50187](https://github.com/microsoft/TypeScript/issues/50187) @mjbvz

### Testing
- [ ] :runner: Finalize attributable test coverage API [vscode#212196](https://github.com/microsoft/vscode/issues/212196) @connor4312
- [ ] :runner: Support stack traces in test messages [vscode#214488](https://github.com/microsoft/vscode/issues/214488) @connor4312
- [x] Correlate testRun in DebugSessionOptions [vscode#214486](https://github.com/microsoft/vscode/issues/214486) @connor4312

### Debug
- [x] API for debug session correlation [vscode#214486](https://github.com/microsoft/vscode/issues/214486) @connor4312

#### Debug Adapter Protocol
- [x] Include document location in hover evaluations [debug-adapter-protocol#465](https://github.com/microsoft/debug-adapter-protocol/issues/465) @connor4312
- [ ] :runner: Add return value field to stop events [debug-adapter-protocol#458](https://github.com/microsoft/debug-adapter-protocol/issues/458) @connor4312

### Terminal
- [ ] :hand: Finalize shellIntegration API [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @tyriar
- [x] Support OSC52 Escape character sequence for copy to local clipboard  [vscode#193508](https://github.com/microsoft/vscode/issues/193508) @tyriar
- [ ] :runner: Iterating on pwsh suggest and PromptInputModel [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar

### Source Control
- [ ] :runner: Graph visualization for Incoming/Ougoing view [vscode#215439](https://github.com/microsoft/vscode/issues/215439) @lszomoru

### API
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [x] `GetAccounts` API proposal for multi-account [vscode#152399](https://github.com/microsoft/vscode/issues/152399) @tylerleonhardt
- [x] Handle proposed extension API incompatibilities [vscode#214294](https://github.com/microsoft/vscode/issues/214294) @sandy081 @roblourens

### Engineering
- [x] Decouple NLS from loader [vscode#212542](https://github.com/microsoft/vscode/issues/212542) @bpasero

### Extensions
- [x] Enable signing capabilities in vsce [vscode-vsce#986](https://github.com/microsoft/vscode-vsce/pull/986) @sandy081
- [x] Support installing pre-release extension version, despite last published version [vscode#214341](https://github.com/microsoft/vscode/issues/214341) @sandy081
- [x] Allow extension to contribute custom labels [vscode#211632](https://github.com/microsoft/vscode/issues/211632) @benibenj

### Extension Contributions
- [x] Adapt the new ESLint flat config support [vscode-eslint#1644](https://github.com/microsoft/vscode-eslint/issues/1644) @dbaeumer

### Electron
- [x] Electron updates duty @deepak1556
- [x] Implement basic auth support for net api in utility process [vscode#212949](https://github.com/microsoft/vscode/issues/212949) @deepak1556
- [ ] V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556

### Documentation
- [x] Add Testing user guide [vscode-docs#7208](https://github.com/microsoft/vscode-docs/issues/7208) @ntrogh
- [x] Create a terminal getting started tutorial [vscode-docs#7360](https://github.com/microsoft/vscode-docs/issues/7360) @ntrogh @tyriar
- [ ] :runner: Create an outline for overall getting started experience [vscode-docs#7359](https://github.com/microsoft/vscode-docs/issues/7359) @ntrogh @bhavyaus
- [ ] :runner: Update extension guide documentation with latest issue reporter guidance @justschen

---
### Deferred
- [ ] Add url handling for settings [vscode#212079](https://github.com/microsoft/vscode/issues/212079) @alexr00
- [ ] Command to Toggle comment for multiple cells [vscode#142437](https://github.com/microsoft/vscode/issues/142437) @Yoyokrazy
- [ ] Explore Terminal Buffer access for extensions [vscode#207504](https://github.com/microsoft/vscode/issues/207504) @tyriar
- [ ] SCM accessibility improvements [vscode#203577](https://github.com/microsoft/vscode/issues/203577) @lszomoru @meganrogge
