### ISSUE TITLE
New policy 

### ISSUE THREAD

**Issue by yaseenaljamal** [microsoft/vscode#216945]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/214070
- [ ] https://github.com/microsoft/vscode/pull/213986
- [ ] https://github.com/microsoft/vscode/issues/209802
```
