### ISSUE TITLE
jjmace7 

### ISSUE THREAD

**Issue by romanmace615** [microsoft/vscode#218344]
adb shell pm grant com.netvor.settings.database.editor android.permission.WRITE_SECURE_SETTINGS
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/218340
- [ ] https://github.com/microsoft/vscode/issues/218343
- [ ] https://github.com/microsoft/vscode/issues/218339
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/218343
- [ ] https://github.com/microsoft/vscode/issues/218341
```

**Comment by gjsjohnmurray** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/218340

**Comment by VSCodeTriageBot** [comment]
Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for [similar existing issues](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+). See also our [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Happy Coding!
