### ISSUE TITLE
March Iteration Plan

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#21923]
This plan captures the focus of our work during the March iteration. It's a 5 week iteration. We will ship **early April**.

## Endgame
- *March, 27th*: Code freeze for the endgame
- *March 31st*: Endgame done

The endgame details for this iteration are tracked in #23276.

## Plan Items

Below is a summary of the top level plan items.

Legend for annotations:

| Mark  | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Workbench
- [x] Initial investigation into multi-root, multi-folder workspaces #396 @bpasero @Tyriar
- [x] Additional theming options in the workbench #3112 @aeschli @bpasero
- [x] Search speed improvements #19983 @roblourens
- [x] Polish - Affordance to maximize Panel #22135 @isidorn
- [x] UI - Investigate on improve key binding customization support #18095 @sandy081 @alexandrudima
- [x] UI - support to keep files deleted on disk open in the editor @bpasero

##### Tasks
  - [x] Support contributing problem matchers #22066 @dbaeumer
  - [x] Define TaskProvider API #22069 @dbaeumer 

### Editor
- [x] Move keybinding dispatching off e.keyCode @alexandrudima  #17521
- [x] Polish mini map support [(see query)](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=label%3Aeditor-minimap%20milestone%3A%22March%202017%22%20) @alexandrudima
- [x] Polish drag & drop support (clean up event ordering) #22094 @rebornix
- [x] Polish rich text copy/paste #22095 @rebornix
- [x] Investigate offline spell checking #20266 @rebornix
- [x] Improve auto completion with fuzzy matching #22153 @jrieken

### Terminal
- [x] Terminal improvements to support tasks @Tyriar
   - [x] link validation #21226 @Tyriar
   - [x] argument parsing for commands #19078 @Tyriar
- [x] Revisit: Terminal settings as workspace settings #19758 @Tyriar
- [x] UI - navigate to links on modifier click only #21506 @Tyriar

##### Languages UI
- [x] Suggestions in comments - revisit and reopen #9504 and leverage new token types in API @jrieken

##### TypeScript/JavaScript
- [x] Support Implementors Code Lens #20832 @mjbvz
- [x] Adopt cancellation support #18053 @mjbvz
- [x] Investigate performance issues reported for TS Server #22102 @mjbvz
- [x] Track TS server extension API #22101 @mjbvz

##### Markdown
- [x] Explore extension mechanisms for the buiilt-in markdown support #22916 @mjbvz

### Debugging
- [x] Support async stack frames  #5552 @roblourens @weinand
- [x]  Show all source code when debugging against a remote process #20355 https://github.com/Microsoft/vscode-chrome-debug-core/issues/182 @weinand @roblourens
- [x] Surface new Exception DAP in UI #22078 @weinand @michelkaporin 
- [x] Support a server mode for debug adapters #22080 @weinand
- [x] Debt: Support env variables for extension host debugging #22150 @weinand
- [x] Debt: Reliable inline instruction pointer (e.g. multi threaded programs) #21122 @weinand @isidorn
- [x] Explore: Add debug menu to improve discoverability #22077 @isidorn
- [x] Explore: configuration UI (quick pick) for exceptions #18093 @weinand
- [ ]  :runner: Experiment: support Live Edit for node-debug (legacy protocol) #6930 @weinand
- [x] Edit breakpoint conditions with multiple breakpoint on same line #21151 @isidorn

### Extension Authoring
- [x] SCM - finish API based on feedback from early adapters #15894 @joaomoreno
- [x] SCM - make the git SCM Provider the default git support #22131 @joaomoreno
- [x] Support large extension, adopt new marketplace support #18146 @joaomoreno
- [x] Expose progress API #18066 @jrieken
- [x] Control script execution in HTML preview #22103 @mjbvz
- [x] Investigate more types for CompletionItemKind enum #2628 @jrieken
- [x] Add support for a ContentProvider (only interested in content, not a Document) #15723 @jrieken

### Contributions to Extensions
- [x] TSLint: investigate into running tslint as a TS server extension Microsoft/vscode-tslint#171 @egamma
- [x] Docker - add telemetry @chrisdias
- [x] Go - https://github.com/Microsoft/vscode-go/issues/837 @ramya-rao-a
- [ ] :runner: PHP - language server contributions https://github.com/felixfbecker/php-language-server/issues/323 @mousetraps
- [ ] :runner: PHP - continued progress on PHP parser https://github.com/Microsoft/tolerant-php-parser/milestone/2 @mousetraps

### Engineering Items
- [x] Assess Electron adoption @bpasero
   - [x] Understand impact of Electron update on keycodes @alexandrudima
- [ ] :runner: Investigate into proxy issues #22214 @joaomoreno
- [x] extension host error spamming the core #22804 @kieferrm

##### Startup performance
- [x] Support that users can capture and report an execution profile on slow startup #21631 @jrieken

##### Translations
- [x] Import/export to xliff #22092 @michelkaporin
- [x] Explore doing translations using transifex #22070 @dbaeumer @michelkaporin

##### Telemetry
- [x] Finish migration of backend @ramya-rao-a
- [x] Prune error telemetry @ramya-rao-a

##### Documentation
- [x] New TOC on website @waderyan @gregvanl 
- [x] Update vscode-samples @chrisdias @kieferrm

----

### Deferred
- Editor architectural documentation @rebornix @alexandrudima
- UI - explore improved notification story #22388 @stevencl @chrisdias
- Debug - Support to copy the entire text of the debug console #2163 @isidorn
- Tasks - Support that an extension defines the 'Build' command #22067 @dbaeumer
- Tasks - Enable link detection for common error messages #21928 @dbaeumer
- Investigate into UI extension API, improve HTML preview #22068 @jrieken
- HTML - format on paste support #21218 @aeschli
- HTML - tag completion #2246 @aeschli
- Investigate improve release notes for Insiders #22051 @joaomoreno @gregvanl

---

- Move lines up/down with auto indent #22093 @rebornix
- Explore emmet 2.0 support #21943 @ramya-rao-a
- Separate 'configuration' from 'learning' quick links #22097 @chrmarti
- Investigate to provide guidance for technology stacks #22098 @chrmarti @chrisdias
- Enable Electron Crash reporter for all processes after Electron update #21944 @ramya-rao-a 
- Support migrating from 0.1.0 to 2.0.0 #22065 @dbaeumer

**Comment by equinusocio** [comment]
I hope for this
> Additional theming options in the workbench (colors, fonts)

**Comment by dariusrosendahl** [comment]
Would love 

> Investigate into multi-root, multi-folder workspaces #396 @bpasero @Tyriar

To be able to completely replace Sublime / Atom

**Comment by opus131** [comment]
FYI this is not linked from the wiki page yet:
https://github.com/Microsoft/vscode/wiki/Iteration-Plans

**Comment by equinusocio** [comment]
> Improve website download performance Microsoft/vscode-website#521 @waderyan
 #521 is a 404

**Comment by jens1o** [comment]
@equinusocio I think it's just a private repo 😉

**Comment by equinusocio** [comment]
@jens1o right

**Comment by Tyriar** [comment]
@opus131 I added it plus the missing endgame issues :+1:

**Comment by opus131** [comment]
@Tyriar thank you!

**Comment by zbandhan** [comment]
It's really adorable. VS CODE is gonna improve in unbelievable velocity. Thanks VS CODE team and everyone behind this nice project.

**Comment by equinusocio** [comment]
I hope that "Additional theming options in the workbench" is not just a "on/off" show setting

**Comment by egamma** [comment]
Closing the March release has been published.
