### ISSUE TITLE
Cr

### ISSUE THREAD

**Issue by Dgggreevj** [microsoft/vscode#219805]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/218666
- [ ] https://github.com/microsoft/vscode/issues/219277
- [ ] https://github.com/microsoft/vscode/issues/219804
- [ ] https://github.com/microsoft/vscode/pull/208526
- [ ] https://github.com/microsoft/vscode/pull/212387
- [ ] https://github.com/microsoft/vscode/pull/219803
```
