### ISSUE TITLE
Iteration Plan for July 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#220925]
This plan captures our work in **July**. This is a 4-week iteration. We will ship in **early August**.

## Endgame

- **July 22, 2024**: Endgame begins
- **July 26, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22July+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22July+2024%22) @meganrogge **team**

### Workbench
- [x] Add url handling for settings [vscode#212079](https://github.com/microsoft/vscode/issues/212079) @alexr00
- [x] Polish Profiles Editor UX [vscode#218162](https://github.com/microsoft/vscode/issues/218162) @sandy081
- [x] Support an icon button style in quick pick [vscode#221397](https://github.com/microsoft/vscode/issues/221397) @TylerLeonhardt
- [x] Support panel at the top [vscode#50984](https://github.com/microsoft/vscode/issues/50984) @benibenj
- [ ] :muscle: Tree: Support contributable find providers [vscode#212077](https://github.com/microsoft/vscode/issues/212077) @benibenj
- [x] Improve basic auth proxy support [vscode#220034](https://github.com/microsoft/vscode/issues/220034) @chrmarti

### Code Editor
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00
- [x] Allow editor.codeActionsOnSave for autoSave afterDelay [vscode#200881](https://github.com/microsoft/vscode/issues/200881) @justschen
- [x] Improve where the lightbulb widget appears in the editor and notebook [vscode#202767](https://github.com/microsoft/vscode/issues/202767) @justschen
- [x] Improve jumping when Code Lenses appear [vscode#216824](https://github.com/microsoft/vscode/issues/216824) @hediet
- [x] Improve the diff editor when rendered in narrow containers [vscode#221245](https://github.com/microsoft/vscode/issues/221245) @hediet
- [ ] :runner: Adopt EditContext [vscode@207700](https://github.com/microsoft/vscode/issues/207700) @aiday-mar @hediet
- [ ] :runner: Release Monaco Editor @aiday-mar @hediet

### Notebook Editor
- [x] Command to Toggle comment for multiple cells [vscode#142437](https://github.com/microsoft/vscode/issues/142437) @Yoyokrazy
- [ ] :runner: Proposal for restructuring and cleaning up the context menu in Notebook [vscode#219240](https://github.com/microsoft/vscode/issues/219240) @Yoyokrazy
- [ ] :muscle: Explore supporting <kbd>cmd</kbd>+<kbd>d</kbd> across multiple cells [vscode#141673](https://github.com/microsoft/vscode/issues/141673) @Yoyokrazy
- [ ] :muscle: Improve rendering of large code cell editor (e.g., sticky execution count) [vscode#209154](https://github.com/microsoft/vscode/issues/209154) @rebornix
- [ ] :muscle: Explore hiding/collapsing unchanged cells in Notebook Diff Editor [vscode#174152](https://github.com/microsoft/vscode/issues/174152) @DonJayamanne

### Search
- [ ] :runner: Explore finalizing `FileSearchProvider` API [vscode#73524](https://github.com/microsoft/vscode/issues/73524) @andreamah
- [ ] :runner: Explore finalizing `TextSearchProvider` API [vscode#59921](https://github.com/microsoft/vscode/issues/59921) @andreamah

### Issue Reporter
- [ ] :runner: Continue migrating desktop issue report to auxiliary service approach [vscode#213332](https://github.com/microsoft/vscode/issues/213332) @justschen
- [x] Incorporate issue reporter participation into `yo code` generator [vscode#220969](https://github.com/microsoft/vscode/issues/220969) @justschen

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22July+2024%22) @karthiknadig **team**

#### Language Server Protocol
- [x] Investigate into delaying open event to avoid sending open/close notification pairs to the server when VS Code reads file contents [#lsp-848](https://github.com/microsoft/vscode-languageserver-node/issues/848) @dbaeumer

### Testing
- [ ] :hand: Finalize attributable test coverage API [vscode#212196](https://github.com/microsoft/vscode/issues/212196) @connor4312
- [x] Support stack traces in test messages [vscode#214488](https://github.com/microsoft/vscode/issues/214488) @connor4312
- [x] Explore support for related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312

#### Debug Adapter Protocol
- [ ] :muscle: Explore green thread support [debug-adapter-protocol#339](https://github.com/microsoft/debug-adapter-protocol/issues/339) @connor4312

### Terminal
- [x] Adopt esbuild and ship ESM module with xterm.js [xterm.js#2878](https://github.com/xtermjs/xterm.js/issues/2878) @tyriar
- [x] Adopt VS Code scrollbar in xterm.js [vscode#216521](https://github.com/microsoft/vscode/issues/216521) @tyriar
- [ ] :runner: Finalize shellIntegration API [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @tyriar
- [ ] :runner: Iterating on pwsh suggest and PromptInputModel [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar

### Source Control
- [ ] :runner: Graph visualization for Incoming/Ougoing view [vscode#215439](https://github.com/microsoft/vscode/issues/215439) @lszomoru
- [x] Adopt shell integration API for git commands [vscode#220995](https://github.com/microsoft/vscode/issues/220995) @lszomoru @tyriar

### API
- [ ] :runner: API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [x] Print packaged extension contents on package/publish [vscode-vsce#995](https://github.com/microsoft/vscode-vsce/issues/995) @benibenj
- [x] Polish extension auto-update mechanism [vscode#219720](https://github.com/microsoft/vscode/issues/219720) @sandy081

### Extension Contributions
- [x] Support reverting merged PR changes [vscode-pull-request-github#2103](https://github.com/microsoft/vscode-pull-request-github/issues/2103) @alexr00

### Engineering
- [ ] :runner: Explore AMD to ESM migration [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken @bpasero

### Electron
- [x] Electron 30 upgrade [vscode#214394](https://github.com/microsoft/vscode/issues/214394) @deepak1556
- [ ] :runner: V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556
- [x] Adopt basic auth support for net api in utility process [vscode#212949](https://github.com/microsoft/vscode/issues/212949) @deepak1556

### Documentation
- [ ] :muscle: Update Getting Started experience doc [vsocde-docs#7359](https://github.com/microsoft/vscode-docs/issues/7359) @ntrogh

---
### Deferred
- [ ] Explore GPU rendering of the code editor [vscode#221145](https://github.com/microsoft/vscode/issues/221145) @tyriar @hediet
- [ ] Support Exceptions for result return types [#wasm-177](https://github.com/microsoft/vscode-wasm/issues/177) @dbaeumer
- [ ] Add SCM accessibility help dialog [vscode#203577](https://github.com/microsoft/vscode/issues/203577) @lszomoru @meganrogge

**Comment by gjsjohnmurray** [comment]
> * **July 24, 2024**: Endgame begins
> * **July 26, 2024**: Endgame done

@kieferrm previous endgames have typically started on a Monday. Any reason for this one showing a Wednesday start?

**Comment by kieferrm** [comment]
> > * **July 24, 2024**: Endgame begins
> > * **July 26, 2024**: Endgame done
> 
> [@kieferrm](https://github.com/kieferrm) previous endgames have typically started on a Monday. Any reason for this one showing a Wednesday start?

Good catch. Thank you.
