### ISSUE TITLE
Damarcus Jones Ai Chips

### ISSUE THREAD

**Issue by corp-jones-damarcus** [microsoft/vscode#221420]
https://scout.docker.com/org/damarcusjonesaichips/settings/integrations/slack/add?inviterEmail=damarcusjonesaichips%40gmail.com

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/213485
- [ ] https://github.com/microsoft/vscode/issues/212005
- [ ] https://github.com/microsoft/vscode/issues/209962
- [ ] https://github.com/microsoft/vscode/issues/213494
- [ ] https://github.com/microsoft/vscode/issues/213510
- [ ] https://github.com/microsoft/vscode/pull/221419
- [ ] https://github.com/microsoft/vscode/issues/213491
- [ ] https://github.com/microsoft/vscode/issues/213496
```
