### ISSUE TITLE
git@github.com:donnemartin/system-design-primer.git

### ISSUE THREAD

**Issue by Macyoutuber** [microsoft/vscode#221516]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2. 

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/221515
- [ ] https://github.com/microsoft/vscode/pull/221514
- [ ] https://github.com/microsoft/vscode/pull/221513
- [ ] https://github.com/microsoft/vscode/pull/221511
- [ ] https://github.com/microsoft/vscode/pull/221510
- [ ] https://github.com/microsoft/vscode/pull/221500
- [ ] https://github.com/microsoft/vscode/pull/221508
- [ ] https://github.com/microsoft/vscode/issues/35337
- [ ] https://github.com/microsoft/vscode/pull/214041
```

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/pull/221514
- [ ] https://github.com/microsoft/vscode/pull/221510
```
