### ISSUE TITLE
Explore adopting multi file diff editor for notebook diff

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#224760]
```[tasklist]
### Tasks
- [x] New Editor behind a setting
- [ ] Ability to edit cells on the right hand side
- [ ] Ability to edit outputs/metadata on the right hand side (ensure metadata changes are validated, as valid JSON before saving)
- [x] Ability to revert input, metadata and output
- [x] Address issue with not being able to open editor more than once
- [ ] Toggle between rich and plain text outputs
- [ ] View white space differences in cells
- [x] Collapse unchanged cells (perhaps we can display them and just collapse by default, instead of hiding them?)
- [x] Navigation icons in editor toolbar to navigate to next/previous changed cell
- [x] Menu to show/hide metadata/output differences
- [ ] Breadcrumbs in new Editor (for some reason its not displayed)
- [x] Possibly display all output/metadata and suffix with (changed) and expand changed items by default (instead of hiding them)
- [ ] Change progress lable from `No Changed Files` to something else (e.g. `Computing Notebook Diffs`)
```

**Comment by DonJayamanne** [comment]
<details>
  <summary>Internal Notes</summary>
  
**Features not available in multi-diff that will need to be added**
* Diff overview ruler
* Display unmodified cells (akin to displaying un-modified files) & ability to hide/collapse these 
    * Will be required for diff overview ruler as well
* Custom toolbar actions
    * Revert a cell
    * Revert changes to metadata
    * Revert changes to outputs
* Add margin for metadata & output diff view (but not allow reverting individual parts, as we only allow reverting everything)
    * I.e. we do not want to give fine grained control of diff editing of metadata changes.
* Grouping a cell (i.e. ensure sub-sections under the cell resource for output/metadata, etc)
    * Current approach of treating them as separate resources works, but feels wrong (no separation between cells)
    * Perhaps having the ability to group resources would work
* Custom names of the resources (currently file name cannot be removed)
* Ignore white space (per resource/cell)
* Accessibility (e.g. keyboard navigation between cells)
* Optionally: Ability to have custom content in each diff view item
    * Current work around of using editor insets works best (before we build something more generic)

**Other changes**
* Ability to create read-write editor models (currently all virtual text models are readonly), only file backed models are read-write.
    * Need to create a custom impl of `TextResourceEditorModel` & modify `textModelResolverService.ts`

**Output Diffing**
* Using individual web views for each output seems to work 
    * However still using the backview layer components with messages being sent back n forth).
    * I.e. given we're using the same infra structure, we might as well use the single webview approach.
* There are some delays in loading the webviews

**Multi-Diff Editor View Model** 
Current approach of using a custom impl of `IMultiDiffSourceResolver` works, 
* However we need access to the current Diff Editor (`IEditorGroup`)
* We need the ability to store local disposables (the source resolver doesn't provide that option)
    * Perhaps a custom EditorInput class will work (but requires changes to multi-diff editor class)
* 
</details>

**Comment by DonJayamanne** [comment]
* Ability to mark an editor as editable (right now cells cannot be edited as they are virtual documents, unless we make a change in core text resource provider)
* custom context for toolbar actions (currently hardcoded to pass uri)
* Changes to expose a custom context object via view model (currently need to perform lookup via uri, similar to previous request)
* Custom collapsible sections (with a hierarchy)
    * Custom borders to  clearly distinguish between cells, metadata, etc)
* Toggle white space differences per item (or resource type)
* Change progress lable from No Changed Files to something else (e.g. Computing Notebook Diffs)
* ability to hide/collapse unchanged cells (like unchanged lines)
* ability to navigate to each item (keyboard navigation to next changed cell)
    * ie ficus next item if not visible in viewport
* Custom editors (webview support in outputs)
*
