### ISSUE TITLE
Iteration Plan for August 2024 [DRAFT]

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#224756]
This plan captures our work in **August**. This is a 5-week iteration. We will ship in **early September**.

## Endgame

- **August 26, 2024**: Endgame begins
- **August 30, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22August+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22August+2024%22) @meganrogge **team**

### UX
- [ ] :red_circle: Proposal for cleaning up our context menus @daviddossett

### Workbench
- [ ] :muscle: Tree: Support contributable find providers [vscode#212077](https://github.com/microsoft/vscode/issues/212077) @benibenj

### Code Editor
- [ ] Explore GPU rendering of the code editor [vscode#221145](https://github.com/microsoft/vscode/issues/221145) @tyriar @hediet
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00
- [ ] :runner: Adopt `EditContext` [vscode@207700](https://github.com/microsoft/vscode/issues/207700) @aiday-mar @hediet
- [ ] :runner: Release Monaco Editor @aiday-mar @hediet

### Notebook Editor
- [ ] API proposal for IW/REPL (`openNotebookDocument` with additional `mode: repl`) [vscode#154983](https://github.com/microsoft/vscode/issues/154983) @amunger
- [ ] Review REPL/IW Accessibility [vscode#209140](https://github.com/microsoft/vscode/issues/209140) @amunger
- [ ] Support for toggling comments on cells outside of the viewport [vscode#22344](https://github.com/microsoft/vscode/issues/223344) @Yoyokrazy
- [ ] Explore supporting <kbd>cmd</kbd>+<kbd>d</kbd> across multiple cells [vscode#141673](https://github.com/microsoft/vscode/issues/141673) @Yoyokrazy
- [ ] :muscle: Proposal for restructuring and cleaning up the context menu in Notebook [vscode#219240](https://github.com/microsoft/vscode/issues/219240) @Yoyokrazy
- [ ] Improve rendering of large code cell editor (e.g., sticky execution count) [vscode#209154](https://github.com/microsoft/vscode/issues/209154) @rebornix
- [ ] Explore hiding/collapsing unchanged cells in Notebook Diff Editor [vscode#174152](https://github.com/microsoft/vscode/issues/174152) @DonJayamanne
- [ ] :red_circle: Support inlinediff/wordwrap/whitespace in Notebook Diff Editor @DonJayamanne
- [ ] :red_circle: Explore adopting multi file diff editor for notebook diff @DonJayamanne

### Search
- [ ] :runner: Prepare `FileSearchProvider` API for finalization [vscode#73524](https://github.com/microsoft/vscode/issues/73524) @andreamah
- [ ] :runner: Prepare `TextSearchProvider` API for finalization [vscode#59921](https://github.com/microsoft/vscode/issues/59921) @andreamah

### WebAssembly Support
- [ ] Support Exceptions for result return types [#wasm-177](https://github.com/microsoft/vscode-wasm/issues/177) @dbaeumer

### Issue Reporter
- [ ] :runner: Finish migrating desktop issue report to auxiliary service approach [vscode#213332](https://github.com/microsoft/vscode/issues/213332) @justschen

#### TypeScript
- [ ] Investigate performance issues when adding all missing imports [vscode#208911](https://github.com/microsoft/vscode/issues/208911) @justschen
- [ ] Investigate folding issues with imports [vscode#156675](https://github.com/microsoft/vscode/issues/156675) @justschen
- [ ] :muscle: Explore support adding imports via drag and drop from explorer [](https://github.com/microsoft/typescript/issues/50170) @justschen

#### Python
- [ ] :runner: Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22August+2024%22) @karthiknadig **team**

#### Language Server Protocol
- None.

### Authentication
- [ ] :red_circle: Explore UX for switching accounts for extensions @TylerLeonhardt

### Testing
- [ ] Finalize attributable test coverage API [vscode#212196](https://github.com/microsoft/vscode/issues/212196) @connor4312
- [ ] Finalize Call stacks API [vscode#214488](https://github.com/microsoft/vscode/issues/214488) @connor4312
- [ ] Finalize Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [ ] Improve UX of the new call stack widget @connor4312 @daviddossett

### Debug
- [ ] Support find in the debug console [vscode#4338](https://github.com/microsoft/vscode/issues/4338) @meganrogge @connor4312

#### Debug Adapter Protocol
- [ ] :muscle: Explore green thread support [debug-adapter-protocol#339](https://github.com/microsoft/debug-adapter-protocol/issues/339) @connor4312
- [ ] BreakpointEvent enhancements for data breakpoints [debug-adapter-protocol#406](https://github.com/microsoft/debug-adapter-protocol/issues/406) @connor4312

### Terminal
- [ ] :runner: Finalize `shellIntegration` API [vscode#145234](https://github.com/microsoft/vscode/issues/145234) @tyriar
- [ ] :runner: Iterating on `pwsh` suggest and PromptInputModel [vscode#154662](https://github.com/microsoft/vscode/issues/154662) @tyriar

### Tasks
- [ ] Explore issues with duplicated terminals [vscode#216826](https://github.com/microsoft/vscode/issues/216826) @meganrogge

### Source Control
- [ ] Add SCM accessibility help dialog [vscode#203577](https://github.com/microsoft/vscode/issues/203577) @lszomoru @meganrogge
- [ ] Support for blame inline decorations [vscode#203841](https://github.com/microsoft/vscode/issues/203841) @lszomoru
- [ ] Support new git `reftable` format [vscode#221642](https://github.com/microsoft/vscode/issues/221642) @lszomoru

### API
- [ ] :runner: API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz
- [ ] Finalize the GetAccounts API [vscode#145307](https://github.com/microsoft/vscode/issues/145307) @TylerLeonhardt

### Extensions
- [ ] :muscle: Make repository signature verification blocking [vscode#223942](https://github.com/microsoft/vscode/issues/223942) @sandy081 @isidorn
- [ ] :muscle: Investigate different extension update mechanisms [vscode#215555](https://github.com/microsoft/vscode/issues/215555) @sandy081 @isidorn

### Extension Contributions
- [ ] :runner: Improvements to the Remote extensions, see [plan](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22August+2024%22) @roblourens @chrmarti @connor4312 @joyceerhl
- [ ] Create suggestions from working tree changes [vscode-pull-request-github#5256](https://github.com/microsoft/vscode-pull-request-github/issues/5256) @alexr00

### Engineering
- [ ] :runner: Explore AMD to ESM migration [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @jrieken @bpasero
- [ ] Investigate moving from yarn back to npm [vscode#196795](https://github.com/microsoft/vscode/issues/196795) @deepak1556

### Electron
- [ ] :runner: V8: Support usage of external array buffers for embedders in sandbox mode [chromium#14585](https://bugs.chromium.org/p/v8/issues/detail?id=14585#c3) @deepak1556
- [ ] Crash when searching in extension preview editor [vscode#177046](https://github.com/microsoft/vscode/issues/177046) @rzhao271

### Documentation
- [ ] :muscle: Update Getting Started experience doc [vsocde-docs#7359](https://github.com/microsoft/vscode-docs/issues/7359) @ntrogh

---
### Deferred
- None.

**Comment by faheemstepsharp** [comment]
Is there any plan for a Windows 11-inspired UI/UX in VS Code, featuring modern design elements like rounded corners, sleek animations, and subtle shadows? Adding native hover information with rich content previews (e.g., images and links), as well as improved preview features for Markdown and files, would enhance the overall experience. However, these updates should be optimized to avoid impacting performance, especially for developers working on resource-heavy tasks. Additionally, better extension management and a built-in system resource monitor could help maintain a responsive and efficient environment.

**Comment by faheemstepsharp** [comment]
August release DATE?
