### ISSUE TITLE
Breach..

### ISSUE THREAD

**Issue by bysnet** [microsoft/vscode#227290]
Type: <b>Bug</b>

Over the past 2 days I have experienced some minor issues when working on the Visual Studio Code app, but now ALL my repositories in GitHub and Cloudflare have all (12 buckets) been emptied. GitHub profiles do not allow updates or change of setting and all Extensions have been uninstalled!

VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 3, 6|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 070a98a2-e676-4bf4-a9cc-8cc1c1df80b6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
9c06g630:31013171
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
ei213698:31121563
aajjf12562:31125793

```

</details>

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode/issues/227288
- [ ] https://github.com/microsoft/vscode/issues/227285
- [ ] https://github.com/microsoft/vscode/issues/196948
- [ ] https://github.com/microsoft/vscode/issues/227286
- [ ] https://github.com/microsoft/vscode/pull/227289
- [ ] https://github.com/microsoft/vscode/pull/227287
- [ ] https://github.com/microsoft/vscode/issues/183199
- [ ] https://github.com/microsoft/vscode/issues/225468
- [ ] https://github.com/microsoft/vscode/issues/190569
- [ ] https://github.com/microsoft/vscode/issues/173861
- [ ] https://github.com/microsoft/vscode/issues/227068
- [ ] https://github.com/microsoft/vscode/issues/227284
- [ ] https://github.com/microsoft/vscode/issues/227222
```

**Comment by mjbvz** [comment]
The number of linked issues makes this seems like spam. And without evidence, this does not sound related to VS Code anyways
