### ISSUE TITLE
Iteration Plan for September 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#228053]
This plan captures our work in **September**. This is a 4-week iteration. We will ship in **early October**.

## Endgame
- **September 23, 2024**: Endgame begins
- **September 27, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22September+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22September+2024%22) @meganrogge **team**
- [x] <kbd>alt</kbd>+<kbd>f1</kbd> in standalone editor [monaco-editor#4583](https://github.com/microsoft/monaco-editor/issues/4583) @hediet @meganrogge
- [x] Allow focusing the suggestion details [vscode#190096](https://github.com/microsoft/vscode/pull/190096) @jrieken

### Workbench
- [x] Provide a way to sent ad-hoc notifications for Insiders users [vscode#227321](https://github.com/microsoft/vscode/issues/227321) @bpasero
- [x] Tree: Support contributable find providers [vscode#212077](https://github.com/microsoft/vscode/issues/212077) @benibenj
- [x] Support `setting(my-setting-id)` syntax in Release Notes editor [vscode#228736](https://github.com/microsoft/vscode/issues/228736) @alexr00
- [x] Support a workspace table in profiles editor [vscode#228087](https://github.com/microsoft/vscode/issues/228087) @sandy081

### Code Editor
- [ ] :runner: Explore GPU rendering of the code editor [vscode#221145](https://github.com/microsoft/vscode/issues/221145) @tyriar @hediet
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00 @hediet
- [ ] :runner: Make `EditContext` the default input strategy [vscode#228093](https://github.com/microsoft/vscode/issues/228093) @aiday-mar @hediet
- [x] Syntax highlighting for inline completions [vscode#225400](https://github.com/microsoft/vscode/issues/225400) @hediet
- [x] Release Monaco Editor @aiday-mar @hediet

### Notebook Editor
- [ ] :runner: Review REPL/IW Accessibility [vscode#209140](https://github.com/microsoft/vscode/issues/209140) @amunger
- [ ] :runner: Support core actions (type/cut/paste/delete/undo/redo) for multi cursors (<kbd>cmd</kbd>+<kbd>d</kbd>) across cells [vscode#141673](https://github.com/microsoft/vscode/issues/141673) @Yoyokrazy
- [ ] :runner: Clean up and review usage of notebook context menu (telemetry + proposal) [vscode#219240](https://github.com/microsoft/vscode/issues/219240) @Yoyokrazy
- [x] Notebook diff: support collapsing unmodified lines in cell input/metadata editor [vscode#227927](https://github.com/microsoft/vscode/issues/227927) @DonJayamanne
- [x] Notebook diff: support rendering notebook document metadata changes [vscode#208280](https://github.com/microsoft/vscode/issues/208280) @DonJayamanne

### Search
- [ ] :runner: Prepare `FileSearchProvider` API for finalization [vscode#73524](https://github.com/microsoft/vscode/issues/73524) @andreamah
- [ ] :runner: Prepare `TextSearchProvider` API for finalization [vscode#59921](https://github.com/microsoft/vscode/issues/59921) @andreamah

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22September+2024%22) @karthiknadig **team**

### Authentication
- [x] Add UX for switching accounts for extensions [vscode#225943](https://github.com/microsoft/vscode/issues/225943) @TylerLeonhardt

### Testing
- [ ] :muscle: Finalize attributable test coverage API [vscode#212196](https://github.com/microsoft/vscode/issues/212196) @connor4312
- [ ] :muscle: Finalize Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312

### Debug
- [ ] :muscle: Find in output [vscode#225417](https://github.com/microsoft/vscode/issues/225417) @meganrogge
- [ ] :muscle: Explore supporting reverse search in tree find to remove filter widget [vscode#227009](https://github.com/microsoft/vscode/issues/227009) @meganrogge
#### Debug Adapter Protocol
- [x] Support for ANSI styling [debug-adapter-protocol#500](https://github.com/microsoft/debug-adapter-protocol/issues/500) @connor4312

### Terminal
- [ ] :runner: API to expose the shell's actual environment to extensions [vscode#227467](https://github.com/microsoft/vscode/issues/227467) @anthonykim1
- [ ] :runner: :muscle: Add support for terminal suggest in zsh/bash [vscode#226562](https://github.com/microsoft/vscode/issues/226562) @meganrogge

### Source Control
- [ ] Add SCM accessibility help dialog [vscode#203577](https://github.com/microsoft/vscode/issues/203577) @lszomoru @meganrogge
- [x] Polish multi-repository scenario in SCM Graph view [vscode#227211](https://github.com/microsoft/vscode/issues/227211) @lszomoru
- [x] Support selecting branches in SCM Graph view [vscode#227213](https://github.com/microsoft/vscode/issues/227213) @lszomoru
- [x] Polish hover and context menu action in SCM Graph commits [vscode#227214](https://github.com/microsoft/vscode/issues/227214) @lszomoru

### API
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x]  API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [x] Make repository signature verification blocking [vscode#223942](https://github.com/microsoft/vscode/issues/223942) @sandy081 @isidorn
- [x] Support update extensions across profiles [vscode#193446](https://github.com/microsoft/vscode/issues/193446) @sandy081
- [x] Dependent extension is not activated if the depending extension gets activated after getting updated [vscode#226660](https://github.com/microsoft/vscode/issues/226660) @sandy081
- [x] Improve extension incompatibility UX [vscode#227047](https://github.com/microsoft/vscode/issues/227047) @sandy081
- [ ] :runner: Change the global `fetch` available in local extension hosts to be the one from Electron [vscode#228696](https://github.com/microsoft/vscode/issues/228696) @chrmarti

### Remote Extension Contributions
- [ ] :runner: Add proxy support to the `fetch` defined by node when in a remote [vscode#228697](https://github.com/microsoft/vscode/issues/228697) @chrmarti

#### SSH Extension
- [x] `remote.SSH.connectTimeout` overrides ConnectTimeout from config file [vscode-remote-release#8519](https://github.com/microsoft/vscode-remote-release/issues/8519) @joshspicer
- [ ] :runner: Catalog configurations for remote testing [vscode-remote-release#10248](https://github.com/microsoft/vscode-remote-release/issues/10248) @joshspicer

### Engineering
- [x] Finish AMD to ESM migration [vscode#160416](https://github.com/microsoft/vscode/issues/160416) @bpasero @jrieken
- [x] Support building the monaco-editor ESM variant from new sources [vscode#227192](https://github.com/microsoft/vscode/issues/227192) @bpasero @hediet
- [ ] Support building the monaco-editor AMD variant from new sources @hediet @alexdima
- [ ] Support blocking startup on pending update [vscode#227322](https://github.com/microsoft/vscode/issues/227322) @bpasero
- [x] Stabilize FS watcher issues [vscode#216825](https://github.com/microsoft/vscode/issues/216825) @bpasero

### Electron
- [ ] :runner: Crash when searching in extension preview editor [vscode#177046](https://github.com/microsoft/vscode/issues/177046) @rzhao271
- [x] Electron 32 update [vscode#218245](https://github.com/microsoft/vscode/pull/218245) @deepak1556
- [ ] :runner: Support for V8 sandbox in the extension host [vscode#202385](https://github.com/microsoft/vscode/issues/202385) @deepak1556

### Documentation
- [x] Update Getting Started experience doc [vscode-docs#7359](https://github.com/microsoft/vscode-docs/issues/7359) @ntrogh
- [x] Explore updated Docs landing page to improve call-to-actions [vscode-docs#7544](https://github.com/microsoft/vscode-docs/issues/7544) @ntrogh @daviddossett @bamurtaugh
- [x] Refresh Workspace Trust article [vscode-docs#7545](https://github.com/microsoft/vscode-docs/issues/7545) @ntrogh
- [x] Describe Application settings [vscode-docs#7480](https://github.com/microsoft/vscode-docs/issues/7480) @ntrogh
- [x] Revisit Doc Writer profile template [vscode-docs#7546](https://github.com/microsoft/vscode-docs/issues/7546) @ntrogh
- [x] Update Tips & Tricks to include product walkthroughs [vscode-docs#7547](https://github.com/microsoft/vscode-docs/issues/7547) @ntrogh

---
### Deferred
- [ ] Exploration on how to improve the diff algorithm [vscode#227928](https://github.com/microsoft/vscode/issues/227928) @DonJayamanne
- [ ] VSCode freezing when adding folder to workspace while working on remote Linux machine [vscode-remote-release#10168](https://github.com/microsoft/vscode-remote-release/issues/10168) @joshspicer
- [ ] Audit error handling [vscode-remote-release#10249](https://github.com/microsoft/vscode-remote-release/issues/10249) @joshspicer
- [ ] :runner: Create suggestions from working tree changes [vscode-pull-request-github#5256](https://github.com/microsoft/vscode-pull-request-github/issues/5256) @alexr00
- [ ] :runner: Proposal for cleaning up our context menus [vscode#225411](https://github.com/microsoft/vscode/issues/225411) @daviddossett
- [ ] Support for blame inline decorations [vscode#203841](https://github.com/microsoft/vscode/issues/203841) @lszomoru
- [ ] :muscle: Add setting to control rendering of multi-line inline completions [vscode#225399](https://github.com/microsoft/vscode/issues/225399) @hediet

**Comment by sanket-bhalerao** [comment]
apoogies for spamming
@lszomoru , @kieferrm  is there a roadmap for the git graph feature to see what might be coming in the future?

* is there a plan to show tags on the commits?
* is there a plan to soft/hard deletes?

**Comment by lszomoru** [comment]
> is there a plan to show tags on the commits?

you can enable that in the latest VS Code Insiders release using the `"scm.graph.badges": "all"` setting.

> is there a plan to soft/hard deletes?

yes, we will continue to expand the list of actions that are available in the Source Control Graph

**Comment by aguluman** [comment]
Hi, 
I'm having trouble adding a reviewer in my VS Code while creating a pull request using the in-IDE experience.

Is there a plan to add reviewers in VS-Code?

**Comment by iwangbowen** [comment]
We want new features

**Comment by aguluman** [comment]
> Hello, I'm having trouble adding a reviewer in my VS Code while creating a pull request using the in-IDE experience.
> 
> Is there a plan to add reviewers in VS-Code?

Thank you, admin, I noticed this has been fixed, and I can add a reviewer without context switching.

I appreciate your help with this one.

Have a great day.

**Comment by aguluman** [comment]
Contributors are not shown on the git icon page on VS-Code. It queries then times out.

Bringing it to your attention.  **thank you**
