### ISSUE TITLE
Iteration Plan for October 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#230653]
This plan captures our work in **October**. This is a 4-week iteration. We will ship in **early November**. With GH Universe right around the corner, we're working on several Copilot improvements. Thus, this month's core plan is more light than usual.

## Endgame
- **October 21, 2024**: Endgame begins
- **October 25, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22October+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [x] Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22October+2024%22) @meganrogge **team**

### Code Editor
- [ ] :runner: Make `EditContext` the default input strategy [vscode#228093](https://github.com/microsoft/vscode/issues/228093) @aiday-mar @hediet

#### Jupyter Notebooks
- [x] Update Jupyterlab npm package (supporting newer Jupyter server versions) [vscode-jupyter#14422](https://github.com/microsoft/vscode-jupyter/issues/14422) @DonJayamanne

#### Python
- [x] Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22October+2024%22) @karthiknadig **team**

### Authentication
- [x] Introduce method to add additional account when switching preferences [vscode#229496](https://github.com/microsoft/vscode/issues/229496) @tylerleonhardt

### API
- [x] API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [x] API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Electron
- [ ] :runner: Electron 32 update [vscode#218245](https://github.com/microsoft/vscode/pull/218245) @deepak1556
- [x] Electron upgrades duty @deepak1556
- [x] Crash when searching in extension preview editor [vscode#177046](https://github.com/microsoft/vscode/issues/177046) @rzhao271
- [ ] :runner: Align Electron fetch with Node.js fetch [electron#43715](https://github.com/electron/electron/issues/43715), [electron#43712](https://github.com/electron/electron/issues/43712) @deepak1556
- [ ] :runner: Explore enabling COI on desktop, context for current block [vscode#186614](https://github.com/microsoft/vscode/issues/186614) @deepak1556

### Documentation
- [x] Implement redesign of the Docs landing page [vscode-docs#7544](https://github.com/microsoft/vscode-docs/issues/7544) @ntrogh
- [ ] :runner: Address feedback from customer interviews on VS Code tutorial [vscode-internalbacklog#5127](https://github.com/microsoft/vscode-internalbacklog/issues/5127) @ntrogh

---
### Deferred
- [ ] Support building the monaco-editor AMD variant from new sources @hediet @alexdima
- [ ] Add SCM accessibility help dialog [vscode#203577](https://github.com/microsoft/vscode/issues/203577) @lszomoru @meganrogge
- [ ] :runner: Add proxy support to the `fetch` defined by node when in a remote [vscode#228697](https://github.com/microsoft/vscode/issues/228697) @chrmarti
- [ ] :runner: Explore GPU rendering of the code editor [vscode#221145](https://github.com/microsoft/vscode/issues/221145) @tyriar @hediet
- [ ] :runner: Review REPL/IW Accessibility [vscode#209140](https://github.com/microsoft/vscode/issues/209140) @amunger
- [ ] :runner: Support core actions (type/cut/paste/delete/undo/redo) for multi cursors (<kbd>cmd</kbd>+<kbd>d</kbd>) across cells [vscode#141673](https://github.com/microsoft/vscode/issues/141673) @Yoyokrazy
- [ ] :runner: Clean up and review usage of notebook context menu (telemetry + proposal) [vscode#219240](https://github.com/microsoft/vscode/issues/219240) @Yoyokrazy
- [ ] Exploration on how to improve the diff algorithm [vscode#227928](https://github.com/microsoft/vscode/issues/227928) @DonJayamanne
- [ ] :muscle: Finalize attributable test coverage API [vscode#212196](https://github.com/microsoft/vscode/issues/212196) @connor4312
- [ ] :muscle: Finalize Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [ ] :muscle: Find in output [vscode#225417](https://github.com/microsoft/vscode/issues/225417) @meganrogge
- [ ] :muscle: Explore supporting reverse search in tree find to remove filter widget [vscode#227009](https://github.com/microsoft/vscode/issues/227009) @meganrogge
- [ ] :runner: API to expose the shell's actual environment to extensions [vscode#227467](https://github.com/microsoft/vscode/issues/227467) @anthonykim1
- [ ] :runner: :muscle: Add support for terminal suggest in zsh/bash [vscode#226562](https://github.com/microsoft/vscode/issues/226562) @meganrogge
- [ ] VSCode freezing when adding folder to workspace while working on remote Linux machine [vscode-remote-release#10168](https://github.com/microsoft/vscode-remote-release/issues/10168) @joshspicer
- [ ] :runner: Catalog configurations for remote testing [vscode-remote-release#10248](https://github.com/microsoft/vscode-remote-release/issues/10248) @joshspicer
- [ ] Audit error handling [vscode-remote-release#10249](https://github.com/microsoft/vscode-remote-release/issues/10249) @joshspicer
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00 @hediet
- [ ] :runner: Change the global `fetch` available in local extension hosts to be the one from Electron [vscode#228696](https://github.com/microsoft/vscode/issues/228696) @chrmarti
- [ ] :runner: Add proxy support to the `fetch` defined by node when in a remote [vscode#228697](https://github.com/microsoft/vscode/issues/228697) @chrmarti

**Comment by iwangbowen** [comment]
Waiting for more features

**Comment by hickford** [comment]
Any time to look at bug fix https://github.com/microsoft/vscode/pull/216085 please?

**Comment by alphachart** [comment]
locked

**Comment by fisforfaheem** [comment]
Kindly Add proper changelogs, with each release inside the vscode as well, also for isniders as well

**Comment by niceEli** [comment]
would be good if #519 was 🏃 rn

**Comment by Landscaping69** [comment]
https://github.com/microsoft/vscode-jupyter/issues/14422

**Comment by Amirbakhtiaro** [comment]
> This plan captures our work in **October**. This is a 4-week iteration. We will ship in **early November**. With GH Universe right around the corner, we're working on several Copilot improvements. Thus, this month's core plan is more light than usual.
> 
> ## Endgame
> * **October 21, 2024**: Endgame begins
> * **October 25, 2024**: Endgame done
> 
> The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22October+2024%22).
> 
> ## Plan Items
> Below is a summary of the top level plan items.
> 
> Legend of annotations:
> 
> Mark	Description
> 🏃	work in progress
> ✋	blocked task
> 💪	stretch goal for this iteration
> 🔴	missing issue reference
> 🔵	more investigation required to remove uncertainty
> ⚫	under discussion within the team
> ⬛	a large work item, larger than one iteration
> ### Accessibility
> * [ ]  🏃 Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22October+2024%22) [@meganrogge](https://github.com/meganrogge) **team**
> 
> ### Code Editor
> * [ ]  🏃 Make `EditContext` the default input strategy [vscode#228093](https://github.com/microsoft/vscode/issues/228093) [@aiday-mar](https://github.com/aiday-mar) [@hediet](https://github.com/hediet)
> 
> ### Notebook Editor
> #### Jupyter Notebooks
> * [x]  Update Jupyterlab npm package (supporting newer Jupyter server versions) [vscode-jupyter#14422](https://github.com/microsoft/vscode-jupyter/issues/14422) [@DonJayamanne](https://github.com/DonJayamanne)
> 
> ### Languages
> #### Python
> * [ ]  🏃 Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22October+2024%22) [@karthiknadig](https://github.com/karthiknadig) **team**
> 
> ### Authentication
> * [x]  Introduce method to add additional account when switching preferences [vscode#229496](https://github.com/microsoft/vscode/issues/229496) [@TylerLeonhardt](https://github.com/TylerLeonhardt)
> 
> ### Source Control
> * [ ]  Add SCM accessibility help dialog [vscode#203577](https://github.com/microsoft/vscode/issues/203577) [@lszomoru](https://github.com/lszomoru) [@meganrogge](https://github.com/meganrogge)
> 
> ### API
> * [ ]  🏃 API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2024%22+label%3A%22api-proposal%22) [@jrieken](https://github.com/jrieken) [@mjbvz](https://github.com/mjbvz)[ ]  🏃 API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2024%22+label%3A%22api-finalization%22) [@jrieken](https://github.com/jrieken) [@mjbvz](https://github.com/mjbvz)
> 
> ### Engineering
> * [ ]  Support building the monaco-editor AMD variant from new sources [@hediet](https://github.com/hediet) [@alexdima](https://github.com/alexdima)
> 
> ### Electron
> * [ ]  🏃 Electron 32 update [vscode#218245](https://github.com/microsoft/vscode/pull/218245) [@deepak1556](https://github.com/deepak1556)[x]  Electron upgrades duty [@deepak1556](https://github.com/deepak1556)[x]  Crash when searching in extension preview editor [vscode#177046](https://github.com/microsoft/vscode/issues/177046) [@rzhao271](https://github.com/rzhao271)[ ]  🏃 Align Electron fetch with Node.js fetch [electron#43715](https://github.com/electron/electron/issues/43715), [electron#43712](https://github.com/electron/electron/issues/43712) [@deepak1556](https://github.com/deepak1556)[ ]  🏃 Explore enabling COI on desktop, context for current block [vscode#186614](https://github.com/microsoft/vscode/issues/186614) [@deepak1556](https://github.com/deepak1556)
> 
> ### Documentation
> * [x]  Implement redesign of the Docs landing page [vscode-docs#7544](https://github.com/microsoft/vscode-docs/issues/7544) [@ntrogh](https://github.com/ntrogh)[ ]  🏃 Address feedback from customer interviews on VS Code tutorial [vscode-internalbacklog#5127](https://github.com/microsoft/vscode-internalbacklog/issues/5127) [@ntrogh](https://github.com/ntrogh)
> 
> ### Deferred
> * [ ]  🏃 Add proxy support to the `fetch` defined by node when in a remote [vscode#228697](https://github.com/microsoft/vscode/issues/228697) [@chrmarti](https://github.com/chrmarti)[ ]  🏃 Explore GPU rendering of the code editor [vscode#221145](https://github.com/microsoft/vscode/issues/221145) [@Tyriar](https://github.com/Tyriar) [@hediet](https://github.com/hediet)[ ]  🏃 Review REPL/IW Accessibility [vscode#209140](https://github.com/microsoft/vscode/issues/209140) [@amunger](https://github.com/amunger)[ ]  🏃 Support core actions (type/cut/paste/delete/undo/redo) for multi cursors (cmd+d) across cells [vscode#141673](https://github.com/microsoft/vscode/issues/141673) [@Yoyokrazy](https://github.com/Yoyokrazy)[ ]  🏃 Clean up and review usage of notebook context menu (telemetry + proposal) [vscode#219240](https://github.com/microsoft/vscode/issues/219240) [@Yoyokrazy](https://github.com/Yoyokrazy)[ ]  Exploration on how to improve the diff algorithm [vscode#227928](https://github.com/microsoft/vscode/issues/227928) [@DonJayamanne](https://github.com/DonJayamanne)[ ]  💪 Finalize attributable test coverage API [vscode#212196](https://github.com/microsoft/vscode/issues/212196) [@connor4312](https://github.com/connor4312)[ ]  💪 Finalize Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) [@connor4312](https://github.com/connor4312)[ ]  💪 Find in output [vscode#225417](https://github.com/microsoft/vscode/issues/225417) [@meganrogge](https://github.com/meganrogge)[ ]  💪 Explore supporting reverse search in tree find to remove filter widget [vscode#227009](https://github.com/microsoft/vscode/issues/227009) [@meganrogge](https://github.com/meganrogge)[ ]  🏃 API to expose the shell's actual environment to extensions [vscode#227467](https://github.com/microsoft/vscode/issues/227467) [@anthonykim1](https://github.com/anthonykim1)[ ]  🏃 💪 Add support for terminal suggest in zsh/bash [vscode#226562](https://github.com/microsoft/vscode/issues/226562) [@meganrogge](https://github.com/meganrogge)[ ]  VSCode freezing when adding folder to workspace while working on remote Linux machine [vscode-remote-release#10168](https://github.com/microsoft/vscode-remote-release/issues/10168) [@joshspicer](https://github.com/joshspicer)[ ]  🏃 Catalog configurations for remote testing [vscode-remote-release#10248](https://github.com/microsoft/vscode-remote-release/issues/10248) [@joshspicer](https://github.com/joshspicer)[ ]  Audit error handling [vscode-remote-release#10249](https://github.com/microsoft/vscode-remote-release/issues/10249) [@joshspicer](https://github.com/joshspicer)[ ]  🏃 Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) [@alexr00](https://github.com/alexr00) [@hediet](https://github.com/hediet)[ ]  🏃 Change the global `fetch` available in local extension hosts to be the one from Electron [vscode#228696](https://github.com/microsoft/vscode/issues/228696) [@chrmarti](https://github.com/chrmarti)[ ]  🏃 Add proxy support to the `fetch` defined by node when in a remote [vscode#228697](https://github.com/microsoft/vscode/issues/228697) [@chrmarti](https://github.com/chrmarti)

https://github.com/microsoft/vscode/issues/230653#issue-2568674950

**Comment by gburkhow** [comment]
https://github.com/microsoft/vscode/issues/230653

**Comment by niceEli** [comment]
ah so you didnt finish #519 instead adding copilot builtin to the editor, i am a copilot subscriber through my educational institution and that means your getting money because of me, this is unacceptable to make people who are disabled not be able to use your code editor, not everyone can read the fancy dynamic spaced calibri fonts, some need monospace. cmon its been 9 years and you still dont have this basic accessibility feature.
