### ISSUE TITLE
Iteration Plan for November 2024 [DRAFT]

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#232927]
This plan captures our work in **November**. This is a 6-week iteration in order to accommodate the Thanksgiving Holiday in the United States. We will ship in **first half of December**. The rest of December will be dedicated to our annual house keeping. 

## Endgame
- **Dec 02, 2024**: Endgame begins
- **Dec 06, 2024**: Endgame done

The endgame details for this iteration are tracked [here](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aendgame-plan+milestone%3A%22November+2024%22).

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| :runner:             | work in progress                                  |
| :hand:               | blocked task                                      |
| :muscle:             | stretch goal for this iteration                   |
| :red_circle:         | missing issue reference                           |
| :large_blue_circle:  | more investigation required to remove uncertainty |
| :black_circle:       | under discussion within the team                  |
| :black_large_square: | a large work item, larger than one iteration      |

### Accessibility
- [ ] :runner: Accessibility issues, see [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22November+2024%22) @meganrogge **team**
- [ ] :runner: Interactive window accessibility issues for SR users [vscode#209140](https://github.com/microsoft/vscode/issues/209140) @amunger

### Code Editor
- [ ] :runner: Explore GPU rendering of the code editor [vscode#221145](https://github.com/microsoft/vscode/issues/221145) @tyriar @hediet
- [ ] :runner: Make `EditContext` the default input strategy [vscode#228093](https://github.com/microsoft/vscode/issues/228093) @aiday-mar @hediet

### Notebook Editor
- [ ] Multi cursor across cells: support selection highlights and select all find occurrences [vscode#232866](https://github.com/microsoft/vscode/issues/232866) @Yoyokrazy
- [ ] Support run cells in section from markdown cells [vscode#232865](https://github.com/microsoft/vscode/issues/232865) @Yoyokrazy
- [ ] Show last executed time on cell status bar [vscode#168792](https://github.com/microsoft/vscode/issues/168792) @Yoyokrazy
- [ ] Improve notebook model diff algorithm (cell id, execution count, etc) [vscode#227928](https://github.com/microsoft/vscode/issues/227928) @DonJayamanne

#### Jupyter Notebooks
- [ ] Improve Context key for execution/debug/run-by-line actions [vscode-jupyter#16189](https://github.com/microsoft/vscode-jupyter/issues/16189) @Yoyokrazy
- [ ] :red_circle: :muscle: Explore kernel persistence for Remote environments @DonJayamanne

#### Python
- [ ] :runner: Contributions to the Python extension, see [plan](https://github.com/microsoft/vscode-python/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22November+2024%22) @karthiknadig **team**

#### TypeScript
- [ ] Send Custom Requests To TypeScript Language Service Plugins [vscode#218275](https://github.com/microsoft/vscode/issues/218275) @mjbvz

### Authentication
- [ ] Adopt Broker flow in Microsoft Auth provider via MSAL-node [vscode#229431](https://github.com/microsoft/vscode/issues/229431) @TylerLeonhardt

### Source Control
- [ ] Add SCM accessibility help dialog [vscode#203577](https://github.com/microsoft/vscode/issues/203577) @lszomoru @meganrogge

### Testing
- [ ] Finalize attributable test coverage API [vscode#212196](https://github.com/microsoft/vscode/issues/212196) @connor4312
- [ ] :red_circle: Improve how failed tests are being displayed @connor4312 
- [ ] Improve continuous run UI [vscode#210848](https://github.com/microsoft/vscode/issues/210848) @connor4312

### Debug
- [ ] Find in output [vscode#225417](https://github.com/microsoft/vscode/issues/225417) @meganrogge

### Terminal
- [ ] :runner: Add support for terminal suggest in zsh/bash [vscode#226562](https://github.com/microsoft/vscode/issues/226562) @meganrogge
- [ ] :runner: API to expose the shell's actual environment to extensions [vscode#227467](https://github.com/microsoft/vscode/issues/227467) @anthonykim1

### API
- [ ] :runner: API proposals: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2024%22+label%3A%22api-proposal%22) @jrieken @mjbvz
- [ ] :runner: API finalization: [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2024%22+label%3A%22api-finalization%22) @jrieken @mjbvz

### Extensions
- [ ] Setting to control what extensions/publishers can be installed [vscode#84756](https://github.com/microsoft/vscode/issues/84756) @sandy081 @joaomoreno @isidorn

#### SSH Extension
- [ ] SSH connection issues @joshspicer
    - [ ] :red_circle: SSH agent forwarding does work for second window or reconnection
    - [ ] :red_circle: Can't establish connection with `ProxyCommand`
- [ ] Audit error handling for SSH connections [vscode#10249](https://github.com/microsoft/vscode-remote-release/issues/10249 ) @joshspicer

### Engineering
- [ ] :red_circle: Support building the monaco-editor AMD variant from new sources @hediet @alexdima

### Electron
- [ ] :runner: Electron 32 update [vscode#218245](https://github.com/microsoft/vscode/pull/218245) @deepak1556
- [ ] :runner: Align Electron fetch with Node.js fetch [electron#43715](https://github.com/electron/electron/issues/43715), [electron#43712](https://github.com/electron/electron/issues/43712) @deepak1556
- [ ] :runner: Explore enabling COI on desktop, context for current block [vscode#186614](https://github.com/microsoft/vscode/issues/186614) @deepak1556

### Documentation
- [ ] :runner: Address feedback from customer interviews on VS Code tutorial [vscode-internalbacklog#5127](https://github.com/microsoft/vscode-internalbacklog/issues/5127) @ntrogh
- [ ] Document Tools API [vscode-docs#7725](https://github.com/microsoft/vscode-docs/issues/7725) @isidorn @roblourens @ntrogh 

---
### Deferred
- [ ] :runner: Add proxy support to the `fetch` defined by node when in a remote [vscode#228697](https://github.com/microsoft/vscode/issues/228697) @chrmarti
- [ ] :muscle: Finalize Related code [vscode#126932](https://github.com/microsoft/vscode/issues/126932) @connor4312
- [ ] :muscle: Explore supporting reverse search in tree find to remove filter widget [vscode#227009](https://github.com/microsoft/vscode/issues/227009) @meganrogge
- [ ] VSCode freezing when adding folder to workspace while working on remote Linux machine [vscode-remote-release#10168](https://github.com/microsoft/vscode-remote-release/issues/10168) @joshspicer
- [ ] :runner: Investigation: Use tree-sitter for grammar colorization [vscode#210475](https://github.com/microsoft/vscode/issues/210475) @alexr00 @hediet
- [ ] :runner: Change the global `fetch` available in local extension hosts to be the one from Electron [vscode#228696](https://github.com/microsoft/vscode/issues/228696) @chrmarti

**Comment by iwangbowen** [comment]
Always looking forward to new features😍😍😍

**Comment by GitMensch** [comment]
Will #233188 be included?

**Comment by rszwajko** [comment]
Is there any schedule for finalizing API in proposal state? I'm interested in using `contribDiffEditorGutterToolBarMenus` API. [The Git Stage diff view](https://github.com/microsoft/vscode/issues/206808) uses it successfully since March so it seems ready.

**Comment by jlynchMicron** [comment]
This PR (226662) has already been pulled to main, but I don't see it in the current plan.  Any chance it can be included in this release?  It fixes MSFT authentication issues behind corporate proxies.

**Comment by fisforfaheem** [comment]
when will the update be released its been 1+ months now

**Comment by ladyrick** [comment]
looking forward to new release.

**Comment by NateRadebaugh** [comment]
@fisforfaheem the November iteration releases in December.... see #234966

**Comment by iwangbowen** [comment]
The release date has changed to 12/11
