### ISSUE TITLE
Improve linkification in notebook outputs

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#236113]
We currently have a set of issue for linkification for notebook outputs (e.g., error outputs). Here a couple of failing scenarios:

- [ ] broken when path contains space https://github.com/microsoft/vscode/issues/226882
- [ ] slash is linkified https://github.com/microsoft/vscode/issues/208935
- [ ] links in nested folders https://github.com/microsoft/vscode/issues/185205
- [ ] not rendered properly on Windows https://github.com/microsoft/vscode/issues/177854 

We might need to revisit the linkification code and one alternative is xterm.
