### ISSUE TITLE
April Iteration Plan

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#24111]
This plan captures the focus of our work during the April iteration. It's a 4 week iteration. We will ship **early May**.

The last few iterations were exciting for us. We shipped an abundance of features, and every day we see more new users. With more users comes more activity in our repo:  more PRs, more issues, more discussions. It's a great. Thank you!

We have been trying hard to keep up with everything. But, we feel our issue situation is not in the best possible shape. So, for this iteration, we'll slightly shift our focus: We'll focus more on grooming our issues, fixing bugs, and improving engineering than we'll focus on new features. 

We'll still continue to work on items that have been in flight. For example, last month, we started the exploration to support multi-root workspaces (#396). We'll continue the design and planning work this iteration. BTW, this is a big one and it will take us several iterations to ship it all.

No worries, our release notes will still have a few entries :smile:.

## Endgame
- *April, 25th*: Code freeze for the endgame (_shifted it by one day since we have less new features to test_)
- *April, 28th*: Endgame done

The endgame details for this iteration are tracked in #25250.

## Plan Items

Below is a summary of the top level plan items.

Legend for annotations:

| Mark  | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Progress on in-flight items
- [x] :running_man: Investigate into multi-root, multi-folder workspaces #396 @bpasero @tyriar **all**
- [x] :running_man: Additional theming options in the workbench #3112 @aeschli @bpasero **all**
- [x] :running_man: Debug - Complete support for column break points https://github.com/Microsoft/vscode-chrome-debug-core/issues/144 @roblourens
- [x] :running_man: SCM Provider API - react to feedback from Adopters, finalize the API #15894 @joaomoreno
- [x] :running_man: Typescript - investigate into TS language server extensions, validate with tslint as a server extension Microsoft/vscode-tslint#171 @mjbvz, @egamma
- [ ] :running_man: PHP - language server contributions https://github.com/felixfbecker/php-language-server/issues/323 @mousetraps
- [x] 🏃 Explore emmet 2.0 support #21943 @ramya-rao-a
- [x] Keybindings customization - improved search, duplicate detection #23400 #23368 @sandy081

### Issues we plan to fix
- [Bugs planned for April](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Abug+milestone%3A%22April+2017%22)
- :running_man: Address [accessibility issues](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20label%3Aaccessibility%20usability%20in%3Atitle%20OR%20accessibility%20in%3Atitle%20%20-label%3Aupstream%20) 

### Engineering items
- [x] :running_man: Issue categorization, review, assignment #24059 **all**
- Testing
  - [x] [Test Tours](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+Test+Tour+label%3Atestplan-item+milestone%3A%22April+2017%22) to validate with VS Code with popular JS frameworks **all**
  - [x] Test running - support to run tests inside the electron renderer process @jrieken
  - [x] :running_man: Explore the use of [Spectron](https://electron.atom.io/spectron/) for automated UI testing of VS Code @michelkaporin
- [x] :running_man: Update to Electron 1.6 #23159 @bpasero
- Performance
  - [x] 🏃 Debug node stepping performance #23743 @isidorn
  - [x]  Investigate into the negative Windows startup time trend @jrieken @ramya-rao-a @seanmcbreen

### Deferred
- Install/update- Investigate into a rolling install-update scheme or to suspend an update without roll back @joaomoreno @bpasero

**Comment by csholmq** [comment]
Missing reference on eg the negative windows startup time.

**Comment by egamma** [comment]
@csholmq fixed thanks.

**Comment by octref** [comment]
@mjbvz @egamma Can I get a ping if you create an issue for the TS LS extension?

**Comment by Paviluf** [comment]
Do you think this one can be fixed for april release ?
https://github.com/Microsoft/vscode/issues/24309
Thanks !

**Comment by sathish25071992** [comment]
Hi,
Is the openSuse rpm repo is updated? If I refresh it is not updating. saying vs code is already up-to-date

**Comment by egamma** [comment]
closing April update has been published.

**Comment by Tyriar** [comment]
@sathish25071992 yes, unfortunately there is a bit of a delay with our signing system this release. You can wait 1-2 days until it's done or install the rpm from the site and ignore the update available message.

**Comment by sathish25071992** [comment]
@Tyriar thank you for the response. No problem. I used rpm package for the update.
