### ISSUE TITLE
May Iteration Plan

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#26068]
This plan captures the focus of our work during the May iteration. It's a 5 week iteration. We will ship **early June**.

## Endgame
- *May, 29th*: Code freeze for the endgame
- *June 2nd*: Endgame done

The endgame details for this iteration are tracked in #27415.

## Plan Items

Below is a summary of the top level plan items.

Legend for annotations:

| Mark  | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Workbench
- [x] Design for multi root workspaces, multi folder, validate with user testing #396 @bpasero @tyriar 
- [x] Investigate restructuring Welcome page into Learn and Configure sections #22097 @chrmarti
- [x] Improve presentation of documentation in intellisense #18582 #25812 @ramya-rao-a
- [x] Emmet 2.0 support #21943 @ramya-rao-a
- [x] Improve theming support for Welcome page #25798 @chrmarti
- [x] Remember scroll position when switching between webviews #22995 @mjbvz
- [x] Add command to install additional SCM provider extensions #25696 @isidorn @waderyan
- [x] React to feedback for workbench theming [new colors](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_13.md#theming)@bpasero @aeschli 

### Editor
- [x] Find widget improvements #2657 #6158 #26498 @rebornix
- [x] Support to configure mouse/keyboard gesture for adding multiple cursors @alexandrudima 
- [x] Improve the snippet infrastructure (enable emmet 2.0, support multi cursor) @jrieken

### Monaco Editor
- [ ] :running: Improve [editor accessibility focusing on Edge+Narrator](https://github.com/Microsoft/monaco-editor/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3Aaccessibility%20milestone%3A%22May%202017%22)  #26730 @alexandrudima 

### Install/Update
- [x] 64 bits windows install #507 @joaomoreno
  *update* for April we will only make a zip install available, full install update is planned for June
- [x] Investigate improving update experience. (See also, #24823 too many update prompts for users) 26199 @joaomoreno, @isidorn 

### Integrated Terminal
- [ ] :runner: :muscle: Support selecting and copy more than just the visible text in a terminal #9958 @tyriar 

### Tasks
- [x] Finalize and publish task provider API #23435 @dbaeumer
- [x] Support to associate problem matchers with contributed tasks #25518 @dbaeumer
- [x] Contribute tasks for scripts in the `package.json` (in a bundled npm extension) #27447 @egamma

##### JavaScript/TypeScript
  - [x] Finish support for TS server plugins #25740 @mjbvz
  - [x] Improve TS editing experience #25842 @mjbvz
  - [x] Contribute tasks for building and watching TypeScript #26079 @mjbvz
  - [x] Initial preparations for adopting TS 2.4 in June #26080 @mjbvz 

##### Markdown
  - [x] Support quick outline for markdown #25574 @mjbvz

### Debug
- [x] Allow `remoteRoot` also for node "Launch" action #11681 @weinand
- [x] Explore - SSH based remote debugging (e.g. for Azure App Services, Containers) #26205 @weinand
- [x] Honor the optional `endLine` and `endColumn` attributes of `StackFrame` and `Breakpoint` #8851 @isidorn
- [x] Improve stepping performance #25605 @isidorn
- [x] Support to copy the entire text of the debug console #2163 @isidorn
- [x] Investigate improving the debug toolbar placement #2513 @isidorn

### Extensions API
- [x] Support to contribute a tree section to the explorer #26948 @sandy081 
- [x] Allow extensions to use theme colors #26974 @aeschli

### Extension Contributions
- [ ] :runner: Round up PHP language server PR https://github.com/felixfbecker/php-language-server/pull/357 @roblourens
- [x] Preview of a VS Code extension that bundles the tslint [typeScript server plugin](https://github.com/angelozerr/tslint-language-service) angelozerr/tslint-language-service#32 @egamma
- [x] VIM improvements https://github.com/VSCodeVim/Vim/issues/1706 @rebornix 

### Engineering Items

- [ ] :runner: Hire new team member #27092 @kieferrm
- [ ] Open [accessibility Issues](https://github.com/microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aissue%20label%3Aaccessibility%20usability%20in%3Atitle%20OR%20accessibility%20in%3Atitle%20-label%3Aupstream%20is%3Aopen%20milestone%3A%22May%202017%22) **all**
- [x] Automate the Smoke test using Spectron #25291 @michelkaporin

##### Startup performance
  - [x] Improve startup performance using cached data, V8 snapshots #25229 @jrieken

##### Issue management
  - [x] Automate identifying, labeling, and closing stale issues #26223 @chrmarti
  - [x] Make it easy to verify that an issue is from an extension by supporting to disable all extensions in the extensions viewlet @sandy081

##### Build
  - [x] Can we use the TypeScript [`--noEmitHelper`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) option to reduce the compiled output size  and replace our custom solution #25612 @jrieken
  - [x] Review Multi-arch build configurations (armhf/arm64) for Travis CI #24943 @joaomoreno

### Documentation

Provide recipes for using VS Code with particular technologies
- [x] Debugging Docker with Source maps [See repository.](https://github.com/weinand/vscode-recipes/tree/master/Docker-TypeScript) @weinand 
- [x] Developing the MERN Starter in VS Code [See repository.](https://github.com/weinand/vscode-recipes/tree/master/MERN-Starter) @weinand 

----

### Deferred
- Make v2 the default and provide parity with 1.0 @dbaeumer
---
- Typescript - Investigate improving the development support for TS server plugins #26235 @mjbvz
- Improve extension API to better support extensions that provided synching of the vs code setup #14444 @sandy081
 - Improve `checkJS` experience with React #26081 @mjbvz
---
- Editor - Publish a new version of the monaco editor @alexandrudima 
- Editor - Investigate aligning column selection with other editors @alexandrudima
- Install - 64 bits windows install #507 @joaomoreno
- Debug - "Live Edit" [Node.js] #8127 #6930 @weinand
- Go https://github.com/Microsoft/vscode-go/issues/959 @ramya-rao-a
- Enable electron crash reporter for all processes #21944 @ramya-rao-a
- Continue investigation into markdown extensions #22916 @mjbvz

**Comment by shanalikhan** [comment]
#14444  Issue Included on May Iteration Plan !
Thanks Team!

Code Settings Sync is Going to Become Much Better ! 😄

**Comment by egamma** [comment]
Closing - 1.13. has been shipped
