### ISSUE TITLE
Iteration Plan for June 2017 - DRAFT

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#28387]
This plan captures our work in June. This is a **4 week** iteration. We will ship **early July**. The main focus of this iteration is to continue pushing on the big rock item #396 "Multi-folder workspaces".

## Endgame
- *June 26th*: Code freeze for the endgame
- *June 30th*: Endgame done

The endgame details for this iteration are tracked in **TBD**

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Workbench
- [ ] Multi-folder workspaces #28344 (feature request #396) @bpasero @tyriar **@ team**
- [ ] :red_circle: Improve window switching on Windows @bpasero
- [ ] :red_circle: Finish emmet 2.0 support @ramya-rao-a
- [ ] :red_circle: Finish Tasks v2.0 improvements @dbaeumer
- [ ] :red_circle: Provide out-of-the-box color picker @michelkaporin
- [ ] :large_blue_circle: Overflow design for custom sections in the explorer @sandy081

### Editor
- [ ] :red_circle: Improve indentation of lines @rebornix

### Monaco Editor
- [ ] :red_circle: New release of the Monaco Editor @alexandrudima

### Accessibility
- [ ] Improve accessibility of the Monaco editor [See query.](https://github.com/Microsoft/monaco-editor/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility) @alexandrudima
- [ ] Improve accessibility of the diff editor #17263 @alexandrudima
- [ ] Improve accessibility of the Tree/List widget #27900 @isidorn

### Debug
- [ ] :red_circle: Switch to the inspector protocol for extension debugging @bpasero @weinand
- [ ] Autodetect debug protocol used by a node process #25036 @roblourens
- [ ] :red_circle: Translation support for node debug @weinand
- [ ] :red_circle: :muscle: Show loaded scripts in a custom explorer section @weinand

### Install/update
- [ ] :large_blue_circle: Provide Windows 64-bit install (and migration from 32-bit) #507 @joaomoreno
- [ ] Improve update experience on Windows #26199 @joaomoreno

### Integrated Terminal
- [ ] Support selecting and copy more than just the visible text in a terminal #9958 @tyriar 

##### JavaScript/TypeScript
 - [ ] :red_circle: Bundle [TypeScript 2.4](https://github.com/Microsoft/TypeScript/wiki/Roadmap#24) @mjbvz
 - [ ] :red_circle: Support TS 2.4 refactorings @mjbvz
 - [ ] Improve development support for TS server plugins #26235 @mjbvz

##### API
- [ ] :red_circle: Tasks: Finish Task Provider API @dbaeumer
- [ ] :red_circle: Debug: support a `debug session terminated` event @weinand
- [x] :red_circle: Custom sections: support conditional visibility based on a context (when clause) @sandy081
- [ ] :red_circle: :muscle: Support custom sections in other viewlets @sandy081
- [ ] :red_circle: `DocumentContentProvider` support to update document content @jrieken

##### Extension management
- [ ] :red_circle: Add sections for installed and recommended sections to the extensions viewlet @sandy081

### Extension Contributions
- [ ] Go https://github.com/Microsoft/vscode-go/issues/959 @ramya-rao-a
- [ ] :red_circle: Polish PHP language server @roblourens
- [ ] :red_circle: Polish Git extension @rebornix
- [ ] :red_circle: Polish Github extension @chrmarti

### Engineering items
- [ ] :red_circle: Investigate using snapshots for `workbench.main.js` to speed up startup @jrieken
- [ ] :red_circle: Adopt Electron `1.7.2` @bpasero
- [ ] :red_circle: Adopt TS 2.4 @mjbvz
- [ ] :red_circle: Investigate language packs for translations @dbaumer
- [ ] Avoid process leakage of the extension host #15962 @alexandrudima
- [ ] :red_circle: Build definition for smoke test @michelkaporin
- [ ] :red_circle: Smoke test build status indicator @michelkaporin
- [ ] Improve issue tracking with automation #26223 @chrmarti
- [ ] :muscle: Enable electron crash reporter for all processes #21944 @ramya-rao-a

### Documentation
- [ ] :red_circle: Add recipe for Angular debugging @weinand

----

### Deferred
None.

**Comment by obrejla** [comment]
Hi, link to this issue is missing in wiki. Thanks!

**Comment by Tyriar** [comment]
@obrejla fixed :smiley:

**Comment by gulshan** [comment]
I think this issue should be included in June milestone. :)
