### ISSUE TITLE
Iteration Plan for July 2017

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#30209]
This plan captures our work in July. This is a 5 week iteration. We will ship early August. The main focus remains the same as last iteration's: We continue pushing on #396 "Multi-folder workspaces".

In July and August our team will operate with slightly reduced capacity. Being on the northern hemisphere means summer is upon us. At any given time, a few of us will be busy recharging with friends and families. If you mention somebody in an issue and you don't hear anything for a couple of days, just picture them hanging out on the beach :swimming_woman: :swimming_man: :beach_umbrella:

## Endgame
- *July26nd*: Code freeze for the Zurich endgame
- *July 31st*: Code freeze for the Redmond & Zurich endgame
- *August 4th*: Endgame done

The endgame details for this iteration are tracked in #31333

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | needs more discussion |
| :red_circle: | missing issue reference |

### Workbench
- [ ] :runner: Multi-folder workspaces #28344 (feature request #396) @bpasero @tyriar **@** **team**
- [x] Improve usability of text search in multi-folder workspaces #29977 #27226 @roblourens
- [x] Allow users to manage custom sections in the explorer (reorder, show/hide) #30120 @sandy081
- [x] Polish Tasks v2.0 [See query.](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Adbaeumer+milestone%3A%22July+2017%22+label%3Atasks) @dbaeumer
- [x] Provide color picker #28587 @michelkaporin @joaomoreno

### Editor
- [x] Polish indentation of lines #28658 @rebornix
- [x] Support for choices in snippets @jrieken
- [x] Improve handling of large files (memory usage, tune max size heuristic) #30180 @alexandrudima
- [x] Make diffs prettier #30087 #23636 #11657 @alexandrudima

### Accessibility
- [ ] :runner: Improve support for assistive technologies in the integrated terminal #8339 @tyriar

### Debug
- [x] Make debug launching multi-folder-workspace aware #29245 @isidorn @weinand 
- [x] Make Debug API multi-folder-workspace aware #31202 @weinand @isidorn 
- [x] Expand API for extensions (`sessionStarted`, `sessionTerminated`, `sendCustomRequest`, `handleCustomEvent`) #30338 @weinand
- [x] Show loaded scripts in a custom explorer section #28521 @weinand
- [x] Support to contribute sections to the debug viewlet @sandy081

### Install/update
- [x] Help users to switch from the Windows 32bit install to the Windows 64-bit install @joaomoreno
- [x] Improve proxy support, support proxies requiring authentication #22214 @joaomoreno

### SCM
- [ ] :muscle: :runner: :red_circle: Support for multiple repositories in a workspace @joaomoreno
- [x] Revive creating a branch on checkout from status bar #21439 @joaomoreno 

### Integrated Terminal
- [x] Quick pick to navigate to a particular terminal #29879 @lixire

##### Language Server Protocol
- [x] Maintenance, answer questions, clarify protocol as needed @dbaeumer

##### JavaScript/TypeScript
- [x] Support multi-folder workspaces #30414 @mjbvz
- [x] Explore how to support external files supported by TS server plug-ins #30411 @mjbvz
- [x] Explore watch mode for TS build task #29580 @mjbvz

#### ESLint
- [x]  Explore the eslint language server supporting multi-folder workspaces @dbaeumer

##### CSS
- [x] Explore moving Emmet css completion provider into the css LS #29113 @ramya-rao-a 

##### Emmet
- [x] Support custom snippets in new Emmet #29146
- [x] Collaborate on Emmet fixes @ramya-rao-a https://github.com/emmetio/atom-plugin/issues/30, https://github.com/emmetio/atom-plugin/issues/23, https://github.com/Microsoft/vscode/issues/30078, https://github.com/emmetio/abbreviation/pull/3 and https://github.com/emmetio/abbreviation/pull/2, https://github.com/emmetio/html-transform/pull/1
- [x] Increase test coverage for Emmet #8454 @ramya-rao-a
- [x]  Implement remaining 2 emmet actions: Update Image Size (#27977) and Reflect CSS Value (#31298)
- [x] Prepare Emmet extension for translation #29969 @ramya-rao-a

##### API
- [x] Experiment: remote file system #30337 @jrieken

### Engineering items
- [x] Adopt TS 2.4.1 in vscode and team-supported extensions #28643 @mjbvz **@** **team**
- [x] Improve automated support for issue labeling and assignment #26223 @chrmarti
- [x] Startup performance: use V8 snapshots for the VS Code loader #28492 @jrieken 

### Documentation
- [ ] :runner: Recipe using Tasks with webpack, starting, problem matchers (see also #29619) @aefernandes @lixire

### Exploration
- [x] Explore the idea of a task panel @lixire @aefernandes
- [ ] :runner:  Analysis of current test runner extensions (see also #9505) @aefernandes 
- [x] Investigate into adding a secure credential storage API #15414 @chrmarti

## Deferred
- New release of the Monaco Editor https://github.com/Microsoft/monaco-editor/issues/510 @rebornix
- :runner: Adopt Electron `1.7.4` #28582  @tyriar
- :runner: Use inspector protocol for extension debugging Microsoft/vscode-node-debug2#4 @roblourens
- Support commands in the hover #29076 @jrieken
- Enable electron crash reporter for all processes #21944 @ramya-rao-a
- Explore how best to help HTMLHint @ramya-rao-a
- Improve selection drawing #29042 @tyriar
- Improve link detection #30211 @tyriar

**Comment by glen-84** [comment]
> Improve usability of text search in multi-folder workspaces

This might be #29977 (?)

**Comment by PCPrincess** [comment]
Multi-Folder - Color Picker - Tasks Panel =>  Yay!

**Comment by Jeyanthinath** [comment]
It would be great if vscode would support **pycharm style** , task configure and task runner on the top right with run button, 

Suppose user need to run multiple configuration file for same file , he can very well setup and need to go to  command pannel for task running ,ther is no **one click solution**

**Comment by mrmlnc** [comment]
> Explore how best to help HTMLHint

Where I can read solution for this issue? IMHO, HTMLHint is dead two years ago :)

**Comment by ramya-rao-a** [comment]
@mrmlnc That item got deferred. We didnt get time to get to that in July

**Comment by kieferrm** [comment]
Release published.
