### ISSUE TITLE
Improve terminal link detection July plan item

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#30211]
Some improvements for the terminal's link detection:

- [ ] Multi-line links https://github.com/Microsoft/vscode/issues/28746
- [ ] Support folders (could open folder in the explorer) #29499
- [ ] Proper link parser https://github.com/sourcelair/xterm.js/issues/583
  - [ ] Unicode/styled links https://github.com/sourcelair/xterm.js/issues/654
  - [ ] Detecting whether `()` are within links https://github.com/sourcelair/xterm.js/issues/583
  - [ ] Improve hostname/TLD support https://github.com/sourcelair/xterm.js/issues/653, https://github.com/sourcelair/xterm.js/issues/601

**Comment by Tyriar** [comment]
Not going to be able to get to this for July
