### ISSUE TITLE
Multi root: Adopt and Improve Settings editor for Multi root workspaces

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#30955]
Multi root: Adopt and Improve Settings editor for Multi root workspaces

- [x] Allow extensions to define resource and workbench settings #29831
- [x] Indicate workbench settings in folder target as not applicable settings  #29462
- [x] API to read and write configuration value given a resource #31358

**Comment by vvs** [comment]
Please note that e6770cc broke the user settings editing when `EditorConfig` extension is installed.

See #31246

**Comment by sandy081** [comment]
In Multi-root workspaces, workspace settings come from the workspace config file which has other configurations like `id`, `folders`.  Eg:

```
{
	"id": "1499978571481",
	"folders": [
		"file:///.../vscode",
		"file:///.../vscode-docs"
	],
	"settings":{
	    "editor.insertSpaces": false,
	    "files.eol": "\n",
       }
}
```

Hence, Settings editor needed a virtual editor for displaying only settings section of the config file for Workspace Settings. This should also support editing just like in other editors.

![image](https://user-images.githubusercontent.com/10746682/28518312-1196950c-7085-11e7-9f54-5dab76498d4a.png)

To get consistent experience in Settings Editor across, while editing settings in virtual editor (Workspace Settings), content is written directly into the real configuration file on disk. This needs #23413 Auto saving of settings for consistent experience.

**Comment by sandy081** [comment]
Reverted virtual editor support in favour of #31246
