### ISSUE TITLE
Iteration Plan for August 2017

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#32043]
This plan captures our work in August. This is a **4 week** iteration. We will ship **early September**. The main focus remains the same as last iteration's: We continue pushing on #396 "Multi-folder workspaces", this is our roadmap #28344.

As in July, our team will operate with slightly reduced capacity. Being on the Northern Hemisphere means Summer is upon us and so, at any given time, a few of us will be busy recharging with friends and families. If you mention somebody in an issue and you don't hear anything for a couple of days, just picture them hanging out on the beach :beach_umbrella: or skiing in New Zealand :skier:.

## Endgame
- *August 29th*: Code freeze for the endgame
- *Sept 1th*: Endgame done

The endgame details for this iteration are tracked in #33215.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Workbench
Multi-folder workspaces #28344 (feature request #396) @bpasero @tyriar **@** **team**
- [x] migrate hot-exit data (do not prompt to save dirty files)
- [x] migrate UI state (local storage)
- [x] investigate to not require a window reload @bpasero @sandy081 (#32945)
- [x] migrate workspace settings if any @sandy081 (#32947)
- [x] revisit workspace file format @bpasero (#32946)
- [x] support to add a folder to a workspace from the command line @bpasero 

### Editor
- [x] Finish/polish Color Picker #32235 @rebornix @joaomoreno
- [ ] :runner: Refactor the Find widget so that it can be shared across components #32241 @rebornix
- [ ] :muscle: Explore additional column selection gestures #32491 @alexandrudima
- [x] Support for smooth scrolling #25286 @alexandrudima
- [x] Add support for setting the cursor from a Braille display #27216 @alexandrudima 

### Monaco Editor
- [x] New release of the Monaco Editor https://github.com/Microsoft/monaco-editor/issues/510 @rebornix

### Debug
- [x] Extension Debugging using inspector protocol Microsoft/vscode-node-debug2#4 @roblourens @weinand
- [ ] :hand: Investigate WSL support for debuggers [issues](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Adebug+label%3AWSL) @weinand

#### Protocol
- [x] Support `scriptParsed` like event in the protocol [debugadapter-node/108](https://github.com/Microsoft/vscode-debugadapter-node/issues/108) @weinand
- [x] Add a `url` field to `source` objects  [debugadapter-node/125](https://github.com/Microsoft/vscode-debugadapter-node/issues/125) #30996 @weinand
- [x] Include display hints on evaluation results [debugadapter-node/123](https://github.com/Microsoft/vscode-debugadapter-node/issues/123) @weinand
- [x] Support links to source locations in OutputEvents [debugadapter-node/94](https://github.com/Microsoft/vscode-debugadapter-node/issues/94) @weinand

### Terminal
- [x] Polish terminal switcher #32236 @lixire
- [x] Analyze specific needs for terminal accessibility @aefernandes @tyriar
- [x] Native node module to pull Windows process information #31818 @tyriar @lixire

### SCM
- [x] Initial support for multiple repositories in a workspace #31325 @joaomoreno

### Tasks
- [x] Contribute problem matchers for webpack #29619 @lixire

#### Multi-root folder support
- [x] Support multi-root-folder setup for CSS/LESS/SASS #32486 @aeschli
- [x] Support multi-root-folder setup for JSON #32487 @aeschli
- [x] Support multi-root-folder setup for HTML #32489 @aeschli
- [x] Support multi-root folder setup for TypeScript #30414 @mjbvz

##### Language Server Support (vscode-languageclient, vscode-languageserver)
- [x] Multiroot language support for shared servers (server can handle multiple folders) https://github.com/Microsoft/vscode-languageserver-node/issues/232 @dbaeumer
- [x] Multiroot language support for isolated servers (server per folder, scoped settings) https://github.com/Microsoft/vscode-languageserver-node/issues/235 @dbaeumer

#### HTML
- [x] Autoclosing tags support #2246 @aeschli

##### JavaScript/TypeScript
- [x] Adopt TS 2.5 #32109 @mjbvz
- [ ] :hand: Support external files supported by TS server plug-ins #30411 @mjbvz
- [ ] :hand: Explore compile-on save #32108 @mjbvz

### Extensions
- [ ]  :runner: Improve extension recommendations #32422 @ramya-rao-a
- [x] Provide extension authors with extension uninstall information #32765 @joaomoreno  

#### API
- [x] Finalize secure credential storage API #15414 @chrmarti
- [x] Support commands in the hover #29076 @jrieken
- [x] Explore support to open File/Folder dialog from an extension #13807 @jrieken
- [x] SearchProvider` propose API for contributing to Search #29194 @jrieken
- [x] Debug - add support for a debug configuration provider #32086 @weinand

### Extension Contributions
- [x] PHP parser maintenance https://github.com/Microsoft/tolerant-php-parser/issues/12 @roblourens
- [x] TaskProvider for `rake` https://github.com/rubyide/vscode-ruby/issues/192 @rebornix
- [x] Go enable the extension for the multiroot setup https://github.com/Microsoft/vscode-go/issues/1142 @ramya-rao-a
- [x] Multi root support for vscode-eslint @dbaeumer 
- [x] Multi root support for vscode-tslint @egamma

### Engineering Items
- [x] Adopt latest Electron #28582 @tyriar
- [ ] :runner: Add watch-dog which can kill runaway extension host processes #26445 @alexandrudima
- [x] Implement extension host restarting #32768 @alexandrudima 
- [x] When encountering errors, identify the extension they came from #32766 #21302 @jrieken
- [x] Correlate unhandled extension host exceptions with extensions #32490 @alexandrudima

### Documentation
- [x] Recipe for using Tasks with webpack (see #29619) @lixire @aefernandes
- [ ] :runner: Recipe for debugging an electron app in TS https://github.com/Microsoft/vscode-recipes/issues/10 @auchenberg

### Exploration
- [x] Analysis of current test runner extensions @aefernandes

----

### Deferred
- Continue improving  automated issue management #32238 @chrmarti
- Investigate improved support for webpack #32108 @mjbvz
- Extension search improvements (by category, trending) #33035 @sandy081
---
- Explore improve performance of quick open on Windows using  a native module #32237 @chrmarti
- Cleanup `ExtensionContext.workspaceState` when a workspace no longer exists #32461  @dbaeumer

**Comment by ghiscoding** [comment]
@kieferrm did you forget add the milestone or is it intentional? 
I like seeing these plans directly in the milestone :)

BTW, I know that the multi-folder workspaces is currently the biggest focus, however I'm curious to know when should we expect more cleanup/polish of the [minimap](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+minimap+label%3Aeditor-minimap)? I'd really like to see a better integration of the [Git Status](https://github.com/Microsoft/vscode/issues/20934) inside the minimap.

**Comment by Tobyee** [comment]
As polishing terminal, I perfer this way #9353 to support creating new terminal which has more scalability.
Multi-type terminal support is useful while there are different style between terminals, such as git bash and cmd.

**Comment by Tyriar** [comment]
@Tobyee please check out the extension https://marketplace.visualstudio.com/items?itemName=Tyriar.shell-launcher which was built to support this use case.

**Comment by egamma** [comment]
Closing - 1.16 has shipped
