### ISSUE TITLE
Polish Terminal Switcher

### ISSUE THREAD

**Issue by Lixire** [Microsoft/vscode#32236]
This is to track all the issues surrounding the terminal switcher for the August iteration.

- [x] move keyboard focus https://github.com/Microsoft/vscode/issues/32149
- [x] add create new terminal option https://github.com/Microsoft/vscode/issues/31949
- [x] add kill terminal actionbar item to entries https://github.com/Microsoft/vscode/pull/32160 and https://github.com/Microsoft/vscode/pull/32161
- [x] fix tab focus for action items https://github.com/Microsoft/vscode/issues/31835
- [x] fix focus on arrow keys https://github.com/Microsoft/vscode/issues/31836
- [x] fix spacing between actionbar icons
