### ISSUE TITLE
Help Sublime Text users migrate to VS Code

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode#32890]
# Help Sublime Text 3 users migrate to VS Code

We want to provide more welcoming experience for Sublime Text 3 users when they try/open VS Code. In order to do that we want people to help migrate the followings:
- Basic user settings
- Basic project settings
- Snippets
- Keyboard shortcuts

**Future**
Provide recommendations for:
- Themes
- Extensions

## Structure of Sublime Text Settings
Sublime settings are stored as JSON files, in the following locations

- Packages/Default/Preferences.sublime-settings
- Packages/Default/Preferences (<platform>).sublime-settings
- Packages/User/Preferences.sublime-settings
- Project Settings
- Packages/<syntax>/<syntax>.sublime-settings
- Packages/User/<syntax>.sublime-settings
- Buffer Specific Settings

### Locations
OSX: ~/Library/Application Support/Sublime Text 3/Packages/
Windows: C:\Users\<username>\AppData\Roaming\Sublime Text 2\Packages
Ubuntu: ~/.config/sublime-text-3/Packages/

### Mappable Sublime Text settings

**Sublime setting**|**Code setting**
:-----:|:-----:
theme|workbench.colorTheme
scroll_speed|editor.mouseWheelScrollSensitivity
hot_exit|files.hotExit
remember_open_files|window.restoreWindows
open_files_in_new_window|window.openFilesInNewWindow
close_windows_when_empty|window.closeWhenEmpty
show_full_path|"window.title": "${activeEditorFull}${separator}${rootName}",
preview_on_click|workbench.editor.enablePreview
folder_exclude_patterns|files.exclude
file_exclude_patterns|files.exclude
show_tab_close_buttons|workbench.editor.tabCloseButton (off)
save_on_focus_lost|files.autoSave (onFocusChange)
find_selected_text|editor.find.seedSearchStringFromSelection
word_separators|editor.wordSeparators
ensure_newline_at_eof_on_save|files.insertFinalNewline
auto_indent|editor.autoIndent
tab_size|editor.tabSize
use_tab_stops|editor.useTabStops
trim_automatic_white_space|editor.trimAutoWhitespace
detect_indentation|editor.detectIndentation
draw_white_space|editor.renderWhitespace
trim_trailing_white_space_on_save|files.trimTrailingWhitespace
tab_completion|editor.tabCompletion
auto_complete|editor.quickSuggestions
auto_complete_delay|editor.quickSuggestionsDelay
auto_complete_commit_on_tab|True => editor.acceptSuggestionOnEnter = "off"
copy_with_empty_selection|editor.emptySelectionClipboard
find_selected_text|autoFindInSelection
auto_find_in_selection|editor.find.autoFindInSelection
drag_text|editor.dragAndDrop
default_encoding|files.encoding
color_scheme|workbench.colorTheme
font_face|editor.fontFamily
font_size|editor.fontSize
line_numbers|editor.lineNumbers
fade_fold_buttons|"editor.showFoldingControls": "mouseover",
rulers|editor.rulers
caret_style|editor.cursorBlinking
scroll_past_end|editor.scrollBeyondLastLine
word_wrap|editor.wordWrap
wrap_width|editor.wordWrapColumn
indent_subsequent_lines|editor.wrappingIndent='none'
match_brackets|editor.matchBrackets
match_selection|editor.selectionHighlight
draw_indent_guides|editor.renderIndentGuides
remember_full_screen|window.restoreFullscreen

### Non-mapabble settings
**Sublime setting**|**Code setting**
:-----:|:-----:
mouse\_wheel\_switches\_tabs| 
ignored\_packages| 
binary\_file\_patterns| 
default\_dir| 
atomic\_save| 
auto\_match\_enabled| 
result\_file\_regex| 
result\_line\_regex| 
result\_base\_dir| 
build\_env| 
smart\_indent| 
indent\_to\_bracket| 
translate\_tabs\_to\_spaces| 
auto\_complete\_size\_limit| 
auto\_complete\_selector| 
auto\_complete\_triggers| 
auto\_complete\_with\_fields| 
auto\_complete\_cycle| 
auto\_close\_tags| 
shift\_tab\_unindent| 
command\_mode| 
move\_to\_limit\_on\_up\_down| 
is\_widget| 
spell\_check| 

More detailed comparison and mapping can be found in this spreadsheet: https://docs.google.com/spreadsheets/d/1cpUGALUmd-_MPV3-fJfUTjQdCFTFm6RHTEfvMXNY8lw/edit?usp=sharing

## Snippets
We can detect if the user has any Sublime snippets, parse them and convert them to our snippet format. 

More about the snippet format can be read here, http://sublimetext.info/docs/en/extensibility/snippets.html

Prior art: 
- https://github.com/idleberg/sublime-atomizr
- https://github.com/james2doyle/sublime-to-atom-snippets

### MVP as VS Code extension
New "Sublime migrator" extensions add a new command `Migrate from Sublime`, which when executed shows prompts for:
1. Do you want to import your Sublime user settings?
2. Do you want to import your Sublime project settings?
3. Do you want to import your Sublime snippets?

Migration runs in the background and shows a infoMessage when finished.

This command could be linked up on the welcome screen, as the existing key bindings for Sublime.

## Milestones
- [x] Enable migration of user settings
- [x] Enable migration of user+project settings 
- [ ] Enable migration of user snippets
- [ ] Enable migration of keyboard shortcuts
/Kenneth

**Comment by auchenberg** [comment]
@jens1o Atom is in our radar too.

**Comment by auchenberg** [comment]
MVP shipped in marketplace, https://marketplace.visualstudio.com/items?itemName=auchenberg.vscode-sublime-importer#overview

Source: https://github.com/Microsoft/vscode-sublime-importer/issues on

**Comment by auchenberg** [comment]
Closing as this landed in https://github.com/Microsoft/vscode-sublime-keybindings
