### ISSUE TITLE
Task list markdown not showing properly in preview tab

### ISSUE THREAD

**Issue by palashmon** [Microsoft/vscode#33755]
- VSCode Version: Code 1.15.1 (41abd21afdf7424c89319ee7cb0445cc6f376959, 2017-08-16T18:05:38.342Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|1.2.11
tslint|eg2|0.17.0

(1 theme extensions excluded)

---

Steps to Reproduce:

1. Create a `test.md` file.
2. Enter task list markdown like:
```
- [x] Hello World
- [x] list syntax required
- [x] this is a complete item
- [ ] this is an incomplete item
```
3. Open preview pressing <kbd>Ctrl+K</kbd><kbd>V</kbd> hot keys.
4. And we can see the preview for this markdown like this:
![vscode-issue](https://user-images.githubusercontent.com/14850464/30005138-6e27115e-90f9-11e7-93d7-96e0ea74d226.jpg)

5. Which is not same as we see here:
- [x] Hello World
- [x] list syntax required
- [x] this is a complete item
- [ ] this is an incomplete item

Reproduces without extensions: Yes

**Comment by yume-chan** [comment]
Code doesn't support many non-standard Markdown features, but Code can use extensions to extend it.

For checkboxes, you can try [this extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox).

**Comment by mjbvz** [comment]
Yes, we only support common mark markdown out of the box. Try [the extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox) @yume-chan suggested to add checkbox syntax support

**Comment by palashmon** [comment]
Cool. I will look into it.

Thanks!
