### ISSUE TITLE
Iteration Plan for September 2017

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#34160]
This plan captures our work in **September**. This is a 4 week iteration. We will **ship early October**. It's almost getting boring, but the main focus still remains on providing support for multi-root-folder workspaces #396. However, we're getting into the home stretch, and we'll wrap up the work in the core. We'll also work with extension authors on getting their extensions ready for multi-root-folder support.

Other than that, most of the team is back from vacation. We are approaching our full capacity.

## Endgame
- *Sept 26th*: Code freeze for the endgame
- *Sept 29th*: Endgame done

The endgame details for this iteration are tracked in #34939.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress  |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration  |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Workbench
- [x]  Avoid window reload when transitioning to multi-root-folder setup #32945 @sandy081 @bpasero
- [x] Explore using `ripgrep` for file quick-open #24074 @chrmarti
- [x] Add touchbar support for OS X @bpasero
- [x] Improve editor history navigation (go back/go forward) #29027 @bpasero
- [x] `code --wait` returns when the editor tab is closed #24327 @bpasero

### Editor
- [x] Support for user-defined folding regions #12146 @aeschli
- [x] Refine indent based folding for python style languages #3353 @aeschli
- [x] Can't create breakpoint on current line because light bulb is in the way #25174 @jrieken
- [x] Add support for transformations in snippet placeholders #6920 @jrieken
- [x] Allow to specify file encoding per language #19890 @bpasero
- [x] Optimize the drawing of the minimap #34170 @tyriar @alexandrudima

### Debug
- [x] Link origin of messages in the Debug Console #24490 @isidorn
- [x] Improve WSL support in node debugger adapter https://github.com/Microsoft/vscode-node-debug/pull/158 @weinand
- [x] Debt: Adapt debug adapters to new `DebugConfigurationProvider` #33835 @weinand
- [x] Switch to official "loaded scripts" debug API #33834 @weinand

### Terminal
- [x] Optimize terminal drawing performance #34169 @tyriar

### SCM
- [x] Refine UI when using multiple repositories in a workspace #33363 @joaomoreno

### Tasks
- [x] Support Task configuration in the multi-root-folder setup #29454 @dbaeumer
- [x] Multi-root-folder support for gulp, grunt, npm task runner #34228 @dbaeumer @egamma

#### Language Server Support (vscode-languageclient, vscode-languageserver)
- [x] :red_circle: Document proposed protocol changes (`ColorProvider`) @aeschli

#### Emmet
- [x] :runner: Support for choices in Emmet snippets #33994 @ramya-rao-a

##### JavaScript/TypeScript
- [x] Explore how to get syntax highlighting in template strings #34260 @mjbvz
- [x] Explore improve UX for when to surface Extract Method to users #34261 @mjbvz
- [x] Automatically show suggestions when entering an import statement #21543 @mjbvz @jrieken
- [x] :red_circle: Adopt TypeScript v.2.5.3 @mjbvz

### Extensions
- [x] Adapt workspace extension recommendations to multi-root-folder workspaces #29242 @sandy081
- [x] Improve relevance of prompted extension recommendations #34233 @ramya-rao-a 

### Extension Contributions
- [ ] :runner: Docker: Support multi-root-folder workspaces Microsoft/vscode-docker#101 @bpasero @chrisdias
- [ ] :runner: Go: Ship support for multi-root-folder workspaces https://github.com/Microsoft/vscode-go/issues/1142 @ramya-rao-a
- [x] :GitHub issues: Support multi-root folder workspaces https://github.com/Microsoft/vscode-github-issues-prs/issues/21 @chrmarti

### API
- [x] Broader support for  `WorkspaceFolder` in the API (glob, doc filter) #34157 @bpasero
- [x] Provide a picker UI for `WorkspaceFolders` #32936 @bpasero
- [x] Support formatted parameter hints and suggest items using `MarkedString` #11877 @jrieken
- [x] Promote Open/Save dialog API to stable #13807 @jrieken
- [x] Debug: Add "breakpoint created/deleted" notifications #8642 @weinand @isidorn

### Engineering
- [x] Adopt Electron 1.7.7 #33953 @tyriar
- [ ] :runner: Improve stability and performance of smoke test #34203 @joaomoreno @isidorn @sandy081
- [x] Explore bot support in component repositories #32238 @chrmarti
- [x] Adopt new CLA bot on GitHub #34239 @kieferrm

### Documentation
- [x] :red_circle: Publish extension guide for multiple-root-folder support @bpasero @dbaeumer @sandy081
- [x] :red_circle: Publish sample extension with multi-root-folder support @bpasero
- [x] Move Tips and Tricks to code.visualstudio.com @gregvanl
- [x] Review and update keyboard cheatsheets @gregvanl
- [x] Review debugging docs, and link up existing vscode-recipies to new debugging sections @auchenberg

### Explorations
- [x] Provide `FileSystemProvider` API  #34218 @jrieken
- [x] :red_circle: Support root folders populated by a `FileSystemProvider` (see API) @isidorn @jrieken 
- [x] Provide `FtpFileSystemProvider` sample #34218 @jrieken
- [x] Explore ways how to make Electron adoptions less painful #34395 @Tyriar 
 
----
### Deferred
- Vetur: Explore support for multi-root-folder workspaces https://github.com/vuejs/vetur/issues/424 @octref
- Support to attach debugger to an electron-spawned node process #25618 @weinand
- Support to contribute a menu item for a resource suffix (e.g. `*.zip`) #26044 @jrieken
- Debug: Expose debug status such as `started`/`stopped` #30810 @weinand
- Debug: Allow access to current launch configuration in an extension #23564 @weinand
- Promote Color Provider API to stable #34366 @rebornix @jrieken 
- Add Multi-root workspace topic @gregvanl

**Comment by NateLing** [comment]
中国人民送来贺电(The Chinese have send message of congratulation)！

**Comment by jasnzhuang** [comment]
同祝~

**Comment by guoboism** [comment]
The C# region folding thing is finally seeing some lights?

**Comment by manuelelucchi** [comment]
what about a Windows Store port? It's under consideration?

**Comment by DongLee0504** [comment]
在git环境下，对修改的文件进行跟踪标记，像webstorm那样修改过的文件名的颜色发生变化
![tim 20170921143546](https://user-images.githubusercontent.com/20215926/30681950-410d05ae-9eda-11e7-9143-2338f57122ed.png)

**Comment by ikatyang** [comment]
@DongLee0504 

See #178. And this issue is for tracking the iteration plan, please comment on the appropriate place with English next time.

**Comment by bramborman** [comment]
@manuelelucchi Take a look at this screenshot. https://github.com/Microsoft/vscode/issues/33362#issue-253591569. You can see _Visual Studio Code (Centennial)_ in the All apps list on the left. So it seems like they're at least testing it 😊

**Comment by egamma** [comment]
Closing 1.17 has shipped.
