### ISSUE TITLE
Improve Windows support in integrated terminal October 2017

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#35505]
This is a plan item for terminal work in the October iteration, in rough order of priority:

- [x] Terminal leaks processes https://github.com/Microsoft/vscode/issues/26807
- [x] Trashcan button kills entire terminal process tree including non-console apps https://github.com/Microsoft/vscode/issues/35492
- [x] Wrapped lines lead to wrong problems https://github.com/Microsoft/vscode/issues/32042
- [ ] ~~Scrolling via mousewheel in the terminal scrolls by a lot on Windows (about 12 lines) https://github.com/Microsoft/vscode/issues/35111~~
- [ ] ~~Terminals launched with invalid paths hang during creation and never emit onExit https://github.com/Microsoft/vscode/issues/31301~~
- [ ] ~~Terminal doesn't handle PowerShell's space escape character correctly #33584~~

**Comment by equinusocio** [comment]
@Tyriar what about this one?
https://github.com/Microsoft/vscode/issues/35963

**Comment by Tyriar** [comment]
@equinusocio that one's not Windows. I suspect that process may be detaching itself or something as there haven't been any reports of it happening on macOS or Linux.

**Comment by dbaeumer** [comment]
@Tyriar could we add https://github.com/Microsoft/vscode/issues/33584 to the list. I have requests  to better handle spaces in commands and for bash I propose to use `\` as a space escape character. Would be cool if I could propose the backtick for PowerShell. This has the advantage of not dealing with quotes which always complicates things.

**Comment by Tyriar** [comment]
@dbaeumer sure I'll see if I can get to it for October. Could you provide repro steps in that issue where you expect it to work, either as a `task.json` or `terminal.integrated.shellArgs.windows`?

**Comment by ghiscoding** [comment]
@Tyriar what about this one?
#30638 
I find it a bit annoying that a `cls` doesn't clear the history entirely as it comes back in some situations and it seems to be Windows only.

**Comment by dbaeumer** [comment]
@Tyriar regarding #33584: I retested this and it seems to work using this task now in a workspace that has a `test folder` directory. The task is:
```
		{
			"type": "shell",
			"taskName": "dir",
			"command": "dir test` folder"
		}
```

Terminal must be PowerShell. The internal launch args are:

![capture](https://user-images.githubusercontent.com/1931590/31532725-4d923210-afef-11e7-9d17-39d627611a37.png)

**Comment by eamodio** [comment]
@Tyriar maybe https://github.com/Microsoft/vscode/issues/36989 can be included here too?
