### ISSUE TITLE
March Iteration Plan

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#3555]
March is our end game for the [Build 2016](http://build.microsoft.com/) milestone. During the endgame the focus is on problems, performance, publish. This doesn't mean that we do stop listening to feedback, but we will slow down on adding new features.

##### Monday, Mar 14
- [x] Code freeze early morning
- [x] Test build done
- [x] Testing

##### Tuesday
- [x] Test tours
- [x] Fixing
- [x] Run OSS tool @joaomoreno  

##### Wednesday
- [x] Test tours
- [x] Fixing

##### Thursday
- [x] Fixing
- [x] Test [Tours](https://github.com/Microsoft/vscode/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Atestplan-item+tour)
- [x] Verification

##### Friday
- [x] Memory leak investigation and fixing
- [x] nls input @dbaeumer 
- [x] Verification

##### Monday, Mar 21
- [x] Smoketest
  - [x] Windows 
  - [x] OS X 
  - [x] Linux 
- [x] Release [`insider`](https://blogs.msdn.microsoft.com/vscode/2016/02/01/introducing-insiders-builds/) channel
- [x] All release notes updated 

##### Tuesday-Friday
- [x] All issues verified
- Satellite modules ready, version updated, smoke tested
  - [x] vscode @bpasero 
  - [x] yo generator @aeschli 
  - [x] vsce @joaomoreno: 
  - [x] Debug adapter @weinand 
  - [x] Language client/server @dbaeumer 
  - [x] eslint (recommended linter for JS) @dbaeumer 
- [ ] doc(review)athon Microsoft/vscode-docs#244

For more information about our development process please refer to the development process [page](https://github.com/Microsoft/vscode/wiki/Development-Process).

#### Finish
- UI
  - [x] Folding - add commands to fold to a particular level @aeschli 
    - Test #4069
    - [x] Release notes
  - Explore - HTML Preview run from a WebView and support executing JS #2912 @bpasero, @jrieken 
    - [x] WebView is the way to go, but we have to defer this to after March. For March we will support to run scripts inside the iframe, this addresses #2912.
    - [x] Release notes
  - [x] Support to associate an extension with a language/mode @bpasero @aeschli 
    - Test: #3925
    - [x] Release notes
  - [x] Column Select #1515 @alexandrudima 
    - Mouse select is done, need to also support using the keyboard, the preferred key binding is already 
taken.
    - Test: #4092
    - [x] Release notes
- Install
  - [x] Support redhat install, provide RPM package #3603, #3595 @tyriar
    - Test: #4041
    - [x] Release notes
  - [x] Support install localized version of Code+bundled extensions @dbaeumer 
    - Test: #4018 
    - [x] Release notes
- Extensions
  - [x] Inform user when an update to an extension is available #3540 @joaomoreno 
    - Show a status bar contribution with the number of out dated extensions
  - [x] Show progress when installing an extension #2835 @joaomoreno 
    - Show a status bar contribution `installing extensions`
  - Test: #4024
-  JS  
  - [x] Add support to disable Salsa syntax errors `javascript.validate.enable` #3909 @dbaeumer 
  - [x] Guide users to configure a `jsconfig.json` file @jrieken 
    - Test: #4007 
    - [x] Release notes
  - [x] Guide users configure excludes for a large project @jrieken
    - Test: #4007 
    - [x] Release notes
- Debug
  - [x] Support to run a target without the debugger Microsoft/vscode#2780 @weinand
    - Test: #3906
    - [x] Release notes
  - [x] Integrate node-debug in nls tooling Microsoft/vscode#3578 @weinand, @dbaeumer 
  - [x] Support to pass a 'More Information' url from the debug adapter to the frontend 
    - Test: #4026
Microsoft/vscode#3448 @weinand
- Accessibility
  - [x] Reader cannot access IntelliSense dropdown contents Microsoft/vscode#3640 @alexandrudima   
    - Test: #4093
    - [x] Release notes
- Editor
  - [x] Investigate into how we can help improve VIM extensions by providing additional API @alexandrudima  
    - [x] Release notes
  - [x] Add support so that Code can be used as the git editor @bpasero 
    - Test #3954
    - [x] Release notes
- Localization
  - Support a setting for the locale @dbaeumer 
     - [x] Release notes
      
#### Problems.Performance
- [x] High Energy Impact. #774, #3222 @bpasero
- [x] Code Folding in larger files add a limit for the number of folded regions #3582 @aeschli
- [x] Debt - Do not use Remote in event handlers #3072

#### Polish
- Language support
  - [x] Revisit intellisense inside comments Microsoft/vscode-go#203 @jrieken 
    - [x] Release notes
    - Enable that users can configure RETURN to not be a completion character.
- UI
  - [x] Guide the user for how to bring the hidden menu bar back #3421 @bpasero
  - [x] Toggle render whitespace shortcut/discoverability @isidorn 
  - [x] Allow to save UTF 8 with BOM Microsoft/vscode#751 @bpasero
    - Test: #3924
    - [x] Release notes
  - [x] Polish Indentation story #3590 @isidorn, @alexandrudima 
    - Test: #3922 
    - [x] Release notes
- Tasks
  - [x] Improve task configuration/creation #3849 @dbaeumer
  - test: #3159, #4019
  - [x] Release notes
- TypeScript/JavaScript
  - [x] Expose TS formatter options as user settings #3721 @dbaeumer 
    - Test: #4022 
    - [x] Release notes
  - [x] Expose the HTML formatter options as user settings #4013 @aeschli
    - Test: #4066
    - [x] Release notes
- Install/update
  - [x] Help users to not forget to read the release notes #3525 @joaomoreno
    - Show an info message with a command to open the release notes after an update restart
    - Test: #4023 
- Debug
  - [x] Show StoppedEvent.text in the UI Microsoft/vscode#3101 @isidorn
  - [x] Watermark, hint when watch pane is empty @isidorn
  - [x] Improving transition from debug to editing #3829 @isidorn 

#### Adoptions
- [x] TypeScript 1.8.9 when it becomes available (1.8.5 is available now)
- ~~Electron~~

#### Release
- [x] GA licenses @chrisdias 
- [x] Accessibility document @gregvanl

**Comment by codyrigney92** [comment]
For the item, "HTML Preview run from a WebView and support executing JS", is there any plans to add support for jade templates also?  Like jade to html on the fly and render?

**Comment by tht13** [comment]
@codyrigney92 There is an [extension](https://marketplace.visualstudio.com/items?itemName=wmaurer.html2jade) to convert jade to html, you could use this in combination with [HTML preview](https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode) to achieve this?

**Comment by codyrigney92** [comment]
@tht13 Thanks, I'll have to give that a try.

**Comment by luisrudge** [comment]
I'm sad [this](https://github.com/Microsoft/vscode/issues/78) is not on the roadmap :(

**Comment by egamma** [comment]
@luisrudge this is just the finish list for the build conference end of March. We will update the roadmap soon.

**Comment by felixfbecker** [comment]
> Example of a localized extension

Is there also a way for debug adapters to get the locale of the user? I name my "Threads" _Request X (time)_ and would like to localize the time format and also translate "Request". Maybe the locale ID could be send in the InitializeRequest? @weinand

**Comment by weinand** [comment]
@felixfbecker the localisation story is in the works. The locale is passed via the environment. node-debug is an example.

**Comment by codyrigney92** [comment]
@tht13 I tried your suggestion but there are 2 problems

 - HTML Preview won't recognize a .jade file with HTML in it after converting (although it would be cool if this was automatic)
 - It doesn't run javascript

I'll wait for the release and see what's possible then.  Thanks!

**Comment by tht13** [comment]
@codyrigney92 If you add a feature request to the html preview repo I'll remember to add that compatibility.
As for Javascipt that is a current limitation of VSCode which @egamma has marked as todo for the March plan (it looks like the feature is already done :smile:) So that will have to wait for the end of the month.

**Comment by codyrigney92** [comment]
Thanks @tht13 

https://github.com/tht13/html-preview-vscode/issues/1

**Comment by tht13** [comment]
@codyrigney92 Jade preview compatibility has been added and v0.0.3 will be released later this evening :smile:

**Comment by codyrigney92** [comment]
@tht13 Thanks!

**Comment by seanmcbreen** [comment]
Add comment about insiders release ready for testing.

**Comment by ciel** [comment]
So I'm confused; The ability to disable intellisense in comments - was that fixed, or not? I've tried out the insider build and don't see the functionality implemented.
