### ISSUE TITLE
Iteration Plan for October 2017

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#35875]
This plan captures our work in **October**. This is a 5 week iteration. We will **ship early November**. We're done with our work regarding supporting multi-root-folder workspaces (see #396) in the core. During this iteration we will assist extension authors to enable multi-root-folder support in their extensions. We will provide support using [documentation](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs), [samples](https://github.com/Microsoft/vscode-extension-samples), issues, Pull Requests, and a special slack channel.

## Endgame
- **October 30th**: Code freeze for the endgame
- **November 3rd**: Endgame done
The endgame details for this iteration are tracked in #37117.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :large_blue_circle: | more details required |
| :red_circle: | missing issue reference |

### Workbench
- [x] Decorate explorer items with the SCM and error state #178 @jrieken
- [x] Multi-root folders: indicate when a user is using an extension in a multi-root setup, but the extension does not yet support it @bpasero
- [x] Overflow design for the panel title area #31503 @isidorn
- [x] Support a vertical panel layout #2806 @isidorn
- [x] Avoiding catastrophic backtracking for Quick Open #35346 @chrmarti
- [x] Respect `.gitignore` in Quick Open #34991 @chrmarti

### Editor
- [x] Editor performance: decorations as an interval tree #36410@ alexandrudima
- [x] Improve Ctrl+D/Cmd+D in collapsed selection case #8869 #9978 #19825  #28528 #34548 
- [x] Improve editor undo stops #29036
- [ ] :runner: :muscle: Editor investigate into a native model layer
- [x] Folding performance: compute fold regions more lazy, create fewer decorations #36555 @aeschli

### Debug
- [x] Current launch config should be visible when the Debug viewlet is not active #31745 @isidorn
- [x] node debug: Colorize evaluation results in the Console #35324 @isidorn, @roblourens

### Terminal
- [x] Avoid leaking processes on Windows when closing the terminal #26807 @tyriar
- [x] Terminal improvements #35505 @tyriar

### SCM
- [x] Support to view a change indicted in the gutter of the editor #10782 @joaomoreno

### Tasks
- [x] Task 2.0 schema polish #29852 @dbaeumer

#### JSON
- [x] Support JSON schema draft-06 #29152 @aeschli

#### JavaScript/TypeScript
- [x] Adopt TypeScript v2.6 #36100 @mjbvz
- [x] Support completion proposals with explicit imports #2635 @mjbvz
- [x] Provide Quick Fixes for adding/installing `@type` dependencies #34787 @mjbvz
- [x] :runner: Support as you type completions inside template strings #34857 @mjbvz

### Extensions
- [x] Use UUIDs for extension identification to enable publisher changes #34812 @sandy081
- [x] Highlight recommended extensions in extension search results #36650 @ramya-rao-a
- [x] Improve default view of the extension viewlet #36649 @ramya-rao-a

### Extension Contributions
- [x] :runner: Work with extension authors to enable multi-root-folder support, see [documentation](https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs) **team**
- [x] Support ESLint/tslint module install globally via yarn Microsoft/vscode-eslint#187 Microsoft/vscode-tslint#178 @dbaeumer @egamma
- [x] Support multiple root folders in the npm-script-runner extension @egamma

### API
- [x] Add `resourceExtname` context key https://github.com/Microsoft/vscode/pull/34889 @jrieken
- [x] Promote Color Provider API to stable @jrieken
- [x] Expose API to listen to particular configuration changes @sandy081
- [x] FileSystemProvider add support to search for file names @jrieken
- [x] Replace the `debug.logToDebugConsole` command with an API #36753 @weinand
- [x] Async validation of the input box #34532 @jrieken

### Engineering
- [ ] :runner: Windows: high precision touch pad support, investigate whether a chromium patch improves the current behaviour #13612 @bpasero
- [x] Support fine grained listening to configuration changes @sandy081
- [x] Explore adoption of Electron 1.8 @tyriar @bpasero
- [x] Improve stability and performance of smoke test #34203 @joaomoreno 

### Documentation
- [x] Update the multi-root folder migration support doc @egamma
- [x] Add Multi-root workspace topic https://github.com/Microsoft/vscode-docs/issues/1169 @gregvanl

## Deferred

- Explore using automated smoke tests to test electron beta releases @tyriar
- FileSystemProvider add support to search in files @jrieken
- Enable groups in the explorer's context menu @bpasero
- Investigate into improving install/update experience on Windows @joaomoreno
- Support to enable an extension for a single workspace (currently only disable is supported) @sandy081
- Multi-select in explorer #1023  @isidorn @bpasero
- Explore improving GDPR annotations in our code #36659 @kieferrm
- :runner: Separate refactorings from the code actions menu #34664 @mjbvz
- Vetur: Explore support for multi-root-folder workspaces vuejs/vetur#424 @octref
- Support to programatically add/remove a root folder to a workspace #35407 @bpasero

**Comment by Mlocik97-issues** [comment]
so early.?.

**Comment by derekriemer** [comment]
hey, just an FYI, your table for legend is appearing as markdown.

**Comment by gulshan** [comment]
This is not included in October milestone yet. :)

**Comment by egamma** [comment]
@gulshan fixed, thanks.

**Comment by abhigp27** [comment]
when is the release date?

**Comment by jens1o** [comment]
On Thursday, the 9th November as [you can see here](https://github.com/Microsoft/vscode/issues/37117).

**Comment by agauniyal** [comment]
> Editor investigate into a native model layer
Is this similar to what Atom did with 1.19 - http://blog.atom.io/2017/08/08/atom-1-19.html ?

**Comment by agauniyal** [comment]
> Editor investigate into a native model layer

Is this similar to what Atom did with 1.19 - http://blog.atom.io/2017/08/08/atom-1-19.html ?
