### ISSUE TITLE
Log file uploader - client side, master issue

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#40056]
Earlier experiment is at https://github.com/Microsoft/vscode/tree/verbose-logging-mode

**General tasks**
- [ ] Move uploader extension into core
- [ ] Use fewer dependencies (no archiver or azure storage npm modules)

**UX**

Basic user flow
- User files bug, we ask user to launch with `--log trace`, then run command "Upload logs", then copy the blob ID back into the issue
- And alternately, user collects logs, runs "Upload logs". When complete it shows a notification with 3 buttons: Review logs, File issue, Cancel. User selects File Issue, which uploads the logs then opens github with the blob ID pre-filled in the issue template

**UX Tasks** 
- [ ] How to invoke "I want to upload logs"? Originally was a status bar item. Could keep that and just make it visible when you're at a non-default log level.
- [ ] Implement three buttons: review, file issue (upload and then create issue with blob ID), cancel
- [ ] Upload progress indicator

**Comment by roblourens** [comment]
and cc @joaomoreno @sandy081 @jrieken

**Comment by augb** [comment]
Any plans to allow non-VS Code projects to make use of this functionality via an API or via some other means?

**Comment by roblourens** [comment]
Not at the moment.

**Comment by mjbvz** [comment]
Closing this out. 

We moved to use the CLI for this instead of VS Code UI. The new `--upload-logs` command line options walks you through uploading logs from the currently running session
