### ISSUE TITLE
Iteration Plan for January 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#41061]
Happy 2018 everyone! This plan captures our work in **January**. This is a 5 week iteration. We will **ship early February**.

## Endgame
- **January 29th**: Code freeze for the endgame
- **February 2nd**: Endgame done

The endgame details for this iteration are tracked in #42374

## Plan Items
Below is a summary of the top level plan items. Given the large number of explorations, we'll diverge from our usual practice of having plan items for all bullets upfront. This time we'll add them as we go.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Install/Update
- [x] Investigate in improving the update experience on Windows #41676 @joaomoreno

### Workbench
- [x] Switch to async dialog API #39536 @bpasero
- [x] Support saving a file in admin mode #1614 @bpasero
- [x] UX for notification improvements #22388 @bpasero @stevencl
- [x] Multi-select in the Explorer, Open Editor #1023 @isidorn
- [x] Reimplement drop downs for Linux/Windows (themable, fixes initial empty contents) #25965 (PR @cleidigh) @bpasero
- [x] Enable Error decorations in explorer #782 @jrieken
- [x] Support natural language search in Settings editor #40957 @roblourens
- [x] Explore improving how a user changes a setting #41040 @roblourens @sandy081

### Editor
- [x] Text model and storage reimplementation to improve performance #41042 @alexandrudima @rebornix
- [x] Allow to save large files > 256 MB #32503 @bpasero @alexandrudima
- [x] Support language-type independent snippets #13182 @jrieken
- [x] More customization for the caret #41052 @ramya-rao-a 

### Debug
- [x] Launch configs for multi root workspaces #38134 @isidorn
- [x] Support auto attach for node.js subprocess (aka cluster support) #40123 @weinand
- [x] Support to use `nvm` configuratons in node launch configs #25386 @weinand
- [x] Explore how to run DebugAdapter inside extension #40906 @weinand

### Terminal
- [x] Improve accessibility of built-in terminal #8339 @tyriar

### SCM
- [x] Submodule support @joaomoreno
- [x] Git commit message length counter @joaomoreno

### Output Panel
- [x] Show product logs in the output panel #39638 @sandy081
- [x] Make log viewing in output panel more memory efficient #40196 @sandy081

#### Language Server Support
- [x] Create a [website for LSP](https://microsoft.github.io/language-server-protocol/) @dbaeumer @auchenberg
- [x] Protocol extension for goto implementation Microsoft/language-server-protocol#156 @dbaeumer

#### Emmet
- [x] Explore how to improve emmet activation in `html` and `css` files #29113 @ramya-rao-a

#### JavaScript/TypeScript
- [x] Adoption of TS 2.7 #41046 @mjbvz

#### CSS/HTML
- [x] Catchup with latest CSS/Less syntax Microsoft/vscode-css-languageservice#56 Microsoft/vscode-css-languageservice#57 Microsoft/vscode-css-languageservice#58 Microsoft/vscode-css-languageservice#47 @octref @aeschli

### Extensions
- [x]  `vsce` - Warn when `package.json` misses `repository` entry #41677 @joaomoreno
- [x] Improve quality of recommended extensions #41054 @ramya-rao-a
- [x] Tastefully extend recommendations to a wider range of file types #38543 @ramya-rao-a

### Extension Contributions
- [x] Refresh JS Hint support Microsoft/vscode-jshint#48 @rmacfarlane

### API
- [x] Migrate proposed `Code action` API to stable #34664 @jrieken @mjbvz 
- [x] Propose API to resolve rename/definition scope #7340 @jrieken @mjbvz
- [x] Explore improving the HTMLPreview support #41047 @mjbvz @jrieken
- [x] Propose refactoring provider API #41048 @jrieken @mjbvz
- [x] Expose logging API to extensions #40053 @roblourens
- [x] Propose Search Provider API @jrieken, @roblourens 
- [x] Propose API to create/delete/rename resources for refactorings @jrieken @mjbvz 
- [x] Enhance custom tree view API, primary actions, use icons from resource URI, preserve expansion state, improve managing contributions  #27823 @sandy081
- [x] Debug API to create/remove breakpoints @weinand
- [x] Support to modify the root folder of a workspace #35407 @bpasero 

### Performance
- [x] Use ASAR for bundled node modules #41350, #41353 @alexandrudima
- [x] Explore using plain nodejs for helper processes #41685 @alexandrudima
- [x] Explore local storage replacement #18439 @bpasero

### Serviceability
- [x] Issue reporter in separate renderer windows #41041 @rmacfarlane @octref
- Logs
  - [x] Propagate log level to all processes dynamically #39754 @sandy081
  - [x] Support to upload logs #40056 @mjbvz @roblourens

### Engineering
- [x] Self-host on `@ts-check` for our JS code #41678 @joaomoreno @egamma
- [ ] :runner: Support extensions that contribute translations aka "language packs" #39178 @dbaeumer @sandy081 @aeschli
- [ ] :runner: Tool to generate/update a language pack from transifex #41682 @aeschli
- [x] Speed up gulp-build @alexandrudima
- Improve issue tracking support bot @chrmarti
  - [x] Delay action of auto-assignment bot by 15s #33999
  - [x] Explore support for detecting duplicate issues #41292

### Documentations
- [x] Make 5min Node.js debugging video to be embedded in docs and uploaded to YouTube channel @auchenberg
- [x] Add Debugging Recipe for VueJS. https://github.com/Microsoft/vscode-recipes/issues/55 @auchenberg

------
### Deferred
- Improve documentation of our electron upgrade process #41036 @tyriar
- Add intelisense support for `src ` attributes and `href` in html #2037 @octref @aeschli 
- Adopt logging service  @joaomoreno the adoption by the #41680 **team**

- :muscle: Render white space for selection option #1477 @ramya-rao-a
- Provide API for creating a file based output channel #41672 @sandy081
- :hand: Electron update to 2.0 @tyriar @bpasero
- :muscle: Docathon **team**
-  :hand: Support 32-bit apt repositories #20790 @tyriar
- Better support for webpack **TBD**
- Support web-site for issue reporting @octref @rmacfarlane
- Improve stability of smoke test, run it as part of the builds #41679 # @joaomoreno
- :muscle: Process explorer as a separate renderer window #41045 @rmacfarlane

**Comment by NateLing** [comment]
hi,are you sure update electron to 2.0?  The last electron version is v1.8.2-beta.3.

**Comment by roblourens** [comment]
We haven't done it yet, this is just the plan for the month. And the ✋ means we're blocked.

**Comment by Eskibear** [comment]
I find the following entry in [Roadmap#for-extension-authors](https://github.com/Microsoft/vscode/wiki/Roadmap#for-extension-authors), seems completed.

> - [x] Support migrating the publisher of an extension to another publisher

Does this means we can transfer `alice.toy-extension` to `bob.toy-extension`, leaving everything else (new extension di) unchanged? 
If so, I'm eager to know when to include the feature, and how to migrate. Thanks.

**Comment by aberonni** [comment]
Hi, sorry to bother, I'm wondering whether you think #14909 might possibly make it into the next iteration? I think it is quite the dealbreaker for a lot of people who aren't using VSCode right now only because of that issue.

If not, could you give an update on the issue as to why it is not being developed?

Thanks!

**Comment by egamma** [comment]
@aberonni we create the iteration plan at the beginning of an iteration ([pls see](https://github.com/Microsoft/vscode/wiki/Development-Process)). We understand that this feature has many up votes, but there are others with [more votes](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc). All I can say for now is that the feature is on our radar.

**Comment by aberonni** [comment]
@egamma thanks for getting back to me, that makes perfect sense to me.

**Comment by egamma** [comment]
@alxgrtnstrngl thanks for your feedback. In addition to the iteration plan we also maintain the [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) for the next 6 months. We update the roadmap based on user feedback. Several of the items you mention above are already on this roadmap. 

Our planning process is documented here https://github.com/Microsoft/vscode/wiki/Development-Process

**Comment by bsvipas** [comment]
Guys I saw release notes and I'm impressed. Thank you very much! It's my daily tool which I'm using more than 8 hours per day and I'm every single day happy because of VS Code. Thank you very much! That support, activity, features, bug-fixes, team - it's amazing! 🥇

**Comment by onetrev** [comment]
I'm concerned that "Catchup with latest CSS/less syntax" was checked off when [this item](https://github.com/Microsoft/vscode-css-languageservice/issues/47) that was in the list is still open.

**Comment by octref** [comment]
@onetrev Getting full PostCSS/cssnext support is going to take multiple iterations. We've started internal discussion and you'll see more work toward it in future iterations.
With that said, if future CSS features come out of the draft phase, become spec and get supported by major browsers, we will support those features in vscode-css-languageservrice.

**Comment by kieferrm** [comment]
Shipped. Closing.
