### ISSUE TITLE
Add support for "logPoints"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#45128]
Umbrella item for LogPoints:

- [x] show breakpoint icon in Breakpoints view (finished in February #3388)
- [x] DAP: Add support for log-points #162
- [x] treat source breakpoints with logMessage as logPoints in the UI
  - [x] show them with diamond shaped icon
- [x] new "Add Logpoint" and "Edit Logpoint..." actions in gutter
- [x] new peek UI for editing logPoint message
  - [ ] Support language specific intellisense in logMessage peek UI #45127
- [x] surface logMessage in extension API (see #45643)
- [x] implement logPoint semantics in node-debug
- [x] implement logPoint semantics in node-debug2 (see https://github.com/Microsoft/vscode-node-debug2/issues/163)

**Comment by isidorn** [comment]
@chryw fyi this milestone we will also be using the nice log point icon you provided us. Once you go over our icons to standardise them you could also make sure the log point is consistent with other icons as well.

**Comment by weinand** [comment]
@isidorn in the DAP the "logMessage" exists only on the SourceBreakpoint but for VS Code I suggest that "logMessage" lives on some common base class for SourceBreakpoint and FunctionBreakpoint. Most likely I'll add a "logMessage" on the FunctionBreakpoint soon.
It would be great if all the common attributes "enabled", "condition", "hitCondition", "logMessage", "id", would live in a baseclass...

**Comment by isidorn** [comment]
@weinand agree, I will try to structure it like that this afternoon.

**Comment by isidorn** [comment]
![logpoint](https://user-images.githubusercontent.com/1926584/37514360-03131a82-2908-11e8-9c95-c5093208b2ad.gif)

I have created test plan item https://github.com/Microsoft/vscode/issues/45962
Feel free to modify it

**Comment by weinand** [comment]
@isidorn you've checked off `new "Add Logpoint" and "Edit Logpoint..." actions in gutter`.
I'm not seeing those actions? Am I missing something?

**Comment by isidorn** [comment]
@weinand you can see them if you run vscode out of source. They will be avilable in tomorrows insiders.
As for the Edit Logpoint - will not introdcue that action since there is an edit breakpoint actions which is smart enough imho.

**Comment by weinand** [comment]
I am running out of latest source but I was only looking for the "Edit Log Point" actions...

**Comment by isidorn** [comment]
If demand is high I can rename the "Edit Breakpoint" action to "Edit Log Point" if the user clicks on a log point.

**Comment by auchenberg** [comment]
@isidorn @roblourens @weinand Do we want to mention LogPoints in this iterations release notes? I'm not convinced our implementation for Node is ready for prime time, per learnings from yesterday: https://github.com/Microsoft/vscode-node-debug/pull/174#issuecomment-376691912

One option for us could be to prefix it with "Preview"

**Comment by nonameolsson** [comment]
Does this only apply for Node? Not PHP?

**Comment by weinand** [comment]
@nonameolsson from the 1.22 release notes:

![2018-04-06_10-45-50](https://user-images.githubusercontent.com/1898161/38411601-b8ede956-3987-11e8-93c6-4a1890b50909.png)

Debug extensions have to actively opt into this feature.
