### ISSUE TITLE
Iteration Plan for March 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#45632]
This plan captures our work for our **March Update**. This is a 4-week iteration. We will ship **early April**. We'll continue our work on terminal splitting, supporting more flexible workbench layouts, and language aware folding. All three items are still among the top upvoted features (4, 5, 10). We'll also work on log-point support in our debuggers.

## Endgame
- **March 26th**: Code freeze for the endgame
- **March 30th**: Endgame done

The endgame details for this iteration are tracked in #46620.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Install
- [x] Improve the update experience on Windows #41676 @joaomoreno
- [ ] :hand: :runner: Allow user level installs on Windows #534 @joaomoreno
- [ ] :runner: :muscle: Provide a VS Code snap package #5458 @tyriar
- [ ] :hand: Support 32-bit apt repositories #20790 @tyriar

### Workbench
- [x] Propose how to unbundle built-in languages in favor of languages packs #45663 @dbaeumer
- [x] Finish language-aware folding #45981 @aeschli
- [x] Allow <kbd>F8</kbd> to navigate across files #14783 @jrieken
- [x] Allow to navigate to next/previous reference match using <kbd>F4</kbd> #44414 @jrieken
- [x] Improve presentation of search results when they are shown in the panel #45063 @roblourens @isidorn
- [x] Explore multi-location diagnostics support in the problems view, in <kbd>F8</kbd>, and in the hover #10271 @sandy081 @jrieken
- [ ] :runner: Explore improving settings experience #41040 @roblourens @sandy081
- [x] Support horizontal-scrolling in tree views #15539 @joaomoreno
- [x] Support using the Editor as a workbench widget in the Repl input, breakpoint widget, git commit input etc. #46112 @isidorn

### Editor
- [x] Optimize 'find and replace' for large files #45690 @rebornix
- [x] Coloring of large files when not opened at the top #45944 @rebornix @alexandrudima 
- [x] Exploration using viewzones for code discussions #45945 @rebornix
- [x] Ship a new version of the monaco editor [See query.](https://github.com/Microsoft/monaco-editor/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22On+Deck%22) @rebornix @alexandrudima
- [x] Package the monaco editor in the ESM format Microsoft/monaco-editor#18 @alexandrudima

### Terminal
- [x] Support for multi-line links #28746 @tyriar
- [x] Navigation between commands run in the terminal #45435 @tyriar
- [x] Explore options for reflow #23688 @tyriar
- [x] Investigate which terminal state to persist across sessions #44302 @tyriar

### Source Control
- [x] Explore supporting custom view contributions to the Git viewlet #45686 @joaomoreno

#### Language Server Protocol
- [x] Propose support for multi-location diagnostics Microsoft/vscode-languageserver-node#324 Microsoft/vscode-extension-samples#51 @kieferrm @dbaeumer
- [x] Propose support for language aware folding #45983 @aeschli

#### Emmet
- [x] List gaps that are blocking the move of css emmet completions to css extension #29113 @gushuro @ramya-rao-a
- [ ] :runner: Explore speed improvements of the expand command by replacing emmet parser #43470 @gushuro @ramya-rao-a
- [x] Support wrap with abbreviation in real-time #23169 @gushuro @ramya-rao-a

#### JavaScript/TypeScript
- [x] Improve auto-activation of intelli-sense in `jsdoc` types #43715 @mjbvz
- [x] Improve auto-activation of intelli-sense in template literals #37176 @mjbvz
- [x] Improve auto-activation of intelli-sense in `.jsx` files #40941 @mjbvz
- [x] Adopt TS 2.8 #45949
   - [x] Organize imports #45108 @mjbvz
   - [x] Language aware folding #45950 @mjbvz
   - [x] Handling of info-level diagnostics #45378 @mjbvz 

#### CSS/HTML/JSON
- [x] Language aware folding for JSON #45981 @aeschli
- [x] Language aware folding for HTML #45981 @aeschli
- [x] Language aware folding for css/less/scss #45899 @octref
- [x] Split html, css, and json built-in extensions into basic and language features #45900 @aeschli @octref
- [x] CSS path completion #45235 @octref
- [x] Polish path completion in html #44813 #44814 #44815 @octref

### Extensions
- [x] :muscle: Improve sorting of built-in extensions #45921 @ramya

### Extension Contributions
- [ ] :runner: Sublime config importer #45984 @tsalinger @sandy081
- [x] Vetur: Review PR for JS completions in template section of a `vue` file vuejs/vetur#681 @octref

### Debug
- [x] Add LogPoints support #45128 @isidorn
- [x] Breakpoint Extension API: support for LogPoints and bug fixing #45643 #44433 @weinand
- [ ] :runner: Support language specific intelli-sense in breakpoints conditions and logMessage peek UI #45127 @isidorn
- [x] Auto attach debugger to Node processes started from integrated terminal #42521 @weinand
- [x] Explore support for extension debug adapters #45129 @weinand
- [x] StoppedEvent should indicate thread focus Microsoft/vscode-debugadapter-node#147 @weinand @isidorn
- [x] Add postDebugTask to launch configurations #11522 @isidorn

### API
- [x] Allow extenions to report progress in notifications #44090 @bpasero
- [x] Explore quick-pick support for multiple selection input #45589 @chrmarti
- [x] Propose a Task Execution API #45664 @dbaeumer
- [x] Propose API to allow extensions to listen to marker changes #30075 @jrieken
- [x] Support multi-location diagnostics #10271 @jrieken
- [ ] :muscle: :runner: Discuss consolidation of output channels and logs #43276 @mjbvz @jrieken
- [ ] :runner: Finialize support for computing rename locations #7340 @jrieken
- [x] :runner: Finalize Custom View API #30288 @sandy081 @jrieken 
- [ ] :runner: Propose WebView API #43713 @mjbvz @jrieken

### Serviceability
- [ ] :runner: Process explorer as a separate renderer window #41045 @rmacfarlane
- [x] Issue Reporter - support filing issues against extensions #45673 @rmacfarlane

### Engineering
- [x] Adopt electron v1.7.12 @tyriar @bpasero
- [x] Address high-precision touchpad issue on Windows @bpasero
- [x] Adoption testing for electron v2.0 beta @tyriar @bpasero
- [x] VSTS CI adoption #45048 @joaomoreno
- [x] Use `.gitattributes` to define line terminator conventions #45052 @joaomoreno
- [x] Improve [process tree module](https://github.com/Microsoft/vscode-windows-process-tree) with support for memory and CPU #46433 @rmacfarlane
- [x] Adopt TS 2.7 for selfhosting #42853 @mjbvz

### Documentation
- [ ] Continue to refresh videos on the website @auchenberg #45924

-------
### Deferred Items
- Support for computing definition locations #10037 @mjbvz
- Explore how to improve support for filing performance issues ##45674 @rmacfarlane
- Investigate support a grid layout for editors #14909 @stevencl @bpasero
- :runner: Protocol handler to open a git repository in VS Code #45685 @joaomoreno
- Support to resolve an unresolved response item #44846 @jrieken
- Explore promoting a custom view to a viewlet #43645 @sandy081
- Tune Zen mode to not show title bar #44593 @isidorn
- :muscle: Adopt new TS APIs in gulp-tsb https://github.com/jrieken/gulp-tsb/pull/76 @jrieken
- Continue exploration of V8 snapshots to improve startup performance @jrieken
- :muscle: Support encode/decoding of images in HTML #27978 @gushuro
- Support for wrap with abbreviation with history #40096 @gushuro @ramya-rao-a

**Comment by egamma** [comment]
Closing - 1.22 has shipped
