### ISSUE TITLE
Iteration Plan for April 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#47369]
This plan captures our work in **April**. This is a 4-week iteration. We will ship our April Update in **early May**. The highlights include: a preview of a more flexible editor layout (since we didn't get to it in March), a better experience when changing settings, and several new APIs for extension authors.

## Endgame
- **April 23th**: Code freeze for the endgame
- **April 27th**: Endgame done

The endgame details for this iteration are tracked in #48372.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Install
- [ ] :runner: :muscle: Provide a VS Code snap package #5458 @tyriar

### Workbench
- [ ] :runner: Preview for grid layout for editors #14909 @bpasero
- [ ] :runner: Explore improving settings experience #41040 @roblourens
- [x] Explore enabling view contributions to the activity bar #43645 @sandy081
- [x] Unbundle bundled language packs #45663 @dbaeumer @sandy081 @ramya-rao-a
- [x] Quick box improvements for multi-step inputs #48116 @chrmarti
- [x] Problems view support to exclude errors for some files/folders #22289 @sandy081

### Editor
- [x] Ship a new version of the Monaco editor @alexandrudima @rebornix

### Terminal
- [ ] :runner: Enable multi-plexing of terminals #46192 @tyriar

### Source Control
- [x] Support custom view contributions to the Git viewlet #45686 @joaomoreno
- [x] Provide a protocol handler that clones a git repository and opens VS Code #45685 @joaomoreno

#### JavaScript/TypeScript
- [x] Adopt TypeScript 2.8.x #48008 @mjbvz
- [x] Explore moving Organize Import to be a code action #46647 @mjbvz
- [x] Support Organize Import on save #46678 @mjbvz
- [x] Provide an NPM script explorer view that can run/debug scripts as tasks @egamma

#### CSS/HTML/JSON
- [x] Support regions in CSS folding provider #46591 @octref
- [x] Polish path completion #46644 #46639 @octref
- [x] :muscle: Explore how to provide cross-file `$` variable completions in SCSS and LESS #6734 @octref
- [x] Investigate how to use [MDN data](https://github.com/mdn/browser-compat-data) to power our language servers Microsoft/vscode-css-languageservice#68 @octref @aeschli
- [x] :muscle: Explore how users could extend CSS support through settings #47775 @octref
- [x] Expose API from JSON language server [vscode-json-languageservice#18](https://github.com/Microsoft/vscode-json-languageservice/issues/19) @aeschli
- [x] Restrict handling to documents with `file:` and `untitled:` schemes #48777 @octref
- [x] Make the supported schemes explicit for JSON @egamma

#### Markdown
- [x] Restrict handling to documents with `file:` and `untitled:` schemes #48777 @mjbvz

### Extensions
- [x] Extension install - detect incomplete installations @sandy081
- [x] Document what document URIs extensions should handle @jrieken
- [x] Review and ensure that bundled extensions handle non `file` based resource schemes **@team**
- [x] Add a resource scope for global settings @sandy081

### Extension Contributions
- [x] Sublime configuration settings importer #45984 @tsalinger @sandy081

### Debug
- [x] Polish LogPoints support #46821 @isidorn
- [x] Provide setting to enable/disable show value hover only #47466 @isidorn
- [x] Launch Debug Adapters in extension host #45129 @weinand

### API
- [x] Provide API to register a protocol handler #45685 @joaomoreno
- [x] Finalize the FileSystemProvider API #47475 @jrieken
- [x] Finalize FoldingProvider API #47808 @aeschli
- [ ] :runner: Consolidate Debug Adapter launch API @weinand
- [x] Finalize WebView API #43713 @mjbvz @jrieken
- [x] Finalize Task execution API @dbaeumer
- [x] Make it easier for extension authors to deal with non-file-based URI schemes #21886 @jrieken
- [x] Explore support to resolve an unresolved response items (completions, code lens) when using the language API through commands #44846 @jrieken

### Serviceability
- [x] Process explorer as a separate renderer window #41045 @rmacfarlane

### Engineering
- [x] Continue adoption of electron 2.0 @tyriar @bpasero
- [x] Automate adoption of new electron builds @bpasero
- [x] Move off spectron for the smoke test #47471 @joaomoreno

### Documentation
- [ ] :runner: Continue to refresh videos on the website #45924 @auchenberg 

-------
### Deferred Items
- :runner: Allow user level installs on Windows #534 @joaomoreno
- :runner: Finalize API to support computing definition locations #10037 @mjbvz
- Provide API for hierarchical document symbols, to enable early adopters @jrieken

**Comment by RoyTinker** [comment]
@kieferrm Any updates on floating window support plans? I'm seriously considering buying a bottle of champagne to have on hand, in case it appears here sometime soon!

🍾

**Comment by corbinu** [comment]
Quick comment. I am a lurker who likes to read these each month. However had a hard time finding this one as it is not part of the April Milestone

**Comment by pallapo** [comment]
@bpasero we need feature #14909 !!!!!
We neeeeeeed it!!!!
;-))

**Comment by RoyTinker** [comment]
<img src="https://quotefancy.com/media/wallpaper/3840x2160/226630-J-R-R-Tolkien-Quote-We-wants-it-we-needs-it-Must-have-the-precious.jpg">
