### ISSUE TITLE
Iteration Plan for May 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#49327]
This plan captures our work in **May**. This is a 5-week iteration. We will ship our May Update in **early June**.

In this iteration, we'll provide a preview of the grid layout support for the editor as well as an alternative UI for configuring settings. We'll also look into ways to provide outline information for open documents.

## Endgame
- **May 28th, 2018**: Code freeze for the endgame
- **June 1st, 2018**: Endgame done

The endgame details for this iteration are tracked in #50477.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Workbench
- [x] :runner: Preview for grid layout for editors #14909 @bpasero @joaomoreno
- [ ] :runner: Continue to improve settings experience #41040 @roblourens
- [ ] :runner: Quick box improvements for multi-step inputs #49340 @chrmarti
- [ ] :runner: Investigate custom title bar and menus for improved accessibility on Windows #29024 @sbatten
- [x] Provide command to open New Window on open workspace #49346 @isidorn
- [x] Explore supporting an Outline view #5605 @jrieken
- [x] Enable custom search implementations #47058 @roblourens
- [x] Polish activity bar contribution support #49103 #48580 @sandy081

### Editor
- [x] Ship a new version of the Monaco editor @alexandrudima @rebornix

### Terminal
- [ ] :runner: Enable multi-plexing of terminals #46192 @tyriar
- [x] Provide DOM-based rendering when GPUs are disabled #46954 @tyriar
- [x] :muscle: :runner: Investigate top-level `Terminal` menu for better discoverability #49477 @tyriar

#### Language Server Protocol
- [x] Support Code Action API and code actions that return workspace edits https://github.com/Microsoft/language-server-protocol/issues/389 @dbaeumer

#### JavaScript/TypeScript
- [x] Adopt TypeScript 2.9 #49654 @mjbvz
   - [x] Options for quote style in generated code #49653 @mjbvz
   - [x] Disable suggestions at the TS server level #47617 @mjbvz
   - [x] Support TS trigger characters #40539, #25034 @mjbvz
   - [x] :runner: Support TS `Move to New File` refactoring #49866 @mjbvz
- [x] :runner: Reasonable presentation style for 'unused variable' suggestions #15710 @mjbvz

#### CSS/HTML/JSON
- [x] :runner: Provide support for @-keywords in SASS/SCSS #41929 @octref
- [x] :runner: Debt reduction in the CSS/HTML extensions and language servers [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Acss-less-sass+milestone%3A%22May+2018%22) @octref

### Debug
- [x] Explore improved positioning of the debug toolbar #2513 @isidorn
- [x] `nodemon` re-attach issue #48501 @roblourens

### Extension Contributions
- [x] Submit PRs to extensions to suggest contributions to the built-in Test viewlet @sandy081
- [x] :runner: Re-Investigate `tslint` running as a TypeScript server plugin Microsoft/vscode-ts-tslint#7 @egamma
- Architectural improvements to the `vetur` extension @octref
  - [x] :runner: Cover Vetur's Language Features with ene-to-end tests vuejs/vetur#802
  - [x] Centralize all file system access in VLS vuejs/vetur#800
  - [ ] :runner: Decouple sub language services with top-level MetadataStore
- [x] Consolidate handling of `webroot` and `pathmapping` in the Chrome Debugger #49472 @roblourens
- [x] :runner: Support several forthcoming PRs against the `xterm.js` project xtermjs/xterm.js#1399 xtermjs/xterm.js#1327 xtermjs/xterm.js#958 @tyriar

### Extensions
- [x] :runner: Recommend language packs based on the locale of the OS #45663 @ramya-rao-a

### API
- Finalize API for
   - [x] Tasks #49806 @dbaeumer
   - [ ] :runner: Compute definition locations #10037 @mjbvz
   - [x] :runner: WebView persistence #49022 @mjbvz
   - [ ] :runner: SearchProvider #47058 @roblourens
- Propose API for:
   - [ ] :runner: Hierachical Document Symbols #34968 @jrieken
   - [ ] :runner: Quick box multi-step inputs #49340 @chrmarti
- Custom view API enhancements: 
   - [x] Access the current selection #49511 @sandy081
   - [x] Support to listen the expand/collapse state #30535 @sandy081

### Serviceability
- [x] Improve the perceived speed of opening the process explorer on Windows #45163 @rmacfarlane
- [x] Update performance wiki with how to use the process explorer #48970 @rmacfarlane
- [x] Cosmetic changes to issue reporter #49579 @rmacfarlane

### Engineering
- [x] Move to the public VSTS build infrastructure @joaomoreno
- [x] Address Github reported module vulnerabilities #49146 **team**
- [ ] :muscle: Retrain issue classifier bot #49341 @chrmarti

### Documentation
- [x] Continue to refresh videos on the website #45924 @auchenberg

-------
### Deferred Items
- Custom view: Execute command on double click #39601 @sandy081
- Electron 2.0 update
- Explore bread crumb support for navigation #9418 @jrieken
- Support intellisense in edit boxes for watches, variables #48810 @isidorn
- Adopt new VS Code APIs in the VS Code Go extension Microsoft/vscode-go#1676 @ramya-rao-a
- In settings search provide a way to show matching but not-installed extensions #49474 @roblourens

**Comment by WaiSiuKei** [comment]
>  Investigate custom title bar and menus for improved accessibility on Windows @sbatten

I think it is related to https://github.com/Microsoft/vscode/issues/29024

**Comment by Kroc** [comment]
@WaiSiuKei Also, https://github.com/Microsoft/vscode/issues/17060

**Comment by levrik** [comment]
> 🔴 Investigate custom title bar and menus for improved accessibility on Windows @sbatten

Just want to mention that the latest Windows update 1803 has issues with custom title bars. See my issue telegramdesktop/tdesktop#4649 for more information.

**Comment by ivanvoznyakovsky** [comment]
any chance to get this one #10026 on board?

**Comment by guledali** [comment]
@kieferrm 
>  Investigate custom title bar and menus for improved accessibility on Windows @sbatten 

Why does it say missing issue reference the are numerous issues out there mention this. I can just list a few of them.
#39972
#32257 
#29997
#17060

**Comment by Tyriar** [comment]
@guledali the people working on the features will fill in the issue references eventually 😄

**Comment by DarthSpock** [comment]
Yes but that would be one of the changes. The nightly could be of the alpha such as Firefox does it, and weekly could be the beta and monthly be the stable (or however long it's needed to deem it "stable") The alpha would have auto-commits per change on dependencies (a commit to NodeJs or Electron for example would update over to here instead of manually pulling it down and pushing back up) (at least on a 12 hour increment to meet the nightly update schedule). The beta would have the tweaking optimizations that ensure that at least nothing breaks even if in a rough state while the stable would be polished out. A somewhat more Agile approach that what's currently done if I understand the release schedule correctly.

**Comment by MeikTranel** [comment]
@DarthSpock but that's not all compliant to the work item planning right  in front of you.
They iterate Monthly with a focus on stabilizing at the end of each month aka "The Endgame", where they prepare the develop to be merged into master (branch names don't matter; insider / release, alpha / release all the same).

What you are asking them for is a weekly release cycle, a weekly planning cycle... which would change things on so many ends i wouldn't be able to accurately predict the impact and i would assume neither can the more active contributors...

As you can see simply through the existence of  0.X.1 Or 0.X.2 releases in the past, there already is a fast action plan in place allowing them to iterate small to hotfix something. We don't need a seperate release channel for that, especially if that potentially increases planning requirements a ton while simultaneously forcing contributors to edge down the integration process of their features to one week.

The latter is the biggest nono i see in your proposal. 
When a contributor has to be able to guarantee that his/her feature is stably integrated within one week i really doubt there'd be any community contributors who'd do large features.
Just look at some of the issues in this integration plan...

**Comment by ghiscoding** [comment]
I don't know where else to put this but would it be possible to close ticket on previous features that were half implemented? These 2 features have been pushed away for so long without any love
- [Editor Minimap](https://github.com/Microsoft/vscode/labels/editor-minimap) (30 opened issues)
- [Color Picker](https://github.com/Microsoft/vscode/labels/editor-color-picker) (20 opened issues)
   - this one in particular #33568 (when user start changing color the picker should not easily close)

**Comment by egamma** [comment]
@ghiscoding thanks for the feedback we will keep it in mind for future iteration planning. For now I suggest to vote on individual feature requests.

**Comment by egamma** [comment]
Closing - 1.24 has been shipped.
