### ISSUE TITLE
Iteration Plan for July 2018

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#53850]
This plan captures our work in **July**. This is a 5-week iteration. We will ship our July Update in **early August**.

Being in the Northerm Hemisphere, July is the first of our two Summer iterations that traditionally are a little bit lighter than the rest of the year. Many of us are out for a couple of weeks hanging out on beaches, climbing mountains, riding bikes, sleeping in the sun. We surely hope you will too.

Nevertheless, work will be done. In June we made good progress moving features out of preview. We are optimistic we can do the same for the alternative settings UI in July. We will make a user setup on Windows available, which does not require Administrator privileges to install. This setup package will provide a smoother background update experience on Windows. We also try to push the extension for GitHub pull requests so far that it's worthwhile to publish a preview in the extension marketplace.

We'll also use the Summer to look into improving accessibility of VS Code (keyboard navigation, screen reader support etc.) and make overall issue reduction a focus. The latter you already know from previous iterations. Having many actively engaged users on GH means high issue traffic and we always have to walk the delicate balance between being responsive to issues and getting sufficient focus time to get things done.

## Endgame
- **July 30th, 2018**: Code freeze for the endgame
- **August 3rd, 2018**: Endgame done

The endgame details for this iteration are tracked in #55349.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Accessibility
- [ ] :runner: Fix accessibility issues See [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22July+2018%22). @isidorn @ramya-rao-a **team**

### Workbench
- [ ] :runner: Continue to improve settings experience #3355 @roblourens
   - [ ] :runner: Explore settings editor improvements possible with additional metadata #51778 @roblourens @misolori
   - [x] Support rendering of backticks and links @roblourens #53911
   - [x] Improve `files.exclude` control @roblourens @misolori #53913
- [ ] :runner: Polish custom titlebar and menus on Windows ([titlebar query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+assignee%3Asbatten+milestone%3A%22July+2018%22+label%3Aworkbench-title)) ([menus query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+assignee%3Asbatten+milestone%3A%22July+2018%22+label%3Aworkbench-menu)) @sbatten
- [x] Improve global menu structure, e.g. the View menu @bpasero @misolori
- [x] Support to open a workspace from a URI #54483 @sandy081 @aeschli
- [x] 'bread-crumb' navigation #9418 @jrieken @misolori
- [x] Introduce a log file all telemetry events #54001 @ramya-rao-a
- [x] Simplify entering offline mode #54354 @ramya-rao-a
- [x] Explore how to support multi-line searches and search results @roblourens @misolori #13155
- [ ] :hand: :runner: :muscle: In Settings search, provide a way to show matching but not-installed extensions #49474 @roblourens

### Terminal

- [x] Keep renderer process in sync with pty @Tyriar #42234 #53974

### Install
- [x] Make user level install available; guide users to user level install @joaomoreno

### Problems Panel
- [x] Support quick fixing a problem from the Problems Panel #52627 @sandy081

#### Language Server Protocol
- [x] Support hierarchical document symbols [vscode-languageserver-node#3739](https://github.com/Microsoft/vscode-languageserver-node/issues/373) @dbaeumer
- [x] Support the preselect property for completion items [515](https://github.com/Microsoft/language-server-protocol/pull/515) @dbaeumer
- [x] Improve LSP inspector [query](https://github.com/Microsoft/language-server-protocol-inspector/milestone/1) @octref
- [x] Publish language aware folding support #45983 @aeschli
- [x] Explore improved support for language extension tests
octref/vscode-language-server-e2e-test#2 octref/vscode-language-server-e2e-test#3 @octref

#### JavaScript/TypeScript
- [x] Adopt TS version 3.0 #54845 @mjbvz
- As part of TS 3.0
   - [X] Support for auto closing JSX tags #34307 @mjbvz
   - [x] Support for Typescript project references #54104 @mjbvz
   - [X] Support for TS multi-location diagnostics #54102 @mjbvz
   - [X] Update third party notice. See [here](https://github.com/Microsoft/TypeScript/blob/master/ThirdPartyNoticeText.txt) #54103 @mjbvz

### Debug
- [x] Provide fine-grained support for smart-step Microsoft/vscode-chrome-debug-core#245 @roblourens @weinand
- [x] Improvements to Node Auto Attach behavior: remember mode #53586 @weinand
- [x] Don't force-kill debuggees on session end #54384 @weinand @isidorn 
- [x] Move 'loaded scripts explorer' into VS Code #37767 @weinand @isidorn

### Extension Contributions
- [x] Support several forthcoming PRs against the `xterm.js` project such as xtermjs/xterm-ligature-support#1 @tyriar
- [ ] :runner: Provide support for pull requests Microsoft/vscode-pull-request-github#1 @rmacfarlane @rebornix @shana @daviwil @sguthals
- [x] Improve end-2-end test coverage of the Vetur LS vuejs/vetur#802 @octref

### Extensions
- [x] Support for Extension Packs independent of the 'extensionDependencies' property #48430 @sandy081
- [x] Improve presentation and detail pages of built-in extensions #54098 @ramya-rao-a
- [x] Provide completion proposals in the search box of the Extensions view #46333 @jacksonkearl

### API
- Finalize API for
   - [x] `SearchProvider`, support to invoke find in files programmatically #47058 @roblourens
   - [x] Terminal API #52574 @tyriar
   - [x] Support for custom editor tab icons for webviews #48864 @mjbvz
   - [x] Compute definition locations #54101 @mjbvz
   - [x] Resource level workspace edits #10659 @jrieken
   - [x] Quick input improvements #53327 @chrmarti
   - [x] Protocol handler #48426 @joaomoreno
- Propose API
   - [x] Custom views, support decorations on items #47502 @sandy081

### Engineering
- [x] Adopt Electron 2.0 #48290 @bpasero @tyriar
- [x] Foundational work to remove `TPromise` from the code base #48290 @joaomoreno @jrieken
- [ ] :runner: Provide tooling for extracting telemetry event summary #54401 @kieferrm
- [x] Show a window layout 'preview' during startup #53871 @jrieken

### Documentation
- [x] Update intro videos for getting started and debugging https://github.com/Microsoft/vscode-docs/issues/1706 @auchenberg

-------

### Deferred Items
- Trigger characters for signature help #51731 @mjbvz (will come up with more complete api proposal for next iteration)
- Support downloading of additional resources when installing an extension #53855 @sandy081
- Tree widget optimizations for Outline @joaomoreno
- Explore fluent design options #32257 #52707 @sbatten @bpasero
- Finish read only workspace support (dynamically enable/disable) #53256 #53257 @isidorn
- Investigate into automated daily startup performance regression testing @jrieken
- more improvements for Node Auto Attach discoverability #53640 @weinand
