### ISSUE TITLE
Settings editor backlog

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#55791]
💯 - @JacksonKearl 
🤖 - @roblourens
✋ - Blocked (on 54039)
👁 - UX investigation
🐛 - bug-level change
❓ - Needs discussion or dev investigation

This is the master tracking issue for remaining settings editor tasks 🎉 

**Needs decisions made**
- [x] ❓💯 https://github.com/Microsoft/vscode/issues/55796 - New dropdown
- [x] 👁 https://github.com/Microsoft/vscode/issues/54140 - Context menu or gear button (like extension viewlet)
- [x] 👁 https://github.com/Microsoft/vscode/issues/55800 - Category format

**Opening**
- [x] 🤖 https://github.com/Microsoft/vscode/issues/50641 - Handle user/workspace/folder scoped settings correctly
  - The EditorInput must resolve to the setting model for the right scope
  - Maybe goes along with https://github.com/Microsoft/vscode/issues/55792
- [x] 🐛 https://github.com/Microsoft/vscode/issues/55375 - Add commands for opening the UI, .json, the setting-configured version
  - And decide on command IDs. Currently we only have `workbench.action.openSettings2`

**Search/filter**
- [x] 🤖 https://github.com/Microsoft/vscode/issues/55616 - "filter" mode should look like "search" mode
- [x] 🤖 https://github.com/Microsoft/vscode/issues/50652 - exact key match should show just that setting
  - json editor does this, do the same for new editor
- [x] 👁💯 https://github.com/Microsoft/vscode/issues/55615 - show "no results" message when search returns no results

**General UX**
- [x] 🤖 https://github.com/Microsoft/vscode/issues/56612 - Change "modified" text to indicator bar
- [x] 💯  https://github.com/Microsoft/vscode/issues/55804 - Intellisense for filters in search bar
- [ ] 🤖 https://github.com/Microsoft/vscode/issues/55795 - Scrollbar should be on far right edge

**Table of contents**
- [x] ✋ https://github.com/Microsoft/vscode/issues/55527 - Up/down navigation weirdness from syncing selection state btw trees
  - https://github.com/Microsoft/vscode/issues/55528 probably the same
- [x] 🐛 https://github.com/Microsoft/vscode/issues/53120 - Remove search modes besides 'filter'

**Setting row UX**
- [x] :bug: https://github.com/Microsoft/vscode/issues/56296 - Slow refresh
- [x] 🐛 https://github.com/Microsoft/vscode/issues/55797 - Show full setting description
- [x] 🐛 https://github.com/Microsoft/vscode/issues/55478 - Respect `description` vs `markdownDescription` and update all settings accordingly
- [x] 🐛 https://github.com/Microsoft/vscode/issues/55179 - Setting links don't work during search
- [x] ✋ https://github.com/Microsoft/vscode/issues/54053 - Bool setting label should be clickable
  - Makes sense once settings are no longer expandable
- [x] 🐛 https://github.com/Microsoft/vscode/issues/55695 - Setting links should use the formatted name, not the key
- [x] 🐛https://github.com/Microsoft/vscode/issues/56020 - Can't activate focused links with `<enter>`

**Setting schema**
- [ ] ❓ https://github.com/Microsoft/vscode/issues/51778 - Extending setting schema for extensions
  - Maybe let extensions add settings to groups

**Controls**
- [x] 💯 https://github.com/Microsoft/vscode/issues/55794 - Support some compound setting types like `null | something`
- [ ] ❓ https://github.com/Microsoft/vscode/issues/50704 - Square corners vs rounded corners, platform-specific, probably a larger issue
- [x] 💯 https://github.com/Microsoft/vscode/issues/55801 - Validation
  - [x] 💯 https://github.com/Microsoft/vscode/issues/55646 - Show deprecated settings with some hint
- [x] 🤖 https://github.com/Microsoft/vscode/issues/49474 - Button to see search results from other extensions

**Other**
- [x] 🤖 https://github.com/Microsoft/vscode/issues/55803 - Settings editor UI is slow to update and sometimes renders out of date values

**Accessibility**
- [x] 👉👉👉 https://github.com/Microsoft/vscode/issues/54039 - Decide once and for all, do we keep the model of "selecting" setting rows for navigation? It makes some things more complicated and maybe is not "typical", but is a very efficient way to navigate once you are used to it. Affects many other things.
  - If the point of the new settings editor is to be immediately familiar to new users, then maybe this model is too unexpected, judging by some feedback. 
- [ ] 🐛 https://github.com/Microsoft/vscode/issues/52464 - "clickable" 
- [ ] 🐛 https://github.com/Microsoft/vscode/issues/55799 - Trees have wrong tab order

**??**
- [x] 🐛 https://github.com/Microsoft/vscode/issues/54280 - Opening the explorer switches away from the settings editor to the selected file

**More issues**
- [x] https://github.com/Microsoft/vscode/issues/56928 - Underline links on hover
- [x] Show a notification the first time a user changes a setting - https://github.com/Microsoft/vscode/issues/57033
- [x] Change modified indicator ::after to real element so it can have a tooltip
- [x] Move 'reset setting' to the top of the context menu and remove "Copy Name"
- [x] Optimize settings list layout by loading elements in pages
- [ ] Add commands that implement "Focus next/previous setting control". e.g. cmd+down skips other focusable elements and focuses the next setting control in the list.
- [x] Persist the order of rows in the exclude control across edits.
