### ISSUE TITLE
Iteration Plan for August 2018 - EARLY DRAFT

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#55927]
This plan captures our work in **August**. This is a 4-week iteration. We will ship our August Update in **early September**. August is the second of our two Summer iterations. Those of us who didn't take time off earlier are doing so now.

Nevertheless, work will be done. We'll move the new settings experience out of preview and we'll publish a preview of the GitHub pull request extension. We'll also continue improving the accessibility of VS Code (keyboard navigation and screen reader support).

## Endgame
- **August 27th, 2018**: Code freeze for the endgame
- **August 31st, 2018**: Endgame done

The endgame details for this iteration are tracked in **TBD**.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Accessibility
- [ ] :runner: Fix accessibility issues (see [query](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22August+2018%22+)) @isidorn @ramya-rao-a **team**

### Workbench
- [ ] :runner: Continue to improve settings experience #3355 @roblourens
- [ ] Support `@` queries in the new settings experience @jacksonkearl
- [ ] :runner: Polish custom titlebar and menus (see [titlebar](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+assignee%3Asbatten+milestone%3A%22August+2018%22+label%3Aworkbench-title+label%3Aworkbench-menu) and [menus](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+assignee%3Asbatten+milestone%3A%22August+2018%22+label%3Aworkbench-menu) query) @sbatten
- [ ] Revisit layout of global menu bar @bpasero
- [ ] Finish read-only workspace support (dynamically enable/disable) #53256 #53257 @isidorn
- [ ] Polishing breadcrumbs interactions @jrieken
- [ ] Update interface overview @chrmarti

### Monaco Editor
- [ ] Provide an option to render whitespace in text selections #1477 @ramya-rao-a 

### Terminal
- [ ] Explore support for Window's conpty @tyriar

### Language Server Protocol
- [ ] Propose support for workspace resource edits @dbaeumer

### Debug
- [ ] Explore API for injecting a middle-man into DAP communication @weinand
- [ ] :runner: Improvements to Node Auto Attach to improve defaults and discoverability #53640 @weinand
- [ ] :runner: Move 'loaded scripts explorer' into VS Code #37767 @weinand @isidorn

### Extension Contributions
- [ ] :runner: Support PRs against `xterm.js` such as xtermjs/xterm-ligature-support#1 @tyriar
- [ ] :runner: Provide support for pull requests Microsoft/vscode-pull-request-github#1 @rmacfarlane @rebornix @shana @daviwil @sguthals
- [ ] Explore `vscode-tslint` as a TypeScript server plugin @mjbvz @egamma

### Extensions
- [ ] Add 'Show Recommended Extensions' to the Help menu @ramya-rao-a
- [ ] Explore support for extensions to download additional resources #53855 @sandy081

### API
- Finalize API for
   - [ ] :runner: Search Provider API https://github.com/Microsoft/vscode/issues/47058#issuecomment-406323909 @roblourens
   - [ ] Logging API https://github.com/Microsoft/vscode/pull/43276#issuecomment-373446670 @jrieken
   - [ ] Trigger characters for signature help #51731 @mjbvz
- Propose API
    - [ ] Disable auto-ident on completion item for space sensitive languages @jrieken
    - [ ] Support case-sensitive FileSystemProviders @isidorn
    - [ ] Allow extension to use the built-in git extension @joaomoreno

### Engineering
- [ ] `TPromise` removal (remove use of cancelation and progress support) #53526 @jrieken
- [ ] Investigate automated startup performance regression testing @jrieken
- [ ] Explore using webpack to bundle the git extension @jrieken
- [ ] Tree widget optimizations for Outline @joaomoreno
- [ ] Measure performance impact when search runs as an extension @roblourens
- [ ] :runner: Provide tooling for extracting telemetry event summary #54401 @kieferrm

### Documentation
- [ ] Update intro section and videos @auchenberg

-------

### Deferred Items
- :hand: In Settings search, provide a way to show matching but not-installed extensions #49474 @roblourens

**Comment by gmastergreatee** [comment]
Typo
![image](https://user-images.githubusercontent.com/17880848/44251053-a79e1180-a214-11e8-8005-1b2937e89d30.png)

**Comment by shanalikhan** [comment]
Guys, 
This issue https://github.com/Microsoft/vscode/issues/14444 needs your love.
This single thread have over 900 votes.

**Comment by myfairsyer** [comment]
There's an issue for the August endgame now: https://github.com/Microsoft/vscode/issues/57245

**Comment by egamma** [comment]
@myfairsyer thanks, updated the description with link to the endgame issue.

**Comment by myfairsyer** [comment]
> @myfairsyer thanks, updated the description with link to the endgame issue.

Thanks. I also filed a [PR for the Wiki page](https://github.com/Microsoft/vscode-wiki/pull/60)
