### ISSUE TITLE
Electron 3.0.x: Webview issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#56988]
Electron `3.0.0-beta.8` changed the `<webview>` implementation to "Out of Process Iframe". This issue tracks regressions found by that move.

* [ ] `<webview>` in some cases no longer emits `onfocus` events: an editor group no longer gets active when clicking into a webview (https://github.com/Microsoft/vscode/issues/56988#issuecomment-418677482)
* [ ] `<webview>` no longer prevents commands from the global menu to fire, thus resulting in 2 commands potentially triggering (macOS, https://github.com/Microsoft/vscode/issues/56988#issuecomment-419044926, https://github.com/electron/electron/issues/14514)
* [x] `<webview>` should not set a context key based on DOM focus but rather based on the active editor being a `webview` or not to prevent weird issues where the context key is not cleared properly
* [x] `<webview>` traps keydown events: our keybindings are broken once focus is within the webview (https://github.com/electron/electron/issues/14258) - fixed via https://github.com/Microsoft/vscode/commit/34a635e92d76ba58b2d0519c3fdc4fab8e7e1214
* [x] While a webview is visible, things like quick open or the custom menu close immediately after opened (https://github.com/electron/electron/issues/14259)

**Comment by bpasero** [comment]
@mjbvz fyi see my change in https://github.com/Microsoft/vscode/commit/34a635e92d76ba58b2d0519c3fdc4fab8e7e1214 to bubble out keyboard events from `<webview>` to our keybinding service.

**Comment by bpasero** [comment]
@mjbvz fyi see my change in https://github.com/Microsoft/vscode/commit/135032baf0501212be2dbdaa1d234b35132b78f8 to workaround the new focus behaviour of `webview`.

**Comment by bpasero** [comment]
There is still lots of flakiness in `<webview>` with regards to focus. It seems that the fact that we use an `<iframe>` within the `<webview>` makes proper focus/blur detection harder. 

I think the context key in `webviewElement.ts` should not work with focus/blur but rather just be enabled when the active editor is a `<webview>` editor. Ideally we do not have to rely on focus/blur at all for the commands (select all, find) to work.

**Comment by bpasero** [comment]
I pushed another comment to move away from DOM.trackFocus() for the webview element and rather send an explicit event. 

There is still focus issues when doing this:
* install `negokaz.live-server-preview-0.1.2`
* open a empty HTML file and type some words
* open preview to the side
* click between editor and right hand preview

=> at one point focus is no longer detected

**Comment by bpasero** [comment]
Another issue (macOS):
* open one editor (markdown)
* open preview to the side
* hit `Cmd+W` to close
* => both editors close

It looks like both the `Cmd+W` is fired from within the `webview` as well as the `File > Close Editor` menu entry from the global menu.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/commit/c47790a7289238da605ca0ff8f19dc6fc8bdd551 changes to not rely on DOM focus/blur for context keys in the `webview`.

**Comment by bpasero** [comment]
I have extracted https://github.com/Microsoft/vscode/issues/64724 into its own issue.
