### ISSUE TITLE
Iteration Plan for September 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#58224]
This plan captures our work in **September**. This is a 4-week iteration. We will ship our September Update in **early October**. As mentioned in [July](https://github.com/Microsoft/vscode/issues/53850) having many actively engaged users means high GitHub issue traffic, and we always have to walk the delicate balance between being responsive to issues and getting sufficient focus time to get things done. Now, it's this time of the year again, the time we tip the balance toward issue grooming.

We'll go through all of our issues in all our [repositories](https://github.com/Microsoft/vscode/wiki/Related-Projects), ensure all issues are labeled correctly and have the correct owners, close duplicates, fix bugs. This time, we'll also think about reducing the number of open feature requests. At the time of writing, we have [more than 3000 open feature requests](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3Afeature-request). For you and us it would be better if the set of open feature requests is more reflective of what has a chance to be considered within the next 12 - 24 months.

So, if all of a sudden you see a lot of GitHub notifications, don't get scared.

## Endgame
- **September 24th, 2018**: Code freeze for the endgame
- **September 28th, 2018**: Endgame done

The endgame details for this iteration are tracked in #59271.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Accessibility
- [ ] :runner: Fix accessibility issues (see [query](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22September+2018%22+)) @isidorn @ramya-rao-a **team**
add
### Github Issue Housekeeping
- [x] Issue/PR Grooming - review, categorization, assignment #58336 @Microsoft/vscode

### Workbench
- [x] Make custom menus the default on Windows #29997 #29024 @sbatten

#### TypeScript/JavaScript
- [x] Adopt TS 3.1 #58994 @mjbvz

### Debug
- [x] Explore API for injecting a middleman into DAP communication #55945 @weinand

### Extension Contributions
- [x] Support exploration of performance improvements in `xterm.js` xtermjs/xterm.js#791 @tyriar 
- [x] Adopt go's new module feature in `vscode-go` Microsoft/vscode-go#1532 @ramya-rao-a
- [x] GitHub PR extension: bug fixing and support for multi-root-folder workspaces. See [query](https://github.com/Microsoft/vscode-pull-request-github/milestone/2 ). @rmacfarlane @rebornix @shana

### API
- Propose API
    - [x] Allow text search providers to show the `maxResults` indicator after a custom number of results #55790 @roblourens
    - [x] API for editing and deleting document comments #58078 @rmacfarlane
    - [x] Add the ability to pass "post extension install" query parameters #57636 @joaomoreno @sandy081

### Engineering
- [x] Continue preparation of adopting Electron 3.0 (includes local storage, webview migration) @bpasero @tyriar #52629
- [x] Webpack built-in extensions #57680 @jrieken
- [x] Explore showing issues by type summary on our GitHub readme page @kieferrm @tyriar
- [x] Restrict build badge to CI builds on `master` @joaomoreno
- [x] Use `spdlog` for output channels straight from the extension host #57618 @sandy081
- [x] Remove WinJS.Promise#cancel usage #56137 @jrieken

### Documentation
- [x] Devise plan how to improve our documentation for extension authors #58226 @octref @weinand @gregvanl @jrieken **team**

-------

### Deferred Items
None.

**Comment by anthcool** [comment]
#5953

**Comment by anthcool** [comment]
#5953 Please add this to the your plans if possible.  Thanks!  Would be nice to even hear something from a contributor on if there's any hope of getting File > Print added.  Thanks again!

**Comment by beastdestroyer** [comment]
@kieferrm Add the endgame

**Comment by xyzdata** [comment]
# that's great!

**Comment by glekner** [comment]
Is Mojave Dark mode supported yet? heard its in the Insider build.
