### ISSUE TITLE
Iteration Plan for October 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#60106]
This plan captures our work in **October**. This is a 5-week iteration. We will **ship** our October Update **in early November**. After this iteration, there will be one more iteration this year. It will also be 5 weeks long, and we'll ship the November Update in the first half of December.

After our focus was limited on issue housekeeping, we now also look at features again. For example, we'll work on dynamic menubar and multi-line search support, and we'll explore more flexible workbench layouts. We also keep improving the GitHub Pull Request extension so that we are ready to meet you at [Github Universe](https://githubuniverse.com/program/#cross-company-collaboration-colon-extending-github-to-a-new-ide).

## Endgame

- **October 29th, 2018**: Code freeze for the endgame
- **November 2nd, 2018**: Endgame done

The endgame details for this iteration are tracked in #62045.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Accessibility

- [x] Improve screenreader support for focus changes in terminals #52304 @alexr00 @tyriar
- [x] Improve tabbing order in extensions view in screenreader mode #51496 @ramya-rao-a @sandy081

### Workbench

- [x] Provide dynamic menubar support on all platforms #58928 #59936 @sbatten
- [x] Add support for multi-line file search #13155 @roblourens
- [x] Improve sidebar/panel navigation #59858 @octref
- [x] Improve centered layout #53989 @isidorn
- [x] Support option to emphasize modified editor tabs more #26284 @bpasero
- [ ] :runner: Explore a viewlet that shows search reference results #22261 @jrieken
- [ ] :runner: Explore flexible panel/sidebar layout #50853 @sbatten @joaomoreno
- [x] Notifications - Revisit when a notification persists or disappears (related #51013 #46571) @bpasero
- [x] Support for 'Simple Full Screen' mode on OS X (do not open a new 'space') #5344 @bpasero

### Terminal

- [x] Support maintaining context when splitting terminals #48447 @alexr00
- [ ] :runner: :muscle: Support `conpty` on Windows #45693 @tyriar

### Tasks

- [x] Add new setting for clearing terminal when running a task #30058 @alexr00
- [ ] :runner: New command for rerunning last task with same variables #25310 @alexr00

### Source Control

- [x] Allow `SourceControl` implementations to hide the `SourceControlInputBox` #51808 @joaomoreno

### Languages

- [x] Use icons from file icon themes for completion items of kind `file` #44860 @jrieken

#### JavaScript/TypeScript

- [ ] :runner: Adopt TypeScript maintenance release 3.1.x #60814 @mjbvz

### Debug

- [x] Multiple debug consoles, switch between outputs #31377 @isidorn
- [x] Collapse skipped stack frames into one node #50334 @isidorn
- [x] LoadedScripts View support to show related resources, e.g. TS source for JS scripts #62034 @weinand
- [x] Investigate in webpacking the node-debug extension #59237 @weinand @jrieken @roblourens
- [x] <kbd>F10</kbd> and <kbd>F11</kbd> should start debugging with `stopAtEntry:true` #49855 @isidorn

### Extension Contributions

- [ ] :runner: Migrate `vscode-tslint` to use tslint as a TS server plugin Microsoft/typescript-tslint-plugin#1 @mjbvz
- [x] GitHub PR extension Microsoft/vscode-pull-request-github#544 @rebornix @rmacfarlane
- [ ] :runner: Sheppard performance improvement PRs through `xterm.js` xtermjs/xterm.js#791 @tyriar

### Extensions

- [x] Provide sample search extension to get feedback on performance and API #60207 @roblourens

### API

- [x] Custom tree view: Proposed API to expand/collapse tree items #55879 @sandy081
- [x] Custom tree view: Proposed API to support partial highlight of tree item labels #61313 @sandy081
- API finalization: [query](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+milestone%3A%22October+2018%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?utf8=✓&q=is%3Aissue+is%3Aopen+milestone%3A%22October+2018%22+label%3A%22api-proposal%22+)

### Engineering

- [x] Electron 2.0.11 adoption #60143 @bpasero @tyriar
- [ ] :runner: Continue Electron 3.0 adoption, migrate local storage #52629 @bpasero
- [x] :red_circle: Tree widget performance improvements & filtering support @joaomoreno
- [x] Adopt new tree widget in Problems view @joaomoreno @sandy081
- [ ] :runner: WinJS.Promise removal #53526 @jrieken **team**
- [ ] :runner: :muscle: Strict null checking VS Code #60565 @mjbvz **team**
- [ ] :red_circle: Perf - investigate into web pack bundling support for extensions @jrieken

### Documentation

- [x] Overhaul extensibility documentation Microsoft/vscode-docs#1949 @octref **team**
- [x] Normalize samples Microsoft/vscode-extension-samples#110 @octref **team**

---

### Deferred Items

- [ ] Allow for case-sensitive/insensitive file system providers #48258 @isidorn

**Comment by ryenus** [comment]
Is it possible to propose https://github.com/Microsoft/vscode/issues/42880 which allows quick navigation across recently edited files? Thank you!

**Comment by MartinSGill** [comment]
I'm fairly sure you meant 'shepherd' not Sheppard.

**Comment by Aamir2000** [comment]
No New Features In This Update Just Fixing And Migration To Electron 3.0 ???? No New Features Are Going To Added ?????

**Comment by Eskibear** [comment]
> Engineering
> 🔴 Tree widget performance improvements & filtering support

I think the issue ref is https://github.com/Microsoft/vscode/issues/50062

**Comment by joaomoreno** [comment]
Actually it's https://github.com/Microsoft/vscode/pull/59976

**Comment by mjbvz** [comment]
1.29.0 has shipped
