### ISSUE TITLE
May Iteration Plan

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#6105]
This plan captures what we **work on during May** and will **ship early June**.

We arrived at the following themes for May:
* Work on highly requested UI features (tabs, integrated terminal).
* Make a repository with the Monaco/standalone editor available.
* Continue to do some UI explorations.

The [May Test Plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+label%3Atestplan-item+milestone%3A%22May+2016%22) are created as issues get closed.

For more information about our development process please refer to the development process [page](https://github.com/Microsoft/vscode/wiki/Development-Process).

### Schedule
The goal is to make the May update available by the following dates.

End game dates (we end an iteration with an [endgame](https://github.com/Microsoft/vscode/wiki/Development-Process#end-game))

##### Monday, May 23
- [x] Code freeze at end of day
- [x] Test plan input done at 9 pm Zurich time
- [x] Prepare blog post about more frequent update of `insider` channel

##### Tuesday, May 24
- [x] Test plan ready
- [x] Test build done
- [x] Testing

##### Wednesday, May 25
- [x] Testing
- [x] Fixing

##### Thursday, May 26
- [x] Fixing
- [x] Run OSS tool
- [x] Verification
- [x] Update release notes

##### Friday, May 27
- [x] Fixing (only critical bugs)
- [x] Smoketest
  - [x] Windows - @alexandrudima  
  - [x] OS X - @sandy081  
  - [x] Linux - @joaomoreno 
- [x] All release notes updated 
  - [x] @aeschli
  - [x] @alexandrudima 
  - [x] @dbaeumer 
  - [x] @stevencl  
  - [x] @jrieken 
  - [x] @joaomoreno 
  - [x] @isidorn 
  - [x] @egamma 
  - [x] @sandy081 
  - [x] @Tyriar 
  - [x] @weinand
- [x] Acknowledge pull requests in release notes - All 
- [ ] All issues verified
- [ ] Satellite modules ready, version updated, smoke tested
  - [x] vscode @bpasero 
  - [ ] yo generator @aeschli 
  - [x] vsce @joaomoreno 
  - [x] node debug @weinand 

##### Monday, May 30
- [x] build `insider` release
- [x] sanity check `insider` release
  - [x] Windows - @dbaeumer 
  - [x] OS X - @joaomoreno 
  - [x] linux - @weinand 
- [x] Release `insider` channel

##### Monday, June 6
- [x] build `stable` release
- [x] sanity check `stable` build
  - [x] Windows - @sandy081  
  - [x] OS X - @jrieken  
  - [x] linux - @weinand 
- [x] Release `stable` channel - **Redmond**

##### Tuesday, June 7
- [ ] Change `insider` channel to take over role from `alpha`
- [ ] Retire `alpha` channel

### Plan Items

| Mark  | Description |
| ------------- | ------------- |
| :runner:  | work in progress  |
| :hand:  | task is blocked  |
| :muscle:  | stretch goal for this iteration  |

#### Debt Items

This section lists items to reduce our engineering debt:

- [ ] :runner::muscle: Extract the MarkDown editing support into an extension  #6106 @kieferrm 

#### Feedback

Issues to address feedback from the community:
- [x] :runner: UI - Tabs - support stacks in editor groups, expose stacks in an `open editors` pane (was working files)  #224 @bpasero @isidorn 
    - Test #6536 
    - [x] Release notes
- [x] UI - Add an integrated terminal #143 @Tyriar
    - Test #6654 
    - [x] Release notes
- [x] :runner: Editor - Support that the Monaco editor can be consumed standalone @alexandrudima
  - Define 1.0 version of the API
  - Support to contribute new language outside of the editor source tree
  - Test #6655 
  - [x] Release notes
- [x] API - Expose the diff editor in the API #1865 @jrieken
    - Test #6648
    - [x] Release notes
- [x] CSS: Variables should offer same support as SASS/LESS variables #3077 @sandy081 
    - Test #6656
    - [x] Release notes
- [x] Install - Support to install/update an extension from the command line #691 @joaomoreno 
    - Test #6099
    - [x] Release notes
- [x] UI - Intellisense support to disable word completions, to address #5574 @jrieken
    - Test #6650
    - [x] Release notes
- [x] Debug - Support to start a debug session from an extension: #4615 @isidorn
    - Test #6248 
    - [x] Release notes 
- [x] vscode-eslint support a "fix all" action @dbaeumer 
    - Test #6581 
    - [x] Release notes 
- [x] vscode-tslint support quick fixing of warnings same as in vscode-eslint @egamma
    - Test #6700
    - [x] Release notes

#### Engineering

This section lists several engineering/development items that the team identified:
- [x] API - Add documentation for virtual document support and provide a sample @jrieken 
    - Test #6675
    - [x] Release notes 
- [x] JSON - Support to rewrite JSON configuration files programmatically @aeschli 
    - Test #6657
- [x] Debug - support a all "One Thread" and "All Thread" model @isidorn @weinand
    - Test #6160  
    - [x] Release notes   
- [x] Debug - Slow call stack response for TS repository #5645 @weinand
    - Test #6658 
    - [x] Release notes  
- [x] Debug - Node v6 debugging support  #6029 @weinand 
    - Test #6659 
    - [x] Release notes  
- [x] Debug - Introduce "Reveal" setting for debug console #6159 @isidorn  
    - Test #6159  
    - [x] Release notes  
- [x] :runner: Improve story for markers generated by a task and markers generated by a language service @dbaeumer
    - See proposal here: https://github.com/Microsoft/vscode/issues/6973
- [x] Linter/language protocol support a trace option @dbaeumer 
    - Test #6580 
    - [x] Release notes 
- [x] Telemetry - Explore shared telemetry implementation with VS #4792 @jrieken 
    - Test #6246 
    - [x] Release notes

#### Explorations
- :runner: UI - Improve extension installation UI #637 @joaomoreno
- :runner: UI - Move the error list from the quick box to a panel @Sandeep 

#### Deferred from May
- Configuration - Help getting started with configuring the Code preferences @aeschli
- UI - Indent guides #2192 @alexandrudima @aeschli 
- :running: Debug - Debugging with babel-register (dynamic sourcemaps) + NodeJs does not work #5728 @weinand 
- UI Open custom terminal for OS X #5462 @Tyriar
- UI - Support to increase the font size used by IntelliSense #2465 @joaomoreno 

## Bugs
Bugs assigned to the current milestone:
- [vscode](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Abug+-label%3Aupstream+milestone%3A%22May+2016%22)

**Comment by daviwil** [comment]
This is going to be an amazing release!

**Comment by Alexisvt** [comment]
This already is amazing!!!! Thanks!!! :smile_cat:
