### ISSUE TITLE
Iteration Plan for November 2018

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#62876]
This plan captures our work in **November**. This is a 5-week iteration. We will **ship** our November Update - the last of the year - **in the first half of December**. As in 2018, there will be no update in early January 2019. The next major update will be in early February 2019.

We have a full plan stretching from polishing functionality that we introduced earlier such as reference lists and multi-line search, to smaller productivity features such as `Commit & Push`, all the way to getting ready for electron 3.0 and adopting the new tree implementation throughout our code base. We also start exploring what it takes to make developing on WSL on Windows more natural. Some of us will also eat a lot in the middle of the iteration.

## Endgame

- **December 3, 2018**: Code freeze for the endgame
- **December 7, 2018**: Endgame done

The endgame details for this iteration are tracked in #64182.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Workbench

- [ ] :runner: Explore flexible panel/sidebar layout https://github.com/Microsoft/vscode/issues/50853 @sbatten @joaomoreno
- [x] Polish viewlet that shows search reference results https://github.com/Microsoft/vscode/issues/22261 @jrieken
- [x] Improve multiline search experience https://github.com/Microsoft/vscode/issues/62304, https://github.com/Microsoft/vscode/issues/62961 @roblourens
- [x] Support overflow in custom menubar and menus https://github.com/Microsoft/vscode/issues/52533 https://github.com/Microsoft/vscode/issues/57756 @sbatten
- [x] Enable custom menubar on Linux by default https://github.com/Microsoft/vscode/issues/62727 @sbatten
- [x] Improve rendering of diagnostics in hovers and F8 https://github.com/Microsoft/vscode/issues/62370 @sandy081
- [x] Explore deprecating the old settings editor https://github.com/Microsoft/vscode/issues/62964 @roblourens

### UX

- [x] Explore streamlining design for hovers, completion items, signature help https://github.com/Microsoft/vscode/issues/63144 @misolori
- [x] Explore welcome page improvements https://github.com/Microsoft/vscode/issues/63152 @misolori

### Monaco Editor

- [x] Publish a new editor version @alexandrudima

### Tasks

- [x] Support input parameters for Tasks https://github.com/Microsoft/vscode/issues/4758 @alexr00
- [x] Support to start a task automatically https://github.com/Microsoft/vscode/issues/17147 @alexr00
- [x] Explore to automatically attach problem matcher when running in the terminal https://github.com/Microsoft/vscode/issues/62937 @alexr00

### Source Control

- [x] Support one-step action `Commit & Push` https://github.com/Microsoft/vscode/issues/62058 @joaomoreno
- [x] Provide option to open file on single click from SCM viewlet https://github.com/Microsoft/vscode/issues/63005 @joaomoreno

### Languages

- [ ] :runner: Improve expand selection support https://github.com/Microsoft/vscode/issues/4795 @jrieken
- [x] Add "Go to Declaration" feature #62483 @jrieken
- [x] Add `go-to-declaration` request to LSP https://github.com/Microsoft/language-server-protocol/issues/605 @dbaeumer

#### JavaScript/TypeScript

- [x] Adopt TS version 3.2 @mjbvz https://github.com/Microsoft/vscode/issues/63179
- [x] Allow VS Code extensions to configure TS Server plugins https://github.com/Microsoft/vscode/issues/63181

#### CSS/HTML
- [ ] :runner: Support custom tags and properties in HTML and CSS https://github.com/Microsoft/vscode/issues/62976 @octref

### Debug

- [x] Loaded Scripts view improvements (observing changes, explore filtering based on new tree) https://github.com/Microsoft/vscode/issues/62939 @weinand
- [x] Polish multi-debug console support https://github.com/Microsoft/vscode/issues/62419 https://github.com/Microsoft/vscode/issues/62418 https://github.com/Microsoft/vscode/issues/62420 @isidorn
- [x] Explore supporting data break points https://github.com/Microsoft/vscode/issues/58304 @weinand
- [x] Explore minimal multi-step quick pick providing guidance for creating launch configs https://github.com/Microsoft/vscode/issues/62851 @isidorn
- [x] Investigate issues with debugging apps generated with `create-react-app` https://github.com/Microsoft/vscode/issues/60187 @roblourens
- [x] Enable Smart Step by default https://github.com/Microsoft/vscode/issues/62965 @roblourens

### Extension Contributions

- [ ] :runner: Migrate `vscode-tslint` to use tslint as a TS server plugin https://github.com/Microsoft/typescript-tslint-plugin/issues/1 @mjbvz
- [x] GitHub PR extension https://github.com/Microsoft/vscode-pull-request-github/issues/678 @rebornix @rmacfarlane

### Extensions

- [x] Support installing the previous version of an extension https://github.com/Microsoft/vscode/issues/12764 @sandy081

### API

- [x] Help extensions moving off the `htmlPreview` https://github.com/Microsoft/vscode/issues/62630 command @mjbvz
- [x] Explore alternatives to `FileIndexProvider` https://github.com/Microsoft/vscode/issues/59922 @roblourens
- API finalization: [query](https://github.com/Microsoft/vscode/issues?utf8=âœ“&q=is%3Aissue+is%3Aopen+milestone%3A%22November+2018%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?utf8=âœ“&q=is%3Aissue+is%3Aopen+milestone%3A%22November+2018%22+label%3A%22api-proposal%22+)

### Serviceability

- [x] Identify extensions causing the extension host to be unresponsive, provide support for generating a CPU profile, hint user about the performance problem caused by the extension. https://github.com/Microsoft/vscode/issues/60332 @jrieken
- [x] Support to start debugging directly from within the process explorer https://github.com/Microsoft/vscode/issues/63147 @rmacfarlane

### Exploration

- [ ] :runner: Explore support for developing on WSL https://github.com/Microsoft/vscode/issues/63155 @alexandrudima **team**

### Engineering

- [x] Continue Electron 3.0 adoption, migrate local storage https://github.com/Microsoft/vscode/issues/52629 @bpasero
- [x] WinJS.Promise removal https://github.com/Microsoft/vscode/issues/53526 @jrieken **team**
- [ ] :runner: Strict null checking VS Code https://github.com/Microsoft/vscode/issues/60565 @mjbvz **team**
- [x] Document new Tree widget implementation (https://github.com/Microsoft/vscode/wiki/Lists-And-Trees) @joaomoreno
- Support the adoption of the new Tree widget @joaomoreno
   - [ ] :runner: Adopt new tree widget in Search @roblourens
   - [ ] :runner: Adopt new tree widget in Settings @roblourens
   - [x] :runner: Adopt new tree in peek references ui @jrieken https://github.com/Microsoft/vscode/issues/63904
   - [ ] :runner: Adopt new tree widget Outline @jrieken
   - [x] :runner: Adopt new tree widget in the debugger @isidorn, @weinand

### Documentation

- [ ] :runner: Continue extensibility documentation improvements https://github.com/Microsoft/vscode-docs/issues/2199 @octref **team**

---

### Deferred Items

- Revisit the explorer context menu (cut, duplicate, open folder) https://github.com/Microsoft/vscode/issues/61110 @isidorn @bpasero
- :muscle: Explore flatting folder hierarchies in the explorer https://github.com/Microsoft/vscode/issues/41627 @isidorn @joaomoreno
- Explore Debug API: Debug Config Provider to return launch configurations dynamically https://github.com/Microsoft/vscode/issues/54212 @weinand
- Adopt new tree widget in the workbench @isidorn
- Support a post install/update hook for extensions https://github.com/Microsoft/vscode/issues/23251 @sandy081 @joaomoreno
- Explore generalizing NPM Script Explorer into a Task runner view https://github.com/Microsoft/vscode/issues/28235 @alexr00
- :muscle: Use browser logic for improved word navigation in CJK https://github.com/Microsoft/vscode/issues/50045 @rebornix
- Explore impact of Webview changes in electron 3.0 on extensions @mjbvz https://github.com/Microsoft/vscode/issues/63180
- :muscle: Revisit Javascript end user documentation @mjbvz @gregvanl https://github.com/Microsoft/vscode-docs/issues/2190

**Comment by beastdestroyer** [comment]
Explore welcome page improvements  #56144

**Comment by BartolomeSintes** [comment]
Please, don't remove the old settings editor (last item in the workbench section of this month's plan). It is easier to copy and paste all the settings at once (from one workspace to another) than modify one by one.

**Comment by roblourens** [comment]
We will never get rid of editing settings with a JSON file. The issue is just about the UX we have around the json settings editor (pencil icon to edit, search bar, etc).

**Comment by vSanjo** [comment]
The search bar is a little annoying in `settings.json` view. I'd rather be looking through my settings I've set over the settings I have available. Perhaps a toggle between the two?

**Comment by jtcontreras90** [comment]
```markdown
CSS/HTML
- [ ] Support **support** for custom tags and properties in HTML and CSS #62976 @octref
```

**Comment by myfairsyer** [comment]
There's an issue for the endgame: https://github.com/Microsoft/vscode/issues/64182

**Comment by kieferrm** [comment]
Shipped.
