### ISSUE TITLE
Tree: features for debug

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#63783]
Here's the list of things which are currently missing in our new tree implementation for debug use cases:
- [x] `WorkbenchDataTree` which takes into account theming, keyboard shortcuts. DataTreeResourceNavigator should get the `WorkenchDataTree`
- [x] double click and context menu click on empty area #63598
- [x] IdentityProvider support so the expanded elements are kept expanded #63149
- [x] new tree: returning "recurse" from filter does not work #63952
- [x] need a better way to try to expand elements that are not there
- [x] Features needed for debug console
  - [x] Have an option for the twistie vertical position
  - [x] Option for the mouse to not select and focus but still trigger context menu and expand (also need this for debug hover)
  - [x] I need `getScrollPosition` and `setScrollPosition`. Currently I need it for: users adds a new repl input -> whole repl gets refreshed, I need to figure out if I should reveal the end, I do that only if the end was previously revelied
  - [x] I need to navigate through all the visible elements to get their content for Copy All action. I can expose getNode and than go over all looking at the `expanded` property
- [x] DataTreeResourceNavigator, @weinand already did an initial implementation
- [x] `onChangeCollapseState` fired before children count is taken into account for debug hover

:muscle: 

- [ ] Drag and drop support for watch expressions #63762
- [ ] Horizontal scroll for debug hover #63684

fyi @weinand

**Comment by weinand** [comment]
@joaomoreno I've added a new issue "new tree: returning "recurse" from filter does not work #63952" to the list and unchecked the "IdentityProvider" because it does not work.

**Comment by joaomoreno** [comment]
@isidorn Closing this for now as the :muscle: items are issues in themselves.
