### ISSUE TITLE
Explorer new tree adoption

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#64799]
Explorer needs to adopt to the new tree. I plan to keep this issue updated with tree features which are missing for the explorer:

- [ ] Drag and drop #63762
- [ ] Filtering, [example](https://github.com/Microsoft/vscode/blob/55cbf197b483d644bb8ac32ed03c14ea94638ad8/src/vs/workbench/parts/files/electron-browser/views/explorerViewer.ts#L699) what is now done. I think the new tree also supports filtering, so just need to check if everything is there
- [ ] Highlight, when a file is being renamed or a new file is added the rest of the tree blurs out https://github.com/Microsoft/vscode/issues/64886
- [ ] Auto expand single children #64888
- [ ] Customised sort order #63148

**Comment by isidorn** [comment]
@joaomoreno let me know if you prefer that I keep all the issues here, or you would like that I file seperate issues for each request. Thanks

**Comment by joaomoreno** [comment]
Isolated issues, please. Also, always search for `tree` issues before filling.

**Comment by isidorn** [comment]
Clsoing this in favor of isolated issues, and the list of things needed I will keep in this PR https://github.com/Microsoft/vscode/pull/65008
