### ISSUE TITLE
Iteration Plan for January 2019

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#65570]
This plan captures our work in **late December** and **January**. Although longer, we treat this iteration as a 4-week iteration because most of us will have time off over the holidays, and it will take us a little bit to get going again once we are back. We will **ship** our January Update in **in early Feburary**.

## Endgame

- **January 28, 2019**: Code freeze for the endgame
- **February 1, 2019**: Endgame done

The endgame details for this iteration are tracked in https://github.com/Microsoft/vscode/issues/67225.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Roadmap

- [x] Publish the [2019 roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) @egamma @kieferrm

### Workbench

- [x] Provide preview of flexible panel/sidebar layout https://github.com/Microsoft/vscode/issues/50853 @sbatten @joaomoreno
- [x] Support multi-line diagnostics messages in the Problems panel https://github.com/Microsoft/vscode/issues/1927 @sandy081
- [x] Navigate through explorer by typing start of file/folder name https://github.com/Microsoft/vscode/issues/10026 @isidorn
- [x] Revisit the explorer context menu (cut, duplicate, open folder) https://github.com/Microsoft/vscode/issues/61110 @isidorn @bpasero

### UX

- [x] Update Octicons https://github.com/Microsoft/vscode/issues/65508 @misolori
- [ ] :runner: Iconography re-design https://github.com/Microsoft/vscode/issues/8017 @misolori

### Terminal

- [x] Support `conpty` on Windows https://github.com/Microsoft/vscode/issues/45693 @tyriar
- [x] Reflow text when terminal is resized https://github.com/Microsoft/vscode/issues/23688 @tyriar
- [x] Improve accessibility of the terminal https://github.com/Microsoft/vscode/issues/59794 @tyriar

### Languages

- [ ] :runner: Support semantic selections https://github.com/Microsoft/vscode/issues/4795 @jrieken
- [ ] :runner: Support semantic selections in LSP https://github.com/Microsoft/language-server-protocol/issues/613 @dbaeumer
- [x] Provide feedback on [LSP tutorial](https://github.com/donaldpipowitch/how-to-create-a-language-server-and-vscode-extension) @dbaeumer @octref

#### JavaScript/TypeScript

- [x] Adopt TypeScript 3.3 https://github.com/Microsoft/vscode/issues/66175 @mjbvz

#### JSON

- [x] Support semantic selections in JSON https://github.com/Microsoft/vscode/issues/67232 @aeschli

#### CSS/HTML

- [x] Improve custom tags and properties in HTML https://github.com/Microsoft/vscode/issues/62976 @octref
- [x] Provide custom properties in CSS https://github.com/Microsoft/vscode/issues/64164 @octref
- [x] Support semantic selections in CSS and HTML https://github.com/Microsoft/vscode/issues/65925 @octref

### Debug

- [x] Add support for data break points in the Debug Adapter Protocol https://github.com/Microsoft/debug-adapter-protocol/issues/20 @weinand
- [x] Fully support input arguments for command variables in launch configs https://github.com/Microsoft/vscode/issues/64362 @weinand
- [x] Explore Debug API: Debug Config Provider to return launch configurations dynamically https://github.com/Microsoft/vscode/issues/54212 @weinand

### Install

- [x] Linux: Provide daily insider snaps @joaomoreno

### Extension Contributions

- [ ] :runner: Migrate `vscode-tslint` to use tslint as a TS server plugin https://github.com/Microsoft/typescript-tslint-plugin/issues/1 @mjbvz
- [x] GitHub PR extension https://github.com/Microsoft/vscode-pull-request-github/issues/762 @rmacfarlane @rebornix
- [x] Azure Account Extension: improve login flow https://github.com/Microsoft/vscode-azure-account/issues/75 @chrmarti

### Extensions

- [x] Explore impact of Webview changes in electron 3.0 on extensions @mjbvz https://github.com/Microsoft/vscode/issues/63180
- [x] Investigate to activate extensions after install without window reload @alexandrudima @sandy081 https://github.com/Microsoft/vscode/issues/66199
- [ ] :runner: Support to install native dependencies when an extension is installed https://github.com/Microsoft/vscode/issues/23251 @sandy081
- [x] `vsce` should block publishing extensions that use `vscode` as a dependency (should always be a `devDependency`) https://github.com/Microsoft/vscode-vsce/issues/319 @joaomoreno

### API

- [x] Address "`DefinitionLink:targetSelectionRange` not working as expected" https://github.com/Microsoft/vscode/issues/58649 @jrieken
- [x] Investigate generalized support for 'Fix All' https://github.com/Microsoft/vscode/issues/62110 @mjbvz

### Exploration

- [ ] :runner: Explore support for developing on WSL https://github.com/Microsoft/vscode/issues/63155 **team**

### Engineering

- [x] Electron 3.0 upgrade https://github.com/Microsoft/vscode/issues/52629 @bpasero
- [ ] :runner: Explore Electron 4.0 upgrade https://github.com/Microsoft/vscode/issues/61787 @bpasero
- [ ] :runner: Strict null checking VS Code https://github.com/Microsoft/vscode/issues/60565 @mjbvz **team**
- [x] Show startup performance times inside an editor https://github.com/Microsoft/vscode/issues/65400 @jrieken
- Support the adoption of the new Tree widget @joaomoreno
   - [x] Adopt new tree widget in the Explorer @isidorn
   - [x] Adopt new tree widget in the Peek widget @jrieken
   - [x] Adopt new tree widget in Search @roblourens
   - [x] Adopt new tree widget in Settings @roblourens

### Documentation

- [x] Publish new extensibility documentation https://github.com/Microsoft/vscode-docs/issues/2199 @octref **team**
- [ ] :runner: Revisit Javascript end user documentation https://github.com/Microsoft/vscode-docs/issues/2190 @mjbvz @gregvanl

---

### Deferred Items
- :muscle: Use browser logic for improved word navigation in CJK https://github.com/Microsoft/vscode/issues/50045 @rebornix
- :muscle: Explore flatting folder hierarchies in the explorer https://github.com/Microsoft/vscode/issues/41627 @isidorn @joaomoreno
- Improve Vetur roadmap @octref
- Add support for custom execution in addition to ShellExecution and ProcessExecution @alexr00
- :muscle: Welcome page improvements https://github.com/Microsoft/vscode/issues/63152 @chrmarti @misolori

**Comment by beastdestroyer** [comment]
Explore upgrade to Electron 4 is #61787 ?

**Comment by NateLing** [comment]
happy new year .
