### ISSUE TITLE
UX Backlog

### ISSUE THREAD

**Issue by misolori** [Microsoft/vscode#66299]
# Intro
This backlog is a collection of items related to the user experience of the product. Design will use this list as a discussion point for iteration planning as well as discussions with the team during our weekly ux sync. Additionally, we will use our [design principles](https://github.com/Microsoft/vscode/wiki/%5BWIP%5D-Design-Principles) and [design checklist](https://github.com/Microsoft/vscode/wiki/%5BWIP%5D-Design-Checklist) to guide the process for designing and implementing this work.

The backlog is split up into three parts: **Existing users**, **New users**, and **Not yet incorporated**. 

# Backlog
## Existing users
- [x] :running_man: Review code at your finger tips: hover, completion items, completion item details [#63144](https://github.com/Microsoft/vscode/issues/63144)
   - `css` completions showing MDN info
   - fonts, colors, etc. in completion items and completion details, hovers
- [ ] :running_man: Iconography re-design [#8017](https://github.com/Microsoft/vscode/issues/8017), [44594](https://github.com/Microsoft/vscode/issues/44594)
- [x] :running_man: Update Octicons [#65508](https://github.com/Microsoft/vscode/issues/65508)
- [ ] Improve the `Show Running Extensions` experience
  - Explore the best way to show this information (viewlet vs new tab)
  - Show this information on the extension detail view [#64344)](https://github.com/Microsoft/vscode/issues/64344)
- [ ] Improve Find All References [#22261](https://github.com/Microsoft/vscode/issues/22261)
   - Implications for the monaco editor
  - Can this be done in the search viewlet instead?
  - Better empty selection state
- [ ] Overflow and customization for status bar [#6651](https://github.com/Microsoft/vscode/issues/6651), [#35744](https://github.com/Microsoft/vscode/issues/35744), [#3874](https://github.com/Microsoft/vscode/issues/3874)
- [ ] Revisit extension recommendation end-to-end experience (on file load, ext. viewlet, etc.)
- [ ] Improve Search when position is moved to panel [#64418](https://github.com/Microsoft/vscode/issues/64418)
  - The search icon is gone, making it harder to remember to use the keyboard shortcut
  - The over layout panel is not a good user of space
- [ ] Ability to move views into separate viewlets/panels
- [ ] Improve creating a new file/folder when explorer has content and when hidden
  - We should show a quickpick that has the path pre-populated 
- [ ] Better experience for dynamic views/viewlets (list all references, hiding an activity bar item & accessing it)
- [ ] Hide titlebar on Mac [#12377](https://github.com/Microsoft/vscode/issues/12377)
- [ ] Fluent Design [#26572](https://github.com/Microsoft/vscode/issues/26572), [#17060](https://github.com/Microsoft/vscode/issues/17060), [#12578](https://github.com/Microsoft/vscode/issues/12578), [PR 52707](https://github.com/Microsoft/vscode/pull/52707)

------
## New users
- [ ] First user onboarding experience
   - [ ] :running_man: Welcome page [#63152](https://github.com/Microsoft/vscode/issues/63152)
   - [ ] Stacking of notifications (particularly when on non-English locales)
   - [ ] Playground
   - [ ] UI overview
   - [ ] Loading of webpage on first launch
     - Do we still need this for cookie tracking?
   - [ ] Guidance to install extensions
- [ ] Website re-design: roadmap outlining incremental steps to a friendlier, more modern website
  - Internationalization
- [ ] Discoverability: How do we raise awareness of functionality?
- [ ] Update default theme colors with modern (Fluent?) color palette

------
## Not yet incorporated
- [ ] Extension welcome pages and release notes
  - Potentially show an area on the welcome page for release notes and recently updates
    - Add "Recently updated" as a keyword option in the extension viewlet
    - Show diagnostics tab when in this view
    - Default tab would go to changelog from this view
- [ ] Explore ways for the community to contribute to designs in the same way as code is contributed

**Comment by eliashdezr** [comment]
@misolori 
It is possible to consider this feature for this backlog?
https://github.com/Microsoft/vscode/issues/12622

Has to be some of the most wanted UI features, yet not a single word from the team.

**Comment by gkkirilov** [comment]
These issues should get some priority. [#52707](https://github.com/Microsoft/vscode/pull/52707) was ready but wasn't merged.
Visuals are as important as new features

**Comment by gkkirilov** [comment]
Can we also add [32257](https://github.com/Microsoft/vscode/issues/32257)?
Thanks for the awesome editor 💖

**Comment by SupinePandora43** [comment]
what's about allowing custom background image?! something like [![anime background](http://coding.net/u/ice1000/p/Images/git/raw/master/test1.png)](https://vscode.one.love/#pls-implement-this "this")

**Comment by zbandhan** [comment]
Could you please let us know if the topmost feature in the list take longer time to be merged?

**Comment by misolori** [comment]
@zbandhan which item are you referring to?

**Comment by zbandhan** [comment]
@misolori referring to #63144

**Comment by SamAtAnyRoad** [comment]
I see that boolean search references here, and that ticket is closed and mentioned as having been added to this list, but it seems that it never actually was added to the list. 

Boolean search is an essential feature, and regex search isn't really a replacement for it. Certain operations, like looking for all files that contain "email" AND "receipt" are trivially easy in a standard boolean search and devilishly difficult to phrase effectively in regex.

**Comment by lambainsaan** [comment]
Hey @misolori , dumb question but what do you mean by items that have :running_man:? Does it mean part of the current sprint?

**Comment by misolori** [comment]
@lambainsaan they're not all necessarily tied to a milestone, it just means we are actively working on it or have efforts in place to be working on them. You can think of it as being "active".

**Comment by tclzcja** [comment]
Hi @misolori quick question about “Add touch support #70764”. In order for VS Code to be on iPadOS, is the main blocker more about the Apple App Store/Electron/HTML5 policy? Or it’s something smaller like touch support?
For a long time I thought it’s the Apple’s policy that makes it difficult for VS Code to land, but since you use “Add touch support” as the title there, I’m just a little confused. Thank you very much!

**Comment by lujo777** [comment]
@misolori, It would be cool, if they will publish VS Code for iPadOS, but, i think, touch support is only support for touch-screens in browser version of vsc (online.visualstudio.com) :(

**Comment by misolori** [comment]
@tclzcja @lujo777 the touch support issue is to support [Visual Studio Online](https://visualstudio.microsoft.com/services/visual-studio-online/), we don't have any current plans to create an iOS app.

**Comment by tclzcja** [comment]
@misolori got it, thank you.

**Comment by thomasio101** [comment]
@misolori, I understand there are no *official* plans to create an iOS app, but I think it wouldn't be a bad idea to attempt creating a simplified version of Visual Studio which only includes core functionality for development.

By the way @tclzcja, Apple's policy would make it quite difficult to implement a full Visual Studio Code experience on either iOS or iPadOS as the policy forbids apps that are able to run arbitrary code (Which is strange, given the existence and success of apps like [Codea](https://codea.io/).). But the policy does not, or so I think, forbid apps that remotely execute code, so just having a built-in SSH terminal would be allowed for example.

**Comment by misolori** [comment]
Closing this issue as most items are complete and we've created a new, revamped, version in #146840
