### ISSUE TITLE
Iteration Plan for February 2019

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#68293]
This plan captures our work in **February**. This is a 4 week iteration, and we will **ship** our February Update in **in early March**. We'll continue work we started in the previous iteration, and we started to pick up items from our [roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap).

## Endgame

- **February 25, 2019**: Code freeze for the endgame (Zurich freezes on February 22)
- **March 1, 2019**: Endgame done

The endgame details for this iteration are tracked in https://github.com/Microsoft/vscode/issues/69177.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Workbench
- [x] Revisit the custom menubar on Linux https://github.com/Microsoft/vscode/issues/65608 @sbatten
- [x] Simplify switching to an newly installed theme https://github.com/Microsoft/vscode/issues/68408 @sandy081 @aeschli
- [x] Adopt new tree in Outline https://github.com/Microsoft/vscode/issues/64727 @jrieken @joaomoreno

### UX
- [ ] :runner: Iconography re-design https://github.com/Microsoft/vscode/issues/8017 @misolori

### Editor
- [x] Improve hover presentation for complex errors https://github.com/Microsoft/vscode/issues/67076 @sandy081
- [x] Adopt new tree in bread crumb https://github.com/Microsoft/vscode/issues/64727 @jrieken @joaomoreno

### Tasks
- [ ] :runner: Add support for custom execution in addition to ShellExecution and ProcessExecution https://github.com/Microsoft/vscode/issues/66818 @alexr00

### Languages
- [ ] :runner: Support semantic selections https://github.com/Microsoft/vscode/issues/4795 @jrieken

#### LSP
- [x] Support semantic selections https://github.com/Microsoft/language-server-protocol/issues/613 @dbaeumer
- [ ] :runner: [PR #426](https://github.com/Microsoft/vscode-languageserver-node/pull/426) LSP support for type hierarchies @dbaeumer
- [ ] :runner: [PR #420](https://github.com/Microsoft/vscode-languageserver-node/pull/420) LSP support for call hierarchies @dbaeumer
- [ ] :runner: [PR #261](https://github.com/Microsoft/vscode-languageserver-node/pull/261) LSP support for progress reporting @dbaeumer

#### JavaScript/TypeScript
- [x] Adopt TypeScript 3.3.x https://github.com/Microsoft/vscode/issues/68823 @mjbvz

#### CSS/HTML
- [x] Update CSS and HTML language services with MDN data https://github.com/Microsoft/vscode-html-languageservice/issues/44 @octref

### Debug
- [x] Support a "debug target ready" hook for launch configs https://github.com/Microsoft/vscode/issues/69311 @weinand
- [x] Explore how to support extending the debug toolbar https://github.com/Microsoft/vscode/issues/45116 @isidorn
- [ ] :runner: Providing additional hooks for generating `launch.json` https://github.com/Microsoft/vscode/issues/65988 @isidorn
- [x] Investigate Find in Console https://github.com/Microsoft/vscode/issues/4338 @isidorn

### Debug Adapter Protocol
- [x] Finalize data breakpoints https://github.com/Microsoft/debug-adapter-protocol/issues/20 @weinand
- [x] Investigate protocol addition to support opening a page in the browser https://github.com/Microsoft/debug-adapter-protocol/issues/23 @weinand

### Extension Contributions
- [x] Work with extension authors on adoption of dynamic loading of extensions https://github.com/Microsoft/vscode/issues/67958 @sandy081 @alexandrudima
- [x] Migrate `vscode-tslint` to use tslint as a TS server plugin https://github.com/Microsoft/typescript-tslint-plugin/issues/1 @mjbvz @egamma
- [x] Contributions to the GitHub PR extension https://github.com/Microsoft/vscode-pull-request-github/issues/921 @rebornix @rmacfarlane
- [x] Contributions to the Vetur extension https://github.com/vuejs/vetur/milestone/5 @octref

### Extensions
- [x] Webpack eslint extension @dbaeumer

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2019%22+label%3A%22api-proposal%22+)
- [x] Reconsider comment provider APIs https://github.com/Microsoft/vscode/issues/68020 @rebornix @rmacfarlane @jrieken

### Exploration
- [ ] :runner: Explore support for developing on WSL https://github.com/Microsoft/vscode/issues/63155 @alexandrudima **team**
- [ ] :runner: Explore supporting Electron 5.0 default renderer configuration https://github.com/Microsoft/vscode/issues/68302 @bpasero @sbatten
- [x] Explore webview rendered code insets https://github.com/Microsoft/vscode/pull/66418 @jrieken

### Engineering
- [x] Ensure user need to choose target when filing issues https://github.com/Microsoft/vscode/issues/66080 @rmacfarlane
- [x] Ensure all of our built-in extensions support dynamic loading https://github.com/Microsoft/vscode/issues/67574 https://github.com/Microsoft/vscode/issues/67575 @mjbvz **team**
- [ ] :runner: Strict null checking VS Code https://github.com/Microsoft/vscode/issues/60565 @mjbvz **team**
- [x] Compile TS to ES6 https://github.com/Microsoft/vscode/issues/65372 @jrieken

### Documentation
- [x] Revisit Javascript end user documentation https://github.com/Microsoft/vscode-docs/issues/2190 @mjbvz @gregvanl
- [ ] :runner: Create a guide for webpacking extensions https://github.com/Microsoft/vscode/issues/64532, https://github.com/Microsoft/vscode-docs/issues/2403, https://github.com/Microsoft/vscode-vsce/issues/333 @jrieken

---

### Deferred Items
- Explore flatting folder hierarchies in the explorer https://github.com/Microsoft/vscode/issues/41627 @isidorn @joaomoreno
- :hand: Electron 4.0 upgrade https://github.com/Microsoft/vscode/issues/61787 @bpasero
- Explore alternative extension install/management experiences https://github.com/Microsoft/vscode/issues/68527 @misolori @sandy081
- Improve presentation of debugged subprocesses https://github.com/Microsoft/vscode/issues/62972 @weinand
- Investigate reviving translations for the Monaco editor @dbaeumer
- Improve user experience when multiple-formatters are registered https://github.com/Microsoft/vscode/issues/41882 @jrieken @octref

**Comment by maciejw** [comment]
you mean Electron 4.0 upgrade released on stable channel!? finally in my company we will be able to upgrade from 1.25.1 ❤👌

**Comment by svipben** [comment]
@maciejw  Just curious, why you're still using 1.25.1 version? And how Electron 4 is related to this? Current VS Code version uses Electron 3.1.3 which is latest from v3.x.

**Comment by maciejw** [comment]
@svipben because of this https://github.com/Microsoft/vscode/issues/56644, 40 seconds startup is too painful :)

**Comment by svipben** [comment]
Thanks, didn't know about this issue. Good news there are already exploration builds with Electron 4 which you can download and use ✨

**Comment by maciejw** [comment]
I know, are they stable enough though ;)

**Comment by dpen2000** [comment]
Can this (and hopefully future iteration plans) be pinned so they show up above issue list? See https://help.github.com/articles/pinning-an-issue-to-your-repository/

**Comment by egamma** [comment]
@dpen2000 thanks for the suggestion. I've pinned the issue so that we can try this out.

**Comment by JCMais** [comment]
is just me or the dpi was really improved recently? Was that something worked on for this release? Or I'm just imagining things (using latest Insiders on Win10)

**Comment by kieferrm** [comment]
Shipped.
