### ISSUE TITLE
Explore supporting Electron 5.0 default renderer configuration

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#68302]
### Synopsis

**Electron 5.0** disables node integration (by default). Explore if we can run VSCode in such an environment where node.js cannot be used from the renderer.

### Development

All changes happen on `master`. To run, simply append `--nodeless` to the startup, e.g. 

```
scripts/code.sh --nodeless
```

This will open a version of the workbench that can run without node by pulling in `src/vs/workbench/workbench.nodeless.main.ts`. This is a list of dependencies that have no node.js or electron dependency. It closely mirrors `src/vs/workbench/workbench.main.ts` as much as possible.

Many services in `src/vs/workbench/workbench.nodeless.main.ts` are shimmed with a simple implementation until they are adopted (see `src/vs/workbench/browser/nodeless.simpleservices.ts`).

### Example: make emmet fit to run without node/electron

We recently [pushed changes](https://github.com/Microsoft/vscode/commit/85d983391a3c1ff65db6746b8c6994ec0833b3d8) to support emmet fully in an environment without node. The steps involved:
* moving the code itself to a `common` or `browser` layer ([more info on our layers](https://github.com/Microsoft/vscode/wiki/Code-Organization#target-environments))
* this typically means to avoid using node.js or electron API by using a service instead that can be referenced from `common` or `browser`

### Example: make the hash service fit to run without node/electron

We have a `IHashService` that can be used to compute SHA1 hashes of strings that is implemented by using the node.js API. To allow to use this service from an environment without node:
* we created as `src/vs/workbench/services/hash/common/hashService.ts` that is fully implemented to run without node
* we updated `src/vs/workbench/workbench.nodeless.main.ts` to use that implementation instead of the simple implementations from `src/vs/workbench/browser/nodeless.simpleservices.ts`

**Note:** if the new implementation of the service is good enough, we can drop the existing one to ensure we only have one service implementation.

### Backlog

**Related Issues:**
* [x] InstantiationService with proxys: allow to be used in browser namespace #69141
* [x] Split up workbench/api into a electron-browser and browser part #70319
* [ ] Implement a `IRequestService` that works in `browser` context (using XHR) (blocks https://github.com/Microsoft/vscode/issues/69111)
* [x] Revisit need for `node/electron-browser` in `workbench/contrib/watermark` #69117
* [x] Revisit need for `node/electron-browser` in `workbench/contrib/welcome` #69116
* [x] Revisit need for `node/electron-browser` in `workbench/contrib/terminal` #69115
* [ ] Revisit need for `node/electron-browser` in `workbench/contrib/tasks` #69113
* [x] Revisit need for `node/electron-browser` in `workbench/contrib/scm` #69112
* [ ] Revisit need for `node/electron-browser` in `workbench/contrib/preferences` #69111
* [x] Revisit need for `node/electron-browser` in `workbench/contrib/output` #69110
* [x] Revisit need for `node/electron-browser` in `workbench/contrib/markers` #69109
* [ ] Revisit need for `node/electron-browser` in `workbench/contrib/experiments` #69108
* [x] Revisit need for `electron-browser` in `workbench/contrib/execution` #69107
* [x] Revisit need for `electron-browser` in `workbench/contrib/emmet` #69105
* [x] Revisit need for `electron-browser` in `workbench/contrib/debug` #69104
* [x] Revisit need for `electron-browser` in `workbench/contrib/comments` #69103
* [x] Revisit need for `electron-browser` in `workbench/contrib/codeEditor` #69102

**Comment by bpasero** [comment]
We will continue this investigation but current thinking is to adopt Electron 5 and 6 with `nodeIntegration` still being enabled as before.
