### ISSUE TITLE
Iteration Plan for March 2019

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#70102]
This plan captures our work in **March**. We will **ship** our March Update in **in early April**. We entered March with a considerable number of items still in progress. We'll focus on those first. We'll look into providing support for Call Hierachies, UI and Language Server Protocol. We'll make it easier to develop extensions and contribute to our documentations. And we'll keep looking into getting ready for electron 5.0. We'll also continue our good deeds for the Vetur extension.

## Endgame

- **March 25, 2019**: Code freeze for the endgame
- **March 29, 2019**: Endgame done

The endgame details for this iteration are tracked in https://github.com/Microsoft/vscode/issues/71059.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Workbench
- [x] Simplify switching between display languages https://github.com/Microsoft/vscode/issues/22758 @rmacfarlane
- [x] Allow users to filter intellisense suggestions https://github.com/Microsoft/vscode/issues/45039 @jrieken

### UX
- [ ] :runner: Iconography re-design https://github.com/Microsoft/vscode/issues/8017 @misolori
- [ ] :runner: Explore Extensions Management UX https://github.com/Microsoft/vscode/issues/68527 @misolori @sandy081

### Editor
- [x] Investigate reviving translations for the Monaco editor https://github.com/Microsoft/vscode/issues/71065  @dbaeumer

### Terminal
- [x] Improve layering and code structure @tyriar https://github.com/Microsoft/vscode/issues/69115

### Languages
- [x] Support semantic selections https://github.com/Microsoft/vscode/issues/4795 @jrieken
- [x] Explore support for a Call Hierarchy view https://github.com/Microsoft/vscode/issues/16110 @jrieken

#### LSP
- [ ] :runner: LSP support for type hierarchies [PR #426](https://github.com/Microsoft/vscode-languageserver-node/pull/426)  @dbaeumer
- [ ] :runner: LSP support for call hierarchies [PR #420](https://github.com/Microsoft/vscode-languageserver-node/pull/420) @dbaeumer
- [ ] :runner: LSP support for progress reporting [PR #261](https://github.com/Microsoft/vscode-languageserver-node/pull/261) @dbaeumer

#### JavaScript/TypeScript
- [x] Adopt TypeScript 3.4 @mjbvz https://github.com/Microsoft/vscode/issues/70434

### Debug
- [X] Providing additional hooks for generating `launch.json` https://github.com/Microsoft/vscode/issues/65988 @isidorn
- [X] Improve presentation of debugged subprocesses https://github.com/Microsoft/vscode/issues/62972 @weinand @isidorn
- [X] Finish `serverReadyAction` support https://github.com/Microsoft/vscode/issues/69898 @weinand

### Extension Contributions
- [x] Contributions to the GitHub PR extension https://github.com/Microsoft/vscode-pull-request-github/issues/1023 @rebornix @rmacfarlane
- [x] Contributions to the Vetur extension https://github.com/vuejs/vetur/milestone/6 @octref

### Extensions
- [x] Remove `postInstall` by moving `vscode.d.ts` to `@types` on npm https://github.com/Microsoft/vscode/issues/70175 @octref
- [x] Improve user experience when multiple-formatters are registered https://github.com/Microsoft/vscode/issues/41882 @jrieken
- [x] Improve proxy support for extensions https://github.com/Microsoft/vscode/issues/52880 @chrmarti

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2019%22+label%3A%22api-proposal%22+)
- [x] Replace proposed comment provider APIs https://github.com/Microsoft/vscode/issues/68020 @rebornix

### Install
- [x] :running: Provide Linux snap packages for for stable and insiders @joaomoreno

### Exploration
- [ ] :runner: Explore support for developing on WSL https://github.com/Microsoft/vscode/issues/63155 @alexandrudima **team**
- [ ] :runner: Explore supporting Electron 5.0 default renderer configuration https://github.com/Microsoft/vscode/issues/68302 @bpasero @sbatten **team**

### Engineering
- [x] Strict null checking VS Code https://github.com/Microsoft/vscode/issues/60565 @mjbvz **team**

### Documentation
- [x] Make it easier to contribute to our documentation by using `git lfs` https://github.com/Microsoft/vscode-docs/issues/1789 @octref

---

### Deferred Items
- Electron 4.0 upgrade https://github.com/Microsoft/vscode/issues/61787 @bpasero
- Explore flatting folder hierarchies in the explorer https://github.com/Microsoft/vscode/issues/41627 @isidorn @joaomoreno

**Comment by KevinG2011** [comment]
Kamino cloned this issue to [KevinG2011/FlutterGuide](https://github.com/KevinG2011/FlutterGuide/issues/1)

**Comment by yyahoo11** [comment]
Ok

**Comment by yyahoo11** [comment]
Ok

**Comment by waynebloss** [comment]
Will #70032 be included?

**Comment by Tyriar** [comment]
@waynebloss yes, any issues that are assigned to the March milestone (like https://github.com/Microsoft/vscode/issues/70032) will be included in this release.

**Comment by kieferrm** [comment]
Shipped.
