### ISSUE TITLE
Iteration Plan for April 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#71830]
This plan captures our work in **April**. This is a 6-week iteration. We will **ship** our April Update **in early May**. You'll notice that we list less work than usual in an iteration that is longer than usual. If you wonder what we are up to: One of the [most commented issues](https://github.com/Microsoft/vscode/issues/13138) is about WSL and led us to explore what we can do ([#63155](https://github.com/Microsoft/vscode/issues/63155)). It made us realize that with a bit of enablement in the core, we can build extensions that greatly improve the WSL experience and "a bunch of other stuff" :smiley:. It's a model comparable to what happened a year ago with the LiveShare extension. So, this month we keep the focus on those extensions and lift the curtain in early May. It's going to be cool, stay tuned. 

Oh, and the Swiss part of our team needs to [set a :snowman: on :fire:](https://en.wikipedia.org/wiki/SechselÃ¤uten).

## Endgame

- **May 6, 2019**: Endgame begins
- **May 10, 2019**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/73175.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [ ] :runner: Iconography re-design https://github.com/Microsoft/vscode/issues/8017 @misolori
- [ ] :runner: Explore Extensions Management UX https://github.com/Microsoft/vscode/issues/68527 @misolori @sandy081
- [ ] :runner: Explore new VS Code icons https://github.com/Microsoft/vscode/issues/71827 @misolori

#### LSP
- [x] LSP support for call hierarchies [PR #420](https://github.com/Microsoft/vscode-languageserver-node/pull/420) @dbaeumer
- [x] LSP support for progress reporting [PR #261](https://github.com/Microsoft/vscode-languageserver-node/pull/261) @dbaeumer

#### JavaScript/TypeScript
- [x] Adopt TypeScript 3.4.x @mjbvz

### Extension Contributions
- [x] Contributions to the Vetur extension https://github.com/vuejs/vetur/milestone/7 @octref

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2019%22+label%3A%22api-proposal%22+)

### Exploration
- [x] Explore support for developing on WSL https://github.com/Microsoft/vscode/issues/63155 @alexandrudima **team**
- [ ] :runner: Explore supporting Electron 5.0 default renderer configuration https://github.com/Microsoft/vscode/issues/68302 @bpasero @sbatten **team**

---

### Deferred Items
- Electron 4.0 upgrade https://github.com/Microsoft/vscode/issues/61787 @bpasero
- Explore flatting folder hierarchies in the explorer https://github.com/Microsoft/vscode/issues/41627 @isidorn @joaomoreno
- LSP support for type hierarchies [PR #426](https://github.com/Microsoft/vscode-languageserver-node/pull/426) @dbaeumer

**Comment by MichaelTong** [comment]
Really excited for the tease of WSL support 😀

**Comment by beastdestroyer** [comment]
Don't forget to pin when ready! @kieferrm :)

**Comment by joewood** [comment]
I'm hoping my old issue from 2 years ago can be closed ! https://github.com/Microsoft/vscode/issues/22663

**Comment by DovydasNavickas** [comment]
I googled "endgame release date", 'cause I though it was a bit earlier than May 6, 2019. And it was.
Only then I understood that you did not take 4 days of iteration just because everyone could see the newest Avengers movie.... It's just an endgame for the iteration 😂

**Comment by Geobert** [comment]
Every month I'm hoping for a line about at least exploring tree-sitter :'(

**Comment by mtxr** [comment]
@kieferrm no plans for #50062 on horizon?

**Comment by kieferrm** [comment]
@mtxr not this iteration.

**Comment by NateLing** [comment]
Should we create a hope(wish) list?

**Comment by madarsbiss** [comment]
@NateLing excatly! :)

**Comment by jhpratt** [comment]
Can we please get a temporary solution to #68001? Even a dropdown to toggle the setting, as indicated in the comments.

**Comment by axetroy** [comment]
Should we create a pinned issue for `Features Wish List`?

Developers can vote for the features they need most.

Then consider implementing it and join into the iteration plan.

**Comment by gulshan** [comment]
The list is already there-
https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc
And everyone can vote!

**Comment by randrade23** [comment]
No plans for #45385 ? It would help make autocomplete much more robust, while extending possibilities for extension devs. @kieferrm , @mjbvz , anyone?

**Comment by MichaelTong** [comment]
What is the status of WSL supporting? The task is still not checked, so will it come to the release of this month? (Anxiously waiting 😟)

**Comment by connorshea** [comment]
@MichaelTong seems your wish was granted: https://code.visualstudio.com/blogs/2019/05/02/remote-development

**Comment by EthanRutherford** [comment]
It exists, but hasn't been linked yet (there's actually a link to it just a few comments above)

https://github.com/microsoft/vscode/issues/73175

**Comment by paterasMSFT** [comment]
How's endgame looking? Typical details page missing.

Also, for anyone unfamiliar, WSL = Windows Subsystem for Linux.

**Comment by BobCu** [comment]
Be sure to target [WSL2](https://devblogs.microsoft.com/commandline/announcing-wsl-2/), which embeds an actual Linux kernel (4.19 to start with) into Windows (including some hardware device access), and not the initial WSL "compatibility layer" (Cygwin-like) effort.

**Comment by cure77** [comment]
What's an early May?
