### ISSUE TITLE
Iteration Plan for May 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#74143]
This plan captures our work in the second half of **May**. This is a 1.5-week "mini iteration". We will **ship** our May Update **in early June**.

Early May, we successfully released the preview of our [Remote Development extensions](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack). After that came **//build** and then we had our first **Team Week**. May 13-18, the whole team came together in Redmond, USA to discuss and work together. We enjoyed every moment of it. Now, we need to get back into our usual rhythm of shipping a new version of VS Code at the beginning of each month. To do that as quickly as possible, we only focus on bugs and paper-cuts for a short period.

## Endgame

- **May 28, 2019**: Endgame begins
- **May 31, 2019**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/74412.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Bugs and Paper Cuts
- [x] [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2019%22)

### UX
- [ ] :runner: Iconography re-design https://github.com/Microsoft/vscode/issues/8017 @misolori
- [x] Explore new VS Code icons https://github.com/Microsoft/vscode/issues/71827 @misolori

#### JavaScript/TypeScript
- [x] Support semanic selection https://github.com/microsoft/vscode/issues/74243 @mjbvz

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2019%22+label%3A%22api-proposal%22+)

### Extension Contributions
- [x] Improve and stabilize Remote Development extensions [query](https://github.com/microsoft/vscode-remote-release/milestone/2)

### Exploration
- [ ] :runner: Explore supporting Electron 5.0 default renderer configuration @bpasero @sbatten **team**

### Engineering
- [x] Improve infrastructure for supporting extension authors https://github.com/microsoft/vscode/issues/71048 @octref

---

### Deferred Items
- Electron 4.0 upgrade https://github.com/Microsoft/vscode/issues/61787 @bpasero

**Comment by wendzhue** [comment]
Still working for the new icons and logo. 🤗

**Comment by misolori** [comment]
@wendzhue please see https://github.com/microsoft/vscode/issues/71827#issuecomment-495167013, we're hoping to roll out the new product icon in the next release.

**Comment by gulshan** [comment]
Add to milestone?

**Comment by pixieaka** [comment]
#28409 Is this soon...

**Comment by CookieCrumbles** [comment]
> Still waiting for the new icons and logo. 🤗

New icon is lit AF

**Comment by AntSworD** [comment]
Explore flatting folder hierarchies in the explorer still derer😭
