### ISSUE TITLE
June plan for xterm.js in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#74861]
A lot of things have been happening in xterm.js with the upcoming xterm v4 that we need to adopt as part of the June release. Here are the highlights:

- [x] Old addon support is dropped, only new addons (added in 3.14) will work. These new addons support TypeScript much better and have a much better thought out lifecycle than the previous model (https://github.com/xtermjs/xterm.js/pull/2164)
- [x] Adopting the new buffer and selection APIs allows us to remove some of the private API typings we touch (https://github.com/xtermjs/xterm.js/pull/2074, https://github.com/xtermjs/xterm.js/pull/2078)
- [x] New addons are published as separate npm modules which allows us to remove the dodgy `__nodeRequire` calls (https://github.com/microsoft/vscode/issues/74398)
- [x] Since beta builds in xterm.js are now automated we can move over to use the official `xterm` module instead of `vscode-xterm` (https://github.com/microsoft/vscode/issues/74690)
- [x] The [working with xterm.js](https://github.com/microsoft/vscode/wiki/Working-with-xterm.js) wiki article should be updated to reflect these changes
- [x] The xterm module main JS file is now webpacked so which makes it a single file and minified (https://github.com/xtermjs/xterm.js/pull/2132)
- [x] Continued improvement to the layering and enabling TS strict mode makes the library more stable https://github.com/xtermjs/xterm.js/issues/1507
