### ISSUE TITLE
Iteration Plan for June 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#75103]
This plan captures our work in **June**. This is a 4-week iteration. We will **ship** our June Update **in early July**.

We'll focus on smaller, highly upvoted features such as improvements to the minimap, and we'll keep stabilizing and improving the remote development extensions.

## Endgame

- **June 24, 2019**: Endgame begins
- **June 28, 2019**: Endgame done

The endgame details for this iteration are tracked in **TBD**

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [ ] :runner: Iconography re-design https://github.com/Microsoft/vscode/issues/8017 @misolori

### Workbench
- [x] Support to hide/show status bar items contributed by extensions @bpasero https://github.com/microsoft/vscode/issues/3874
- [x] :runner: Add support for indentation guides in trees https://github.com/microsoft/vscode/issues/17777 @joaomoreno
- [x] Provide easy access to online services settings https://github.com/microsoft/vscode/issues/75215 @rmacfarlane

### Editor
- [x] :runner: Render search results in the editor minimap https://github.com/microsoft/vscode/issues/75216 @rmacfarlane
- [ ] :muscle: Provide setting for visually indicating whitespace in selections https://github.com/microsoft/vscode/issues/1477 @rmacfarlane

### Terminal
- [x] `xterm.js` improvements https://github.com/microsoft/vscode/issues/74861 @tyriar
- [x] Investigate providing a clean environment for the terminal https://github.com/microsoft/vscode/issues/70248 @tyriar

### Git
- [x] Support watching files outside of the workspace https://github.com/microsoft/vscode/issues/41085 @joaomoreno

#### CSS/HTML/JSON
- [x] Adopt latest LSP improvements https://github.com/microsoft/vscode/issues/75271 @aeschli

#### TS
- [x] Provide support to easily use the nightly of TS inside VS Code @mjbvz https://github.com/microsoft/vscode/issues/75222

### Debug
- [x] Add 'Jump to Cursor' support https://github.com/Microsoft/vscode/issues/25653 @weinand @isidorn

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22June+2019%22+label%3A%22api-proposal%22+)

### Extension Contributions
- [ ] :runner: Improve getting started experience with the TS Lint extension https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/99 @mjbvz
- [ ] :runner: Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/608)) **team**

### Engineering
- [ ] :runner: Update to electron 4.0 @bpasero @deepak1556 https://github.com/microsoft/vscode/issues/61787
- [x] :runner: Categorize/analyze currently open accessibility issues @isidorn https://github.com/microsoft/vscode/issues/75840
- [ ] :runner: Explore providing tooling for GDPR code annotation extraction @lramos15 https://github.com/microsoft/vscode/issues/75524
- [x] :runner: Explore using TS for our GDPR code annotations @lramos15 https://github.com/microsoft/vscode/issues/75527

-------
### Deferred Items
- Adopt new `Tree` implementation in Custom Views https://github.com/microsoft/vscode/issues/63566 @alexr00 @sandy081
- Flatten folder hierarchies in the explorer https://github.com/Microsoft/vscode/issues/41627 @isidorn @joaomoreno

#### LSP
- :runner: Add support for progress reporting for client initiated work https://github.com/microsoft/language-server-protocol/issues/70 and https://github.com/microsoft/vs-streamjsonrpc/issues/139 @dbaeumer
- :runner: Explore support for reporting partial results (e.g. workspace symbols) https://github.com/microsoft/vs-streamjsonrpc/issues/139 @dbaeumer

**Comment by ghiscoding** [comment]
@kieferrm 
You mentioned minimap, is there a chance to look at this minimap enhancement issue #21404 that I opened 2.5 years ago? 

Another topic that I'd like to see improvement, to be more user friendly, is the color picker especially this issue #33568

Keep up the good work, that is by far my favorite editor!

**Comment by pie6k** [comment]
> 🔴 🏃 Add support for indentation guides in trees @joaomoreno 

here is missing issue reference

https://github.com/microsoft/vscode/issues/17777

**Comment by egamma** [comment]
@pie6k added the issue reference, thanks!

**Comment by NateLing** [comment]
Hi there. electron nightly version comes to v7,  VSCode still use v4.  come on , let's do something.

**Comment by Tyriar** [comment]
@NateLing it's missing on the plan but we're exploring Electron 6 support right now.

**Comment by kanlukasz** [comment]
> 
> 
> @NateLing it's missing on the plan but we're exploring Electron 6 support right now.

Great to hear it. I hope that upgrading to the v. 6 will solve this annoying visual error in Win10 - https://github.com/microsoft/vscode/issues/74047

**Comment by beastdestroyer** [comment]
@kieferrm Gotta add #75985 endgame to top

**Comment by kanlukasz** [comment]
Is June session closed? 
What's going on with: `Provide setting for visually indicating whitespace in selections` - #1477
I was waiting for it very much 😞

**Comment by MommyMisty1** [comment]
Home sweet heart .
