### ISSUE TITLE
Iteration Plan for July 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#76735]
This plan captures our work in **July**. This is a 5-week iteration. We will **ship** our July Update **in early August**.

During this iteration, we make last polishing changes to our new icons so that you can enjoy them in Insiders and Stable. We'll keep improving the minimap and add additional controls to the settings editor. The biggest chunk of our work though goes into engineering and improvements for extensions such as multi-selection in custom views, improving LSIF and DAB, and finalizing the custom data support in our HTML and CSS support.

Also it's July. As usual, we start to see members of our team to take time off. So, if you don't get responses from us as quickly as you're used to, imagine white ocean beaches or beautiful mountains.

## Endgame

- **July 29, 2019**: Endgame begins
- **August 2, 2019**: Endgame done

The endgame details for this iteration are tracked in #78131.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [x] Iconography re-design https://github.com/Microsoft/vscode/issues/8017 @misolori
- [ ] :runner: Update main extension icons to match new icon style https://github.com/microsoft/vscode/issues/77411 @misolori

### Workbench
- [ ] :runner: Implement workbench layout using grid widget https://github.com/Microsoft/vscode/issues/50853 @sbatten @joaomoreno
- [x] Provide built-in support for settings with values that are lists of strings https://github.com/Microsoft/vscode/issues/62440 @octref
- [x] Explore support for custom editors https://github.com/microsoft/vscode/issues/77131 @mjbvz @jrieken

### Accessibility
- [x] Fix [actionable issues](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22July+2019%22), see also https://github.com/microsoft/vscode/issues/75840 @isidorn

### Editor
- [x] Support multi-line decorations in the minimap https://github.com/microsoft/vscode/issues/76133 @rmacfarlane
- [x] Explore improving presentation of search results in minimap (size, theme color) https://github.com/microsoft/vscode/issues/76122 @rmacfarlane
- [ ] :runner: Revisit the tokenization implementation with the end goal to support asynchronous semantic coloring https://github.com/microsoft/vscode/issues/77140 @alexandrudima
- [x] Provide setting for visually indicating whitespace in selections https://github.com/microsoft/vscode/issues/1477 @rmacfarlane
- [x] Special rendering for diagnostics that mark deprecated code, https://github.com/microsoft/vscode/issues/56694 @jrieken

### Terminal
- [x] Add commands to focus the previous/next row when in screenreader mode https://github.com/microsoft/vscode/issues/76050 @tyriar

#### LSP
- [x] Finalize LSIF spec `v0.4` with support for partitioned index updating @dbaeumer https://github.com/microsoft/lsif-node/issues/60

#### CSS/HTML/JSON
- [x] Improve navigation for sass `import` statements https://github.com/microsoft/vscode/issues/58204 @octref
- [ ] :runner: Finalize experimental custom data support https://github.com/microsoft/vscode/issues/76914 @octref

### Debug
- [x] Investigate VS Code UI for data breakpoints https://github.com/microsoft/vscode/issues/58304 @weinand

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22July+2019%22+label%3A%22api-proposal%22)

### Extension Contributions
- [x] Improve getting started experience with the TS Lint extension https://github.com/microsoft/vscode-typescript-tslint-plugin/issues/99 @mjbvz
- [x] Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/916)) **team**

### Engineering
- [ ] :runner: Address electron 4.0 regressions (see [query](https://github.com/microsoft/vscode/projects/6)) @deepak1556
- [ ] :runner: Continue exploring upgrade to electron 6.0 https://github.com/microsoft/vscode/issues/76069 @deepak1556
- [x] Improve build performance https://github.com/microsoft/vscode/issues/75983 @joaomoreno
- [x] Adopt new `Tree` implementation in Custom Views https://github.com/microsoft/vscode/issues/63566 @alexr00 @sandy081
- [ ] :runner: Support flattened rendering of empty nodes to enable https://github.com/Microsoft/vscode/issues/41627 @joaomoreno
- [x] Provide tooling for GDPR code annotation extraction https://github.com/microsoft/vscode/issues/75524 @lramos15
- [x] Migrate tasks to use `TerminalVirtualProcess` https://github.com/microsoft/vscode/issues/76492 @alexr00
- [x] Finish `resolveTask` support https://github.com/microsoft/vscode/issues/33523 @alexr00
- [x] Provide a solid engineering system for `vscode-ripgrep` https://github.com/roblourens/vscode-ripgrep/issues/26 @roblourens
- [x] Remove `suppressImplicitAnyIndexErrors` https://github.com/microsoft/vscode/issues/76442 @mjbvz **team**
- [x] Investigate slow `emmet` activations https://github.com/microsoft/vscode/issues/71381 @octref

-------
### Deferred Items
- Support multi-selection in Custom Views https://github.com/microsoft/vscode/issues/76941 @alexr00
- Explore theming support for semantic colors https://github.com/microsoft/vscode/issues/77133 @aeschli
- Increase automation for upgrading to newer electron versions https://github.com/microsoft/vscode/issues/77159 @deepak1556

**Comment by ghiscoding** [comment]
For the following 2 minimap enhancement, I believe there issue reference is #21404 that I mentioned in last month iteration. 
>  🔴 Support multi-line decorations in the minimap @RMacfarlane
  🔴 Explore improving presentation of search results in minimap (size, theme color) @RMacfarlane

**Comment by ddzy** [comment]
Awesome!

**Comment by efroim102** [comment]
Can we get  white ocean beaches or beautiful mountains as the background of the Welcome screen?...

Also, Aug 2nd is by birthday (the same as when Endgame ends) so maybe in time?

**Comment by Chefdavone12** [comment]
Awesome can't wait to see the finished product 😁

**Comment by andremacola** [comment]
I do not know if this is the correct place but could please check the ticket #73828
It is impossible to work with quotes and International keyboard as system language, specially with multicolumn selection.

**Comment by mysmlz** [comment]
The new icon looks good.

**Comment by gjsjohnmurray** [comment]
The related endgame is #78131. Maybe update the **tbd** in the issue description?
