### ISSUE TITLE
Update extension icons to match new icon style

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#77411]
This is to track the work of updating our main extensions to match our new outline icon style (#8017). Below is a list of the extensions we are tracking to update:

- [x] [Find All References](https://github.com/microsoft/vscode-references-view) - [PR#52](https://github.com/microsoft/vscode-references-view/pull/52)
- [x] [GitHub Pull Requests](https://github.com/microsoft/vscode-pull-request-github/) - [PR#1261](https://github.com/microsoft/vscode-pull-request-github/pull/1261)
- [x] [Remote Development](https://github.com/microsoft/vscode-remote-release)
- [x] [Minimal file icon theme](https://github.com/microsoft/vscode/blob/master/extensions/theme-defaults/fileicons/vs_minimal-icon-theme.json) - [PR#77431](https://github.com/microsoft/vscode/pull/77431)
- [x] [Docker](https://github.com/Microsoft/vscode-docker) - https://github.com/microsoft/vscode-docker/pull/1192
- [ ] [Azure Tools](https://github.com/microsoft/vscode-azure-pack) - https://github.com/microsoft/vscode-azure-pack/issues/19
- [ ] [Live Share](https://github.com/MicrosoftDocs/live-share) - https://github.com/MicrosoftDocs/live-share/issues/2765

**Comment by tavrez** [comment]
What about Live Share?

**Comment by misolori** [comment]
@tavrez added to the list ;) FYI @lostintangent, let's coordicante

**Comment by misolori** [comment]
I've created issues for the Azure + Live Share team to look into updating their icons (updated the description). Since we don't own those extensions (and the rest of their extension packs) I'm going to close this as we've finished the work on our side.
