### ISSUE TITLE
Hover / Suggest widget inconsistencies

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#78718]
Meta issue to track inconsistencies between hover / suggest, in the way they handle and present plaintext / markdown contents.

**Update: Split into multiple issues to track progress easily**

- [x] Markdown `ul` List Rendering #79817
- [x] Markdown `li` List Rendering #79839
- [x] Markdown difference between inline code and code block font family #79818
- [x] Allow completion details to be selected #55853
- [ ] ~~MarkupContent: Link not rendered when space exists on line start #78717~~

---

### Deferred

- [ ] Plaintext Linebreak #79840
- [ ] Plaintext Linkifying #79841

**Comment by jrieken** [comment]
I don't wanna be assigned here, I didn't write any of the code

**Comment by mjbvz** [comment]
Assigning myself to see if any of these are upstream issues with marked

**Comment by octref** [comment]
info hover
