### ISSUE TITLE
Iteration Plan for August 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#78844]
This plan captures our work in **August**. This is a 4-week iteration. We will **ship** our August Update **in early September**.

Although this is the last of the Summer vacation months for us, good work is coming your way. With our work on Custom Editors and the settings sync provider API exploration we continue to pushing the boundaries of what extensions can provide. We also work on the overall user experience with items such as improved minimap and multi-select in custom tree views, and we continue our journey to better performance with reworking tokenization. See below for all the details.

## Endgame

- **August 26, 2019**: Endgame begins
- **August 30, 2019**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/79792.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [x] Update main extension icons to match new icon style https://github.com/microsoft/vscode/issues/77411 @misolori
- [ ] :runner: Update Octicons to match new icon style https://github.com/microsoft/vscode/issues/76909 @misolori
- [ ] :runner: Explore settings sync UX https://github.com/microsoft/vscode/issues/78869 @misolori @sandy081

### Workbench
- [x] Implement workbench layout using grid widget https://github.com/Microsoft/vscode/issues/50853 @sbatten @joaomoreno
- [x] Support multi-selection in Custom Views https://github.com/microsoft/vscode/issues/76941 @alexr00
- [ ] :runner: Support for custom editors https://github.com/microsoft/vscode/issues/77131 @mjbvz @jrieken
- [x] Show file search results in the minimap https://github.com/microsoft/vscode/issues/78236 @rmacfarlane
- [x] Polish settings with values that are lists of strings https://github.com/microsoft/vscode/issues/79050 @octref
- [x] Provide link protection mechanism https://github.com/microsoft/vscode/issues/78125 @octref
- [x] Simplify creation of top-level folder https://github.com/microsoft/vscode/issues/1043 @isidorn
- [x] Allow workspace settings to override machine scoped settings https://github.com/microsoft/vscode/issues/73985 @sandy081
- [ ] :runner: Explore using icon fonts for product icons https://github.com/microsoft/vscode/issues/78889 @misolori @bpasero
- [x] Preserve casing in search/replace across files https://github.com/microsoft/vscode/issues/78397 @roblourens

### Editor
- [x] Support vim's scrollOff feature https://github.com/microsoft/vscode/issues/12048 @rebornix
- [x] Support multi-line search in the editor https://github.com/microsoft/vscode/issues/15727 https://github.com/microsoft/vscode/pull/79329 @rebornix
- [x] Cannot select deleted text in inline diff view (https://github.com/microsoft/vscode/issues/8226) @rebornix
- [x] Deprecated completion items & symbols https://github.com/microsoft/vscode/issues/50972 @jrieken

#### JavaScript/TypeScript
- [x] Adopt TypeScript 3.6 https://github.com/microsoft/vscode/issues/78973 @mjbvz

#### LSP
- [x] Add support for progress reporting for client initiated work https://github.com/microsoft/language-server-protocol/issues/70 and https://github.com/microsoft/vs-streamjsonrpc/issues/139 @dbaeumer
- [x] Explore support for reporting partial results (e.g. workspace symbols) https://github.com/microsoft/vs-streamjsonrpc/issues/139 @dbaeumer
- [x] Add support for deprecated indication in diagnostics https://github.com/microsoft/language-server-protocol/issues/815 @dbaeumer
- [ ] :runner: Productize the TypeScript LSIF indexer https://github.com/microsoft/lsif-node/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug @dbaeumer

#### CSS/HTML/JSON
- [x] Finalize experimental custom data support https://github.com/microsoft/vscode/issues/76914 @octref

### Debug
- [x] Support data breakpoints https://github.com/microsoft/vscode/issues/58304 @isidorn @weinand
- [x] Explore support for custom object formatters https://github.com/microsoft/vscode/issues/26234 @weinand

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2019%22+label%3A%22api-proposal%22)
- [x] Provide an icons repository for extension developers https://github.com/microsoft/vscode/issues/74974 @misolori
- [ ] :runner: Explore settings sync provider API https://github.com/microsoft/vscode/issues/78966 @sandy081
- [ ] :runner: Allow for [Completion|Symbol]Item tags/modifiers @jrieken https://github.com/microsoft/vscode/issues/23927

### Extension Contributions
- [x] Delete Branch after merging PR https://github.com/microsoft/vscode-pull-request-github/issues/350 @rebornix
- [x] Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/1135)) **team**
- [ ] :runner: ES Lint: TSLint -> ESLint migration (see [roadmap](https://github.com/palantir/tslint/issues/4534)) document how to use the eslint extension for TS linting @dbaeumer

### Engineering
- [ ] :runner: Continue exploring upgrade to Electron 6.0 https://github.com/microsoft/vscode/issues/76069 @deepak1556
- [ ] :runner: Increase automation for upgrading to newer Electron versions https://github.com/microsoft/vscode/issues/77159 @deepak1556
- [ ] :runner: Convert native modules to NAPI https://github.com/microsoft/vscode/issues/79137 @deepak1556
- [ ] :runner: Adopt `strictPropertyInitialization` https://github.com/microsoft/vscode/issues/78168 @alexandrudima **team**
- [x] Investigate performance of syntax coloring JS files https://github.com/microsoft/vscode/issues/77990 @mjbvz
- [x] Investigate to eliminate resource access through custom electron protocol handler https://github.com/microsoft/vscode-remote-release/issues/687 @alexandrudima

-------
### Deferred Items
- Option for merging single child directories with parent in the Explorer https://github.com/microsoft/vscode/issues/41627 @isidorn @joaomoreno
- Explore theming support for semantic colors https://github.com/microsoft/vscode/issues/77133 @aeschli
- Specify the LSIF indexer tool https://github.com/microsoft/lsif-node/issues/67 CLI @dbaeumer
- Explore aligning presentation of hovers and completion items https://github.com/microsoft/vscode/issues/78718 https://github.com/microsoft/vscode/issues/78717 @octref
- Identify the work required to use chrome process architecture https://github.com/microsoft/vscode/issues/79138 @deepak1556
- Revisit the tokenization implementation with the end goal to support asynchronous semantic coloring https://github.com/microsoft/vscode/issues/77140 @alexandrudima

**Comment by KevinWuWon** [comment]
Looking forward to the Custom Editors API!

**Comment by ackvf** [comment]
Awesome, can't wait for being able to copy deleted text from diff. Hurray 🎉 🎉 https://github.com/microsoft/vscode/issues/8226

**Comment by johnletey** [comment]
@kieferrm Here is the correct link to https://github.com/microsoft/vscode/issues/78889: `https://github.com/microsoft/vscode/issues/78889`

**Comment by equinusocio** [comment]
Please, please decrease the arrow size for code folding 😂  😂

**Comment by aeschli** [comment]
@equinusocio Please file a separate issue with your settings.

**Comment by DiamondYuan** [comment]
As a community contributor, I also hope to fix some issues and complete some feature.

**Comment by FFY00** [comment]
@DiamondYuan you could look into https://github.com/microsoft/vscode/issues/72298 if you have time. The official team doesn't want to spend time on it but is something that would really help the community.

**Comment by tristan957** [comment]
@FFY00 in the issue the team specifically asks you to point out the lines that need changing. I am sure someone would like to fix it, but you haven't responded in 8 days with the answer.

**Comment by jregistr** [comment]
> Option for merging single child directories with parent in the Explorer #41627

🤞 This is certainly my most anticipated feature in this release cycle. This is such a must for anyone in the JVM community.

**Comment by FFY00** [comment]
> @FFY00 in the issue the team specifically asks you to point out the lines that need changing. I am sure someone would like to fix it, but you haven't responded in 8 days with the answer.

I am not a JavaScript developer, still I have spent hours trying to fix this. That's why I opened the issue. If I knew how to fix it I would just open a pull request. The vscode team knows the codebase and given that this is not a difficult issue I am pretty sure they would be able to track down the source easily. I have projects that actually need my attention, I can't keep wasting time here just because the vscode team doesn't want to help.

**Comment by Beer1234** [comment]
> This plan captures our work in **August**. This is a 4-week iteration. We will **ship** our August Update **in early September**.
> 
> Although this is the last of the Summer vacation months for us, good work is coming your way. With our work on Custom Editors and the settings sync provider API exploration we continue to pushing the boundaries of what extensions can provide. We also work on the overall user experience with items such as improved minimap and multi-select in custom tree views, and we continue our journey to better performance with reworking tokenization. See below for all the details.
> 
> ## Endgame
> * **August 26, 2019**: Endgame begins
> * **August 30, 2019**: Endgame done
> 
> The endgame details for this iteration are tracked in **TBD**.
> 
> ## Plan Items
> Below is a summary of the top level plan items.
> 
> Legend of annotations:
> 
> Mark	Description
> 	work in progress
> 	blocked task
> 	stretch goal for this iteration
> 	missing issue reference
> 	more investigation required to remove uncertainty
> 	under discussion within the team
> ### UX
> * [ ]  running_man Update main extension icons to match new icon style #77411 @misolori
> * [ ]  running_man Update Octicons to match new icon style @misolori #76909
> * [ ]  running_man Explore settings sync UX @misolori @sandy081 #78869
> 
> ### Workbench
> * [ ]  running_man Implement workbench layout using grid widget #50853 @sbatten @joaomoreno
> * [x]  Support multi-selection in Custom Views #76941 @alexr00
> * [ ]  running_man Support for custom editors #77131 @mjbvz @jrieken
> * [x]  Show file search results in the minimap #78236 @RMacfarlane
> * [x]  running_man Polish settings with values that are lists of strings #79050 @octref
> * [x]  Provide link protection mechanism #78125 @octref
> * [x]  Simplify creation of top-level folder #1043 @isidorn
> * [x]  Allow workspace settings to override machine scoped settings #73985 @sandy081
> * [ ]  running_man Explore using icon fonts for product icons #78889 @misolori @bpasero
> * [x]  running_man Preserve casing in search/replace across files #78397 @roblourens
> * [ ]  running_man Explore aligning presentation of hovers and completion items #78718 #78717 @octref
> 
> ### Editor
> * [ ]  Revisit the tokenization implementation with the end goal to support asynchronous semantic coloring #77140 @alexandrudima
> * [x]  Support vim's scrollOff feature #12048 @rebornix
> * [x]  Support multi-line search in the editor #15727 #79329 @rebornix
> * [x]  running_man muscle Cannot select deleted text in inline diff view (#8226) @rebornix
> * [x]  running_man Deprecated completion items & symbols #50972 @jrieken
> 
> ### Languages
> #### JavaScript/TypeScript
> * [ ]  running_man Adopt TypeScript 3.6 #78973 @mjbvz
> 
> #### LSP
> * [x]  Add support for progress reporting for client initiated work [microsoft/language-server-protocol#70](https://github.com/microsoft/language-server-protocol/issues/70) and [microsoft/vs-streamjsonrpc#139](https://github.com/microsoft/vs-streamjsonrpc/issues/139) @dbaeumer
> * [x]  Explore support for reporting partial results (e.g. workspace symbols) [microsoft/vs-streamjsonrpc#139](https://github.com/microsoft/vs-streamjsonrpc/issues/139) @dbaeumer
> * [x]  running_man Add support for deprecated indication in diagnostics [microsoft/language-server-protocol#815](https://github.com/microsoft/language-server-protocol/issues/815) @dbaeumer
> * [ ]  -> defer Specify the LSIF indexer tool [microsoft/lsif-node#67](https://github.com/microsoft/lsif-node/issues/67) CLI @dbaeumer
> * [ ]  running_man Productize the TypeScript LSIF indexer https://github.com/microsoft/lsif-node/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug @dbaeumer
> 
> #### CSS/HTML/JSON
> * [x]  running_man Finalize experimental custom data support #76914 @octref
> 
> ### Debug
> * [x]  running_man Support data breakpoints #58304 @isidorn @weinand
> * [x]  running_man Explore support for custom object formatters #26234 @weinand
> 
> ### API
> * API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2019%22+label%3A%22api-finalization%22)
> * API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22August+2019%22+label%3A%22api-proposal%22)
> * [x]  Provide an icons repository for extension developers @misolori #74974
> * [ ]  running_man Explore settings sync provider API @sandy081 #78966
> * [ ]  running_man Allow for [Completion|Symbol]Item tags/modifiers @jrieken #23927
> 
> ### Extension Contributions
> * [x]  Delete Branch after merging PR [microsoft/vscode-pull-request-github#350](https://github.com/microsoft/vscode-pull-request-github/issues/350) @rebornix
> * [x]  Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/1135)) **team**
> * [ ]  running_man ES Lint: TSLint -> ESLint migration (see [roadmap](https://github.com/palantir/tslint/issues/4534)) document how to use the eslint extension for TS linting @dbaeumer
> 
> ### Engineering
> * [ ]  running_man Continue exploring upgrade to Electron 6.0 #76069 @deepak1556
> * [ ]  running_man Increase automation for upgrading to newer Electron versions #77159 @deepak1556
> * [ ]  running_man Convert native modules to NAPI #79137 @deepak1556
> * [ ]  Identify the work required to use chrome process architecture #79138 @deepak1556
> * [ ]  Adopt `strictPropertyInitialization` #78168 @alexandrudima **team**
> * [ ]  Investigate performance of syntax coloring JS files #77990 @mjbvz
> * [x]  Investigate to eliminate resource access through custom electron protocol handler [microsoft/vscode-remote-release#687](https://github.com/microsoft/vscode-remote-release/issues/687) @alexandrudima
> 
> ### Deferred Items
> * running_man Option for merging single child directories with parent in the Explorer #41627 @isidorn @joaomoreno
> * Explore theming support for semantic colors #77133 @aeschli
