### ISSUE TITLE
String array Setting GUI improvements

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#79050]
- [x] [Settings GUI] String array: No help in filling enum values #77458
- [x] [Settings GUI] String array: maxItems & minItems ignored #77459
- [ ] Settings UI: When "Add Item" out of view port, have to click 2x #78237 @roblourens 
- [ ] String Settings UI: Multiple edits loses data on Save #78243
- [ ] ~~[Settings GUI] String array: Icons should inherit focused/selected themable colors~~ #78292

**Comment by octref** [comment]
Was for issue tracking purpose — closing.
