### ISSUE TITLE
Iteration Plan for September 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#80591]
This plan captures our work in **September**. This is a 5-week iteration. We will **ship** our September Update **in early October**.

This iteration will be followed by a housekeeping iteration in October. Before we focus on issue grooming and issue reduction, we want to make progress on work we started in the Summer such as the API for custom editors and settings sync providers, or our overhaul of how tokenziation works in the editor. We also will spend some time polishing our UI. Examples are improving the presentation of hovers and completion items and alignment octicons with our new icon style. See below for details.

## Endgame

- **Sept 30, 2019**: Endgame begins
- **Oct 4, 2019**: Endgame done

The endgame details for this iteration are tracked in **tbd**.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [x] :runner: Update Octicons to match new icon style https://github.com/microsoft/vscode/issues/76909 @misolori
- [x] :runner: Explore settings sync UX https://github.com/microsoft/vscode/issues/78869 @misolori @sandy081

### Workbench
- [ ] :runner: Support for custom editors https://github.com/microsoft/vscode/issues/77131 @mjbvz @jrieken
- [ ] :runner: Use icon fonts for product icons https://github.com/microsoft/vscode/issues/78889 @misolori @bpasero
- [x] :runner: Implement a compressible tree widget https://github.com/microsoft/vscode/pull/77876 @joaomoreno
- [ ] :runner: Option for merging sequences of single child directories in the Explorer (compressible tree widget) https://github.com/microsoft/vscode/issues/41627 @joaomoreno @isidorn
- [x] :runner: Explore aligning the presentation of hovers and completion items https://github.com/microsoft/vscode/issues/78718 @octref
- [x] Show current selection in the minimap https://github.com/microsoft/vscode/issues/21404 @rmacfarlane
- [x] Polish link protection UI https://github.com/microsoft/vscode/issues/80595 @octref @misolori
- [x] :runner: Polish workbench gridlayout [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+assignee%3Asbatten+milestone%3A%22September+2019%22+label%3Aworkbench-layout) @sbatten

### Editor
- [x] Publish a new version of the Monaco editor https://github.com/microsoft/monaco-editor/releases/tag/v0.18.0 @rebornix
- [ ] :runner: Revisit the tokenization implementation with the end goal to support asynchronous semantic coloring https://github.com/microsoft/vscode/issues/77140 @alexandrudima
- [ ] :runner: Explore theming support for semantic colors https://github.com/microsoft/vscode/issues/77133 @aeschli

### Languages
- [ ] :runner: Support for a Call Hierarchy navigation https://github.com/microsoft/vscode/issues/70231 @jrieken

#### LSP / LSIF
- [x] Update LSP spec to version 3.15 https://github.com/microsoft/language-server-protocol/tree/dbaeumer/3.15 @dbaeumer
- [x] Support deprecated Symbols https://github.com/microsoft/vscode-languageserver-node/issues/450 @dbaeumer
- [ ] :runner: Productize the TypeScript LSIF indexer https://github.com/microsoft/lsif-node/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug @dbaeumer
- [x] Specify the LSIF indexer tool CLI https://github.com/microsoft/lsif-node/issues/67 @dbaeumer
- [ ] :muscle: Support Call Hierarchy navigation https://github.com/microsoft/language-server-protocol/issues/468 @dbaeumer

#### CSS/HTML/JSON
- [x] Add semicolon on autocompletion of css properties https://github.com/microsoft/vscode/issues/32200 @octref

### Debug
- [x] Allow reloading/stopping/pausing sessions inline in the tree https://github.com/microsoft/vscode/issues/79189 @isidorn @weinand
- [x] Support cancellation in DAP communication https://github.com/microsoft/vscode/issues/80374 @isidorn @weinand
- [x] Enable to combine Debugger console for multiple sessions in a single console https://github.com/microsoft/vscode/issues/62419 @isidorn @weinandÂ 
- [x] Support visual hints for inline breakpoints (add support in protocol https://github.com/microsoft/debug-adapter-protocol/issues/72, explore UI https://github.com/microsoft/vscode/issues/31612) @isidorn @weinand

### SCM
- [x] Adopt compressed trees in the SCM view @joaomoreno
  - Show changes in tree-like format https://github.com/microsoft/vscode/issues/14582
  - Support view filter https://github.com/microsoft/vscode/issues/30199

### Terminal
- [x] Publish `xterm.js` v4 https://github.com/xtermjs/xterm.js/milestone/22 @tyriar

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22September+2019%22+label%3A%22api-proposal%22)
- [ ] :runner: Remove the deprecated `rootPath` https://github.com/microsoft/vscode/issues/69335 @roblourens
- [x] Allow for [Completion|Symbol]Item tags/modifiers https://github.com/microsoft/vscode/issues/23927 @jrieken
- [ ] :runner: Explore settings sync provider API https://github.com/microsoft/vscode/issues/78966 @sandy081

### Extensions
- [ ] Support for installing extensions with platform specific dependencies https://github.com/microsoft/vscode/issues/23251 @joaomoreno

### Extension Contributions
- [ ] Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/1390)) **team**

### Engineering
- [ ] :red_circle: Explore converting SCM smoke tests into integration tests @joaomoreno
- [x] Align TSB with 'tsc -watch' behaviour (file discorvery) @jrieken
- [ ] :runner: Continue exploring upgrade to Electron 6.0 https://github.com/microsoft/vscode/issues/76069 @deepak1556
- [ ] :runner: Adopt `strictPropertyInitialization` https://github.com/microsoft/vscode/issues/78168 @alexandrudima **team**
- [x] :runner: Work with Chromium on issue https://bugs.chromium.org/p/chromium/issues/detail?id=978325 @mjbvz
- [x] Bump Chromium version of electron 8 https://github.com/electron/electron/pull/19923 @deepak1556

-------

### Deferred Items
- Identify the work required to use chrome process architecture https://github.com/microsoft/vscode/issues/79138 @deepak1556
- :runner: Increase automation for upgrading to newer Electron versions https://github.com/microsoft/vscode/issues/77159 @deepak1556
- :runner: Convert native modules to NAPI https://github.com/microsoft/vscode/issues/79137 @deepak1556
- :runner: Improve keyboard support for in completion item lists https://github.com/microsoft/vscode/issues/24918 @octref
- Explore Saas variable completion across files https://github.com/microsoft/vscode/issues/6734 @octref

**Comment by mhermis2011** [comment]
I went to view fullscreen mode and now I can't exit full screen mode even when I shut the app down and reopen it

**Comment by dalisoft** [comment]
Maybe anyone from VSCode team wanna fix https://github.com/microsoft/vscode/issues/76537? Or available alternative to VSCode with same design (especially GUI find), maybe Oni v2?

**Comment by xiaok0928** [comment]
If you can, can you include the #29126 problem in the plan? After all, many people are worried about it.

**Comment by linuxjh** [comment]
please fix this for outline view:
Adopt new DocumentSymbol API #2230

**Comment by kanlukasz** [comment]
Why are you returning to the older Electron?

From what I see, the last but one Insider update was
```
Version: 1.39.0-insider
Commit: 575062278d181c075ea8dce345ab3d20a127309c
Date: 2019-09-20T06:11:13.647Z

Electron: 6.0.9

Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Now we have:
```
Version: 1.39.0-insider
Commit: 79978f96d3501f14b235ed0a33a7360772a726a3
Date: 2019-09-30T14:18:14.941Z

Electron: 4.2.10

Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by Tyriar** [comment]
@kanlukasz see https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron-blocker

**Comment by jregistr** [comment]
🤞 🤞 🤞  Option for merging sequences of single child directories in the Explorer (compressible tree widget) #41627 @joaomoreno @isidorn

**Comment by danilaml** [comment]
@Tyriar both open issues seem to be already fixed in Electron.

**Comment by Tyriar** [comment]
@danilaml they are now because the team has been working on them. It's too risky to update Electron for this version though.

**Comment by TonioGela** [comment]
@jregistr apparently no luck, it's marked as still in progress :(
