### ISSUE TITLE
Link Protection Improvements

### ISSUE THREAD

**Issue by octref** [microsoft/vscode#80595]
- [x] Allow adding trusted domains #80010
- [x] Link protection ux is confusing #80489
- [x] Link protection UI inconsistency #79900
- [x] Add a setting for disabling link protection #80592
- [x] Reset trusted domains list for link protection #80333

**Comment by octref** [comment]
The new dialog is more clearer:

![image](https://user-images.githubusercontent.com/4033249/64928938-cd109c80-d7d3-11e9-97fa-36bdf2e9828d.png)

And the configuration process becomes editing a JSON file (for the 3rd option above):

![image](https://user-images.githubusercontent.com/4033249/64928947-e9143e00-d7d3-11e9-90ea-8e39da9349fe.png)

These two commands will be available:

![image](https://user-images.githubusercontent.com/4033249/64928949-f0d3e280-d7d3-11e9-979a-1a7c337ef5df.png)

**Comment by octref** [comment]
@jrieken In Redmond we discussed how we can improve the link protection configuring experience, but we realize QuickInput is not the right widget for all CRUD operations. So I went with the approach of having a FS provider and let use configure the JSON setting.

I see https://github.com/microsoft/vscode/issues/10547 and @Tyriar is interested in having something similar for editing an in-memory item in terminal area. I'm wondering if we should have a dedicated schema for such use cases.

**Comment by aeschli** [comment]
@octref Why is the list of trusted domains not part of the (user) settings?
That way it will be profit from our synced-settings story.

**Comment by aeschli** [comment]
Can you describe what is there to verify (I have the feeling this would even deserve it's own test item...)

**Comment by Tyriar** [comment]
@aeschli because an extension could just write the settings and bypass the security feature completely.

**Comment by aeschli** [comment]
@Tyriar Extensions can cause much worse things to your machine than hiding a 'Do you want to open an external website...' dialog.

**Comment by octref** [comment]
> Extensions can cause much worse things to your machine than hiding a 'Do you want to open an external website...' dialog.

That's exactly what I said, but I think @Tyriar has a point: Just because extensions can make worse things happen doesn't mean we should not care about security at all.

I had the idea of having private settings that should only be writable by users and programmatically by itself. For example `eslint` can set settings of `eslint.*` but not `tslint.*`. But that wouldn't completely solve the problem because extension can just modify settings through file system.

**Comment by samrat-gavale** [comment]
@octref how is this to be handled in an enterprise scenario? e.g. like when an engineering services team wants to create a one-click setup for a development environment, which consists of a couple of extensions pointing users to a bunch of external sites? Currently there is no way but to ask each developer to configure those domains.

**Comment by octref** [comment]
@samrat-gavale I opened #82794 but I don't have a plan yet. If you have a good suggestion how this might work, please follow up in that thread.
