### ISSUE TITLE
Iteration Plan for October 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#82194]
This plan captures our work in **October**. This is a 4-week iteration. We will ship our October Update in **early November**. 

This is our annual issue house keeping iteration. You'll see a large number of GitHub issue notifications over the course of this iteration. If you want to track our progress, the community has us covered: https://vscode-github-stats.netlify.com/

If you are interested in why we have issue house keeping iterations and in our general philosophy around issue management, then we have this [write-up](https://github.com/microsoft/vscode/wiki/Issue-Grooming) for you.

## Endgame
- **October 28th, 2019**: Code freeze for the endgame
- **November 1st, 2019**: Endgame done

The endgame details for this iteration are tracked in **TBD**.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark | Description |
| ------------- | ------------- |
| :runner: | work in progress |
| :hand: | blocked task |
| :muscle: | stretch goal for this iteration |
| :red_circle: | missing issue reference |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle: | under discussion within the team |

### Housekeeping
- [ ] :runner: Issue/PR Grooming - review, categorization, assignment https://github.com/microsoft/vscode/issues/82032 **team**
- [x] Design and document revised workflow of how we triage issues https://github.com/microsoft/vscode/issues/83124 @kieferrm **team**
- [ ] :runner: Implement revised issue triaging workflow https://github.com/microsoft/vscode/issues/83125 @kieferrm **team**

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22October+2019%22+label%3A%22api-finalization%22)

### Engineering
- [x] :runner: Continue exploring upgrade to Electron 6.0 https://github.com/microsoft/vscode/issues/76069 @deepak1556
- [ ] :runner: Adopt `strictPropertyInitialization` https://github.com/microsoft/vscode/issues/78168 **team**
- [ ] :runner: Adopt `enableStrictFunctionTypes` https://github.com/microsoft/vscode/issues/81574 **team**

-------

### Deferred Items
- All work that was in-flight end of September. We'll resume that work in early November.

**Comment by linuxjh** [comment]
Still, please fix this for C++ Outline View. It's more important than all the other features like color scheme, font setting, etc..
Adopt new DocumentSymbol API
https://github.com/microsoft/vscode-cpptools/issues/2230

**Comment by egamma** [comment]
@linuxjh this is the iteration plan for VS Code team and the VS Code editor. You are asking for a fix in an extension which is maintained by another team. 

Please check the issue you are asking to be fixed... it has been fixed in the meantime, please see https://github.com/microsoft/vscode-cpptools/issues/2230#issuecomment-536695862

**Comment by linuxjh** [comment]
I tried the insider release but it failed to be installed

**Comment by lcswillems** [comment]
Is it planned to support TypeScript 3.7?

**Comment by DeltaRazero** [comment]
Hopefully we can see the upgrade to Electron 6 real soon, lots of good progress is being made :)

**Comment by crper** [comment]
explorer Electron 7 ? now latest

https://electronjs.org/

![image](https://user-images.githubusercontent.com/8272877/67273848-d509dd80-f4f1-11e9-9290-5bb736783686.png)

**Comment by yogeshkotadiya** [comment]
@crper Since Electron 7 is now out, Electron 8 Beta will start to roll out soon. So I think the team should start with Electron 8 and skip the 7 just like they did with v5 becasue as we can see it takes a lot of time to update VSCode to the new Electron version.

**Comment by ddzy** [comment]
> I tried the insider release but it failed to be installed

Maybe you should reinstall your system😄
