### ISSUE TITLE
Provide encoding-related APIs for editor extensions

### ISSUE THREAD

**Issue by haoqunjiang** [microsoft/vscode#824]
Currently there are only two fields in the TextEditorOptions API, a few other TextEditor-related APIs, and none of them is able to deal with the text buffer's encoding.
Comparing to [Atom's TextEdit API](https://atom.io/docs/api/v1.2.4/TextEditor), that is far from enough.

Most importantly, the API limitation makes it (seems) impossible for vscode-editorconfig to implement features like `charset` support, which is a crucial need for many people.

**Comment by alexandrudima** [comment]
:+1: Also `trimTrailingWhitespaces` is missing

**Comment by kmpm** [comment]
#751 and #844 would probably be helped by this as well.
At least #751 would be solvable if working with BOM were better and my issues would completely go away if there was a way to, per editor extension, set the encoding and other stuff.
So :+1:

**Comment by jedmao** [comment]
We also need access to the end of line sequence for EditorConfig.

**Comment by jrieken** [comment]
* [ ] set/get encoding
* [ ] set/get charset

**Comment by iHuahua** [comment]
T_T... my extension ......

**Comment by buzzzzer** [comment]
still backlog... :(

**Comment by Dickurt** [comment]
I also need this for my extension, as I explain [here](https://github.com/Microsoft/vscode/issues/11690). Did not realize this issue already existed.

**Comment by tomasiser** [comment]
I believe that full `.editorconfig` support is blocked (https://github.com/editorconfig/editorconfig-vscode/issues/35) until the API for buffer encoding is added. Is there any chance this fact could speed this up?

**Comment by jedmao** [comment]
@tomasiser is correct. This is the last feature for full EditorConfig support.

**Comment by afucher** [comment]
any news?

**Comment by irudoy** [comment]
any news?

**Comment by takekazuomi** [comment]
any news?

**Comment by pixelhuh** [comment]
any news?

**Comment by Ryshyi** [comment]
any news?

**Comment by bizoo** [comment]
Does this issue have any chance to be resolved ?
I didn't find a way to work with a multi-encoding project (git repository), someone can help ?

**Comment by chongchai** [comment]
any news? As @bizoo said,  my multi-encoding project (git repository) will get problem in git diff view.

**Comment by gingerbeardman** [comment]
please say this is coming soon?

**Comment by irudoy** [comment]
This will be implemented after the Half-Life 3 release, I think 🤔

**Comment by brainz80** [comment]
Why does there seem to be so little interest in implementing this into the API? I don't believe it should be too difficult to do.

**Comment by brainz80** [comment]
How is this issue handled? I See it's in the backlog but very far down. How are issues handled from the backlog? Could this perhaps be bumped up?

**Comment by irudoy** [comment]
There are much more important features that should be implemented. For example, in May, it was done:
- [x] Explore improved positioning of the debug toolbar #2513 (WOW)
- [x] Recommend language packs based on the locale of the OS #45663 (AMAZING)
- [x] Custom view API enhancements: Support to listen the expand/collapse state #30535 (such a collapse API, BOOM)
- [x] Cosmetic changes to issue reporter #49579 (😱)

Encoding-related issues have low priority, because they are related to text editing. As you might guess, text editing is not important for a text editor.

**Comment by AGraber** [comment]
:rage4:

**Comment by brainz80** [comment]
@bpasero, @jrieken Care to take a look at this? 

This issue was brought up by @sodatea [(his comment)](https://github.com/Microsoft/vscode/issues/824#issue-119514111) on November of 2015 and a similar issue seems to be reported here [#34](https://github.com/ikappas/vscode-phpcs/issues/34) from February of 2017. It would be nice if you could provide any explanation / "definitive no" if implementing these aren't possible -- my understanding is that you guys should be familiar with the API.

This issue has forced me to use other editors instead (Atom, Sublime Text) - in my work I have to constantly switch between files with different encodings and line-endings. Without [editorconfig](https://editorconfig.org/) this would most likely end in a disaster.

**Comment by mi-hol** [comment]
@joaomoreno @bpasero @jrieken this issue is blocking phpcs 'PHP CodeSniffer for Visual Studio Code' from being used to its full potential. Any change to consider closing this to get more php coders into the user base?

**Comment by edgardmessias** [comment]
With access to 'encoding' of file, the diff gutter of GIT and SVN can improved (when `files.autoGuessEncoding` is `true`)

**Comment by brainz80** [comment]
@joaomoreno @bpasero @jrieken this issue keeps being unresolved. Would be nice if you guys at least had a shout here. So we'd know we're not just barking at trees

**Comment by gingerbeardman** [comment]
Woof woof woof (one for each year this bug has been alive)

**Comment by brainz80** [comment]
@alexandrudima I see you're a dev of VS Code. Could you shed some light on this matter?

**Comment by mechatroner** [comment]
For me it would be great to have at least `get_encoding()`, unlike `set_encoding()` it should be much easier to implement.

**Comment by shiyugege** [comment]
please  support multi charset

**Comment by csaar95** [comment]
any news on this?

**Comment by KUGA2** [comment]
Any news here?

**Comment by gingerbeardman** [comment]
5 years!?

**Comment by jamilraichouni** [comment]
This is needed!

Similar to

`vscode.window.activeTextEditor.document.eol`

something like

`vscode.window.activeTextEditor.document.encoding`

is needed and I can imagine multiple use cases.

In my case (some own extension) I want to process a VSCode document's content with some external processing tool.
That tool must for sure be aware of the encoding to do a good job.

Thank you,
Jamil

**Comment by gingerbeardman** [comment]
5 years!?

**Comment by kristian-b** [comment]
Any news? Without this feature the editorconfig extension is very limited. In my legacy projects VS code is destroying my latin1 files again and again.

**Comment by themikesam** [comment]
2021 now :smile:

**Comment by Leif-W** [comment]
Coming up on 6 years, no response.  How can we get this issue resolved?  Consider how the project prioritizes things.

From vscode's README.md, under section Feedback, Upvote [popular feature requests](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afeature-request+sort%3Areactions-%2B1-desc).  This indicates to me that maybe the team is probably busy and does not even bother reading anything not on the first few pages.

The URL specifies `sort:reactions-+1-desc`, which counts the number of thumbs-up emojis.  Whether this is for the initial comment only, or the issue total upvotes, I am not sure.  I doubt it even subtracts down votes.  It's likely not really a valid "voting" method, just an approximation of positive popularity.  (One issue could have 10 up votes on first comment, 10 million down votes, and still be ranked higher than an issue with 1 up vote on first comment and 20 million up votes on second comment).  Again, I do not know what algorithm GitHub uses to calculate the value held in the up vote column that is being sorted, so my guess may be wrong.

Looking at the actual up vote sorted list.  The first item on the list has nearly 3,000 up votes (thumb up emoji) on the first comment.  The second item has nearly 2,000 up votes on the first comment.  The first item on this issue has 87 votes at time of writing.

So what can be done to get the issue resolved?  Assuming this passive mode is pursued, then we go for higher visibility.  Everyone that visits, up vote spam the first comment, possibly every comment, and add a comment.  Advertise the issue prominently on highly visible projects.  Get entire teams to up vote.  Make click bait videos and a campaign of memes.  Post on social media, mailing lists, forums.  And so on.  Big investment of energy for a passive request which will likely be ignored until it can't (say 5,000-10,000 up votes, twice the first two combined, possibly doubled, ought to be overwhelming enough).

Or, a fraction of thst time and energy could be spent by 1 or a few people to actually fix the problem and submit a pull request.  Prior to the Feedback section in the README.md is the Contributing section.  This informs us that contributions might be regarded with higher priority by the team.  I see no pull requests associated with this issue.  If such pull requests exists, great, maybe focus energy there and get any tweaks necessary for a pull to be completed.  If not, have a look at the contribution guidelines, build vscode project, and start hacking.

**Comment by lygstate** [comment]
What's the hard part to expose this API?

**Comment by mozhuanzuojing** [comment]
In 2022, the enhancement of coding should join the milestone. VSCode team.

**Comment by gingerbeardman** [comment]
6+ years LOL

**Comment by lygstate** [comment]
maybe we can create a pr for this？

**Comment by sophodoros** [comment]
This feature was first requested back in 2015 when VSCode was just emerging from the primordial ooze. VSCode has come a long way since then, but still no encoding support in the extension API?

Perhaps a full-blown feature that allows the encoding to be modified is too far down the priority list. However, it seems like it shouldn't be too difficult to add a simple read-only `encoding` property to `TextDocument`. After all, the encoding is already displayed in VSCode's status bar along with the language (TypeScript, etc), which IS supplied via the `TextDocument.languageId` property. 

Even if the value shown in the status bar is a guess as seems to be suggested in earlier comments, it would be better than nothing. As an extension writer, I'd rather use VSCode's best guess at the encoding than try to figure it out on my own.

**Comment by gingerbeardman** [comment]
The most sane way to get features like this, or column select, is to use a different editor. IMHO

**Comment by lygstate** [comment]
ping for it

**Comment by Tarrowren** [comment]
I looked at the code and I thought the coding was tied to the document, but it's actually tied to the editor.

I spent some time exposing it to the `TextEditor API`

```typescript
/**
 * Represents an editor that is attached to a {@link TextDocument document}.
 */
export interface TextEditor {
  ...

  getEncoding(): Promise<string | undefined>;

  setEncoding(encoding: string, mode: "encode" | "decode"): Promise<void>;
}
```

and then in the json extension using

```typescript
export async function activate(context: ExtensionContext) {
  ...

  const editer = window.activeTextEditor;
  if (editer) {
    outputChannel.appendLine("ok");
    outputChannel.appendLine((await editer.getEncoding()) ?? "null");
    await editer.setEncoding("utf16be", "encode");
    outputChannel.appendLine((await editer.getEncoding()) ?? "null");
  }
}

```

It worked! When opening the file he changed the document from utf8 to utf16be.

![1](https://user-images.githubusercontent.com/35626141/223909837-15a68371-5807-4333-812b-880813d38033.png)

**Comment by Tarrowren** [comment]
I have moved it to `TextEdit` and it now works like this

```typescript
toDispose.push(
  workspace.onWillSaveTextDocument((e) => {
    e.waitUntil(Promise.resolve([TextEdit.setEncoding("utf8")]));
  })
);

// or

window.activeTextEditor.edit((textEdit) => {
  textEdit.setEncoding("utf8");
});
```

But `encoding` needs to be added to the `UndoRedoSnapshot`, and I haven't implemented it yet.

And I didn't follow the rules of eslint(local/code-import-patterns) and couldn't submit the code, so I had to return to the previous method.

If I want to provide `encoding` in the `TextDocument`, I tried it and it requires a lot of code changes, there may be other simpler ways to do it.

I've spent a lot of time on this and now I'm going back to work😥.

https://github.com/Tarrowren/vscode/tree/textedit-encoding

**Comment by lygstate** [comment]
@takekazuomi  do you create a MR for this?

**Comment by denniskp** [comment]
C'mon guys, the PR is already there. Please check it out https://github.com/microsoft/vscode/pull/177434

**Comment by leaumar** [comment]
I was getting ready to file a bug against editorconfig for this. That the *microsoft-affiliated editor* does not let editorconfig safeguard the charset of *windows-specific files that cannot be in utf8* is **too** ironic and not funny in 2024. When merge?

**Comment by gingerbeardman** [comment]
We're now up to 230K+ issues, and this is issue 824, from 2015, it has a PR, yet we are still waiting? 🙃

**Comment by mozhuanzuojing** [comment]
确实，我也从20年等到今天

**Comment by mozhuanzuojing** [comment]
把这个问题在里程碑下面讨论一下

**Comment by xlilos** [comment]
Thanks for taking this one on @bpasero, for my extension, I think the APIs you are proposing would fit all the needs. Maybe there is some case for adding encoding parameters in FileSystemProvider interfaces so the provider could enforce some encoding for the underlying resource as need be. That said, someone could still get the encoding from the text document because they have the URI, probably more of a "nice to have".

One other potential use case outside of the extension API could be a CLI option to set encoding for opening a file or diffing/merging files. Although you could mitigate this with user/extension encoding config defaults (until someone overrides them...).

**Comment by bpasero** [comment]
> Finally, are people expecting extension APIs to convert raw Uint8Array to different encodings?

Fyi we are now also pushing proposed API in https://github.com/microsoft/vscode/pull/241160 to `encode` and `decode` between `Uint8Array` and `string`. Optionally allowing to set the `encoding` to use, with a fallback to using the rules VS Code applies.

**Comment by bpasero** [comment]
All, here is an updated proposal for API related to encoding/decoding:

```ts
export interface TextDocument {
	readonly encoding: string;
}

export namespace workspace {
	export function openTextDocument(uri: Uri, options?: { encoding?: string; }): Thenable<TextDocument>;
	export function openTextDocument(path: string, options?: { encoding?: string; }): Thenable<TextDocument>;
	export function openTextDocument(options?: { encoding?: string; }): Thenable<TextDocument>;

	export function decode(content: Uint8Array, uri: Uri | undefined, options?: { encoding: string }): Thenable<string>;
	export function encode(content: string, uri: Uri | undefined, options?: { encoding: string }): Thenable<Uint8Array>;
}
```

I think that `TextDocument.encoding` and the `encode`/`decode` methods on `workspace` are pretty straightforward and have a good chance of being finalised.

As for `openTextDocument` there is some caveats to be aware of:
* this will read the contents of the file from the file system and convert based on the encoding
* this CAN result in a change of the content of the document for any extension that has the document opened
* this method THROWS if the document is dirty because in that case we cannot force revert the file to the version on disk

Finally, I am not seeing a good use case for the initially suggested `save({ encoding: })` proposed API. I would not want to add API as final that in the end has no use cases, so I am asking for feedback here as well if there is any scenario for having it.

**Comment by SunsetTechuila** [comment]
@bpasero hello! So which API can be used to change the encoding of an already opened document? If none of the proposed, I would ask to add one

**Comment by bpasero** [comment]
@SunsetTechuila `openTextDocument` with an `encoding` will always attempt to read the contents of the document from the file system and convert it based on the `encoding` provided. If there are characters that previously did not render or now cannot render, the content of the document changes, signalled by events.

Thing is, if the document is dirty (has changes by the user), we cannot force this to happen. We can also not really just save the document because it may result in broken contents, given the encoding maybe wrong.

If you call `openTextDocument` with an encoding that is different than what is currently set, this will cause the encoding of the document to change.

Thinking about this more, I wonder if we need a way to change the encoding of the document without forcing it to save. We do not really offer this to the user today, we only have these 2 options:

<img width="724" alt="Image" src="https://github.com/user-attachments/assets/2acdcc56-48f0-43ac-9338-5a1012dee57a" />

Maybe in that case, we go back to having the `encoding` in the `save` method 🤔 

Can you clarify the use case here?

**Comment by bpasero** [comment]
With the new proposed APIs already pushed, one could emulate the `save(encoding)` routine:
* take the value of a `TextDocument` as string
* use `workspace.encode` to get the `Uint8Array` for a specific desired encoding
* use `workspace.fs` to write the bytes to disk at the location of `TextDocument`
* use the `openTextDocument` API to open the document with that encoding

**Comment by bpasero** [comment]
Continues in https://github.com/microsoft/vscode/issues/241449 for finalisation. I encourage extension authors to play with the proposed API and report issues as they encounter them. Thanks 🙏

**Comment by bpasero** [comment]
Fyi we plan to finalise the API for our April release: https://github.com/microsoft/vscode/pull/246016
