### ISSUE TITLE
Iteration Plan for November 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#83930]
This plan captures our work in **November**. This is a 5-week iteration. We will **ship** our November Update **in early December**.

Last month we focussed on getting our issue database back in shape and we made [great progress](https://vscode-github-stats.netlify.com/). As this included bug fixing and debt work, unlike in other months, we'll start with feature work right away and skip our typical debt week. Unsurprisingly, November is densely packed with feature work all across VS Code. It stretched from addressing paper cuts all the way to big-rock items such as settings sync and more flexible workbench layout. You also see a new `Web` section. With the public availability of [Visual Studio Online](https://online.visualstudio.com) you can now use VS Code also in the browser and we'll surface any related future work on our iteration plans.

## Endgame

- **December 2nd, 2019**: Endgame begins
- **December 6th, 2019**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/85959.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [X] :runner: Create a design toolkit for extension authors https://github.com/microsoft/vscode/issues/83952 @misolori
- [ ] :muscle: Identify design inconsistencies with UI + JSON experiences https://github.com/microsoft/vscode/issues/84309 @misolori

### Workbench
- [ ] :runner: Support for custom editors https://github.com/microsoft/vscode/issues/77131 @mjbvz @jrieken @bpasero
- [x] Compressed tree support in the explorer (merging sequences of single child directories in the Explorer) https://github.com/microsoft/vscode/issues/41627 @joaomoreno
- [ ] :runner: Settings sync support (settings, extensions, key bindings, snippets) https://github.com/microsoft/vscode/issues/2743 @sandy081
- [ ] :runner: Provide login support for settings sync https://github.com/microsoft/vscode/issues/84332 @rmacfarlane
- [X] Use icon fonts for product icons https://github.com/microsoft/vscode/issues/78889 @misolori @bpasero
- [x] Show SCM decorations in the minimap https://github.com/microsoft/vscode/issues/20934 @rmacfarlane
- [x] Support search as you type across files https://github.com/microsoft/vscode/issues/46326 @jacksonkearl
- [x] Support auto-expanding all search results in the search viewlet https://github.com/microsoft/vscode/issues/83917 @jacksonkearl
- [x] Copy search results in a search-results editor https://github.com/microsoft/vscode/issues/23931 @jacksonkearl
- [x] Filter by type in problems view https://github.com/microsoft/vscode/issues/47354 @sandy081
- [x] Show problems only for current active file - https://github.com/microsoft/vscode/issues/30038  @sandy081
- [x] Show current error in status bar - https://github.com/microsoft/vscode/issues/20183  @sandy081
- [x] Improve trusted domain support for url shorteners https://github.com/microsoft/vscode/issues/83731 @octref
- [ ] :runner: Allow to move sidebar views to the panel and vice versa https://github.com/microsoft/vscode/issues/85164 @sbatten
- [x] Polish custom dialogs with long contents (such as the open url confirmation) @sbatten
- [x] Explore how to improve existing notebook implementations https://github.com/microsoft/vscode/issues/84293 @rebornix

### Editor
- [ ] :runner: Semantic coloring - VS Code Language API and implementation https://github.com/microsoft/vscode/issues/77140 @alexandrudima
- [ ] :runner: Semantic coloring - Syntax tokens and theming https://github.com/microsoft/vscode/issues/77133 @aeschli
- [x] Improve the editor release process with automated builds and tests [monaco-editor#1668](https://github.com/microsoft/monaco-editor/issues/1668) @rebornix

### Terminal
- [x] Experimental WebGL renderer https://github.com/microsoft/vscode/issues/84949 @Tyriar

### Languages
- [x] Finish Call Hierarchy navigation and align it with the find all references support https://github.com/microsoft/vscode/issues/83419, https://github.com/microsoft/vscode/issues/83274 @jrieken
- [x] Review and polish existing code navigation gestures, https://github.com/microsoft/vscode/issues/83752 @jrieken
- [x] Run reference search when running go-to-symbol command on target, https://github.com/microsoft/vscode/issues/73081 @jrieken
- [x] Show keybindings in `Refactor` menu https://github.com/microsoft/vscode/issues/84101 @mjbvz
- [ ] :runner: Explore how extensions can announce all refactorings they support https://github.com/microsoft/vscode/issues/82718 @mjbvz

#### LSP / LSIF
- [x] Finalize LSP spec [version 3.15](https://github.com/microsoft/language-server-protocol/tree/dbaeumer/3.15) @dbaeumer
- [x] Support Call Hierarchy navigation https://github.com/microsoft/language-server-protocol/issues/468 @dbaeumer

#### CSS/HTML/JSON
- [x] Improve performance of emmet in large `html` files https://github.com/microsoft/vscode/issues/71996 @octref
- [x] Explore Saas variable completion across files https://github.com/microsoft/vscode/issues/6734 @octref
- [x] Improve ranking of `css` properties based on statistics like `chromestatus.com` https://github.com/microsoft/vscode/issues/3145 @octref
- [x] Improve performance of auto-rename tag (core or extension contribution) https://github.com/microsoft/vscode/issues/47069 @octref
- [ ] :runner: Publish blog post about our custom data support https://github.com/microsoft/vscode/issues/83928 @octref
- [x] Support SCSS Modules https://github.com/microsoft/vscode/issues/81943 @octref

#### TypeScript/JavaScript
- [X] Adopt TS v3.7 https://github.com/microsoft/vscode/issues/83935 @mjbvz

### Debug
- [x] Investigate into using language service support for scope resolution https://github.com/microsoft/vscode/issues/84044 @weinand
- [x] Improve initial debug / run experience https://github.com/microsoft/vscode/issues/84677 @isidorn @weinand
- [x] Debug console - Improve presentation of input/output https://github.com/microsoft/vscode/issues/37363 @isidorn
- [x] Improve discoverability of 'Restart Frame' https://github.com/microsoft/vscode/issues/84045 @isidorn
- [ ] :runner: Improve support for PWAs https://github.com/microsoft/vscode-pwa/issues/56 @connor4312 @roblourens

### SCM
- [ ] :runner: Explore File History view https://github.com/microsoft/vscode/issues/84297 @eamodio
- [ ] :runner: Investigate a more organic integration between GitLens with the core SCM https://github.com/microsoft/vscode/issues/84300 @eamodio
- [x] Adopt FileSystemProvider API: https://github.com/microsoft/vscode/issues/55110 @joaomoreno

### Extensions
- [x] Support extensions that can run locally and remotely (multiple extension kinds) https://github.com/microsoft/vscode/issues/85036 @sandy081 @alexandrudima
- [x] Adopt new extension kind type in extensions (built in and published) https://github.com/microsoft/vscode/issues/85819 **team**

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2019%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22November+2019%22+label%3A%22api-proposal%22)
- Closer engagement with the VS Code extension authors
   - [x] Make it easier for extension authors to follow our API workflow https://github.com/microsoft/vscode/issues/84507 @eamodio @jrieken
   - [ ] :runner: Explore closer feedback loop with extension authors https://github.com/microsoft/vscode/issues/84506 @eamodio

### Extension Contributions
- [x] Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/1775)) **team**
- [x] ESLint - Improve TypeScript integration and support [#802](https://github.com/microsoft/vscode-eslint/issues/802) @dbaeumer
- [x] ESLint - Improve support for mono repositories https://github.com/microsoft/vscode-eslint/issues/745 @dbaeumer
- [x] ESLint - Improve Auto fix support https://github.com/microsoft/vscode-eslint/issues/154 @dbaeumer

### Web
- [x] Improve support for [Firefox](https://github.com/microsoft/vscode/issues/85252) and [Safari](https://github.com/microsoft/vscode/issues/85253) @bpasero @rebornix
- [x] Improve support for [mobile](https://github.com/microsoft/vscode/issues/85254) @rebornix
- [x] Support running VS Code Web out of sources aka `yarn web` @bpasero
- [x] Enrich `yarn web` by adding mock search provider, mock problems provider, custom task running, ... @bpasero
- [x] Provide hosted version of `yarn web` for issue validation https://github.com/microsoft/vscode/issues/84485 @bpasero
- [x] Enrich `yarn web` by adding debug support @weinand

### Engineering
- [ ] :runner: Notarization of VS Code builds for OS X/Catalina https://github.com/microsoft/vscode/issues/74782 @bpasero @joaomoreno
- [x]  Automatic signing of RPM packages https://github.com/microsoft/vscode/issues/78727 @tyriar
- [x] Explore upgrade to electron 7 https://github.com/microsoft/vscode/pull/83796 @deepak1556
- [x] Identify the work required to use chrome process architecture https://github.com/microsoft/vscode/issues/79138 @deepak1556
- [x] Adopt `strictPropertyInitialization` https://github.com/microsoft/vscode/issues/78168 **team**
- [ ] :runner: Adopt `enableStrictFunctionTypes` https://github.com/microsoft/vscode/issues/81574 **team**
- [ ] :runner: Implement revised issue triaging workflow https://github.com/microsoft/vscode/issues/83125 @kieferrm @chrmarti
- [x] Improve build resubmission perf https://github.com/microsoft/vscode/issues/85107 @joaomoreno

### Planning
- [ ] :runner: Develop and publish the 2020 roadmap https://github.com/microsoft/vscode/issues/84015 @egamma @kieferrm @chrisdias
- [ ] :runner: Collaborate with TS on their 2020 roadmap https://github.com/microsoft/vscode/issues/84102 @mjbvz

-------

### Deferred Items
- :runner: Increase automation for upgrading to newer Electron versions https://github.com/microsoft/vscode/issues/77159 @deepak1556
- :runner: Convert native modules to NAPI https://github.com/microsoft/vscode/issues/79137 @deepak1556
- :hand: Git: Adopt editor in SCM input: https://github.com/microsoft/vscode/issues/84831 @joaomoreno
- :muscle: Setting sync support in the default Settings editor https://github.com/microsoft/vscode/issues/84431 @roblourens
- :muscle: Support for custom views with WebView contents https://github.com/microsoft/vscode/issues/83911 @alexr00
- Add LSIF to the [LSP portal](https://microsoft.github.io/language-server-protocol) @dbaeumer
- :muscle: Support semantic coloring in the spec [LSP #18](https://github.com/microsoft/language-server-protocol/issues/18)  @dbaeumer
- :muscle: Support semantic coloring in the LSP libraries [LSP Libs #368](https://github.com/microsoft/vscode-languageserver-node/issues/368) @dbaeumer
- Productize the TypeScript LSIF indexer [issues](https://github.com/microsoft/lsif-node/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) @dbaeumer
- :runner: Allow attaching/detaching from the debug targets https://github.com/microsoft/vscode/issues/79314 @weinand
- Debug console - Support for log grouping https://github.com/microsoft/vscode/issues/34981 @isidorn
- :muscle: Debug console - Support to find text https://github.com/microsoft/vscode/issues/4338 @isidorn

**Comment by cedric05** [comment]
it's nice including `code --web` as a feature.

**Comment by blizzardzheng** [comment]
will vs-code web opensource recently?

**Comment by bpasero** [comment]
Re `yarn web`: Please see https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_40.md#run-vs-code-web-out-of-sources for docs.

**Comment by zeroidentidad** [comment]
hi, why update 1.40.2 for ubuntu is not available in repository but only can be downloaded on vs code website page?

**Comment by chrmarti** [comment]
@zeroidentidad It updated now. Please try again.

**Comment by zeroidentidad** [comment]
@chrmarti thanks, I check it out

**Comment by shanalikhan** [comment]
@kieferrm @chrmarti

I'm the author of Settings Sync extension. I wanted you know about the plans of integrating Settings Sync within code. I saw multiple tickets with that. 

Are you guys going to develop full Sync solution within code inlcuding UX, API and backend provider ( like Gist in Settings Sync ) or the goal will be to provide the API access to authors to manage the backend providers

**Comment by Noiredd** [comment]
What about #12058, pretty please?

**Comment by sandy081** [comment]
@shanalikhan Current plan is to build end to end settings sync feature. Please see https://github.com/microsoft/vscode/issues/2743#issuecomment-560116420 about the proposal.

**Comment by zhangzheyu2simple** [comment]
It will be great if support attaching to kubernetes container.

**Comment by eman291** [comment]
I agree ill start a workshop for u

**Comment by NateLing** [comment]
i am coming

**Comment by J3m5** [comment]
It would be nice to see the [multi-line tabs feature](https://github.com/Microsoft/vscode/issues/70413) implemented soon.

**Comment by eman291** [comment]
#
Duplicate of #
@zeroidentidad

**Comment by eman291** [comment]
#86048

**Comment by eman291** [comment]
#
