### ISSUE TITLE
Test: Update to electron 7

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#85994]
- [ ] Mac @isidorn
- [x] Linux @JacksonKearl
- [x] Windows @alexr00

Complexity: 5

We plan to promote Electron 7 in the next milestone for Insiders. Download the latest released **Code Exploration** build from [here](https://builds.code.visualstudio.com/builds/exploration).

Refs https://github.com/microsoft/vscode/pull/83796

**Verify:**
* our smoke tests pass when run against this build (in case of an error, compare with insiders to see if it is Electron related or not)
* do some exploratory testing covering some native pieces of the application
  * **macOS:** Native Tabs (enable via settings: `window.nativeTabs: true`)
     - [x]  Verify opening tabs isn't slow, previous regression https://github.com/microsoft/vscode/issues/69301
  * **macOS:** Simple Fullscreen (enable via settings: `window.nativeFullScreen: false`)
     - [x] Verify going fullscreen isn't slow, previous regression https://github.com/microsoft/vscode/issues/75054
  * **windows:** touch device, verify onscreen keyboard doesn't pop up when clicking inside vscode while external keyboard is attached
     - [x] Previous regression https://github.com/microsoft/vscode/issues/76560
  * **macOS** - verify color profiles aren't faded
    - [x] Use cmd palette and go to `configure runtime arguments`, set `disable-color-correct-rendering: false`, check colors are faded on an external P3 display and it isn't with default value. Previous regression https://github.com/Microsoft/vscode/issues/51791, https://github.com/microsoft/vscode/issues/76656, https://github.com/microsoft/vscode/issues/84154
  * **windows** - verify maximize and restore operations work as expected when task bar is auto-hidden
    - [x] Previous regressions https://github.com/microsoft/vscode/issues/81102
  * `fs.watch` - works as expected https://github.com/microsoft/vscode/issues/74323
     - [x] **macOS**
  *  **windows** - verifying minimizing and restoring the window doesn't reset to minimum width
    - [x] Previous regression https://github.com/microsoft/vscode/issues/77207
  * **windows** - fullscreen doesn't have unrelated borders
    - [x] Previous regression https://github.com/microsoft/vscode/issues/77208
  * **macOS** - window is focused when starting from command line
     - [x] Previous regression https://github.com/microsoft/vscode/issues/79709
  * Verifying extension debugging works fine, previous regression https://github.com/microsoft/vscode/issues/79929
     - [x] **macOS**
     - [x] **windows**
     - [x] **linux**
  * Verify Subpixel AA is not regressed on LCD for the editor area, https://github.com/microsoft/vscode/issues/84214
     - [x] **Linux**
     - [x] **Windows**
  * **windows:** Verify titlebar is not clipped off when exit fullscreen
     - [x] Previous regression https://github.com/microsoft/vscode/issues/83456
  * **windows** Verify there is no rendering lag with custom titlebar
    - [x] Previous regression https://github.com/microsoft/vscode/issues/84343
  * Verify opening multiple windows doesn't stop rendering the oldest windows. Previous regression https://github.com/microsoft/vscode/issues/85338
     - [x] **Linux**
     - [x] **windows**
  
* check out the `electron-7.0.x` branch locally and verify you can run out of sources, set a breakpoint and debug using chrome devtools

**Comment by JacksonKearl** [comment]
I'm only seeing recent builds for Windows, should I work from the month old linux build or will you be triggering another build?

**Comment by isidorn** [comment]
I talked to @deepak1556 and he is triggering newer builds as we speak.

**Comment by deepak1556** [comment]
Sorry for the delay, internal builds got held up, new release will be completed in 1hr, will update here.

**Comment by deepak1556** [comment]
New builds have been published, make sure the electron version points to `7.1.3` . Thanks!

**Comment by isidorn** [comment]
Looks good. I will continue to self host on it for the rest of the week and file issues if I hit them.
Closing this for now.
