### ISSUE TITLE
Iteration Plan for January 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#87479]
This plan captures our work in **December and January**. We will **not** ship a December update. The next update will be **early February**. This is a 5-week iteration.

## Endgame

- **January 27th, 2020**: Endgame begins
- **January 31st, 2020**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/89326.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [ ] :muscle: Identify design inconsistencies with UI + JSON experiences https://github.com/microsoft/vscode/issues/84309 @misolori

### Accessibility
- [x] :runner: Accessibility, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22January+2020%22) @isidorn

### Workbench
- [ ] :runner: Support for custom editors https://github.com/microsoft/vscode/issues/77131 @mjbvz @bpasero @jrieken
- [x] Settings sync support (settings, extensions, keybindings, global state), see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Asettings-sync+milestone%3A%22January+2020%22) @sandy081
- [x] Provide login support for settings sync https://github.com/microsoft/vscode/issues/84332 @rmacfarlane
- [x] Setting sync support in the default Settings editor https://github.com/microsoft/vscode/issues/84431 @roblourens
- [x] Adopt new `ViewPaneContainer` for Panels https://github.com/microsoft/vscode/pull/87191 @sbatten @isidorn @sandy081
- [ ] :runner: Allow Outline and views contributed from extensions to be moved between sidebar and panel in their own tab https://github.com/microsoft/vscode/issues/85164 @sbatten @isidorn @sandy081
- [x] Save UI state periodically to prevent loss on shutdown https://github.com/microsoft/vscode/issues/12058 @bpasero
- [x] Improve MRU list of active editors, support to limit the number of open editors https://github.com/microsoft/vscode/issues/9872 @bpasero
- [x] Add support for language specific settings for extension contributed settings https://github.com/microsoft/vscode/issues/26707 @sandy081
- [x] Explore supporting links in diagnostic messages https://github.com/microsoft/vscode/issues/11847 @octref
- [x] Explore ways to start a file search in a search editor https://github.com/microsoft/vscode/issues/88154 @jacksonkearl

### Editor
- [ ] :runner: Semantic coloring: validate current API, engage with popular extensions https://github.com/microsoft/vscode/issues/77140 @aeschli @alexdima
- [x] Ship a new release of the Monaco editor [issues](https://github.com/microsoft/monaco-editor/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A%22December+2019%22+) @alexdima @rebornix
- [x] Implement word wrapping for non-monospaced fonts https://github.com/microsoft/vscode/issues/2654 @alexdima

### Languages
- [x] Explore how extensions can announce all refactorings they support https://github.com/microsoft/vscode/issues/82718 @mjbvz
- [ ] :runner: Explore support to preview refactoring changes https://github.com/microsoft/vscode/issues/77728 @jrieken @mjbvz
- [ ] :runner: Revisit rendering of completion items (support to always render details, e.g. package names) https://github.com/microsoft/vscode/issues/39441 @jrieken @octref

#### LSP / LSIF
- [x] Support semantic coloring in the spec [LSP #18](https://github.com/microsoft/language-server-protocol/issues/18)  @dbaeumer
- [x] Support semantic coloring in the LSP libraries [LSP Libs #368](https://github.com/microsoft/vscode-languageserver-node/issues/368) @dbaeumer
- [x] Add LSIF to the [LSP portal](https://microsoft.github.io/language-server-protocol) @dbaeumer

#### TypeScript/JavaScript
- [x] :red_circle: Adopt TS v3.8 RC for building VS Code @mjbvz

### Debug
- [x] Continue to improve the initial debug experience https://github.com/microsoft/vscode/issues/87162 @isidorn @weinand
- [x] Polish the new [JavaScript debugger](https://github.com/microsoft/vscode-js-debug/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22January+2020%22) @connor4312 @roblourens
- [x] Tune presentation of input/output in the debug console https://github.com/microsoft/vscode/issues/87599 @isidorn
- [ ] :runner: Continue on investigate into using language service support for scope resolution https://github.com/microsoft/vscode/issues/84044 @weinand
- [x] Support the 'compact' tree representation and searching/filtering in the `LoadedScriptsView` https://github.com/microsoft/vscode/issues/88526 https://github.com/microsoft/vscode/issues/88527 @weinand
- [x] Support to group launch configurations https://github.com/microsoft/vscode/issues/82332 @isidorn

### SCM
- [ ] :runner: Explore File History view https://github.com/microsoft/vscode/issues/84297 @eamodio
- [x] Explore how to support VS Code editor inside comment box of SCM Viewlet https://github.com/microsoft/vscode/issues/84831 @joaomoreno @alexdima

### Extensions
- [x] Allow menu contributions in Extension viewlet https://github.com/microsoft/vscode/issues/87285 @sandy081

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22January+2020%22+label%3A%22api-proposal%22)
- [ ] :runner: Explore closer feedback loop with extension authors https://github.com/microsoft/vscode/issues/84506 @eamodio

### Extension Contributions
- [x] Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/2075)) **team**

### Explorations
- [x] Explore alternative implementation and API approaches for notebooks https://github.com/microsoft/vscode/issues/88243, [feature list](https://github.com/rebornix/notebook-test/blob/master/roadmap.md) @rebornix @alexdima

### Engineering
- [x] Migrate custom `tslint` rules to `eslint` https://github.com/microsoft/vscode/pull/87644 @jrieken @bpasero
- [ ] :runner: Continue electron 7 adoption https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron-7-update @deepak1556
- [ ] :runner: Adopt `enableStrictFunctionTypes` https://github.com/microsoft/vscode/issues/81574 **team**
- [x] Implement revised issue triaging workflow https://github.com/microsoft/vscode/issues/83125 @kieferrm @chrmarti

### Planning
- [x] Collaborate with TS on their 2020 roadmap https://github.com/microsoft/vscode/issues/84102 @mjbvz

-----
### Deferred Items
- :hand: Notarization of VS Code builds for OS X/Catalina https://github.com/microsoft/vscode/issues/74782 @bpasero @joaomoreno
- :hand: Investigate into support for downloading a folder from the browser to the desktop https://github.com/microsoft/vscode/issues/83579 @bpasero
- :runner: Improve SCM 'no repositories' view https://github.com/microsoft/vscode/issues/61491 @joaomoreno
- :runner: Publish blog post about our custom data support https://github.com/microsoft/vscode/issues/83928 @octref
- Rewrite quick open with quick pick widget https://github.com/microsoft/vscode/issues/69955 @bpasero @chrmarti
- Continuous building support of the Monaco editor https://github.com/microsoft/vscode/pull/84636 @alexdima @rebornix
- Productize the TypeScript LSIF indexer [issues](https://github.com/microsoft/lsif-node/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) @dbaeumer
- Explore node-free renderer processes https://github.com/microsoft/vscode/issues/88549 @deepak1556
- :muscle: Support for custom views with WebView contents https://github.com/microsoft/vscode/issues/83911 @alexr00
- :muscle: Improve console.group in Debug Console https://github.com/microsoft/vscode/issues/34981 @isidorn
- :muscle: Debug console - Support to find text https://github.com/microsoft/vscode/issues/4338 @isidorn
- :muscle: Explore supporting to customize workbench icons in file icon themes @aeschli @misolori
- :muscle: Explore how to improve the discoverability of the column selection support @alexdima
- :muscle: Investigate into support for optimized LSP transport of JSON payloads (gzip, [MessagePack](https://msgpack.org/)) [issue](https://github.com/microsoft/vscode-languageserver-node/issues/553) @dbaeumer

**Comment by usernamehw** [comment]
> ### Deferred Items
> * 💪 Support for custom views with WebView contents #83911 alexr00

Deferred from the start... Does that mean there won't be any progress on that feature in December/January?

**Comment by kieferrm** [comment]
@usernamehw, correct. We show it there as there for transparency as we had questions about it.

**Comment by NateLing** [comment]
happy holidays

**Comment by Ryuurock** [comment]
happy holidays!
Is it possible to have a translucent window like xcode。
![image](https://user-images.githubusercontent.com/25604544/71436115-e1dfc300-2726-11ea-8b7d-1cd193903496.png)

**Comment by wendellhu95** [comment]
> happy holidays!
> Is it possible to have a translucent window like xcode。
> ![image](https://user-images.githubusercontent.com/25604544/71436115-e1dfc300-2726-11ea-8b7d-1cd193903496.png)

https://dev.to/emmanuelnk/how-to-be-cool-and-make-vscode-transparent-56ib

**Comment by Ryuurock** [comment]
> > happy holidays!
> > Is it possible to have a translucent window like xcode。
> > ![image](https://user-images.githubusercontent.com/25604544/71436115-e1dfc300-2726-11ea-8b7d-1cd193903496.png)
> 
> https://dev.to/emmanuelnk/how-to-be-cool-and-make-vscode-transparent-56ib

I found one called Vibrancy in the extended store
https://marketplace.visualstudio.com/items?itemName=eyhn.vscode-vibrancy

**Comment by davux** [comment]
How do you pronounce "January 27nd"? :)

**Comment by justlurking** [comment]
Extremely disappointed to see that #74782 won't be fixed until early February.

First it was supposed to be fixed in November, then in December, and now it slips all the way to February. This, for a feature (app notarization) first announced in 2018, for an operating system (Catalina) that has been available in beta for > six months and which went Gold in October, and which anyone who has purchased a new Mac since has no choice but to run.

Yes, I realize there is a workaround to install on macOS Catalina, but I don't want to install a non-hardened app. **Every other app** I've needed / wanted to install on my new Mac was hardened and notarized on a timely basis. 

Is there a reason VS Code hasn't been able to ship a point release to fix this issue more quickly?

**Comment by regs01** [comment]
>     * 🔴 Allow Outline and views contributed from extensions to be moved between sidebar and panel in their own tab @sbatten @isidorn

If I understand it correctly, probably this issue #49923

**Comment by hooch** [comment]
Is it possible to explain what's making #74782 difficult to solve? @bpasero @joaomoreno

**Comment by egamma** [comment]
@hooch this did not make it into the stable release, sorry. The good news is that notarization support is now available in the insiders release.
