### ISSUE TITLE
July Iteration Plan

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8760]
This plan captures what we **work on during July** and will **ship early August**.

**Notice** there will be a delay in 1.4 with regard to the translations and 1.4 will not be fully translated. We are planning for 1.5 to be fully translated release again.

June was a feature rich [release](https://code.visualstudio.com/Updates) and July is a heavy vacation month for the team. We have therefore decided that in July we will slow down feature work in favor of reducing our bug backlog and removing debt. Given this, we have the following themes for July:

* Bug/Issue management: review, cleanse, fix 
* Reduce debt items
* Engage and support popular extensions. We want to make sure that popular extensions are as good as possible so we will spend time supporting these extensions with feedback and Pull Requests.  
* React to feedback from the June release

The [July Test Plan items](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+label%3Atestplan-item+milestone%3A%22July+2016%22) are created as issues get closed.

### Schedule
- July 25 Code freeze for the endgame 
- July 29 endgame done

We end an iteration with an [endgame](https://github.com/Microsoft/vscode/wiki/Development-Process#end-game). The endgame is driven by Redmond.

##### Monday, Jul 25
- [x] Code freeze at 5pm PT
- [x] Ensure we have a green build on all platforms
- [x] All test items contain sufficiently comprehensive test descriptions by 6pm PT

##### Tuesday, Jul 26
- [x] Test build starts at 7am CET / 10pm PT on Monday
- [x] Test plan ready by 8am CET / 11pm PT on Monday
- [x] Testing

##### Wednesday, Jul 27
- [x] Testing
- [x] Fixing (self-assigned, milestone assigned, and labeled as `candidate`)
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)

##### Thursday, Jul 28
- [x] Fixing (scrutiny sets in - major bugs only - to be discussed in stand-up meeting)
- [x] [Verification](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Update release notes
   - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
- [x] Add/update shrink-wrap files for built-in extensions if needed (see [instructions](https://github.com/Microsoft/vscode/issues/8570#issuecomment-229669456)) **@Tyriar**
- [x] Update `OSSREADME.json` for built-in extensions based on differences to generated `npm-shrinkwrap.json` files if needed **@Tyriar**
- [x] Run [OSS tool](https://github.com/Microsoft/vscode-distro/blob/master/distro-tools/README.md) after merging shrink-wrap findings **@Tyriar**
  - *The LCA review of the ThirdPartyNotices.txt files is not needed anymore*
- [x] Check new OSS usage is entered into the [OSS registry](https://ossmsft.visualstudio.com/_apps/hub/ms.vss-oss-web.hub-oss) **@Tyriar**

##### Friday, Jul 29
- [x] Pause scheduled `insider` builds **@zurich**
- Satellite modules/npm packages ready, version updated, smoke tested
  - [x] vscode **@bpasero**
  - [x] yo generator **@aeschli**
  - [x] vsce **@joaomoreno**
  - [x] node debug **@weinand**
-  ~~Translation input~~ - **@isdorn** 
- [x] All issues [verified](https://github.com/Microsoft/vscode/wiki/Issue-Tracking#verification)
- [x] Fixing (only critical bugs - no string changes)
- [Smoketest](https://github.com/Microsoft/vscode/wiki/Smoke-Test)
  - [x] Windows - **@weinand**
  - [x] OS X - **@sandy081**
  - [x] Linux - **@isidorn**
- [x] All release notes updated
  - release notes are collected in a file named *`Month_Year.md`* in this [repo directory](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/)
- [x] Acknowledge pull requests in release notes **@Tyriar**
- [x] Mention notable fixes in the release notes

##### Monday, Aug 1
- National Day in Zurich
- [x] Trigger new insider build and publish it manually (was delayed due to build server issue) **@Tyriar**
- [x] Polish release notes **@redmond**

##### Tuesday, Aug 2
- [ ] ~~Resubmit translation input **@zurich**~~
- [x] Branch code with release number **@zurich**
- [x] Announce master is open for business **@zurich**
- [x] Publish `Insider` with hand-picked and reviewed candidate fixes **@jrieken**

##### Thursday/Friday, Aug 4/5
- [x] Rebuild for all platforms (if necessary) **@Tyriar**
- [x] Sanity check of installable bits
  - [x] Windows
    - [x] signed installer **@ramya-rao-a**
    - [x] zip **@ramya-rao-a**
  - [x] OS X - **@chrmarti**
  - [x] Linux
    - [x] deb packages **@Tyriar**
    - [x] rpm packages 64-bit **@Tyriar**
    - [x] rpm packages 32-bit **@Tyriar**
    - [x] archives **@Tyriar**
- [x] Publish website **@gregvanl**
- [x] Publish to stable **@seanmcbreen**
- [x] Git tag stable build with 1.4.0 **@Tyriar**
- [x] Enable scheduled `insider` builds **@joaomoreno**
- [x] Twitter announcement **@seanmcbreen**

---

### Plan Items

| Mark  | Description |
| ------------- | ------------- |
| :runner:  | work in progress  |
| :hand:  | task is blocked  |
| :muscle:  | stretch goal for this iteration  |

#### Debt Items

This section lists items to reduce our engineering debt:

- [x] Reduce our high contrast theme CSS hacks and inline SVGs during build #8516 @bpasero
  - Test #9692
  - [x] Release notes
- [x] Allow to have scoped instantiation service per editor slot #8579 @bpasero
  - Test #9693
  - [x] Release notes
- [x] Menu/title bar contribution consistency for the editor context menu @jrieken
  - Test #9694
  - [x] Release notes
- [x] :runner: Improve integrated terminal i18n support #8936  @tyriar 
  - Test #9695
  - [x] Release notes
- Snippet improvements #9072, #9122, #6320, #9286 @jrieken, @aeschli
  - [x] Provide a setting to define the snippet sort order
    - Test #9696
    - [x] Release notes
  - [x] Provide a separate 'Insert snippet' command that allows the user to pick a snippet
    - Test #9697
    - [x] Release notes
  - [x] Support tab completion for snippets #9579 @jrieken
    - Test #9698
    - [x] Release notes
  

#### Feedback

Issues to address community feedback: 
- Improve VIM support 
    - [x] :runner: Contribute to VIM extension @rebornix 
    - [x] :runner: Evaluate API gaps for better VIM support #8997 @sandy, @alexandrudima, @jrieken 
      - Test #9699
      - [x] Release notes
- [x] :runner: Quick open/file list performance for large workspaces #55 @chrmarti 
  - Test #9700
  - [x] Release notes
- [x] Editor actions are hard to discover when tabs are enabled #7666 @bpasero
  - Test #9701
  - [x] Release notes
- [x] API - support group ordering for menu contributions #9153 @jrieken
  - Test #9702
  - [x] Release notes
- [x] API - support for document link provider #1805 @jrieken
  - Test #9703
  - [x] Release notes

#### Engineering

This section lists several engineering/development items that the team identified:
- [x] - Add Net Promoter Score feedback support #9686 @joaomoreno 
  - Test #9690
- Debug: Incorporate debug protocol additions @weinand
    - [x] Support 'Restart Frame' Microsoft/vscode-debugadapter-node#43
    - [x] Support step-into-specifc Microsoft/vscode-debugadapter-node#39
    - [x] Support set-next-statement Microsoft/vscode-debugadapter-node#28
    - [x] Support paging for 'variables' request Microsoft/vscode-debugadapter-node#31
    - [x] Release notes
- Debug: Surface new debug protocol additions in VS Code @isidorn, @weinand
    - [x] VSCode should only update breakpoints after save #8077
      - Test #9533
    - [x] Support 'Restart Frame' #9145
      - Test #9691
    - [x] Support variable paging (aka chunked arrays) #9537
      - Test #9684
    - [x] Release notes

  
#### Explorations
- [x] :runner: Node debugging - investigate into supporting/switching to the Chrome Debugger Protocol that comes with node 7.0 @weinand
  - [ ] Release notes
- [ ] :runner: Review/investigate current error telemetry  @ramya-rao-a 

#### Deferred
- Debug: Add modules view @isidorn, @weinand
- Simplify configuration support and enable to programmatically modify configurations #8937  @bpasero 
- Add the Language Extension Checklist to our docs @kieferrm 

## Bugs
Bugs assigned to the current milestone:
- [vscode](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Abug+-label%3Aupstream+milestone%3A%22July+2016%22)

**Comment by johnfn** [comment]
Maybe this isn't the best place to put this, but I'm a Vim extension developer and I noticed you guys wanted to know the API gaps. I made an issue for each gap I'm aware of: #2771, #8096, #1431, #8094, #8093, #7177.

#2771 is the highest priority because it can't be worked around.

#8096 is also really important because although it can be worked around, I'm scared of breaking user's history.

The rest would be very nice to have.

**Comment by egamma** [comment]
@johnfn thanks, extracted into #8997

**Comment by egamma** [comment]
Closing - 1.4 has been shipped.

**Comment by niieani** [comment]
What came out of this exploration?

> Node debugging - investigate into supporting/switching to the Chrome Debugger Protocol that comes with node 7.0 @weinand

Nothing was mentioned in the release notes :(

**Comment by egamma** [comment]
The first step was a gap analysis between the V8 node debugger adapter and the chrome debugger adapter. This is no continued in August and the August plan has a link to the gap analysis.
