### ISSUE TITLE
Enable views to move between containers (Part 2)

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#89729]
This is a continuation of the work from #85164.

## Debt

- [x] `ViewDescriptorService` tests #89686
- [x] Remove sync `openPanel` in favor of `async` #89723
- [ ] Fix issue with panel naming before opening #88637
- [x] Have all panels using the new infrastructure #90252 #89993 50bc5d71aa4f5ea728ace3daaa4574f12fcc4d9a
- [ ] Make sure views are not using panel or viewlet semantics (`IPanelService`, `IViewletService`) 
#90020
- [x] ~~Introduce `attachStyler` in `ViewPane` so that implementing views can simply attach tree or list using it.~~ No longer necessary

## Features
 
- [x] Ensure all core views can be moved without issue
  - [x] Explorer
    - [x] Open Editors a28e0a93b170ead69645a3d64f00e7d3a06af2d0
    - [x] ~File Explorer~
    - [x] Timeline d05b78490f04d66d05a856f57169f724d7679049
  - [x] ~~Source Control~~ #90461
  - [x] Search
  - [x] Run and Debug #90468
  - [x] Extensions (will not be enabled)
  - [x] References view?
  - [x] ~~Remote~~
- [ ] Invert `canMove` property to allow exclusion of extensions viewlet views
- [x] Drag and drop support between existing containers
- [x] Drag and drop support into new containers

## Future (Not targeted for February)

- [ ] Generate icons for panel views/containers to enable new containers in sidebar from panel views
- [ ] Enable multiple views in panels

**Comment by sbatten** [comment]
migrated comments panel with 50bc5d71aa4f5ea728ace3daaa4574f12fcc4d9a

**Comment by sandy081** [comment]
Updated description 

- added all default views contributed to explorer in order to make sure we do not miss any. We have new `timeline` view and I think this can be made movable. 

- Added debt item to remove deps on panel and viewlet semantics
- Added debt item to introduce `attachStyler`

**Comment by isidorn** [comment]
I have updated the `OpenEditorsView`, it was pretty straightforward.
The only remaining "reference" to viewlets in these views is a mention of `IViewletViewOptions`. We should probably try to get rid of them.

**Comment by sbatten** [comment]
Timeline is done

**Comment by terrysahaidak** [comment]
Will it let me drag the tree view to the left side while activity bar and all the other panels/views on the left? Just like in Atom where you can move views to any side container.

**Comment by isidorn** [comment]
Clsoing this issue since I believe @sbatten has done what was on the plan for this milestone
@sbatten feel free to reopen or to create follow up issues.

@terrysahaidak this is not possible currently in vscode, though we do want to have that in the future

**Comment by djmisterjon** [comment]
@sbatten just want say thank you so much sbatten, i just tested and this was awesome feature and will help a lot my workflow.
Your awesome !
