### ISSUE TITLE
VIM API Gaps

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#8997]
From @johnfn in #8760 

 I'm a Vim extension developer and I noticed you guys wanted to know the API gaps. I made an issue for each gap I'm aware of: #2771, #8096, #1431, #8094, #8093, #7177.
#2771 is the highest priority because it can't be worked around.
#8096 is also really important because although it can be worked around, I'm scared of breaking user's history.

The rest would be very nice to have.

Features:
- [x] #2771 - Cursor movement commands
- [x] #8234 - Active editor movement commands
- [x] #9609 - Scroll Window/Page commands
- [ ] #9786 - Manage fold areas
- [ ] #8096
- [ ] #1431
- [ ] #8094
- [ ] #7177

Bugs:
- [x] #9542

**Comment by kieferrm** [comment]
Also includes  #9143.

**Comment by rebornix** [comment]
Short summary of current Vim API gaps:

## CJK
it's about #8133.
We had [CJK IME issues](https://github.com/Microsoft/vscode/issues/8133) with VS Code and not enough API exposed for external callers. Alex already fixed those bugs and provided two composing APIs, now CJK should be pefect. What's more, our Integrated Terminal also benefits from it https://github.com/Microsoft/vscode/issues/8892.

## Scrolling
it's about #2177, #9143, #9220. 
@sandy081 already provided us an API for moving cursors to screen lines and they work great. Now he is working on screen characters and Window/Screen Width information.

1. [x] Move cursor to specific Screen Line or line start, middle or end.
2. [ ] Lines in Visible Window. Eg, `go to the Nth/Middle line in the window`,  `go to the Nth line from the bottom`
3. [ ] Screen characters. `Scroll screen N characters`, it's likely an addition to `gm`.
4. [ ] Scroll Window/Page.

## History, Live Position, SelectionChange Reason, BracketMatching
#8096, #8094 #8093 #7177 are all in the backlog.

**Comment by sandy081** [comment]
I am removing Scroll Window/Page feature from the current plan. We will take a look at it for next iteration.

**Comment by kieferrm** [comment]
@sandy081 which issue do you defer?

**Comment by kieferrm** [comment]
@sandy081: @rebornix and I just ranked the backlog in the comment above to correctly reflect the priorities from the VIM perspective.

**Comment by rebornix** [comment]
@sandy081 updated my summary and added 4 more separate items. Now they covered all missing features currently on our roadmap, those commands/motions on our roadmap are from Vim's quickref so if there is any missing command that's dependent on VS Code API support but not listed by Vim documentation, I'll update this summary.

**Comment by sandy081** [comment]
@kieferrm Item I deferred is scrolling window / page feature - https://github.com/VSCodeVim/Vim/issues/210.

**Comment by sandy081** [comment]
@rebornix I moved Scrolling and other Tabs items to backlog in above comment. Please arrange them in the order of Vim extension priority.

Thanks.

**Comment by rebornix** [comment]
Implement all commands that are currently possible with @sandy081 's newly added API. Others are all moved to Backlog section, ordered by priorities.

**Comment by egamma** [comment]
This work will continue in August - moving the milestone accordingly
