### ISSUE TITLE
Settings Sync Plan

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90129]
Settings sync plan for March 2020 milestone

## Features

- [x] Synchronise Snippets - https://github.com/microsoft/vscode/issues/86678
- [x] Synchronise UI State - https://github.com/microsoft/vscode/issues/86679
- [x] Show previously synced data from server - https://github.com/microsoft/vscode/issues/85619

# Backlog

## Architecture

- [ ] Prevent update request when payload is too large - https://github.com/microsoft/vscode/issues/89597
- [ ] Trace update requests by attaching machine id - https://github.com/microsoft/vscode/issues/90074
- [ ] Local Ignored settings - https://github.com/microsoft/vscode/issues/89627
