### ISSUE TITLE
Iteration Plan for February 2020

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#90371]
This plan captures our work in **February**. We will ship in **early March**. This is a 4-week iteration.

## Endgame

- **February 24th, 2020**: Endgame begins
- **February 28th, 2020**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/91278.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [x] Identify design inconsistencies with UI + JSON experiences https://github.com/microsoft/vscode/issues/84309 @misolori
- [x] Explore how to make extension packs more visible https://github.com/microsoft/vscode/issues/89962 @misolori @sandy081

### Accessibility
- [x] Investigate into accessibility on Linux (using Orca) https://github.com/microsoft/vscode/issues/90446 @isidorn
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22February+2020%22) @isidorn

### Workbench
- [x] Settings sync https://github.com/Microsoft/vscode/issues/90129 @sandy081
- [x] Improve testing support for settings sync https://github.com/microsoft/vscode/issues/90076 @sandy081 @tyriar
- [x] Enable views to move between containers using drag'n drop and commands https://github.com/microsoft/vscode/issues/89729 @sbatten @sandy081 @isidorn
- [ ] :runner: Custom Editors - validate the proposed API for custom editors https://github.com/microsoft/vscode/issues/77131  @mjbvz @bpasero @jrieken
- [x] Custom Editors - enable workspace edits https://github.com/microsoft/vscode/issues/84672 @bpasero
- [x] Improve offline support for authentication providers  https://github.com/microsoft/vscode/issues/89200 @rmacfarlane
- [x] Validate the proposed API for authentication providers by implementing a GitHub provider https://github.com/microsoft/vscode/issues/90384 @rmacfarlane
- [ ] :runner: Explore UX for account management https://github.com/microsoft/vscode/issues/90385 @rmacfarlane
- [x] Render whitespace in selection by default https://github.com/microsoft/vscode/issues/90386 @rmacfarlane
- [x] Enable search editor in stable https://github.com/Micrsoft/vscode/issues/23931 @jacksonkearl
- [ ] :runner: Provide in core implementation for notebooks (see [feature list](https://github.com/rebornix/notebook-test/blob/master/roadmap.md)) https://github.com/microsoft/vscode/issues/90382 @rebornix
- [ ] :red_circle: :runner: Explore language support for notebooks @jrieken
- [x] Explore global undo/redo of workspace edits https://github.com/microsoft/vscode/issues/638 @alexdima
- [x] Support contributable `Welcome View` contents https://github.com/microsoft/vscode/issues/89080 shown when a view is empty @joaomoreno

### Editor
- [ ] :runner: Semantic coloring: validate current API, engage with popular extensions https://github.com/microsoft/vscode/issues/77140 @aeschli @alexdima
- [x] :red_circle: :muscle: Improve the discoverability of the column selection support @alexdima
- [x] Support to render the full document in the minimap https://github.com/microsoft/vscode/issues/21849 @alexdima
- [x] :red_circle: Ship the standalone editor @alexdima

### Languages
- [ ] :runner: Support to preview refactoring changes for other refactorings than Rename https://github.com/microsoft/vscode/issues/77728 @jrieken @mjbvz
- [ ] :runner: Revisit rendering of completion items (richer completion labels) https://github.com/microsoft/vscode/issues/39441 @octref @jrieken

#### LSP / LSIF
- [ ] :runner: Investigate into support for optimized LSP transport of JSON payloads (gzip, [MessagePack](https://msgpack.org/)) [issue](https://github.com/microsoft/vscode-languageserver-node/issues/553) @dbaeumer
- [x] LSP protocol enhancements ([symbol tags](https://github.com/microsoft/language-server-protocol/issues/927), [links in diagnostic messages](https://github.com/microsoft/language-server-protocol/issues/926)) @dbaeumer
- [x] [LSIF Web Page polish](https://github.com/microsoft/language-server-protocol/issues/928) @dbaeumer

#### HTML/CSS
- [ ] :runner: Improve auto-rename tag implementation by not relying on multiple cursors https://github.com/microsoft/vscode/issues/88424 @octref

#### TypeScript/JavaScript
- [x] Adopt TS v3.8 https://github.com/microsoft/vscode/issues/91339 @mjbvz

### Debug
- [x] Improve the new js debugger (see [query](https://github.com/microsoft/vscode-js-debug/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22February+2020%22)) @connor4312 @roblourens
- [x] Add language service extension API for debug hovers (part of the language service/debugger investigation https://github.com/microsoft/vscode/issues/84044) @weinand
- [ ] :runner: Allow debug extensions to provide configurations to display in Select and Start Debugging https://github.com/microsoft/vscode/issues/88230 @weinand @isidorn
- [x] Make initial debug / run view extensible https://github.com/microsoft/vscode/issues/85548 @isidorn
- [x] Breakpoint improvements https://github.com/microsoft/vscode/issues/89756 https://github.com/microsoft/vscode/issues/89059 https://github.com/microsoft/vscode/issues/86749 @isidorn
- [x] Improve console.group in Debug Console https://github.com/microsoft/vscode/issues/34981 @isidorn
- [x] Experiment whether renaming Debug -> Run in menu bar improves the debugger discoverabilty https://github.com/microsoft/vscode/issues/90445 @isidorn @miguel

#### DAP
- [x] Support grouping in output events https://github.com/microsoft/debug-adapter-protocol/issues/96 @weinand
- [x] Allow the placement of the cursor in a DAP completion item https://github.com/microsoft/debug-adapter-protocol/issues/87 @weinand
- [x] Proposal: Cancellable Progress Events https://github.com/microsoft/debug-adapter-protocol/issues/92 @weinand

### SCM
- [x] Improve SCM 'no repositories' view https://github.com/microsoft/vscode/issues/61491 @joaomoreno
- [x] Provide File History view https://github.com/microsoft/vscode/issues/84297 @eamodio

### Terminal
- [x] Improve support for Unicode 11 https://github.com/microsoft/vscode/issues/90029 @tyriar

### Tasks
- [ ] :runner: Automatic task detection improve feedback and support cancellation of long running detectors https://github.com/microsoft/vscode/issues/90087 @alexr00

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22February+2020%22+label%3A%22api-proposal%22)
- [x] Explore closer feedback loop with extension authors https://github.com/microsoft/vscode/issues/84506 @eamodio @fiveisprime

### Web
- [x] Provide `registerCommand` in the embedder API https://github.com/microsoft/vscode/issues/90569 @bpasero

### Extension Contributions
- [x] Improvements to the Remote extensions ([see plan here](https://github.com/microsoft/vscode-remote-release/issues/2329)) **team**
- [x] Contributions to Vetur https://github.com/vuejs/vetur/milestone/9 @octref

### Engineering
- [x] Notarization of VS Code builds for OS X/Catalina https://github.com/microsoft/vscode/issues/74782 @joaomoreno
- [ ] :runner: Rewrite quick open with quick pick widget https://github.com/microsoft/vscode/issues/69955 @bpasero @chrmarti
- [x] Testing - run unit/integration across different browsers as part of our integration builds leveraging [playwright](https://github.com/microsoft/playwright) @bpasero @jrieken
- [x] Continue electron 7 adoption https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aelectron-7-update @deepak1556 @bpasero
- [X] Adopt `enableStrictFunctionTypes` https://github.com/microsoft/vscode/issues/81574 **team**
- [x] Continuous building support of the Monaco editor https://github.com/microsoft/vscode/pull/84636 @alexdima @rebornix

### Documentation
- [x] Publish blog post about our custom data support https://github.com/microsoft/vscode/issues/83928 @octref

-----
### Deferred Items
- :red_circle: Semantic coloring: implement API to color a range of a document @alexdima
- :muscle: Explore supporting to customize workbench icons in file icon themes https://github.com/microsoft/vscode/issues/79130 @aeschli @misolori
- :muscle: Provide guidance for language servers for embedded languages https://github.com/microsoft/vscode/issues/47288 @octref @aeschli
- Explore node-free renderer processes https://github.com/microsoft/vscode/issues/88549 @deepak1556
- :red_circle: Identify which icons we use for dynamic sidebar views (caused by moving views) @misolori
- :red_circle: Explore bracket pair colorizing performance improvements @alexdima
- :red_circle: Explore how to enable 'working sets' as an extension @isidorn @bpasero @sandy081
- Improve the accessibility of the Differences view (F7) https://github.com/microsoft/vscode/issues/88695 @isidorn
- :red_circle: Endgame testing: Support to validate Test Plan Items @sandy081
- :hand: Investigate into support for downloading a folder from the browser to the desktop https://github.com/microsoft/vscode/issues/83579 @bpasero
- Productize the TypeScript LSIF indexer [issues](https://github.com/microsoft/lsif-node/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) @dbaeumer
- Support for custom views with WebView contents https://github.com/microsoft/vscode/issues/83911 @alexr00

**Comment by jvesouza** [comment]
First of all forgive me if the comments are not relevant or if they are not in the right place.
I was excited by the fact that accessibility in linux is being taken into account by the VSCode accessibility team. I have been using orca for over 10 years and I believe that VSCode will greatly increase my productivity in this environment.

Here are some links that may help with research:

https://wiki.gnome.org/Projects/Orca/Chromium
https://wiki.gnome.org/Projects/Orca
https://mail.gnome.org/mailman/listinfo/orca-list

**Comment by isidorn** [comment]
@jvesouza Thank you very much for the pointers, let's continue the discussion here https://github.com/microsoft/vscode/issues/90446

**Comment by Kroc** [comment]
Can I ask please that this issue be looked at this month? #87347 "New minimum width of panel is too wide on 1366px screen", this is making it awkward for laptop users

**Comment by jhpratt** [comment]
Can we _please_ get someone to look into #23991? It's an issue that has been around for years and affects a number of people. It doesn't necessarily have to be fixed immediately; even having eyes on it would be an improvement.

**Comment by gazzar** [comment]
There's an editor item to "Improve the discoverability of the column selection support." This seems like a pointless waste of effort. Apart from column selection being already supported and documented, I actually don't see a lot of benefit to the current implementation of column selection in VSCode. Usually the point of column selection is to be able to move blocks of code, i.e. cut or copy the selection then paste it elsewhere in the code, but pasting columns basically doesn't work in VSCode. Until that is fixed, there is little benefit to improving discoverability of a feature that is only useful if you happen to want to delete columns of code and not also paste them back somewhere.

**Comment by Tyriar** [comment]
> but pasting columns basically doesn't work in VSCode

@gazzar do you know if there is an issue tracking the problems with column selection copy+pasting?

**Comment by gazzar** [comment]
> 
> 
> > but pasting columns basically doesn't work in VSCode
> 
> @gazzar do you know if there is an issue tracking the problems with column selection copy+pasting?

Hi @Tyriar, the main one is #5940. There is also #43145 which is to do with pasting blocks at the ends of lines. I don't really think it is different, but was closed and reopened, perhaps because it contains extra detail about the behaviour of how this works in other editors such as Visual Studio.

**Comment by kanlukasz** [comment]
> 

>     * [ ]  🏃 Explore global undo/redo of workspace edits @alexdima
I think you can see, among others, this one: https://github.com/microsoft/vscode/issues/55440
