### ISSUE TITLE
Settings Sync UX Study

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#90970]
### Turn on/off
  - [x] Everyone went to the File > Preferences menu to turn on Sync. They eventually went to the gear and found the “Turn on Sync” command - #90925
  - No one used the command palette in any task

### Log in
   - [x] Some expressed wanting to stay logged in when turning off/on (known bug) - #90924

### Discoverability 
  - [x] Everyone wasn’t sure whether sync was working, they all manually searched through settings/extensions to verify that sync was working. Everyone expressed a desire for an indicator (last synced timstamp, sync is on, etc.) - #90967 
  - [x] Sync actions are not discoverable - #91097

### Extensions Syncing
  - [x] Everyone expected to see a “Ignore extension” from the extension configure menu - #86915
  - [x] Most typed the extension name in the “ignore extesnions” setting then tried the ID and saw it worked - #90930
  - [x] Most encountered issues with IntelliSense in settings.json, after typing the quotes the suggest widget went away and they had a hard time re-triggering it - #90931
  - [ ] Try out an extension without syncing everywhere - #91054
  - [ ] Some expressed wanting WSL extensions synced across machines - #90968

### Conflicts Resolution
  - Everyone understood the “git merge” conflict view and was comfortable deciding which settings to choose

### Other Areas
- Everyone was confused when they clicked on “Edit in settings.json”, they expected to start editing the setting in the settings.json file - #90969

## Feedback
- Everyone had that “ah-hah!” moment when changing themes and seeing it appear on the secondary machine
- Everyone loved the feature and said it would solve a pain point of managing data across devices
