### ISSUE TITLE
Iteration Plan for March 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#92242]
This plan captures our work in **March**. We will ship in **early April**. This is a 5-week iteration.

## Endgame
- **March 30th, 2020**: Endgame begins
- **April 3rd, 2020**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/93717.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [x] Identify which icons we use for dynamic sidebar views (caused by moving views) https://github.com/microsoft/vscode/issues/92590 @misolori

### Accessibility
- [x] Improve the accessibility of the Differences view (F7) https://github.com/microsoft/vscode/issues/88695 @isidorn
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22March+2020%22) @isidorn

### Workbench
- [x] Settings sync: support global state, snippets https://github.com/microsoft/vscode/issues/86678 https://github.com/microsoft/vscode/issues/86679 @sandy081
- [x] Settings sync: improvements to the settings editor (visual indicators, filters) https://github.com/microsoft/vscode/issues/92517 @roblourens
- [x] Enable views to move between containers using drag'n drop and commands https://github.com/microsoft/vscode/issues/92786 @sbatten @sandy081 @isidorn
- [x] Allow contribution of views into the panel https://github.com/microsoft/vscode/issues/41686 @sbatten
- [ ] :runner: Provide in core implementation for notebooks https://github.com/microsoft/vscode/issues/91987 @rebornix @jrieken @roblourens
- [ ] :runner: Stabilize and document Custom Editor support https://github.com/microsoft/vscode/issues/77131 @mjbvz @bpasero @jrieken
- [ ] :runner: Provide account management UI https://github.com/microsoft/vscode/issues/90385 @rmacfarlane @misolori
- [x] Explore using GH Applications in GH authentication provider https://github.com/microsoft/vscode/issues/92675 @rmacfarlane
- [ ] :runner: Supporting to customize the product icons https://github.com/microsoft/vscode/issues/79130 @aeschli @misolori
- [x] Global undo/redo: close and reopen a file preserves the undo stack https://github.com/microsoft/vscode/issues/7169 @alexdima
- [ ] Global undo/redo: support to undo an operation for a file that is not in memory https://github.com/microsoft/vscode/issues/92272 @alexdima
- [x] Investigate support for Local Workspace settings https://github.com/microsoft/vscode/issues/40233 @sandy081
- [x] Make extension packs more visible in the Extensions view https://github.com/microsoft/vscode/issues/89962 @sandy081
- [x] Support `Welcome Views` for Custom Views https://github.com/microsoft/vscode/issues/92143 @alexr00
- [x] Explorer: Show hidden files and their path when they are opened https://github.com/microsoft/vscode/issues/92090 @isidorn
- [ ] :muscle: Explorer: Add support for inclusion filters https://github.com/microsoft/vscode/issues/869 @isidorn
- [x] Finish timeline support and enable it in Stable https://github.com/microsoft/vscode/issues/84297 @eamodio
- [x] Allow for view-local progress indication https://github.com/microsoft/vscode/issues/92421 @eamodio

### Editor
- [x] Semantic coloring: finalize API https://github.com/microsoft/vscode/issues/77140 @alexdima @aeschli
- [ ] :runner: Semantic coloring: implement API to color a range of a document https://github.com/microsoft/vscode/issues/92273 @alexdima
- [x] Semantic coloring: Add support for coloring library symbols https://github.com/microsoft/vscode/issues/91090 @aeschli

### Terminal
- [ ] :runner: :muscle: Allow extensions to customize the environment of terminal processes https://github.com/microsoft/vscode/issues/46696 @tyriar
- [x] Support for terminal link handlers https://github.com/microsoft/vscode/issues/91606 @tyriar

### Languages
- [ ] :runner: Support richer labels in completion items https://github.com/microsoft/vscode/issues/39441 @octref @jrieken
- [x] Provide guidance for language servers for embedded languages https://github.com/microsoft/vscode/issues/47288 @octref @aeschli

#### LSP / LSIF
- [x] Update the TypeScript LSIF indexer to TypeScript 3.8 https://github.com/microsoft/lsif-node/issues/94 @dbaeumer
- [x] LSIF: Support reference delegates over projects https://github.com/microsoft/lsif-node/issues/95 @dbaeumer
- [ ] :muscle: Specify accept and content encoding in LSP https://github.com/microsoft/vscode-languageserver-node/issues/553 @dbaeumer

#### HTML/CSS
- [x] Improve auto-rename tag implementation by not relying on multiple cursors https://github.com/microsoft/vscode/issues/88424 @octref

#### TypeScript/JavaScript
- [ ] :hand: Adopt TS recovery release 3.8.x https://github.com/microsoft/vscode/issues/92819 @mjbvz
- [ ] :runner: Help TS team to assume ownership of semantic highlighting in TS tooling https://github.com/microsoft/vscode/issues/92789 @aeschli @mjbvz
- [ ] Collaborate with TS team on documentation of how to work with large TS projects https://github.com/microsoft/vscode/issues/92820 @mjbvz

### Debug
- [x] Allow debug extensions to provide configurations to display in *Select and Start Debugging* https://github.com/microsoft/vscode/issues/88230 @weinand @isidorn @connor4312
- [ ] :runner: Adapt "auto attach" feature in js-debug https://github.com/microsoft/vscode/issues/88599 @connor4312 @weinand
- [x] Adopt terminal link handlers in js-debug https://github.com/microsoft/vscode-js-debug/issues/387 @connor4312
- [x] Improve Call Stack presentation in the UI https://github.com/microsoft/vscode/issues/83986 @isidorn @misolori
- [x] Debug `Welcome View`: work with Debug Adapter providers to contribute content https://github.com/microsoft/vscode/issues/85548 @isidorn
- [ ] :runner: Explore using language service support for scope resolution https://github.com/microsoft/vscode/issues/84044 @weinand
- [ ] :muscle: Explore using language service support for REPL evaluation https://github.com/microsoft/vscode/issues/87448 @weinand
- [x] Explore progress UI for debugging https://github.com/microsoft/vscode/issues/92253 @isidorn @weinand
- [x] Explore improving the debug experience when a single file is open without a launch config https://github.com/microsoft/vscode/issues/92269 @weinand
- [x] Implement new DAP protocol features for caret/selection positioning in completions https://github.com/microsoft/vscode/issues/90974 @isidorn
- [ ] :runner: Explore initial support for capturing and viewing performance profiles in js-debug https://github.com/microsoft/vscode-js-debug/issues/388 @connor4312

#### DAP
- [x] Finalize cancellable progress events https://github.com/microsoft/debug-adapter-protocol/issues/92 @weinand

### Tasks
- [x] Improve task detection and selection https://github.com/microsoft/vscode/issues/90087 @alexr00

### API
- [ ] :runner: March extension authors call https://github.com/microsoft/vscode/issues/93604 @eamodio @fiveisprime
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22March+2020%22+label%3A%22api-proposal%22)

### Extension Contributions
- [ ] Improvements to the Remote extensions (see plan [here](https://github.com/microsoft/vscode-remote-release/issues/2493)) **team**

#### ES Lint
- [x] Embbed links to documentation in eslint diagnostic messages https://github.com/microsoft/vscode-eslint/issues/911 @dbaeumer

### Engineering
- [ ] :runner: Explore node-free renderer processes https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556
- [x] Rewrite quick open with quick pick widget https://github.com/microsoft/vscode/issues/69955 @bpasero @chrmarti
- [x] Run Smoke Tests as part of the nightly build (without failing the build if unsuccessful) https://github.com/microsoft/vscode/issues/92271 @bpasero @chrmarti
- [x] Support to validate Test Plan items when generate endgame testing assignments https://github.com/microsoft/vscode-tools/issues/34 @sandy081 @JacksonKearl

### Documentation
- None.

-----
### Deferred Items
- Support for custom views with WebView contents https://github.com/microsoft/vscode/issues/83911 @mjbvz
- :runner: Support to preview refactoring changes for other refactorings than Rename https://github.com/microsoft/vscode/issues/77728 @jrieken @mjbvz
- Terminal link provider API https://github.com/microsoft/vscode/issues/91290 @Tyriar
- :runner: Improve presentation of TS hovers https://github.com/microsoft/vscode/issues/92787 @octref @mjbvz

**Comment by sanket-bhalerao** [comment]
vscode 1.44 update seems to have broken the remote connection.
#92423

**Comment by AndrewDavis** [comment]
Hey, how come I don't see anything about the pinning tabs feature (like, **actually pinning** tabs) here? It's one of the most desired, asked for, and needed features in VSCode, it's been 3.5 years, and we haven't heard anything back about it.

https://github.com/Microsoft/vscode/issues/12622

**Comment by AndrewDavis** [comment]
And I thought I had mentioned in the past somewhere but when I think of pinning tabs I'm thinking of the exact same functionality that Firefox provides for pinning tabs: Right click -> Pin Tab, tab becomes a small square that you can't move or easily close. Right click -> Unpin Tab, now it's like a regular tab again.

I pin tabs all the time, when they're meant to be there for the long-term. The rest of the tabs I may close at any time. I'm certain this must be a very common workflow, and VSCode should support it.

**Comment by gkkirilov** [comment]
Also, multi-row tabs would be great

**Comment by J3m5** [comment]
@gkkirilov I asked for it [in early December](https://github.com/microsoft/vscode/issues/83930#issuecomment-560304790)
[This feature](https://github.com/Microsoft/vscode/issues/70413) was requested in March 2019.
IMHO, multi-line tabs and pinned tabs is a must have.

**Comment by Tyriar** [comment]
Released yesterday
