### ISSUE TITLE
Bot work for March 2020 milestone

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#93316]
## Background
As part of the March 2020 milestone we will be transitioning some of our GitHub App powered triage flows over to GitHub Actions. The rationale behind this is in several parts:
- With GitHub Actions, the ops side of the service maintained by GitHub rather than us.
  - This is doubly important as our GitHub App is run in a server using a now deprecated Docker for Azure service that only two people on the team are able to connect to, and only from inside corpnet or a SAW. This has become an event more significant bottleneck in development given coronavirus. 
- With GitHub Actions, liveness, logs, and errors can be easily checked in the `Actions` tab of the Microsoft GitHub page, by any member of the team at any time. This is compared to previously needing to connect to the Azure instance to diagnose issues (which again only two people on the team are able to do). 

## Goals
- Create a wrapper around Octokit API that can be tested against which we can reuse across Apps and Actions ([repo](https://github.com/JacksonKearl/vscode-triage-github-actions)):
  - [X] Support basic Issue management (labels, issue body, open/close, add comment)
  - [x] Support reading comments (https://github.com/JacksonKearl/vscode-triage-github-actions/issues/1)
  - [x] Support querying for issues (https://github.com/JacksonKearl/vscode-triage-github-actions/issues/3)
  - [x] Support managing milestones (https://github.com/JacksonKearl/vscode-triage-github-actions/issues/2)
- Build Actions to replace existing stateless App functionality:
  - [X] Commands (except `findDuplicates`)
  - [X] CopyCat
  - [x] NewRelease
  - [x] Locker
  - [x] Needs More Info
  - [x] 💪 Feature Requests (depends on milestones)
- [X] Create a new Action for requesting version information for issues that do not have it (https://github.com/microsoft/vscode/issues/92958) (depends on comments)
- [x] Catalog and specify all existing automations ([OneNote](https://microsoft.sharepoint.com/:o:/t/VSCode68/EiM53jLHTsVEh25du3JG66IB9JQ9ZImNsEHjc0qnG4hcRQ?e=RRTMrU))
- [x] 🏃 Begin to develop a set of high-impact low-conflict automations to create in future iterations ([query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Abot-proposal+label%3Aunder-discussion+))
