### ISSUE TITLE
Improve Sync views

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#93960]
- [x] Show diff editor for all resources (extensions, global state)
- [x] It's missing `Revert to this state` actions on any JSON file
- [x] Show Remote backup view even if Sync is turned off with signed in user #96370
- [x] Nuke button on Remote view #96370
- [x] Show machines being synced
- [x] Show client or machine information with sync data #96170

**Comment by texastoland** [comment]
One related note is it was unintuitive to find the backup because the activity bar icon visible in the docs is hidden until you are already in one of the sync panels.

**Comment by sandy081** [comment]
Yeah currently it is not shown by default and is shown only when you try to access the sync views using commands because they are advanced and showing them with some action makes sense.

**Comment by texastoland** [comment]
That makes sense. At the very least they could be included in the "manage menu" (the gear below the account icon). The menu item's label <kbd>Preferences Sync is On</kbd> also look like a toggle instead of opening a navigator. I don't know the best solution but <kbd>Preferences Sync (On)...</kbd> seems the easiest.

**Comment by sandy081** [comment]
Showing synced machines:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/10746682/82459585-69ecad80-9ab8-11ea-9280-f69faee373e6.png">

**Comment by texastoland** [comment]
> The menu item's label Preferences Sync is On also looks like a toggle instead of opening a navigator. I don't know the best solution but Preferences Sync (On)... seems the easiest.

@sandy081 Is there a separate ticket addressing #97443? Should I open a new ticket about changing labels?

**Comment by sandy081** [comment]
There is no separate issue you can open one/

**Comment by texastoland** [comment]
You already closed #97443 as a duplicate of this, but it doesn't seem to address it?

**Comment by sandy081** [comment]
#97443 Does not seem to inline with what you are asking for

**Comment by texastoland** [comment]
This issue doesn't address anything in that one. Please reopen #97443 until there's a new theme issue.
