### ISSUE TITLE
Notebook debt for April

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#94328]
Debt items for Notebook core after endgame testing

- Actions
  - [x] Missing keybindings https://github.com/microsoft/vscode/issues/94097
  - [x] Conflicts with editor https://github.com/microsoft/vscode/issues/94270
  - [x] Command Palette https://github.com/microsoft/vscode/issues/94098, https://github.com/microsoft/vscode/issues/94102
- Output webview
  - [x] Copy/Paste https://github.com/microsoft/vscode/issues/94088 (PR  https://github.com/microsoft/vscode/pull/94089)
  - [x] Nested scrollable element inside the output https://github.com/microsoft/vscode/issues/93621 (PR https://github.com/microsoft/vscode/pull/94222)
  - [x] Cell focus should take webview element focus into account https://github.com/microsoft/vscode/issues/94314 
    - note: when the focus is inside an output in the webview, the cell should be treated as focused.
  - [x] Dragging scrollbar of notebook or cell editor stops when the focus moves into the webview #94055
- Layout 
  - [x] Cell height caching https://github.com/microsoft/vscode/issues/94230
- Theming 
  - [x] move colors from CSS to Color Rules  https://github.com/microsoft/vscode/issues/94253
- Web
  - [x] Uri https://github.com/microsoft/vscode/issues/93716
  - [x] use iframe in Web

💪 
  - Editor widgets cutoff https://github.com/microsoft/vscode/issues/93930 (PR https://github.com/microsoft/vscode/pull/94195)
  - Accessible mime type of output

cc @roblourens @jrieken
