### ISSUE TITLE
Terminal link provider-based links preview

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#95081]
You can try out this feature in [Insiders](https://code.visualstudio.com/insiders) by enabling this setting:

![image](https://user-images.githubusercontent.com/2193314/79593567-80a27d80-8090-11ea-8466-02c796ee1d76.png)

---

The link provider experimental API in xterm.js has been merged in with https://github.com/xtermjs/xterm.js/pull/2530 and adopted in VS Code with https://github.com/microsoft/vscode/pull/90336. I improved it further by adding validated local links (closes the gap with the old system) and "word" links which is the fallback that created words links based on the `wordSeparators` setting that open quick access.

This issue tracks removal of the old link matcher code, promoting the link provider to default and cleaning up the rough edges.

- [ ] Terminal link detection issues https://github.com/microsoft/vscode/issues/21125, this was the previous general link problems issue. A lot of this is covered with the adoption of the editor's link detector
- [x] Are terminal word link hovers too aggressive? https://github.com/microsoft/vscode/issues/95080
- [ ] Terminal "word" link provider does not support wrapping https://github.com/microsoft/vscode/issues/95077
- [x] Terminal link hover obscures hovered text on top line https://github.com/microsoft/vscode/issues/95079
- [x] Linkify terminal paths without any path separators https://github.com/microsoft/vscode/issues/22772, covered by word link provider
- [x] Support terminal.integrated.enableFileLinks when link providers is on https://github.com/microsoft/vscode/issues/95082
- [x] Terminal link provider links don't support git diff links https://github.com/microsoft/vscode/issues/95114
- [x] Terminal links should support folders https://github.com/microsoft/vscode/issues/29499
- [x] Terminal links should open word links if there is exactly 1 matching file inside the workspaces https://github.com/microsoft/vscode/issues/95119
- [x] Some windows links don't work with link providers https://github.com/microsoft/vscode/issues/95166
- [x] Support git hashes in terminal word links https://github.com/eamodio/vscode-gitlens/issues/1002
- [x] Properly invalidate links when the buffer changes https://github.com/microsoft/vscode/issues/95556
- [ ] Keyboard navigation https://github.com/microsoft/vscode/issues/95570
- [ ] Link hover sticks around sometimes https://github.com/microsoft/vscode/issues/95997

The plan for April is to get this in a reasonable/preview state, which is already is pretty much. Then for May polish and invest in exposing an API to extensions #91290

**Comment by kelleyma49** [comment]
Great stuff! Will it navigation via the keyboard?

This might be overkill, but the ability to use something like jumpy (https://github.com/wmaurer/vscode-jumpy) to follow links would be nice.

**Comment by Tyriar** [comment]
@kelleyma49 currently not, but https://github.com/xtermjs/xterm.js/issues/2848 could make it easier to do that. It would be cool to be able to navigate to the most recently output link and before that, definitely something that should be considered before it's no longer a preview. Created https://github.com/microsoft/vscode/issues/95570

For jumpy support it would need a whole bunch of APIs which don't exist so that's out of scope but may be possible one day.

**Comment by kelleyma49** [comment]
Agreed! Thanks for creating the new issue. Subscribed!

**Comment by Tyriar** [comment]
Closing off for April, May's work is tracked in https://github.com/microsoft/vscode/issues/96266
