### ISSUE TITLE
Stablize account management UI and flows

### ISSUE THREAD

**Issue by RMacfarlane** [microsoft/vscode#95163]
- [x] Should always show Github sign in entry, have default scopes for provider https://github.com/microsoft/vscode/issues/94488
- [x] Add sign out toast for GitHub provider https://github.com/microsoft/vscode/issues/94634
- [x] Show Active Accounts - show session usage per session https://github.com/microsoft/vscode/issues/94635
- [x] Only prompt setting sync changes on active window https://github.com/microsoft/vscode/issues/94176
- [x] Show auth provider name next to account https://github.com/microsoft/vscode/issues/95476

**Comment by RMacfarlane** [comment]
Marking as duplicate to remove from verification list, each individual item will be verified instead
