### ISSUE TITLE
Iteration Plan for April 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#95168]
This plan captures our work in **April**. We will ship in **early May**. This is a 4-week iteration.

## Endgame
- **April 27th, 2020**: Endgame begins
- **May 1st, 2020**: Endgame done

The endgame details for this iteration are tracked in **TBD**.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [ ] :runner: Notebook UX explorations https://github.com/microsoft/vscode/issues/95154 @misolori
- [x] Reconsider timeline icons and follow active editor UX https://github.com/microsoft/vscode/issues/94092 https://github.com/microsoft/vscode/issues/94091 @misolori @eamodio

### Accessibility
- [x] Improve status bar accessibility, enable F6 style UI navigation https://github.com/microsoft/vscode/issues/94677 @isidorn
- [x] :runner: Investigate accessibility for debugging: Screen readers are not announcing encountered break points https://github.com/microsoft/vscode/issues/90842  @isidorn
- [x] :runner: Investigate/assess JAWS support https://github.com/microsoft/vscode/issues/95225 @isidorn
- [ ] :runner: Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22April+2020%22) @isidorn

### Workbench
- [ ] :runner: Migrate to dynamic view containers https://github.com/microsoft/vscode/issues/94688 @sbatten @sandy081
- [x] Stabilize account management UI and flows https://github.com/microsoft/vscode/issues/95163 https://github.com/microsoft/vscode/issues/94766 @rmacfarlane @sandy081 @misolori
- [ ] :runner: Use encrypted keychain for account management https://github.com/microsoft/vscode/issues/95475 @rmacfarlane
- [x] :runner: Add support for GH accounts for setting sync https://github.com/microsoft/vscode/issues/95160 @tyriar @rmacfarlane @sandy081
- [ ] :runner: Settings sync: Explore support for extensions to participate in global state synchronization https://github.com/microsoft/vscode/issues/95209 @sandy081
- [ ] :muscle: Adopt GH account for issues reporter https://github.com/microsoft/vscode/issues/95165 @rmacfarlane
- [ ] :runner: Stabilize and document Custom Editor support https://github.com/microsoft/vscode/issues/77131 @mjbvz @bpasero @jrieken
- [ ] :runner: Support url query params for custom editor resources https://github.com/microsoft/vscode/issues/94037 @mjbvz
- [ ] :runner: Provide in core implementation for notebooks https://github.com/microsoft/vscode/issues/91987 @rebornix @jrieken @roblourens @weinand @connor4312
- [ ] :runner: Adopt `Open With...` https://github.com/microsoft/vscode/issues/94408 @rebornix **team**
- [x] :runner: Allow for better support of guiding users in the presence of deprecates settings https://github.com/microsoft/vscode/issues/91618 @roblourens

### Theme Support
- [ ] :runner: Supporting to customize the product icons https://github.com/microsoft/vscode/issues/79130 @aeschli @misolori
- [ ] :runner: Adopt and enrich the semantic coloring support for bundled VS Code color themes https://github.com/microsoft/vscode/issues/95346  @aeschli
- [x] :runner: Work with popular themes to adopt the semantic coloring support @aeschli

### Editor
- None.

### Terminal
- [x] Allow extensions to customize the environment of terminal processes https://github.com/microsoft/vscode/issues/46696 @tyriar
- [x] :runner: Link provider based terminal links preview https://github.com/microsoft/vscode/issues/95081 @tyriar
- [x] :runner: `xterm.js`: Prepare client/server separation for terminals https://github.com/xtermjs/xterm.js/issues/2749 @tyriar

### Languages
- [ ] :runner: Support richer labels in completion items https://github.com/microsoft/vscode/issues/39441 @octref @jrieken

#### LSP / LSIF
- [x] :runner: Adopt the latest semantic coloring API in the LSP spec @dbaeumer

#### TypeScript/JavaScript
- [ ] :runner: Collaborate with TS team on documentation of how to work with large TS projects https://github.com/microsoft/vscode/issues/92820 @mjbvz
- [ ] :runner: Improve presentation of TS hovers https://github.com/microsoft/vscode/issues/92787 @octref @mjbvz
- [x] :runner: Help TS team to assume ownership of semantic highlighting in TS tooling https://github.com/microsoft/vscode/issues/92789 @aeschli @mjbvz @alexdima

### Debug
- [x] :runner: Allow debug extensions to provide configurations to display in Select and Start Debugging https://github.com/microsoft/vscode/issues/95835 @isidorn @weinand
- [ ] :runner: Improve the single file debug experience https://github.com/microsoft/vscode/issues/92269 @weinand @isidorn
- [x] Adapt "auto attach" feature in js-debug https://github.com/microsoft/vscode/issues/88599 @connor4312 @weinand
- [ ] :runner: Adopt Select and Debug for js-debug https://github.com/microsoft/vscode-js-debug/issues/433 @connor4312
- [x] Provide basic support for capturing and viewing performance profiles in js-debug https://github.com/microsoft/vscode-js-debug/issues/388 @connor4312
- [x] :runner: Support necessary UI adaptations for profiling https://github.com/microsoft/vscode/issues/94812 @isidorn
- [x] :runner: :muscle: Investigate how to support StepInTarget in the UI https://github.com/microsoft/vscode/issues/90793 @weinand @isidorn

### SCM
- [x] Provide commands for git status https://github.com/microsoft/vscode/issues/93779 @joaomoreno
- [x] Git: Support that extensions can contribute repository sources to clone from. @joaomoreno
- [x] :runner: Git: Provide automatic HTTPS authentication with GitHub https://github.com/microsoft/vscode/issues/96241 @joaomoreno

### API
- [ ] :red_circle: April extension authors call @eamodio @fiveisprime
- [ ] Explore how to make it easier for extension authors to react to deprecated API https://github.com/microsoft/vscode/issues/94751 @eamodio
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22April+2020%22+label%3A%22api-proposal%22)

### Extension Contributions
- [ ] :runner: Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/2752 **team**
- [ ] :runner: Improvements to the GitHub PR extension https://github.com/microsoft/vscode-pull-request-github/issues/1619 @alexr00 @rmacfarlane
- [ ] :runner: Improvements to the GH Issues Notebook extension  https://github.com/microsoft/vscode-github-issue-notebooks/issues @jrieken
- [x] :muscle: Provide an extension contributing a flame chart presentation for performance profiles https://github.com/microsoft/vscode-js-debug/issues/434 @connor4312

### Engineering
- [ ] :runner: Explore node-free renderer processes https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556
- [ ] Investigate into an ARM product build for Windows https://github.com/microsoft/vscode/issues/33620 @joaomoreno
- [x] Adopt working copy service in Search editor https://github.com/microsoft/vscode/issues/89268 @jacksonkearl
- [x] :runner: Bring back automated issue classification https://github.com/microsoft/vscode/issues/95086 @jacksonkearl
- [x] :runner: Ongoing work on proposing and implementing new bots ([query](https://github.com/issues?q=is%3Aissue+archived%3Afalse+label%3Abot-proposal+milestone%3A%22April+2020%22)) @jacksonkearl
- [x] Contribute to electron's continuous Chromium update @deepak1556

### Documentation
- None.

-----
### Deferred Items
- Support for custom views with WebView contents https://github.com/microsoft/vscode/issues/83911 @mjbvz
- :runner: Support to preview refactoring changes for other refactorings than Rename https://github.com/microsoft/vscode/issues/77728 @jrieken @mjbvz
- Global undo/redo: support to undo an operation for a file that is not in memory https://github.com/microsoft/vscode/issues/92272 @alexdima
- Introduce a memory limit to saved undo-redo elements. https://github.com/microsoft/vscode/issues/93687 @alexdima
- Support to eventually activate an extension on startup @alexdima

**Comment by usernamehw** [comment]
I don't understand why you are putting this item to the Iteration Plan Item list

> Support for custom views with WebView contents #83911 mjbvz

If it's not planned for this iteration.

**Comment by 395053994** [comment]
I would like to ask which iteration can specifically improve the efficiency of java coding. Many functions of Red Hat's Java language service cannot keep up with the development steps of Eclipse.
Why doesn't Microsoft develop or maintain the Java language service engine extension by itself? I look forward to Microsoft's own development of a Java language service engine extension based on Eclipse JDT, which will be more friendly, convenient, and rapid for the overall VSCode Java update iteration.
Because of the Java development extensions provided by Microsoft so far, only the core Java language service engine extension is missing. This is very regrettable.

**Comment by war525** [comment]
Is it difficult to solve half a year's worth of proposals?

Word navigation in QuickOpen
https://github.com/microsoft/vscode/issues/84755

**Comment by ahmednrana** [comment]
> I would like to ask which iteration can specifically improve the efficiency of java coding. Many functions of Red Hat's Java language service cannot keep up with the development steps of Eclipse.
> Why doesn't Microsoft develop or maintain the Java language service engine extension by itself? I look forward to Microsoft's own development of a Java language service engine extension based on Eclipse JDT, which will be more friendly, convenient, and rapid for the overall VSCode Java update iteration.
> Because of the Java development extensions provided by Microsoft so far, only the core Java language service engine extension is missing. This is very regrettable.

much needed

**Comment by jedwards1211** [comment]
Could you implement a separate extension host for type commands this iteration? 
 The keyboard lag is awful at times.
https://github.com/microsoft/vscode/issues/75627

Vim users feel like second class citizens in VSCode right now.

**Comment by Rcubes** [comment]
are you guys planning to fix export from jupyter to python script during this iteration?

**Comment by regs01** [comment]
> Below the OPEN EDITORS section header does not have a background color and the VSCODE and OUTLINE headers have an upper border.

This isn't good way of UI.  It's visually messing up sections. It's when designers taking over UI and putting style above productivity. The good way of UI is when each section on screen that is not related to each other should have visual contrast separation. That's why nobody liked Office 2013.

#93764 proposal received just one like, yet has been implemented.
