### ISSUE TITLE
Polish terminal link provider-based links and remove link matcher support

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#96266]
Follow up from https://github.com/microsoft/vscode/issues/95081

- Bugs
  - [x] Terminal link detection issues https://github.com/microsoft/vscode/issues/21125, this can probably be closed off and any lingering issues can be handled individually (or use the [link provider API](https://github.com/microsoft/vscode/issues/91290) and live in an extension)
  - [ ] Terminal "word" link provider does not support wrapping https://github.com/microsoft/vscode/issues/95077
  - [x] Exception after resizing a terminal on Windows https://github.com/microsoft/vscode/issues/95575
- Accessibility
  - [ ] Keyboard navigation https://github.com/microsoft/vscode/issues/95570
- Polish
  - [x] Link hover sticks around sometimes https://github.com/microsoft/vscode/issues/95997
  - [x] Remove old link system https://github.com/microsoft/vscode/pull/98182
- API
  - [ ] Link provider extension API https://github.com/microsoft/vscode/issues/91290

[integrated-terminal links query](https://github.com/microsoft/vscode/labels/integrated-terminal-links)

**Comment by Tyriar** [comment]
The default has been switched and old code removed, individual follow up items that are not checked above have their own tracking issues.
