### ISSUE TITLE
Notebook debt for May

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#96745]
A brief summary of items we didn't finish in last iteration and issues reported during endgame

- [x] Drag & Drop #96308 
- [x] API refactoring #95854
- [x] TextBuffer/TextModel (blocker of https://github.com/microsoft/vscode/pull/96156)
  * The idea is every `CellTextModel` will manage its content in `ITextBuffer`, which be used as the backing store for `TextModel` thus every edit in Monaco Editor will be updated in the text buffer immediately. Also we will have a set of TextModel like API to use even when the cell is not attached to an editor yet.
- [x] Renderers
  - [x] `acquireVSCodeApi(rendererId)` in Notebook Webview #95361
  - [x] development mode API #95926
  - [x] polish hot reloading #95908, #95990 
- [ ] Working Copy (revert, hot exit)
  - [ ] revert
  - [x] hot exit
  - [x] 🔧 register working copy in `NotebookTextModel` other than `NotebookViewModel` to avoid duplicated registration #96402
- [x] Language selector
- [x] Undo/redo of notebook only workspace edits should be one operation
- [ ] Composite Editor
  - [x] add `isCompositeEditor` context key
  - [ ] add a way to see all editors/uris of a composite editor
- [x] revisit `vscode-notebook`-scheme for cell, maybe `vscode-notebook-cell`?

**Comment by rebornix** [comment]
Please help add items which are not tracked by issues and we can have a good discussion about them tomorrow.
