### ISSUE TITLE
Iteration Plan for May 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#97432]
This plan captures our work in **May**. We will ship in **early June**. This is a ~~4-week~~ 5-week iteration. (We extended the iteration by one week on 05/18/2020.)

## Endgame
- **June 1st, 2020**: Endgame begins
- **June 5th, 2020**: Endgame done

The endgame details for this iteration are tracked in https://github.com/microsoft/vscode/issues/98811.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Accessibility
- [x] Keyboard shortcuts to set start and end selection https://github.com/microsoft/vscode/issues/95894 @isidorn
- [x] Investigate into contentEditable for the hidden accessibility 'textArea' https://github.com/microsoft/vscode/issues/97154 @isidorn
- [x] Accessibility issues, see [query](https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Aaccessibility+milestone%3A%22May+2020%22) @isidorn
- [x] Community call https://github.com/microsoft/vscode/issues/97519 @sana-ajani @isidorn

### Workbench
- [ ] :runner: Use encrypted keychain for account management https://github.com/microsoft/vscode/issues/95475 @rmacfarlane
- [x] Polish auth provider UX: soft-login, managing trusted extensions https://github.com/microsoft/vscode/issues/96367  @rmacfarlane
- [x] Stablize and polish workbench drag n' drop [query](https://github.com/microsoft/vscode/issues?q=is%3Aissue+assignee%3Asbatten+milestone%3A%22May+2020%22+label%3Aworkbench-views) @sbatten
- [ ] :runner: :muscle: Enable rich hovers across the workbench (custom trees, terminal) https://github.com/microsoft/vscode/issues/97496 @tyriar @alexdima
- [x] Finalize Custom Editor support https://github.com/microsoft/vscode/issues/77131 @mjbvz
- [x] Dynamically update trusted domains based on repositort remote and GH id https://github.com/microsoft/vscode/issues/97532 @jacksonkearl
- [x] Improve the settings sync views https://github.com/microsoft/vscode/issues/93960 @sandy081
- [ ] :runner: Provide in core implementation for notebooks https://github.com/microsoft/vscode/issues/91987 @rebornix @jrieken @roblourens @weinand @connor4312
- [x] Allow to pin tabs https://github.com/microsoft/vscode/issues/98558 @bpasero
- [x] Support undoing textual edits in text buffers that were disposed https://github.com/microsoft/vscode/issues/92272 @alexdima
- [x] Support undo/redo in Notebook as in a single document https://github.com/microsoft/vscode/issues/92811 @alexdima
- [ ] :runner: Supporting to customize the product icons https://github.com/microsoft/vscode/issues/92791 @aeschli @misolori
- [ ] :runner: Improve first run experience (open editors, npm scripts, ...) https://github.com/microsoft/vscode/issues/98614 @misolori
- [ ] :runner: Provide object editing support in the settings editor https://github.com/microsoft/vscode/issues/93598 @9at8

### Editor
- [x] Improve line terminator handling to support different programming language rules https://github.com/microsoft/vscode/issues/96142 @alexdima

### Languages
- [x] Investigate resolving and inserting additional text edits asynchronously https://github.com/microsoft/vscode/issues/96779 @jrieken
- [x] Explore API to expose standard token types https://github.com/microsoft/vscode/issues/91555 @jrieken

#### LSP / LSIF
- [x] Explore batched LSP requests https://github.com/microsoft/language-server-protocol/issues/988 @dbaeumer

#### TypeScript/JavaScript
- [x] Adopt TS 3.9.x to ship with VS Code https://github.com/microsoft/vscode/issues/97959 @mjbvz

### Debug
- [x] Polish the support for dynamic debug configurations https://github.com/microsoft/vscode/issues/96293, https://github.com/microsoft/vscode/issues/95863, https://github.com/microsoft/vscode/issues/95836 @isidorn @weinand
- [ ] :runner: Improve the single file debug experience https://github.com/microsoft/vscode/issues/92269 @weinand @isidorn
- [ ] :runner: Explore how to make the debug terminal easier to discover https://github.com/microsoft/vscode/issues/98054 @connor4312
- [x] Ensure correct error output in the js-debug terminal @connor4312 https://github.com/microsoft/vscode-js-debug/issues/462 @connor4312
- [x] Ensure all our debug adapters deal correctly with error-telemetry https://github.com/microsoft/vscode-js-debug/issues/464 https://github.com/microsoft/vscode/issues/97628 @connor4312 @isidorn
- [x] Verify liveshare works with js-debug https://github.com/microsoft/vscode-js-debug/issues/463 @connor4312
- [x] Support `StepInTarget` in the UI https://github.com/microsoft/vscode/issues/90793 @isidorn @weinand

#### DAP
- [x] Support Stepping Granularities https://github.com/microsoft/debug-adapter-protocol/issues/110 @weinand
- [x] Support memory reference breakpoints https://github.com/microsoft/debug-adapter-protocol/issues/102 @weinand

### SCM
- [ ] :runner: Make SCM view(s) moveable https://github.com/microsoft/vscode/issues/90461 @sbatten @joaomoreno

### API
- API finalization: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2020%22+label%3A%22api-finalization%22)
- API proposals: [query](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+milestone%3A%22May+2020%22+label%3A%22api-proposal%22)

### Web
- [x] Indicate when a breakpoint is hit in the browser tab @bpasero @isidorn
- [x] Improve support for embedder-defined layouts https://github.com/microsoft/vscode/issues/96939 @eamodio
- [x] Enrich `yarn web` to include GH support https://github.com/microsoft/vscode/issues/97708 @bpasero @eamodio
- [x] Investigate running the 'CSS Language Features extension' in `yarn web` https://github.com/microsoft/vscode/issues/97701 @aeschli @dbaeumer

### Extensions
- [x] Support to eventually activate an extension on startup https://github.com/microsoft/vscode/issues/98083 @alexdima
- [x] Enhance hovers by enabling rendering of some HTML https://github.com/microsoft/vscode/issues/40607 @alexr00
- [x] Guide users of the [Auto Rename Tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag) extension to the new `editor.renameOnType` setting https://github.com/microsoft/vscode/issues/97700 @aeschli

### Extension Contributions
- [x] Improvements to the Remote extensions https://github.com/microsoft/vscode-remote-release/issues/2973 **team**
- [x] Improvements to the GitHub PR and Issues extension https://github.com/microsoft/vscode-pull-request-github/issues/1788 @alexr00
- [x] Implement a hex editor using the custom editor API https://github.com/microsoft/vscode/issues/98105 @lramos15

### Install
- [x] Explore `msix` installer for VS Code on Windows https://github.com/microsoft/vscode/issues/61793 @lszomoru @joaomoreno @sbatten

### Engineering
- [ ] :runner: Explore node-free renderer processes https://github.com/microsoft/vscode/issues/92164 @bpasero @deepak1556
- [x] Review our handling of URI across the workbench (critical for notebook support) https://github.com/microsoft/vscode/issues/97881 @jrieken
- [x] Report crash reports that occur during builds with new `--crash-reporter-directory` CLI option @bpasero
- [x] Adopt `eslint` for `vscode-extension-samples` https://github.com/microsoft/vscode/issues/97476 @mjbvz
- [x] Investigate into an ARM product build for Windows https://github.com/microsoft/vscode/issues/33620 @joaomoreno

### Bots
- [X] Support roll-out of automated issues classification https://github.com/microsoft/vscode/issues/97533 @jacksonkearl
- [X] Increase discoverability of existing bot actions via a browser extension https://github.com/microsoft/vscode/issues/97534 @jacksonkearl
- [X] Provide bot action to notify issue followers when fixes/features are released in Insiders https://github.com/microsoft/vscode/issues/97536 @jacksonkearl

### Electron
- [ ] :runner: Investigate start-up performance issues when using electron 8 https://github.com/microsoft/vscode/issues/97638 @deepak1556 @jrieken
- [ ] electron bug fixes @deepak1556
   - [x] Split the helper entitlements on macOS https://github.com/microsoft/vscode/pull/94728
   - [ ] :hand: Adopt new version of gulp-atom-electron https://github.com/joaomoreno/gulp-atom-electron/pull/59
   - [ ] Custom titlebar on windows overflows when moving from hiDPI displays https://github.com/microsoft/vscode/issues/85592
   - [x] Update MS electron crash-reporter patch to accommodate refactor from OSS electron https://github.com/electron/electron/pull/23265
   - [x] Dialog message not read out by screen reader https://github.com/electron/electron/issues/14234
- [ ] :runner: :muscle: OOPIF support with custom protocols for desktop https://github.com/microsoft/vscode/issues/83188 @mjbvz @deepak1556
- [ ] :hand: Enable `LayoutNG` by backporting chromium patch https://github.com/microsoft/vscode/issues/88873 @deepak1556

### Documentation
- None.

-----
### Deferred Items from previous iteration(s)
- Support to preview refactoring changes for other refactorings than Rename https://github.com/microsoft/vscode/issues/77728 @jrieken @mjbvz
- Explore support for extensions to contribute a welcome page and release notes https://github.com/microsoft/vscode/issues/83451 @sandy081
- Investigate into the performance of the [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) extension @alexdima
- Provide an extension to find VS Code API references in the samples and popular extensions https://github.com/microsoft/vscode/issues/98077 @dbaeumer
- Improve support for `git` commands https://github.com/microsoft/vscode/issues/98047 @eamodio @joaomoreno
- :muscle: Adopt GH account for issues reporter https://github.com/microsoft/vscode/issues/95165 @rmacfarlane
- :muscle: Kick-off for custom views with WebView contents https://github.com/microsoft/vscode/issues/83911 @mjbvz
- :muscle: Investigate support of `webview` debugging https://github.com/microsoft/vscode/issues/96626 @connor4312 @weinand
- :muscle: Investigate SDK deprecations for the Azure Account extensions https://github.com/microsoft/vscode-azure-account/issues/140 @rmacfarlane
- :muscle: Provide guidelines for extension authors how to adopt the GH auth provider @rmacfarlane

**Comment by CoenraadS** [comment]
Hello

I see investigating my extension "https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer" is on the list.

I actually have 2 versions, the second one is this one: https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer-2

The first one is unmaintained. Feel free to contact me, as my code is very confusing and has no tests... 🐬

**Comment by sanket-bhalerao** [comment]
Microsoft code OSS?
for the insiders, I could not download/install the update. so I downloaded the latest insiders build and tried to install and I get this message
![image](https://user-images.githubusercontent.com/9264813/82300111-05582280-99d4-11ea-80ad-bcf6dee18ff5.png)
I thought maybe last time downloaded a 32-bit installer and installed, so I uninstalled both code oss and vs code insiders. tried the latest code insiders install (which is now Microsoft code oss?) made sure I am downloading 64bit version twice, and after installation, there are no old extensions and not even the setting sync option.
tried to download and install the vscode insider and got the 
![image](https://user-images.githubusercontent.com/9264813/82300492-8d3e2c80-99d4-11ea-96cd-a91d08733972.png)
message again.
not sure what is happening.

**Comment by UnsnappedKhan8** [comment]
My team?

**Comment by UnsnappedKhan8** [comment]
@UnsnappedKhan8

**Comment by Poopooracoocoo** [comment]
uh what happened to the msix installer
